Repository opensearch-project/OpenSearch, pull requests merged in 2021-11, with the labels that each got.

#1456 Make TranslogDeletionPolicy abstract for extension
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/translog/DefaultTranslogDeletionPolicy.java
  server/src/main/java/org/opensearch/index/translog/TranslogDeletionPolicy.java
  server/src/main/java/org/opensearch/index/translog/TranslogReader.java
  server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogTests.java
  test/framework/src/main/java/org/opensearch/index/translog/TranslogDeletionPolicies.java
Labels: enhancement, v1.2.0

#1471 [Backport 1.x] Remove deprecated settings and logic for translog pruning by retentio…
  server/src/internalClusterTest/java/org/opensearch/indices/settings/UpdateSettingsIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/TranslogDeletionPolicy.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
Labels: backport

#1478 [Backport 1.x] Make TranslogDeletionPolicy abstract for extension (#1456)
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/translog/DefaultTranslogDeletionPolicy.java
  server/src/main/java/org/opensearch/index/translog/TranslogDeletionPolicy.java
  server/src/main/java/org/opensearch/index/translog/TranslogReader.java
  server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogTests.java
  test/framework/src/main/java/org/opensearch/index/translog/TranslogDeletionPolicies.java
Labels: backport

#1370 Removed CheckStyle code formatting plugin
  buildSrc/build.gradle
  buildSrc/src/integTest/java/org/opensearch/gradle/ExportOpenSearchBuildResourcesTaskIT.java
  buildSrc/src/main/groovy/org/opensearch/gradle/precommit/PrecommitTasks.groovy
  buildSrc/src/main/java/org/opensearch/gradle/checkstyle/SnippetLengthCheck.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/CheckstylePrecommitPlugin.java
  buildSrc/src/main/resources/checkstyle.xml
  buildSrc/src/main/resources/checkstyle_suppressions.xml
  buildSrc/src/test/java/org/opensearch/gradle/checkstyle/SnipptLengthCheckTests.java
  buildSrc/src/testKit/opensearch-build-resources/build.gradle
  buildSrc/version.properties
  gradle/formatting.gradle
Labels: Build Libraries & Interfaces, v2.0.0, v1.2.0

#1403 Remove codeQL warning about implicit narrowing conversion in compound assignment
  libs/nio/src/test/java/org/opensearch/nio/InboundChannelBufferTests.java
  plugins/examples/rescore/src/main/java/org/opensearch/example/rescore/ExampleRescoreBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/BestBucketsDeferringCollector.java
  server/src/test/java/org/opensearch/action/search/SearchPhaseControllerTests.java
  server/src/test/java/org/opensearch/index/shard/StoreRecoveryTests.java
  server/src/test/java/org/opensearch/index/snapshots/blobstore/FileInfoTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/InternalBinaryRangeTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/SumAggregatorTests.java
  test/framework/src/main/java/org/opensearch/common/bytes/AbstractBytesReferenceTestCase.java
Labels: enhancement, v2.0.0, v1.2.0

#1495 [Backport-1.x] Upgrading dependencies (#1491)
  buildSrc/build.gradle
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/jackson-databind-2.12.5.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-LICENSE.txt
  plugins/repository-hdfs/licenses/jackson-databind-NOTICE.txt
  plugins/repository-hdfs/licenses/log4j-1.2-api-2.11.1.jar.sha1
  plugins/repository-hdfs/licenses/log4j-LICENSE.txt
  plugins/repository-hdfs/licenses/log4j-NOTICE.txt
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport

#1498 [Backport 1.x]Change JNA to upstream version from elastic JNA build
  buildSrc/build.gradle
  buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
  server/build.gradle
  server/licenses/jna-5.5.0.jar.sha1
Labels: backport, v1.2.0

#1503 Add staged version 1.1.1
  .ci/bwcVersions
  buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
Labels: non-issue, v1.1.1

#1508 [BWC] Diable BWC tests until branch versions are synced
  build.gradle
Labels: v2.0.0, non-issue, backwards-compatibility

#1505 [1.2] Add staged version 1.1.1 for bwc testing
  .ci/bwcVersions
  buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
  server/src/main/java/org/opensearch/Version.java
Labels: CI, non-issue, backwards-compatibility, v1.2.0

#1506 [main] Add staged version 1.1.1 for bwc
  .ci/bwcVersions
  buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
  server/src/main/java/org/opensearch/Version.java
Labels: CI, v2.0.0, non-issue, backwards-compatibility

#1509 [1x] Add staged version 1.1.1 for bwc testing
  .ci/bwcVersions
  buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
  server/src/main/java/org/opensearch/Version.java
Labels: CI, non-issue, backwards-compatibility, v1.3.0

#1510 [main] Add staged version 1.3.0 for bwc
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: CI, v2.0.0, non-issue, backwards-compatibility

#1511 [bwc] reenable bwc testing after syncing staged branches
  build.gradle
Labels: CI, v2.0.0, non-issue, backwards-compatibility

#1524 Integration test that checks for settings upgrade (#1482)
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartSettingsUpgradeIT.java
Labels: :test, backport

#1521 [repository-azure] Update to the latest Azure Storage SDK v12, remove privileged runnable wrapper in favor of access helper
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-core-1.20.0.jar.sha1
  plugins/repository-azure/licenses/azure-core-1.22.0.jar.sha1
  plugins/repository-azure/licenses/azure-core-http-netty-1.11.0.jar.sha1
  plugins/repository-azure/licenses/azure-core-http-netty-1.11.2.jar.sha1
  plugins/repository-azure/licenses/azure-storage-blob-12.13.0.jar.sha1
  plugins/repository-azure/licenses/azure-storage-blob-12.14.1.jar.sha1
  plugins/repository-azure/licenses/azure-storage-common-12.12.0.jar.sha1
  plugins/repository-azure/licenses/azure-storage-common-12.14.0.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-1.0.12.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-1.0.13.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.0.12.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.0.13.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.0.12.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.0.13.jar.sha1
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageService.java
Labels: backport pending, Plugins

#1538 [Backport] [1.x] [repository-azure] Update to the latest Azure Storage SDK v12, remove privileged runnable wrapper in favor of access helper (#1521)
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-core-1.20.0.jar.sha1
  plugins/repository-azure/licenses/azure-core-1.22.0.jar.sha1
  plugins/repository-azure/licenses/azure-core-http-netty-1.11.0.jar.sha1
  plugins/repository-azure/licenses/azure-core-http-netty-1.11.2.jar.sha1
  plugins/repository-azure/licenses/azure-storage-blob-12.13.0.jar.sha1
  plugins/repository-azure/licenses/azure-storage-blob-12.14.1.jar.sha1
  plugins/repository-azure/licenses/azure-storage-common-12.12.0.jar.sha1
  plugins/repository-azure/licenses/azure-storage-common-12.14.0.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-1.0.12.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-1.0.13.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.0.12.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.0.13.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.0.12.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.0.13.jar.sha1
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageService.java
Labels: backport

#1546 [Backport] Upgrading gson to 2.8.9 (#1541)
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/gson-2.7.jar.sha1
  plugins/repository-gcs/licenses/gson-2.8.9.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/gson-2.8.9.jar.sha1
  plugins/repository-hdfs/licenses/gson-LICENSE.txt
  plugins/repository-hdfs/licenses/gson-NOTICE.txt
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport, v1.2.0

#1571 Upgrade dependency
  buildSrc/build.gradle
  distribution/tools/keystore-cli/build.gradle
  distribution/tools/plugin-cli/build.gradle
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/failureaccess-1.0.1.jar.sha1
  plugins/repository-gcs/licenses/failureaccess-LICENSE.txt
  plugins/repository-gcs/licenses/failureaccess-NOTICE.txt
  plugins/repository-gcs/licenses/guava-26.0-jre.jar.sha1
  plugins/repository-gcs/licenses/guava-30.1.1-jre.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/commons-io-2.4.jar.sha1
  plugins/repository-hdfs/licenses/commons-io-2.7.jar.sha1
Labels: >upgrade, v1.3.0

#1545 [Backport-1.x] Upgrading gson to 2.8.9 (#1541)
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/gson-2.7.jar.sha1
  plugins/repository-gcs/licenses/gson-2.8.9.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/gson-2.8.9.jar.sha1
  plugins/repository-hdfs/licenses/gson-LICENSE.txt
  plugins/repository-hdfs/licenses/gson-NOTICE.txt
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport

#1604 Enable RestHighLevel-Client to set parameter require_alias for bulk index and reindex requests
  client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
  client/rest-high-level/src/test/java/org/opensearch/client/CrudIT.java
  client/rest-high-level/src/test/java/org/opensearch/client/ReindexIT.java
Labels: backport

#1594 [Backport-1.x] Upgrade dependency (#1571)
  buildSrc/build.gradle
  distribution/tools/keystore-cli/build.gradle
  distribution/tools/plugin-cli/build.gradle
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/failureaccess-1.0.1.jar.sha1
  plugins/repository-gcs/licenses/failureaccess-LICENSE.txt
  plugins/repository-gcs/licenses/failureaccess-NOTICE.txt
  plugins/repository-gcs/licenses/guava-26.0-jre.jar.sha1
  plugins/repository-gcs/licenses/guava-30.1.1-jre.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/commons-io-2.4.jar.sha1
  plugins/repository-hdfs/licenses/commons-io-2.7.jar.sha1
Labels: backport, >upgrade, v1.3.0

#1624 Support Gradle 7. Fixing publishing to Maven Local for plugins
  buildSrc/build.gradle
Labels: backport, backport 1.x

#1621 [Backport-1.x] Upgrading commons-codec in hdfs-fixture and cleaning up dependencies …
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/hadoop-annotations-3.3.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-auth-3.3.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-3.3.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-api-3.3.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-runtime-3.3.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-common-3.3.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-client-3.3.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-shaded-guava-1.1.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-shaded-protobuf_3_7-1.1.1.jar.sha1
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport
