Repository opensearch-project/OpenSearch, pull requests merged in 2021-12, with the labels that each got.

#1639 Remove Deprecated SimpleFS
  plugins/store-smb/src/internalClusterTest/java/org/opensearch/index/store/SmbSimpleFsTests.java
  plugins/store-smb/src/main/java/org/opensearch/index/store/smbsimplefs/SmbSimpleFsDirectoryFactory.java
  plugins/store-smb/src/main/java/org/opensearch/plugin/store/smb/SMBStorePlugin.java
  plugins/store-smb/src/test/java/org/opensearch/index/store/SmbSimpleFSDirectoryTests.java
  server/src/main/java/org/opensearch/index/store/FsDirectoryFactory.java
  server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java
Labels: v2.0.0, durability

#1645 Renaming Slave terminology to Replica in 1.x branch (backporting)
  modules/mapper-extras/src/test/resources/org/opensearch/index/mapper/metricbeat-6.0.template.json
Labels: enhancement, backport, v1.3.0

#1662 Refactor LegacyESVersion tests from Version tests
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/LegacyESVersionTests.java
  server/src/test/java/org/opensearch/VersionTests.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
  test/framework/src/test/java/org/opensearch/test/VersionUtilsTests.java
Labels: v2.0.0, non-issue, backport pending

#1664 Move Gradle wrapper and precommit checks into OpenSearch repo.
  .github/workflows/precommit.yml
  .github/workflows/wrapper.yml
Labels: backport pending, backport 1.x

#1678 Move Gradle wrapper and precommit checks into OpenSearch repo. (#1664)
  .github/workflows/precommit.yml
  .github/workflows/wrapper.yml
Labels: CI, backport, v1.3.0

#1681 Remove LegacyESVersion.V_6_1_x constants
  modules/percolator/src/main/java/org/opensearch/percolator/PercolateQueryBuilder.java
  modules/percolator/src/main/java/org/opensearch/percolator/PercolatorFieldMapper.java
  modules/percolator/src/main/java/org/opensearch/percolator/QueryAnalyzer.java
  modules/percolator/src/test/java/org/opensearch/percolator/CandidateQueryTests.java
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartSettingsUpgradeIT.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/open/OpenIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/open/OpenIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/rollover/MaxSizeCondition.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeAction.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/main/java/org/opensearch/action/search/SearchResponse.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ResizeAllocationDecider.java
  server/src/main/java/org/opensearch/common/lucene/search/Queries.java
  server/src/main/java/org/opensearch/common/settings/Settings.java
  server/src/main/java/org/opensearch/common/unit/Fuzziness.java
  server/src/main/java/org/opensearch/discovery/DiscoveryStats.java
  server/src/main/java/org/opensearch/index/engine/Segment.java
  server/src/main/java/org/opensearch/index/mapper/FieldNamesFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/SeqNoFieldMapper.java
  server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MultiMatchQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/QueryStringQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SimpleQueryStringBuilder.java
  server/src/main/java/org/opensearch/index/reindex/AbstractBulkByScrollRequest.java
  server/src/main/java/org/opensearch/index/shard/DocsStats.java
  server/src/main/java/org/opensearch/monitor/os/OsStats.java
  server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/GeoDistanceSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java
  server/src/main/java/org/opensearch/search/suggest/completion/CompletionSuggestion.java
  server/src/main/java/org/opensearch/search/suggest/completion/CompletionSuggestionBuilder.java
  server/src/test/java/org/opensearch/common/lucene/search/QueriesTests.java
  server/src/test/java/org/opensearch/common/settings/SettingsTests.java
  server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/RangeQueryBuilderTests.java
  server/src/test/java/org/opensearch/transport/RemoteClusterConnectionTests.java
  test/framework/src/test/java/org/opensearch/test/rest/yaml/section/SkipSectionTests.java
Labels: v2.0.0, non-issue

#1692 Fix unit test testFailsHealthOnHungIOBeyondHealthyTimeout() by incresing the max waiting time before assertion
  server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java
Labels: backport, backport 1.x

#1701 Add version 1.2.1.
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: pending backport, backport 1.x

#1702 [Backport][1.x] Add version 1.2.1
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: non-issue, backport, v1.2.1

#1698 Upgrade to log4j 2.15.0
  buildSrc/version.properties
  plugins/discovery-azure-classic/build.gradle
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.11.2.jar.sha1
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/discovery-ec2/build.gradle
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.11.2.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/discovery-gce/build.gradle
  plugins/discovery-gce/licenses/log4j-1.2-api-2.11.2.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/log4j-1.2-api-2.11.2.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.11.2.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.15.0.jar.sha1
  plugins/repository-s3/build.gradle
  plugins/repository-s3/licenses/log4j-1.2-api-2.11.2.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.15.0.jar.sha1
  server/build.gradle
  server/licenses/log4j-api-2.11.2.jar.sha1
  server/licenses/log4j-api-2.15.0.jar.sha1
  server/licenses/log4j-core-2.11.2.jar.sha1
  server/licenses/log4j-core-2.15.0.jar.sha1
Labels: Severity-Critical, pending backport, CVE, backport 1.x, v1.2.1

#1721 Upgrade to log4j 2.16.0
  buildSrc/version.properties
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.15.0.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.16.0.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.16.0.jar.sha1
  server/licenses/log4j-api-2.15.0.jar.sha1
  server/licenses/log4j-api-2.16.0.jar.sha1
  server/licenses/log4j-core-2.15.0.jar.sha1
  server/licenses/log4j-core-2.16.0.jar.sha1
Labels: pending backport, backport 1.x

#1728 Increment version to 1.2.2 and backport log4j upgrade to 2.16.
  .ci/bwcVersions
  .github/workflows/dco.yml
  buildSrc/version.properties
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.15.0.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.16.0.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.15.0.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.16.0.jar.sha1
  server/licenses/log4j-api-2.15.0.jar.sha1
  server/licenses/log4j-api-2.16.0.jar.sha1
  server/licenses/log4j-core-2.15.0.jar.sha1
  server/licenses/log4j-core-2.16.0.jar.sha1
  server/src/main/java/org/opensearch/Version.java
Labels: pending backport

#1731 Adding 1.2.2
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: backport 1.x, v1.2.2

#1730 Adding release notes for 1.2.2
  release-notes/opensearch.release-notes-1.2.2.md
Labels: release, v1.2.2

#1736 Adding 1.2.2 (#1731)
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: backport, v1.2.2

#1741 [Remove] Analyzer Deprecations
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CJKBigramFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisPlugin.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonGramsTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/EdgeNGramTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/FingerprintTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/LegacyDelimitedPayloadTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/MultiplexerTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/NGramTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/NGramTokenizerFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/StandardHtmlStripAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterGraphTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/CommonAnalysisPluginTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/HtmlStripCharFilterFactoryTests.java
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/20_analyzers.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/40_token_filters.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/indices.analyze/10_analyze.yml
  plugins/analysis-icu/src/main/java/org/opensearch/index/analysis/IcuNormalizerTokenFilterFactory.java
  plugins/analysis-icu/src/yamlRestTest/resources/rest-api-spec/test/analysis_icu/10_basic.yml
  plugins/analysis-phonetic/src/main/java/org/opensearch/index/analysis/PhoneticTokenFilterFactory.java
  server/src/main/java/org/opensearch/index/analysis/PreConfiguredTokenFilter.java
Labels: v2.0.0, non-issue

#1742 [Remove] DynamicTemplate deprecations
  server/src/main/java/org/opensearch/index/mapper/DynamicTemplate.java
  server/src/main/java/org/opensearch/index/mapper/RootObjectMapper.java
  server/src/test/java/org/opensearch/index/mapper/DynamicTemplateTests.java
Labels: v2.0.0, non-issue

#1740 [plugin] repository-azure is not working properly hangs on basic operations
  plugins/repository-azure/build.gradle
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureBlobStore.java
  test/fixtures/azure-fixture/src/main/java/fixture/azure/AzureHttpHandler.java
Labels: bug, Plugins, v1.2.0

#1749 [plugin] repository-azure is not working properly hangs on basic oper…
  plugins/repository-azure/build.gradle
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureBlobStore.java
  test/fixtures/azure-fixture/src/main/java/fixture/azure/AzureHttpHandler.java
Labels: bug, Severity-Blocker, v2.0.0, pending backport, Plugins

#1751 [Remove] Remaining Flavor Serialization
  server/src/main/java/org/opensearch/Build.java
Labels: v2.0.0, non-issue, backwards-compatibility

#1752 [Remove] various builder and mapping deprecations
  server/src/internalClusterTest/java/org/opensearch/indices/mapping/LegacyUpdateMappingIntegrationIT.java
  server/src/main/java/org/opensearch/common/geo/builders/ShapeBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchPhraseQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/TypeQueryBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
  server/src/test/java/org/opensearch/LegacyESVersionTests.java
  server/src/test/java/org/opensearch/common/geo/GeoWKTShapeParserTests.java
  server/src/test/java/org/opensearch/index/mapper/LegacyDynamicMappingTests.java
  server/src/test/java/org/opensearch/index/mapper/LegacyMapperServiceTests.java
  server/src/test/java/org/opensearch/index/similarity/LegacySimilarityTests.java
Labels: v2.0.0, non-issue

#1360 Bridging the gap in network overhead measurement in the profiler
  server/src/internalClusterTest/java/org/opensearch/search/profile/ProfilerSingleNodeNetworkTest.java
  server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
  server/src/main/java/org/opensearch/action/search/SearchExecutionStatsCollector.java
  server/src/main/java/org/opensearch/action/search/SearchQueryThenFetchAsyncAction.java
  server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
  server/src/main/java/org/opensearch/search/profile/NetworkTime.java
  server/src/main/java/org/opensearch/search/profile/ProfileShardResult.java
  server/src/main/java/org/opensearch/search/profile/SearchProfileShardResults.java
  server/src/main/java/org/opensearch/search/query/QueryPhase.java
  server/src/main/java/org/opensearch/search/query/QuerySearchResult.java
  server/src/main/java/org/opensearch/transport/RequestHandlerRegistry.java
  server/src/main/java/org/opensearch/transport/TcpTransportChannel.java
  server/src/test/java/org/opensearch/search/profile/SearchProfileShardResultsTests.java
Labels: enhancement, v2.0.0, documentation pending, distributed framework

#1691 Remove LegacyESVersion.V_6_3_x constants
  server/src/main/java/org/opensearch/Build.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/action/admin/cluster/reroute/ClusterRerouteResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/ClusterStateResponse.java
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/cluster/action/shard/ShardStateAction.java
  server/src/main/java/org/opensearch/index/flush/FlushStats.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/index/translog/TranslogStats.java
  server/src/main/java/org/opensearch/indices/flush/SyncedFlushService.java
  server/src/main/java/org/opensearch/persistent/PersistentTasksCustomMetadata.java
  server/src/main/java/org/opensearch/persistent/StartPersistentTaskAction.java
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
  server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
  server/src/main/java/org/opensearch/search/slice/SliceBuilder.java
  server/src/main/java/org/opensearch/transport/Header.java
  server/src/main/java/org/opensearch/transport/OutboundMessage.java
  server/src/main/java/org/opensearch/transport/TransportLogger.java
  server/src/test/java/org/opensearch/BuildTests.java
  server/src/test/java/org/opensearch/LegacyESVersionTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequestTests.java
  server/src/test/java/org/opensearch/search/slice/SliceBuilderTests.java
  test/framework/src/test/java/org/opensearch/test/rest/yaml/section/SetupSectionTests.java
Labels: v2.0.0, non-issue

#1766 [Backport 1.x] Updating .gitattributes for additional file types
  .gitattributes
Labels: backport, backport 1.x

#1718 Fixing allocation filters to persist existing state on settings update
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeFilters.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeFiltersTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java
Labels: pending backport, backport 1.x

#1771 Update to log4j 2.17.0
  buildSrc/version.properties
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.17.0.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.17.0.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.17.0.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.17.0.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.16.0.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.17.0.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.16.0.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.17.0.jar.sha1
  server/licenses/log4j-api-2.16.0.jar.sha1
  server/licenses/log4j-api-2.17.0.jar.sha1
  server/licenses/log4j-core-2.16.0.jar.sha1
  server/licenses/log4j-core-2.17.0.jar.sha1
Labels: pending backport, backport 1.x, v1.2.3

#1787 Remove LegacyESVersion.V_6_4_x constants
  modules/lang-painless/src/main/java/org/opensearch/painless/action/PainlessExecuteAction.java
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/action/admin/cluster/reroute/ClusterRerouteResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/settings/ClusterUpdateSettingsResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/storedscripts/GetStoredScriptResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/Alias.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/IndicesAliasesRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/get/GetAliasesRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/close/CloseIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/open/OpenIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/readonly/AddIndexBlockResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/rollover/RolloverResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/settings/get/GetSettingsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/validate/query/QueryExplanation.java
  server/src/main/java/org/opensearch/action/resync/ResyncReplicationRequest.java
  server/src/main/java/org/opensearch/action/support/master/ShardsAcknowledgedResponse.java
  server/src/main/java/org/opensearch/cluster/metadata/AliasMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/index/query/AbstractGeometryQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/InnerHitBuilder.java
  server/src/main/java/org/opensearch/index/reindex/RemoteInfo.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/InternalBinaryRange.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/InternalRange.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/main/java/org/opensearch/search/fetch/subphase/FieldAndFormat.java
  server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
  server/src/main/java/org/opensearch/search/slice/SliceBuilder.java
  server/src/main/java/org/opensearch/search/sort/GeoDistanceSortBuilder.java
  server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
  server/src/test/java/org/opensearch/action/support/master/ShardsAcknowledgedResponseTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/ingest/IngestStatsTests.java
Labels: v2.0.0, non-issue

#1794 Remove LegacyESVersion.V_6_5_x constants
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartSettingsUpgradeIT.java
  qa/translog-policy/src/test/java/org/opensearch/upgrades/TranslogPolicyIT.java
  server/src/internalClusterTest/java/org/opensearch/index/seqno/PeerRecoveryRetentionLeaseCreationIT.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/template/put/PutIndexTemplateRequest.java
  server/src/main/java/org/opensearch/action/resync/ResyncReplicationRequest.java
  server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/mapper/ParseContext.java
  server/src/main/java/org/opensearch/index/similarity/SimilarityService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTranslogOperationsRequest.java
  server/src/main/java/org/opensearch/ingest/IngestStats.java
  server/src/main/java/org/opensearch/search/fetch/FetchPhase.java
  server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/GeoDistanceSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/NestedSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java
  server/src/test/java/org/opensearch/LegacyESVersionTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/replication/RetentionLeasesReplicationTests.java
Labels: v2.0.0, non-issue

#1815 RestIntegTestTask fails because of missed log4j-core dependency
  buildSrc/src/main/java/org/opensearch/gradle/test/rest/RestTestUtil.java
Labels: backport 1.x

#1813 [TEST] Fix FsHealthServiceTest by increasing the timeout period before checking the FS health after restoring the FS status
  server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java
Labels: :test, v2.0.0

#1804 Remove LegacyESVersion.V_6_6_x constants
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/ClusterStateRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/ClusterStateResponse.java
  server/src/main/java/org/opensearch/action/delete/DeleteRequest.java
  server/src/main/java/org/opensearch/action/index/IndexRequest.java
  server/src/main/java/org/opensearch/action/support/IndicesOptions.java
  server/src/main/java/org/opensearch/cluster/RestoreInProgress.java
  server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
  server/src/main/java/org/opensearch/index/get/GetResult.java
  server/src/main/java/org/opensearch/index/mapper/AbstractShapeGeometryFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/LegacyGeoShapeFieldMapper.java
  server/src/main/java/org/opensearch/monitor/os/OsInfo.java
  server/src/main/java/org/opensearch/search/SearchHits.java
  server/src/main/java/org/opensearch/search/SearchSortValues.java
  server/src/test/java/org/opensearch/BuildTests.java
  server/src/test/java/org/opensearch/LegacyESVersionTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/state/ClusterStateRequestTests.java
  server/src/test/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelperTests.java
  server/src/test/java/org/opensearch/index/mapper/ExternalMapper.java
  server/src/test/java/org/opensearch/index/query/GeoShapeQueryBuilderTests.java
Labels: v2.0.0, non-issue
