Repository opensearch-project/OpenSearch, pull requests merged in 2021-09, with the labels that each got.

#1191 [Bug] Fix mixed cluster support for OpenSearch 2+
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/test/java/org/opensearch/VersionTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
Labels: bug, v2.0.0, backport pending, backwards-compatibility

#1153 Clarify JDK requirement in the Developer Guide
  DEVELOPER_GUIDE.md
  TESTING.md
Labels: documentation, v2.0.0, backport pending, v1.1.0

#1195 [1.x] Fix mixed cluster support for OpenSearch 2+ (#1191)
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/test/java/org/opensearch/VersionTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
Labels: backport, backwards-compatibility, v1.1.0, v1.0.1

#1112 Restoring alpha/beta/rc version semantics
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/VersionTests.java
Labels: Re-version, v2.0.0, backport pending

#1197 Upgrade Apache commons-compress to 1.21
  buildSrc/build.gradle
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/commons-compress-1.19.jar.sha1
  plugins/ingest-attachment/licenses/commons-compress-1.21.jar.sha1
Labels: enhancement, backport pending

#1192 [Version] Increment main to 2.0
  buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
  buildSrc/src/main/java/org/opensearch/gradle/Version.java
  buildSrc/src/test/java/org/opensearch/gradle/BwcOpenSearchVersionsTests.java
  buildSrc/src/test/java/org/opensearch/gradle/DistributionDownloadPluginTests.java
  buildSrc/src/test/java/org/opensearch/gradle/VersionTests.java
  buildSrc/version.properties
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/cluster/coordination/DiscoveryUpgradeService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/transport/InboundDecoder.java
  server/src/main/java/org/opensearch/transport/TransportHandshaker.java
  server/src/test/java/org/opensearch/VersionTests.java
  server/src/test/java/org/opensearch/action/support/IndicesOptionsTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/discovery/zen/NodeJoinControllerTests.java
  server/src/test/java/org/opensearch/transport/TransportHandshakerTests.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
  test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
  test/framework/src/main/java/org/opensearch/upgrades/AbstractFullClusterRestartTestCase.java
  test/framework/src/test/java/org/opensearch/test/VersionUtilsTests.java
Labels: v2.0.0, non-issue

#1204 [1.x] Restoring alpha/beta/rc version semantics (#1112)
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/VersionTests.java
Labels: backport, v1.1.0

#1203 [Backport-1.x] Upgrade apache commons-compress to 1.21 (#1197)
  buildSrc/build.gradle
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/commons-compress-1.19.jar.sha1
  plugins/ingest-attachment/licenses/commons-compress-1.21.jar.sha1
Labels: backport

#1208 [1.x] Clarify JDK requirement in the Developer Guide
  DEVELOPER_GUIDE.md
  TESTING.md
Labels: documentation, backport, v1.1.0

#1206 Kept the original constructor for PluginInfo to maintain bwc
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
  server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
  server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
Labels: v1.1.0

#1209 [Backport-1.x] Kept the original constructor for PluginInfo to maintain bwc (#1206)
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
  server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
  server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
Labels: backport, v1.1.0

#1215 Added Eclipse import instructions to DEVELOPER_GUIDE.md
  DEVELOPER_GUIDE.md
Labels: documentation, v2.0.0

#1222 [1.x] Backport opensearch-upgrade CLI tool.
  distribution/build.gradle
  distribution/src/bin/opensearch-upgrade
  distribution/src/bin/opensearch-upgrade.bat
  distribution/tools/upgrade-cli/build.gradle
  distribution/tools/upgrade-cli/licenses/jackson-LICENSE
  distribution/tools/upgrade-cli/licenses/jackson-NOTICE
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.11.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.11.4.jar.sha1
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/common/settings/KeystoreWrapperUtil.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/common/settings/package-info.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/DetectEsInstallationTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ImportJvmOptionsTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ImportKeystoreTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ImportLog4jPropertiesTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ImportYmlConfigTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/InstallPluginsTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/TaskInput.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/UpgradeCli.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/UpgradeTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ValidateInputTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/package-info.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/DetectEsInstallationTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/ImportLog4jPropertiesTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/ImportYmlConfigTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/InstallPluginsTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/UpgradeCliTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/ValidateInputTaskTests.java
  distribution/tools/upgrade-cli/src/test/resources/config/elasticsearch.keystore
  distribution/tools/upgrade-cli/src/test/resources/config/elasticsearch.yml
  distribution/tools/upgrade-cli/src/test/resources/config/jvm.options.d/test.options
  distribution/tools/upgrade-cli/src/test/resources/config/log4j2.properties
  server/src/main/java/org/opensearch/common/settings/KeyStoreWrapper.java
  settings.gradle
Labels: backport, backwards-compatibility, v1.1.0

#1221 Run link checker GitHub action on schedule.
  .github/workflows/links.yml
Labels: CI

#1231 [1.x] Max scroll limit breach to throw a OpenSearchRejectedExecutionException (#1054)
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
Labels: backport, v1.1.0

#1224 [Backport 1.x] Fix org.opensearch.index.reindex.ReindexRestClientSslTests#testClientSucceedsWithCertificateAuthorities - javax.net.ssl.SSLPeerUnverifiedException
  modules/reindex/src/test/java/org/opensearch/index/reindex/ReindexRestClientSslTests.java
Labels: backport

#1233 [Bug] Fix InstallPluginCommand to use proper key signatures
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
  distribution/tools/plugin-cli/src/main/resources/public_key.asc
  distribution/tools/plugin-cli/src/main/resources/public_key.sig
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
Labels: bug, v1.1.0

#1214 Fix defects in code-coverage.gralde to generate code coverage report properly
  gradle/code-coverage.gradle
  test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java
Labels: Build Libraries & Interfaces, v2.0.0

#1235 [1x] Bug - Fix InstallPluginCommand to use proper key signatures (#1233)
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
  distribution/tools/plugin-cli/src/main/resources/public_key.asc
  distribution/tools/plugin-cli/src/main/resources/public_key.sig
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
Labels: bug, backport, v1.1.0

#1239 [Version] Increment 1x branch to 1.2
  .ci/bwcVersions
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
Labels: non-issue, v1.2.0

#1241 [Version] Add 1.2 for BWC testing
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: non-issue, backwards-compatibility, v1.2.0

#1167 Introduce FS Health HEALTHY threshold to fail stuck node
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/monitor/fs/FsHealthService.java
  server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java
Labels: bug, v1.2.0

#1227 [Backport] Changes to support retrieval of operations from translog based on specified range
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/MissingHistoryOperationsException.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Labels: v1.0.0, backport, distributed framework

#1236 [1.x] Add support to generate code coverage report with JaCoCo
  build.gradle
  buildSrc/src/main/groovy/org/opensearch/gradle/BuildPlugin.groovy
  gradle/code-coverage.gradle
  test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java
Labels: enhancement, CI, Build Libraries & Interfaces, backport, v1.2.0

#1200 adding components to DEVELOPER_GUIDE
  DEVELOPER_GUIDE.md
Labels: documentation, v2.0.0, v1.2.0

#1247 Update Jackson to 2.12.5
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.11.4.jar.sha1
  client/sniffer/licenses/jackson-core-2.12.5.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.11.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.12.5.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.11.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.12.5.jar.sha1
  libs/x-content/licenses/jackson-core-2.11.4.jar.sha1
  libs/x-content/licenses/jackson-core-2.12.5.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.11.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.12.5.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.11.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.12.5.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.11.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.12.5.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.11.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.12.5.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.11.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.12.5.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.11.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.12.5.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.11.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.12.5.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.11.4.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.12.5.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.11.4.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.12.5.jar.sha1
Labels: enhancement

#1251 Rename build artifact to include -min
  buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPluginFuncTest.groovy
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
  distribution/docker/build.gradle
  distribution/packages/build.gradle
Labels: CI, v2.0.0, v1.2.0

#1264 [DOCS] Add guide for generating code coverage report in TESTING.md
  TESTING.md
Labels: documentation, v2.0.0, v1.2.0

#1267 [1.x] Rename build artifact to include -min
  buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPluginFuncTest.groovy
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
  distribution/docker/build.gradle
  distribution/packages/build.gradle
Labels: CI, backport, v1.1.0, v1.2.0

#1289 Fix gradle check fail due to artifact renaming with "-min"
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java
Labels: Build Libraries & Interfaces, v2.0.0, backport pending

#1226 [Backport] Support for translog pruning based on retention leases
  server/src/internalClusterTest/java/org/opensearch/indices/settings/UpdateSettingsIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/TranslogDeletionPolicy.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogTests.java
Labels: Severity-Blocker, backport, v1.1.0, distributed framework

#1294 [Revert] Translog Pruning Setting Deprecation Removal
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
Labels: distributed framework, deprecate, v1.2.0

#1295 [Tests] Translog Pruning tests to MetadataCreateIndexServiceTests
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: :test, v2.0.0, distributed framework

#1309 [Backport] [1.x] Support for Heap after GC stats (opensearch-project#1265)
  server/src/main/java/org/opensearch/monitor/jvm/JvmStats.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
Labels: enhancement, backport, v1.2.0

#1311 [BUG] ConcurrentSnapshotsIT#testAssertMultipleSnapshotsAndPrimaryFailOver fails intermittently
  server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java
Labels: :test, v2.0.0, backport pending, v1.2.0

#1322 [Backport] [1.x] [BUG] ConcurrentSnapshotsIT#testAssertMultipleSnapshotsAndPrimaryFailOver fails intermittently (#1311)
  server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java
Labels: :test, backport, v1.2.0
