Repository opensearch-project/OpenSearch, pull requests merged in 2021-07, with the labels that each got.

#916 Fix Snapshot pattern in DistributionDownloader.
  buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
  buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
Labels: bug, v1.0.0

#913 Add 'tagline' back to MainResponse in server that was removed in PR #427
  server/src/main/java/org/opensearch/action/main/MainResponse.java
  server/src/test/java/org/opensearch/action/main/MainResponseTests.java
Labels: backport pending, backwards-compatibility, v1.0.0, v2.0.0

#914 [1.x] Add 'tagline' back to MainResponse in server that was removed in PR #427
  server/src/main/java/org/opensearch/action/main/MainResponse.java
  server/src/test/java/org/opensearch/action/main/MainResponseTests.java
Labels: backport, backwards-compatibility, v1.0.0

#915 [1.0] Add 'tagline' back to MainResponse in server that was removed in PR #427
  server/src/main/java/org/opensearch/action/main/MainResponse.java
  server/src/test/java/org/opensearch/action/main/MainResponseTests.java
Labels: backport, backwards-compatibility, v1.0.0

#920 [Backport 1.x] Fix Snapshot pattern in DistributionDownloader. (#916)
  buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
  buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
Labels: backport, bug, v1.0.0

#917 Fix arm architecture translation issue (#809)
  buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
Labels: Delivery/Build, backport, bug, v1.0.0

#865 Refresh OpenSearch nodes version in cluster state after upgrade
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RefreshVersionInClusterStateIT.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
  server/src/main/java/org/opensearch/discovery/zen/NodeJoinController.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodesTests.java
  server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
Labels: bug, rolling-upgrade, v1.0.0

#926 [1.x] Refresh OpenSearch nodes version in cluster state after upgrade (#865)
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RefreshVersionInClusterStateIT.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
  server/src/main/java/org/opensearch/discovery/zen/NodeJoinController.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodesTests.java
  server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
Labels: backport, bug, rolling-upgrade, v1.0.0

#932 Update favicon for OpenSearch
  server/src/main/resources/config/favicon.ico
Labels: :sanitize, v1.0.0

#933 [1.x] Update favicon for OpenSearch
  server/src/main/resources/config/favicon.ico
Labels: backport, v1.0.0

#927 [1.x] Fix arm architecture translation issue (#809)
  buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
Labels: backport, v1.0.0

#935 [1.x] Bug - Fix cat.health test failures in pre 1.0.0 mixed cluster test (#928)
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.health/10_basic.yml
  test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
Labels: backport, bug, v1.0.0

#876 Rebuild Rest client after setting interceptor
  modules/reindex/src/main/java/org/opensearch/index/reindex/AbstractAsyncBulkByScrollAction.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java
Labels: bug, v1.0.0, v2.0.0

#838 Add Shard Indexing Pressure Store (#478)
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/ShardIndexingPressureStore.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureStoreTests.java
Labels: feature, v1.1.0, v2.0.0

#937 [1.x] Pass interceptor to super constructor (#876)
  modules/reindex/src/main/java/org/opensearch/index/reindex/AbstractAsyncBulkByScrollAction.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java
Labels: backport, v1.0.0

#950 [Backport-1.x] Updated READMEs on releasing, maintaining, admins and security. (#853)
  ADMINS.md
  MAINTAINERS.md
  README.md
  RELEASING.md
  SECURITY.md
Labels: backport

#877 Adding broken links checker
  .github/workflows/links.yml
  client/benchmark/README.md
  plugins/examples/rest-handler/src/yamlRestTest/resources/rest-api-spec/api/cat.example.json
Labels: CI, Delivery/Build, non-issue

#846 A CLI tool to assist during an upgrade to OpenSearch.
  distribution/build.gradle
  distribution/src/bin/opensearch-upgrade
  distribution/src/bin/opensearch-upgrade.bat
  distribution/tools/upgrade-cli/build.gradle
  distribution/tools/upgrade-cli/licenses/jackson-LICENSE
  distribution/tools/upgrade-cli/licenses/jackson-NOTICE
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.11.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.11.4.jar.sha1
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/common/settings/KeystoreWrapperUtil.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/common/settings/package-info.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/DetectEsInstallationTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ImportJvmOptionsTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ImportKeystoreTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ImportLog4jPropertiesTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ImportYmlConfigTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/InstallPluginsTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/TaskInput.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/UpgradeCli.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/UpgradeTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ValidateInputTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/package-info.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/DetectEsInstallationTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/ImportLog4jPropertiesTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/ImportYmlConfigTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/UpgradeCliTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/ValidateInputTaskTests.java
  distribution/tools/upgrade-cli/src/test/resources/config/elasticsearch.keystore
  distribution/tools/upgrade-cli/src/test/resources/config/elasticsearch.yml
  distribution/tools/upgrade-cli/src/test/resources/config/jvm.options.d/test.options
  distribution/tools/upgrade-cli/src/test/resources/config/log4j2.properties
  server/src/main/java/org/opensearch/common/settings/KeyStoreWrapper.java
  settings.gradle
Labels: backwards-compatibility, feature, v1.1.0, v2.0.0

#889 Avoid override of routes() in BaseRestHandler to respect the default behavior defined in RestHandler
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
  server/src/test/java/org/opensearch/rest/BaseRestHandlerTests.java
  server/src/test/java/org/opensearch/usage/UsageServiceTests.java
Labels: enhancement, v2.0.0

#966 Restricting logs permissions
  distribution/src/config/log4j2.properties
Labels: enhancement, security, v1.1.0

#923 Fail fast when BytesRestResponse ctor throws exception
  server/src/main/java/org/opensearch/rest/action/RestActionListener.java
Labels: enhancement, v1.1.0, v2.0.0

#947 Introduce replaceRoutes() method and 2 new constructors to RestHandler.java
  server/src/main/java/org/opensearch/rest/RestHandler.java
  server/src/test/java/org/opensearch/rest/BaseRestHandlerTests.java
Labels: backport pending, enhancement, v1.1.0

#875 Fix opensearch-env always sources the environment from hardcoded file
  distribution/src/bin/opensearch-env
Labels: bug, v1.1.0, v2.0.0

#994 Reset Elasticsearch 7.13 links in scripts
  distribution/src/bin/opensearch-env
  distribution/src/config/jvm.options
Labels: backport pending, documentation, v1.1.0

#848 Allowing custom folder name for plugin installation
  buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
  buildSrc/src/main/java/org/opensearch/gradle/plugin/PluginPropertiesExtension.java
  buildSrc/src/main/resources/plugin-descriptor.properties
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/ListPluginsCommand.java
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/PluginHelper.java
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/RemovePluginCommand.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/ListPluginsCommandTests.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/RemovePluginCommandTests.java
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
  server/src/main/java/org/opensearch/plugins/PluginsService.java
  server/src/test/java/org/opensearch/nodesinfo/NodeInfoStreamingTests.java
  server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
  server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
Labels: feature, v1.1.0, v2.0.0

#1001 [1.x] Replace Elasticsearch docs links in scripts (#994)
  distribution/src/bin/opensearch-env
  distribution/src/config/jvm.options
Labels: backport, documentation, v1.1.0
