Repository opensearch-project/OpenSearch, pull requests merged in 2021-06, with the labels that each got.

#797 Version checks are incorrectly returning versions < 1.0.0.
  buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
  buildSrc/src/test/java/org/opensearch/gradle/BwcOpenSearchVersionsTests.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
Labels: :test, backport, backwards-compatibility, v1.0.0

#807 [Backport][1.x] Version checks are incorrectly returning versions < 1.0.0. (#797)
  buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
  buildSrc/src/test/java/org/opensearch/gradle/BwcOpenSearchVersionsTests.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
Labels: backport, v1.1.0

#796 Enable BWC checks
  build.gradle
Labels: :test, backwards-compatibility

#812 Remove reference to an EC2 instance type.
  DEVELOPER_GUIDE.md
Labels: documentation

#811 [1.x] Enable BWC checks (#796)
  build.gradle
Labels: :test, backport, backwards-compatibility

#792 Remove checks for legacy .yaml and .json config files.
  server/src/main/java/org/opensearch/node/InternalSettingsPreparer.java
  server/src/test/java/org/opensearch/node/InternalSettingsPreparerTests.java
Labels: v1.0.0, v1.1.0

#741 Document running individual tests.
  TESTING.md
Labels: documentation, v1.0.0, v2.0.0

#809 Fix arm architecture translation issue
  buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
Labels: backport pending

#816 Fix resource leak issues suggested by Amazon CodeGuru
  buildSrc/src/integTest/java/org/opensearch/gradle/tar/SymbolicLinkPreservingTarIT.java
  buildSrc/src/main/java/org/opensearch/gradle/VersionProperties.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/LicenseAnalyzer.java
  buildSrc/src/main/java/org/opensearch/gradle/transform/SymbolicLinkPreservingUntarTransform.java
  libs/nio/src/main/java/org/opensearch/nio/ServerChannelContext.java
  modules/lang-painless/src/main/java/org/opensearch/painless/api/Json.java
  server/src/internalClusterTest/java/org/opensearch/search/geo/GeoFilterIT.java
  server/src/internalClusterTest/java/org/opensearch/versioning/ConcurrentSeqNoVersioningIT.java
  server/src/main/java/org/opensearch/common/xcontent/XContentHelper.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: security

#858 Add URL for lucene snapshots
  buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java
Labels: Delivery/Build, backport pending, enhancement, v1.1.0, v2.0.0

#691 Enable adding experimental features through sandbox modules
  DEVELOPER_GUIDE.md
  distribution/build.gradle
  sandbox/build.gradle
  sandbox/libs/build.gradle
  sandbox/modules/build.gradle
  sandbox/plugins/build.gradle
  settings.gradle
Labels: backport pending, feature, v1.1.0, v2.0.0

#847 Add MainResponse version override as a cluster setting.
  client/rest-high-level/src/test/java/org/opensearch/client/PingAndInfoIT.java
  server/src/main/java/org/opensearch/action/main/MainResponse.java
  server/src/main/java/org/opensearch/action/main/TransportMainAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/action/main/MainActionTests.java
  server/src/test/java/org/opensearch/action/main/MainResponseTests.java
Labels: Severity-Blocker, enhancement, v1.0.0, v1.1.0, v2.0.0

#870 Backport 1.x - Add cluster setting to spoof version number returned from MainResponse (#847)
  client/rest-high-level/src/test/java/org/opensearch/client/PingAndInfoIT.java
  server/src/main/java/org/opensearch/action/main/MainResponse.java
  server/src/main/java/org/opensearch/action/main/TransportMainAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/action/main/MainActionTests.java
  server/src/test/java/org/opensearch/action/main/MainResponseTests.java
Labels: backport, enhancement, v1.0.0

#878 docker build: use OSS `log4j2.properties`
  distribution/docker/src/docker/config/log4j2.properties
  distribution/docker/src/docker/config/oss/log4j2.properties
Labels: bug

#883 [CVE] Update external library 'pdfbox' version to 2.0.24 to reduce vulnerability
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/fontbox-2.0.23.jar.sha1
  plugins/ingest-attachment/licenses/fontbox-2.0.24.jar.sha1
  plugins/ingest-attachment/licenses/pdfbox-2.0.23.jar.sha1
  plugins/ingest-attachment/licenses/pdfbox-2.0.24.jar.sha1
Labels: CVE, security, v1.0.0, v2.0.0

#884 [BUG] Fix versioning issues discovered through version bump
  buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: backport pending, bug, v1.0.0, v2.0.0

#887 [1.x] Fix versioning issues discovered through version bump (#884)
  buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: backport, bug, v1.0.0

#886 [1.x][Backport][CVE] Update external library 'pdfbox' version to 2.0.24 to reduce vulnerability
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/fontbox-2.0.23.jar.sha1
  plugins/ingest-attachment/licenses/fontbox-2.0.24.jar.sha1
  plugins/ingest-attachment/licenses/pdfbox-2.0.23.jar.sha1
  plugins/ingest-attachment/licenses/pdfbox-2.0.24.jar.sha1
Labels: CVE, backport, security, v1.0.0

#882 [1.0] Backport support running elasticsearch-oss distribution in test cluster for BWC
  buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
  buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
Labels: backport, v1.0.0

#772 Version bump for 1.1 release
  .ci/bwcVersions
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: v1.1.0, v2.0.0

#892 [1.x] Version bump/1.1 backport
  .ci/bwcVersions
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: backport, v1.1.0

#903 [1.0] Update external library 'pdfbox' version to 2.0.24 to reduce vulnerability
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/fontbox-2.0.23.jar.sha1
  plugins/ingest-attachment/licenses/fontbox-2.0.24.jar.sha1
  plugins/ingest-attachment/licenses/pdfbox-2.0.23.jar.sha1
  plugins/ingest-attachment/licenses/pdfbox-2.0.24.jar.sha1
Labels: CVE, backport, security, v1.0.0

#904 Update DistributionDownloader to fetch snapshots and staging bundles.
  buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
  buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
Labels: Delivery/Build, backport pending, enhancement

#910 Backport [1.x] - Replace metadata keys in OpenSearchException during serialization and…
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/ExceptionIT.java
  server/src/main/java/org/opensearch/OpenSearchException.java
Labels: backport, backwards-compatibility, bug, v1.0.0
