Repository opensearch-project/OpenSearch, pull requests merged in 2021-05, with the labels that each got.

#629 Fix snapshot deletion task getting stuck in the event of exceptions
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: bug, enhancement, v1.0.0, v2.0.0

#625 Make default number of shards configurable
  qa/evil-tests/src/test/java/org/opensearch/cluster/metadata/EvilSystemPropertyTests.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
Labels: enhancement

#630 Remove URL content from Reindex error response
  modules/reindex/src/main/java/org/opensearch/index/reindex/remote/RemoteScrollableHitSource.java
  modules/reindex/src/test/java/org/opensearch/index/reindex/remote/RemoteScrollableHitSourceTests.java
Labels: enhancement, v2.0.0

#689 Update instructions on how to start OpenSearch in debug mode
  TESTING.md
Labels: documentation

#650 [1.x] Fix snapshot deletion task getting stuck in the event of exceptions (#629)
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: backport, v1.0.0

#662 [CVE-2020-7692] Upgrade google-oauth-client for Google cloud plugins
  plugins/discovery-gce/build.gradle
  plugins/discovery-gce/licenses/google-oauth-client-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-oauth-client-1.31.0.jar.sha1
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/google-oauth-client-1.28.0.jar.sha1
  plugins/repository-gcs/licenses/google-oauth-client-1.31.0.jar.sha1
Labels: CVE, v1.0.0, v2.0.0

#654 [CVE-2018-11765] Upgrade hadoop dependencies for hdfs plugin to mitigate CVEs.
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/guava-11.0.2.jar.sha1
  plugins/repository-hdfs/licenses/guava-30.1.1-jre.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-annotations-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-annotations-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-auth-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-auth-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-common-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-common-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-client-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-client-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/stax2-api-4.2.1.jar.sha1
  plugins/repository-hdfs/licenses/stax2-api-LICENSE.txt
  plugins/repository-hdfs/licenses/stax2-api-NOTICE.txt
  plugins/repository-hdfs/licenses/woodstox-core-6.1.1.jar.sha1
  plugins/repository-hdfs/licenses/woodstox-core-LICENSE.txt
  plugins/repository-hdfs/licenses/woodstox-core-NOTICE.txt
  test/fixtures/hdfs-fixture/build.gradle
Labels: CVE, v1.0.0, v2.0.0

#569 [TEST] Fix distro tests for linux packages
  NOTICE.txt
  Vagrantfile
  buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPluginFuncTest.groovy
  buildSrc/src/main/groovy/org/opensearch/gradle/NoticeTask.groovy
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPlugin.java
  distribution/packages/build.gradle
  qa/os/src/test/java/org/opensearch/packaging/test/DockerTests.java
  qa/os/src/test/java/org/opensearch/packaging/util/Docker.java
  qa/os/src/test/java/org/opensearch/packaging/util/Packages.java
Labels: >test-failure, v1.0.0, v2.0.0

#690 Support Data Streams in OpenSearch
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/datastream/DataStreamIndexTemplateIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/datastream/DataStreamRolloverIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/datastream/DataStreamTestCase.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/datastream/DataStreamUsageIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/template/ComposableTemplateIT.java
  server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java
  server/src/main/java/org/opensearch/cluster/metadata/DataStream.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateDataStreamService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/index/mapper/DataStreamFieldMapper.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/test/java/org/opensearch/action/admin/indices/create/AutoCreateActionTests.java
  server/src/test/java/org/opensearch/cluster/metadata/DataStreamTemplateTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/opensearch/index/mapper/DataStreamFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java
  server/src/test/java/org/opensearch/indices/IndicesModuleTests.java
  test/framework/src/main/java/org/opensearch/cluster/DataStreamTestHelper.java
Labels: enhancement, v1.0.0, v2.0.0

#707 Fixes precommit task configuration failures due to newly added missin…
  client/rest/src/main/java/org/opensearch/client/NodeSelector.java
  client/rest/src/main/java/org/opensearch/client/RestClientBuilder.java
  gradle/missing-javadoc.gradle
Labels: javadocs

#715 Merging javadoc feature branch changes to main
  CONTRIBUTING.md
  build.gradle
  buildSrc/reaper/src/main/java/org/opensearch/gradle/reaper/package-info.java
  client/rest/src/main/java/org/opensearch/client/HasAttributeNodeSelector.java
  client/rest/src/main/java/org/opensearch/client/HeapBufferedAsyncResponseConsumer.java
  client/rest/src/main/java/org/opensearch/client/HttpAsyncResponseConsumerFactory.java
  client/rest/src/main/java/org/opensearch/client/Node.java
  client/rest/src/main/java/org/opensearch/client/NodeSelector.java
  client/rest/src/main/java/org/opensearch/client/PreferHasAttributeNodeSelector.java
  client/rest/src/main/java/org/opensearch/client/Request.java
  client/rest/src/main/java/org/opensearch/client/RequestOptions.java
  client/rest/src/main/java/org/opensearch/client/Response.java
  client/rest/src/main/java/org/opensearch/client/ResponseException.java
  client/rest/src/main/java/org/opensearch/client/ResponseListener.java
  client/rest/src/main/java/org/opensearch/client/RestClient.java
  client/rest/src/main/java/org/opensearch/client/RestClientBuilder.java
  client/rest/src/main/java/org/opensearch/client/WarningFailureException.java
  client/rest/src/main/java/org/opensearch/client/WarningsHandler.java
  client/rest/src/main/java/org/opensearch/client/package-info.java
  distribution/tools/launchers/build.gradle
  doc-tools/build.gradle
  doc-tools/missing-doclet/build.gradle
  doc-tools/missing-doclet/src/main/java/org/opensearch/missingdoclet/MissingDoclet.java
  gradle/missing-javadoc.gradle
  settings.gradle
  test/fixtures/azure-fixture/build.gradle
  test/fixtures/gcs-fixture/build.gradle
  test/fixtures/hdfs-fixture/build.gradle
  test/fixtures/old-elasticsearch/build.gradle
  test/fixtures/s3-fixture/build.gradle
Labels: javadocs

#731 [1.x][backport] Added a link to the maintainer file in contribution guides (#589)
  CONTRIBUTING.md
Labels: backport, v1.0.0

#743 Create group settings with fallback.
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
Labels: v1.0.0, v2.0.0

#739 [1.x][backport] Make allocation decisions at node level first for pending task optimi…
  benchmarks/src/main/java/org/opensearch/benchmark/routing/allocation/AllocationBenchmark.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AllocationDecider.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AllocationDeciders.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ConcurrentRecoveriesAllocationDecider.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/Decision.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/AllocationDecidersTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/ConcurrentRecoveriesAllocationDeciderTests.java
Labels: backport, v1.0.0

#745 [1.x][Backport] Create group settings with fallback. (#743)
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
Labels: backport, v1.0.0

#738 [1.x] Update instructions on debugging OpenSearch. (#689)
  TESTING.md
Labels: backport, v1.0.0

#733 [1.x] [TEST] Fix failing distro tests for linux packages (#569)
  NOTICE.txt
  Vagrantfile
  buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPluginFuncTest.groovy
  buildSrc/src/main/groovy/org/opensearch/gradle/NoticeTask.groovy
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPlugin.java
  distribution/packages/build.gradle
  qa/os/src/test/java/org/opensearch/packaging/test/DockerTests.java
  qa/os/src/test/java/org/opensearch/packaging/util/Docker.java
  qa/os/src/test/java/org/opensearch/packaging/util/Packages.java
Labels: backport, v1.0.0

#730 [1.x][backport]Handle inefficiencies while fetching the delayed unassigned shards du…
  server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/UnassignedInfo.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingTableTests.java
Labels: backport, v1.0.0

#725 [1.x] Add read_only block argument to opensearch-node unsafe-bootstrap command #599
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/UnsafeBootstrapAndDetachCommandIT.java
  server/src/main/java/org/opensearch/cluster/coordination/UnsafeBootstrapMasterCommand.java
Labels: backport, v1.0.0

#736 [1.x] [CVE-2018-11765] Upgrade hadoop dependencies for hdfs plugin (#654)
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/guava-11.0.2.jar.sha1
  plugins/repository-hdfs/licenses/guava-30.1.1-jre.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-annotations-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-annotations-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-auth-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-auth-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-common-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-common-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-client-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-client-2.8.5.jar.sha1
  plugins/repository-hdfs/licenses/stax2-api-4.2.1.jar.sha1
  plugins/repository-hdfs/licenses/stax2-api-LICENSE.txt
  plugins/repository-hdfs/licenses/stax2-api-NOTICE.txt
  plugins/repository-hdfs/licenses/woodstox-core-6.1.1.jar.sha1
  plugins/repository-hdfs/licenses/woodstox-core-LICENSE.txt
  plugins/repository-hdfs/licenses/woodstox-core-NOTICE.txt
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport, v1.0.0

#735 [1.x] Update dependencies for ingest-attachment plugin. (#666)
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/commons-io-2.6.jar.sha1
  plugins/ingest-attachment/licenses/commons-io-2.7.jar.sha1
  plugins/ingest-attachment/licenses/fontbox-2.0.19.jar.sha1
  plugins/ingest-attachment/licenses/fontbox-2.0.23.jar.sha1
  plugins/ingest-attachment/licenses/pdfbox-2.0.19.jar.sha1
  plugins/ingest-attachment/licenses/pdfbox-2.0.23.jar.sha1
  plugins/ingest-attachment/licenses/tika-core-1.24.1.jar.sha1
  plugins/ingest-attachment/licenses/tika-core-1.24.jar.sha1
  plugins/ingest-attachment/licenses/tika-parsers-1.24.1.jar.sha1
  plugins/ingest-attachment/licenses/tika-parsers-1.24.jar.sha1
Labels: backport, v1.0.0

#734 [1.x] [CVE-2020-7692] Upgrade google-oauth clients for goolge cloud plugins (#662)
  plugins/discovery-gce/build.gradle
  plugins/discovery-gce/licenses/google-oauth-client-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-oauth-client-1.31.0.jar.sha1
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/google-oauth-client-1.28.0.jar.sha1
  plugins/repository-gcs/licenses/google-oauth-client-1.31.0.jar.sha1
Labels: backport, v1.0.0

#726 [1.x][backport]Make default number of shards configurable
  qa/evil-tests/src/test/java/org/opensearch/cluster/metadata/EvilSystemPropertyTests.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
Labels: backport, v1.0.0

#713 [1.x] Support Data Streams in OpenSearch (#690)
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/datastream/DataStreamIndexTemplateIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/datastream/DataStreamRolloverIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/datastream/DataStreamTestCase.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/datastream/DataStreamUsageIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/template/ComposableTemplateIT.java
  server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java
  server/src/main/java/org/opensearch/cluster/metadata/DataStream.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateDataStreamService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/index/mapper/DataStreamFieldMapper.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/test/java/org/opensearch/action/admin/indices/create/AutoCreateActionTests.java
  server/src/test/java/org/opensearch/cluster/metadata/DataStreamTemplateTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/opensearch/index/mapper/DataStreamFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java
  server/src/test/java/org/opensearch/indices/IndicesModuleTests.java
  test/framework/src/main/java/org/opensearch/cluster/DataStreamTestHelper.java
Labels: backport

#749 [1.x] Update issue template for multiple labels
  .github/ISSUE_TEMPLATE/bug_template.md
Labels: backport

#751 [1.x] Updating README and CONTRIBUTING guide to get ready for beta1 release.
  CONTRIBUTING.md
  README.md
Labels: backport

#752 [1.x] Update/maintainers.md
  MAINTAINERS.md
Labels: backport

#753 [1.x] distribution/packages: Fix filename format for deb archives (#621)
  distribution/packages/build.gradle
Labels: backport

#750 [1.x] Catch runtime exceptions to make class loader race conditions easier to debug
  server/src/main/java/org/opensearch/LegacyESVersion.java
Labels: backport

#756 [1.x] Add Remote Reindex SPI extension (#547)
  modules/reindex/src/main/java/org/opensearch/index/reindex/AbstractAsyncBulkByScrollAction.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/ReindexPlugin.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/TransportReindexAction.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/spi/ReindexRestInterceptorProvider.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/spi/RemoteReindexExtension.java
Labels: backport

#748 [1.x] Remove URL content from Reindex error response
  modules/reindex/src/main/java/org/opensearch/index/reindex/remote/RemoteScrollableHitSource.java
  modules/reindex/src/test/java/org/opensearch/index/reindex/remote/RemoteScrollableHitSourceTests.java
Labels: backport

#656 Apply fix for health API response to distinguish no master
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.health/10_basic.yml
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
  server/src/main/java/org/opensearch/cluster/health/ClusterStateHealth.java
  server/src/main/java/org/opensearch/rest/action/cat/RestHealthAction.java
  server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponsesTests.java
  server/src/test/java/org/opensearch/cluster/health/ClusterStateHealthTests.java
Labels: backport pending, enhancement

#759 [1.x] Add timeout on cat/stats API
  server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsRequestBuilder.java
  server/src/main/java/org/opensearch/action/support/broadcast/BroadcastRequest.java
  server/src/main/java/org/opensearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java
  server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesInfoAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestIndicesStatsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/AbstractCatAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestAllocationAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestCatRecoveryAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodeAttrsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestPluginsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestThreadPoolAction.java
  server/src/test/java/org/opensearch/action/support/broadcast/node/TransportBroadcastByNodeActionTests.java
Labels: backport

#758 [Bug] Fix gradle build on Windows failing from a recent change
  buildSrc/src/main/groovy/org/opensearch/gradle/NoticeTask.groovy
Labels: Severity-Critical, bug, v1.0.0

#765 [1.x] [Bug] Fix gradle build on Windows failing from a recent change
  buildSrc/src/main/groovy/org/opensearch/gradle/NoticeTask.groovy
Labels: backport, v1.0.0

#764 Support running elasticsearch-oss distribution in test cluster for BWC
  buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
  buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
Labels: backwards-compatibility, v1.0.0

#688 [CVE] Upgrade dependencies for Azure related plugins to mitigate CVEs
  plugins/discovery-azure-classic/build.gradle
  plugins/discovery-azure-classic/licenses/commons-io-2.4.jar.sha1
  plugins/discovery-azure-classic/licenses/commons-io-2.7.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-LICENSE
  plugins/discovery-azure-classic/licenses/jackson-NOTICE
  plugins/discovery-azure-classic/licenses/jackson-core-asl-1.9.2.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-jaxrs-1.9.2.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-mapper-asl-1.9.2.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-xc-1.9.2.jar.sha1
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/guava-20.0.jar.sha1
  plugins/repository-azure/licenses/guava-30.1.1-jre.jar.sha1
Labels: CVE, v2.0.0

#770 [1.x] distribution/packages: Fix RPM architecture name for 64-bit x86 (#620)
  distribution/packages/build.gradle
Labels: backport

#771 [1.x][CVE] Upgrade dependencies for Azure related plugins to mitigate CVEs
  plugins/discovery-azure-classic/build.gradle
  plugins/discovery-azure-classic/licenses/commons-io-2.4.jar.sha1
  plugins/discovery-azure-classic/licenses/commons-io-2.7.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-LICENSE
  plugins/discovery-azure-classic/licenses/jackson-NOTICE
  plugins/discovery-azure-classic/licenses/jackson-core-asl-1.9.2.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-jaxrs-1.9.2.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-mapper-asl-1.9.2.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-xc-1.9.2.jar.sha1
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/guava-20.0.jar.sha1
  plugins/repository-azure/licenses/guava-30.1.1-jre.jar.sha1
Labels: backport

#680 An allocation constraint mechanism, that de-prioritizes nodes from getting picked for allocation if they breach certain constraints
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/IndexShardConstraintDeciderOverlapTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/IndexShardHotSpotTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/ShardsLimitAllocationTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationWithConstraintsTestCase.java
Labels: WIP, feature

#755 Add a method to use fallback setting to set the memory size
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
Labels: backport pending

#783 [1.0] distribution/packages: Fix RPM architecture name for 64-bit x86
  distribution/packages/build.gradle
Labels: v1.0.0

#784 [1.0][CVE] Upgrade dependencies for Azure related plugins to mitigate CVEs
  plugins/discovery-azure-classic/build.gradle
  plugins/discovery-azure-classic/licenses/commons-io-2.4.jar.sha1
  plugins/discovery-azure-classic/licenses/commons-io-2.7.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-LICENSE
  plugins/discovery-azure-classic/licenses/jackson-NOTICE
  plugins/discovery-azure-classic/licenses/jackson-core-asl-1.9.2.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-jaxrs-1.9.2.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-mapper-asl-1.9.2.jar.sha1
  plugins/discovery-azure-classic/licenses/jackson-xc-1.9.2.jar.sha1
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/guava-20.0.jar.sha1
  plugins/repository-azure/licenses/guava-30.1.1-jre.jar.sha1
Labels: v1.0.0

#708 [BUG] fix MainResponse to spoof version number for legacy clients
  server/src/main/java/org/opensearch/action/main/MainResponse.java
Labels: Severity-Blocker, WIP, backwards-compatibility, bug, v1.0.0, v2.0.0

#775 [BWC] fix mixedCluster and rolling upgrades
  client/rest/src/main/java/org/opensearch/client/Response.java
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/90_remote.yml
  qa/full-cluster-restart/build.gradle
  qa/mixed-cluster/build.gradle
  qa/repository-multi-version/build.gradle
  qa/verify-version-constants/build.gradle
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.validate_query/10_basic.yml
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodeInfo.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/common/logging/HeaderWarning.java
  server/src/main/java/org/opensearch/transport/TransportHandshaker.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/discovery/ZenFaultDetectionTests.java
  server/src/test/java/org/opensearch/transport/TransportHandshakerTests.java
  test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
Labels: Severity-Blocker, backwards-compatibility, bug, v1.0.0, v1.1.0, v2.0.0

#793 [1.x] BWC - fix mixedCluster and rolling upgrades (#775)
  client/rest/src/main/java/org/opensearch/client/Response.java
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/90_remote.yml
  qa/full-cluster-restart/build.gradle
  qa/mixed-cluster/build.gradle
  qa/repository-multi-version/build.gradle
  qa/verify-version-constants/build.gradle
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.validate_query/10_basic.yml
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodeInfo.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/common/logging/HeaderWarning.java
  server/src/main/java/org/opensearch/transport/TransportHandshaker.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/discovery/ZenFaultDetectionTests.java
  server/src/test/java/org/opensearch/transport/TransportHandshakerTests.java
  test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
Labels: Severity-Blocker, backport, backwards-compatibility, bug, v1.0.0
