Repository opensearch-project/OpenSearch, pull requests merged in 2021-04, with the labels that each got.

#527 Remove extra greater-thans from README
  README.md
Labels: documentation

#531 [License] Add SPDX License Header to security policies
  buildSrc/src/main/resources/fips_java_bcjsse_11.policy
  buildSrc/src/main/resources/fips_java_bcjsse_8.policy
  buildSrc/src/main/resources/fips_java_sunjsse.policy
  distribution/archives/integ-test-zip/src/test/resources/plugin-security.policy
  modules/ingest-geoip/src/main/plugin-metadata/plugin-security.policy
  modules/lang-expression/src/main/plugin-metadata/plugin-security.policy
  modules/lang-mustache/src/main/plugin-metadata/plugin-security.policy
  modules/lang-painless/src/main/plugin-metadata/plugin-security.policy
  modules/reindex/src/main/plugin-metadata/plugin-security.policy
  modules/repository-url/src/main/plugin-metadata/plugin-security.policy
  modules/systemd/src/main/plugin-metadata/plugin-security.policy
  modules/transport-netty4/src/main/plugin-metadata/plugin-security.policy
  plugins/discovery-azure-classic/src/main/plugin-metadata/plugin-security.policy
  plugins/discovery-ec2/src/main/plugin-metadata/plugin-security.policy
  plugins/discovery-gce/src/main/plugin-metadata/plugin-security.policy
  plugins/ingest-attachment/src/main/plugin-metadata/plugin-security.policy
  plugins/repository-azure/src/main/plugin-metadata/plugin-security.policy
  plugins/repository-gcs/src/main/plugin-metadata/plugin-security.policy
  plugins/repository-hdfs/src/main/plugin-metadata/plugin-security.policy
  plugins/repository-s3/src/main/plugin-metadata/plugin-security.policy
  plugins/transport-nio/src/main/plugin-metadata/plugin-security.policy
  qa/evil-tests/src/test/resources/org/opensearch/plugins/security/complex-plugin-security.policy
  qa/evil-tests/src/test/resources/org/opensearch/plugins/security/simple-plugin-security.policy
  qa/evil-tests/src/test/resources/org/opensearch/plugins/security/unresolved-plugin-security.policy
  qa/logging-config/src/test/resources/plugin-security.policy
  qa/unconfigured-node-name/src/test/resources/plugin-security.policy
  server/src/main/resources/org/opensearch/bootstrap/security.policy
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
  server/src/main/resources/org/opensearch/bootstrap/untrusted.policy
Labels: >FORK, v1.0.0, v1.0.0-alpha1, v2.0.0

#541 [TEST] Fix failing packaging tests for OpenSearch distributions.
  distribution/archives/build.gradle
  distribution/packages/build.gradle
  qa/os/src/test/java/org/opensearch/packaging/util/Archives.java
  qa/os/src/test/java/org/opensearch/packaging/util/Docker.java
  qa/os/src/test/java/org/opensearch/packaging/util/Packages.java
Labels: >test-failure, v1.0.0, v1.0.0-alpha1

#559 TEST BUG: MergeSchedulerSettingsTests fails always on small machines
  server/src/test/java/org/opensearch/index/MergeSchedulerSettingsTests.java
Labels: community

#565 [DOCKER] add apt update to test fixture krb5kdc
  test/fixtures/krb5kdc-fixture/Dockerfile
Labels: >test-failure

#575 Remove the oss string from OpenSearch distributions
  TESTING.asciidoc
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/integTest/groovy/org/opensearch/gradle/DistributionDownloadPluginFuncTest.groovy
  buildSrc/src/integTest/groovy/org/opensearch/gradle/fixtures/DistributionDownloadFixture.groovy
  buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPluginFuncTest.groovy
  buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionBwcSetupPluginFuncTest.groovy
  buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionDownloadPluginFuncTest.groovy
  buildSrc/src/integTest/resources/org/opensearch/gradle/internal/fake_git/remote/distribution/archives/build.gradle
  buildSrc/src/integTest/resources/org/opensearch/gradle/internal/fake_git/remote/settings.gradle
  buildSrc/src/main/groovy/org/opensearch/gradle/test/ClusterFormationTasks.groovy
  buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionDownloadPlugin.java
  buildSrc/src/main/resources/license-headers/license-header.txt
  buildSrc/src/test/java/org/opensearch/gradle/DistributionDownloadPluginTests.java
  distribution/archives/build.gradle
  distribution/archives/darwin-tar/build.gradle
  distribution/archives/linux-aarch64-tar/build.gradle
  distribution/archives/linux-tar/build.gradle
  distribution/archives/no-jdk-darwin-tar/build.gradle
  distribution/archives/no-jdk-linux-tar/build.gradle
  distribution/archives/no-jdk-windows-zip/build.gradle
  distribution/archives/windows-zip/build.gradle
  distribution/build.gradle
  distribution/docker/build.gradle
  distribution/docker/docker-aarch64-export/build.gradle
  distribution/docker/docker-build-context/build.gradle
  distribution/docker/docker-compose.yml
  distribution/docker/docker-export/build.gradle
  distribution/docker/src/test/java/org/opensearch/docker/test/DockerYmlTestSuiteIT.java
  distribution/packages/aarch64-deb/build.gradle
  distribution/packages/aarch64-rpm/build.gradle
  distribution/packages/build.gradle
  distribution/packages/deb/build.gradle
  distribution/packages/no-jdk-deb/build.gradle
  distribution/packages/no-jdk-rpm/build.gradle
  distribution/packages/rpm/build.gradle
  qa/os/src/test/java/org/opensearch/packaging/util/Archives.java
  qa/os/src/test/java/org/opensearch/packaging/util/Cleanup.java
  qa/os/src/test/java/org/opensearch/packaging/util/Docker.java
  qa/os/src/test/java/org/opensearch/packaging/util/Packages.java
  qa/remote-clusters/build.gradle
  qa/remote-clusters/docker-compose.yml
  qa/remote-clusters/haproxy.cfg
  qa/remote-clusters/src/test/java/org/opensearch/cluster/remote/test/AbstractMultiClusterRemoteTestCase.java
  qa/remote-clusters/src/test/java/org/opensearch/cluster/remote/test/RemoteClustersIT.java
  qa/wildfly/docker-compose.yml
  settings.gradle
Labels: :sanitize, v1.0.0, v1.0.0-alpha1

#586 Remove all elastic.co references from javadocs
  client/rest-high-level/src/main/java/org/opensearch/client/ClusterClient.java
  client/rest-high-level/src/main/java/org/opensearch/client/IndicesClient.java
  client/rest-high-level/src/main/java/org/opensearch/client/IngestClient.java
  client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java
  client/rest-high-level/src/main/java/org/opensearch/client/SnapshotClient.java
  client/rest-high-level/src/main/java/org/opensearch/client/TasksClient.java
  server/src/main/java/org/opensearch/index/query/SimpleQueryStringBuilder.java
Labels: :sanitize

#603 Rename the 'oss' distribution used in test clusters.
  TESTING.asciidoc
  buildSrc/src/integTest/groovy/org/opensearch/gradle/TestClustersPluginFuncTest.groovy
  buildSrc/src/main/groovy/org/opensearch/gradle/doc/DocsTestPlugin.groovy
  buildSrc/src/main/groovy/org/opensearch/gradle/test/ClusterConfiguration.groovy
  buildSrc/src/main/groovy/org/opensearch/gradle/test/ClusterFormationTasks.groovy
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestDistribution.java
  client/rest-high-level/build.gradle
  gradle/run.gradle
  modules/lang-painless/build.gradle
  plugins/examples/painless-whitelist/build.gradle
  qa/build.gradle
Labels: :sanitize, v1.0.0, v1.0.0-alpha1, v2.0.0

#604 [Versioning] Fix Version.fromString logic for legacy version
  client/rest-high-level/src/test/java/org/opensearch/client/core/MainResponseTests.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/remote/RemoteResponseParsers.java
  modules/reindex/src/test/java/org/opensearch/index/reindex/remote/RemoteScrollableHitSourceTests.java
  modules/reindex/src/test/resources/responses/main/OpenSearch_1_0_0.json
  server/src/main/java/org/opensearch/Build.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/action/main/MainResponse.java
  server/src/test/java/org/opensearch/BuildTests.java
  server/src/test/java/org/opensearch/VersionTests.java
  server/src/test/java/org/opensearch/action/main/MainResponseTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexUpgradeServiceTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodesTests.java
  server/src/test/java/org/opensearch/common/lucene/uid/VersionsTests.java
  server/src/test/java/org/opensearch/index/analysis/PreConfiguredTokenFilterTests.java
  server/src/test/java/org/opensearch/transport/InboundDecoderTests.java
  test/framework/src/test/java/org/opensearch/test/VersionUtilsTests.java
  test/framework/src/test/java/org/opensearch/test/rest/yaml/section/DoSectionTests.java
Labels: Re-version, v1.0.0, v1.0.0-alpha1, v2.0.0

#598 Fix failing test caused by versioning change.
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/VersionTests.java
  server/src/test/java/org/opensearch/discovery/zen/NodeJoinControllerTests.java
Labels: >test-failure, bug, v1.0.0, v1.0.0-alpha1

#557 Update lucene version to 8.8.2
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-8.7.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-8.8.2.jar.sha1
  plugins/analysis-icu/licenses/lucene-analyzers-icu-8.7.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analyzers-icu-8.8.2.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analyzers-kuromoji-8.7.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analyzers-kuromoji-8.8.2.jar.sha1
  plugins/analysis-nori/licenses/lucene-analyzers-nori-8.7.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analyzers-nori-8.8.2.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analyzers-phonetic-8.7.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analyzers-phonetic-8.8.2.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analyzers-smartcn-8.7.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analyzers-smartcn-8.8.2.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analyzers-stempel-8.7.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analyzers-stempel-8.8.2.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analyzers-morfologik-8.7.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analyzers-morfologik-8.8.2.jar.sha1
  server/licenses/lucene-analyzers-common-8.7.0.jar.sha1
  server/licenses/lucene-analyzers-common-8.8.2.jar.sha1
  server/licenses/lucene-backward-codecs-8.7.0.jar.sha1
  server/licenses/lucene-backward-codecs-8.8.2.jar.sha1
  server/licenses/lucene-core-8.7.0.jar.sha1
  server/licenses/lucene-core-8.8.2.jar.sha1
  server/licenses/lucene-grouping-8.7.0.jar.sha1
  server/licenses/lucene-grouping-8.8.2.jar.sha1
  server/licenses/lucene-highlighter-8.7.0.jar.sha1
  server/licenses/lucene-highlighter-8.8.2.jar.sha1
  server/licenses/lucene-join-8.7.0.jar.sha1
  server/licenses/lucene-join-8.8.2.jar.sha1
  server/licenses/lucene-memory-8.7.0.jar.sha1
  server/licenses/lucene-memory-8.8.2.jar.sha1
  server/licenses/lucene-misc-8.7.0.jar.sha1
  server/licenses/lucene-misc-8.8.2.jar.sha1
  server/licenses/lucene-queries-8.7.0.jar.sha1
  server/licenses/lucene-queries-8.8.2.jar.sha1
  server/licenses/lucene-queryparser-8.7.0.jar.sha1
  server/licenses/lucene-queryparser-8.8.2.jar.sha1
  server/licenses/lucene-sandbox-8.7.0.jar.sha1
  server/licenses/lucene-sandbox-8.8.2.jar.sha1
  server/licenses/lucene-spatial-extras-8.7.0.jar.sha1
  server/licenses/lucene-spatial-extras-8.8.2.jar.sha1
  server/licenses/lucene-spatial3d-8.7.0.jar.sha1
  server/licenses/lucene-spatial3d-8.8.2.jar.sha1
  server/licenses/lucene-suggest-8.7.0.jar.sha1
  server/licenses/lucene-suggest-8.8.2.jar.sha1
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/index/codec/CodecService.java
  server/src/main/java/org/opensearch/index/codec/PerFieldMappingPostingFormatCodec.java
  server/src/main/java/org/opensearch/index/query/VectorGeoShapeQueryProcessor.java
  server/src/test/java/org/opensearch/index/codec/CodecTests.java
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: v1.0.0, v1.0.0-alpha1, v2.0.0

#613 Speedup snapshot stale indices delete
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java
Labels: enhancement, v1.0.0, v2.0.0

#611 Replace elastic.co with opensearch.org in opensearch.yml
  distribution/src/config/opensearch.yml
Labels: :sanitize

#595 [WIP] Developer guide updates
  DEVELOPER_GUIDE.md
Labels: documentation

#623 [1.x] Replace elastic.co with opensearch.org (#611)
  distribution/src/config/opensearch.yml
Labels: backport

#616 [1.x] Speedup snapshot stale indices delete (#613)
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java
Labels: backport, enhancement
