Repository opensearch-project/OpenSearch, pull requests merged in 2021-08, with the labels that each got.

#1057 Replace JCenter with Maven Central.
  buildSrc/build.gradle
  buildSrc/src/integTest/groovy/org/opensearch/gradle/OpenSearchTestBasePluginFuncTest.groovy
  buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java
  buildSrc/src/testKit/opensearch.build/build.gradle
  buildSrc/src/testKit/testingConventions/build.gradle
  buildSrc/src/testKit/thirdPartyAudit/build.gradle
Labels: v2.0.0

#971 Add support to generate code coverage report with JaCoCo
  build.gradle
  buildSrc/src/main/groovy/org/opensearch/gradle/BuildPlugin.groovy
  gradle/code-coverage.gradle
Labels: enhancement, CI, Delivery/Build, v2.0.0, feedback needed

#1070 Avoid crashing on using the index.lifecycle.name in the API body (#1060)
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: backport

#1051 Support for bwc tests for plugins
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
Labels: enhancement, v1.1.0

#1087 Backport fix for CVE 2021 22144 to 1.x
  libs/grok/src/main/java/org/opensearch/grok/Grok.java
  libs/grok/src/test/java/org/opensearch/grok/GrokTests.java
Labels: v1.1.0, v1.0.1

#1090 [Backport-1.x] Support for bwc tests for plugins (#1051)
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
Labels: enhancement, backport, backwards-compatibility, v1.1.0

#1105 Fix failure in SearchCancellationIT.testMSearchChildReqCancellationWi…
  server/src/internalClusterTest/java/org/opensearch/search/SearchCancellationIT.java
Labels: bug, >test-failure, v2.0.0, v1.1.0

#1073 [DEPRECATE] SimpleFS in favor of NIOFS
  distribution/tools/keystore-cli/src/test/java/org/opensearch/common/settings/KeyStoreWrapperTests.java
  plugins/store-smb/src/internalClusterTest/java/org/opensearch/index/store/SmbNIOFsTests.java
  plugins/store-smb/src/main/java/org/opensearch/index/store/smbniofs/SmbNIOFsDirectoryFactory.java
  plugins/store-smb/src/main/java/org/opensearch/index/store/smbsimplefs/SmbSimpleFsDirectoryFactory.java
  plugins/store-smb/src/main/java/org/opensearch/plugin/store/smb/SMBStorePlugin.java
  plugins/store-smb/src/test/java/org/opensearch/index/store/SmbNIOFSDirectoryTests.java
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/AllocationIdIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/common/settings/KeyStoreWrapper.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/gateway/MetadataStateFormat.java
  server/src/main/java/org/opensearch/gateway/PersistedClusterStateService.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/store/FsDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/index/translog/Checkpoint.java
  server/src/main/java/org/opensearch/indices/analysis/HunspellService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/gateway/MetadataStateFormatTests.java
  server/src/test/java/org/opensearch/gateway/PersistedClusterStateServiceTests.java
  server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
  server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
Labels: v1.1.0, deprecate

#1114 [1.x] Deprecate SimpleFS in favor of NIOFS (#1073)
  distribution/tools/keystore-cli/src/test/java/org/opensearch/common/settings/KeyStoreWrapperTests.java
  plugins/store-smb/src/internalClusterTest/java/org/opensearch/index/store/SmbNIOFsTests.java
  plugins/store-smb/src/main/java/org/opensearch/index/store/smbniofs/SmbNIOFsDirectoryFactory.java
  plugins/store-smb/src/main/java/org/opensearch/index/store/smbsimplefs/SmbSimpleFsDirectoryFactory.java
  plugins/store-smb/src/main/java/org/opensearch/plugin/store/smb/SMBStorePlugin.java
  plugins/store-smb/src/test/java/org/opensearch/index/store/SmbNIOFSDirectoryTests.java
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/AllocationIdIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/common/settings/KeyStoreWrapper.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/gateway/MetadataStateFormat.java
  server/src/main/java/org/opensearch/gateway/PersistedClusterStateService.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/store/FsDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/index/translog/Checkpoint.java
  server/src/main/java/org/opensearch/indices/analysis/HunspellService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/gateway/MetadataStateFormatTests.java
  server/src/test/java/org/opensearch/gateway/PersistedClusterStateServiceTests.java
  server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
  server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
Labels: backport, v1.1.0, deprecate

#1080 Upgrade to Lucene 8.9
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-8.8.2.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-8.9.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analyzers-icu-8.8.2.jar.sha1
  plugins/analysis-icu/licenses/lucene-analyzers-icu-8.9.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analyzers-kuromoji-8.8.2.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analyzers-kuromoji-8.9.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analyzers-nori-8.8.2.jar.sha1
  plugins/analysis-nori/licenses/lucene-analyzers-nori-8.9.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analyzers-phonetic-8.8.2.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analyzers-phonetic-8.9.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analyzers-smartcn-8.8.2.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analyzers-smartcn-8.9.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analyzers-stempel-8.8.2.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analyzers-stempel-8.9.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analyzers-morfologik-8.8.2.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analyzers-morfologik-8.9.0.jar.sha1
  server/licenses/lucene-analyzers-common-8.8.2.jar.sha1
  server/licenses/lucene-analyzers-common-8.9.0.jar.sha1
  server/licenses/lucene-backward-codecs-8.8.2.jar.sha1
  server/licenses/lucene-backward-codecs-8.9.0.jar.sha1
  server/licenses/lucene-core-8.8.2.jar.sha1
  server/licenses/lucene-core-8.9.0.jar.sha1
  server/licenses/lucene-grouping-8.8.2.jar.sha1
  server/licenses/lucene-grouping-8.9.0.jar.sha1
  server/licenses/lucene-highlighter-8.8.2.jar.sha1
  server/licenses/lucene-highlighter-8.9.0.jar.sha1
  server/licenses/lucene-join-8.8.2.jar.sha1
  server/licenses/lucene-join-8.9.0.jar.sha1
  server/licenses/lucene-memory-8.8.2.jar.sha1
  server/licenses/lucene-memory-8.9.0.jar.sha1
  server/licenses/lucene-misc-8.8.2.jar.sha1
  server/licenses/lucene-misc-8.9.0.jar.sha1
  server/licenses/lucene-queries-8.8.2.jar.sha1
  server/licenses/lucene-queries-8.9.0.jar.sha1
  server/licenses/lucene-queryparser-8.8.2.jar.sha1
  server/licenses/lucene-queryparser-8.9.0.jar.sha1
  server/licenses/lucene-sandbox-8.8.2.jar.sha1
  server/licenses/lucene-sandbox-8.9.0.jar.sha1
  server/licenses/lucene-spatial-extras-8.8.2.jar.sha1
  server/licenses/lucene-spatial-extras-8.9.0.jar.sha1
  server/licenses/lucene-spatial3d-8.8.2.jar.sha1
  server/licenses/lucene-spatial3d-8.9.0.jar.sha1
  server/licenses/lucene-suggest-8.8.2.jar.sha1
  server/licenses/lucene-suggest-8.9.0.jar.sha1
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: v1.1.0

#1115 [1.x] Upgrade to Lucene 8.9 (#1080)
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-8.8.2.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-8.9.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analyzers-icu-8.8.2.jar.sha1
  plugins/analysis-icu/licenses/lucene-analyzers-icu-8.9.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analyzers-kuromoji-8.8.2.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analyzers-kuromoji-8.9.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analyzers-nori-8.8.2.jar.sha1
  plugins/analysis-nori/licenses/lucene-analyzers-nori-8.9.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analyzers-phonetic-8.8.2.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analyzers-phonetic-8.9.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analyzers-smartcn-8.8.2.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analyzers-smartcn-8.9.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analyzers-stempel-8.8.2.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analyzers-stempel-8.9.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analyzers-morfologik-8.8.2.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analyzers-morfologik-8.9.0.jar.sha1
  server/licenses/lucene-analyzers-common-8.8.2.jar.sha1
  server/licenses/lucene-analyzers-common-8.9.0.jar.sha1
  server/licenses/lucene-backward-codecs-8.8.2.jar.sha1
  server/licenses/lucene-backward-codecs-8.9.0.jar.sha1
  server/licenses/lucene-core-8.8.2.jar.sha1
  server/licenses/lucene-core-8.9.0.jar.sha1
  server/licenses/lucene-grouping-8.8.2.jar.sha1
  server/licenses/lucene-grouping-8.9.0.jar.sha1
  server/licenses/lucene-highlighter-8.8.2.jar.sha1
  server/licenses/lucene-highlighter-8.9.0.jar.sha1
  server/licenses/lucene-join-8.8.2.jar.sha1
  server/licenses/lucene-join-8.9.0.jar.sha1
  server/licenses/lucene-memory-8.8.2.jar.sha1
  server/licenses/lucene-memory-8.9.0.jar.sha1
  server/licenses/lucene-misc-8.8.2.jar.sha1
  server/licenses/lucene-misc-8.9.0.jar.sha1
  server/licenses/lucene-queries-8.8.2.jar.sha1
  server/licenses/lucene-queries-8.9.0.jar.sha1
  server/licenses/lucene-queryparser-8.8.2.jar.sha1
  server/licenses/lucene-queryparser-8.9.0.jar.sha1
  server/licenses/lucene-sandbox-8.8.2.jar.sha1
  server/licenses/lucene-sandbox-8.9.0.jar.sha1
  server/licenses/lucene-spatial-extras-8.8.2.jar.sha1
  server/licenses/lucene-spatial-extras-8.9.0.jar.sha1
  server/licenses/lucene-spatial3d-8.8.2.jar.sha1
  server/licenses/lucene-spatial3d-8.9.0.jar.sha1
  server/licenses/lucene-suggest-8.8.2.jar.sha1
  server/licenses/lucene-suggest-8.9.0.jar.sha1
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: backport, v1.1.0, >upgrade

#1116 [Backport-1.x] Allowing custom folder name for plugin installation (#848)
  buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
  buildSrc/src/main/java/org/opensearch/gradle/plugin/PluginPropertiesExtension.java
  buildSrc/src/main/resources/plugin-descriptor.properties
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/ListPluginsCommand.java
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/PluginHelper.java
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/RemovePluginCommand.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/ListPluginsCommandTests.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/RemovePluginCommandTests.java
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
  server/src/main/java/org/opensearch/plugins/PluginsService.java
  server/src/test/java/org/opensearch/nodesinfo/NodeInfoStreamingTests.java
  server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
  server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
Labels: enhancement, backport, v1.1.0

#1139 [1.x] Include sources and javadoc artifacts while publishing to a Maven repository (#1049)
  buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
Labels: backport

#1151 Bump version to 1.0.1 revision
  .ci/bwcVersions
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
Labels: v1.0.1, >upgrade

#1170 Improve test run time for SnapshotResiliencyTests.testSnapshotPrimaryRelocations
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement

#1168 Reduce iterations to improve test run time for SearchServiceTests.testSearchWhileIndexDeleted
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
Labels: enhancement, backport

#1176 [Backport-1.x] Tune datanode count and shards count to improve test run time (#1170)
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, backport

#1177 [Backport-1.x] Reduce iterations to improve test run time (#1168)
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
Labels: enhancement, backport
