Repository opensearch-project/OpenSearch, pull requests merged in 2022-01, with the labels that each got.

#1807 Remove LegacyESVersion.V_6_7_x constants
  modules/reindex/src/main/java/org/opensearch/index/reindex/TransportUpdateByQueryAction.java
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  qa/translog-policy/src/test/java/org/opensearch/upgrades/TranslogPolicyIT.java
  server/src/main/java/org/opensearch/Build.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/put/PutMappingRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/ShardStats.java
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/cluster/ClusterState.java
  server/src/main/java/org/opensearch/cluster/action/shard/ShardStateAction.java
  server/src/main/java/org/opensearch/cluster/block/ClusterBlock.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/query/InnerHitBuilder.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTranslogOperationsRequest.java
  server/src/main/java/org/opensearch/search/SearchHit.java
  server/src/main/java/org/opensearch/search/aggregations/InternalAggregations.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/TopHitsAggregationBuilder.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/test/java/org/opensearch/BuildTests.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
  server/src/test/java/org/opensearch/LegacyESVersionTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
  server/src/test/java/org/opensearch/cluster/action/shard/ShardStateActionTests.java
  server/src/test/java/org/opensearch/cluster/block/ClusterBlockTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/indices/TermsLookupTests.java
Labels: v2.0.0, non-issue

#1786 Change whitesource integration to scan on 1.x branch
  .whitesource
  whitesource.config
Labels: backport 1.x

#1837 Update junit to 4.13.1
  buildSrc/src/testKit/opensearch.build/licenses/junit-4.12.jar.sha1
  buildSrc/src/testKit/opensearch.build/licenses/junit-4.13.2.jar.sha1
  buildSrc/version.properties
Labels: backport 1.x

#1835 [Backport 1.x] Netty upgrade 1.x
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.72.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.69.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.72.Final.jar.sha1
Labels: backport, >upgrade, backport 1.x

#1834 [Backport 1.x] Bouncycastle upgrade 1.x
  buildSrc/version.properties
  plugins/ingest-attachment/licenses/bcmail-jdk15on-1.64.jar.sha1
  plugins/ingest-attachment/licenses/bcmail-jdk15on-1.70.jar.sha1
  plugins/ingest-attachment/licenses/bcpkix-jdk15on-1.64.jar.sha1
  plugins/ingest-attachment/licenses/bcpkix-jdk15on-1.70.jar.sha1
  plugins/ingest-attachment/licenses/bcprov-jdk15on-1.64.jar.sha1
  plugins/ingest-attachment/licenses/bcprov-jdk15on-1.70.jar.sha1
Labels: backport, >upgrade, backport 1.x

#1849 Fixing typo in TESTING.md
  TESTING.md
Labels: backport 1.x

#1853 Update FIPS API libraries of Bouncy Castle
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/plugin-cli/licenses/bc-fips-1.0.2.1.jar.sha1
  distribution/tools/plugin-cli/licenses/bc-fips-1.0.2.jar.sha1
  distribution/tools/plugin-cli/licenses/bcpg-fips-1.0.4.jar.sha1
  distribution/tools/plugin-cli/licenses/bcpg-fips-1.0.5.1.jar.sha1
  gradle/fips.gradle
  test/fixtures/hdfs-fixture/build.gradle
Labels: v2.0.0, pending backport, CVE, >upgrade, v1.3.0, backport 1.x

#1757 [1.x] Remove remaining Flavor Serialization (#1751)
  server/src/main/java/org/opensearch/Build.java
Labels: non-issue, backwards-compatibility, v1.3.0, backport 1.x

#1869 Remove LegacyESVersion.V_6_8_x constants
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/transport/TransportHandshaker.java
  server/src/test/java/org/opensearch/LegacyESVersionTests.java
  server/src/test/java/org/opensearch/VersionTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/common/lucene/uid/VersionsTests.java
  server/src/test/java/org/opensearch/common/rounding/RoundingDuelTests.java
Labels: v2.0.0, non-issue

#1870 Remove deprecated search.remote settings
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartSettingsUpgradeIT.java
  server/src/internalClusterTest/java/org/opensearch/common/settings/UpgradeSettingsIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/transport/RemoteClusterAware.java
  server/src/main/java/org/opensearch/transport/RemoteClusterService.java
  server/src/main/java/org/opensearch/transport/SniffConnectionStrategy.java
  server/src/test/java/org/opensearch/transport/RemoteClusterSettingsTests.java
Labels: v2.0.0, non-issue

#1876 Use Version.compareMajor instead of using equals operator
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
Labels: bug, v2.0.0

#1877 Remove unwanted unreleased versions
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/VersionTests.java
Labels: bug, :test, backwards-compatibility

#1884 [Remove] Old Translog Checkpoint Format
  server/src/main/java/org/opensearch/index/translog/Checkpoint.java
  server/src/test/java/org/opensearch/index/translog/TranslogTests.java
  server/src/test/resources/org/opensearch/index/checkpoint/v1.ckp.binary
Labels: v2.0.0, non-issue, durability

#1889 [Backport 1.2] Upgrading bouncycastle to 1.70 (#1832)
  buildSrc/version.properties
  plugins/ingest-attachment/licenses/bcmail-jdk15on-1.64.jar.sha1
  plugins/ingest-attachment/licenses/bcmail-jdk15on-1.70.jar.sha1
  plugins/ingest-attachment/licenses/bcpkix-jdk15on-1.64.jar.sha1
  plugins/ingest-attachment/licenses/bcpkix-jdk15on-1.70.jar.sha1
  plugins/ingest-attachment/licenses/bcprov-jdk15on-1.64.jar.sha1
  plugins/ingest-attachment/licenses/bcprov-jdk15on-1.70.jar.sha1
Labels: backport, CVE, >upgrade, v1.2.4

#1886 [1.x] Update FIPS API libraries of Bouncy Castle (#1853)
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/plugin-cli/licenses/bc-fips-1.0.2.1.jar.sha1
  distribution/tools/plugin-cli/licenses/bc-fips-1.0.2.jar.sha1
  distribution/tools/plugin-cli/licenses/bcpg-fips-1.0.4.jar.sha1
  distribution/tools/plugin-cli/licenses/bcpg-fips-1.0.5.1.jar.sha1
  gradle/fips.gradle
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport, CVE, >upgrade, v1.3.0

#1890 [Backport 1.2] Upgrading Netty to 4.1.72-Final
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.72.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.69.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.72.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.69.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.72.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.69.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.72.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.69.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.72.Final.jar.sha1
Labels: backport, CVE, >upgrade, backport 1.2, v1.2.4

#1888 [1.2] Update FIPS API libraries of Bouncy Castle (#1853)
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/plugin-cli/licenses/bc-fips-1.0.2.1.jar.sha1
  distribution/tools/plugin-cli/licenses/bc-fips-1.0.2.jar.sha1
  distribution/tools/plugin-cli/licenses/bcpg-fips-1.0.4.jar.sha1
  distribution/tools/plugin-cli/licenses/bcpg-fips-1.0.5.1.jar.sha1
  gradle/fips.gradle
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport, CVE, >upgrade, v1.2.4

#1900 Attempt to fix o.o.transport.netty4.OpenSearchLoggingHandlerIT fails w/ stack overflow by hardening test expectation patterns
  modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/netty4/OpenSearchLoggingHandlerIT.java
Labels: :test, v2.0.0

#1911 [Backport] [1.x] [BUG] Serialization bugs can cause node drops (#1885)
  server/src/main/java/org/opensearch/transport/InboundHandler.java
  server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
Labels: bug, backport, v1.3.0, backport 1.x

#1913 Fixing org.opensearch.common.network.InetAddressesTests.testForStringIPv6WithScopeIdInput
  server/src/test/java/org/opensearch/common/network/InetAddressesTests.java
Labels: bug, :test, v2.0.0, pending backport

#1914 [Backport] [1.x] Fixing org.opensearch.common.network.InetAddressesTests.testForStringPv6WithScopeIdInput (#1913)
  server/src/test/java/org/opensearch/common/network/InetAddressesTests.java
Labels: :test, backport, v1.3.0

#1902 [BWC] Ensure 2.x compatibility with Legacy 7.10.x
  server/src/main/java/org/opensearch/transport/TransportHandshaker.java
  test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
Labels: :test, v2.0.0, backwards-compatibility

#1663 [1x] Backport Refactor LegacyESVersion tests from Version tests (#1662)
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/LegacyESVersionTests.java
  server/src/test/java/org/opensearch/VersionTests.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
  test/framework/src/test/java/org/opensearch/test/VersionUtilsTests.java
Labels: non-issue, backport, v1.3.0

#1915 [1.x] Make SortBuilders pluggable (#1856)
  server/src/internalClusterTest/java/org/opensearch/search/sort/SortFromPluginIT.java
  server/src/main/java/org/opensearch/plugins/SearchPlugin.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/SortBuilder.java
  server/src/main/java/org/opensearch/search/sort/SortParser.java
  server/src/test/java/org/opensearch/search/sort/SortBuilderTests.java
  server/src/test/java/org/opensearch/search/sort/plugin/CustomSortBuilder.java
  server/src/test/java/org/opensearch/search/sort/plugin/CustomSortPlugin.java
Labels: enhancement, Indexing & Search, v1.3.0

#1923 [Back port] Expand SearchPlugin javadocs. (#1909)
  server/src/main/java/org/opensearch/plugins/SearchPlugin.java
Labels: documentation, backport, Indexing & Search

#1903 Enforce soft deletes
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RecoveryIT.java
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.create/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/20_translog.yml
  server/src/internalClusterTest/java/org/opensearch/gateway/ReplicaShardAllocatorIT.java
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/state/OpenCloseIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SharedClusterSnapshotRestoreIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/replication/RecoveryDuringReplicationTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardRetentionLeaseTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
Labels: enhancement, v2.0.0

#1945 Update protobuf-java to 3.19.3
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/protobuf-java-3.11.3.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-3.19.3.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-util-3.11.3.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-util-3.19.3.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/protobuf-java-2.5.0.jar.sha1
  plugins/repository-hdfs/licenses/protobuf-java-3.19.3.jar.sha1
Labels: v2.0.0, CVE, >upgrade, v1.3.0, backport 1.x

#1445 Prioritize primary shard movement during shard allocation
  server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/routing/MovePrimaryFirstTests.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingNodeTests.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingNodesTests.java
Labels: enhancement, Indexing & Search, v1.3.0

#1949 [1.x] Update protobuf-java to 3.19.3 (#1945)
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/protobuf-java-3.11.3.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-3.19.3.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-util-3.11.3.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-util-3.19.3.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/protobuf-java-2.5.0.jar.sha1
  plugins/repository-hdfs/licenses/protobuf-java-3.19.3.jar.sha1
Labels: backport, CVE, >upgrade, v1.3.0

#1969 Add hook to execute custom logic before Integ test task starts
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/StandaloneRestIntegTestTask.java
Labels: backport 1.x

#1933 [Refactor] InternalEngine to always use soft deletes
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Labels: enhancement, v2.0.0, Indexing & Search

#1981 [Deprecate] index.merge.policy.max_merge_at_once_explicit
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/MergePolicyConfig.java
  server/src/main/java/org/opensearch/index/OpenSearchTieredMergePolicy.java
  server/src/test/java/org/opensearch/index/MergePolicySettingsTests.java
Labels: v2.0.0, non-issue, deprecate

#1978 [Deprecate] Setting explicit version on analysis component
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ArabicAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ArmenianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/BasqueAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/BengaliAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/BrazilianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/BulgarianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CatalanAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ChineseAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CjkAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CzechAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/DanishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/DutchAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/EnglishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/EstonianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/FinnishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/FrenchAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/GalicianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/GermanAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/GreekAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/HindiAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/HungarianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/IndonesianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/IrishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ItalianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/LatvianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/LithuanianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/NorwegianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/PersianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/PortugueseAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/RomanianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/RussianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SnowballAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SoraniAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SpanishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SwedishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ThaiAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/TurkishAnalyzerProvider.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/CompoundAnalysisTests.java
  plugins/analysis-stempel/src/main/java/org/opensearch/index/analysis/pl/PolishAnalyzerProvider.java
  plugins/analysis-ukrainian/src/main/java/org/opensearch/index/analysis/UkrainianAnalyzerProvider.java
  server/src/main/java/org/opensearch/index/analysis/AbstractIndexAnalyzerProvider.java
  server/src/main/java/org/opensearch/index/analysis/AbstractTokenFilterFactory.java
  server/src/main/java/org/opensearch/index/analysis/AbstractTokenizerFactory.java
  server/src/main/java/org/opensearch/index/analysis/Analysis.java
  server/src/main/java/org/opensearch/index/analysis/PreBuiltAnalyzerProviderFactory.java
  server/src/main/java/org/opensearch/index/analysis/SimpleAnalyzerProvider.java
  server/src/main/java/org/opensearch/index/analysis/StandardAnalyzerProvider.java
  server/src/main/java/org/opensearch/index/analysis/StopAnalyzerProvider.java
  server/src/main/java/org/opensearch/index/analysis/WhitespaceAnalyzerProvider.java
  server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
  server/src/test/resources/org/opensearch/index/analysis/test1.json
Labels: v2.0.0, non-issue, deprecate

#1761 [Remove] Deprecated Synced Flush API
  client/rest-high-level/src/main/java/org/opensearch/client/IndicesClient.java
  client/rest-high-level/src/main/java/org/opensearch/client/IndicesRequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/SyncedFlushResponse.java
  client/rest-high-level/src/test/java/org/opensearch/client/IndicesClientIT.java
  client/rest-high-level/src/test/java/org/opensearch/client/IndicesRequestConvertersTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/SyncedFlushResponseTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/documentation/IndicesClientDocumentationIT.java
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RecoveryIT.java
  qa/translog-policy/src/test/java/org/opensearch/upgrades/TranslogPolicyIT.java
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.flush_synced.json
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.flush/10_basic.yml
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/ShrinkIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/ReplicaShardAllocatorIT.java
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/flush/FlushIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/state/CloseIndexIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/indices/flush/SyncedFlushAction.java
  server/src/main/java/org/opensearch/action/admin/indices/flush/SyncedFlushRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/flush/SyncedFlushRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/indices/flush/SyncedFlushResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/flush/TransportShardFlushAction.java
  server/src/main/java/org/opensearch/action/admin/indices/flush/TransportSyncedFlushAction.java
  server/src/main/java/org/opensearch/client/IndicesAdminClient.java
  server/src/main/java/org/opensearch/client/Requests.java
  server/src/main/java/org/opensearch/client/support/AbstractClient.java
  server/src/main/java/org/opensearch/index/CompositeIndexEventListener.java
  server/src/main/java/org/opensearch/index/engine/CommitStats.java
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexEventListener.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/IndexingMemoryController.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/opensearch/indices/flush/ShardsSyncedFlushResult.java
  server/src/main/java/org/opensearch/indices/flush/SyncedFlushService.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestSyncedFlushAction.java
  server/src/test/java/org/opensearch/action/admin/indices/close/TransportVerifyShardBeforeCloseActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/flush/SyncedFlushUnitTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/engine/ReadOnlyEngineTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
  server/src/test/java/org/opensearch/indices/flush/SyncedFlushSingleNodeTests.java
  server/src/test/java/org/opensearch/indices/flush/SyncedFlushUtil.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/MockIndexEventListener.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: v2.0.0, non-issue, backwards-compatibility

#1982 Upgrading Jackson-Databind version
  buildSrc/build.gradle
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.12.5.jar.sha1
  client/sniffer/licenses/jackson-core-2.12.6.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.12.5.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.12.6.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.12.5.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.12.6.jar.sha1
  libs/x-content/licenses/jackson-core-2.12.5.jar.sha1
  libs/x-content/licenses/jackson-core-2.12.6.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.12.5.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.12.6.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.12.5.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.12.6.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.12.5.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.12.6.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.12.5.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.12.6.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.12.5.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.12.6.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.12.5.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.12.6.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.12.5.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.12.6.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.12.5.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.12.6.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.12.5.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.12.6.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.12.5.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.12.6.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.12.5.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.12.6.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.12.5.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.12.6.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.12.5.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.12.6.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.12.5.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.12.6.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.12.5.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.12.6.jar.sha1
Labels: v2.0.0, CVE, >upgrade, v1.3.0, backport 1.x

#1983 Added timeout to ensureGreen() for testClusterGreenAfterPartialRelocation
  server/src/test/java/org/opensearch/cluster/routing/MovePrimaryFirstTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: bug, :test, pending backport, backport 1.x

#2009 [Backport] [1.x] Update bundled JDK distribution to 17.0.2+8 (#2007)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport, v1.3.0

#2008 Fixing invalid Java code example in JavaDoc
  server/src/main/java/org/opensearch/common/settings/Setting.java
Labels: v2.0.0, javadocs, v1.3.0, backport 1.x

#1989 [Backport] Enabling Sort Optimization to make use of Lucene
  server/src/main/java/org/opensearch/search/query/QueryPhase.java
  server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
  test/framework/src/main/java/org/opensearch/test/TestSearchContext.java
Labels: enhancement, backport, Indexing & Search, v1.3.0
