Repository opensearch-project/OpenSearch, pull requests merged in 2022-05, with the labels that each got.

#3132 Sync maintainers with actual permissions. (#3127)
  MAINTAINERS.md
Labels: backport 2.0

#3116 Rename reserved node id '_must_join_elected_master_' to '_must_join_elected_cluster_manager_' that used by in DetachClusterCommand
  server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationMetadata.java
  server/src/main/java/org/opensearch/cluster/coordination/DetachClusterCommand.java
  server/src/test/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelperTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/CoordinationStateTestCluster.java
Labels: v3.0.0

#3138 [2.x] Deprecated reserved node id '_must_join_elected_master_' that used by DetachClusterCommand and replace with '_must_join_elected_cluster_manager_'
  server/src/main/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelper.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationMetadata.java
  server/src/main/java/org/opensearch/cluster/coordination/DetachClusterCommand.java
  server/src/test/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelperTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/CoordinationStateTestCluster.java
Labels: v2.0.0, v2.1.0, backport 2.x, backport 2.0

#3133 Rename ClusterBlock description 'no master' to 'no cluster-manager'
  server/src/internalClusterTest/java/org/opensearch/cluster/MinimumMasterNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/SpecificMasterNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/MasterDisruptionIT.java
  server/src/main/java/org/opensearch/cluster/coordination/NoMasterBlockService.java
  server/src/main/java/org/opensearch/discovery/SeedHostsProvider.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
  server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
  server/src/test/java/org/opensearch/cluster/ClusterStateTests.java
  test/framework/src/main/java/org/opensearch/action/support/replication/ClusterStateCreationUtils.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/RandomObjects.java
  test/framework/src/test/java/org/opensearch/test/test/InternalTestClusterTests.java
Labels: v2.1.0, backport 2.x

#3137 Fix Emeritus Table in MAINTAINERS.md
  MAINTAINERS.md
Labels: documentation, non-issue

#3139 [Remove] TypesExist Action
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesOptionsIntegrationIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/indices/exists/types/TransportTypesExistsAction.java
  server/src/main/java/org/opensearch/action/admin/indices/exists/types/TypesExistsAction.java
  server/src/main/java/org/opensearch/action/admin/indices/exists/types/TypesExistsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/exists/types/TypesExistsRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/indices/exists/types/TypesExistsResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/exists/types/package-info.java
  server/src/main/java/org/opensearch/client/IndicesAdminClient.java
  server/src/main/java/org/opensearch/client/support/AbstractClient.java
Labels: non-issue, v3.0.0, backport 2.x, backport 2.0

#3149 [Remove] AliasesExistAction
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/alias/ValidateIndicesAliasesRequestIT.java
  server/src/internalClusterTest/java/org/opensearch/aliases/IndexAliasesIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesOptionsIntegrationIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/exists/AliasesExistAction.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/exists/AliasesExistRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/exists/AliasesExistResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/exists/TransportAliasesExistAction.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/exists/package-info.java
  server/src/main/java/org/opensearch/client/IndicesAdminClient.java
  server/src/main/java/org/opensearch/client/support/AbstractClient.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  test/framework/src/main/java/org/opensearch/test/hamcrest/OpenSearchAssertions.java
Labels: non-issue, v3.0.0, backport 2.x, backport 2.0

#3163 [Javadocs] add to o.o.bootstrap, cli, and client
  build.gradle
  server/src/main/java/org/opensearch/bootstrap/Bootstrap.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapCheck.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapChecks.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapContext.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapException.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapInfo.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapSettings.java
  server/src/main/java/org/opensearch/bootstrap/ConsoleCtrlHandler.java
  server/src/main/java/org/opensearch/bootstrap/FilePermissionUtils.java
  server/src/main/java/org/opensearch/bootstrap/JNACLibrary.java
  server/src/main/java/org/opensearch/bootstrap/JNAKernel32Library.java
  server/src/main/java/org/opensearch/bootstrap/JNANatives.java
  server/src/main/java/org/opensearch/bootstrap/Natives.java
  server/src/main/java/org/opensearch/bootstrap/OpenSearch.java
  server/src/main/java/org/opensearch/bootstrap/OpenSearchPolicy.java
  server/src/main/java/org/opensearch/bootstrap/OpenSearchUncaughtExceptionHandler.java
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/main/java/org/opensearch/bootstrap/Spawner.java
  server/src/main/java/org/opensearch/bootstrap/StartupException.java
  server/src/main/java/org/opensearch/bootstrap/SystemCallFilter.java
  server/src/main/java/org/opensearch/cli/CommandLoggingConfigurator.java
  server/src/main/java/org/opensearch/cli/EnvironmentAwareCommand.java
  server/src/main/java/org/opensearch/cli/KeyStoreAwareCommand.java
  server/src/main/java/org/opensearch/cli/LoggingAwareCommand.java
  server/src/main/java/org/opensearch/cli/LoggingAwareMultiCommand.java
  server/src/main/java/org/opensearch/client/AdminClient.java
  server/src/main/java/org/opensearch/client/Client.java
  server/src/main/java/org/opensearch/client/ClusterAdminClient.java
  server/src/main/java/org/opensearch/client/FilterClient.java
  server/src/main/java/org/opensearch/client/IndicesAdminClient.java
  server/src/main/java/org/opensearch/client/OpenSearchClient.java
  server/src/main/java/org/opensearch/client/OriginSettingClient.java
  server/src/main/java/org/opensearch/client/ParentTaskAssigningClient.java
  server/src/main/java/org/opensearch/client/Requests.java
  server/src/main/java/org/opensearch/client/node/NodeClient.java
  server/src/main/java/org/opensearch/client/support/AbstractClient.java
  server/src/main/java/org/opensearch/client/transport/NoNodeAvailableException.java
Labels: documentation, non-issue, v3.0.0, backport 2.x, backport 2.0

#3171 [Backport 2.0][Javadocs] add to o.o.bootstrap, cli, and client (#3163)
  build.gradle
  server/src/main/java/org/opensearch/bootstrap/Bootstrap.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapCheck.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapChecks.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapContext.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapException.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapInfo.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapSettings.java
  server/src/main/java/org/opensearch/bootstrap/ConsoleCtrlHandler.java
  server/src/main/java/org/opensearch/bootstrap/FilePermissionUtils.java
  server/src/main/java/org/opensearch/bootstrap/JNACLibrary.java
  server/src/main/java/org/opensearch/bootstrap/JNAKernel32Library.java
  server/src/main/java/org/opensearch/bootstrap/JNANatives.java
  server/src/main/java/org/opensearch/bootstrap/Natives.java
  server/src/main/java/org/opensearch/bootstrap/OpenSearch.java
  server/src/main/java/org/opensearch/bootstrap/OpenSearchPolicy.java
  server/src/main/java/org/opensearch/bootstrap/OpenSearchUncaughtExceptionHandler.java
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/main/java/org/opensearch/bootstrap/Spawner.java
  server/src/main/java/org/opensearch/bootstrap/StartupException.java
  server/src/main/java/org/opensearch/bootstrap/SystemCallFilter.java
  server/src/main/java/org/opensearch/cli/CommandLoggingConfigurator.java
  server/src/main/java/org/opensearch/cli/EnvironmentAwareCommand.java
  server/src/main/java/org/opensearch/cli/KeyStoreAwareCommand.java
  server/src/main/java/org/opensearch/cli/LoggingAwareCommand.java
  server/src/main/java/org/opensearch/cli/LoggingAwareMultiCommand.java
  server/src/main/java/org/opensearch/client/AdminClient.java
  server/src/main/java/org/opensearch/client/Client.java
  server/src/main/java/org/opensearch/client/ClusterAdminClient.java
  server/src/main/java/org/opensearch/client/FilterClient.java
  server/src/main/java/org/opensearch/client/IndicesAdminClient.java
  server/src/main/java/org/opensearch/client/OpenSearchClient.java
  server/src/main/java/org/opensearch/client/OriginSettingClient.java
  server/src/main/java/org/opensearch/client/ParentTaskAssigningClient.java
  server/src/main/java/org/opensearch/client/Requests.java
  server/src/main/java/org/opensearch/client/node/NodeClient.java
  server/src/main/java/org/opensearch/client/support/AbstractClient.java
  server/src/main/java/org/opensearch/client/transport/NoNodeAvailableException.java
Labels: documentation, v2.0.0, non-issue, backport

#3169 [Remove] ShrinkAction, ShardUpgradeRequest, UpgradeSettingsRequestBuilder
  server/src/main/java/org/opensearch/action/admin/indices/shrink/ShrinkAction.java
  server/src/main/java/org/opensearch/action/admin/indices/upgrade/post/ShardUpgradeRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/upgrade/post/UpgradeSettingsRequestBuilder.java
Labels: non-issue, v3.0.0, backport 2.x, backport 2.0

#3196 [Remove] TypeFieldMapper
  server/src/main/java/org/opensearch/common/lucene/search/Queries.java
  server/src/main/java/org/opensearch/index/mapper/TypeFieldMapper.java
Labels: non-issue, Indexing & Search, v3.0.0, backport 2.x, backport 2.0

#3179 [2.x] Rename BecomeMasterTask to BecomeClusterManagerTask in JoinTaskExecutor (#3099)
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
Labels: v2.0.0, v2.1.0, backport 2.0

#3193 Fixing plugin installation URL to consume build qualifier
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
Labels: bug, Plugins, v2.1.0, v3.0.0, backport 2.x, backport 2.0

#3221 [2.x] Add bwc version 1.3.3
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: v2.1.0, backport 2.0

#3174 [2.0] Replace 'master' terminology with 'cluster manager' in log messages in 'server/src/main' directory - Part 2
  server/src/internalClusterTest/java/org/opensearch/discovery/SnapshotDisruptionIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/repositories/cleanup/TransportCleanupRepositoryAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/opensearch/action/support/master/TransportMasterNodeAction.java
  server/src/main/java/org/opensearch/cluster/ClusterStateTaskListener.java
  server/src/main/java/org/opensearch/cluster/action/index/NodeMappingRefreshAction.java
  server/src/main/java/org/opensearch/cluster/action/shard/ShardStateAction.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/coordination/LeaderChecker.java
  server/src/main/java/org/opensearch/cluster/coordination/NoMasterBlockService.java
  server/src/main/java/org/opensearch/cluster/coordination/NodeRemovalClusterStateTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/coordination/Reconfigurator.java
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/common/settings/ConsistentSettingsService.java
  server/src/main/java/org/opensearch/gateway/GatewayService.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/opensearch/repositories/fs/FsRepository.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
  server/src/test/java/org/opensearch/discovery/PeerFinderTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: v2.0.0

#3235 [2.0] Add bwc version 1.3.3
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: CI, v2.0.0

#3102 [Remote Segment Store] Add RemoteDirectory interface to copy segment files to/from remote store
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteIndexInput.java
  server/src/main/java/org/opensearch/index/store/RemoteIndexOutput.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/RemoteIndexOutputTests.java
Labels: durability

#3253 Fixing PublishTests tests (running against unclean build folders)
  buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
Labels: backport 2.x, backport 2.0

#3252 Allow to configure POM for ZIP publication
  buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
  buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
Labels: backport 2.x, backport 2.0

#3093 Update bundled JDK to 17.0.3+7
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport 2.x, backport 2.0

#3164 Bootstrap should implement a denylist of Java versions (ranges)
  server/src/main/java/org/opensearch/bootstrap/BootstrapChecks.java
  server/src/main/java/org/opensearch/bootstrap/jvm/DenyJvmVersionsParser.java
  server/src/main/resources/org/opensearch/bootstrap/jvm/deny-jvm-versions.txt
  server/src/test/java/org/opensearch/bootstrap/BootstrapChecksTests.java
  server/src/test/java/org/opensearch/bootstrap/jvm/DenyJvmVersionsParserTests.java
Labels: v2.1.0, v3.0.0, backport 2.x

#3284 [2.x] Replace internal usages of 'master' term in 'client' directory
  client/rest-high-level/src/main/java/org/opensearch/client/TimedRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComponentTemplatesRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComposableIndexTemplateRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexTemplatesRequest.java
  client/rest-high-level/src/test/java/org/opensearch/client/ClusterRequestConvertersTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/TimedRequestTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/indices/CloseIndexRequestTests.java
  client/rest/src/main/java/org/opensearch/client/Node.java
  client/rest/src/main/java/org/opensearch/client/NodeSelector.java
  client/rest/src/test/java/org/opensearch/client/NodeSelectorTests.java
  client/rest/src/test/java/org/opensearch/client/RestClientMultipleHostsTests.java
  client/rest/src/test/java/org/opensearch/client/documentation/RestClientDocumentation.java
  test/framework/src/test/java/org/opensearch/test/rest/yaml/section/ClientYamlTestSuiteTests.java
Labels: backport, v2.1.0

#3297 Update generated ANTLR lexer/parser to match runtime version
  modules/lang-painless/build.gradle
  modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessLexer.java
  modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java
Labels: backport 2.x, backport 2.0

#3324 Added Adoptium JDK8 support and updated DistroTestPlugin JDK version used by Gradle
  buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
  buildSrc/src/main/java/org/opensearch/gradle/JdkDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
Labels: backport 2.x, backport 2.0

#3327 [Backport 2.0] [Remove] TypeFieldMapper (#3196)
  server/src/main/java/org/opensearch/common/lucene/search/Queries.java
  server/src/main/java/org/opensearch/index/mapper/TypeFieldMapper.java
Labels: v2.0.0, Indexing & Search

#3330 Replace 'master' terminology with 'cluster manager' in 'qa' directory
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  qa/multi-cluster-search/build.gradle
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RecoveryIT.java
  qa/smoke-test-ingest-disabled/build.gradle
  qa/smoke-test-plugins/src/test/resources/rest-api-spec/test/smoke_test_plugins/10_basic.yml
Labels: v2.1.0, backport 2.x

#3328 Replace 'master' terminology with 'cluster manager' in 'modules' directory
  modules/aggs-matrix-stats/src/yamlRestTest/resources/rest-api-spec/test/stats/10_basic.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/10_basic.yml
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/10_basic.yml
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
  modules/ingest-geoip/src/main/java/org/opensearch/ingest/geoip/DatabaseReaderLazyLoader.java
  modules/ingest-geoip/src/yamlRestTest/resources/rest-api-spec/test/ingest_geoip/10_basic.yml
  modules/ingest-user-agent/src/yamlRestTest/resources/rest-api-spec/test/ingest-useragent/10_basic.yml
  modules/lang-expression/src/yamlRestTest/resources/rest-api-spec/test/lang_expression/10_basic.yml
  modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache/10_basic.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/10_basic.yml
  modules/mapper-extras/src/test/resources/org/opensearch/index/mapper/metricbeat-6.0.template.json
  modules/parent-join/src/internalClusterTest/java/org/opensearch/join/aggregations/ChildrenIT.java
  modules/reindex/src/test/java/org/opensearch/index/reindex/RetryTests.java
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/90_remote.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/95_parent_join.yml
  modules/repository-url/src/yamlRestTest/resources/rest-api-spec/test/repository_url/10_basic.yml
  modules/transport-netty4/src/yamlRestTest/resources/rest-api-spec/test/10_basic.yml
Labels: v2.1.0, backport 2.x

#3329 Replace 'master' terminology with 'cluster manager' in 'plugins' directory
  plugins/discovery-azure-classic/src/yamlRestTest/resources/rest-api-spec/test/discovery_azure_classic/10_basic.yml
  plugins/discovery-ec2/src/internalClusterTest/java/org/opensearch/discovery/ec2/Ec2DiscoveryUpdateSettingsTests.java
  plugins/discovery-ec2/src/yamlRestTest/resources/rest-api-spec/test/discovery_ec2/10_basic.yml
  plugins/discovery-gce/src/internalClusterTest/java/org/opensearch/discovery/gce/GceDiscoverTests.java
  plugins/discovery-gce/src/yamlRestTest/resources/rest-api-spec/test/discovery_gce/10_basic.yml
  plugins/examples/custom-significance-heuristic/src/yamlRestTest/resources/rest-api-spec/test/custom-significance-heuristic/10_basic.yml
  plugins/examples/custom-suggester/src/yamlRestTest/resources/rest-api-spec/test/custom-suggester/10_basic.yml
  plugins/examples/painless-whitelist/src/yamlRestTest/resources/rest-api-spec/test/painless_whitelist/10_basic.yml
  plugins/examples/rescore/src/yamlRestTest/resources/rest-api-spec/test/example-rescore/10_basic.yml
  plugins/examples/script-expert-scoring/src/yamlRestTest/resources/rest-api-spec/test/script_expert_scoring/10_basic.yml
  plugins/ingest-attachment/src/yamlRestTest/resources/rest-api-spec/test/ingest_attachment/10_basic.yml
  plugins/repository-azure/src/yamlRestTest/resources/rest-api-spec/test/repository_azure/10_basic.yml
  plugins/repository-gcs/src/yamlRestTest/resources/rest-api-spec/test/repository_gcs/10_basic.yml
  plugins/repository-hdfs/src/test/resources/rest-api-spec/test/hdfs_repository/10_basic.yml
  plugins/repository-hdfs/src/test/resources/rest-api-spec/test/secure_hdfs_repository/10_basic.yml
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/10_basic.yml
  plugins/store-smb/src/yamlRestTest/resources/rest-api-spec/test/store_smb/10_basic.yml
Labels: v2.1.0, backport 2.x

#3346 [Remove] Remove deprecated methods from JodaCompatibleZonedDateTime which are called by scripts
  modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.txt
  server/src/main/java/org/opensearch/script/JodaCompatibleZonedDateTime.java
  server/src/test/java/org/opensearch/script/JodaCompatibleZonedDateTimeTests.java
Labels: v2.0.0, >breaking, v3.0.0, backport 2.x, backport 2.0

#2825 [TEST] Add back necessary tests for deprecated settings that are replaced during applying inclusive naming
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
  server/src/test/java/org/opensearch/action/admin/cluster/configuration/AddVotingConfigExclusionsRequestTests.java
  server/src/test/java/org/opensearch/action/support/master/TransportMasterNodeActionTests.java
  server/src/test/java/org/opensearch/cluster/ClusterChangedEventTests.java
  server/src/test/java/org/opensearch/cluster/coordination/ClusterBootstrapServiceDeprecatedMasterTests.java
  server/src/test/java/org/opensearch/cluster/coordination/ClusterBootstrapServiceRenamedSettingTests.java
  server/src/test/java/org/opensearch/cluster/coordination/ClusterBootstrapServiceTests.java
  server/src/test/java/org/opensearch/cluster/coordination/ClusterFormationFailureHelperTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
Labels: :test, v2.1.0, backport 2.x

#3352 [REMOVE] Cleanup deprecated thread pool settings (AutoQueueAdjustingExecutorBuilder)
  server/src/main/java/org/opensearch/threadpool/AutoQueueAdjustingExecutorBuilder.java
  server/src/test/java/org/opensearch/threadpool/AutoQueueAdjustingExecutorBuilderTests.java
Labels: >breaking, v3.0.0

#3364 Removing hard coded value of max concurrent shard requests
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
Labels: bug, Indexing & Search, backport 2.x, backport 2.0

#3377 [Type removal] _type removal from mocked responses of scroll hit tests
  modules/reindex/src/test/resources/responses/failure_with_status.json
  modules/reindex/src/test/resources/responses/rejection.json
  modules/reindex/src/test/resources/responses/scroll_fully_loaded.json
  modules/reindex/src/test/resources/responses/scroll_fully_loaded_1_7.json
  modules/reindex/src/test/resources/responses/scroll_ok.json
  modules/reindex/src/test/resources/responses/start_ok.json
Labels: backport 2.x, backport 2.0

#3372 [Type removal] Remove _type from _bulk yaml test, scripts, unused constants
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/ForEachProcessorTests.java
  rest-api-spec/src/main/resources/rest-api-spec/test/bulk/60_deprecated.yml
  server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java
  server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsResponse.java
  server/src/main/java/org/opensearch/action/update/UpdateHelper.java
Labels: backport 2.x, backport 2.0

#3396 Fix Lucene-snapshots workflow to ensure gradle settings are created first.
  .github/workflows/lucene-snapshots.yml
Labels: CI, backport 2.x

#2521 Replace internal usages of 'master' term in 'server/src/internalClusterTest' directory
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/tasks/PendingTasksBlocksIT.java
  server/src/internalClusterTest/java/org/opensearch/action/support/master/IndexingClusterManagerFailoverIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterHealthIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterInfoServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterStateDiffIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/MinimumClusterManagerNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/NoClusterManagerNodeIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/SimpleClusterStateIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/action/shard/ShardStateActionIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/RareClusterStateIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/UnsafeBootstrapAndDetachCommandIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/VotingConfigurationIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/ZenDiscoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/AllocationIdIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/PrimaryAllocationIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/MockDiskUsagesIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/ClusterDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/SnapshotDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/StableClusterManagerDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/env/NodeEnvironmentIT.java
  server/src/internalClusterTest/java/org/opensearch/env/NodeRepurposeCommandIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/GatewayIndexStateIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/MetadataNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoverAfterNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/internalClusterTest/java/org/opensearch/index/mapper/DynamicMappingIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/mapping/DedicatedClusterManagerGetFieldMappingIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/mapping/UpdateMappingIntegrationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/state/CloseWhileRelocatingShardsIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/store/IndicesStoreIntegrationIT.java
  server/src/internalClusterTest/java/org/opensearch/ingest/IngestProcessorNotInstalledOnAllNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/persistent/PersistentTasksExecutorIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java
  server/src/internalClusterTest/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryCleanupIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/MetadataLoadingDuringSnapshotRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoryFilterUserMetadataIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotShardsServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
  server/src/internalClusterTest/java/org/opensearch/versioning/ConcurrentDocumentOperationIT.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, v2.1.0, backport 2.x

#3369 [REMOVE] Cleanup deprecated thread pool types (FIXED_AUTO_QUEUE_SIZE)
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
Labels: >breaking, v3.0.0

#3406 [Type removal] _type removal from tests of yaml tests
  test/framework/src/test/java/org/opensearch/test/rest/yaml/section/ClientYamlTestSuiteTests.java
  test/framework/src/test/java/org/opensearch/test/rest/yaml/section/DoSectionTests.java
  test/framework/src/test/resources/rest-api-spec/test/suite1/10_basic.yml
Labels: v2.1.0, backport 2.x

#3410 Add release notes for version 2.0.0
  release-notes/opensearch.release-notes-2.0.0.md
Labels: documentation, v2.0.0, backport 2.0

#3416 [Upgrade] Lucene-9.2.0-snapshot-ba8c3a8
  buildSrc/src/main/resources/forbidden/opensearch-test-signatures.txt
  buildSrc/version.properties
  libs/core/src/test/java/org/opensearch/core/internal/io/IOUtilsTests.java
  modules/lang-expression/licenses/lucene-expressions-9.2.0-snapshot-ba8c3a8.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-analysis-common-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-analysis-common-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-backward-codecs-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-backward-codecs-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-core-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-core-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-grouping-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-grouping-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-highlighter-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-highlighter-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-join-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-join-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-memory-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-memory-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-misc-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-misc-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-queries-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-queries-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-queryparser-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-queryparser-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-sandbox-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-sandbox-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-spatial-extras-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-spatial-extras-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-spatial3d-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-spatial3d-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-suggest-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-suggest-9.2.0-snapshot-f4f1f70.jar.sha1
  server/src/main/java/org/opensearch/common/lucene/Lucene.java
  server/src/main/java/org/opensearch/index/codec/CodecService.java
  server/src/main/java/org/opensearch/index/codec/PerFieldMappingPostingFormatCodec.java
  server/src/main/java/org/opensearch/index/fielddata/ordinals/GlobalOrdinalMapping.java
  server/src/main/java/org/opensearch/index/fielddata/ordinals/MultiOrdinals.java
  server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
  server/src/test/java/org/opensearch/index/codec/CodecTests.java
  server/src/test/java/org/opensearch/index/engine/CompletionStatsCacheTests.java
  server/src/test/java/org/opensearch/search/MultiValueModeTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/BinaryRangeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/MissingValuesTests.java
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: non-issue, >upgrade, v3.0.0, backport 2.x

#3418 Fix release notes for 2.0.0-rc1 version
  release-notes/opensearch.release-notes-2.0.0-rc1.md
  release-notes/opensearch.release-notes-2.0.0.md
Labels: documentation, backport 2.0

#3419 [Backport 2.x] [Upgrade] Lucene-9.2-snapshot (#2924)
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.1.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.1.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.1.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.1.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.1.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.1.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.1.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.1.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.2.0-snapshot-f4f1f70.jar.sha1
  sandbox/plugins/concurrent-search/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
  server/licenses/lucene-analysis-common-9.1.0.jar.sha1
  server/licenses/lucene-analysis-common-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-backward-codecs-9.1.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-core-9.1.0.jar.sha1
  server/licenses/lucene-core-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-grouping-9.1.0.jar.sha1
  server/licenses/lucene-grouping-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-highlighter-9.1.0.jar.sha1
  server/licenses/lucene-highlighter-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-join-9.1.0.jar.sha1
  server/licenses/lucene-join-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-memory-9.1.0.jar.sha1
  server/licenses/lucene-memory-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-misc-9.1.0.jar.sha1
  server/licenses/lucene-misc-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-queries-9.1.0.jar.sha1
  server/licenses/lucene-queries-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-queryparser-9.1.0.jar.sha1
  server/licenses/lucene-queryparser-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-sandbox-9.1.0.jar.sha1
  server/licenses/lucene-sandbox-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-spatial-extras-9.1.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-spatial3d-9.1.0.jar.sha1
  server/licenses/lucene-spatial3d-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-suggest-9.1.0.jar.sha1
  server/licenses/lucene-suggest-9.2.0-snapshot-f4f1f70.jar.sha1
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/common/lucene/uid/VersionsTests.java
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: non-issue, >upgrade, v2.1.0

#3422 [Backport 2.x] [Upgrade] Lucene-9.2.0-snapshot-ba8c3a8 (#3416)
  buildSrc/src/main/resources/forbidden/opensearch-test-signatures.txt
  buildSrc/version.properties
  libs/core/src/test/java/org/opensearch/core/internal/io/IOUtilsTests.java
  modules/lang-expression/licenses/lucene-expressions-9.2.0-snapshot-ba8c3a8.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-analysis-common-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-analysis-common-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-backward-codecs-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-backward-codecs-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-core-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-core-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-grouping-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-grouping-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-highlighter-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-highlighter-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-join-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-join-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-memory-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-memory-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-misc-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-misc-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-queries-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-queries-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-queryparser-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-queryparser-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-sandbox-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-sandbox-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-spatial-extras-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-spatial-extras-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-spatial3d-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-spatial3d-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-suggest-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-suggest-9.2.0-snapshot-f4f1f70.jar.sha1
  server/src/main/java/org/opensearch/common/lucene/Lucene.java
  server/src/main/java/org/opensearch/index/codec/CodecService.java
  server/src/main/java/org/opensearch/index/codec/PerFieldMappingPostingFormatCodec.java
  server/src/main/java/org/opensearch/index/fielddata/ordinals/GlobalOrdinalMapping.java
  server/src/main/java/org/opensearch/index/fielddata/ordinals/MultiOrdinals.java
  server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
  server/src/test/java/org/opensearch/index/codec/CodecTests.java
  server/src/test/java/org/opensearch/index/engine/CompletionStatsCacheTests.java
  server/src/test/java/org/opensearch/search/MultiValueModeTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/BinaryRangeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/MissingValuesTests.java
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: non-issue, >upgrade, v2.1.0

#3424 Bump version 2.1 to Lucene 9.2 after upgrade
  server/src/main/java/org/opensearch/Version.java
Labels: non-issue, >upgrade, v3.0.0

#3423 [Type removal] Remove type from BulkRequestParser
  server/src/main/java/org/opensearch/action/bulk/BulkRequest.java
  server/src/main/java/org/opensearch/action/bulk/BulkRequestParser.java
  server/src/test/java/org/opensearch/action/bulk/BulkRequestParserTests.java
Labels: backport 2.x

#3432 Rename master to cluster_manager in the XContent Parser of ClusterHealthResponse
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
  server/src/main/java/org/opensearch/cluster/health/ClusterStateHealth.java
  server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponsesTests.java
Labels: v2.1.0, backport 2.x

#3441 [TEST] Fix testSetAdditionalRolesCanAddDeprecatedMasterRole() by removing the initial assertion
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
Labels: :test, v2.1.0, backport 2.x

#3437 Removing unused method from TransportSearchAction
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
Labels: backport 2.x

#3119 Set term vector flags to false for ._index_prefix field (#1901).
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapper.java
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapperTests.java
Labels: enhancement, Indexing & Search, backport 2.x

#3448 [BUG] Fixing org.opensearch.monitor.os.OsProbeTests > testLogWarnCpuMessageOnlyOnes when cgroups are available but cgroup stats is not
  server/src/test/java/org/opensearch/monitor/os/OsProbeTests.java
Labels: backport 2.x, backport 2.0, backport 1.3

#3439 [Segment Replication] Add SegmentReplicationTargetService to orchestrate replication events.
  server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/TruncatedRecoveryIT.java
  server/src/main/java/org/opensearch/indices/recovery/FileChunkRequest.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryState.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RetryableTransportClient.java
  server/src/main/java/org/opensearch/indices/replication/CheckpointInfoResponse.java
  server/src/main/java/org/opensearch/indices/replication/GetSegmentFilesResponse.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceFactory.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationCollection.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationState.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
  server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Labels: enhancement, feature, Indexing & Search, v3.0.0

#3477 Update to Apache Lucene 9.2
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.2.0-snapshot-ba8c3a8.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.2.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.2.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.2.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.2.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.2.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.2.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.2.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.2.0.jar.sha1
  server/licenses/lucene-analysis-common-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-analysis-common-9.2.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-backward-codecs-9.2.0.jar.sha1
  server/licenses/lucene-core-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-core-9.2.0.jar.sha1
  server/licenses/lucene-grouping-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-grouping-9.2.0.jar.sha1
  server/licenses/lucene-highlighter-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-highlighter-9.2.0.jar.sha1
  server/licenses/lucene-join-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-join-9.2.0.jar.sha1
  server/licenses/lucene-memory-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-memory-9.2.0.jar.sha1
  server/licenses/lucene-misc-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-misc-9.2.0.jar.sha1
  server/licenses/lucene-queries-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-queries-9.2.0.jar.sha1
  server/licenses/lucene-queryparser-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-queryparser-9.2.0.jar.sha1
  server/licenses/lucene-sandbox-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-sandbox-9.2.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-spatial-extras-9.2.0.jar.sha1
  server/licenses/lucene-spatial3d-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-spatial3d-9.2.0.jar.sha1
  server/licenses/lucene-suggest-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-suggest-9.2.0.jar.sha1
Labels: non-issue, >upgrade, v3.0.0, backport 2.x

#3478 [Upgrade] Lucene-9.3.0-snapshot-823df23
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.2.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.2.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.2.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.2.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.2.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.2.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.2.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.2.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-analysis-common-9.2.0.jar.sha1
  server/licenses/lucene-analysis-common-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-backward-codecs-9.2.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-core-9.2.0.jar.sha1
  server/licenses/lucene-core-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-grouping-9.2.0.jar.sha1
  server/licenses/lucene-grouping-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-highlighter-9.2.0.jar.sha1
  server/licenses/lucene-highlighter-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-join-9.2.0.jar.sha1
  server/licenses/lucene-join-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-memory-9.2.0.jar.sha1
  server/licenses/lucene-memory-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-misc-9.2.0.jar.sha1
  server/licenses/lucene-misc-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-queries-9.2.0.jar.sha1
  server/licenses/lucene-queries-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-queryparser-9.2.0.jar.sha1
  server/licenses/lucene-queryparser-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-sandbox-9.2.0.jar.sha1
  server/licenses/lucene-sandbox-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-spatial-extras-9.2.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-spatial3d-9.2.0.jar.sha1
  server/licenses/lucene-spatial3d-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-suggest-9.2.0.jar.sha1
  server/licenses/lucene-suggest-9.3.0-snapshot-823df23.jar.sha1
  server/src/main/java/org/opensearch/Version.java
Labels: non-issue, >upgrade, v3.0.0, backport 2.x
