Repository opensearch-project/OpenSearch, pull requests merged in 2022-08, with the labels that each got.

#4051 Rename classes with name 'MasterService' to 'ClusterManagerService' in directory 'test/framework'
  server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
  server/src/test/java/org/opensearch/cluster/InternalClusterInfoServiceSchedulingTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
  test/framework/src/main/java/org/opensearch/cluster/service/FakeThreadPoolClusterManagerService.java
  test/framework/src/main/java/org/opensearch/test/disruption/BlockClusterManagerServiceOnClusterManager.java
  test/framework/src/main/java/org/opensearch/test/disruption/BusyClusterManagerServiceDisruption.java
  test/framework/src/test/java/org/opensearch/cluster/service/FakeThreadPoolClusterManagerServiceTests.java
Labels: enhancement, v3.0.0, backport 2.x, v2.2.0

#4058 Deprecate class FakeThreadPoolMasterService, BlockMasterServiceOnMaster and BusyMasterServiceDisruption, in 'test/framework' directory
  test/framework/src/main/java/org/opensearch/cluster/service/FakeThreadPoolMasterService.java
  test/framework/src/main/java/org/opensearch/test/disruption/BlockMasterServiceOnMaster.java
  test/framework/src/main/java/org/opensearch/test/disruption/BusyMasterServiceDisruption.java
Labels: enhancement, deprecate, v3.0.0, backport 2.x, v2.2.0

#4043 Update to Lucene 9.3.0
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.3.0-snapshot-b7231bb.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.3.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.3.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.3.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.3.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.3.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.3.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.3.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.3.0.jar.sha1
  server/licenses/lucene-analysis-common-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-analysis-common-9.3.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-backward-codecs-9.3.0.jar.sha1
  server/licenses/lucene-core-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-core-9.3.0.jar.sha1
  server/licenses/lucene-grouping-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-grouping-9.3.0.jar.sha1
  server/licenses/lucene-highlighter-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-highlighter-9.3.0.jar.sha1
  server/licenses/lucene-join-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-join-9.3.0.jar.sha1
  server/licenses/lucene-memory-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-memory-9.3.0.jar.sha1
  server/licenses/lucene-misc-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-misc-9.3.0.jar.sha1
  server/licenses/lucene-queries-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-queries-9.3.0.jar.sha1
  server/licenses/lucene-queryparser-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-queryparser-9.3.0.jar.sha1
  server/licenses/lucene-sandbox-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-sandbox-9.3.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-spatial-extras-9.3.0.jar.sha1
  server/licenses/lucene-spatial3d-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-spatial3d-9.3.0.jar.sha1
  server/licenses/lucene-suggest-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-suggest-9.3.0.jar.sha1
  server/src/main/java/org/opensearch/index/fielddata/ordinals/GlobalOrdinalMapping.java
  server/src/main/java/org/opensearch/index/fielddata/ordinals/MultiOrdinals.java
  server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/main/java/org/opensearch/search/query/TotalHitCountCollectorManager.java
  server/src/test/java/org/opensearch/search/MultiValueModeTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/BinaryRangeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/MissingValuesTests.java
Labels: dependencies, v3.0.0, backport 2.x, v2.2.0

#4054 Publish transport-netty4 module to Central Repository
  modules/transport-netty4/build.gradle
Labels: v3.0.0, backport 2.x, v2.2.0

#4079 Replace master terminology in documentation
  DEVELOPER_GUIDE.md
  TESTING.md
  rest-api-spec/src/main/resources/rest-api-spec/test/README.md
Labels: documentation, v3.0.0

#4088 [Backport] [2.x] Update to Lucene 9.3.0 (#4043)
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.3.0-snapshot-b7231bb.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.3.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.3.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.3.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.3.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.3.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.3.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.3.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.3.0.jar.sha1
  server/licenses/lucene-analysis-common-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-analysis-common-9.3.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-backward-codecs-9.3.0.jar.sha1
  server/licenses/lucene-core-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-core-9.3.0.jar.sha1
  server/licenses/lucene-grouping-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-grouping-9.3.0.jar.sha1
  server/licenses/lucene-highlighter-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-highlighter-9.3.0.jar.sha1
  server/licenses/lucene-join-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-join-9.3.0.jar.sha1
  server/licenses/lucene-memory-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-memory-9.3.0.jar.sha1
  server/licenses/lucene-misc-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-misc-9.3.0.jar.sha1
  server/licenses/lucene-queries-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-queries-9.3.0.jar.sha1
  server/licenses/lucene-queryparser-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-queryparser-9.3.0.jar.sha1
  server/licenses/lucene-sandbox-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-sandbox-9.3.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-spatial-extras-9.3.0.jar.sha1
  server/licenses/lucene-spatial3d-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-spatial3d-9.3.0.jar.sha1
  server/licenses/lucene-suggest-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-suggest-9.3.0.jar.sha1
  server/src/main/java/org/opensearch/index/fielddata/ordinals/GlobalOrdinalMapping.java
  server/src/main/java/org/opensearch/index/fielddata/ordinals/MultiOrdinals.java
  server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/main/java/org/opensearch/search/query/TotalHitCountCollectorManager.java
  server/src/test/java/org/opensearch/search/MultiValueModeTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/BinaryRangeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/MissingValuesTests.java
Labels: backport, v2.2.0

#4091 OpenJDK Update (July 2022 Patch releases)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: security, dependencies, backport 1.3

#4023 OpenJDK Update (July 2022 Patch releases)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: security, dependencies, backport 2.x, backport 2.0, backport 2.1

#4077 Correctly ignore depandabot branches during push
  .github/workflows/gradle-check.yml
Labels: bug, CI, cicd, backport 1.x, backport 2.x, backport 2.0, backport 1.3, backport 2.1

#4103 Fix the bug that masterOperation(with task param) is bypassed
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/info/TransportClusterInfoAction.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
  test/framework/src/main/java/org/opensearch/test/TestCluster.java
Labels: bug, backwards-compatibility, v3.0.0, backport 2.x, v2.2.0, backport 2.2

#4121 Deprecate and rename abstract methods in interfaces that contain 'master' in name
  server/src/main/java/org/opensearch/cluster/LocalNodeClusterManagerListener.java
  server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
  server/src/main/java/org/opensearch/cluster/ack/AckedRequest.java
  server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
Labels: enhancement, deprecate, v3.0.0, backport 2.x, v2.2.0, backport 2.2

#4097 [Backport] [1.3] OpenJDK Update (July 2022 Patch releases)
  buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
  buildSrc/src/main/java/org/opensearch/gradle/JdkDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport

#2293 Task consumer Integration
  distribution/docker/src/docker/config/log4j2.properties
  distribution/src/config/log4j2.properties
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/ImportLog4jPropertiesTaskTests.java
  distribution/tools/upgrade-cli/src/test/resources/config/log4j2.properties
  server/src/main/java/org/opensearch/action/search/SearchShardTask.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
  server/src/main/java/org/opensearch/search/query/QuerySearchRequest.java
  server/src/main/java/org/opensearch/tasks/TaskManager.java
  server/src/main/java/org/opensearch/tasks/consumer/SearchShardTaskDetailsLogMessage.java
  server/src/main/java/org/opensearch/tasks/consumer/TopNSearchTasksLogger.java
  server/src/main/java/org/opensearch/tasks/consumer/package-info.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/TaskManagerTestCase.java
  server/src/test/java/org/opensearch/index/IndexingSlowLogTests.java
  server/src/test/java/org/opensearch/index/SearchSlowLogTests.java
  server/src/test/java/org/opensearch/tasks/consumer/SearchShardTaskDetailsLogMessageTests.java
  server/src/test/java/org/opensearch/tasks/consumer/TopNSearchTasksLoggerTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/test/transport/MockTransportService.java
Labels: backport 2.x, v2.2.0, backport 2.2

#4145 [Backport 2.2] OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: backport

#4146 [Backport 2.1] OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: backport

#4147 [Backport 1.x] OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: backport

#4148 [Backport 1.3] OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: backport

#4149 [Backport 2.0] OpenSearch crashes on closed client connection before search reply when total ops higher compared to expected
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: backport

#4150 [Bug]: gradle check failing with java heap OutOfMemoryError
  gradle.properties
Labels: backport 1.x, backport 2.x, backport 2.0, backport 1.3, backport 2.1, backport 2.2

#3992 Refactored the GeoBoundsAggregation code from server folder to geo module.
  client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java
  modules/geo/build.gradle
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/GeoModulePluginIntegTestCase.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/MissingValueIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/AbstractGeoAggregatorTestCaseModulePlugin.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsIT.java
  modules/geo/src/main/java/org/opensearch/geo/GeoModulePlugin.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/AbstractGeoBoundsAggregator.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBounds.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregationBuilder.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregator.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregatorFactory.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/InternalGeoBounds.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/ParsedGeoBounds.java
  modules/geo/src/test/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregationBuilderTests.java
  modules/geo/src/test/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregatorTests.java
  modules/geo/src/test/java/org/opensearch/geo/search/aggregations/metrics/InternalGeoBoundsTests.java
  modules/geo/src/test/java/org/opensearch/geo/tests/common/AggregationBuilders.java
  modules/geo/src/test/java/org/opensearch/geo/tests/common/AggregationInspectionHelper.java
  modules/geo/src/test/java/org/opensearch/geo/tests/common/RandomGeoGenerator.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/MissingValueIT.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationBuilders.java
  server/src/main/java/org/opensearch/search/aggregations/support/AggregationInspectionHelper.java
  server/src/test/java/org/opensearch/search/aggregations/AggregationsTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/GeoBoundsTests.java
  test/framework/src/main/java/org/opensearch/test/InternalAggregationTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: Plugins, Aggregations, Geospatial, v2.5.0

#4181 [Backport 2.x] [Segment Replication] Backport PR's : #3525 #3533 #3540 #3943 #3963 From main branch
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/RunUnderPrimaryPermit.java
  server/src/main/java/org/opensearch/indices/recovery/FileChunkWriter.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTargetHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RetryableTransportClient.java
  server/src/main/java/org/opensearch/indices/replication/GetSegmentFilesRequest.java
  server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
  server/src/main/java/org/opensearch/indices/replication/RemoteSegmentFileChunkWriter.java
  server/src/main/java/org/opensearch/indices/replication/SegmentFileTransferHandler.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/SegmentReplicationCheckpointPublisher.java
  server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationCollection.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationFailedException.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/common/SegmentReplicationTransportRequest.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
  server/src/test/java/org/opensearch/index/store/StoreTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentFileTransferHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
  server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
Labels: feature, backport, distributed framework, v2.3.0

#4211 Update Gradle to 7.5.1
  gradle/wrapper/gradle-wrapper.properties
Labels: Build Libraries & Interfaces, backport 2.x, backport 2.2

#4208 [Backport] [1.x] [Bug]: gradle check failing with java heap OutOfMemoryError (#4150)
  gradle.properties
Labels: backport

#4179 [Backport 2.x] Refactors the GeoBoundsAggregation for geo_point types from the core server to the geo module (#3992)
  client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java
  modules/geo/build.gradle
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/GeoModulePluginIntegTestCase.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/MissingValueIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/AbstractGeoAggregatorTestCaseModulePlugin.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsIT.java
  modules/geo/src/main/java/org/opensearch/geo/GeoModulePlugin.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/AbstractGeoBoundsAggregator.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBounds.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregationBuilder.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregator.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregatorFactory.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/InternalGeoBounds.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/ParsedGeoBounds.java
  modules/geo/src/test/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregationBuilderTests.java
  modules/geo/src/test/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregatorTests.java
  modules/geo/src/test/java/org/opensearch/geo/search/aggregations/metrics/InternalGeoBoundsTests.java
  modules/geo/src/test/java/org/opensearch/geo/tests/common/AggregationBuilders.java
  modules/geo/src/test/java/org/opensearch/geo/tests/common/AggregationInspectionHelper.java
  modules/geo/src/test/java/org/opensearch/geo/tests/common/RandomGeoGenerator.java
  modules/percolator/src/internalClusterTest/java/org/opensearch/percolator/PercolatorQuerySearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/MissingValueIT.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationBuilders.java
  server/src/main/java/org/opensearch/search/aggregations/support/AggregationInspectionHelper.java
  server/src/test/java/org/opensearch/search/aggregations/AggregationsTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/GeoBoundsTests.java
  test/framework/src/main/java/org/opensearch/test/InternalAggregationTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: Plugins, Aggregations, Geospatial, v2.3.0

#4183 [Upgrade] to lucene-9.4.0-snapshot-ddf0d0a
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.3.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.4.0-snapshot-ddf0d0a.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.3.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.4.0-snapshot-ddf0d0a.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.3.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.4.0-snapshot-ddf0d0a.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.3.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.4.0-snapshot-ddf0d0a.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.3.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.4.0-snapshot-ddf0d0a.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.3.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.4.0-snapshot-ddf0d0a.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.3.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.4.0-snapshot-ddf0d0a.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.3.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-analysis-common-9.3.0.jar.sha1
  server/licenses/lucene-analysis-common-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-backward-codecs-9.3.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-core-9.3.0.jar.sha1
  server/licenses/lucene-core-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-grouping-9.3.0.jar.sha1
  server/licenses/lucene-grouping-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-highlighter-9.3.0.jar.sha1
  server/licenses/lucene-highlighter-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-join-9.3.0.jar.sha1
  server/licenses/lucene-join-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-memory-9.3.0.jar.sha1
  server/licenses/lucene-memory-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-misc-9.3.0.jar.sha1
  server/licenses/lucene-misc-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-queries-9.3.0.jar.sha1
  server/licenses/lucene-queries-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-queryparser-9.3.0.jar.sha1
  server/licenses/lucene-queryparser-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-sandbox-9.3.0.jar.sha1
  server/licenses/lucene-sandbox-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-spatial-extras-9.3.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-spatial3d-9.3.0.jar.sha1
  server/licenses/lucene-spatial3d-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/licenses/lucene-suggest-9.3.0.jar.sha1
  server/licenses/lucene-suggest-9.4.0-snapshot-ddf0d0a.jar.sha1
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/common/lucene/Lucene.java
  server/src/main/java/org/opensearch/index/codec/CodecService.java
  server/src/main/java/org/opensearch/index/codec/PerFieldMappingPostingFormatCodec.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/BytesRefFieldComparatorSource.java
  server/src/test/java/org/opensearch/index/codec/CodecTests.java
  server/src/test/java/org/opensearch/index/engine/CompletionStatsCacheTests.java
Labels: non-issue, >upgrade, v3.0.0

#4209 [Backport] [1.3] [Bug]: gradle check failing with java heap OutOfMemoryError (#4150)
  gradle.properties
Labels: backport

#4226 [MUTE] search with uppercase regex in bwc testing
  rest-api-spec/src/main/resources/rest-api-spec/test/search/190_index_prefix_search.yml
Labels: :test, CI

#4246 Handles the status code for `.` properties
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
Labels: bug, security, backport 1.x, backport 2.x, backport 1.3, backport 2.2

#4258 Fixing NodeGatewayStartedShards bwc (de)serialization issues
  modules/repository-s3/licenses/commons-logging-1.2.jar.sha1
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
Labels: >test-failure, backwards-compatibility

#4085 Add workflow for changelog verification
  .github/pull_request_template.md
  .github/workflows/changelog_verifier.yml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: CI, v3.0.0

#4133 Do not fail replica shard due to primary closure
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/main/java/org/opensearch/action/support/replication/PendingReplicationActions.java
  server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java
  server/src/main/java/org/opensearch/index/shard/PrimaryShardClosedException.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
  server/src/test/java/org/opensearch/action/support/replication/PendingReplicationActionsTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionTests.java
Labels: backport 2.x

#4308 Some dependency updates
  CHANGELOG.md
  buildSrc/version.properties
  client/rest/licenses/commons-codec-1.13.jar.sha1
  client/rest/licenses/commons-codec-1.15.jar.sha1
  client/rest/licenses/httpasyncclient-4.1.4.jar.sha1
  client/rest/licenses/httpasyncclient-4.1.5.jar.sha1
  client/rest/licenses/httpcore-4.4.12.jar.sha1
  client/rest/licenses/httpcore-4.4.15.jar.sha1
  client/rest/licenses/httpcore-nio-4.4.12.jar.sha1
  client/rest/licenses/httpcore-nio-4.4.15.jar.sha1
  client/sniffer/licenses/commons-codec-1.13.jar.sha1
  client/sniffer/licenses/commons-codec-1.15.jar.sha1
  client/sniffer/licenses/httpcore-4.4.12.jar.sha1
  client/sniffer/licenses/httpcore-4.4.15.jar.sha1
  plugins/analysis-phonetic/licenses/commons-codec-1.13.jar.sha1
  plugins/analysis-phonetic/licenses/commons-codec-1.15.jar.sha1
  plugins/discovery-azure-classic/licenses/commons-codec-1.13.jar.sha1
  plugins/discovery-azure-classic/licenses/commons-codec-1.15.jar.sha1
  plugins/discovery-azure-classic/licenses/httpcore-4.4.12.jar.sha1
  plugins/discovery-azure-classic/licenses/httpcore-4.4.15.jar.sha1
  plugins/discovery-ec2/licenses/commons-codec-1.13.jar.sha1
  plugins/discovery-ec2/licenses/commons-codec-1.15.jar.sha1
  plugins/discovery-ec2/licenses/httpcore-4.4.12.jar.sha1
  plugins/discovery-ec2/licenses/httpcore-4.4.15.jar.sha1
  plugins/discovery-gce/licenses/commons-codec-1.13.jar.sha1
  plugins/discovery-gce/licenses/commons-codec-1.15.jar.sha1
  plugins/discovery-gce/licenses/httpcore-4.4.12.jar.sha1
  plugins/discovery-gce/licenses/httpcore-4.4.15.jar.sha1
  plugins/ingest-attachment/licenses/commons-codec-1.13.jar.sha1
  plugins/ingest-attachment/licenses/commons-codec-1.15.jar.sha1
  plugins/ingest-attachment/licenses/slf4j-api-1.6.2.jar.sha1
  plugins/ingest-attachment/licenses/slf4j-api-1.7.36.jar.sha1
  plugins/repository-azure/licenses/slf4j-api-1.6.2.jar.sha1
  plugins/repository-azure/licenses/slf4j-api-1.7.36.jar.sha1
  plugins/repository-gcs/licenses/commons-codec-1.13.jar.sha1
  plugins/repository-gcs/licenses/commons-codec-1.15.jar.sha1
  plugins/repository-hdfs/licenses/commons-codec-1.13.jar.sha1
  plugins/repository-hdfs/licenses/commons-codec-1.15.jar.sha1
  plugins/repository-hdfs/licenses/slf4j-api-1.6.2.jar.sha1
  plugins/repository-hdfs/licenses/slf4j-api-1.7.36.jar.sha1
  plugins/repository-s3/licenses/commons-codec-1.13.jar.sha1
  plugins/repository-s3/licenses/commons-codec-1.15.jar.sha1
  plugins/repository-s3/licenses/httpcore-4.4.12.jar.sha1
  plugins/repository-s3/licenses/httpcore-4.4.15.jar.sha1
Labels: >upgrade, dependencies, v3.0.0, backport 2.x

#4307 Restore using the class ClusterInfoRequest and ClusterInfoRequestBuilder from package 'org.opensearch.action.support.master.info' for subclasses
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/get/GetMappingsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/get/GetMappingsRequestBuilder.java
  server/src/test/java/org/opensearch/action/admin/indices/get/GetIndexRequestTests.java
Labels: bug, backwards-compatibility, v3.0.0, backport 2.x, v2.3.0, backport 2.2

#4156 Use the project.group value for Zip POM groupId value
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
  buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
  buildSrc/src/test/resources/pluginzip/customizedGroupValue.gradle
  buildSrc/src/test/resources/pluginzip/customizedInvalidGroupValue.gradle
  buildSrc/src/test/resources/pluginzip/groupAndVersionValue.gradle
  buildSrc/src/test/resources/pluginzip/missingGroupValue.gradle
  buildSrc/src/test/resources/pluginzip/missingPOMEntity.gradle
Labels: backport 2.x

#4324 [2.x] Restore using the class ClusterInfoRequest and ClusterInfoRequestBuilder from package 'org.opensearch.action.support.master.info' for subclasses (#4307)
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/get/GetMappingsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/get/GetMappingsRequestBuilder.java
  server/src/test/java/org/opensearch/action/admin/indices/get/GetIndexRequestTests.java
Labels: bug, backport, backwards-compatibility, backport 2.2

#4342 Adding @dreamer-89 to Opensearch maintainers.
  CHANGELOG.md
  MAINTAINERS.md
Labels: backport 2.x

#4341 [CVE] Update snakeyaml dependency
  CHANGELOG.md
  buildSrc/version.properties
  libs/x-content/licenses/snakeyaml-1.26.jar.sha1
  libs/x-content/licenses/snakeyaml-1.31.jar.sha1
Labels: CVE, >upgrade, dependencies, v3.0.0, backport 2.x

#4331 Fixed commit workflow for dependabot PR helper
  .github/workflows/changelog_verifier.yml
  CHANGELOG.md
Labels: backport 1.x, backport 2.x

#4343 Add release notes for patch release 1.3.5
  CHANGELOG.md
  release-notes/opensearch.release-notes-1.3.5.md
Labels: documentation, backport 1.3

#4344 Add release notes for patch release 2.2.1
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.2.1.md
Labels: documentation, backport 2.2
