Repository opensearch-project/OpenSearch, pull requests merged in 2022-09, with the labels that each got.

#4359 Update to Netty 4.1.80.Final
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http2-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.80.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.80.Final.jar.sha1
Labels: backport 1.x, dependencies, backport 2.x, backport 2.0, backport 1.3, backport 2.1, backport 2.2

#4352 Fix randomized test failure `NRTReplicationEngineTests.testUpdateSegments`
  CHANGELOG.md
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Labels: bug, Flakey Random Test Failure, backport 2.x

#4378 [Backport] [1.x] Update to Netty 4.1.80.Final (#4359)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.80.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.80.Final.jar.sha1
Labels: backport

#4375 [Backport] [2.2] Update to Netty 4.1.80.Final (#4359)
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.80.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.80.Final.jar.sha1
Labels: backport

#4376 [Backport] [2.1] Update to Netty 4.1.80.Final (#4359)
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.80.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.80.Final.jar.sha1
Labels: backport

#4374 [Backport] [2.x] Update to Netty 4.1.80.Final (#4359)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.80.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.80.Final.jar.sha1
Labels: backport

#4377 [Backport] [2.0] Update to Netty 4.1.80.Final (#4359)
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.80.Final.jar.sha1
  modules/transport-netty4/src/javaRestTest/java/org/opensearch/rest/Netty4BadRequestIT.java
  plugins/repository-azure/licenses/netty-codec-dns-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.73.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.80.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.80.Final.jar.sha1
Labels: backport

#4379 [Backport] [1.3] Update to Netty 4.1.80.Final (#4359)
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.80.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.80.Final.jar.sha1
Labels: backport

#4428 Revert to Netty 4.1.79.Final
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http2-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.80.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.80.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.80.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.80.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.80.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.80.Final.jar.sha1
Labels: backport 1.x, backport 2.x, backport 2.0, backport 1.3, backport 2.1, backport 2.2

#4445 [Backport] [2.1] [Bug]: gradle check failing with java heap OutOfMemoryError (#4328)
  build.gradle
  server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java
  server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java
Labels: backport

#4362 Bugfix: Allow opensearch.bat file and opensearch-env.bat files to run when install path includes a space.
  CHANGELOG.md
  distribution/src/bin/opensearch-cli.bat
  distribution/src/bin/opensearch-env.bat
  distribution/src/bin/opensearch-service.bat
  distribution/src/bin/opensearch.bat
Labels: bug, backport 1.x, backport 2.x, backport 2.0, backport 1.3, backport 2.1, backport 2.2

#4442 [Backport] [2.x] [Bug]: gradle check failing with java heap OutOfMemoryError (#4328)
  CHANGELOG.md
  build.gradle
  server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java
  server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java
Labels: backport

#4444 [Backport] [2.2] [Bug]: gradle check failing with java heap OutOfMemoryError (#4328)
  build.gradle
  server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java
  server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java
Labels: backport

#4443 [Backport] [2.0] [Bug]: gradle check failing with java heap OutOfMemoryError (#4328)
  build.gradle
  server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java
  server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java
Labels: backport

#4452 Add bwcVersion 1.3.6 to 2.x
  .ci/bwcVersions
  CHANGELOG.md
  server/src/main/java/org/opensearch/Version.java
Labels: backport 2.0, backport 2.1, backport 2.2

#4469 Getting security exception due to access denied 'java.lang.RuntimePermission' 'accessDeclaredMembers' when trying to get snapshot with S3 IRSA
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
Labels: bug, v3.0.0, backport 2.x, backport 2.1, backport 2.2, backport 2.3

#4476 Backport CODEOWNERS and dependabot.yml files
  .github/CODEOWNERS
  .github/dependabot.yml
  CHANGELOG.md
Labels: backport 1.2, backport 1.3, backport 1.0, backport 1.1

#4494 Ignore all malformed objects when ignore_malformed is true
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/FieldMapper.java
Labels: enhancement, v3.0.0, backport 2.x

#4520 [Backport] [2.x] Getting security exception due to access denied 'java.lang.RuntimePermission' 'accessDeclaredMembers' when trying to get snapshot with S3 IRSA (#4469)
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
Labels: backport

#4521 [Backport] [2.3] Getting security exception due to access denied 'java.lang.RuntimePermission' 'accessDeclaredMembers' when trying to get snapshot with S3 IRSA (#4469)
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
Labels: backport

#4523 [Backport] [2.1] Getting security exception due to access denied 'java.lang.RuntimePermission' 'accessDeclaredMembers' when trying to get snapshot with S3 IRSA (#4469)
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
Labels: backport

#4522 [Backport] [2.2] Getting security exception due to access denied 'java.lang.RuntimePermission' 'accessDeclaredMembers' when trying to get snapshot with S3 IRSA (#4469)
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
Labels: backport

#4266 Added GeoBounds aggregation on GeoShape field type.(#3980)
  CHANGELOG.md
  libs/geo/src/main/java/org/opensearch/geometry/GeometryCollection.java
  modules/geo/build.gradle
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/GeoModulePluginIntegTestCase.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/MissingValueIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/common/GeoBoundsHelper.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/AbstractGeoAggregatorModulePluginTestCase.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsITTestCase.java
  modules/geo/src/main/java/org/opensearch/geo/GeoModulePlugin.java
  modules/geo/src/main/java/org/opensearch/geo/algorithm/PolygonGenerator.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsGeoShapeAggregator.java
  modules/geo/src/test/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsGeoShapeAggregatorTests.java
  modules/geo/src/test/java/org/opensearch/geo/tests/common/RandomGeoGeometryGenerator.java
  server/src/main/java/org/opensearch/common/geo/GeoShapeDocValue.java
  server/src/main/java/org/opensearch/common/geo/ShapeDocValue.java
  server/src/main/java/org/opensearch/common/util/CollectionUtils.java
  server/src/main/java/org/opensearch/index/fielddata/FieldData.java
  server/src/main/java/org/opensearch/index/fielddata/GeoShapeValue.java
  server/src/main/java/org/opensearch/index/fielddata/LeafGeoShapeFieldData.java
  server/src/main/java/org/opensearch/index/fielddata/plain/AbstractGeoShapeIndexFieldData.java
  server/src/main/java/org/opensearch/index/fielddata/plain/AbstractLeafGeoShapeFieldData.java
  server/src/main/java/org/opensearch/index/fielddata/plain/GeoShapeDVLeafFieldData.java
  server/src/main/java/org/opensearch/index/mapper/AbstractGeometryFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/GeoShapeFieldMapper.java
  server/src/main/java/org/opensearch/search/aggregations/support/CoreValuesSourceType.java
  server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
  server/src/test/java/org/opensearch/common/util/CollectionUtilsTests.java
  server/src/test/java/org/opensearch/index/fielddata/GeoShapeValueTests.java
  server/src/test/java/org/opensearch/index/mapper/GeoShapeFieldMapperTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/CoreValuesSourceTypeTests.java
Labels: Aggregations, Geospatial, v2.5.0

#4556 Updates jackson and snakeyml dependencies
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.13.3.jar.sha1
  client/sniffer/licenses/jackson-core-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.3.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.3.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.4.jar.sha1
  libs/x-content/licenses/snakeyaml-1.31.jar.sha1
  libs/x-content/licenses/snakeyaml-1.32.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.3.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.3.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.3.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.4.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.3.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.4.jar.sha1
Labels: >upgrade, dependencies, v3.0.0, backport 2.x

#4568 Remove deprecated code to add node name into log pattern of log4j property file
  CHANGELOG.md
  qa/evil-tests/src/test/java/org/opensearch/common/logging/EvilLoggerTests.java
  server/src/main/java/org/opensearch/common/logging/LogConfigurator.java
Labels: deprecate, v3.0.0

#4569 [2.x] Change the version to remove deprecated code of adding node name into log pattern of log4j property file
  CHANGELOG.md
  qa/evil-tests/src/test/java/org/opensearch/common/logging/EvilLoggerTests.java
  server/src/main/java/org/opensearch/common/logging/LogConfigurator.java
Labels: deprecate, v2.4.0, backport 2.3

#4580 Unmute RelocationIT.testRelocationWhileIndexingRandom.
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java
Labels: backport 2.x

#4622 [Backport-2.3] Updated jackson and snakeyml dependencies
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.13.3.jar.sha1
  client/sniffer/licenses/jackson-core-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.3.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.3.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.4.jar.sha1
  libs/x-content/licenses/snakeyaml-1.31.jar.sha1
  libs/x-content/licenses/snakeyaml-1.32.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.3.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.3.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.3.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.4.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.3.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.4.jar.sha1
Labels: backport, >upgrade, dependencies, v2.3.0

#4638 Relax visibility of the HTTP_CHANNEL_KEY and HTTP_SERVER_CHANNEL_KEY to make it possible for the plugins to access associated Netty4HttpChannel / Netty4HttpServerChannel instance
  CHANGELOG.md
  modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java
Labels: v3.0.0

#4644 Bumping hadoop-hdfs version to 3.3.4
  CHANGELOG.md
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/hadoop-client-api-3.3.3.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-api-3.3.4.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-runtime-3.3.3.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-runtime-3.3.4.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-3.3.3.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-3.3.4.jar.sha1
  test/fixtures/hdfs-fixture/build.gradle
Labels: >upgrade, backport 1.x, dependencies, v3.0.0, backport 2.x, backport 1.3

#4499 Bugfix/496 rollover alias with filters
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverService.java
  server/src/main/java/org/opensearch/cluster/metadata/AliasAction.java
  server/src/test/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverServiceTests.java
Labels: Indexing & Search, backport 2.x

#4582 [Refactor] Load the deprecated master role in a dedicated method instead of in setAdditionalRoles()
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeRoleSettingTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/node/NodeRoleSettingsTests.java
Labels: enhancement, v3.0.0, backport 2.x, v2.4.0
