Repository opensearch-project/OpenSearch, pull requests merged in 2022-04, with the labels that each got.

#2670 Centralize codes related to 'master_timeout' deprecation for eaiser removal - in CAT Nodes API
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
  server/src/main/java/org/opensearch/rest/RestRequest.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
  server/src/test/java/org/opensearch/rest/RestRequestTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestNodesActionTests.java
Labels: enhancement, v2.0.0, backport 2.x, backport 2.0

#2689 [Remove] types from rest-api-spec endpoints
  client/rest-high-level/src/test/java/org/opensearch/client/RestHighLevelClientTests.java
  rest-api-spec/src/main/resources/rest-api-spec/api/bulk.json
  rest-api-spec/src/main/resources/rest-api-spec/api/create.json
  rest-api-spec/src/main/resources/rest-api-spec/api/delete.json
  rest-api-spec/src/main/resources/rest-api-spec/api/exists_source.json
  rest-api-spec/src/main/resources/rest-api-spec/api/explain.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.exists_type.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.stats.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.validate_query.json
  rest-api-spec/src/main/resources/rest-api-spec/api/update.json
Labels: non-issue, pending backport, >breaking, Indexing & Search, v3.0.0

#2557 Add request parameter 'cluster_manager_timeout' as the alternative for 'master_timeout', and deprecate 'master_timeout' - in CAT APIs
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.allocation.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.cluster_manager.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.indices.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.nodeattrs.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.pending_tasks.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.plugins.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.repositories.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.segments.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.shards.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.snapshots.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.templates.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.thread_pool.json
  server/src/main/java/org/opensearch/rest/action/cat/RestAllocationAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestMasterAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodeAttrsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestPendingClusterTasksAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestPluginsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestRepositoriesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestSegmentsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestSnapshotAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestTemplatesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestThreadPoolAction.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
Labels: enhancement, v2.0.0, backport 2.x, backport 2.0

#2715 [Main] Bump Version 2.0 to 2.1
  .ci/bwcVersions
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
  test/framework/src/test/java/org/opensearch/test/VersionUtilsTests.java
Labels: non-issue, backwards-compatibility, >upgrade, v3.0.0

#2702 Make Rest-High-Rest-Level tests allow deprecation warning temporarily, during deprecation of request parameter 'master_timeout'
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: :test, v2.0.0, WIP, backport 2.x, backport 2.0

#2722 [Version] Don't spoof major for 3.0+ clusters
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/LegacyESVersionTests.java
  server/src/test/java/org/opensearch/VersionTests.java
Labels: non-issue, >upgrade, v3.0.0

#2658 Add request parameter 'cluster_manager_timeout' and deprecate 'master_timeout' - in Cluster APIs
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.get_settings.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.health.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.pending_tasks.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.put_settings.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.reroute.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.state.json
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterGetSettingsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterRerouteAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterUpdateSettingsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestPendingClusterTasksAction.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/reroute/ClusterRerouteRequestTests.java
  server/src/test/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthActionTests.java
Labels: enhancement, v2.0.0, backport 2.x, backport 2.0

#2556 Bump version to 3.0.0
  .ci/bwcVersions
  buildSrc/src/main/java/org/opensearch/gradle/Version.java
  buildSrc/src/test/java/org/opensearch/gradle/DistributionDownloadPluginTests.java
  buildSrc/src/test/java/org/opensearch/gradle/VersionTests.java
  buildSrc/version.properties
  client/rest-high-level/src/test/java/org/opensearch/client/core/MainResponseTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/ConcatenateGraphTokenFilterFactoryTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/EdgeNGramTokenizerTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/SynonymsAnalysisTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/WordDelimiterGraphTokenFilterFactoryTests.java
  plugins/analysis-phonetic/src/test/java/org/opensearch/index/analysis/AnalysisPhoneticFactoryTests.java
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/transport/InboundDecoder.java
  server/src/main/java/org/opensearch/transport/TransportHandshaker.java
  server/src/test/java/org/opensearch/LegacyESVersionTests.java
  server/src/test/java/org/opensearch/VersionTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequestTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponsesTests.java
  server/src/test/java/org/opensearch/action/ingest/SimulateProcessorResultTests.java
  server/src/test/java/org/opensearch/action/main/MainResponseTests.java
  server/src/test/java/org/opensearch/action/support/IndicesOptionsTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/metadata/AutoExpandReplicasTests.java
  server/src/test/java/org/opensearch/cluster/metadata/DataStreamTemplateTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/common/lucene/uid/VersionsTests.java
  server/src/test/java/org/opensearch/env/NodeMetadataTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/analysis/PreBuiltAnalyzerTests.java
  server/src/test/java/org/opensearch/index/mapper/RootObjectMapperTests.java
  server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
  server/src/test/java/org/opensearch/ingest/IngestStatsTests.java
  server/src/test/java/org/opensearch/persistent/PersistentTasksCustomMetadataTests.java
  server/src/test/java/org/opensearch/rest/action/document/RestIndexActionTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/GeoHashGridTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/GeoTileGridTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/GeoTileGridValuesSourceBuilderTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/InternalScriptedMetricTests.java
  server/src/test/java/org/opensearch/transport/InboundDecoderTests.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
  test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
  test/framework/src/test/java/org/opensearch/test/VersionUtilsTests.java
  test/framework/src/test/java/org/opensearch/test/rest/yaml/section/SkipSectionTests.java
Labels: WIP, non-issue, >upgrade, v3.0.0

#2755 [2.0] Add request parameter 'cluster_manager_timeout' and deprecate 'master_timeout' in Cluster APIs (#2658)
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.get_settings.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.health.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.pending_tasks.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.put_settings.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.reroute.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.state.json
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterGetSettingsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterRerouteAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterUpdateSettingsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestPendingClusterTasksAction.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/reroute/ClusterRerouteRequestTests.java
  server/src/test/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthActionTests.java
Labels: enhancement, v2.0.0, backport

#2485 Remove endpoint_suffix dependency on account key
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageSettings.java
Labels: enhancement, Plugins, v2.1.0, v3.0.0, backport 2.x

#2760 Update ThirdPartyAuditTask to check for and list pointless exclusions.
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
Labels: enhancement, Build Libraries & Interfaces, v3.0.0, backport 2.x, backport 2.0

#2766 Fix TaskInfo serialization and unmute task_list bwc test
  rest-api-spec/src/main/resources/rest-api-spec/test/tasks.list/10_basic.yml
  server/src/main/java/org/opensearch/tasks/TaskInfo.java
Labels: :test, backwards-compatibility, v3.0.0

#2730 Rename `file` to `dir` in Environment
  distribution/tools/keystore-cli/src/main/java/org/opensearch/common/settings/AddFileKeyStoreCommand.java
  distribution/tools/keystore-cli/src/main/java/org/opensearch/common/settings/AddStringKeyStoreCommand.java
  distribution/tools/keystore-cli/src/main/java/org/opensearch/common/settings/CreateKeyStoreCommand.java
  distribution/tools/keystore-cli/src/main/java/org/opensearch/common/settings/RemoveSettingKeyStoreCommand.java
  distribution/tools/keystore-cli/src/test/java/org/opensearch/bootstrap/BootstrapTests.java
  distribution/tools/keystore-cli/src/test/java/org/opensearch/common/settings/AddFileKeyStoreCommandTests.java
  distribution/tools/keystore-cli/src/test/java/org/opensearch/common/settings/AddStringKeyStoreCommandTests.java
  distribution/tools/keystore-cli/src/test/java/org/opensearch/common/settings/CreateKeyStoreCommandTests.java
  distribution/tools/keystore-cli/src/test/java/org/opensearch/common/settings/KeyStoreCommandTestCase.java
  distribution/tools/keystore-cli/src/test/java/org/opensearch/common/settings/KeyStoreWrapperTests.java
  distribution/tools/keystore-cli/src/test/java/org/opensearch/common/settings/UpgradeKeyStoreCommandTests.java
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/ListPluginsCommand.java
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/RemovePluginCommand.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/ListPluginsCommandTests.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/RemovePluginCommandTests.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/TaskInput.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/UpgradeCliTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/ValidateInputTaskTests.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/HyphenationCompoundWordTokenFilterFactory.java
  modules/ingest-geoip/src/main/java/org/opensearch/ingest/geoip/IngestGeoIpPlugin.java
  modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/IngestUserAgentPlugin.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/ReindexSslConfig.java
  plugins/analysis-icu/src/main/java/org/opensearch/index/analysis/IcuCollationTokenFilterFactory.java
  plugins/analysis-icu/src/main/java/org/opensearch/index/analysis/IcuTokenizerFactory.java
  plugins/examples/custom-settings/src/main/java/org/opensearch/example/customsettings/ExampleCustomSettingsConfig.java
  plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsSecurityContext.java
  qa/evil-tests/src/test/java/org/opensearch/bootstrap/EvilSecurityTests.java
  qa/no-bootstrap-tests/src/test/java/org/opensearch/bootstrap/SpawnerNoBootstrapTests.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/ReloadSecureSettingsIT.java
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/reload/TransportNodesReloadSecureSettingsAction.java
  server/src/main/java/org/opensearch/bootstrap/Bootstrap.java
  server/src/main/java/org/opensearch/bootstrap/OpenSearch.java
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/main/java/org/opensearch/bootstrap/Spawner.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/logging/LogConfigurator.java
  server/src/main/java/org/opensearch/common/settings/BaseKeyStoreCommand.java
  server/src/main/java/org/opensearch/common/settings/ChangeKeyStorePasswordCommand.java
  server/src/main/java/org/opensearch/common/settings/HasPasswordKeyStoreCommand.java
  server/src/main/java/org/opensearch/common/settings/UpgradeKeyStoreCommand.java
  server/src/main/java/org/opensearch/env/Environment.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/index/analysis/Analysis.java
  server/src/main/java/org/opensearch/indices/analysis/HunspellService.java
  server/src/main/java/org/opensearch/node/InternalSettingsPreparer.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverServiceTests.java
  server/src/test/java/org/opensearch/env/EnvironmentTests.java
  server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
  server/src/test/java/org/opensearch/node/InternalSettingsPreparerTests.java
  server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  test/framework/src/main/java/org/opensearch/test/AbstractBuilderTestCase.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: v3.0.0

#2754 [2.x] Add request parameter 'cluster_manager_timeout' and deprecate 'master_timeout' in Cluster APIs (#2658)
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.get_settings.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.health.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.pending_tasks.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.put_settings.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.reroute.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.state.json
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterGetSettingsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterRerouteAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterUpdateSettingsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestPendingClusterTasksAction.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/reroute/ClusterRerouteRequestTests.java
  server/src/test/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthActionTests.java
Labels: enhancement, backport, v2.1.0

#2660 Add request parameter 'cluster_manager_timeout' and deprecate 'master_timeout' - in Index APIs except index template APIs
  qa/smoke-test-http/src/test/java/org/opensearch/http/DanglingIndicesRestIT.java
  rest-api-spec/src/main/resources/rest-api-spec/api/dangling_indices.delete_dangling_index.json
  rest-api-spec/src/main/resources/rest-api-spec/api/dangling_indices.import_dangling_index.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.add_block.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.clone.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.close.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.create.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.delete_alias.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.get.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.get_mapping.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.get_settings.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.get_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.put_alias.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.put_mapping.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.put_settings.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.rollover.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.shrink.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.split.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.update_aliases.json
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/20_source_mapping.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/30_copy_settings.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/20_source_mapping.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/30_copy_settings.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/20_source_mapping.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/30_copy_settings.yml
  server/src/main/java/org/opensearch/rest/action/admin/cluster/dangling/RestDeleteDanglingIndexAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/dangling/RestImportDanglingIndexAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestAddIndexBlockAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestCloseIndexAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestCreateIndexAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestDeleteIndexAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetIndicesAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetMappingAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetSettingsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestIndexDeleteAliasesAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestIndexPutAliasAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestIndicesAliasesAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestOpenIndexAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestPutMappingAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestResizeHandler.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestRolloverIndexAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestUpdateSettingsAction.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
Labels: enhancement, v2.0.0, backport 2.x, backport 2.0

#2752 Replace blacklist in Gradle build environment configuration
  TESTING.md
  plugins/repository-s3/build.gradle
  test/framework/src/main/java/org/opensearch/test/junit/listeners/ReproduceInfoPrinter.java
  test/framework/src/main/java/org/opensearch/test/rest/yaml/OpenSearchClientYamlSuiteTestCase.java
Labels: enhancement, Build Libraries & Interfaces, v2.0.0, v3.0.0, backport 2.x, backport 2.0

#2779 Fix issue that deprecated setting 'cluster.initial_master_nodes' is not identified in node bootstrap check
  server/src/main/java/org/opensearch/cluster/coordination/ClusterBootstrapService.java
  server/src/test/java/org/opensearch/bootstrap/BootstrapChecksTests.java
  server/src/test/java/org/opensearch/cluster/coordination/ClusterBootstrapServiceTests.java
Labels: bug, v2.0.0, distributed framework, v3.0.0, backport 2.x, backport 2.0

#2795 Update azure-storage-blob to 12.15.0: fix test flakiness
  plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java
  test/fixtures/azure-fixture/src/main/java/fixture/azure/AzureHttpHandler.java
Labels: :test, v2.0.0, v3.0.0, backport 2.x, backport 2.0

#2796 [Feature branch: extensions] Adding initial support for extensions
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/main/java/org/opensearch/discovery/PluginRequest.java
  server/src/main/java/org/opensearch/discovery/PluginResponse.java
  server/src/main/java/org/opensearch/env/Environment.java
  server/src/main/java/org/opensearch/extensions/DiscoveryExtension.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/PluginsOrchestrator.java
  server/src/main/java/org/opensearch/transport/TransportService.java
Labels: Plugins

#2801 Gradle check retry (#2638)
  build.gradle
Labels: backport, v1.4.0

#2767 Allow deprecation warning for API call 'GET _cat/master' in 'ExceptionIT' of mixed cluster BWC test
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/ExceptionIT.java
Labels: :test, v2.1.0, v3.0.0, backport 2.x

#2784 Replace remaining 'blacklist' with 'denylist' in internal class and method names
  server/src/main/java/org/opensearch/common/inject/BindingProcessor.java
  server/src/main/java/org/opensearch/common/inject/InheritingState.java
  server/src/main/java/org/opensearch/common/inject/InjectorImpl.java
  server/src/main/java/org/opensearch/common/inject/State.java
  test/framework/src/main/java/org/opensearch/test/rest/yaml/DenylistedPathPatternMatcher.java
  test/framework/src/main/java/org/opensearch/test/rest/yaml/OpenSearchClientYamlSuiteTestCase.java
  test/framework/src/test/java/org/opensearch/test/rest/yaml/DenylistedPathPatternMatcherTests.java
Labels: v2.0.0, Severity-Minor, v3.0.0, backport 2.x, backport 2.0

#2814 Updates to the large string reg-ex check
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
  server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java
Labels: bug, Indexing & Search

#2817 [Backport] [2.x] Bugfix to guard against stack overflow errors caused by very large reg-ex input
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTermsAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/RareTermsTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/SignificantTermsTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/TermsTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/BinaryTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java
Labels: backport, v2.1.0

#2816 [Backport] [2.0] Bugfix to guard against stack overflow errors caused by very large reg-ex input
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTermsAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/RareTermsTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/SignificantTermsTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/TermsTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/BinaryTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java
Labels: v2.0.0, backport

#2806 Update commons-logging to 1.2
  buildSrc/version.properties
  client/rest/build.gradle
  client/rest/licenses/commons-logging-1.1.3.jar.sha1
  client/rest/licenses/commons-logging-1.2.jar.sha1
  client/sniffer/build.gradle
  client/sniffer/licenses/commons-logging-1.1.3.jar.sha1
  client/sniffer/licenses/commons-logging-1.2.jar.sha1
  modules/repository-s3/licenses/commons-logging-1.2.jar.sha1
  plugins/discovery-azure-classic/licenses/commons-logging-1.1.3.jar.sha1
  plugins/discovery-azure-classic/licenses/commons-logging-1.2.jar.sha1
  plugins/discovery-ec2/licenses/commons-logging-1.1.3.jar.sha1
  plugins/discovery-ec2/licenses/commons-logging-1.2.jar.sha1
  plugins/discovery-gce/licenses/commons-logging-1.1.3.jar.sha1
  plugins/discovery-gce/licenses/commons-logging-1.2.jar.sha1
  plugins/ingest-attachment/licenses/commons-logging-1.1.3.jar.sha1
  plugins/ingest-attachment/licenses/commons-logging-1.2.jar.sha1
  plugins/repository-gcs/licenses/commons-logging-1.1.3.jar.sha1
  plugins/repository-gcs/licenses/commons-logging-1.2.jar.sha1
  plugins/repository-hdfs/licenses/commons-logging-1.1.3.jar.sha1
  plugins/repository-hdfs/licenses/commons-logging-1.2.jar.sha1
  plugins/repository-s3/licenses/commons-logging-1.1.3.jar.sha1
  plugins/repository-s3/licenses/commons-logging-1.2.jar.sha1
  test/framework/build.gradle
  x-pack/plugin/core/licenses/commons-logging-1.2.jar.sha1
Labels: >upgrade, dependencies, v2.1.0, v3.0.0, backport 2.x

#2807 [Backport 2.x] Remove endpoint_suffix dependency on account key
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageSettings.java
Labels: backport, v2.1.0

#2860 Decouple IndexSettings from IncludeExclude
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTermsAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java
  server/src/test/java/org/opensearch/search/aggregations/support/IncludeExcludeTests.java
Labels: backport main, backport 2.x

#2863 Change deprecation message for REST API parameter 'master_timeout' to specify the version of removal
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/20_source_mapping.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/30_copy_settings.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/20_source_mapping.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/30_copy_settings.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/20_source_mapping.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/30_copy_settings.yml
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetMappingAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
Labels: v2.0.0, deprecate, backport 2.x, backport 2.0

#2678 Add request parameter 'cluster_manager_timeout' and deprecate 'master_timeout' - in Index Template APIs
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.delete_component_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.get_component_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/cluster.put_component_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.delete_index_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.delete_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.get_index_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.get_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.put_index_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.put_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.simulate_index_template.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.simulate_template.json
  rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/20_filtering.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.exists_template/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_template/10_basic.yml
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestDeleteComponentTemplateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestDeleteComposableIndexTemplateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestDeleteIndexTemplateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetComponentTemplateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetComposableIndexTemplateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetIndexTemplateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestPutComponentTemplateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestPutComposableIndexTemplateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestPutIndexTemplateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestSimulateIndexTemplateAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestSimulateTemplateAction.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
Labels: enhancement, v2.0.0, backport 2.x, backport 2.0

#2680 Add request parameter 'cluster_manager_timeout' and deprecate 'master_timeout' - in Snapshot APIs
  plugins/repository-azure/src/yamlRestTest/resources/rest-api-spec/test/repository_azure/20_repository.yml
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.cleanup_repository.json
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.clone.json
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.create.json
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.create_repository.json
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.delete.json
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.delete_repository.json
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.get.json
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.get_repository.json
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.restore.json
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.status.json
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.verify_repository.json
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestCleanupRepositoryAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestCloneSnapshotAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestCreateSnapshotAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestDeleteRepositoryAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestDeleteSnapshotAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestGetRepositoriesAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestGetSnapshotsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestPutRepositoryAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestRestoreSnapshotAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestSnapshotsStatusAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestVerifyRepositoryAction.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
Labels: enhancement, v2.0.0, backport 2.x, backport 2.0

#2880 Change deprecation message for API parameter value 'master_node' of parameter 'metric'
  rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/20_filtering.yml
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterRerouteAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStateAction.java
Labels: bug, :test, v2.0.0, deprecate, backport 2.x, backport 2.0

#2869 Remove an unused commons-logging-1.2.jar.sha1 checksum file
  x-pack/plugin/core/licenses/commons-logging-1.2.jar.sha1
Labels: non-issue, v3.0.0

#2682 Add request parameter 'cluster_manager_timeout' and deprecate 'master_timeout' - in Ingest APIs and Script APIs
  rest-api-spec/src/main/resources/rest-api-spec/api/delete_script.json
  rest-api-spec/src/main/resources/rest-api-spec/api/get_script.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ingest.delete_pipeline.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ingest.get_pipeline.json
  rest-api-spec/src/main/resources/rest-api-spec/api/ingest.put_pipeline.json
  rest-api-spec/src/main/resources/rest-api-spec/api/put_script.json
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestDeleteStoredScriptAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestGetStoredScriptAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestPutStoredScriptAction.java
  server/src/main/java/org/opensearch/rest/action/ingest/RestDeletePipelineAction.java
  server/src/main/java/org/opensearch/rest/action/ingest/RestGetPipelineAction.java
  server/src/main/java/org/opensearch/rest/action/ingest/RestPutPipelineAction.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
Labels: enhancement, v2.0.0, backport 2.x, backport 2.0

#2879 Adding a null pointer check to fix index_prefix query
  server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldTypeTests.java
Labels: bug, Indexing & Search, v3.0.0, backport 2.x, backport 2.0

#2908 [1.x backport] Fix opensearch-env always sources the environment from hardcoded file in #875
  distribution/src/bin/opensearch-env
Labels: backport, v1.4.0

#2909 [1.3 backport] Fix opensearch-env always sources the environment from hardcoded file in #875
  distribution/src/bin/opensearch-env
Labels: backport, v1.3.0

#2894 Excluding system indices from max shard limit validator
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/indices/ShardLimitValidator.java
  server/src/main/java/org/opensearch/indices/SystemIndices.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverServiceTests.java
  server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java
  server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, Indexing & Search, v2.1.0, v3.0.0, backport 2.x

#2886 Add deprecated API for creating History Ops Snapshot from translog
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: deprecate, v2.1.0, backport 2.0

#2901 Add type mapping removal bwc tests for indexing, searching, snapshots
  qa/rolling-upgrade/build.gradle
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/AbstractRollingTestCase.java
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/MappingTypeRemovalIT.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: backport 2.x

#2918 Fixing Scaled float field mapper to respect ignoreMalformed setting
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/ScaledFloatFieldMapper.java
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldMapperTests.java
Labels: bug, Indexing & Search, v2.1.0, v3.0.0, backport 2.x

#2930 [2.x] Revert "Make High-Level-Rest-Client tests allow deprecation warning temporarily (#2702)"
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: :test, v2.0.0, v2.1.0, backport 2.0

#2933 Adding asm to version file and upgrading
  buildSrc/version.properties
  modules/lang-expression/build.gradle
  modules/lang-expression/licenses/asm-9.2.jar.sha1
  modules/lang-expression/licenses/asm-9.3.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.2.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.3.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.2.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.3.jar.sha1
  modules/lang-painless/build.gradle
  modules/lang-painless/licenses/asm-9.2.jar.sha1
  modules/lang-painless/licenses/asm-9.3.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.2.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.3.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.2.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.3.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.2.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.3.jar.sha1
  modules/lang-painless/licenses/asm-util-9.2.jar.sha1
  modules/lang-painless/licenses/asm-util-9.3.jar.sha1
  test/logger-usage/build.gradle
Labels: >upgrade, dependencies, v3.0.0, backport 2.x

#2898 Removed java11 source folders since JDK-11 is the baseline now
  libs/core/src/main/java/org/opensearch/common/collect/List.java
  libs/core/src/main/java/org/opensearch/common/collect/Map.java
  libs/core/src/main/java/org/opensearch/common/collect/Set.java
  libs/core/src/main/java/org/opensearch/core/internal/io/Streams.java
  libs/core/src/main/java11/org/opensearch/common/collect/List.java
  libs/core/src/main/java11/org/opensearch/common/collect/Map.java
  libs/core/src/main/java11/org/opensearch/common/collect/Set.java
  libs/core/src/main/java11/org/opensearch/core/internal/io/Streams.java
  server/src/main/java/org/opensearch/monitor/jvm/JvmPid.java
  server/src/main/java11/org/opensearch/monitor/jvm/JvmPid.java
Labels: v3.0.0, backport 2.x, backport 2.0

#2929 Adding workflow to create documentation related issues in documentati…
  .ci/documentation/issue.md
  .github/workflows/create-documentation-issue.yml
Labels: documentation, CI

#2969 Remove binary (class) files from the repository
  doc-tools/missing-doclet/bin/main/org/opensearch/missingdoclet/MissingDoclet.class
Labels: backport 2.x

#2821 Add Gradle 7.4 Aggregated Test Reports
  build.gradle
  gradle/code-coverage.gradle
Labels: backport 2.x

#2683 Replace parameter 'master_timeout' with 'cluster_manager_tiemout' in RequestConverters of High-Level-Rest-Client
  client/rest-high-level/src/main/java/org/opensearch/client/ClusterRequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/IndicesRequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/IngestRequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/SnapshotRequestConverters.java
  client/rest-high-level/src/test/java/org/opensearch/client/ClusterRequestConvertersTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/IndicesRequestConvertersTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/IngestRequestConvertersTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/RequestConvertersTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/SnapshotRequestConvertersTests.java
Labels: enhancement, >breaking, v3.0.0

#2744 Revert "Make High-Level-Rest-Client tests allow deprecation warning temporarily (#2702)"
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: :test, v3.0.0

#3007 [Remove] remaining AllFieldMapper references
  server/src/main/java/org/opensearch/index/mapper/AllFieldMapper.java
  server/src/main/java/org/opensearch/indices/mapper/MapperRegistry.java
  server/src/test/java/org/opensearch/index/mapper/AllFieldMapperTests.java
  server/src/test/java/org/opensearch/indices/IndicesModuleTests.java
Labels: non-issue, v3.0.0, backport 2.x, backport 2.0

#3016 [Type Removal] Remove TypeFieldMapper usage, remove support of `_type` in searches and from LeafFieldsLookup
  modules/percolator/src/test/java/org/opensearch/percolator/PercolatorFieldMapperTests.java
  rest-api-spec/src/main/resources/rest-api-spec/test/search/160_exists_query.yml
  server/src/internalClusterTest/java/org/opensearch/document/DocumentActionsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/TopHitsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java
  server/src/main/java/org/opensearch/index/mapper/DocumentMapper.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/mapper/TypeFieldMapper.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/search/lookup/LeafFieldsLookup.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/get/GetResultTests.java
  server/src/test/java/org/opensearch/index/mapper/TypeFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/TypeFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/TermQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/TermsQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/WildcardQueryBuilderTests.java
  server/src/test/java/org/opensearch/indices/IndicesModuleTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/ValuesSourceConfigTests.java
  server/src/test/java/org/opensearch/search/fetch/subphase/FieldFetcherTests.java
Labels: bug, >breaking, v3.0.0, backport 2.x, backport 2.0

#3015 Removed binary file from linelint
  .gitignore
  .linelint.yml
Labels: enhancement, Build Libraries & Interfaces, non-issue, v3.0.0, backport 2.x

#2687 Adding multi_term aggregator support
  client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/370_multi_terms.yml
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/MultiTermsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/terms/BaseStringTermsTestCase.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/terms/StringTermsIT.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationBuilders.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalMultiTerms.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalTerms.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregationBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregationFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/ParsedMultiTerms.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/ParsedTerms.java
  server/src/main/java/org/opensearch/search/aggregations/support/BaseMultiValuesSourceFieldConfig.java
  server/src/main/java/org/opensearch/search/aggregations/support/MultiTermsValuesSourceConfig.java
  server/src/main/java/org/opensearch/search/aggregations/support/MultiValuesSourceFieldConfig.java
  server/src/test/java/org/opensearch/search/aggregations/AggregationsTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/InternalMultiTermsTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregationBuilderTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/MultiTermsValuesSourceConfigTests.java
  test/framework/src/main/java/org/opensearch/test/InternalAggregationTestCase.java
Labels: feature, Aggregations, v2.1.0, backport 2.x

#3031 [Remove] MainResponse version override cluster setting
  client/rest-high-level/src/test/java/org/opensearch/client/PingAndInfoIT.java
  server/src/main/java/org/opensearch/action/main/MainResponse.java
  server/src/main/java/org/opensearch/action/main/TransportMainAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/action/main/MainActionTests.java
  server/src/test/java/org/opensearch/action/main/MainResponseTests.java
Labels: bug, Severity-Blocker, backwards-compatibility, v3.0.0, backport 2.x, backport 2.0

#3027 Remove JavaVersion in favour of standard Runtime.Version (java-version-checker)
  distribution/tools/java-version-checker/src/main/java/org/opensearch/tools/java_version_checker/JavaVersion.java
  distribution/tools/java-version-checker/src/main/java/org/opensearch/tools/java_version_checker/JavaVersionChecker.java
  distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/JvmErgonomics.java
  distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/JvmOptionsParser.java
  distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/SystemJvmOptions.java
  distribution/tools/launchers/src/test/java/org/opensearch/tools/launchers/JvmErgonomicsTests.java
Labels: v2.1.0, v3.0.0, backport 2.x

#2924 [Upgrade] Lucene-9.2-snapshot
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.1.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.1.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.1.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.1.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.1.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.1.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.1.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.2.0-snapshot-f4f1f70.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.1.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.2.0-snapshot-f4f1f70.jar.sha1
  sandbox/plugins/concurrent-search/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
  server/licenses/lucene-analysis-common-9.1.0.jar.sha1
  server/licenses/lucene-analysis-common-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-backward-codecs-9.1.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-core-9.1.0.jar.sha1
  server/licenses/lucene-core-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-grouping-9.1.0.jar.sha1
  server/licenses/lucene-grouping-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-highlighter-9.1.0.jar.sha1
  server/licenses/lucene-highlighter-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-join-9.1.0.jar.sha1
  server/licenses/lucene-join-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-memory-9.1.0.jar.sha1
  server/licenses/lucene-memory-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-misc-9.1.0.jar.sha1
  server/licenses/lucene-misc-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-queries-9.1.0.jar.sha1
  server/licenses/lucene-queries-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-queryparser-9.1.0.jar.sha1
  server/licenses/lucene-queryparser-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-sandbox-9.1.0.jar.sha1
  server/licenses/lucene-sandbox-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-spatial-extras-9.1.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-spatial3d-9.1.0.jar.sha1
  server/licenses/lucene-spatial3d-9.2.0-snapshot-f4f1f70.jar.sha1
  server/licenses/lucene-suggest-9.1.0.jar.sha1
  server/licenses/lucene-suggest-9.2.0-snapshot-f4f1f70.jar.sha1
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/common/lucene/uid/VersionsTests.java
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: enhancement, non-issue, >upgrade, v3.0.0

#3042 Temporary adding Apache Lucene repositories for snapshots
  gradle/code-coverage.gradle
Labels: backport 2.x

#3048 Added explicit 'null' check for response listener to prevent obscure NullPointerException issues
  client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java
  client/rest-high-level/src/test/java/org/opensearch/client/RestHighLevelClientTests.java
Labels: backport 2.x

#3053 [Rename] ESTestCase stragglers to OpenSearchTestCase
  buildSrc/src/main/resources/forbidden/opensearch-test-signatures.txt
  server/src/main/resources/org/opensearch/bootstrap/security.policy
Labels: Rename, non-issue, v3.0.0

#3037 Adds the replication type index setting, alongside a formal notion of feature flags
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/settings/SettingsModule.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationType.java
  server/src/main/resources/org/opensearch/bootstrap/security.policy
  server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java
Labels: feature, Indexing & Search, v2.1.0, v3.0.0, backport 2.x

#3072 Correct the skip version, multi_terms aggregation is supported on 2.1
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/370_multi_terms.yml
Labels: backport 2.x

#3076 [Type removal] Remove _type support in NOOP bulk indexing from client benchmark
  client/benchmark/README.md
  client/benchmark/src/main/java/org/opensearch/client/benchmark/AbstractBenchmark.java
  client/benchmark/src/main/java/org/opensearch/client/benchmark/rest/RestClientBenchmark.java
Labels: Clients & Libraries, backport 2.x, backport 2.0

#3004 [Remove] Type from nested fields using new metadata field mapper
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/main/java/org/opensearch/index/mapper/NestedPathFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/mapper/MapperRegistry.java
  server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
  server/src/test/java/org/opensearch/index/mapper/FieldAliasMapperValidationTests.java
  server/src/test/java/org/opensearch/index/mapper/NestedObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/NestedPathFieldMapperTests.java
  server/src/test/java/org/opensearch/index/search/NestedHelperTests.java
  server/src/test/java/org/opensearch/index/search/nested/NestedSortingTests.java
  server/src/test/java/org/opensearch/index/shard/ShardSplittingQueryTests.java
  server/src/test/java/org/opensearch/indices/IndicesModuleTests.java
  server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/nested/NestedAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/nested/ReverseNestedAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/sort/FieldSortBuilderTests.java
  server/src/test/java/org/opensearch/search/sort/GeoDistanceSortBuilderTests.java
  server/src/test/java/org/opensearch/search/sort/ScriptSortBuilderTests.java
Labels: non-issue, backwards-compatibility, v3.0.0, backport 2.x, backport 2.0

#3088 Replace internal usages of 'master' term in 'client' directory
  client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/TimedRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComponentTemplatesRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComposableIndexTemplateRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexTemplatesRequest.java
  client/rest-high-level/src/test/java/org/opensearch/client/ClusterRequestConvertersTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/TimedRequestTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/indices/CloseIndexRequestTests.java
  client/rest/src/main/java/org/opensearch/client/Node.java
  client/rest/src/main/java/org/opensearch/client/NodeSelector.java
  client/rest/src/test/java/org/opensearch/client/NodeSelectorTests.java
  client/rest/src/test/java/org/opensearch/client/RestClientMultipleHostsTests.java
  client/rest/src/test/java/org/opensearch/client/documentation/RestClientDocumentation.java
  test/framework/src/test/java/org/opensearch/test/rest/yaml/section/ClientYamlTestSuiteTests.java
Labels: v2.1.0, backport 2.x

#3097 [Backport 2.0] [Remove] Type from nested fields using new metadata field mapper
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/main/java/org/opensearch/index/mapper/NestedPathFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/mapper/MapperRegistry.java
  server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
  server/src/test/java/org/opensearch/index/mapper/FieldAliasMapperValidationTests.java
  server/src/test/java/org/opensearch/index/mapper/NestedObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/NestedPathFieldMapperTests.java
  server/src/test/java/org/opensearch/index/search/NestedHelperTests.java
  server/src/test/java/org/opensearch/index/search/nested/NestedSortingTests.java
  server/src/test/java/org/opensearch/index/shard/ShardSplittingQueryTests.java
  server/src/test/java/org/opensearch/indices/IndicesModuleTests.java
  server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/nested/NestedAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/nested/ReverseNestedAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/RareTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/sort/FieldSortBuilderTests.java
  server/src/test/java/org/opensearch/search/sort/GeoDistanceSortBuilderTests.java
  server/src/test/java/org/opensearch/search/sort/ScriptSortBuilderTests.java
Labels: v2.0.0, backport, Indexing & Search

#3100 Update bundled JDK to 11.0.15+10
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport 1.3

#3099 Rename BecomeMasterTask to BecomeClusterManagerTask in JoinTaskExecutor
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
Labels: v2.0.0, v3.0.0, backport 2.x, backport 2.0
