Repository opensearch-project/OpenSearch, pull requests merged in 2022-07, with the labels that each got.

#3621 Changing default no_master_block from write to metadata_write
  server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
  server/src/main/java/org/opensearch/cluster/coordination/NoMasterBlockService.java
  server/src/test/java/org/opensearch/cluster/coordination/NoMasterBlockServiceTests.java
Labels: enhancement, distributed framework, backport 1.x, backport 2.x

#3772 Upgrade netty from 4.1.73.Final to 4.1.78.Final
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.73.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.78.Final.jar.sha1
  modules/transport-netty4/src/javaRestTest/java/org/opensearch/rest/Netty4BadRequestIT.java
  plugins/repository-azure/licenses/netty-codec-dns-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.73.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.78.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.73.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.78.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.73.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.78.Final.jar.sha1
Labels: >upgrade, dependencies, v3.0.0, backport 2.x, v2.2.0

#3799 Enable XML test reports for Jenkins integration
  build.gradle
Labels: backport 1.x, backport 2.x, backport 2.0, backport 2.1

#3813 Adding workflow to automatically publish releases after a tag is pushed
  .github/workflows/auto-release.yml
Labels: documentation, CI, release

#3816 Ignore backport / autocut / dependabot branches for gradle checks on push
  .github/workflows/gradle-check.yml
Labels: enhancement, backport 1.x, backport 2.x, backport 2.0, backport 1.3, backport 2.1

#3821 Update outdated dependencies
  benchmarks/build.gradle
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.13.2.jar.sha1
  client/sniffer/licenses/jackson-core-2.13.3.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.3.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.2.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.2.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.3.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.3.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.3.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.2.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.3.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.2.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.2.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.2.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.2.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.2.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.3.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.2.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.3.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.2.2.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.3.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.2.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.3.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.2.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.3.jar.sha1
Labels: >upgrade, dependencies, v3.0.0, backport 2.x, v2.2.0, backport 2.1

#1596 Adds status badge for showing code coverage in README
  README.md
Labels: documentation, :test, v3.0.0, backport 2.x, v2.2.0

#3848 Add netty-transport-native-unix-common to modules/transport-netty4/bu…
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.78.Final.jar.sha1
Labels: dependencies, backport 2.x

#3541 Upgrade minio image version
  test/fixtures/minio-fixture/Dockerfile
  test/fixtures/minio-fixture/docker-compose.yml
Labels: >upgrade, dependencies, v3.0.0, backport 2.x, v2.2.0

#3868 Update Netty to 4.1.79.Final
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.78.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.78.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.78.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.78.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
Labels: >upgrade, backport 1.x, dependencies, backport 2.x, backport 2.0, backport 1.3, backport 2.1

#3883 Fixing implausibly old time stamp 1970-01-01 00:00:00 by using the timestamp from the Git revision instead of default 0 value
  build.gradle
  buildSrc/src/main/java/org/opensearch/gradle/tar/SymbolicLinkPreservingTar.java
Labels: backport 2.x

#3894 Add release notes for release 1.3.4.
  release-notes/opensearch.release-notes-1.3.4.md
Labels: documentation

#3886 Add coverage, gha, jenkins server, documentation and forum badges
  README.md
Labels: documentation, backport, v2.2.0

#3594 Update to Gradle 7.5
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/StandaloneRestIntegTestTask.java
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x

#3792 Don't run EmptyDirTaskTests in a Docker container
  buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java
Labels: backport 2.x

#3913 [2.x] Added bwc version 1.3.5 (#3911)
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: backport, backport 2.0, v2.2.0, backport 2.1

#3916 [2.0] Added bwc version 1.3.5 (#3911) (#3913)
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: CI, backport

#3931 PR coverage requirement and default settings
  codecov.yml
Labels: CI

#3939 Fail build on wildcard imports
  benchmarks/src/main/java/org/opensearch/benchmark/time/NanoTimeVsCurrentTimeMillisBenchmark.java
  gradle/formatting.gradle
  modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessLexer.java
  modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java
  server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/RemoteIndexOutputTests.java
  server/src/test/java/org/opensearch/index/translog/listener/TranslogListenerTests.java
  server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentFileTransferHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
Labels: backport 2.x

#3935 Upgrading Joda version
  buildSrc/version.properties
  server/licenses/joda-time-2.10.12.jar.sha1
  server/licenses/joda-time-2.10.13.jar.sha1
Labels: >upgrade, dependencies, v3.0.0, v2.2.0

#3893 Adds a new parameter, max_analyzer_offset, for the highlighter
  plugins/mapper-annotated-text/src/test/java/org/opensearch/search/fetch/subphase/highlight/AnnotatedTextHighlighterTests.java
  rest-api-spec/src/main/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml
  server/src/main/java/org/apache/lucene/search/uhighlight/CustomUnifiedHighlighter.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/AbstractHighlighterBuilder.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightBuilder.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/SearchHighlightContext.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java
  server/src/test/java/org/opensearch/lucene/search/uhighlight/CustomUnifiedHighlighterTests.java
Labels: enhancement, community, Indexing & Search, backport 2.x

#3796 Parallelize stale blobs deletion during snapshot delete
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java
Labels: backport 2.x

#3561 Update merge on refresh and merge on commit defaults in Opensearch (Lucene 9.3)
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/test/java/org/opensearch/common/lucene/LuceneTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/shard/ShardGetServiceTests.java
Labels: v3.0.0, backport 2.x, v2.2.0

#4013 [Backport] [2.x] Update merge on refresh and merge on commit defaults in Opensearch (Lucene 9.3) (#3561)
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/test/java/org/opensearch/common/lucene/LuceneTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/shard/ShardGetServiceTests.java
Labels: backport, v2.2.0

#3981 [2.x] Deprecate public methods and variables that contain 'master' terminology in 'client' directory (#3966)
  client/rest-high-level/src/main/java/org/opensearch/client/ClusterRequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/IndicesRequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/TimedRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComponentTemplatesRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComposableIndexTemplateRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexTemplatesRequest.java
  client/rest-high-level/src/test/java/org/opensearch/client/TimedRequestTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/documentation/ClusterClientDocumentationIT.java
  client/rest-high-level/src/test/java/org/opensearch/client/documentation/IndicesClientDocumentationIT.java
  client/rest-high-level/src/test/java/org/opensearch/client/indices/CloseIndexRequestTests.java
  client/rest/src/main/java/org/opensearch/client/Node.java
  client/rest/src/main/java/org/opensearch/client/NodeSelector.java
  client/sniffer/src/test/java/org/opensearch/client/sniff/OpenSearchNodesSnifferTests.java
Labels: enhancement, deprecate, v3.0.0, backport 2.x, v2.2.0

#4006 Deprecate public methods and variables that contain 'master' terminology in class 'NoMasterBlockService' and 'MasterService'
  modules/rank-eval/src/test/java/org/opensearch/index/rankeval/RankEvalResponseTests.java
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterStateDiffIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/MinimumClusterManagerNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/NoClusterManagerNodeIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/UnsafeBootstrapAndDetachCommandIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/coordination/NoClusterManagerBlockService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/common/util/concurrent/BaseFuture.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
  server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
  server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
  server/src/test/java/org/opensearch/cluster/InternalClusterInfoServiceSchedulingTests.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinatorTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NoClusterManagerBlockServiceRenamedSettingTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NoClusterManagerBlockServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
  server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
  test/framework/src/main/java/org/opensearch/test/RandomObjects.java
Labels: enhancement, deprecate, v3.0.0, backport 2.x, v2.2.0

#4022 Deprecate class 'MasterService' and create alternative class 'ClusterManagerService'
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/ZenDiscoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/service/ClusterServiceIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/tasks/TransportPendingClusterTasksAction.java
  server/src/main/java/org/opensearch/cluster/ClusterStateTaskListener.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/util/concurrent/BaseFuture.java
  server/src/main/java/org/opensearch/discovery/DiscoveryModule.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/action/admin/cluster/configuration/TransportAddVotingConfigExclusionsActionTests.java
  server/src/test/java/org/opensearch/cluster/InternalClusterInfoServiceSchedulingTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/cluster/routing/BatchedRerouteServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
  server/src/test/java/org/opensearch/discovery/DiscoveryModuleTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
  test/framework/src/main/java/org/opensearch/cluster/service/FakeThreadPoolMasterService.java
  test/framework/src/main/java/org/opensearch/test/ClusterServiceUtils.java
  test/framework/src/main/java/org/opensearch/test/disruption/BlockMasterServiceOnMaster.java
  test/framework/src/main/java/org/opensearch/test/disruption/BusyMasterServiceDisruption.java
  test/framework/src/test/java/org/opensearch/cluster/service/FakeThreadPoolMasterServiceTests.java
Labels: enhancement, deprecate, v3.0.0, backport 2.x, v2.2.0
