Repository opensearch-project/OpenSearch, pull requests merged in 2022-11, with the labels that each got.

#4997 OpenJDK Update (October 2022 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: dependencies, v3.0.0, backport 2.x, backport 2.0, backport 2.1, v2.4.0, backport 2.2, backport 2.3, backport 2.4

#4998 OpenJDK Update (October 2022 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport 1.x, dependencies, backport 1.3

#4855 [Remove] LegacyESVersion.V_7_8_* and V_7_9_* constants
  CHANGELOG.md
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/main/java/org/opensearch/action/DocWriteRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/configuration/AddVotingConfigExclusionsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/tasks/cancel/CancelTasksRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/usage/NodeUsage.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/usage/NodesUsageRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/IndicesAliasesRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/put/PutMappingRequest.java
  server/src/main/java/org/opensearch/action/bulk/BulkItemRequest.java
  server/src/main/java/org/opensearch/action/bulk/BulkShardRequest.java
  server/src/main/java/org/opensearch/action/bulk/BulkShardResponse.java
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
  server/src/main/java/org/opensearch/action/fieldcaps/FieldCapabilitiesIndexRequest.java
  server/src/main/java/org/opensearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java
  server/src/main/java/org/opensearch/action/fieldcaps/FieldCapabilitiesRequest.java
  server/src/main/java/org/opensearch/action/ingest/SimulateProcessorResult.java
  server/src/main/java/org/opensearch/cluster/ClusterInfo.java
  server/src/main/java/org/opensearch/cluster/action/index/MappingUpdatedAction.java
  server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateDataStreamService.java
  server/src/main/java/org/opensearch/index/store/StoreStats.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTransportRequest.java
  server/src/main/java/org/opensearch/indices/recovery/RetryableTransportClient.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationLuceneIndex.java
  server/src/main/java/org/opensearch/script/ScriptStats.java
  server/src/main/java/org/opensearch/search/SearchHit.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/AbstractPercentilesAggregationBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/InternalScriptedMetric.java
  server/src/main/java/org/opensearch/search/aggregations/support/MultiValuesSourceFieldConfig.java
  server/src/main/java/org/opensearch/search/profile/ProfileResult.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/tasks/TaskCancellationService.java
  server/src/test/java/org/opensearch/cluster/action/index/MappingUpdatedActionTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/index/mapper/ParametrizedMapperTests.java
Labels: non-issue, >upgrade, v3.0.0

#4821 Use getParameterCount instead of getParameterTypes
  CHANGELOG.md
  buildSrc/src/testFixtures/java/org/opensearch/gradle/test/JUnit3MethodProvider.java
  client/rest-high-level/src/test/java/org/opensearch/client/RestHighLevelClientTests.java
  modules/lang-painless/src/main/java/org/opensearch/painless/Compiler.java
  modules/lang-painless/src/main/java/org/opensearch/painless/PainlessScriptEngine.java
  modules/lang-painless/src/main/java/org/opensearch/painless/ScriptClassInfo.java
  modules/lang-painless/src/main/java/org/opensearch/painless/lookup/PainlessLookupBuilder.java
  test/logger-usage/src/test/java/org/opensearch/test/loggerusage/OpenSearchLoggerUsageTests.java
Labels: v3.0.0, backport 2.x, backport 2.0, backport 2.1, v2.4.0, backport 2.2, backport 2.3, backport 2.4

#4837 [Remove] LegacyESVersion.V_7_6_* and V_7_7_* constants
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisModulePlugin.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ConcatenateGraphTokenFilterFactory.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/composite/GeoTileGridValuesSourceBuilder.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/GeoGridAggregationBuilder.java
  modules/rank-eval/src/main/java/org/opensearch/index/rankeval/RankEvalRequest.java
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/reload/NodesReloadSecureSettingsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/Alias.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/IndicesAliasesRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeRequest.java
  server/src/main/java/org/opensearch/action/bulk/BulkItemResponse.java
  server/src/main/java/org/opensearch/action/fieldcaps/FieldCapabilities.java
  server/src/main/java/org/opensearch/action/fieldcaps/IndexFieldCapabilities.java
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/action/search/TransportSearchHelper.java
  server/src/main/java/org/opensearch/action/support/IndicesOptions.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinRequest.java
  server/src/main/java/org/opensearch/cluster/metadata/AliasMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/AutoExpandReplicas.java
  server/src/main/java/org/opensearch/cluster/metadata/ComponentTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/DataStreamMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/RepositoryMetadata.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/mapper/RootObjectMapper.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/indices/analysis/AnalysisModule.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/main/java/org/opensearch/ingest/IngestStats.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/script/ScriptException.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/DateHistogramValuesSourceBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
  server/src/main/java/org/opensearch/search/aggregations/support/BaseMultiValuesSourceFieldConfig.java
  server/src/main/java/org/opensearch/search/internal/ShardSearchContextId.java
  server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
  server/src/main/java/org/opensearch/transport/InboundDecoder.java
  server/src/main/java/org/opensearch/transport/OutboundMessage.java
  server/src/main/java/org/opensearch/transport/ProxyConnectionStrategy.java
  server/src/main/java/org/opensearch/transport/RemoteConnectionInfo.java
  server/src/main/java/org/opensearch/transport/TcpHeader.java
  server/src/main/java/org/opensearch/transport/TransportLogger.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
  server/src/test/java/org/opensearch/action/OriginalIndicesTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/shards/ClusterSearchShardsRequestTests.java
  server/src/test/java/org/opensearch/action/admin/indices/close/CloseIndexRequestTests.java
  server/src/test/java/org/opensearch/action/search/TransportSearchHelperTests.java
  server/src/test/java/org/opensearch/transport/InboundDecoderTests.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: non-issue, >upgrade, v3.0.0

#5018 [Remove] LegacyESVersion.V_7_10_* constants
  CHANGELOG.md
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/upgrade/ValidateInputTask.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/upgrade/ValidateInputTaskTests.java
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/GrokProcessorGetAction.java
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/SystemIndicesUpgradeIT.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodeInfo.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/action/index/IndexRequest.java
  server/src/main/java/org/opensearch/action/ingest/SimulateProcessorResult.java
  server/src/main/java/org/opensearch/action/search/SearchResponse.java
  server/src/main/java/org/opensearch/action/search/SearchTransportService.java
  server/src/main/java/org/opensearch/action/update/UpdateRequest.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
  server/src/main/java/org/opensearch/index/query/InnerHitBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchPhrasePrefixQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/PrefixQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/RegexpQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/TermQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/WildcardQueryBuilder.java
  server/src/main/java/org/opensearch/index/stats/IndexingPressureStats.java
  server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalTerms.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/TopHitsAggregationBuilder.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/main/java/org/opensearch/search/dfs/DfsSearchResult.java
  server/src/main/java/org/opensearch/search/fetch/ShardFetchSearchRequest.java
  server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
  server/src/main/java/org/opensearch/search/query/QuerySearchRequest.java
  server/src/main/java/org/opensearch/transport/TransportHandshaker.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/main/java/org/opensearch/transport/TransportStats.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodesTests.java
Labels: non-issue, >upgrade, v3.0.0

#4870 Add remote shards allocator for searchable snapshots
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingPool.java
  server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java
  server/src/test/java/org/opensearch/cluster/routing/AllocationIdTests.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingNodesTests.java
  server/src/test/java/org/opensearch/cluster/routing/ShardRoutingTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsAllocateUnassignedTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsMoveShardsTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsRebalanceShardsTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDeciderTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: backport 2.x, v2.4.0

#5016 [Backport] [1.3] OpenJDK Update (October 2022 Patch releases) (#4998)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport

#5015 [Backport] [2.0] OpenJDK Update (October 2022 Patch releases) (#4997)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport

#5014 [Backport] [2.1] OpenJDK Update (October 2022 Patch releases) (#4997)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport

#5013 [Backport] [2.2] OpenJDK Update (October 2022 Patch releases) (#4997)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport

#5012 [Backport] [2.3] OpenJDK Update (October 2022 Patch releases) (#4997)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport

#5011 [Backport] [2.4] OpenJDK Update (October 2022 Patch releases) (#4997)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport

#5017 [Backport] [2.4] Use getParameterCount instead of getParameterTypes (#4821)
  CHANGELOG.md
  buildSrc/src/testFixtures/java/org/opensearch/gradle/test/JUnit3MethodProvider.java
  client/rest-high-level/src/test/java/org/opensearch/client/RestHighLevelClientTests.java
  modules/lang-painless/src/main/java/org/opensearch/painless/Compiler.java
  modules/lang-painless/src/main/java/org/opensearch/painless/PainlessScriptEngine.java
  modules/lang-painless/src/main/java/org/opensearch/painless/ScriptClassInfo.java
  modules/lang-painless/src/main/java/org/opensearch/painless/lookup/PainlessLookupBuilder.java
  test/logger-usage/src/test/java/org/opensearch/test/loggerusage/OpenSearchLoggerUsageTests.java
Labels: backport

#5040 [Test] Add IAE test for deprecated edgeNGram analyzer name
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisModulePlugin.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/EdgeNGramTokenizerTests.java
Labels: :test, non-issue, v3.0.0

#4892 Implement Searchable Snapshot using OnDemandBlockIndexInput phase 1
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/lucene/store/ByteArrayIndexInput.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/store/InMemoryRemoteSnapshotDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSnapshotDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/remote/directory/package-info.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandVirtualFileSnapshotIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/file/package-info.java
  server/src/main/java/org/opensearch/index/store/remote/package-info.java
  server/src/main/java/org/opensearch/index/store/remote/utils/BlobFetchRequest.java
  server/src/main/java/org/opensearch/index/store/remote/utils/ConcurrentInvocationLinearizer.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/main/java/org/opensearch/index/store/remote/utils/package-info.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/common/lucene/store/ByteArrayIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/ConcurrentInvocationLinearizerTests.java
Labels: backport 2.x, v2.4.0, backport 2.4

#5021 [Remove] Version.V_1_ constants
  CHANGELOG.md
  client/rest-high-level/src/test/java/org/opensearch/client/core/MainResponseTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/EdgeNGramTokenizerTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/SynonymsAnalysisTests.java
  plugins/analysis-phonetic/src/test/java/org/opensearch/index/analysis/AnalysisPhoneticFactoryTests.java
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/health/ClusterStateHealth.java
  server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java
  server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java
  server/src/main/java/org/opensearch/index/query/functionscore/ScoreFunctionBuilder.java
  server/src/main/java/org/opensearch/monitor/jvm/JvmStats.java
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
  server/src/main/java/org/opensearch/transport/TransportHandshaker.java
  server/src/test/java/org/opensearch/BuildTests.java
  server/src/test/java/org/opensearch/VersionTests.java
  server/src/test/java/org/opensearch/action/main/MainResponseTests.java
  server/src/test/java/org/opensearch/action/search/MultiSearchRequestTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
  server/src/test/java/org/opensearch/action/support/IndicesOptionsTests.java
  server/src/test/java/org/opensearch/cluster/metadata/AutoExpandReplicasTests.java
  server/src/test/java/org/opensearch/common/lucene/uid/VersionsTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/mapper/ParametrizedMapperTests.java
  server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
  server/src/test/java/org/opensearch/transport/InboundDecoderTests.java
  server/src/test/java/org/opensearch/transport/TransportHandshakerTests.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: non-issue, v3.0.0

#5068 Add integration tests for searchable snapshots, Fix length calculation for block based storage
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/utils/BlobFetchRequest.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: v2.4.0

#4708 [Backport] [2.x] Fixed misunderstanding message 'No OpenSearchException found' when detailed_error disabled
  CHANGELOG.md
  server/src/main/java/org/opensearch/ExceptionsHelper.java
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/test/java/org/opensearch/ExceptionsHelperTests.java
  server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
  server/src/test/java/org/opensearch/rest/BytesRestResponseTests.java
Labels: enhancement, backport, v2.4.0, backport 2.4

#5081 Change the output error message back to use OpenSearchException in the cause chain
  CHANGELOG.md
  server/src/main/java/org/opensearch/OpenSearchException.java
Labels: backport 2.x, backport 2.4

#5048 Add allocation tests for searchable snapshot remote shards
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: backport 2.x

#5105 Update Jackson to 2.14.0
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.13.4.jar.sha1
  client/sniffer/licenses/jackson-core-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.4.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.4.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.0.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.0.jar.sha1
Labels: backport 1.x, dependencies, backport 2.x, backport 2.0, backport 1.3, backport 2.1, backport 2.2, backport 2.3, backport 2.4

#5111 [Backport] [2.1] Update Jackson to 2.14.0 (#5105)
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.13.4.jar.sha1
  client/sniffer/licenses/jackson-core-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.0.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.0.jar.sha1
Labels: backport

#5112 [Backport] [2.0] Update Jackson to 2.14.0 (#5105)
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.13.4.jar.sha1
  client/sniffer/licenses/jackson-core-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.0.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.0.jar.sha1
Labels: backport

#5109 [Backport] [2.3] Update Jackson to 2.14.0 (#5105)
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.13.4.jar.sha1
  client/sniffer/licenses/jackson-core-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.4.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.4.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.0.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.0.jar.sha1
Labels: backport

#5108 [Backport] [2.4] Update Jackson to 2.14.0 (#5105)
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.13.4.jar.sha1
  client/sniffer/licenses/jackson-core-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.4.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.4.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.0.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.0.jar.sha1
Labels: backport

#5113 [Backport] [1.3] Update Jackson to 2.14.0 (#5105)
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.13.4.jar.sha1
  client/sniffer/licenses/jackson-core-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.13.4.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.4.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.13.4.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.4.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.0.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.0.jar.sha1
Labels: backport

#5088 Add support for skipping changelog
  .github/workflows/changelog_verifier.yml
Labels: skip-changelog

#5131 [Backport 2.4] Bump nebula-publishing-plugin from v4.4.0 to v4.6.0
  CHANGELOG.md
  buildSrc/build.gradle
Labels: bug, backport

#5137 Upgrade com.netflix.nebula:nebula-publishing-plugin to 4.6.0 and gradle-docker-compose-plugin to 0.14.12.
  buildSrc/build.gradle
  buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java
Labels: skip-changelog

#5138 Upgrade com.netflix.nebula:nebula-publishing-plugin to 4.6.0.
  buildSrc/build.gradle
Labels: skip-changelog

#5144 Only run backport workflow it a backport label was added.
  .github/workflows/backport.yml
Labels: backport 1.x, backport 2.x, skip-changelog

#5142 [Backport 2.x] Fix error handling while reading analyzer mapping rules.
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/HyphenationCompoundWordTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/MappingCharFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerOverrideTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterGraphTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/WordDelimiterTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/BaseWordDelimiterTokenFilterFactoryTestCase.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/MappingCharFilterFactoryTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/StemmerOverrideTokenFilterFactoryTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/SynonymsAnalysisTests.java
  plugins/analysis-icu/src/main/java/org/opensearch/index/analysis/IcuCollationTokenFilterFactory.java
  plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiPartOfSpeechFilterFactory.java
  plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiTokenizerFactory.java
  plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/KuromojiAnalysisTests.java
  plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriAnalyzerProvider.java
  plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriPartOfSpeechStopFilterFactory.java
  plugins/analysis-nori/src/main/java/org/opensearch/index/analysis/NoriTokenizerFactory.java
  release-notes/opensearch.release-notes-2.4.0.md
  server/src/main/java/org/opensearch/index/analysis/Analysis.java
  server/src/main/java/org/opensearch/index/analysis/CustomMappingRuleParser.java
  server/src/main/java/org/opensearch/index/analysis/MappingRule.java
  server/src/main/java/org/opensearch/indices/analysis/HunspellService.java
  server/src/test/java/org/opensearch/index/analysis/AnalysisTests.java
  server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
  server/src/test/java/org/opensearch/indices/analyze/HunspellServiceTests.java
Labels: skip-changelog

#5152 Fix: org.opensearch.clustermanager.ClusterManagerTaskThrottlingIT is flaky.
  server/src/internalClusterTest/java/org/opensearch/clustermanager/ClusterManagerTaskThrottlingIT.java
Labels: skip-changelog

#5143 Fix: raise error on malformed CSV.
  plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiTokenizerFactory.java
  plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/KuromojiAnalysisTests.java
Labels: skip-changelog

#5151 Allow mmap to use new preview JDK-19 APIs in Apache Lucene 9.4+
  CHANGELOG.md
  build.gradle
  distribution/src/config/jvm.options
Labels: v3.0.0

#5158 Fix test to use a file from another temp directory
  server/src/test/java/org/opensearch/index/analysis/AnalysisTests.java
Labels: :test, backport 1.x, backport 2.x, backport 1.3, backport 2.4, skip-changelog

#5159 Fix race condition in testThrottlingForSingleNode.
  server/src/internalClusterTest/java/org/opensearch/clustermanager/ClusterManagerTaskThrottlingIT.java
Labels: skip-changelog

#5169 Cleanup: remove unused semicolon
  modules/percolator/src/main/java/org/opensearch/percolator/PercolateQueryBuilder.java
Labels: backport 1.x, backport 2.x, backport 2.0, backport 1.3, backport 2.1, backport 2.2, backport 2.3, backport 2.4, skip-changelog

#5168 Fix boundary condition in indexing pressure test
  server/src/test/java/org/opensearch/index/ShardIndexingPressureConcurrentExecutionTests.java
Labels: skip-changelog

#5188 [BUG] Gradle Check Failed on Windows due to JDK19 pulling by gradle
  buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
  gradle/runtime-jdk-provision.gradle
Labels: bug, skip-changelog

#5194 Add jvm option to allow security manager
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
  distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/SystemJvmOptions.java
Labels: :test

#5207 [Backport 2.x] Ignore lock file when testing cleanupAndPreserveLatestCommitPoint (#4544)
  server/src/test/java/org/opensearch/index/store/StoreTests.java
Labels: skip-changelog

#5205 Check for JDK version while setting java.security.manager option
  buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
  distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/SystemJvmOptions.java
Labels: skip-changelog

#5212 Clean up common logging code
  client/rest/src/main/java/org/opensearch/client/Response.java
  server/src/main/java/org/opensearch/common/logging/HeaderWarning.java
  server/src/main/java/org/opensearch/common/logging/LogConfigurator.java
  server/src/main/java/org/opensearch/common/logging/LoggerMessageFormat.java
Labels: skip-changelog

#5216 Update Gradle to 7.6-rc3
  gradle/wrapper/gradle-wrapper.properties
Labels: skip-changelog

#5225 Remove spotless exclusion for HyperLogLogPlusPlus
  server/build.gradle
  server/src/main/java/org/opensearch/search/aggregations/metrics/HyperLogLogPlusPlus.java
Labels: backport 2.x, skip-changelog

#5228 Remove changes for legacy mixed-cluster support
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RefreshVersionInClusterStateIT.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
Labels: skip-changelog

#5250 Revert changes in AbstractPointGeometryFieldMapper
  server/src/main/java/org/opensearch/index/mapper/AbstractPointGeometryFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/GeoPointFieldMapperTests.java
Labels: skip-changelog

#5246 Revert changes in AbstractPointGeometryFieldMapper
  server/src/main/java/org/opensearch/index/mapper/AbstractPointGeometryFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/GeoPointFieldMapperTests.java
Labels: skip-changelog

#5252 Fix AwarenessAttributeDecommissionIT flaky tests
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
Labels: skip-changelog

#5258 Remove unused classes
  server/src/main/java/org/opensearch/action/ThreadingModel.java
  server/src/main/java/org/opensearch/cluster/MergableCustomMetadata.java
  server/src/main/java/org/opensearch/common/inject/PreProcessModule.java
  server/src/main/java/org/opensearch/common/inject/internal/ErrorHandler.java
  server/src/main/java/org/opensearch/common/inject/internal/UniqueAnnotations.java
  server/src/main/java/org/opensearch/common/inject/spi/DefaultBindingTargetVisitor.java
  server/src/main/java/org/opensearch/common/util/CombinedRateLimiter.java
  server/src/main/java/org/opensearch/discovery/AckClusterStatePublishResponseHandler.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/SizedBucketAggregatorBuilder.java
  server/src/main/java/org/opensearch/transport/FutureTransportResponseHandler.java
Labels: skip-changelog

#5200 Display test failures in the gradle check status report.
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#4954 Remove PRRL creation/deletion in peer recovery of remote store enabled replica
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoverySourceService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandlerFactory.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandler.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#5279 Add condition to check JVM version for illegal-access switch
  buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
Labels: skip-changelog

#5284 Report test failures on 'flaky' success
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#5278 Fix test failing due to too long http line exception
  test/framework/src/main/java/org/opensearch/test/rest/yaml/ClientYamlTestClient.java
Labels: skip-changelog

#5286 [Backport 2.x] Fix test failing due to too long http line exception (#5278)
  test/framework/src/main/java/org/opensearch/test/rest/yaml/ClientYamlTestClient.java
Labels: skip-changelog

#5262 Make viaNode more deterministic for AwarenessAttributeDecommissionIT tests
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
Labels: skip-changelog

#5285 Fix flaky test AggregationsTests.testFromXContent
  server/src/test/java/org/opensearch/search/aggregations/AggregationsTests.java
Labels: skip-changelog

#5290 Prettify test failures.
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#5265 Fix typo in comment in OpenSearchException
  server/src/main/java/org/opensearch/OpenSearchException.java
Labels: skip-changelog

#5288 Cleanup unused code in org.opensearch.common
  server/src/main/java/org/opensearch/common/Classes.java
  server/src/main/java/org/opensearch/common/LegacyTimeBasedUUIDGenerator.java
  server/src/main/java/org/opensearch/common/Numbers.java
  server/src/main/java/org/opensearch/common/RandomBasedUUIDGenerator.java
  server/src/main/java/org/opensearch/common/Strings.java
  server/src/main/java/org/opensearch/common/UUIDs.java
Labels: skip-changelog

#5297 Fix test failures display.
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#5300 [Backport 2.x] #5297 ++
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#5303 Remove support for legacy es test clusters
  buildSrc/reaper/src/main/java/org/elasticsearch/gradle/reaper/package-info.java
  buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClustersAware.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClustersPlugin.java
  buildSrc/src/test/java/org/opensearch/gradle/DistributionDownloadPluginTests.java
Labels: skip-changelog

#5289 [BUG] OperationRoutingTests.testWeightedOperationRoutingWeightUndefinedForOneZone failure
  server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java
Labels: skip-changelog

#5312 Remove invalid unreleased versions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#5311 Cleanup BWC versions
  .ci/bwcVersions
  buildSrc/src/main/java/org/opensearch/gradle/BwcVersions.java
  buildSrc/src/test/java/org/opensearch/gradle/BwcOpenSearchVersionsTests.java
  qa/full-cluster-restart/build.gradle
  qa/repository-multi-version/build.gradle
  qa/verify-version-constants/build.gradle
Labels: skip-changelog

#5321 Fix flaky test testReplicaReceivesGenIncrease.
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#5325 [BUG] org.opensearch.repositories.s3.RepositoryS3ClientYamlTestSuiteIT/test {yaml=repository_s3/20_repository_permanent_credentials/Snapshot and Restore with repository-s3 using permanent credentials} flaky
  test/fixtures/minio-fixture/Dockerfile
  test/fixtures/minio-fixture/docker-compose.yml
Labels: skip-changelog

#5328 Fix URLDecodeProcessor random test failure
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/URLDecodeProcessor.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/URLDecodeProcessorTests.java
Labels: skip-changelog

#5339 [Backport] [1.3] [BUG] org.opensearch.repositories.s3.RepositoryS3ClientYamlTestSuiteIT/test {yaml=repository_s3/20_repository_permanent_credentials/Snapshot and Restore with repository-s3 using permanent credentials} flaky (#5325)
  test/fixtures/minio-fixture/Dockerfile
  test/fixtures/minio-fixture/docker-compose.yml
Labels: backport, skip-changelog

#5338 [Backport] [1.x] [BUG] org.opensearch.repositories.s3.RepositoryS3ClientYamlTestSuiteIT/test {yaml=repository_s3/20_repository_permanent_credentials/Snapshot and Restore with repository-s3 using permanent credentials} flaky (#5325)
  test/fixtures/minio-fixture/Dockerfile
  test/fixtures/minio-fixture/docker-compose.yml
Labels: backport, skip-changelog

#5308 Adding integration tests for search backpressure
  server/src/internalClusterTest/java/org/opensearch/search/backpressure/SearchBackpressureIT.java
Labels: skip-changelog

#5345 Update Gradle to 7.6-rc-4
  gradle/wrapper/gradle-wrapper.properties
Labels: skip-changelog

#5346 Update Jackson to 2.14.1
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.14.0.jar.sha1
  client/sniffer/licenses/jackson-core-2.14.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.1.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.1.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.1.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.1.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.1.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.1.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.1.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.14.1.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.1.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.1.jar.sha1
Labels: dependencies, skip-changelog

#5349 Retry tests only on CI server
  build.gradle
Labels: skip-changelog

#5354 Update Apache Lucene to 9.4.2
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.4.1.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.4.2.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.4.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.4.2.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.4.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.4.2.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.4.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.4.2.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.4.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.4.2.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.4.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.4.2.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.4.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.4.2.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.4.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.4.2.jar.sha1
  server/licenses/lucene-analysis-common-9.4.1.jar.sha1
  server/licenses/lucene-analysis-common-9.4.2.jar.sha1
  server/licenses/lucene-backward-codecs-9.4.1.jar.sha1
  server/licenses/lucene-backward-codecs-9.4.2.jar.sha1
  server/licenses/lucene-core-9.4.1.jar.sha1
  server/licenses/lucene-core-9.4.2.jar.sha1
  server/licenses/lucene-grouping-9.4.1.jar.sha1
  server/licenses/lucene-grouping-9.4.2.jar.sha1
  server/licenses/lucene-highlighter-9.4.1.jar.sha1
  server/licenses/lucene-highlighter-9.4.2.jar.sha1
  server/licenses/lucene-join-9.4.1.jar.sha1
  server/licenses/lucene-join-9.4.2.jar.sha1
  server/licenses/lucene-memory-9.4.1.jar.sha1
  server/licenses/lucene-memory-9.4.2.jar.sha1
  server/licenses/lucene-misc-9.4.1.jar.sha1
  server/licenses/lucene-misc-9.4.2.jar.sha1
  server/licenses/lucene-queries-9.4.1.jar.sha1
  server/licenses/lucene-queries-9.4.2.jar.sha1
  server/licenses/lucene-queryparser-9.4.1.jar.sha1
  server/licenses/lucene-queryparser-9.4.2.jar.sha1
  server/licenses/lucene-sandbox-9.4.1.jar.sha1
  server/licenses/lucene-sandbox-9.4.2.jar.sha1
  server/licenses/lucene-spatial-extras-9.4.1.jar.sha1
  server/licenses/lucene-spatial-extras-9.4.2.jar.sha1
  server/licenses/lucene-spatial3d-9.4.1.jar.sha1
  server/licenses/lucene-spatial3d-9.4.2.jar.sha1
  server/licenses/lucene-suggest-9.4.1.jar.sha1
  server/licenses/lucene-suggest-9.4.2.jar.sha1
  server/src/main/java/org/opensearch/Version.java
Labels: dependencies, skip-changelog

#5360 Update OpenSearch 2.5.0 version to Apache Lucene 9.4.2
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#5368 Use BuildParams.isCi() instead of checking env var
  build.gradle
Labels: skip-changelog

#5374 [Backport] [1.x] Use BuildParams.isCi() instead of checking env var (#5368)
  build.gradle
Labels: backport, skip-changelog

#5373 [Backport] [2.4] Use BuildParams.isCi() instead of checking env var (#5368)
  build.gradle
Labels: backport, skip-changelog

#5378 Update Apache HttpClient5 to 5.1.4 and Apache HttpCore5 to 5.1.5
  buildSrc/version.properties
  client/rest/licenses/httpclient5-5.1.3.jar.sha1
  client/rest/licenses/httpclient5-5.1.4.jar.sha1
  client/rest/licenses/httpcore5-5.1.4.jar.sha1
  client/rest/licenses/httpcore5-5.1.5.jar.sha1
  client/rest/licenses/httpcore5-h2-5.1.4.jar.sha1
  client/rest/licenses/httpcore5-h2-5.1.5.jar.sha1
  client/sniffer/licenses/httpclient5-5.1.3.jar.sha1
  client/sniffer/licenses/httpclient5-5.1.4.jar.sha1
  client/sniffer/licenses/httpcore5-5.1.4.jar.sha1
  client/sniffer/licenses/httpcore5-5.1.5.jar.sha1
Labels: dependencies, skip-changelog

#5372 [Backport] [2.x] Use BuildParams.isCi() instead of checking env var (#5368)
  build.gradle
Labels: backport, skip-changelog

#5381 Update Gradle to 7.6
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: skip-changelog

#5375 [Backport] [1.3] Use BuildParams.isCi() instead of checking env var (#5368)
  build.gradle
Labels: backport, skip-changelog

#5383 [2.x] Bump test-retry from 1.3.2 to 1.4.1
  build.gradle
Labels: skip-changelog

#5382 [Backport] [2.x] Update Gradle to 7.6
  CHANGELOG.md
  buildSrc/build.gradle
  buildSrc/src/main/java/org/opensearch/gradle/info/GlobalBuildInfoPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditPrecommitPlugin.java
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  test/framework/build.gradle
Labels: backport

#5361 Update Apache Lucene to 9.4.2 (#5354)
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.4.1.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.4.2.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.4.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.4.2.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.4.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.4.2.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.4.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.4.2.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.4.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.4.2.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.4.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.4.2.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.4.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.4.2.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.4.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.4.2.jar.sha1
  server/licenses/lucene-analysis-common-9.4.1.jar.sha1
  server/licenses/lucene-analysis-common-9.4.2.jar.sha1
  server/licenses/lucene-backward-codecs-9.4.1.jar.sha1
  server/licenses/lucene-backward-codecs-9.4.2.jar.sha1
  server/licenses/lucene-core-9.4.1.jar.sha1
  server/licenses/lucene-core-9.4.2.jar.sha1
  server/licenses/lucene-grouping-9.4.1.jar.sha1
  server/licenses/lucene-grouping-9.4.2.jar.sha1
  server/licenses/lucene-highlighter-9.4.1.jar.sha1
  server/licenses/lucene-highlighter-9.4.2.jar.sha1
  server/licenses/lucene-join-9.4.1.jar.sha1
  server/licenses/lucene-join-9.4.2.jar.sha1
  server/licenses/lucene-memory-9.4.1.jar.sha1
  server/licenses/lucene-memory-9.4.2.jar.sha1
  server/licenses/lucene-misc-9.4.1.jar.sha1
  server/licenses/lucene-misc-9.4.2.jar.sha1
  server/licenses/lucene-queries-9.4.1.jar.sha1
  server/licenses/lucene-queries-9.4.2.jar.sha1
  server/licenses/lucene-queryparser-9.4.1.jar.sha1
  server/licenses/lucene-queryparser-9.4.2.jar.sha1
  server/licenses/lucene-sandbox-9.4.1.jar.sha1
  server/licenses/lucene-sandbox-9.4.2.jar.sha1
  server/licenses/lucene-spatial-extras-9.4.1.jar.sha1
  server/licenses/lucene-spatial-extras-9.4.2.jar.sha1
  server/licenses/lucene-spatial3d-9.4.1.jar.sha1
  server/licenses/lucene-spatial3d-9.4.2.jar.sha1
  server/licenses/lucene-suggest-9.4.1.jar.sha1
  server/licenses/lucene-suggest-9.4.2.jar.sha1
  server/src/main/java/org/opensearch/Version.java
Labels: backport, skip-changelog

#5393 Update Apache Lucene to 9.4.2 for OpenSearch 2.4.1
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#5394 Update Apache Lucene to 9.4.2 for OpenSearch 2.4.1
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#5397 Skip Test OnDemandBlockSnapshotIndexInputTests.testVariousBlockSize on Windows.
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
Labels: skip-changelog

#5405 Fix for windows failing test InternalDistributionArchiveCheckPluginFu…
  buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPluginFuncTest.groovy
Labels: skip-changelog

#5399 Fix IndexShardTests.testRestoreShardFromRemoteStore on Windows.
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Labels: skip-changelog
