Repository opensearch-project/OpenSearch, pull requests merged in 2022-10, with the labels that each got.

#4570 Fix SnapshotsInProgress bug during index deletion
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Labels: bug, v3.0.0, backport 2.x, v2.4.0, backport 2.3

#4627 Fixed day of year defaulting for round up parser
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/time/EpochTime.java
  server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java
  server/src/test/java/org/opensearch/common/time/JavaDateMathParserTests.java
Labels: bug, v3.0.0, backport 2.x, v2.4.0

#4636 Add getter for path field in NestedQueryBuilder
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
Labels: enhancement, v3.0.0, backport 2.x

#4660 Pre-commit checks now check for missing javadoc, and the Gradle check Jenkins build now waits for pre-commit checks to pass before attempting
  .github/workflows/gradle-check.yml
  .github/workflows/precommit.yml
  CHANGELOG.md
Labels: CI, v3.0.0, backport 2.x, hacktoberfest

#4647 [Backport 2.x] Bumping hadoop-hdfs version to 3.3.4
  CHANGELOG.md
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/hadoop-client-api-3.3.3.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-api-3.3.4.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-runtime-3.3.3.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-runtime-3.3.4.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-3.3.3.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-3.3.4.jar.sha1
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport, >upgrade, dependencies, v2.4.0

#4676 Adding precommit support for Windows
  .github/workflows/precommit.yml
  CHANGELOG.md
Labels: CI, windows, v3.0.0

#4682 Adding precommit support for MacOS (darwin)
  .github/workflows/precommit.yml
  CHANGELOG.md
Labels: CI, macos

#4669 Fixed misunderstanding message 'No OpenSearchException found' when detailed_error disabled
  CHANGELOG.md
  server/src/main/java/org/opensearch/ExceptionsHelper.java
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/test/java/org/opensearch/ExceptionsHelperTests.java
  server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
  server/src/test/java/org/opensearch/rest/BytesRestResponseTests.java
Labels: backport 2.x

#4703 Always auto release the flood stage block
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdSettings.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/DiskThresholdSettingsTests.java
Labels: non-issue, >breaking, v3.0.0

#4709 [2.x] Add BWC version 1.3.7
  .ci/bwcVersions
  CHANGELOG.md
  server/src/main/java/org/opensearch/Version.java
Labels: CI, v2.4.0

#4702 [Remove] LegacyESVersion.V_7_2_* and V_7_3_* constants
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisModulePlugin.java
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/FullClusterRestartIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/RecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/ReplicaShardAllocatorIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesLifecycleListenerIT.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/hotthreads/TransportNodesHotThreadsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/TransportNodesInfoAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/reload/TransportNodesReloadSecureSettingsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/usage/TransportNodesUsageAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportNodesSnapshotsStatus.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/IndicesAliasesRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/analyze/AnalyzeAction.java
  server/src/main/java/org/opensearch/action/admin/indices/close/CloseIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/close/CloseIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/close/TransportVerifyShardBeforeCloseAction.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/find/NodeFindDanglingIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/list/NodeListDanglingIndicesRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
  server/src/main/java/org/opensearch/action/fieldcaps/FieldCapabilitiesRequest.java
  server/src/main/java/org/opensearch/action/fieldcaps/FieldCapabilitiesResponse.java
  server/src/main/java/org/opensearch/action/search/GetAllPitNodeRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/BaseNodeRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java
  server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexStateService.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/get/GetResult.java
  server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java
  server/src/main/java/org/opensearch/index/refresh/RefreshStats.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryCleanFilesRequest.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTranslogOperationsRequest.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregationBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateIntervalWrapper.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/InternalGeoCentroid.java
  server/src/main/java/org/opensearch/search/query/QuerySearchResult.java
  server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
  server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/CancellableTasksTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/TaskManagerTestCase.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/TestTaskPlugin.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/TransportTasksActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/close/CloseIndexRequestTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesActionTests.java
  server/src/test/java/org/opensearch/action/termvectors/TermVectorsUnitTests.java
Labels: non-issue, >upgrade, v3.0.0

#4704 [Remove] LegacyESVersion.V_7_4_* and V_7_5_* constants
  CHANGELOG.md
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
  server/src/main/java/org/opensearch/LegacyESVersion.java
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/reload/NodesReloadSecureSettingsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/repositories/cleanup/TransportCleanupRepositoryAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/TransportCreateSnapshotAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotStatus.java
  server/src/main/java/org/opensearch/action/admin/indices/shards/IndicesShardStoresResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeRequest.java
  server/src/main/java/org/opensearch/action/index/IndexRequest.java
  server/src/main/java/org/opensearch/action/ingest/SimulateDocumentBaseResult.java
  server/src/main/java/org/opensearch/cluster/RepositoryCleanupInProgress.java
  server/src/main/java/org/opensearch/cluster/routing/UnassignedInfo.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/query/VectorGeoShapeQueryProcessor.java
  server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreQueryBuilder.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryFinalizeRecoveryRequest.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryPrepareForTranslogOperationsRequest.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryState.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/main/java/org/opensearch/repositories/FilterRepository.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/repositories/blobstore/package-info.java
  server/src/main/java/org/opensearch/rest/action/document/RestIndexAction.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceParserHelper.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/MovFnPipelineAggregationBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/MovFnPipelineAggregator.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/index/query/GeoShapeQueryBuilderGeoShapeTests.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
  test/framework/src/main/java/org/opensearch/index/shard/RestoreOnlyRepository.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: non-issue, >upgrade, v3.0.0

#4712 Bump jettison version from 1.5.0 to 1.5.1
  CHANGELOG.md
  plugins/discovery-azure-classic/build.gradle
  plugins/discovery-azure-classic/licenses/jettison-1.4.1.jar.sha1
  plugins/discovery-azure-classic/licenses/jettison-1.5.1.jar.sha1
Labels: CVE, >upgrade, dependencies

#4653 [2.x] Load the deprecated master role in a dedocated method instead of in setAdditionalRoles()
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeRoleSettingTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/node/NodeRoleSettingsTests.java
Labels: enhancement, backport, v2.4.0

#4717 [2.x] Bump jettison version from 1.4.1 to 1.5.1
  CHANGELOG.md
  plugins/discovery-azure-classic/build.gradle
  plugins/discovery-azure-classic/licenses/jettison-1.4.1.jar.sha1
  plugins/discovery-azure-classic/licenses/jettison-1.5.1.jar.sha1
Labels: CVE, >upgrade, dependencies

#4732 [Refactor] Base Action class javadocs to OpenSearch.API
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/ActionFuture.java
  server/src/main/java/org/opensearch/action/ActionListener.java
  server/src/main/java/org/opensearch/action/ActionListenerResponseHandler.java
  server/src/main/java/org/opensearch/action/ActionRequest.java
  server/src/main/java/org/opensearch/action/ActionRequestBuilder.java
  server/src/main/java/org/opensearch/action/ActionRequestValidationException.java
  server/src/main/java/org/opensearch/action/ActionResponse.java
  server/src/main/java/org/opensearch/action/ActionRunnable.java
  server/src/main/java/org/opensearch/action/ActionType.java
Labels: documentation, enhancement, v3.0.0, backport 2.x, extensions

#4689 Add a new node role 'search' which is dedicated to provide search capability
  CHANGELOG.md
  client/rest/src/main/java/org/opensearch/client/Node.java
  client/rest/src/test/java/org/opensearch/client/NodeTests.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
Labels: enhancement, Indexing & Search, v3.0.0, backport 2.x, v2.4.0

#4729 [Deprecate] RepositoryData.MIN_VERSION for removal in next major release
  CHANGELOG.md
  server/src/main/java/org/opensearch/repositories/RepositoryData.java
Labels: non-issue, deprecate, v2.4.0

#4739 [2.x] Add a new node role 'search' which is dedicated to provide search capability (#4689)
  CHANGELOG.md
  client/rest/src/main/java/org/opensearch/client/Node.java
  client/rest/src/test/java/org/opensearch/client/NodeTests.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
Labels: enhancement, backport, Indexing & Search, v2.4.0

#4733 [Backport 2.x] ZIP publication groupId value is configurable (#4156) …
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
  buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
  buildSrc/src/test/resources/pluginzip/customizedGroupValue.gradle
  buildSrc/src/test/resources/pluginzip/customizedInvalidGroupValue.gradle
  buildSrc/src/test/resources/pluginzip/missingGroupValue.gradle
  buildSrc/src/test/resources/pluginzip/missingPOMEntity.gradle
  buildSrc/src/test/resources/pluginzip/missingPublications.gradle
  buildSrc/src/test/resources/pluginzip/publishToMavenLocal.gradle
  buildSrc/src/test/resources/pluginzip/useDefaultValues.gradle
Labels: v2.4.0

#4742 [Backport] [2.x] Fixing Gradle warnings associated with publishPluginZipPublicationToXxx tasks
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
Labels: v2.4.0

#4738 Better plural stemmer than minimal_english
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/EnglishPluralStemFilter.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/StemmerTokenFilterFactoryTests.java
Labels: enhancement, Indexing & Search, v3.0.0, backport 2.x

#4754 Install and configure Log4j JUL adapter for Lucene 9.4
  CHANGELOG.md
  client/rest/build.gradle
  qa/os/build.gradle
  server/build.gradle
  server/licenses/log4j-jul-2.17.1.jar.sha1
  server/licenses/log4j-jul-LICENSE.txt
  server/licenses/log4j-jul-NOTICE.txt
  server/src/main/java/org/opensearch/common/logging/LogConfigurator.java
Labels: enhancement, v3.0.0, backport 2.x

#4779 Update Jackson Databind to 2.13.4.2 (addressing CVE-2022-42003)
  CHANGELOG.md
  buildSrc/version.properties
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.4.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.13.4.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.4.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-hdfs/licenses/jackson-databind-2.13.4.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.4.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.13.4.jar.sha1
Labels: security, >upgrade, backport 1.x, dependencies, v3.0.0, backport 2.x, backport 2.0, backport 1.3, backport 2.1, backport 2.2, backport 2.3

#4786 Update version check after backport
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
Labels: backport 2.x

#4791 Bump Tika from 2.4.0 to 2.5.0 addressing CVE-2022-33879.
  CHANGELOG.md
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/tika-core-2.4.0.jar.sha1
  plugins/ingest-attachment/licenses/tika-core-2.5.0.jar.sha1
  plugins/ingest-attachment/licenses/tika-langdetect-optimaize-2.4.0.jar.sha1
  plugins/ingest-attachment/licenses/tika-langdetect-optimaize-2.5.0.jar.sha1
  plugins/ingest-attachment/licenses/tika-parsers-standard-package-2.4.0.jar.sha1
  plugins/ingest-attachment/licenses/tika-parsers-standard-package-2.5.0.jar.sha1
Labels: >upgrade, dependencies, v3.0.0, backport 2.x

#4813 Fix recovery path for searchable snapshots
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
Labels: backport 2.x

#4758 [Backport 2.x] Install and configure Log4j JUL adapter for Lucene 9.4 (#4754)
  CHANGELOG.md
  client/rest/build.gradle
  qa/os/build.gradle
  server/build.gradle
  server/licenses/log4j-jul-2.17.1.jar.sha1
  server/licenses/log4j-jul-LICENSE.txt
  server/licenses/log4j-jul-NOTICE.txt
  server/src/main/java/org/opensearch/common/logging/LogConfigurator.java
Labels: enhancement, backport, v2.4.0

#4828 Disable merge on refresh in DiskThresholdDeciderIT
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
Labels: bug, :test, v3.0.0, backport 2.x

#4772 Add groupId value propagation tests for ZIP publication task
  CHANGELOG.md
  buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
  buildSrc/src/test/resources/pluginzip/allProjectsGroup.gradle
  buildSrc/src/test/resources/pluginzip/groupPriorityLevel.gradle
Labels: Build Libraries & Interfaces, backport 2.x

#4833 [Backport 2.x] Disable merge on refresh in DiskThresholdDeciderIT (#4828)
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
Labels: :test, backport, cicd, v2.4.0

#4728 [Remove] Legacy Version support from Snapshot/Restore Service
  CHANGELOG.md
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  qa/repository-multi-version/src/test/java/org/opensearch/upgrades/MultiVersionRepositoryAccessIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/CorruptedBlobStoreRepositoryIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/delete/DeleteSnapshotRequest.java
  server/src/main/java/org/opensearch/cluster/SnapshotDeletionsInProgress.java
  server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
  server/src/main/java/org/opensearch/repositories/IndexMetaDataGenerations.java
  server/src/main/java/org/opensearch/repositories/RepositoryData.java
  server/src/main/java/org/opensearch/repositories/ShardGenerations.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/repositories/RepositoryDataTests.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: non-issue, >upgrade, v3.0.0

#4834 [Backport 2.x] Better plural stemmer than minimal_english (#4738)
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/EnglishPluralStemFilter.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/StemmerTokenFilterFactoryTests.java
Labels: enhancement, backport, Indexing & Search, v2.4.0

#4847 [Remove] Deprecated serialization logic from pipeline aggs
  CHANGELOG.md
  server/src/main/java/org/opensearch/plugins/SearchPlugin.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationPhase.java
  server/src/main/java/org/opensearch/search/aggregations/InternalAggregation.java
  server/src/main/java/org/opensearch/search/aggregations/InternalAggregations.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/AvgBucketPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/BucketMetricsPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/BucketScriptPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/BucketSelectorPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/BucketSortPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/CumulativeSumPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/DerivativePipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/ExtendedStatsBucketPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/MaxBucketPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/MinBucketPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/MovAvgPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/MovFnPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/PercentilesBucketPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/PipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/SerialDiffPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/SiblingPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/StatsBucketPipelineAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/pipeline/SumBucketPipelineAggregator.java
  server/src/main/java/org/opensearch/search/query/QuerySearchResult.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
  server/src/test/java/org/opensearch/search/aggregations/InternalAggregationsTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/SignificanceHeuristicTests.java
  test/framework/src/main/java/org/opensearch/test/InternalAggregationTestCase.java
Labels: non-issue, >upgrade, v3.0.0

#4841 [Backport 1.x] Exclude jettison version brought in with hadoop-minicluster
  CHANGELOG.md
  buildSrc/version.properties
  plugins/discovery-azure-classic/build.gradle
  plugins/discovery-azure-classic/licenses/jettison-1.1.jar.sha1
  plugins/discovery-azure-classic/licenses/jettison-1.5.1.jar.sha1
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport

#4812 Compatibility issue with /_mget: RHLC 2.x connected to OpenSearch Cluster 1.x
  CHANGELOG.md
  qa/mixed-cluster/build.gradle
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/SearchingIT.java
  server/src/main/java/org/opensearch/action/get/MultiGetResponse.java
Labels: v3.0.0, backport 2.x, backport 2.0, backport 2.1, backport 2.2, backport 2.3

#4848 [Backport 2.x] Add groupId value propagation tests for ZIP publication task
  CHANGELOG.md
  buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
  buildSrc/src/test/resources/pluginzip/allProjectsGroup.gradle
  buildSrc/src/test/resources/pluginzip/groupPriorityLevel.gradle
Labels: backport

#4722 Add missing no jdk distributions
  CHANGELOG.md
  distribution/README.md
  distribution/archives/build.gradle
  distribution/packages/build.gradle
  settings.gradle
Labels: v3.0.0, backport 2.x, backport 2.3

#4878 [Backport] [2.1] Compatibility issue with /_mget: RHLC 2.x connected to OpenSearch Cluster 1.x (#4812)
  .ci/bwcVersions
  qa/mixed-cluster/build.gradle
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/SearchingIT.java
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/action/get/MultiGetResponse.java
Labels: backport

#4876 [Backport] [2.3] Compatibility issue with /_mget: RHLC 2.x connected to OpenSearch Cluster 1.x (#4812)
  CHANGELOG.md
  qa/mixed-cluster/build.gradle
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/SearchingIT.java
  server/src/main/java/org/opensearch/action/get/MultiGetResponse.java
Labels: backport

#4875 [Backport] [2.x] Compatibility issue with /_mget: RHLC 2.x connected to OpenSearch Cluster 1.x (#4812)
  CHANGELOG.md
  qa/mixed-cluster/build.gradle
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/SearchingIT.java
  server/src/main/java/org/opensearch/action/get/MultiGetResponse.java
Labels: backport

#4879 [Backport] [2.0] Compatibility issue with /_mget: RHLC 2.x connected to OpenSearch Cluster 1.x (#4812)
  .ci/bwcVersions
  qa/mixed-cluster/build.gradle
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/SearchingIT.java
  server/src/main/java/org/opensearch/Version.java
  server/src/main/java/org/opensearch/action/get/MultiGetResponse.java
Labels: backport

#4884 [Backport] [2.x] Add missing no jdk distributions (#4722)
  CHANGELOG.md
  distribution/README.md
  distribution/archives/build.gradle
  distribution/packages/build.gradle
  settings.gradle
Labels: backport

#4888 Updating bundled JDK to 11.0.16.1+1 and 8u345-b01
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport 1.3

#4832 [Backport 2.x] Exclude jettison version brought in with hadoop-minicluster
  CHANGELOG.md
  buildSrc/version.properties
  plugins/discovery-azure-classic/build.gradle
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport

#4893 Upgrade netty to 4.1.84.Final
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
Labels: backport 1.x, dependencies, backport 2.x, backport 2.0, backport 1.3, backport 2.1, backport 2.2, backport 2.3

#4889 Dependency updates: asm 9.3 -> 9.4, bytebuddy 1.12.12 -> 1.12.18
  CHANGELOG.md
  buildSrc/version.properties
  modules/lang-expression/licenses/asm-9.3.jar.sha1
  modules/lang-expression/licenses/asm-9.4.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.3.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.4.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.3.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.4.jar.sha1
  modules/lang-painless/licenses/asm-9.3.jar.sha1
  modules/lang-painless/licenses/asm-9.4.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.3.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.4.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.3.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.4.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.3.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.4.jar.sha1
  modules/lang-painless/licenses/asm-util-9.3.jar.sha1
  modules/lang-painless/licenses/asm-util-9.4.jar.sha1
Labels: dependencies, backport 2.x, backport 2.3

#4908 [Backport 2.x] Upgrade netty to 4.1.84.Final
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
Labels: backport

#4909 [Backport 2.3] Upgrade netty to 4.1.84.Final
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
Labels: backport

#4914 [Backport 2.1] Upgrade netty to 4.1.84.Final
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
Labels: backport

#4913 [Backport 2.2] Upgrade netty to 4.1.84.Final
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
Labels: backport

#4915 [Backport 2.0] Upgrade netty to 4.1.84.Final
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
Labels: backport

#4910 [Backport] [2.x] Dependency updates: asm 9.3 -> 9.4, bytebuddy 1.12.12 -> 1.12.18 (#4889)
  CHANGELOG.md
  buildSrc/version.properties
  modules/lang-expression/licenses/asm-9.3.jar.sha1
  modules/lang-expression/licenses/asm-9.4.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.3.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.4.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.3.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.4.jar.sha1
  modules/lang-painless/licenses/asm-9.3.jar.sha1
  modules/lang-painless/licenses/asm-9.4.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.3.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.4.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.3.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.4.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.3.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.4.jar.sha1
  modules/lang-painless/licenses/asm-util-9.3.jar.sha1
  modules/lang-painless/licenses/asm-util-9.4.jar.sha1
Labels: backport

#4911 [Backport] [2.3] Dependency updates: asm 9.3 -> 9.4, bytebuddy 1.12.12 -> 1.12.18 (#4889)
  CHANGELOG.md
  buildSrc/version.properties
  modules/lang-expression/licenses/asm-9.3.jar.sha1
  modules/lang-expression/licenses/asm-9.4.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.3.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.4.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.3.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.4.jar.sha1
  modules/lang-painless/licenses/asm-9.3.jar.sha1
  modules/lang-painless/licenses/asm-9.4.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.3.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.4.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.3.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.4.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.3.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.4.jar.sha1
  modules/lang-painless/licenses/asm-util-9.3.jar.sha1
  modules/lang-painless/licenses/asm-util-9.4.jar.sha1
Labels: backport

#4919 [Backport 1.3] Upgrade netty to 4.1.84.Final
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.79.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.79.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.79.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
Labels: backport

#4922 Update Apache Lucene to 9.4.1
  CHANGELOG.md
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.4.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.4.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.4.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.4.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.4.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.4.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.4.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.4.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.4.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.4.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.4.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.4.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.4.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.4.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.4.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.4.1.jar.sha1
  server/licenses/lucene-analysis-common-9.4.0.jar.sha1
  server/licenses/lucene-analysis-common-9.4.1.jar.sha1
  server/licenses/lucene-backward-codecs-9.4.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.4.1.jar.sha1
  server/licenses/lucene-core-9.4.0.jar.sha1
  server/licenses/lucene-core-9.4.1.jar.sha1
  server/licenses/lucene-grouping-9.4.0.jar.sha1
  server/licenses/lucene-grouping-9.4.1.jar.sha1
  server/licenses/lucene-highlighter-9.4.0.jar.sha1
  server/licenses/lucene-highlighter-9.4.1.jar.sha1
  server/licenses/lucene-join-9.4.0.jar.sha1
  server/licenses/lucene-join-9.4.1.jar.sha1
  server/licenses/lucene-memory-9.4.0.jar.sha1
  server/licenses/lucene-memory-9.4.1.jar.sha1
  server/licenses/lucene-misc-9.4.0.jar.sha1
  server/licenses/lucene-misc-9.4.1.jar.sha1
  server/licenses/lucene-queries-9.4.0.jar.sha1
  server/licenses/lucene-queries-9.4.1.jar.sha1
  server/licenses/lucene-queryparser-9.4.0.jar.sha1
  server/licenses/lucene-queryparser-9.4.1.jar.sha1
  server/licenses/lucene-sandbox-9.4.0.jar.sha1
  server/licenses/lucene-sandbox-9.4.1.jar.sha1
  server/licenses/lucene-spatial-extras-9.4.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.4.1.jar.sha1
  server/licenses/lucene-spatial3d-9.4.0.jar.sha1
  server/licenses/lucene-spatial3d-9.4.1.jar.sha1
  server/licenses/lucene-suggest-9.4.0.jar.sha1
  server/licenses/lucene-suggest-9.4.1.jar.sha1
  server/src/main/java/org/opensearch/Version.java
Labels: dependencies, v3.0.0, backport 2.x

#4934 [Backport] [2.x] Update Apache Lucene to 9.4.1 (#4922)
  CHANGELOG.md
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.4.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.4.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.4.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.4.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.4.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.4.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.4.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.4.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.4.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.4.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.4.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.4.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.4.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.4.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.4.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.4.1.jar.sha1
  server/licenses/lucene-analysis-common-9.4.0.jar.sha1
  server/licenses/lucene-analysis-common-9.4.1.jar.sha1
  server/licenses/lucene-backward-codecs-9.4.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.4.1.jar.sha1
  server/licenses/lucene-core-9.4.0.jar.sha1
  server/licenses/lucene-core-9.4.1.jar.sha1
  server/licenses/lucene-grouping-9.4.0.jar.sha1
  server/licenses/lucene-grouping-9.4.1.jar.sha1
  server/licenses/lucene-highlighter-9.4.0.jar.sha1
  server/licenses/lucene-highlighter-9.4.1.jar.sha1
  server/licenses/lucene-join-9.4.0.jar.sha1
  server/licenses/lucene-join-9.4.1.jar.sha1
  server/licenses/lucene-memory-9.4.0.jar.sha1
  server/licenses/lucene-memory-9.4.1.jar.sha1
  server/licenses/lucene-misc-9.4.0.jar.sha1
  server/licenses/lucene-misc-9.4.1.jar.sha1
  server/licenses/lucene-queries-9.4.0.jar.sha1
  server/licenses/lucene-queries-9.4.1.jar.sha1
  server/licenses/lucene-queryparser-9.4.0.jar.sha1
  server/licenses/lucene-queryparser-9.4.1.jar.sha1
  server/licenses/lucene-sandbox-9.4.0.jar.sha1
  server/licenses/lucene-sandbox-9.4.1.jar.sha1
  server/licenses/lucene-spatial-extras-9.4.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.4.1.jar.sha1
  server/licenses/lucene-spatial3d-9.4.0.jar.sha1
  server/licenses/lucene-spatial3d-9.4.1.jar.sha1
  server/licenses/lucene-suggest-9.4.0.jar.sha1
  server/licenses/lucene-suggest-9.4.1.jar.sha1
  server/src/main/java/org/opensearch/Version.java
Labels: backport

#4730 [Feature/Identity] Allow for Encryption/Decryption of Principals into PITs
  CHANGELOG.md
  buildSrc/src/integTest/resources/org/opensearch/gradle/internal/fake_git/remote/settings.gradle
  server/src/main/java/org/opensearch/identity/ExtensionTokenProcessor.java
  server/src/main/java/org/opensearch/identity/PrincipalIdentifierToken.java
  server/src/test/java/org/opensearch/identity/ExtensionTokenProcessorTests.java
  server/src/test/java/org/opensearch/identity/PrincipalIdentifierTokenTests.java
Labels: feedback needed

#4947 Upgrade woodstox
  CHANGELOG.md
  buildSrc/version.properties
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/woodstox-core-6.2.8.jar.sha1
  plugins/repository-azure/licenses/woodstox-core-6.4.0.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/woodstox-core-6.3.1.jar.sha1
  plugins/repository-hdfs/licenses/woodstox-core-6.4.0.jar.sha1
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport 1.x, dependencies, backport 2.x, backport 2.0, backport 1.3, backport 2.1, backport 2.2, backport 2.3

#4944 Fixed compression support for h2c protocol
  CHANGELOG.md
  client/rest-high-level/src/test/java/org/opensearch/client/HighLevelRestClientCompressionIT.java
  modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
Labels: bug, v3.0.0

#4928 [Segment Replication] Fix bug of replica shard's translog not purging on index flush.
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: backport 2.x

#4979 [Upgrade] to lucene-9.5.0-snapshot-a4ef70f
  CHANGELOG.md
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.4.1.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.5.0-snapshot-a4ef70f.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.4.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.5.0-snapshot-a4ef70f.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.4.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.5.0-snapshot-a4ef70f.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.4.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.5.0-snapshot-a4ef70f.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.4.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.5.0-snapshot-a4ef70f.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.4.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.5.0-snapshot-a4ef70f.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.4.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.5.0-snapshot-a4ef70f.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.4.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-analysis-common-9.4.1.jar.sha1
  server/licenses/lucene-analysis-common-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-backward-codecs-9.4.1.jar.sha1
  server/licenses/lucene-backward-codecs-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-core-9.4.1.jar.sha1
  server/licenses/lucene-core-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-grouping-9.4.1.jar.sha1
  server/licenses/lucene-grouping-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-highlighter-9.4.1.jar.sha1
  server/licenses/lucene-highlighter-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-join-9.4.1.jar.sha1
  server/licenses/lucene-join-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-memory-9.4.1.jar.sha1
  server/licenses/lucene-memory-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-misc-9.4.1.jar.sha1
  server/licenses/lucene-misc-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-queries-9.4.1.jar.sha1
  server/licenses/lucene-queries-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-queryparser-9.4.1.jar.sha1
  server/licenses/lucene-queryparser-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-sandbox-9.4.1.jar.sha1
  server/licenses/lucene-sandbox-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-spatial-extras-9.4.1.jar.sha1
  server/licenses/lucene-spatial-extras-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-spatial3d-9.4.1.jar.sha1
  server/licenses/lucene-spatial3d-9.5.0-snapshot-a4ef70f.jar.sha1
  server/licenses/lucene-suggest-9.4.1.jar.sha1
  server/licenses/lucene-suggest-9.5.0-snapshot-a4ef70f.jar.sha1
  server/src/main/java/org/opensearch/Version.java
Labels: non-issue, >upgrade, v3.0.0

#4963 Fix dependencies
  CHANGELOG.md
  buildSrc/build.gradle
  buildSrc/version.properties
  test/fixtures/hdfs-fixture/build.gradle
Labels: dependencies, backport 2.x

#4989 [Backport 1.x] copy `build.sh` over from opensearch-build
  CHANGELOG.md
  scripts/build.sh
Labels: backport
