Repository opensearch-project/OpenSearch, pull requests merged in 2022-06, with the labels that each got.

#3459 Filter out invalid URI and HTTP method in the error message of no handler found for a REST request
  server/src/main/java/org/opensearch/rest/RestController.java
  server/src/test/java/org/opensearch/rest/RestControllerTests.java
Labels: enhancement, Severity-Minor, v2.1.0, v3.0.0, backport 2.x

#3475 Support use of IRSA for repository-s3 plugin credentials
  plugins/repository-s3/build.gradle
  plugins/repository-s3/licenses/aws-java-sdk-sts-1.11.749.jar.sha1
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/AmazonS3Reference.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/AmazonS3WithCredentials.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/AwsS3ServiceImplTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ServiceTests.java
Labels: backport 2.x

#3500 [Dependency upgrade] google-oauth-client to 1.33.3
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/google-oauth-client-1.33.1.jar.sha1
  plugins/repository-gcs/licenses/google-oauth-client-1.33.3.jar.sha1
Labels: backport 2.x

#3502 [Dependency upgrade] google-oauth-client to 1.33.3
  plugins/discovery-gce/build.gradle
  plugins/discovery-gce/licenses/google-oauth-client-1.31.0.jar.sha1
  plugins/discovery-gce/licenses/google-oauth-client-1.33.3.jar.sha1
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/google-oauth-client-1.33.1.jar.sha1
  plugins/repository-gcs/licenses/google-oauth-client-1.33.3.jar.sha1
Labels: backport 2.x

#3499 Added YAML Rest Test case to verify use of IRSA for repository-s3 plugin credentials.
  plugins/repository-s3/build.gradle
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/60_repository_eks_credentials.yml
  test/fixtures/s3-fixture/Dockerfile.eks
  test/fixtures/s3-fixture/docker-compose.yml
  test/fixtures/s3-fixture/src/main/java/fixture/s3/S3HttpFixtureWithEKS.java
Labels: backport 2.x

#3487 Fix the support of RestClient Node Sniffer for version 2.x and update tests
  client/sniffer/src/main/java/org/opensearch/client/sniff/OpenSearchNodesSniffer.java
  client/sniffer/src/test/java/org/opensearch/client/sniff/OpenSearchNodesSnifferParseTests.java
  client/sniffer/src/test/java/org/opensearch/client/sniff/OpenSearchNodesSnifferTests.java
  client/sniffer/src/test/resources/1.0.0_nodes_http.json
  client/sniffer/src/test/resources/2.0.0_nodes_http.json
  client/sniffer/src/test/resources/6.0.0_nodes_http.json
  client/sniffer/src/test/resources/7.3.0_nodes_http.json
  client/sniffer/src/test/resources/create_test_nodes_info.bash
Labels: bug, Clients & Libraries, v2.1.0, v3.0.0, backport 2.x, backport 2.0

#3530 Revert "[Remove] MainResponse version override cluster setting (#3031) (#3032)"
  client/rest-high-level/src/test/java/org/opensearch/client/PingAndInfoIT.java
  server/src/main/java/org/opensearch/action/main/MainResponse.java
  server/src/main/java/org/opensearch/action/main/TransportMainAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/action/main/MainActionTests.java
  server/src/test/java/org/opensearch/action/main/MainResponseTests.java
Labels: backwards-compatibility, Clients & Libraries, v2.1.0, backport 2.0

#3549 Add release notes for 1.3.3
  release-notes/opensearch.release-notes-1.3.3.md
Labels: documentation

#3537 [Upgrade] Lucene-9.3.0-snapshot-b7231bb
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.3.0-snapshot-823df23.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.3.0-snapshot-823df23.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-analysis-common-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-analysis-common-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-backward-codecs-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-backward-codecs-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-core-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-core-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-grouping-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-grouping-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-highlighter-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-highlighter-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-join-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-join-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-memory-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-memory-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-misc-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-misc-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-queries-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-queries-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-queryparser-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-queryparser-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-sandbox-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-sandbox-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-spatial-extras-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-spatial-extras-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-spatial3d-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-spatial3d-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-suggest-9.3.0-snapshot-823df23.jar.sha1
  server/licenses/lucene-suggest-9.3.0-snapshot-b7231bb.jar.sha1
  server/src/test/java/org/opensearch/common/lucene/LuceneTests.java
Labels: non-issue, >upgrade, v3.0.0, backport 2.x

#3555 [Backport 2.x] [Upgrade] Lucene-9.3.0-snapshot-b7231bb (#3537)
  buildSrc/version.properties
  modules/lang-expression/licenses/lucene-expressions-9.2.0-snapshot-ba8c3a8.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.3.0-snapshot-b7231bb.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.2.0-snapshot-ba8c3a8.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-analysis-common-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-analysis-common-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-backward-codecs-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-backward-codecs-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-core-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-core-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-grouping-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-grouping-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-highlighter-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-highlighter-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-join-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-join-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-memory-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-memory-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-misc-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-misc-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-queries-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-queries-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-queryparser-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-queryparser-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-sandbox-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-sandbox-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-spatial-extras-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-spatial-extras-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-spatial3d-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-spatial3d-9.3.0-snapshot-b7231bb.jar.sha1
  server/licenses/lucene-suggest-9.2.0-snapshot-ba8c3a8.jar.sha1
  server/licenses/lucene-suggest-9.3.0-snapshot-b7231bb.jar.sha1
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/common/lucene/LuceneTests.java
Labels: non-issue, >upgrade, dependencies, v2.1.0

#3559 Revert beat _type changes
  rest-api-spec/src/main/resources/rest-api-spec/test/bulk/11_with_deprecated_types.yml
  server/src/internalClusterTest/java/org/opensearch/action/bulk/BulkIntegrationIT.java
  server/src/main/java/org/opensearch/action/bulk/BulkRequest.java
  server/src/main/java/org/opensearch/rest/action/document/RestBulkAction.java
  server/src/main/java/org/opensearch/rest/action/document/RestDeleteAction.java
  server/src/main/java/org/opensearch/rest/action/document/RestIndexAction.java
  server/src/main/java/org/opensearch/rest/action/search/RestCountAction.java
  server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java
  server/src/test/java/org/opensearch/action/bulk/BulkRequestParserTests.java
  server/src/test/resources/org/opensearch/action/bulk/bulk-with-deprecated-types.json
Labels: v2.0.0, Indexing & Search

#3436 Support dynamic node role
  distribution/docker/src/test/resources/rest-api-spec/test/11_nodes.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yml
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeRoleGenerator.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeRoleTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/node/NodeRoleSettingsTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestNodesActionTests.java
Labels: v3.0.0, backport 2.x

#3591 Fixing flakiness of ShuffleForcedMergePolicyTests
  server/src/test/java/org/opensearch/lucene/index/ShuffleForcedMergePolicyTests.java
Labels: v2.1.0, v3.0.0, backport 2.x

#3595 Add release notes for version 2.0.1
  release-notes/opensearch.release-notes-2.0.1.md
Labels: documentation, backport 2.0, v2.0.1

#3598 [2.0] Add bwc version 1.3.4
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: backport, v2.0.1

#3605 Fix NPE when minBound/maxBound is not set before being called.
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/HistogramTests.java
Labels: backport 2.x

#3609 [2.x] Deprecate classes in org.opensearch.action.support.master (#3593)
  server/src/main/java/org/opensearch/action/support/master/AcknowledgedRequest.java
  server/src/main/java/org/opensearch/action/support/master/AcknowledgedRequestBuilder.java
  server/src/main/java/org/opensearch/action/support/master/AcknowledgedResponse.java
  server/src/main/java/org/opensearch/action/support/master/MasterNodeOperationRequestBuilder.java
  server/src/main/java/org/opensearch/action/support/master/MasterNodeReadOperationRequestBuilder.java
  server/src/main/java/org/opensearch/action/support/master/MasterNodeReadRequest.java
  server/src/main/java/org/opensearch/action/support/master/MasterNodeRequest.java
  server/src/main/java/org/opensearch/action/support/master/ShardsAcknowledgedResponse.java
  server/src/main/java/org/opensearch/action/support/master/TransportMasterNodeAction.java
  server/src/main/java/org/opensearch/action/support/master/TransportMasterNodeReadAction.java
  server/src/main/java/org/opensearch/action/support/master/info/ClusterInfoRequest.java
  server/src/main/java/org/opensearch/action/support/master/info/ClusterInfoRequestBuilder.java
  server/src/main/java/org/opensearch/action/support/master/info/TransportClusterInfoAction.java
  server/src/main/java/org/opensearch/action/support/master/info/package-info.java
  server/src/main/java/org/opensearch/action/support/master/package-info.java
Labels: enhancement, backport, deprecate, v2.1.0

#3626 [BUG] opensearch crashes on closed client connection before search reply
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: v2.1.0, v3.0.0, backport 2.x

#3644 Reserve all methods with 'master' in the names in the package 'org.opensearch.action.support.clustermanager'
  server/src/main/java/org/opensearch/action/support/clustermanager/ClusterManagerNodeOperationRequestBuilder.java
  server/src/main/java/org/opensearch/action/support/clustermanager/ClusterManagerNodeRequest.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/info/TransportClusterInfoAction.java
  server/src/main/java/org/opensearch/action/support/master/MasterNodeOperationRequestBuilder.java
  server/src/main/java/org/opensearch/action/support/master/MasterNodeRequest.java
  server/src/main/java/org/opensearch/action/support/master/TransportMasterNodeAction.java
  server/src/main/java/org/opensearch/action/support/master/info/TransportClusterInfoAction.java
Labels: enhancement, deprecate, v3.0.0

#3638 Introduce TranslogManager implementations decoupled from the Engine
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/LifecycleAware.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/index/translog/TranslogRecoveryRunner.java
  server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/listener/CompositeTranslogEventListener.java
  server/src/main/java/org/opensearch/index/translog/listener/TranslogEventListener.java
  server/src/main/java/org/opensearch/index/translog/listener/package-info.java
  server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogManagerTestCase.java
  server/src/test/java/org/opensearch/index/translog/listener/TranslogListenerTests.java
Labels: v3.0.0

#3653 [Backport 2.0] [BUG] opensearch crashes on closed client connection before search reply
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: backport

#3654 [Backport 1.x] [BUG] opensearch crashes on closed client connection before search reply
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: backport

#3655 [Backport 1.3] [BUG] opensearch crashes on closed client connection before search reply
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: backport

#3662 Remove class org.opensearch.action.support.master.AcknowledgedResponse
  server/src/main/java/org/opensearch/action/support/master/AcknowledgedRequest.java
  server/src/main/java/org/opensearch/action/support/master/AcknowledgedRequestBuilder.java
  server/src/main/java/org/opensearch/action/support/master/AcknowledgedResponse.java
  server/src/main/java/org/opensearch/action/support/master/ShardsAcknowledgedResponse.java
Labels: bug, backwards-compatibility, v2.1.0, v3.0.0, backport 2.x

#3656 [BUG] Custom POM configuration for ZIP publication produces duplicit tags (url, scm)
  buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
  buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
Labels: bug, Build Libraries & Interfaces, backport 2.x, backport 2.0, backport 2.1

#3687 [2.1] Revert renaming method onMaster() and offMaster() in interface LocalNodeMasterListener
  server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
  server/src/main/java/org/opensearch/common/settings/ConsistentSettingsService.java
  server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
  server/src/test/java/org/opensearch/common/settings/ConsistentSettingsServiceTests.java
Labels: bug, backport, backwards-compatibility, v2.1.0

#3672 Bumping 2.x to 2.2.0
  .ci/bwcVersions
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
Labels: v2.2.0

#3673 Adding 2.2.0 Bwc version to main
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: v3.0.0

#3686 Revert renaming method onMaster() and offMaster() in interface LocalNodeMasterListener
  server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
  server/src/main/java/org/opensearch/common/settings/ConsistentSettingsService.java
  server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
  server/src/test/java/org/opensearch/common/settings/ConsistentSettingsServiceTests.java
Labels: bug, backwards-compatibility, v3.0.0, backport 2.x, v2.2.0

#3693 [2.x] Revert renaming method onMaster() and offMaster() in interface LocalNodeMasterListener
  server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
  server/src/main/java/org/opensearch/common/settings/ConsistentSettingsService.java
  server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
  server/src/test/java/org/opensearch/common/settings/ConsistentSettingsServiceTests.java
Labels: bug, backport, backwards-compatibility, v2.2.0

#3694 Upgrading AWS SDK dependency for native plugins
  buildSrc/version.properties
  plugins/discovery-ec2/build.gradle
  plugins/discovery-ec2/licenses/aws-java-sdk-core-1.11.749.jar.sha1
  plugins/discovery-ec2/licenses/aws-java-sdk-core-1.12.247.jar.sha1
  plugins/discovery-ec2/licenses/aws-java-sdk-ec2-1.11.749.jar.sha1
  plugins/discovery-ec2/licenses/aws-java-sdk-ec2-1.12.247.jar.sha1
  plugins/repository-s3/build.gradle
  plugins/repository-s3/licenses/aws-java-sdk-core-1.11.749.jar.sha1
  plugins/repository-s3/licenses/aws-java-sdk-core-1.12.247.jar.sha1
  plugins/repository-s3/licenses/aws-java-sdk-s3-1.11.749.jar.sha1
  plugins/repository-s3/licenses/aws-java-sdk-s3-1.12.247.jar.sha1
  plugins/repository-s3/licenses/aws-java-sdk-sts-1.11.749.jar.sha1
  plugins/repository-s3/licenses/aws-java-sdk-sts-1.12.247.jar.sha1
  plugins/repository-s3/licenses/jmespath-java-1.11.749.jar.sha1
  plugins/repository-s3/licenses/jmespath-java-1.12.247.jar.sha1
Labels: Plugins, >upgrade, dependencies, v3.0.0, backport 2.x, v2.2.0

#3724 [Backport 1.x] Add gradle check test for github workflows (Testing again)
  .github/workflows/gradle-check.yml
  .github/workflows/wrapper.yml
Labels: enhancement

#3728 Update github action gradle-check to use pull_request_target for accessing token
  .github/workflows/gradle-check.yml
Labels: bug

#3732 [Backport 2.0] Update github action gradle-check to use pull_request_target for accessing token
  .github/workflows/gradle-check.yml
Labels: bug

#3718 Optimize Gradle builds by enabling local build caching
  gradle.properties
  settings.gradle
Labels: backport 2.x, backport 2.0, backport 2.1

#3671 Integrate Engine with decoupled Translog interfaces
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/index/translog/listener/CompositeTranslogEventListener.java
  server/src/main/java/org/opensearch/index/translog/listener/TranslogEventListener.java
  server/src/test/java/org/opensearch/index/IndexServiceTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/engine/LuceneChangesSnapshotTests.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  server/src/test/java/org/opensearch/index/engine/NoOpEngineTests.java
  server/src/test/java/org/opensearch/index/engine/ReadOnlyEngineTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
  server/src/test/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommandTests.java
  server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
  server/src/test/java/org/opensearch/index/translog/listener/TranslogListenerTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
  test/framework/src/main/java/org/opensearch/index/engine/InternalTestEngine.java
  test/framework/src/main/java/org/opensearch/index/engine/TranslogHandler.java
Labels: v3.0.0

#3742 Move gradle-check code to its own scripts and upload codecov
  .github/workflows/gradle-check.yml
Labels: enhancement, backport 1.x, backport 2.x, backport 2.0, backport 2.1
