Repository opensearch-project/OpenSearch, pull requests merged in 2022-12, with the labels that each got.

#4587 GitHub Workflows security hardening
  .github/workflows/gradle-check.yml
  .github/workflows/links.yml
  .github/workflows/version.yml
  CHANGELOG.md
Labels: CI, v3.0.0, backport 2.x

#5417 Fix for windows failure InternalDistributionArchiveSetupPluginFuncTest
  buildSrc/src/integTest/groovy/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPluginFuncTest.groovy
Labels: skip-changelog

#5418 Added release notes for 1.3.7
  release-notes/opensearch.release-notes-1.3.7.md
Labels: skip-changelog

#5439 Fix Flaky Tests testReplicaThreadedUpdateToShardLimitsAndRejections and testCoordinatingPrimaryThreadedUpdateToShardLimitsAndRejections
  server/src/test/java/org/opensearch/index/ShardIndexingPressureConcurrentExecutionTests.java
Labels: skip-changelog

#5448 Update ingest-attachment plugin dependencies: Apache Tika 3.6.0, Apache Mime4j 0.8.8, Apache Poi 5.2.3, Apache PdfBox 2.0.27
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/apache-mime4j-core-0.8.3.jar.sha1
  plugins/ingest-attachment/licenses/apache-mime4j-core-0.8.8.jar.sha1
  plugins/ingest-attachment/licenses/apache-mime4j-dom-0.8.3.jar.sha1
  plugins/ingest-attachment/licenses/apache-mime4j-dom-0.8.8.jar.sha1
  plugins/ingest-attachment/licenses/fontbox-2.0.25.jar.sha1
  plugins/ingest-attachment/licenses/fontbox-2.0.27.jar.sha1
  plugins/ingest-attachment/licenses/pdfbox-2.0.25.jar.sha1
  plugins/ingest-attachment/licenses/pdfbox-2.0.27.jar.sha1
  plugins/ingest-attachment/licenses/poi-5.2.2.jar.sha1
  plugins/ingest-attachment/licenses/poi-5.2.3.jar.sha1
  plugins/ingest-attachment/licenses/poi-ooxml-5.2.2.jar.sha1
  plugins/ingest-attachment/licenses/poi-ooxml-5.2.3.jar.sha1
  plugins/ingest-attachment/licenses/poi-ooxml-lite-5.2.2.jar.sha1
  plugins/ingest-attachment/licenses/poi-ooxml-lite-5.2.3.jar.sha1
  plugins/ingest-attachment/licenses/poi-scratchpad-5.2.2.jar.sha1
  plugins/ingest-attachment/licenses/poi-scratchpad-5.2.3.jar.sha1
  plugins/ingest-attachment/licenses/tika-core-2.5.0.jar.sha1
  plugins/ingest-attachment/licenses/tika-core-2.6.0.jar.sha1
  plugins/ingest-attachment/licenses/tika-langdetect-optimaize-2.5.0.jar.sha1
  plugins/ingest-attachment/licenses/tika-langdetect-optimaize-2.6.0.jar.sha1
  plugins/ingest-attachment/licenses/tika-parsers-standard-package-2.5.0.jar.sha1
  plugins/ingest-attachment/licenses/tika-parsers-standard-package-2.6.0.jar.sha1
Labels: dependencies, skip-changelog

#5301 [Feature/Identity] Include high-level documentation about auth flows and node-to-node communication
  sandbox/libs/authn/docs/auth_flow.md
Labels: skip-changelog

#5282 Enhance CheckpointState to support no-op replication
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/action/support/replication/FanoutReplicationProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationMode.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationModeAwareProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationOperation.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationProxyFactory.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationProxyRequest.java
  server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/test/java/org/opensearch/action/admin/indices/close/TransportVerifyShardBeforeCloseActionTests.java
  server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
  server/src/test/java/org/opensearch/action/support/replication/ReplicationOperationTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportReplicationActionTests.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTestCase.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
Labels: distributed framework, durability, v2.5.0, skip-changelog

#5482 [BUG] org.opensearch.repositories.s3.RepositoryS3ClientYamlTestSuiteIT/test {yaml=repository_s3/20_repository_permanent_credentials/Snapshot and Restore with repository-s3 using permanent credentials} flaky: randomizing basePath
  plugins/repository-s3/build.gradle
Labels: flaky-test, skip-changelog

#5462 [Bug] fix case sensitivity for wildcard queries
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/query/QueryStringIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/MappedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/StringFieldType.java
  server/src/main/java/org/opensearch/index/search/QueryStringQueryParser.java
  server/src/test/java/org/opensearch/index/query/PrefixQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
Labels: bug, v3.0.0, backport 2.x, Search

#5467 [backport 2.4] Revert "build no-jdk distributions as part of release build (#4902)"
  scripts/build.sh
Labels: skip-changelog

#5465 Revert "build no-jdk distributions as part of release build (#4902)"
  scripts/build.sh
Labels: skip-changelog

#5466 [backport 2.x] Revert "build no-jdk distributions as part of release build (#4902)"
  scripts/build.sh
Labels: skip-changelog

#5503 Add max_shard_size parameter for Shrink API (fix supported version after backport)
  server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeRequest.java
Labels: bug, skip-changelog

#5501 Sync CODEOWNERS with MAINTAINERS.
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 1.x, backport 2.x, skip-changelog

#5491 Fix flaky test BulkIntegrationIT.testDeleteIndexWhileIndexing
  server/src/internalClusterTest/java/org/opensearch/action/bulk/BulkIntegrationIT.java
Labels: skip-changelog

#5500 [Backport] [2.4] Support OpenSSL Provider with default Netty allocator (#5460)
  CHANGELOG.md
  modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4NioServerSocketChannel.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/NettyAllocator.java
  server/src/main/java/org/opensearch/common/bytes/BytesReference.java
  server/src/test/java/org/opensearch/common/bytes/ByteBuffersBytesReferenceTests.java
Labels: backport

#5499 [Backport] [2.x] Support OpenSSL Provider with default Netty allocator (#5460)
  CHANGELOG.md
  modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4NioServerSocketChannel.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/NettyAllocator.java
  server/src/main/java/org/opensearch/common/bytes/BytesReference.java
  server/src/test/java/org/opensearch/common/bytes/ByteBuffersBytesReferenceTests.java
Labels: backport

#5488 Add release notes for 2.4.1
  release-notes/opensearch.release-notes-2.4.1.md
Labels: backport 2.x, backport 2.4, skip-changelog

#5511 Properly skip OnDemandBlockSnapshotIndexInputTests.testVariousBlockSize on Windows
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
Labels: skip-changelog

#5533 [Backport 2.x] [Segment Replication] Trigger a round of replication for replica shards during peer recovery when segment replication is enabled
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
Labels: skip-changelog

#5495 Adding support to register settings dynamically
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/AbstractScopedSettings.java
  server/src/main/java/org/opensearch/common/settings/SettingsModule.java
  server/src/test/java/org/opensearch/common/settings/SettingsModuleTests.java
  server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java
Labels: enhancement, backport 2.x

#5536 Updated 1.3.7 release note date
  release-notes/opensearch.release-notes-1.3.7.md
Labels: skip-changelog

#5093 Atomically update cluster state with decommission status and corresponding action
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/configuration/TransportAddVotingConfigExclusionsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/configuration/TransportClearVotingConfigExclusionsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/configuration/VotingConfigExclusionsHelper.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionController.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionHelper.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
  server/src/test/java/org/opensearch/action/admin/cluster/configuration/VotingConfigExclusionsHelperTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionControllerTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionHelperTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
Labels: skip-changelog

#5541 [Backport-2.x]Atomically update cluster state with decommission status and corresponding action
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/configuration/TransportAddVotingConfigExclusionsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/configuration/TransportClearVotingConfigExclusionsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/configuration/VotingConfigExclusionsHelper.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionController.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionHelper.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
  server/src/test/java/org/opensearch/action/admin/cluster/configuration/VotingConfigExclusionsHelperTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionControllerTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionHelperTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
Labels: skip-changelog

#5530 [Backport 2.x] Added experimental extensions
  CHANGELOG.md
  plugins/repository-azure/licenses/jackson-LICENSE.txt
  plugins/repository-azure/licenses/jackson-NOTICE.txt
  plugins/repository-hdfs/build.gradle
  server/src/main/java/org/opensearch/action/admin/cluster/state/ClusterStateResponse.java
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/main/java/org/opensearch/cluster/ClusterSettingsResponse.java
  server/src/main/java/org/opensearch/cluster/LocalNodeResponse.java
  server/src/main/java/org/opensearch/discovery/PluginRequest.java
  server/src/main/java/org/opensearch/discovery/PluginResponse.java
  server/src/main/java/org/opensearch/env/Environment.java
  server/src/main/java/org/opensearch/extensions/DiscoveryExtensionNode.java
  server/src/main/java/org/opensearch/extensions/ExtensionRequest.java
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/main/java/org/opensearch/extensions/ExtensionsSettings.java
  server/src/main/java/org/opensearch/extensions/NoopExtensionsManager.java
  server/src/main/java/org/opensearch/extensions/package-info.java
  server/src/main/java/org/opensearch/index/AcknowledgedResponse.java
  server/src/main/java/org/opensearch/index/IndicesModuleRequest.java
  server/src/main/java/org/opensearch/index/IndicesModuleResponse.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/PluginsService.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  server/src/test/java/org/opensearch/transport/TransportServiceHandshakeTests.java
  server/src/test/resources/config/extensions.yml
Labels: feature, backport, Plugins, v2.5.0

#5529 Update Netty to 4.1.86.Final
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http2-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.86.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.86.Final.jar.sha1
Labels: dependencies, backport 2.x, skip-changelog

#5549 Update release date in 2.4.1 release notes
  release-notes/opensearch.release-notes-2.4.1.md
Labels: skip-changelog

#5550 Add release notes for 2.4.1
  release-notes/opensearch.release-notes-2.4.1.md
Labels: skip-changelog

#5552 Update 2.4.1 release notes
  release-notes/opensearch.release-notes-2.4.1.md
Labels: skip-changelog

#5545 [Backport] [2.x] Update Netty to 4.1.86.Final
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.86.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.86.Final.jar.sha1
Labels: backport, skip-changelog

#5548 [Backport] [1.3] Update Netty to 4.1.86.Final
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.86.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.86.Final.jar.sha1
Labels: backport, skip-changelog

#5547 [Backport] [1.x] Update Netty to 4.1.86.Final
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.84.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.84.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.86.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.84.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.86.Final.jar.sha1
Labels: backport, skip-changelog

#5563 Incremented version to 2.4.2.
  .ci/bwcVersions
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#5433 Refactor fuzziness interface on query builders
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/query/MultiMatchQueryIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
  server/src/main/java/org/opensearch/common/unit/Fuzziness.java
  server/src/main/java/org/opensearch/index/query/MatchBoolPrefixQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MultiMatchQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/QueryStringQueryBuilder.java
  server/src/test/java/org/opensearch/common/unit/FuzzinessTests.java
  server/src/test/java/org/opensearch/index/query/MatchBoolPrefixQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/MatchQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/MultiMatchQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
Labels: enhancement, v2.5.0

#5459 add support for ppc64le architecture
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/Architecture.java
  buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
  buildSrc/src/test/java/org/opensearch/gradle/ArchitectureTests.java
  buildSrc/src/test/java/org/opensearch/gradle/JdkDownloadPluginTests.java
  distribution/archives/build.gradle
  distribution/build.gradle
  distribution/docker/build.gradle
  distribution/docker/docker-ppc64le-export/build.gradle
  server/src/main/java/org/opensearch/bootstrap/SystemCallFilter.java
  settings.gradle
Labels: enhancement, backport 2.x

#4546 Bump antlr4 from 4.9.3 to 4.11.1
  CHANGELOG.md
  buildSrc/version.properties
  modules/lang-expression/build.gradle
  modules/lang-expression/licenses/antlr4-runtime-4.11.1.jar.sha1
  modules/lang-expression/licenses/antlr4-runtime-4.9.3.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.5.0-snapshot-6700b7e.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.5.0-snapshot-d5cef1c.jar.sha1
  modules/lang-painless/build.gradle
  modules/lang-painless/licenses/antlr4-runtime-4.11.1.jar.sha1
  modules/lang-painless/licenses/antlr4-runtime-4.9.3.jar.sha1
  modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessLexer.java
  modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java
  modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParserBaseVisitor.java
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.5.0-snapshot-6700b7e.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.5.0-snapshot-d5cef1c.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.5.0-snapshot-6700b7e.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.5.0-snapshot-d5cef1c.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.5.0-snapshot-6700b7e.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.5.0-snapshot-d5cef1c.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.5.0-snapshot-6700b7e.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.5.0-snapshot-d5cef1c.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.5.0-snapshot-6700b7e.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.5.0-snapshot-d5cef1c.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.5.0-snapshot-6700b7e.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.5.0-snapshot-d5cef1c.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.5.0-snapshot-6700b7e.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-analysis-common-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-analysis-common-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-backward-codecs-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-backward-codecs-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-core-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-core-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-grouping-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-grouping-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-highlighter-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-highlighter-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-join-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-join-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-memory-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-memory-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-misc-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-misc-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-queries-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-queries-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-queryparser-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-queryparser-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-sandbox-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-sandbox-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-spatial-extras-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-spatial-extras-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-spatial3d-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-spatial3d-9.5.0-snapshot-d5cef1c.jar.sha1
  server/licenses/lucene-suggest-9.5.0-snapshot-6700b7e.jar.sha1
  server/licenses/lucene-suggest-9.5.0-snapshot-d5cef1c.jar.sha1
Labels: backport 2.x

#5617 Change version check for cluster manager throttling setting to 2.5
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskThrottler.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java
Labels: skip-changelog

#5620 Reconcile 2.4.0 release notes
  release-notes/opensearch.release-notes-2.4.0.md
Labels: skip-changelog

#5618 Add builder for EngineConfig
  server/src/internalClusterTest/java/org/opensearch/indices/IndexingMemoryControllerIT.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
  server/src/test/java/org/opensearch/indices/IndexingMemoryControllerTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Labels: skip-changelog

#5616 Add transport action for primary term validation for remote-backed indices
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/action/support/replication/FanoutReplicationProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationModeAwareProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationOperation.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationProxyFactory.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationProxyRequest.java
  server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/test/java/org/opensearch/action/admin/indices/close/TransportVerifyShardBeforeCloseActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/flush/TransportShardFlushActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/readonly/TransportVerifyShardIndexBlockActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/refresh/TransportShardRefreshActionTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
  server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
  server/src/test/java/org/opensearch/action/support/replication/ReplicationOperationTests.java
  server/src/test/java/org/opensearch/index/seqno/GlobalCheckpointSyncActionTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseBackgroundSyncActionTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseSyncActionTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
Labels: distributed framework, durability, v2.5.0, skip-changelog

#5392 [Remote Translog] Introduce remote translog with upload functionality
  server/src/main/java/org/opensearch/common/blobstore/fs/FsBlobStore.java
  server/src/main/java/org/opensearch/common/io/stream/BytesStreamInput.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/LocalTranslog.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/translog/LocalTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/TestTranslog.java
  server/src/test/java/org/opensearch/index/translog/TranslogManagerTestCase.java
  server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/FileTransferTrackerTests.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Labels: skip-changelog

#5638 Enable creation of indices using Remote Translog
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommand.java
  server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: skip-changelog

#5651 Increasing timeout of testQuorumRecovery to 90 seconds from 30
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/QuorumGatewayIT.java
Labels: backport 2.x

#5652 Fix flaky test case - string profiler via global ordinals
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/20_terms.yml
Labels: skip-changelog

#5645 Improve tests.config property thread safety
  test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java
Labels: skip-changelog

#5655 Fix flaky PitMultiNodeTests including testCreatePitWhileNodeDropWithAllowPartialCreationFalse
  server/src/test/java/org/opensearch/search/PitMultiNodeTests.java
Labels: backport 2.x, skip-changelog

#5656 Fix flaky SearchCancellationIT tests to avoid race condition
  server/src/internalClusterTest/java/org/opensearch/search/SearchCancellationIT.java
Labels: skip-changelog

#5661 Removing the CHANGELOG entry for unreleased changes
  CHANGELOG.md
Labels: skip-changelog
