Repository opensearch-project/OpenSearch, pull requests merged in 2022-02, with the labels that each got.

#2005 Fix composite aggregation failed test cases introduce by missing_order parameter (#1942)
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/InternalCompositeTests.java
Labels: bug, v2.0.0, Aggregations

#2033 Upgrading Shadow plugin to 7.1.2
  buildSrc/build.gradle
  buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
Labels: CVE, >upgrade, v1.3.0

#1985 [1x] Deprecate setting explicit version on analysis component (#1978)
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ArabicAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ArmenianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/BasqueAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/BengaliAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/BrazilianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/BulgarianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CatalanAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ChineseAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CjkAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CzechAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/DanishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/DutchAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/EnglishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/EstonianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/FinnishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/FrenchAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/GalicianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/GermanAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/GreekAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/HindiAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/HungarianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/IndonesianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/IrishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ItalianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/LatvianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/LithuanianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/NorwegianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/PersianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/PortugueseAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/RomanianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/RussianAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SnowballAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SoraniAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SpanishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/StandardHtmlStripAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SwedishAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/ThaiAnalyzerProvider.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/TurkishAnalyzerProvider.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/CompoundAnalysisTests.java
  plugins/analysis-stempel/src/main/java/org/opensearch/index/analysis/pl/PolishAnalyzerProvider.java
  plugins/analysis-ukrainian/src/main/java/org/opensearch/index/analysis/UkrainianAnalyzerProvider.java
  server/src/main/java/org/opensearch/index/analysis/AbstractIndexAnalyzerProvider.java
  server/src/main/java/org/opensearch/index/analysis/AbstractTokenFilterFactory.java
  server/src/main/java/org/opensearch/index/analysis/AbstractTokenizerFactory.java
  server/src/main/java/org/opensearch/index/analysis/Analysis.java
  server/src/main/java/org/opensearch/index/analysis/PreBuiltAnalyzerProviderFactory.java
  server/src/main/java/org/opensearch/index/analysis/SimpleAnalyzerProvider.java
  server/src/main/java/org/opensearch/index/analysis/StandardAnalyzerProvider.java
  server/src/main/java/org/opensearch/index/analysis/StopAnalyzerProvider.java
  server/src/main/java/org/opensearch/index/analysis/WhitespaceAnalyzerProvider.java
  server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
  server/src/test/resources/org/opensearch/index/analysis/test1.json
Labels: Severity-Blocker, backport, deprecate, v1.3.0

#1984 [1x] Deprecate index.merge.policy.max_merge_at_once_explicit (#1981)
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/MergePolicyConfig.java
  server/src/main/java/org/opensearch/index/OpenSearchTieredMergePolicy.java
  server/src/test/java/org/opensearch/index/MergePolicySettingsTests.java
Labels: Severity-Blocker, backport, deprecate, v1.3.0

#2029 [Remove] Segment memory estimation and tracking
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
  server/src/main/java/org/opensearch/action/admin/indices/segments/IndicesSegmentResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStats.java
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/OpenSearchReaderManager.java
  server/src/main/java/org/opensearch/index/engine/RamAccountingRefreshListener.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/engine/Segment.java
  server/src/main/java/org/opensearch/index/engine/SegmentsStats.java
  server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestSegmentsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/test/java/org/opensearch/action/admin/indices/stats/IndicesStatsTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/engine/NoOpEngineTests.java
  server/src/test/java/org/opensearch/index/engine/SegmentTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  test/framework/src/main/java/org/opensearch/test/ExternalTestCluster.java
Labels: v2.0.0, deprecate

#2035 [Refactor] Lucene DataInput and DataOutput to StreamInput and StreamOutput
  server/src/main/java/org/apache/lucene/queries/BinaryDocValuesRangeQuery.java
  server/src/main/java/org/opensearch/action/search/TransportSearchHelper.java
  server/src/main/java/org/opensearch/common/io/stream/BytesStreamInput.java
  server/src/main/java/org/opensearch/common/util/ByteUtils.java
  server/src/main/java/org/opensearch/index/fielddata/plain/AbstractBinaryDVLeafFieldData.java
  server/src/main/java/org/opensearch/index/mapper/BinaryFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/BinaryRangeUtil.java
  server/src/main/java/org/opensearch/index/mapper/RangeType.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/test/java/org/opensearch/common/io/stream/BaseStreamTests.java
  server/src/test/java/org/opensearch/common/io/stream/ByteBufferStreamInputTests.java
  server/src/test/java/org/opensearch/common/io/stream/BytesReferenceStreamInputTests.java
  server/src/test/java/org/opensearch/common/io/stream/BytesStreamInputTests.java
  server/src/test/java/org/opensearch/common/io/stream/FilterStreamInputTests.java
  server/src/test/java/org/opensearch/common/io/stream/InputStreamStreamInputTests.java
  server/src/test/java/org/opensearch/common/util/ByteUtilsTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogTests.java
Labels: enhancement, v2.0.0

#2056 [Remove] CircuitBreaker Accounting
  server/src/internalClusterTest/java/org/opensearch/indices/memory/breaker/CircuitBreakerServiceIT.java
  server/src/main/java/org/opensearch/common/breaker/CircuitBreaker.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerService.java
  server/src/test/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerServiceTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: v2.0.0

#2050 Adding workflow to auto delete backport merged branches from backport workflow
  .github/workflows/delete_backport_branch.yml
Labels: enhancement, CI

#2048 Stabilizing org.opensearch.cluster.routing.MovePrimaryFirstTests.test…
  server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
  server/src/test/java/org/opensearch/cluster/routing/MovePrimaryFirstTests.java
Labels: bug, :test, v2.0.0, v1.3.0, backport 1.x

#2027 [Refactor] MapperService to QueryShardContext in valueFetcher
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/RankFeatureFieldMapper.java
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/RankFeatureMetaFieldMapper.java
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/RankFeaturesFieldMapper.java
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/ScaledFloatFieldMapper.java
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapper.java
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/TokenCountFieldMapper.java
  modules/parent-join/src/main/java/org/opensearch/join/mapper/MetaJoinFieldMapper.java
  modules/parent-join/src/main/java/org/opensearch/join/mapper/ParentIdFieldMapper.java
  modules/parent-join/src/main/java/org/opensearch/join/mapper/ParentJoinFieldMapper.java
  modules/percolator/src/main/java/org/opensearch/percolator/PercolatorFieldMapper.java
  plugins/analysis-icu/src/main/java/org/opensearch/index/mapper/ICUCollationKeywordFieldMapper.java
  plugins/mapper-annotated-text/src/main/java/org/opensearch/search/fetch/subphase/highlight/AnnotatedTextHighlighter.java
  plugins/mapper-murmur3/src/main/java/org/opensearch/index/mapper/murmur3/Murmur3FieldMapper.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
  server/src/main/java/org/opensearch/index/mapper/AbstractGeometryFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/AllFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/ArraySourceValueFetcher.java
  server/src/main/java/org/opensearch/index/mapper/BinaryFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/BooleanFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/CompletionFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DataStreamFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/FieldNamesFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/IdFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/IgnoredFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/IndexFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/MappedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/RangeFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/RoutingFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/SeqNoFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/SourceValueFetcher.java
  server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/TypeFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/VersionFieldMapper.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/search/fetch/FetchContext.java
  server/src/main/java/org/opensearch/search/fetch/subphase/FetchFieldsPhase.java
  server/src/main/java/org/opensearch/search/fetch/subphase/FieldFetcher.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightUtils.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/PlainHighlighter.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java
  server/src/test/java/org/opensearch/index/fielddata/AbstractStringFieldDataTestCase.java
  server/src/test/java/org/opensearch/index/mapper/DocumentFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/ExternalMapper.java
  server/src/test/java/org/opensearch/index/mapper/FakeStringFieldMapper.java
  server/src/test/java/org/opensearch/search/collapse/CollapseBuilderTests.java
  server/src/test/java/org/opensearch/search/fetch/subphase/FieldFetcherTests.java
  server/src/test/java/org/opensearch/search/slice/SliceBuilderTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/FieldTypeTestCase.java
  test/framework/src/main/java/org/opensearch/index/mapper/MockFieldMapper.java
Labels: enhancement, v2.0.0

#2098 Add proxy username and password settings for Azure repository plugin
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureRepositoryPlugin.java
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageService.java
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageSettings.java
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/ProxySettings.java
  plugins/repository-azure/src/main/plugin-metadata/plugin-security.policy
  plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureStorageServiceTests.java
Labels: backport 1.x

#2104 [Remove] Type parameter from TermVectors API
  client/rest-high-level/src/main/java/org/opensearch/client/core/TermVectorsResponse.java
  client/rest-high-level/src/test/java/org/opensearch/client/core/TermVectorsResponseTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/documentation/CRUDDocumentationIT.java
  rest-api-spec/src/main/resources/rest-api-spec/test/mlt/20_docs.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/mlt/30_unlike.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/mtermvectors/20_deprecated.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/termvectors/20_issue7121.yml
  server/src/internalClusterTest/java/org/opensearch/action/IndicesRequestIT.java
  server/src/internalClusterTest/java/org/opensearch/action/termvectors/GetTermVectorsIT.java
  server/src/internalClusterTest/java/org/opensearch/action/termvectors/MultiTermVectorsIT.java
  server/src/internalClusterTest/java/org/opensearch/routing/SimpleRoutingIT.java
  server/src/internalClusterTest/java/org/opensearch/search/morelikethis/MoreLikeThisIT.java
  server/src/internalClusterTest/java/org/opensearch/validate/SimpleValidateQueryIT.java
  server/src/main/java/org/opensearch/action/RoutingMissingException.java
  server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsItemResponse.java
  server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsRequest.java
  server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsRequestBuilder.java
  server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsResponse.java
  server/src/main/java/org/opensearch/action/termvectors/TermVectorsRequest.java
  server/src/main/java/org/opensearch/action/termvectors/TermVectorsRequestBuilder.java
  server/src/main/java/org/opensearch/action/termvectors/TermVectorsResponse.java
  server/src/main/java/org/opensearch/action/termvectors/TransportMultiTermVectorsAction.java
  server/src/main/java/org/opensearch/action/termvectors/TransportShardMultiTermsVectorAction.java
  server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java
  server/src/main/java/org/opensearch/client/Client.java
  server/src/main/java/org/opensearch/client/support/AbstractClient.java
  server/src/main/java/org/opensearch/index/query/MoreLikeThisQueryBuilder.java
  server/src/main/java/org/opensearch/index/termvectors/TermVectorsService.java
  server/src/main/java/org/opensearch/rest/action/document/RestMultiTermVectorsAction.java
  server/src/main/java/org/opensearch/rest/action/document/RestTermVectorsAction.java
  server/src/test/java/org/opensearch/action/termvectors/AbstractTermVectorsTestCase.java
  server/src/test/java/org/opensearch/action/termvectors/GetTermVectorsTests.java
  server/src/test/java/org/opensearch/action/termvectors/TermVectorsUnitTests.java
  server/src/test/java/org/opensearch/action/termvectors/TransportMultiTermVectorsActionTests.java
  server/src/test/java/org/opensearch/index/query/MoreLikeThisQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/termvectors/TermVectorsServiceTests.java
  server/src/test/java/org/opensearch/rest/action/document/RestMultiTermVectorsActionTests.java
  server/src/test/java/org/opensearch/rest/action/document/RestTermVectorsActionTests.java
  server/src/test/resources/org/opensearch/action/termvectors/multiRequest1.json
  server/src/test/resources/org/opensearch/action/termvectors/multiRequest2.json
  server/src/test/resources/org/opensearch/action/termvectors/multiRequest3.json
Labels: v2.0.0, non-issue, >breaking, Indexing & Search

#2049 [Backport 1.x] Support first and last parameter for missing bucket ordering in composite aggregation
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/BinaryValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceConfig.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceParserHelper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/DateHistogramValuesSourceBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/DoubleValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/GeoTileGridValuesSourceBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/GeoTileValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/GlobalOrdinalValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/HistogramValuesSourceBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/LongValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/SingleDimensionValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/TermsValuesSourceBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/missing/MissingOrder.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationBuilderTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesCollectorQueueTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/InternalCompositeTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/SingleDimensionValuesSourceTests.java
Labels: enhancement, backport, v1.3.0

#2147 Adjust version after backport to 1.3.0.0
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
Labels: >test-failure, v2.0.0, backwards-compatibility

#2151 [Remove] Default Mapping
  modules/parent-join/src/test/java/org/opensearch/join/mapper/ParentJoinFieldMapperTests.java
  server/src/internalClusterTest/java/org/opensearch/search/morelikethis/MoreLikeThisIT.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/get/GetFieldMappingsResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/get/GetMappingsResponse.java
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/cluster/action/index/MappingUpdatedAction.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MappingMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataMappingService.java
  server/src/main/java/org/opensearch/index/mapper/DocumentMapperParser.java
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
  server/src/test/java/org/opensearch/index/mapper/DynamicTemplatesTests.java
  server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java
  server/src/test/java/org/opensearch/index/mapper/NestedObjectMapperTests.java
  server/src/test/java/org/opensearch/index/query/IdsQueryBuilderTests.java
  server/src/test/resources/org/opensearch/index/mapper/dynamictemplate/simple/test-mapping.json
  server/src/test/resources/org/opensearch/index/mapper/simple/test-mapping.json
Labels: v2.0.0, non-issue, >breaking, Indexing & Search

#2198 [Remove] Type Specific Index Stats
  client/rest-high-level/src/test/java/org/opensearch/client/CrudIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStats.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsRequestBuilder.java
  server/src/main/java/org/opensearch/action/update/TransportUpdateAction.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/IndexingStats.java
  server/src/main/java/org/opensearch/index/shard/InternalIndexingStats.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestIndicesStatsAction.java
Labels: v2.0.0, non-issue, Indexing & Search

#2246 [Backport] Case Insensitive Support in Regexp Interval (#2237)
  rest-api-spec/src/main/resources/rest-api-spec/test/search/230_interval_query.yml
  server/src/main/java/org/opensearch/index/query/IntervalsSourceProvider.java
  server/src/test/java/org/opensearch/index/query/IntervalQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/RegexpIntervalsSourceProviderTests.java
Labels: enhancement, backport, Indexing & Search, v1.3.0
