Repository opensearch-project/OpenSearch, pull requests merged in 2023-03, with the labels that each got.

#6511 Bumps snakeyaml to 2.0
  CHANGELOG.md
  buildSrc/version.properties
  libs/x-content/licenses/snakeyaml-1.33.jar.sha1
  libs/x-content/licenses/snakeyaml-2.0.jar.sha1
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
Labels: backport 2.x

#6486 replace unicode control chars as they can't be parsed by YAMLParser
  server/src/test/java/org/opensearch/search/fetch/subphase/highlight/HighlightFieldTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: backport 2.x, skip-changelog

#6215 [Searchable Snapshots] Add integration test to validate cache files are closed after use
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
Labels: :test, v3.0.0, backport 2.x, skip-changelog

#6523 [Segment Replication] Add new segrep settings
  server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
  test/framework/src/main/java/org/opensearch/test/transport/CapturingTransport.java
  test/framework/src/main/java/org/opensearch/test/transport/MockTransport.java
Labels: skip-changelog

#6526 [Segment Replication ]Remove state update of singleIndexWithSegmentReplicationDisabled in TransportSegmentReplicationStatsAction Class
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
Labels: backport 2.x, skip-changelog

#6525 [Segment Replication] Add new segrep settings (#6523)
  server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
  test/framework/src/main/java/org/opensearch/test/transport/CapturingTransport.java
  test/framework/src/main/java/org/opensearch/test/transport/MockTransport.java
Labels: skip-changelog

#6537 Update Gradle to 8.0.2
  gradle/wrapper/gradle-wrapper.properties
Labels: Build Libraries & Interfaces, skip-changelog

#6422 [Segment Replication] Allocation and rebalancing based on average primary shard count per index
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/Constraint.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/RebalanceConstraints.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsBalancer.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
  test/framework/src/main/java/org/opensearch/cluster/routing/TestShardRouting.java
Labels: v2.7.0

#6530 Change default block size to 8MiB
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java
  server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: backport 2.x, skip-changelog

#6335 [Weighted Routing] Add support to allow custom string search
  server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/test/java/org/opensearch/cluster/structure/RoutingIteratorTests.java
Labels: skip-changelog

#6545 [Extensions] Only store names of extension transport actions
  server/src/main/java/org/opensearch/extensions/RegisterTransportActionsRequest.java
  server/src/main/java/org/opensearch/extensions/action/ExtensionTransportActionsHandler.java
  server/src/test/java/org/opensearch/extensions/RegisterTransportActionsRequestTests.java
  server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java
Labels: backport 2.x, extensions, skip-changelog

#6561 Adding permissions for extensions directory
  server/src/main/java/org/opensearch/bootstrap/Security.java
Labels: backport 2.x, skip-changelog

#5827 Use ConcurrentHashMap for batching tasks per executor in TaskBatcher …
  server/src/main/java/org/opensearch/cluster/service/TaskBatcher.java
  server/src/test/java/org/opensearch/cluster/service/TaskBatcherTests.java
Labels: backport 2.x, skip-changelog

#6554 [Backport] [2.x] Bump io.projectreactor.netty:reactor-netty from 1.1.3 to 1.1.4 in /plugins/repository-azure (#6550)
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/reactor-netty-1.1.3.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-1.1.4.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.3.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.4.jar.sha1
Labels: backport

#6357 Implement equals/hashcode for named DocValueFormat inner classes
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/DocValueFormat.java
  server/src/test/java/org/opensearch/search/DocValueFormatTests.java
Labels: backport 2.x

#6191 [Extensions] Communicate implemented extension interfaces to OpenSearch
  server/src/main/java/org/opensearch/discovery/InitializeExtensionResponse.java
  server/src/main/java/org/opensearch/extensions/DiscoveryExtensionNode.java
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/test/java/org/opensearch/discovery/InitializeExtensionResponseTests.java
Labels: skip-changelog

#6555 Remove the JUnit test framework workaround for JarHell issue, fixed in Gradle 8.0.2
  build.gradle
Labels: Build Libraries & Interfaces, backport 2.x, skip-changelog

#6574 [Backport 2.x] Backporting extensions directory permissions
  server/src/main/java/org/opensearch/bootstrap/Security.java
Labels: skip-changelog

#6594 Segment Replication - Remove seqNo field from ReplicationCheckpoint and use UserData to transfer state.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
  server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
  server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
Labels: backport 2.x, skip-changelog

#6599 Fix to ensure fail open causes operations to complete. Also includes …
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
  server/src/main/java/org/opensearch/action/fieldcaps/TransportFieldCapabilitiesIndexAction.java
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/support/broadcast/TransportBroadcastAction.java
  server/src/main/java/org/opensearch/action/support/single/shard/TransportSingleShardAction.java
  server/src/main/java/org/opensearch/cluster/routing/FailAwareWeightedRouting.java
  server/src/test/java/org/opensearch/cluster/routing/FailAwareWeightedRoutingTests.java
Labels: backport 2.x, skip-changelog

#6538 Add file cache restore logic
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInput.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
Labels: backport 2.x, skip-changelog

#6569 Extend the length of OpenSearchJsonLayout logger from 10k to 100k
  CHANGELOG.md
  qa/logging-config/src/test/java/org/opensearch/common/logging/OpenSearchJsonLayoutTests.java
  server/src/main/java/org/opensearch/common/logging/OpenSearchJsonLayout.java
Labels: backport 2.x

#6601 [Backport 2.x] Remove seqNo field from ReplicationCheckpoint and use UserData to transfer state.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
  server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
  server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
Labels: skip-changelog

#6464 [Segment Replication] Update RefreshPolicy.WAIT_UNTIL for replica shards with segment replication enabled to wait for replica refresh
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/action/resync/TransportResyncReplicationAction.java
  server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
  server/src/main/java/org/opensearch/index/seqno/RetentionLeaseSyncAction.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RefreshListeners.java
  server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionForIndexingPressureTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
  test/framework/src/main/java/org/opensearch/action/support/replication/TransportWriteActionTestHelper.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
Labels: backport 2.x, skip-changelog

#6611 [Segment Replication] Prevent segment replication for ineligible targets during recovery
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
Labels: backport 2.x, skip-changelog

#6221 [Extensions] Add Regex validator
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/common/settings/WriteableSetting.java
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
Labels: backport 2.x, skip-changelog

#6622 Revert "[Segment Replication] Update RefreshPolicy.WAIT_UNTIL for rep…
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/action/resync/TransportResyncReplicationAction.java
  server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
  server/src/main/java/org/opensearch/index/seqno/RetentionLeaseSyncAction.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RefreshListeners.java
  server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionForIndexingPressureTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
  test/framework/src/main/java/org/opensearch/action/support/replication/TransportWriteActionTestHelper.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
Labels: skip-changelog

#6623 Allow newer versions of IDEA to control test iterations
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
Labels: skip-changelog

#6517 Add search node repurpose commands
  CHANGELOG.md
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/env/NodeRepurposeCommand.java
  server/src/test/java/org/opensearch/env/NodeRepurposeCommandTests.java
Labels: backport 2.x

#6592 Fix race with eviction when reading from FileCache
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/ConcurrentInvocationLinearizer.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/RefCountedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/StatsCounter.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/ConcurrentInvocationLinearizerTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/cache/LRUCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/cache/RefCountedCacheTestCase.java
  server/src/test/java/org/opensearch/index/store/remote/utils/cache/RefCountedCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/cache/SegmentedCacheTests.java
Labels: skip-changelog

#6581 Ut doc value format test
  server/src/test/java/org/opensearch/search/DocValueFormatTests.java
Labels: skip-changelog

#6615 Add return to avoid unnecessary computation
  server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
Labels: backport 2.x, skip-changelog

#6636 [Segment Replication] Prevent unnecessary shard failure on replication target
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
Labels: skip-changelog

#6657 Removed linelint and check EOL using spotless
  .github/workflows/code-hygiene.yml
  .linelint.yml
  gradle/formatting.gradle
  modules/repository-url/src/yamlRestTest/resources/rest-api-spec/test/repository_url/20_repository.yml
  plugins/repository-hdfs/src/test/resources/rest-api-spec/test/hdfs_repository/30_snapshot.yml
  plugins/repository-hdfs/src/test/resources/rest-api-spec/test/hdfs_repository/30_snapshot_get.yml
  plugins/transport-nio/build.gradle
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.cluster_manager/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.health/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.delete_alias/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/20_source_mapping.yml
  server/src/test/resources/org/opensearch/index/analysis/shingle_analysis.json
  server/src/test/resources/org/opensearch/index/analysis/shingle_analysis2.json
  test/framework/build.gradle
Labels: backport 2.x, skip-changelog

#6672 [Segment Replication] Mute segment replication pressure ITs
  server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
  server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
Labels: skip-changelog

#6637 [Segment Replication] Fix Flaky Test SegmentReplicationRelocationIT.testRelocateWhileContinuouslyIndexingAndWaitingForRefresh
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
  server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
Labels: backport 2.x, skip-changelog

#6678 Bump Mockito to 5.2.0 and ByteBuddy to 1.14.2
  buildSrc/version.properties
Labels: dependencies, skip-changelog

#6643 [Segment Replication] Add global primary shard balance constraint during allocation
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/Constraint.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/ConstraintTypes.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/RebalanceConstraints.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsBalancer.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java
Labels: skip-changelog

#6692 Update Maintainers List
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#6639 [Extensions] Adding testclass for InitializeExtensionRequest.java
  server/src/test/java/org/opensearch/discovery/InitializeExtensionRequestTests.java
Labels: backport 2.x, skip-changelog

#6682 Adds release notes for 1.3.9
  release-notes/opensearch.release-notes-1.3.9.md
Labels: backport 1.x, backport 1.3, skip-changelog

#6693 [Segment Replication] Override segment replication handler for duplicate request from replica
  server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
  server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
Labels: skip-changelog

#6698 Updated 1.3.9 release note to include latest version of Netty
  release-notes/opensearch.release-notes-1.3.9.md
Labels: backport 1.x, backport 1.3, skip-changelog

#6689 Fix shard allocation scenario with dedicated search nodes
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDeciderTests.java
Labels: backport 2.x, skip-changelog

#6674 Segment Replication - Update /_cat/segment_replication API with backpressure metrics.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationShardStatsResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPerGroupStats.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/main/java/org/opensearch/index/SegmentReplicationShardStats.java
  server/src/main/java/org/opensearch/index/SegmentReplicationStats.java
  server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java
  server/src/test/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationActionTests.java
Labels: skip-changelog

#6725 [Segment Replication] Remove completed_only query parameter from _cat/segment_replication API
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.segment_replication.json
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java
Labels: skip-changelog

#6694 [Extensions] Adding extensions to experimental list of features in opensearch.yml
  distribution/src/config/opensearch.yml
Labels: backport 2.x, extensions, skip-changelog

#6733 [2.6] Added BWC version 1.3.10
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#6732 [2.x] Added BWC version 1.3.10
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#6741 [Backport 2.x] Segment Replication - Update /_cat/segment_replication API with backp…
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationShardStatsResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPerGroupStats.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/main/java/org/opensearch/index/SegmentReplicationShardStats.java
  server/src/main/java/org/opensearch/index/SegmentReplicationStats.java
  server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java
  server/src/test/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationActionTests.java
Labels: skip-changelog

#6744 Fix java version for 1.3 maven snapshots
  .github/workflows/publish-maven-snapshots.yml
Labels: skip-changelog

#6746 [Backport 2.x] [Segment Replication] Remove completed_only query parameter from _cat/segment_replication API
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.segment_replication.json
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/SegmentReplicationStatsRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java
Labels: skip-changelog

#6749 [Segment Replication] Fix segrep compatibility check for closed indices
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
Labels: backport 2.x, skip-changelog

#6757 [Segment Replication] Handle update target cp for relocating primary
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: skip-changelog

#6756 [BUG] Fix index create block getting applied when there is no data nodes healthy
  server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitorTests.java
Labels: skip-changelog

#6670 Added github-merit-badger for OpenSearch
  .github/workflows/github-merit-badger.yml
Labels: skip-changelog

#6797 Fix document creation process for testCacheFilesAreClosedAfterUse IT
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
Labels: backport 2.x, skip-changelog, distinguished-contributor

#6795 [Segment Replication] Handling resource close
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
  server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
  server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
Labels: skip-changelog, distinguished-contributor

#6796 Fix node requirement for testPruneFileCacheOnIndexDeletion
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
Labels: backport 2.x, skip-changelog, distinguished-contributor

#6810 [Segment Replication] Remove deprecated feature flag check preventing SegmentReplicationSnapshotIT tests run
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
Labels: skip-changelog, distinguished-contributor

#6815 [Segment Replication] Mute testAllocationWithDisruption flaky test
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
Labels: backport 2.x, skip-changelog, distinguished-contributor

#6817 [Segment Replication] Fix testAllConstraints test
  server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
Labels: backport 2.x, skip-changelog, distinguished-contributor

#6734 [Extensions] Add DynamicActionRegistry to ActionModule
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/client/node/NodeClient.java
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/main/java/org/opensearch/extensions/action/ExtensionAction.java
  server/src/main/java/org/opensearch/extensions/action/ExtensionProxyTransportAction.java
  server/src/main/java/org/opensearch/extensions/action/ExtensionTransportAction.java
  server/src/main/java/org/opensearch/extensions/action/ExtensionTransportActionsHandler.java
  server/src/main/java/org/opensearch/extensions/action/RegisterTransportActionsRequest.java
  server/src/main/java/org/opensearch/extensions/action/RemoteExtensionActionResponse.java
  server/src/main/java/org/opensearch/extensions/action/TransportActionRequestFromExtension.java
  server/src/main/java/org/opensearch/extensions/action/TransportActionResponseToExtension.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/action/ActionModuleTests.java
  server/src/test/java/org/opensearch/client/node/NodeClientHeadersTests.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/extensions/RegisterTransportActionsRequestTests.java
  server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java
  server/src/test/java/org/opensearch/extensions/action/RemoteExtensionActionResponseTests.java
  server/src/test/java/org/opensearch/rest/action/admin/indices/RestValidateQueryActionTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/test/client/NoOpNodeClient.java
Labels: skip-changelog

#6434 Add wait_for_completion parameter to resize, open, and forcemerge APIs (#6228)
  CHANGELOG.md
  modules/reindex/src/main/java/org/opensearch/index/reindex/AbstractBaseReindexRestHandler.java
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.clone.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.forcemerge.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.open.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.shrink.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.split.json
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/40_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.forcemerge/20_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.open/30_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/50_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/40_wait_for_completion.yml
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/ShrinkIndexIT.java
  server/src/main/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/open/OpenIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/open/OpenIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/main/java/org/opensearch/action/support/master/AcknowledgedRequest.java
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestForceMergeAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestOpenIndexAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestResizeHandler.java
  server/src/test/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/open/OpenIndexRequestTests.java
  server/src/test/java/org/opensearch/action/admin/indices/open/OpenIndexResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/shrink/ResizeRequestTests.java
  server/src/test/java/org/opensearch/action/admin/indices/shrink/ResizeResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/shrink/TransportResizeActionTests.java
Labels: backport 2.x

#4719 Fix/2659 deprecation messages updated
  modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/UserAgentProcessor.java
  modules/ingest-user-agent/src/yamlRestTest/resources/rest-api-spec/test/ingest-useragent/20_useragent_processor.yml
  plugins/mapper-annotated-text/src/internalClusterTest/java/org/opensearch/index/mapper/annotatedtext/AnnotatedTextFieldMapperTests.java
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/30_copy_settings.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/30_copy_settings.yml
  server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/TypeParsers.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestResizeHandler.java
  server/src/test/java/org/opensearch/index/mapper/BooleanFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: enhancement, hacktoberfest, skip-changelog

#6331 Remove 'cluster_manager' role attachment when using 'node.master' deprecated setting
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/node/DiscoveryNodeRoleIT.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeRoleSettingTests.java
Labels: bug, v3.0.0, backport 2.x, v2.7.0

#6855 [Backport 2.x] Add wait_for_completion parameter to resize, open, and forcemerge APIs
  CHANGELOG.md
  modules/reindex/src/main/java/org/opensearch/index/reindex/AbstractBaseReindexRestHandler.java
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.clone.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.forcemerge.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.open.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.shrink.json
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.split.json
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/40_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.forcemerge/20_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.open/30_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/50_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/40_wait_for_completion.yml
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/ShrinkIndexIT.java
  server/src/main/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/open/OpenIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/open/OpenIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/ResizeResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/main/java/org/opensearch/action/support/master/AcknowledgedRequest.java
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestForceMergeAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestOpenIndexAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestResizeHandler.java
  server/src/test/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/open/OpenIndexRequestTests.java
  server/src/test/java/org/opensearch/action/admin/indices/open/OpenIndexResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/shrink/ResizeRequestTests.java
  server/src/test/java/org/opensearch/action/admin/indices/shrink/ResizeResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/shrink/TransportResizeActionTests.java
Labels: repeat-contributor

#6868 [Segment Replication] Fix flaky tests in SegmentReplicationPressureIT
  server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
Labels: backport 2.x, skip-changelog

#6871 Remove deprecated collection classes
  CHANGELOG.md
  libs/common/src/main/java/org/opensearch/common/collect/List.java
  libs/common/src/main/java/org/opensearch/common/collect/Map.java
  libs/common/src/main/java/org/opensearch/common/collect/Set.java
Labels: distinguished-contributor

#6876 [Backport] [1.x] fix for updating version numbers for deprecation messages (#4719)
  modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/UserAgentProcessor.java
  modules/ingest-user-agent/src/yamlRestTest/resources/rest-api-spec/test/ingest-useragent/20_useragent_processor.yml
  plugins/mapper-annotated-text/src/internalClusterTest/java/org/opensearch/index/mapper/annotatedtext/AnnotatedTextFieldMapperTests.java
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/30_copy_settings.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/30_copy_settings.yml
  server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/TypeParsers.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestResizeHandler.java
  server/src/test/java/org/opensearch/index/mapper/BooleanFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
  server/src/test/java/org/opensearch/rest/action/admin/indices/RestResizeHandlerTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java
Labels: skip-changelog

#6880 [Backport 2.x] Bump org.codehaus.jettison:jettison to 1.5.4 (#6878)
  CHANGELOG.md
  buildSrc/version.properties
  plugins/discovery-azure-classic/licenses/jettison-1.5.3.jar.sha1
  plugins/discovery-azure-classic/licenses/jettison-1.5.4.jar.sha1
Labels: distinguished-contributor

#6610 Implement microbenchmark for FileCache
  benchmarks/src/main/java/org/opensearch/benchmark/store/remote/filecache/FileCacheBenchmark.java
Labels: backport 2.x, skip-changelog

#6889 Mute SearchableSnapshotIT.testCacheFilesAreClosedAfterUse pending fix
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
Labels: backport 2.x, skip-changelog, distinguished-contributor

#6882 Fix changelog divergence for 2.x on main
  CHANGELOG.md
Labels: distinguished-contributor

#6834 Enhance search preference based routing for WRR
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
  server/src/main/java/org/opensearch/cluster/routing/FailAwareWeightedRouting.java
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingUtils.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/routing/FailAwareWeightedRoutingTests.java
  server/src/test/java/org/opensearch/cluster/structure/RoutingIteratorTests.java
Labels: skip-changelog, first-time-contributor

#6840 Upgrade forbiddenapis to 3.5.1
  buildSrc/build.gradle
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditPrecommitPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
  buildSrc/src/testKit/thirdPartyAudit/build.gradle
Labels: Build Libraries & Interfaces, skip-changelog, first-time-contributor

#6874 [Extensions] Update ExtensionRestResponse to handle RestRequest object
  server/src/main/java/org/opensearch/extensions/rest/ExtensionRestResponse.java
  server/src/main/java/org/opensearch/rest/RestRequest.java
  server/src/test/java/org/opensearch/extensions/rest/ExtensionRestResponseTests.java
Labels: skip-changelog, all-star-contributor

#6906 Revert github-merit-badger for OpenSearch
  .github/workflows/github-merit-badger.yml
Labels: skip-changelog, distinguished-contributor

#6914 Add privileged section to remote fetch/file cache write
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
Labels: backport 2.x, skip-changelog

#6758 [Extensions] BUG NPE handling and malformed Extension.yml
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
Labels: skip-changelog

#6921 [Backport 2.x] Bump azure-storage-blob from 12.15.0 to 12.20.0 in /plugins/repository-azure
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-storage-blob-12.15.0.jar.sha1
  plugins/repository-azure/licenses/azure-storage-blob-12.20.0.jar.sha1
Labels: backport, >upgrade, dependencies, v2.7.0, distinguished-contributor
