Repository opensearch-project/OpenSearch, pull requests merged in 2023-09, with the labels that each got.

#9679 Mute RemoteIndexShardTests primary promotion flaky tests
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
Labels: skip-changelog

#9638 [Backport] [2.x] [BWC and API enforcement] Decorate the existing APIs with proper annotations (part 1) (#9520)
  CHANGELOG.md
  libs/common/src/main/java/org/opensearch/common/CheckedConsumer.java
  libs/common/src/main/java/org/opensearch/common/action/ActionFuture.java
  libs/common/src/main/java/org/opensearch/common/lifecycle/Lifecycle.java
  libs/common/src/main/java/org/opensearch/common/lifecycle/LifecycleComponent.java
  libs/common/src/main/java/org/opensearch/common/unit/TimeValue.java
  libs/core/src/main/java/org/opensearch/Version.java
  libs/core/src/main/java/org/opensearch/core/ParseField.java
  libs/core/src/main/java/org/opensearch/core/action/ActionListener.java
  libs/core/src/main/java/org/opensearch/core/common/bytes/BytesReference.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/NamedWriteableRegistry.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamInput.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamOutput.java
  libs/core/src/main/java/org/opensearch/core/common/settings/SecureString.java
  libs/core/src/main/java/org/opensearch/core/common/unit/ByteSizeUnit.java
  libs/core/src/main/java/org/opensearch/core/common/unit/ByteSizeValue.java
  libs/core/src/main/java/org/opensearch/core/index/Index.java
  libs/core/src/main/java/org/opensearch/core/index/shard/ShardId.java
  libs/core/src/main/java/org/opensearch/core/rest/RestStatus.java
  libs/core/src/main/java/org/opensearch/core/tasks/TaskId.java
  libs/core/src/main/java/org/opensearch/core/xcontent/MediaType.java
  libs/core/src/main/java/org/opensearch/core/xcontent/NamedXContentRegistry.java
  libs/core/src/main/java/org/opensearch/core/xcontent/XContentBuilder.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapCheck.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapContext.java
  server/src/main/java/org/opensearch/client/AdminClient.java
  server/src/main/java/org/opensearch/client/Client.java
  server/src/main/java/org/opensearch/client/ClusterAdminClient.java
  server/src/main/java/org/opensearch/client/IndicesAdminClient.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/common/inject/Module.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/SecureSettings.java
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/common/settings/SettingUpgrader.java
  server/src/main/java/org/opensearch/common/settings/Settings.java
  server/src/main/java/org/opensearch/common/settings/SettingsException.java
  server/src/main/java/org/opensearch/env/Environment.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/env/ShardLock.java
  server/src/main/java/org/opensearch/env/ShardLockObtainFailedException.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexSettingProvider.java
  server/src/main/java/org/opensearch/plugins/Plugin.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/main/java/org/opensearch/script/Script.java
  server/src/main/java/org/opensearch/script/ScriptContext.java
  server/src/main/java/org/opensearch/script/ScriptEngine.java
  server/src/main/java/org/opensearch/script/ScriptService.java
  server/src/main/java/org/opensearch/script/ScriptType.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/main/java/org/opensearch/watcher/ResourceWatcherService.java
Labels: backport, v2.10.0, API

#9615 remove redundent column headers in pit segments response
  server/src/main/java/org/opensearch/rest/action/cat/RestPitSegmentsAction.java
Labels: skip-changelog

#9630 [Segment Replication] Allow segment replication with on disk files not referenced by reader with matching checksum
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
Labels: skip-changelog

#9682 [Remote Store] Mute RemoteIndexRecoveryIT.testReplicaRecovery flaky test
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexRecoveryIT.java
Labels: skip-changelog

#9701 [Backport] [2.x] [Tracing Framework] Redefine telemetry context restoration and propag…
  CHANGELOG.md
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultScopedSpan.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultSpanScope.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/ScopedSpan.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanCreationContext.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanScope.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Tracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/TracingTelemetry.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/http/HttpTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopScopedSpan.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopSpan.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopSpanScope.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/runnable/TraceableRunnable.java
  libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultScopedSpanTests.java
  libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
  libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/TraceableRunnableTests.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelSpan.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelTracingTelemetry.java
  server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
  server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
  server/src/main/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorage.java
  server/src/main/java/org/opensearch/telemetry/tracing/WrappedTracer.java
  server/src/test/java/org/opensearch/telemetry/tracing/SpanBuilderTests.java
  server/src/test/java/org/opensearch/telemetry/tracing/TracerFactoryTests.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockSpan.java
Labels: v2.10.0

#9670 Add average query concurrency metric for concurrent segment search
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
  server/src/internalClusterTest/java/org/opensearch/search/stats/ConcurrentSearchStatsIT.java
  server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
  server/src/main/java/org/opensearch/index/search/stats/ShardSearchStats.java
  server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java
Labels: backport 2.x

#9477 Add support download latest index metadata from remote
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/BlobContainer.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#9683 Disable shard/segment level search_after short cutting if track_total_hits != false
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
Labels: bug, Indexing & Search, v2.10.0

#9629 Segment Replication - Block snapshot creation if the target primary shard has not completed failover.
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: skip-changelog

#9653 [Backport 2.x] Adding concurrent search versions of query count and time metrics (#9622)
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
  server/src/internalClusterTest/java/org/opensearch/search/stats/ConcurrentSearchStatsIT.java
  server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
  server/src/main/java/org/opensearch/index/search/stats/ShardSearchStats.java
  server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
Labels: backport, v2.10.0

#9745 [Segment Replication] Update version back to 2_10_0 in Segmentstats.
  server/src/main/java/org/opensearch/index/engine/SegmentsStats.java
Labels: skip-changelog

#9722 Fix bwc version for concurrent segment search stats
  server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
Labels: skip-changelog

#9749 BWC fix for crypto settings in repository request and metadata
  server/src/main/java/org/opensearch/OpenSearchServerException.java
  server/src/main/java/org/opensearch/action/admin/cluster/repositories/put/PutRepositoryRequest.java
  server/src/main/java/org/opensearch/cluster/metadata/RepositoryMetadata.java
Labels: skip-changelog

#9706 [Tracing Framework] Add proper API annotations
  libs/telemetry/build.gradle
  libs/telemetry/src/main/java/org/opensearch/telemetry/Telemetry.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/MetricsTelemetry.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/AbstractSpan.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultScopedSpan.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultSpanScope.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/ScopedSpan.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Span.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanContext.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanCreationContext.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanReference.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanScope.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Tracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/TracerContextStorage.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/TracingContextPropagator.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/TracingTelemetry.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/attributes/Attributes.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/attributes/package-info.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/http/HttpTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopScopedSpan.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopSpan.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopSpanScope.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopTracer.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelSpan.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/sampler/ProbabilisticSampler.java
  server/src/main/java/org/opensearch/plugins/TelemetryPlugin.java
  server/src/main/java/org/opensearch/telemetry/TelemetrySettings.java
  server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
  server/src/main/java/org/opensearch/telemetry/tracing/NoopTracerFactory.java
  server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
  server/src/main/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorage.java
  server/src/main/java/org/opensearch/telemetry/tracing/TracerFactory.java
  server/src/main/java/org/opensearch/telemetry/tracing/WrappedTracer.java
Labels: skip-changelog, v2.10.0

#9765 Add Peter Nied as a Maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#9763 Rename remote store stats field names
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
Labels: skip-changelog

#9248 Add support for query profiler with concurrent aggregation
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/main/java/org/opensearch/search/profile/AbstractInternalProfileTree.java
  server/src/main/java/org/opensearch/search/profile/AbstractProfileBreakdown.java
  server/src/main/java/org/opensearch/search/profile/ContextualProfileBreakdown.java
  server/src/main/java/org/opensearch/search/profile/aggregation/AggregationProfileBreakdown.java
  server/src/main/java/org/opensearch/search/profile/query/AbstractQueryProfileTree.java
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileTree.java
  server/src/main/java/org/opensearch/search/profile/query/InternalQueryProfileTree.java
  server/src/main/java/org/opensearch/search/profile/query/ProfileWeight.java
  server/src/main/java/org/opensearch/search/profile/query/QueryProfiler.java
  server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdownTests.java
  server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: Indexing & Search, backport 2.x, v2.10.0

#9711 [Segment Replication] Fix shrink Index bug with segment replication.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationResizeRequestIT.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java
Labels: backport 2.x, skip-changelog

#9769 [Backport 2.x] [Snapshot Interop] Add Logic in Lock Manager to cleanup stale data po…
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerFactory.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: skip-changelog

#9565 Retry download of RemoteFSTranslog to fix transient race conditions
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Labels: skip-changelog

#9728 fix: flaky test ClusterMetadataManifestTests
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
Labels: skip-changelog

#9791 [Remote Store] Fix searchable snapshot to not sync from remote
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: backport 2.x, skip-changelog

#9802 Crypto Metadata support in repo registration
  server/src/main/java/org/opensearch/action/admin/cluster/crypto/CryptoSettings.java
  server/src/main/java/org/opensearch/cluster/metadata/CryptoMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/test/java/org/opensearch/node/RemoteStoreNodeAttributeTests.java
Labels: skip-changelog

#9664 [Remote Cluster State] Parallel and Multipart IndexMetadata uploads
  server/src/main/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainer.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/snapshots/BlobStoreFormatTests.java
Labels: skip-changelog

#9086 [Remote Store] Add support to remote restore IndexMetadata
  server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/node/Node.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: skip-changelog

#9818 Validate MockTracingTelemetry span state on shutdown.
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
  test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetry.java
  test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetryPlugin.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingTelemetry.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java
Labels: skip-changelog

#9833 Removing ESDK changes from core
  distribution/tools/plugin-cli/build.gradle
  libs/common/src/main/java/org/opensearch/common/crypto/CryptoHandler.java
  libs/encryption-sdk/build.gradle
  libs/encryption-sdk/licenses/aws-encryption-sdk-java-2.4.0.jar.sha1
  libs/encryption-sdk/licenses/aws-encryption-sdk-java-NOTICE.txt
  libs/encryption-sdk/src/forbidden/crypto-signatures.txt
  libs/encryption-sdk/src/forbidden/crypto-test-signatures.txt
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/CryptoManager.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/CryptoManagerFactory.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/NoOpCryptoHandler.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/TrimmingStream.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/keyprovider/CryptoMasterKey.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/keyprovider/package-info.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/package-info.java
  libs/encryption-sdk/src/test/java/org/opensearch/encryption/CryptoManagerFactoryTests.java
  libs/encryption-sdk/src/test/java/org/opensearch/encryption/MockKeyProvider.java
  libs/encryption-sdk/src/test/java/org/opensearch/encryption/NoOpCryptoHandlerTests.java
  libs/encryption-sdk/src/test/java/org/opensearch/encryption/TrimmingStreamTests.java
  libs/encryption-sdk/src/test/resources/encrypted_key
  libs/encryption-sdk/src/test/resources/raw_content_for_crypto_test
  libs/encryption-sdk/src/test/resources/raw_key
  plugins/crypto-kms/build.gradle
  plugins/crypto-kms/src/main/java/org/opensearch/crypto/kms/KmsService.java
  plugins/ingest-attachment/licenses/commons-lang3-3.13.0.jar.sha1
  plugins/ingest-attachment/licenses/commons-lang3-LICENSE.txt
  plugins/ingest-attachment/licenses/commons-lang3-NOTICE.txt
  plugins/repository-azure/licenses/commons-lang3-3.13.0.jar.sha1
  plugins/repository-azure/licenses/commons-lang3-LICENSE.txt
  plugins/repository-azure/licenses/commons-lang3-NOTICE.txt
  plugins/repository-hdfs/licenses/commons-lang3-3.13.0.jar.sha1
  plugins/repository-hdfs/licenses/commons-lang3-LICENSE.txt
  plugins/repository-hdfs/licenses/commons-lang3-NOTICE.txt
  server/build.gradle
  server/src/main/java/org/opensearch/common/blobstore/EncryptedBlobStore.java
  server/src/main/java/org/opensearch/crypto/CryptoHandlerRegistry.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/CryptoPlugin.java
  server/src/test/java/org/opensearch/crypto/CryptoHandlerRegistryTests.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
Labels: skip-changelog

#9842 Mute flaky test ReadContextListenerTests.testReadContextListenerFailure
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java
Labels: backport 2.x, skip-changelog, backport 2.10

#9849 Bump 2.x to 2.11.0
  .ci/bwcVersions
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#9810 [Remote Store] Muting RemoteStoreRefreshListenerTests.testReplicaPromotion
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#9862 [Backport 2.x][Remote Store] Add support to remote restore IndexMetadata (#9086)
  server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/node/Node.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: skip-changelog

#9856 Bump 2.x version to 2.11
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#9796 Decrease store refcount on any failure to create NRTReplicationEngine
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
Labels: skip-changelog

#9873 Mute org.opensearch.index.codec.MultiCodecMergeIT.testForceMergeMulti…
  plugins/custom-codecs/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecMergeIT.java
Labels: skip-changelog

#9754 [Remote Store] Update version check for Remote Translog Store upload flow stats in nodes stats API
  server/src/main/java/org/opensearch/index/translog/TranslogStats.java
Labels: skip-changelog

#9878 [Remote Store] Removing asserts based on translog stats as it is not applicable for …
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
Labels: skip-changelog

#9811 [Remote Cluster State] Move remote cluster state related settings to node attrs
  server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/node/RemoteStoreNodeAttributeTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
  test/framework/src/main/java/org/opensearch/gateway/MockGatewayMetaState.java
Labels: skip-changelog

#9889 [Bug Fix] Fixing Flaky Codec Tests
  modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java
  plugins/custom-codecs/src/internalClusterTest/java/org/opensearch/index/codec/CodecCompressionLevelIT.java
  plugins/custom-codecs/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecMergeIT.java
Labels: skip-changelog

#9893 [Remote Cluster State] Move remote cluster state related settings to …
  server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/node/RemoteStoreNodeAttributeTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
  test/framework/src/main/java/org/opensearch/gateway/MockGatewayMetaState.java
Labels: skip-changelog

#9895 [Backport 2.x] Add logic to fetch previousClusterUUID (#9746)
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#9742 Unmute testIndexingWithPrimaryOnBwcNodes
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
Labels: backport 2.x, skip-changelog

#9901 [Backport 2.10] Removing feature flag to mark feature GA
  CHANGELOG.md
  distribution/src/config/opensearch.yml
  server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationWithRemoteStorePressureIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RemoteIndexSnapshotStatusApiIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsActionTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Labels: skip-changelog

#9898 [Backport 2.10] Add logic to fetch previousClusterUUID (#9746)
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#9899 [Remote Store] Changing compatibility version of sourceRemoteStoreRepository in RestoreSnaphotRequest back to 2.10
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
Labels: skip-changelog

#9903 [Backport 2.10] Decrease store refcount on any failure to create NRTReplicationEngine
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
Labels: skip-changelog

#9719 [Remote Cluster State] Remove stale remote cluster state
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
  test/framework/src/main/java/org/opensearch/gateway/MockGatewayMetaState.java
Labels: skip-changelog

#9902 [Backport 2.x] Decrease store refcount on any failure to create NRTReplicationEngine
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
Labels: skip-changelog

#9782 Fix default tracer flaky test
  libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
Labels: skip-changelog

#9908 Disable remote integrity check for encrypted repos for ChecksumBlobstoreFormat
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#9585 [Segment Replication] Support realtime TermVector requests with Segment Replication
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/action/termvectors/TransportTermVectorsAction.java
Labels: skip-changelog

#9944 Remove custom-codecs plugin
  CHANGELOG.md
  modules/reindex/build.gradle
  modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java
  plugins/custom-codecs/build.gradle
  plugins/custom-codecs/src/internalClusterTest/java/org/opensearch/index/codec/CodecCompressionLevelIT.java
  plugins/custom-codecs/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecMergeIT.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecPlugin.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecService.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecServiceFactory.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomCodec.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomStoredFieldsFormat.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCodec.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCompressionMode.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdDeprecatedCodec.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCodec.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCompressionMode.java
  plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/package-info.java
  plugins/custom-codecs/src/main/plugin-metadata/plugin-security.policy
  plugins/custom-codecs/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  plugins/custom-codecs/src/test/java/org/opensearch/index/codec/customcodecs/AbstractCompressorTests.java
  plugins/custom-codecs/src/test/java/org/opensearch/index/codec/customcodecs/CustomCodecTests.java
  plugins/custom-codecs/src/test/java/org/opensearch/index/codec/customcodecs/Lucene95CustomStoredFieldsFormatTests.java
  plugins/custom-codecs/src/test/java/org/opensearch/index/codec/customcodecs/ZstdCompressorTests.java
  plugins/custom-codecs/src/test/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCompressorTests.java
Labels: backport 2.x

#9915 Fix ReadContextListenerTests to avoid inconsistent WindowsFS file han…
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java
Labels: backport 2.x, skip-changelog

#9956 Mute CorrelationCodecTests.testCorrelationVectorIndex
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/codec/correlation950/CorrelationCodecTests.java
Labels: backport 2.x, skip-changelog

#9954 Update single comment for check compatibility
  .github/workflows/check-compatibility.yml
Labels: skip-changelog

#9817 Fixing various javadocs
  libs/cli/src/main/java/org/opensearch/cli/ExitCodes.java
  libs/cli/src/main/java/org/opensearch/cli/Terminal.java
  libs/common/src/main/java/org/opensearch/common/collect/Tuple.java
  libs/common/src/main/java/org/opensearch/common/crypto/CryptoHandler.java
  libs/common/src/main/java/org/opensearch/common/crypto/DataKeyPair.java
  libs/common/src/main/java/org/opensearch/common/crypto/DecryptedRangedStreamProvider.java
  libs/common/src/main/java/org/opensearch/common/crypto/MasterKeyProvider.java
  libs/compress/src/main/java/org/opensearch/compress/spi/CompressionProvider.java
Labels: skip-changelog

#9973 Bump org.apache.commons:commons-compress from 1.23.0 to 1.24.0
  CHANGELOG.md
  buildSrc/version.properties
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/plugin-cli/licenses/commons-compress-1.23.0.jar.sha1
  distribution/tools/plugin-cli/licenses/commons-compress-1.24.0.jar.sha1
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/commons-compress-1.23.0.jar.sha1
  plugins/ingest-attachment/licenses/commons-compress-1.24.0.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/commons-compress-1.23.0.jar.sha1
  plugins/repository-hdfs/licenses/commons-compress-1.24.0.jar.sha1
Labels: dependencies

#9950 Bump OpenTelemetry from 1.26.0 to 1.30.1
  CHANGELOG.md
  buildSrc/version.properties
  plugins/telemetry-otel/build.gradle
  plugins/telemetry-otel/licenses/opentelemetry-api-1.26.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-logs-1.26.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-logs-LICENSE.txt
  plugins/telemetry-otel/licenses/opentelemetry-api-logs-NOTICE.txt
  plugins/telemetry-otel/licenses/opentelemetry-context-1.26.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.26.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.26.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.26.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.26.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.26.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.26.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.26.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.30.1-alpha.jar.sha1
Labels: dependencies

#9965 Block unsafe bootstrap when remote state is enabled
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/UnsafeBootstrapAndDetachCommandIT.java
  server/src/main/java/org/opensearch/cluster/coordination/UnsafeBootstrapClusterManagerCommand.java
Labels: skip-changelog

#9993 Don't over-allocate in HeapBufferedAsyncEntityConsumer in order to consume the response
  CHANGELOG.md
  client/rest/src/main/java/org/opensearch/client/nio/HeapBufferedAsyncEntityConsumer.java
  client/rest/src/test/java/org/opensearch/client/nio/HeapBufferedAsyncEntityConsumerTests.java
Labels: bug, v3.0.0

#9995 Remove tf() painless method
  modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.score.txt
  server/src/main/java/org/opensearch/index/query/functionscore/TermFrequencyFunctionFactory.java
  server/src/main/java/org/opensearch/script/ScoreScriptUtils.java
Labels: backport 2.x, skip-changelog, backport 2.10

#9845 Parameterize the tests for concurrent search
  server/src/internalClusterTest/java/org/opensearch/search/SearchWithRejectionsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityWithRequestBreakerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/GeoCentroidIT.java
  server/src/internalClusterTest/java/org/opensearch/search/backpressure/SearchBackpressureIT.java
  server/src/internalClusterTest/java/org/opensearch/search/basic/SearchRedStateIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/search/basic/SearchWhileCreatingIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/search/basic/SearchWhileRelocatingIT.java
  server/src/internalClusterTest/java/org/opensearch/search/basic/SearchWithRandomExceptionsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/basic/SearchWithRandomIOExceptionsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/basic/TransportSearchFailuresIT.java
  server/src/internalClusterTest/java/org/opensearch/search/basic/TransportTwoNodesSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/FetchSubPhasePluginIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/InnerHitsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/MatchedQueriesIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/CustomHighlighterSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fieldcaps/FieldCapabilitiesIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/DecayFunctionScoreIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/ExplainableScriptIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/FunctionScoreFieldValueIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/FunctionScoreIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/FunctionScorePluginIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/QueryRescorerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/RandomScoreFunctionIT.java
  server/src/internalClusterTest/java/org/opensearch/search/geo/GeoFilterIT.java
  server/src/internalClusterTest/java/org/opensearch/search/geo/GeoPolygonIT.java
  server/src/internalClusterTest/java/org/opensearch/search/geo/GeoShapeIntegrationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/geo/LegacyGeoShapeIntegrationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/morelikethis/MoreLikeThisIT.java
  server/src/internalClusterTest/java/org/opensearch/search/msearch/MultiSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java
  server/src/internalClusterTest/java/org/opensearch/search/preference/SearchPreferenceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/profile/aggregation/AggregationProfilerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/ExistsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/MultiMatchQueryIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/QueryStringIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/ScriptScoreQueryIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java
  server/src/internalClusterTest/java/org/opensearch/search/slice/SearchSliceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/source/MetadataFetchingIT.java
  server/src/internalClusterTest/java/org/opensearch/search/source/SourceFetchingIT.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/AbstractGeoTestCase.java
Labels: backport 2.x, skip-changelog

#10022 Bump mockito and bytebuddy
  CHANGELOG.md
  buildSrc/version.properties
Labels: dependencies

#10010 Add workflow to copy labels from linked issues to the PR
  .github/workflows/copy-linked-issue-labels.yml
Labels: backport 2.x, skip-changelog

#9852 Parameterize tests for concurrent search 2
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/CombiIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/MetadataIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/BooleanTermsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DateRangeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DoubleTermsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/FilterIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/FiltersIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/GeoDistanceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/GlobalIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/HistogramIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/IpRangeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/IpTermsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/LongTermsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/MinDocCountIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/MultiTermsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/NaNSortingIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/NestedIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/RangeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/ReverseNestedIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/SamplerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/ShardReduceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/SignificantTermsSignificanceScoreIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsDocCountErrorIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/terms/BaseStringTermsTestCase.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/terms/StringTermsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/ExtendedStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/HDRPercentileRanksIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/HDRPercentilesIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/MedianAbsoluteDeviationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/ScriptedMetricIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/StatsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/SumIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/TDigestPercentileRanksIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/TDigestPercentilesIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/TopHitsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/ValueCountIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/AvgBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/BucketScriptIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/BucketSelectorIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/BucketSortIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/DateDerivativeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/DerivativeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/ExtendedStatsBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/MaxBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/MinBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/MovAvgIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/PercentilesBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/SerialDiffIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/StatsBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/SumBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/sort/GeoDistanceIT.java
  test/framework/src/main/java/org/opensearch/search/aggregations/bucket/AbstractTermsTestCase.java
  test/framework/src/main/java/org/opensearch/search/aggregations/metrics/AbstractNumericTestCase.java
Labels: backport 2.x, skip-changelog

#9982 Parameterize tests for concurrent search 3
  modules/analysis-common/src/internalClusterTest/java/org/opensearch/analysis/common/QueryStringWithAnalyzersIT.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/HighlighterWithAnalyzersTests.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/GeoModulePluginIntegTestCase.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/MissingValueIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoHashGridIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoTileGridIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/ShardReduceIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/AbstractGeoAggregatorModulePluginTestCase.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsITTestCase.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/GeoCentroidITTestCase.java
  modules/lang-expression/src/internalClusterTest/java/org/opensearch/script/expression/MoreExpressionIT.java
  modules/lang-expression/src/internalClusterTest/java/org/opensearch/script/expression/StoredExpressionIT.java
  modules/lang-mustache/src/internalClusterTest/java/org/opensearch/script/mustache/MultiSearchTemplateIT.java
  modules/percolator/src/internalClusterTest/java/org/opensearch/percolator/PercolatorQuerySearchIT.java
  modules/rank-eval/src/internalClusterTest/java/org/opensearch/index/rankeval/RankEvalRequestIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/CancellableTasksIT.java
  server/src/internalClusterTest/java/org/opensearch/action/termvectors/GetTermVectorsIT.java
  server/src/internalClusterTest/java/org/opensearch/action/termvectors/MultiTermVectorsIT.java
  server/src/internalClusterTest/java/org/opensearch/index/IndexSortIT.java
  server/src/internalClusterTest/java/org/opensearch/index/search/MatchPhraseQueryIT.java
  server/src/internalClusterTest/java/org/opensearch/index/suggest/stats/SuggestStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/mget/SimpleMgetIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/EquivalenceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/AdjacencyMatrixIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DateHistogramIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DateHistogramOffsetIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/ShardSizeTermsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsShardMinDocCountIT.java
  server/src/internalClusterTest/java/org/opensearch/search/stats/SearchStatsIT.java
  server/src/test/java/org/opensearch/action/termvectors/AbstractTermVectorsTestCase.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/ShardSizeTestCase.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/AbstractGeoTestCase.java
  test/external-modules/delayed-aggs/src/internalClusterTest/java/org/opensearch/search/aggregations/DelayedShardAggregationIT.java
Labels: backport 2.x, skip-changelog

#10037 Fix typo in Precommit and Assemble workflow
  .github/workflows/precommit.yml
Labels: skip-changelog

#9976 Fixing javadoc error
  libs/common/src/main/java/org/opensearch/common/collect/Iterators.java
  libs/compress/src/main/java/org/opensearch/compress/ZstdCompressor.java
  libs/core/src/main/java/org/opensearch/core/common/breaker/CircuitBreaker.java
  libs/core/src/main/java/org/opensearch/core/common/breaker/CircuitBreakingException.java
  libs/core/src/main/java/org/opensearch/core/common/breaker/NoopCircuitBreaker.java
  libs/core/src/main/java/org/opensearch/core/common/bytes/AbstractBytesReference.java
  libs/core/src/main/java/org/opensearch/core/common/logging/LoggerMessageFormat.java
  libs/core/src/main/java/org/opensearch/core/common/transport/TransportAddress.java
  libs/core/src/main/java/org/opensearch/core/common/unit/ByteSizeUnit.java
  libs/core/src/main/java/org/opensearch/core/common/util/CollectionUtils.java
  libs/core/src/main/java/org/opensearch/core/index/Index.java
  libs/core/src/main/java/org/opensearch/core/index/shard/ShardId.java
  libs/core/src/main/java/org/opensearch/core/indices/breaker/AllCircuitBreakerStats.java
  libs/core/src/main/java/org/opensearch/core/indices/breaker/CircuitBreakerStats.java
  libs/core/src/main/java/org/opensearch/core/indices/breaker/NoneCircuitBreakerService.java
  libs/geo/src/main/java/org/opensearch/geometry/Circle.java
Labels: skip-changelog

#10051 Sync Guava version across all modules
  distribution/tools/keystore-cli/build.gradle
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/upgrade-cli/build.gradle
  plugins/ingest-attachment/build.gradle
  plugins/repository-azure/build.gradle
  plugins/repository-gcs/build.gradle
  plugins/repository-hdfs/build.gradle
  qa/evil-tests/build.gradle
Labels: skip-changelog

#10055 Exclude packaged guava from jimfs
  qa/evil-tests/build.gradle
Labels: skip-changelog

#10052 Disable stalled PR workflow
  .github/workflows/stalled.yml
Labels: backport 2.x, skip-changelog

#10058 Add release notes for 1.3.13
  release-notes/opensearch.release-notes-1.3.13.md
Labels: skip-changelog

#9441 Parameterize ITs to run with concurrent search enabled
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/script/ScriptCacheIT.java
  server/src/internalClusterTest/java/org/opensearch/search/StressSearchServiceReaperIT.java
  server/src/internalClusterTest/java/org/opensearch/search/pit/PitMultiNodeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/scriptfilter/ScriptQuerySearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/scroll/DuelScrollIT.java
  server/src/internalClusterTest/java/org/opensearch/search/scroll/SearchScrollIT.java
  server/src/internalClusterTest/java/org/opensearch/search/scroll/SearchScrollWithFailingNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/search/searchafter/SearchAfterIT.java
  server/src/internalClusterTest/java/org/opensearch/search/sort/GeoDistanceSortBuilderIT.java
  server/src/internalClusterTest/java/org/opensearch/search/sort/SortFromPluginIT.java
  server/src/internalClusterTest/java/org/opensearch/search/suggest/CompletionSuggestSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/suggest/ContextCompletionSuggestSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/suggest/SuggestSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/similarity/SimilarityIT.java
Labels: backport 2.x, skip-changelog

#9887 Fix flaky behavior of RemoteStoreRestoreIT.testRateLimitedRemoteDownloads
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
Labels: skip-changelog

#10042 Add tracing instrumentation in transport service
  CHANGELOG.md
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerEnabledSanityIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/single/SingleNodeDiscoveryIT.java
  server/src/main/java/org/opensearch/telemetry/tracing/handler/TraceableTransportResponseHandler.java
  server/src/main/java/org/opensearch/telemetry/tracing/handler/package-info.java
  server/src/main/java/org/opensearch/transport/TransportResponseHandler.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, distributed framework, v3.0.0, v2.11.0

#10012 Always create empty translog on replica for remote store enabled index
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/TranslogHeader.java
Labels: skip-changelog

#10045 Fix broken backward compatibility from 2.7 for IndexSorted field indices
  CHANGELOG.md
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/IndexSortConfig.java
  server/src/main/java/org/opensearch/index/fielddata/IndexFieldData.java
  server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java
  server/src/test/java/org/opensearch/index/IndexServiceTests.java
  server/src/test/java/org/opensearch/index/fielddata/AbstractFieldDataImplTestCase.java
Labels: bug, rolling-upgrade

#9694 Add async read support for S3 plugin
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/utils/HttpRangeUtils.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/utils/HttpRangeUtilsTests.java
Labels: enhancement, distributed framework

#9962 skip overriding routing table when it already contains entries with remote recovery source
  server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/test/java/org/opensearch/gateway/ClusterStateUpdatersTests.java
Labels: bug, skip-changelog, cluster-manager, v2.10.0

#10087 Integ test fix -> Fix broken backward compatibility from 2.7 for IndexSorted field indices #10045
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSortConfig.java
Labels: skip-changelog

#10076 [Backport 2.10] Fix broken backward compatibility from 2.7 for IndexSorted field indi…
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  release-notes/opensearch.release-notes-2.10.0.md
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/IndexSortConfig.java
  server/src/main/java/org/opensearch/index/fielddata/IndexFieldData.java
  server/src/main/java/org/opensearch/index/fielddata/IndexNumericFieldData.java
  server/src/test/java/org/opensearch/index/IndexServiceTests.java
  server/src/test/java/org/opensearch/index/fielddata/AbstractFieldDataImplTestCase.java
Labels: skip-changelog

#9636 Optimize read write lock constructs during translog upload to remote store
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/listener/TranslogTransferListener.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: enhancement, durability, backport 2.x, skip-changelog, storage, v2.11.0

#10020 Fix cluster chaining during bootstrap
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#10031 Update Apache Lucene to 9.8.0-snapshot-95cdd2e
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.8.0-snapshot-4373c3b.jar.sha1
  libs/core/licenses/lucene-core-9.8.0-snapshot-95cdd2e.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.8.0-snapshot-4373c3b.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.8.0-snapshot-95cdd2e.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.8.0-snapshot-95cdd2e.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.8.0-snapshot-95cdd2e.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.8.0-snapshot-95cdd2e.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.8.0-snapshot-95cdd2e.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.8.0-snapshot-95cdd2e.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.8.0-snapshot-95cdd2e.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.8.0-snapshot-95cdd2e.jar.sha1
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/mapper/CorrelationVectorFieldMapper.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/query/CorrelationQueryBuilderTests.java
  server/licenses/lucene-analysis-common-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-analysis-common-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-backward-codecs-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-backward-codecs-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-core-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-core-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-grouping-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-grouping-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-highlighter-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-highlighter-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-join-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-join-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-memory-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-memory-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-misc-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-misc-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-queries-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-queries-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-queryparser-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-queryparser-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-sandbox-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-sandbox-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-spatial-extras-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-spatial-extras-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-spatial3d-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-spatial3d-9.8.0-snapshot-95cdd2e.jar.sha1
  server/licenses/lucene-suggest-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-suggest-9.8.0-snapshot-95cdd2e.jar.sha1
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/ConcurrentSearchTasksIT.java
  server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java
  server/src/main/java/org/opensearch/index/search/comparators/UnsignedLongComparator.java
Labels: dependencies, skip-changelog

#7008 Remove outdated default index mapping error message
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
Labels: bug, backport 2.x, skip-changelog

#10140 Update Github action for Gradle precommit on MacOS
  .github/workflows/precommit.yml
Labels: skip-changelog

#10111 Fix NPE in ConcurrentQueryProfile while computing the breakdown map for slices
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
  server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdownTests.java
Labels: bug, flaky-test, skip-changelog

#10114 Removing extra protobuf notice file
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/mapper/CorrelationVectorFieldMapperTests.java
  protobuf-java-NOTICE.txt
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: bug, Plugins, skip-changelog

#9825 Add search pipeline README
  modules/search-pipeline-common/README.md
Labels: skip-changelog

#10082 Fix concurrent search NPE with track_total_hits, size=0, and terminate_after
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/simple/ParameterizedSimpleSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
  server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
Labels: enhancement, backport 2.x, Search, Search:Performance

#10135 Downgrade write lock to read lock before translog upload to remote store
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/listener/TranslogTransferListener.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: enhancement, Storage:Durability, backport 2.x, skip-changelog, v2.11.0

#10170 [2.x] Added bwc version 1.3.14
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#10159 [Backport] [2.x] Bump com.github.tomakehurst:wiremock-jre8-standalone from 2.35.0 to 3.0.1 in /buildSrc (#9752)
  CHANGELOG.md
  buildSrc/build.gradle
Labels: backport, dependencies

#10178 Reenable multipart repository within multipart ITs
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartIT.java
Labels: skip-changelog

#10131 Add support for encrypted async blob read
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/EncryptedBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/ReadContext.java
  server/src/test/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainerTests.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ListenerTestUtils.java
Labels: enhancement, distributed framework, backport 2.x

#9710 Add async segment file download support from remote store within OpenSearch core
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartIT.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/StoreTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: enhancement, distributed framework, skip-changelog, v2.11.0

#10036 Honor max segment size during only_expunge_deletes
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/OpenSearchTieredMergePolicy.java
  server/src/test/java/org/opensearch/index/OpenSearchTieredMergePolicyTests.java
Labels: enhancement, Indexing

#10187 [Backport 2.x] Downgrade write lock to read lock before translog upload to remote store
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/listener/TranslogTransferListener.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#10122 [Tracing Framework] Add support for SpanKind
  CHANGELOG.md
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanCreationContext.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanKind.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Tracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/TracingTelemetry.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/runnable/TraceableRunnable.java
  libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
  libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/TraceableRunnableTests.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelSpanKindConverter.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelTracingTelemetry.java
  plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/OTelSpanKindConverterTests.java
  plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/OTelTracingTelemetryTests.java
  server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
  server/src/main/java/org/opensearch/telemetry/tracing/WrappedTracer.java
  server/src/test/java/org/opensearch/telemetry/tracing/TracerFactoryTests.java
  server/src/test/java/org/opensearch/telemetry/tracing/WrappedTracerTests.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockSpan.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingContextPropagator.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingTelemetry.java
Labels: enhancement, v3.0.0, v2.11.0

#10198 Script Score Query Builder Visit Method
  server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/ScriptScoreQueryBuilderTests.java
Labels: skip-changelog

#10189 Add capability to restrict async durability mode for remote indexes
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: enhancement, Storage:Durability, v2.11.0

#10182 Enhance debug, trace & info logs for remote store flows
  libs/core/src/main/java/org/opensearch/core/index/Index.java
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#10197 Add workflow to add stalled label and message
  .github/workflows/stalled.yml
Labels: skip-changelog

#10220 [Feature] Support hashtag in token filter type_table rules parser
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/MappingCharFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/BaseWordDelimiterTokenFilterFactoryTestCase.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/MappingCharFilterFactoryTests.java
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/40_token_filters.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/50_char_filters.yml
  server/src/main/java/org/opensearch/index/analysis/Analysis.java
Labels: bug, skip-changelog, Search, Search:Query Capabilities

#10252 Update recovery target access time during segment sync for remote index
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
Labels: enhancement, Storage:Durability, backport 2.x, skip-changelog, v2.11.0

#8716 Indexing: add Doc status counter
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/rest/RestStatus.java
  rest-api-spec/src/main/resources/rest-api-spec/test/nodes.stats/11_indices_metrics.yml
  server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
  server/src/main/java/org/opensearch/action/update/TransportUpdateAction.java
  server/src/main/java/org/opensearch/index/shard/IndexingStats.java
  server/src/main/java/org/opensearch/index/shard/InternalIndexingStats.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTookTests.java
  server/src/test/java/org/opensearch/core/RestStatusTests.java
  server/src/test/java/org/opensearch/index/shard/IndexingStatsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, Clients & Libraries, distributed framework

#10192 Refactor async blob read to avoid blocking calls, support non multipa…
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
Labels: backport 2.x, skip-changelog

#10280 [Search latency - Coordinator] Changing version check to 2.11
  rest-api-spec/src/main/resources/rest-api-spec/test/nodes.stats/11_indices_metrics.yml
  server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
  server/src/main/java/org/opensearch/index/shard/IndexingStats.java
Labels: skip-changelog
