Repository opensearch-project/OpenSearch, pull requests merged in 2023-02, with the labels that each got.

#6041 [Weighted Routing] Support for fail open stats
  server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/cluster/routing/FailAwareWeightedRouting.java
  server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingStats.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: skip-changelog

#6126 Fix weighted routing stats version
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
Labels: skip-changelog

#6128 Fix weighted routing stats version
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
Labels: skip-changelog

#6003 [Extensions] Add support for minimum compatible version for extensions with OpenSearch
  CHANGELOG.md
  server/src/main/java/org/opensearch/extensions/DiscoveryExtensionNode.java
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/main/java/org/opensearch/extensions/ExtensionsSettings.java
  server/src/test/java/org/opensearch/extensions/DiscoveryExtensionNodeTests.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java
  server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java
  server/src/test/resources/config/extensions.yml
Labels: enhancement, backport 2.x, extensions

#6134 Add release notes for 1.3.8
  release-notes/opensearch.release-notes-1.3.8.md
Labels: backport 1.x, backport 1.3, skip-changelog

#6131 Fix incorrect exception message for ValuesSourceConfig
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSourceConfig.java
Labels: backport 2.x, skip-changelog

#6129 Bumps Jackson from 2.14.1 to 2.14.2
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.14.1.jar.sha1
  client/sniffer/licenses/jackson-core-2.14.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.2.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.1.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.2.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.1.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.1.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.2.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.1.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.2.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.1.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.2.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.1.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.2.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.1.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.1.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.2.jar.sha1
Labels: dependencies, v3.0.0, v2.6.0

#5963 Fix flaky test IndexStatsIT.testFilterCacheStats.
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
Labels: backport 2.x, skip-changelog

#5746 [Segment Replication] For replica recovery, force segment replication sync from peer recovery source
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#6144 [Backport] [2.5] Bumps Netty from 4.1.86.Final to 4.1.87.Final (#6130)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.87.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.86.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.87.Final.jar.sha1
Labels: dependencies

#6145 [Backport] [1.x] Bumps Netty from 4.1.86.Final to 4.1.87.Final (#6130)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.87.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.86.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.87.Final.jar.sha1
Labels: dependencies

#6149 [Segment Replication] For replica recovery, force segment replication sync from peer recovery source
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#6038 [Backport 2.x] Add method to Engine to fetch max seq no of last refresh
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: skip-changelog

#6146 [Backport] [1.3] Bumps Netty from 4.1.86.Final to 4.1.87.Final (#6130)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.87.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.87.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.86.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.87.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.86.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.87.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.86.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.87.Final.jar.sha1
Labels: dependencies

#6157 [Backport 2.x] Backport workflow to autocut issue on push failure.
  .github/ISSUE_TEMPLATE/failed_check.md
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#6017 [Segment Replication] Introduce primary weight factor for primary shards distribution
  libs/common/src/main/java/org/opensearch/common/collect/Triplet.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsBalancer.java
  server/src/main/java/org/opensearch/common/TriConsumer.java
  server/src/main/java/org/opensearch/common/settings/AbstractScopedSettings.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/search/aggregations/support/MultiTermsValuesSourceConfig.java
  server/src/main/java/org/opensearch/search/aggregations/support/MultiValuesSourceFieldConfig.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/SumAggregatorTests.java
Labels: skip-changelog

#6160 Improve autocut issue content on push gradle check failure.
  .github/ISSUE_TEMPLATE/failed_check.md
  .github/workflows/gradle-check.yml
Labels: backport 2.x, skip-changelog

#6137 [Extensions] Adds supports to read extension dependencies
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/main/java/org/opensearch/extensions/ExtensionsSettings.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
Labels: backport 2.x, extensions, skip-changelog

#6086 Purge remote translog basis the latest metadata for remote-backed indexes
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/listener/FileTransferListener.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/FileTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: durability, skip-changelog, v2.6.0

#6067 [Remote Store] Get SeqNo from Segment Info and integ tests for restore flow
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/IndexMetadataUpdater.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#6120 [opensearch-project/geospatial#212] Fixing the IT for GeoTilesAggrega…
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoHashGridIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoTileGridIT.java
Labels: Aggregations, flaky-test, Geospatial, skip-changelog

#6082 Initialize feature flags before extensions manager
  server/src/internalClusterTest/java/org/opensearch/extensions/ExtensionsManagerIT.java
  server/src/main/java/org/opensearch/node/Node.java
Labels: backport 2.x, extensions, skip-changelog

#6174 Add version 1.3.9
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#6176 Add version 1.3.9 (#6174)
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#6177 Change commit message and PR title to imperative mood
  .github/workflows/version.yml
Labels: backport 2.x, skip-changelog

#6184 Update badge version post release
  README.md
Labels: skip-changelog

#6186 [Backport 1.3] Backporting auto release workflow to 1.3
  .github/workflows/auto-release.yml
Labels: skip-changelog

#6182 Backport version.yml to 2.x
  .github/workflows/version.yml
Labels: skip-changelog

#6185 [Backport 1.x] Backporting auto release workflow to 1.x
  .github/workflows/auto-release.yml
Labels: skip-changelog

#6170 [Backport 2.x] Purge remote translog basis the latest metadata for remote-backed indexes
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/listener/FileTransferListener.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/FileTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#6202 [Backport 1.x] Sync CODEOWNERS from main to 1.x
  .github/CODEOWNERS
Labels: skip-changelog

#6205 Use SafeConstructor() instead of Constructor()
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
Labels: backport 2.x, skip-changelog

#6216 Changing SearchBP version to 2_6_0
  server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
  server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java
  server/src/main/java/org/opensearch/search/backpressure/settings/SearchTaskSettings.java
  server/src/main/java/org/opensearch/search/backpressure/stats/SearchBackpressureStats.java
  server/src/test/java/org/opensearch/search/backpressure/SearchBackpressureServiceTests.java
  server/src/test/java/org/opensearch/tasks/TaskCancellationTests.java
Labels: skip-changelog

#5950 power changes for building with and without jdk
  distribution/archives/build.gradle
  settings.gradle
Labels: skip-changelog

#6230 Fix sort order in getMaxSeqNoFromSegmentInfos and mute testRemoteTranslogRestore
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: skip-changelog

#6218 [Refactor] Requests to use MediaType instead of XContentType
  client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/CreateIndexRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/PutIndexTemplateRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/PutMappingRequest.java
  client/rest-high-level/src/test/java/org/opensearch/client/indices/PutMappingRequestTests.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/MediaType.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentBuilder.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentFactory.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentGenerator.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/cbor/CborXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContentGenerator.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/smile/SmileXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
  server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
  server/src/main/java/org/opensearch/action/ingest/PutPipelineRequest.java
  server/src/main/java/org/opensearch/common/settings/Settings.java
  server/src/main/java/org/opensearch/common/xcontent/XContentHelper.java
  server/src/main/java/org/opensearch/index/reindex/ReindexRequest.java
  server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
  server/src/test/java/org/opensearch/action/search/SearchPhaseExecutionExceptionTests.java
  server/src/test/java/org/opensearch/common/xcontent/BaseXContentTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: enhancement, skip-changelog, v2.6.0

#6234 [Backport] [2.x] power changes for building with and without jdk
  distribution/archives/build.gradle
  settings.gradle
Labels: skip-changelog

#6235 [Backport] [1.x] power changes for building with and without jdk
  distribution/archives/build.gradle
  settings.gradle
Labels: skip-changelog

#6246 Move ppec6le changelog entry after backport
  CHANGELOG.md
Labels: skip-changelog

#6256 [Segment Replication] Mute Flaky Test and add segment_replication.json as experimental
  rest-api-spec/src/main/resources/rest-api-spec/api/cat.segment_replication.json
  server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java
Labels: skip-changelog

#6109 Use separate threadpool in remote deletion for remote-backed indexes
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: durability, skip-changelog, Performance, v2.6.0

#6252 [Remote Store] Fix flaky test RemoteStoreIT.testRemoteSegmentStoreRestore
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
  server/src/test/java/org/opensearch/common/lucene/LuceneTests.java
Labels: skip-changelog

#6262 Remove timestamp from translog metadata filename for remote-backed indexes
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: durability, skip-changelog, v2.6.0

#6241 [Backport] [1.3] power changes for building with and without jdk
  distribution/archives/build.gradle
  settings.gradle
Labels: skip-changelog

#6250 [Segment Replication] Add changelog entry and fix allocation test
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
Labels: backport 2.x

#6280 [Segment Replication] Fix flaky testSnapshotOnSegRep_RestoreOnSegRepDuringIngestion test
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
Labels: backport 2.x, skip-changelog

#6282 Fix flaky segrep test testPrimaryStopped_ReplicaPromoted
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: skip-changelog

#6242 [#6187, #6222] Fixing the GeoShapes GeoHash and GeoTile Aggregations Integration tests to make them more robust.
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoHashGridIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoTileGridIT.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/cells/GeoShapeCellValues.java
Labels: Aggregations, Geospatial, backport 2.x, skip-changelog

#5641 File System Caching for remote store
  server/src/main/java/org/opensearch/ExceptionsHelper.java
  server/src/main/java/org/opensearch/common/cache/Cache.java
  server/src/main/java/org/opensearch/common/cache/RemovalNotification.java
  server/src/main/java/org/opensearch/common/cache/RemovalReason.java
  server/src/main/java/org/opensearch/common/cache/Weigher.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/CachedIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/package-info.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/CacheUsage.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/Linked.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LinkedDeque.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/RefCountedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/package-info.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/CacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/DefaultStatsCounter.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/StatsCounter.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/package-info.java
  server/src/main/java/org/opensearch/indices/AbstractIndexShardCacheEntity.java
  server/src/main/java/org/opensearch/indices/fielddata/cache/IndicesFieldDataCache.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/common/cache/CacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/PathTestUtils.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/cache/RefCountedCacheTests.java
Labels: backport 2.x, skip-changelog

#6290 [Backport 2.x] Implement file system caching for searchable snapshots (#5641)
  server/src/main/java/org/opensearch/ExceptionsHelper.java
  server/src/main/java/org/opensearch/common/cache/Cache.java
  server/src/main/java/org/opensearch/common/cache/RemovalNotification.java
  server/src/main/java/org/opensearch/common/cache/RemovalReason.java
  server/src/main/java/org/opensearch/common/cache/Weigher.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/CachedIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/package-info.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/CacheUsage.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/Linked.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LinkedDeque.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/RefCountedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/package-info.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/CacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/DefaultStatsCounter.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/StatsCounter.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/package-info.java
  server/src/main/java/org/opensearch/indices/AbstractIndexShardCacheEntity.java
  server/src/main/java/org/opensearch/indices/fielddata/cache/IndicesFieldDataCache.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/common/cache/CacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/PathTestUtils.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/cache/RefCountedCacheTests.java
Labels: skip-changelog

#6292 Mute integ test RemoteStoreIT.testRemoteStoreRestoreFromRemoteSegmentStore
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
Labels: skip-changelog

#6238 Purge stale translog metadata files for remote-backed indexes
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: durability, skip-changelog, v2.6.0

#6314 Recover all translogs during relocation handoff for remote-backed indexes
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: durability, skip-changelog, v2.6.0

#6288 Backport/backport 6280 to 2.x
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
Labels: skip-changelog

#6320 Added untriaged issue workflow.
  .github/workflows/add-untriaged.yml
Labels: skip-changelog

#6318 [Backport 2.x] Recover all translogs during relocation handoff for remote-backed indexes
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: skip-changelog

#6337 Add support to Gradle run task to spawn OpenSearch instances in debug mode
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/RunTask.java
Labels: Build Libraries & Interfaces, skip-changelog

#6344 [Backport] [2.x] Update Gradle to 8.0 (#5666)
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/StandaloneRestIntegTestTask.java
  buildSrc/src/test/java/org/opensearch/gradle/JdkDownloadPluginTests.java
  buildSrc/src/test/java/org/opensearch/gradle/precommit/DependencyLicensesTaskTests.java
  buildSrc/src/test/java/org/opensearch/gradle/precommit/UpdateShasTaskTests.java
  buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle
  buildSrc/version.properties
  distribution/packages/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  libs/x-content/licenses/snakeyaml-1.32.jar.sha1
  libs/x-content/licenses/snakeyaml-1.33.jar.sha1
  modules/lang-painless/build.gradle
  plugins/examples/build.gradle
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/guava-23.0.jar.sha1
  plugins/ingest-attachment/licenses/guava-31.1-jre.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/avro-1.10.2.jar.sha1
  plugins/repository-hdfs/licenses/avro-1.11.1.jar.sha1
  plugins/repository-hdfs/licenses/gson-2.10.1.jar.sha1
  plugins/repository-hdfs/licenses/gson-2.10.jar.sha1
  plugins/repository-hdfs/licenses/protobuf-java-3.21.12.jar.sha1
  plugins/repository-hdfs/licenses/protobuf-java-3.21.9.jar.sha1
  qa/wildfly/build.gradle
  test/fixtures/hdfs-fixture/build.gradle
  test/framework/build.gradle
Labels: skip-changelog

#6345 [Searchable Snapshots] Remove virtual file and fix duplicate clone
  server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandVirtualFileSnapshotIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
Labels: backport 2.x, skip-changelog

#6352 Segment Replication - Recover all translog ops when flipping to able engine
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: skip-changelog

#6351 [Searchable Snapshot] Use java.lang.ref.Cleaner to close cloned IndexInputs
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
  server/src/test/java/org/opensearch/index/store/remote/file/CleanerDaemonThreadLeakFilter.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockIndexInputLifecycleTests.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
Labels: backport 2.x, skip-changelog, v2.6.0

#6361 Update Gradle to 8.0.1
  gradle/wrapper/gradle-wrapper.properties
Labels: Build Libraries & Interfaces, skip-changelog

#6371 Segment Replication - Recover all translog ops when flipping to write…
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: skip-changelog

#6370 [Segment Replication] Wait for segment replication to be completed and marked done before assertion
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
Labels: backport 2.x, skip-changelog

#6368 [Remote Translog] Fix flaky test in BufferedAsyncIOProcessorTests
  server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
Labels: durability, backport 2.x, skip-changelog, v2.6.0

#6373 [Segment Replication] Wait for segment replication to be completed an…
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
Labels: skip-changelog

#6355 Refactor remote store integ tests to add scenario specific tests
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
Labels: skip-changelog

#6375 [Remote Store] Create empty lucene index during restore if remote segment store is empty
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
Labels: skip-changelog

#6367 [Searchable Snapshots] Correctly clone IndexInputs to avoid race
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
Labels: backport 2.x, skip-changelog

#6366 Skip performOnPrimary step when executing PublishCheckpoint.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
Labels: skip-changelog

#6327 Fix inconsistent cluster state and ensure weigh away exception check only for data nodes
  server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
  server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingUtils.java
Labels: skip-changelog

#5917 [Remote Store] Add header(codec) and footer(checksum) to remote store segment metadata
  server/src/main/java/org/opensearch/common/io/IndexIOStreamHandler.java
  server/src/main/java/org/opensearch/common/io/VersionedCodecStreamWrapper.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandler.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/package-info.java
  server/src/test/java/org/opensearch/common/io/VersionedCodecStreamWrapperTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
Labels: skip-changelog

#6400 [Remote Translog] Allow only one remote generation deletion
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: durability, backport 2.x, skip-changelog, v2.6.0

#6396 [Refactor] Remove PathTestUtils
  server/src/test/java/org/opensearch/index/store/remote/PathTestUtils.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
Labels: backport 2.x, skip-changelog

#6359 [Backport 2.x] Handles the status code for . properties
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
Labels: skip-changelog, v2.6.0

#6394 Add workflow to publish maven snapshots
  .github/workflows/publish-maven-snapshots.yml
Labels: skip-changelog

#6364 [Extensions] Create writeable implementations for parser
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/common/settings/WriteableSetting.java
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
Labels: skip-changelog

#6423 [Backport] [2.x] Opensearch repository-s3 plugin cannot read ServiceAccount token (#6390)
  CHANGELOG.md
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/AwsS3ServiceImplTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/ConfigPathSupport.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ServiceTests.java
Labels: v2.6.0

#6268 [Segment Replication] Fix flaky tests testSegmentReplicationStatsResponse() and testSegmentReplicationStatsWithTimeout()
  server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
  server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java
  server/src/test/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationActionTests.java
Labels: skip-changelog

#6419 [Fix] Fix last runtime millisec reset when applying index create block
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java
Labels: skip-changelog

#6426 [Backport 2.x] [Segment Replication] Backport of #6268
  server/src/internalClusterTest/java/org/opensearch/action/admin/ClientTimeoutIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
  server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java
  server/src/test/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationActionTests.java
Labels: skip-changelog

#6428 Bumping 2.x to 2.7.0
  .ci/bwcVersions
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#6430 Adding 2.7.0 to BWC versions
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#6433 [Backport 2.x] [Refactor] Requests to use MediaType instead of XContentType (#6218)
  client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/CreateIndexRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/PutIndexTemplateRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/PutMappingRequest.java
  client/rest-high-level/src/test/java/org/opensearch/client/indices/PutMappingRequestTests.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/MediaType.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentBuilder.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentFactory.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentGenerator.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/cbor/CborXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContentGenerator.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/smile/SmileXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
  server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
  server/src/main/java/org/opensearch/action/ingest/PutPipelineRequest.java
  server/src/main/java/org/opensearch/common/settings/Settings.java
  server/src/main/java/org/opensearch/common/xcontent/XContentHelper.java
  server/src/main/java/org/opensearch/index/reindex/ReindexRequest.java
  server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
  server/src/test/java/org/opensearch/action/search/SearchPhaseExecutionExceptionTests.java
  server/src/test/java/org/opensearch/common/xcontent/BaseXContentTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: skip-changelog, v2.7.0

#6439 [Segment Replication] Revert primary allocation
  CHANGELOG.md
  libs/common/src/main/java/org/opensearch/common/collect/Triplet.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsBalancer.java
  server/src/main/java/org/opensearch/common/TriConsumer.java
  server/src/main/java/org/opensearch/common/settings/AbstractScopedSettings.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/search/aggregations/support/MultiTermsValuesSourceConfig.java
  server/src/main/java/org/opensearch/search/aggregations/support/MultiValuesSourceFieldConfig.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/SumAggregatorTests.java
Labels: skip-changelog

#6440 [Segment Replication] Revert backport/backport 6017 to 2.x
  CHANGELOG.md
  libs/common/src/main/java/org/opensearch/common/collect/Triplet.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsBalancer.java
  server/src/main/java/org/opensearch/common/TriConsumer.java
  server/src/main/java/org/opensearch/common/settings/AbstractScopedSettings.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/search/aggregations/support/MultiTermsValuesSourceConfig.java
  server/src/main/java/org/opensearch/search/aggregations/support/MultiValuesSourceFieldConfig.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/SumAggregatorTests.java
Labels: skip-changelog, backport 2.6

#6397 [Backport 2.x] Skip performOnPrimary step when executing PublishCheckpoint. (#6366)
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
Labels: skip-changelog

#6455 Fix a bug in Search Backpressure
  server/src/main/java/org/opensearch/search/backpressure/trackers/HeapUsageTracker.java
Labels: skip-changelog

#6463 Adding unit test for test isHeapUsageDominatedBySearch
  server/src/test/java/org/opensearch/search/backpressure/trackers/HeapUsageTrackerTests.java
Labels: backport 2.x, skip-changelog, backport 2.6

#6469 Fix flaky test testNewlyAddedReplicaIsUpdated
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
Labels: backport 2.x, skip-changelog

#6333 Include file cache stats in node stats api response
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheStats.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheStatsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: backport 2.x, skip-changelog

#6467 Fix potential deadlock in ConcurrentInvocationLinearizer
  server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/utils/ConcurrentInvocationLinearizer.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/ConcurrentInvocationLinearizerTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
Labels: backport 2.x, skip-changelog

#6477 Use InputStream#transferTo instead of readAllBytes
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
Labels: backport 2.x, skip-changelog

#6350 Add cache reservation logic
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/SettingsModule.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/ShardPath.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
  server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
  server/src/main/java/org/opensearch/monitor/fs/FsService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
  server/src/test/java/org/opensearch/index/shard/ShardPathTests.java
  server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/NodeRoles.java
Labels: backport 2.x, skip-changelog

#6485 [Backport 2.x] Add file cache stats, reservation logic
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/SettingsModule.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/ShardPath.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheStats.java
  server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
  server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
  server/src/main/java/org/opensearch/monitor/fs/FsService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
  server/src/test/java/org/opensearch/index/shard/ShardPathTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheStatsTests.java
  server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/NodeRoles.java
Labels: skip-changelog

#6446 [Extensions] Add catch block to prevent unintended crash when no extensions are present
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
Labels: backport 2.x, skip-changelog

#6495 Update dependabot changelog helper to v3
  .github/workflows/dependabot_pr.yml
Labels: backport 2.x, skip-changelog

#6473 Add event listener to prune file cache on index deletion
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
Labels: skip-changelog

#6498 Correct link to OSI blog in README
  README.md
Labels: documentation, backport 1.x, backport 2.x, backport 1.3, skip-changelog

#6506 Fix file cache data path computation
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/index/shard/ShardPath.java
  server/src/test/java/org/opensearch/index/shard/ShardPathTests.java
Labels: backport 2.x, skip-changelog

#6503 [Backport 2.x] Bump org.apache.logging.log4j:log4j-core from 2.19.0 to 2.20.0 in /buildSrc/src/testKit/thirdPartyAudit/sample_jars
  CHANGELOG.md
  buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle
Labels: dependencies, dependabot

#6504 [Backport 2.x] Bump com.azure:azure-storage-common from 12.19.3 to 12.20.0 in /plugins/repository-azure
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-storage-common-12.19.3.jar.sha1
  plugins/repository-azure/licenses/azure-storage-common-12.20.0.jar.sha1
Labels: dependencies, dependabot
