Repository opensearch-project/OpenSearch, pull requests merged in 2023-11, with the labels that each got.

#11035 Add Java 11/17/21 matrix for precommit and assemble checks
  .github/workflows/assemble.yml
  .github/workflows/precommit.yml
Labels: skip-changelog

#10946 Fix flaky tests 'testDeleteAllAndListAllPits' and 'testDeleteWhileSearch'
  client/rest-high-level/src/test/java/org/opensearch/client/PitIT.java
  server/src/internalClusterTest/java/org/opensearch/search/pit/DeletePitMultiNodeIT.java
Labels: skip-changelog

#11069 Adding slf4j license header to LoggerMessageFormat.java
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/common/logging/LoggerMessageFormat.java
Labels: bug

#11072 Revert "Add cluster setting cluster.restrict.index.replication_type t…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: bug

#11043 [Segment Replication] Clean up SegmentReplicationTargetService only hold the state of last completed replications
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
Labels: backport 2.x, skip-changelog

#11087 Disable concurrent aggs for Diversified Sampler and Sampler aggs
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/SamplerIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/sampler/DiversifiedAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/sampler/SamplerAggregatorFactory.java
Labels: bug, flaky-test

#11071 Fixing concurrent search tests with one slice
  server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java
  server/src/internalClusterTest/java/org/opensearch/search/pit/PitMultiNodeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/preference/SearchPreferenceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/QueryStringIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/ScriptScoreQueryIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java
Labels: skip-changelog

#10770 Fix flaky pit/scroll tests in SegmentReplicationIT
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: bug, backport 2.x, skip-changelog

#11050 [Backport 2.x] Mute flaky concurrent segment search tests pending fixes (#10437)
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fieldcaps/FieldCapabilitiesIT.java
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: skip-changelog

#11095 Adding version condition while adding geoshape doc values to the index, to ensure backward compatibility.
  CHANGELOG.md
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
  qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/30_geoshape.yml
  qa/rolling-upgrade/src/test/resources/rest-api-spec/test/old_cluster/30_geoshape.yml
  qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/30_geoshape.yml
  server/src/main/java/org/opensearch/index/mapper/GeoShapeFieldMapper.java
Labels: bug, Geospatial, backport 2.x, Indexing

#11111 Fix flaky test RemoteIndexShardtests.testRepicaCleansUpOldCommitsWhenReceivingNew
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#11073 [2.x] Revert "Add cluster setting cluster.restrict.index.replication_type t…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: bug

#11104 Fix flaky testMinScoreDisablesCountOptimization in query profile phase tests
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#11110 Unmute FieldCapabilitiesIT.testWithIndexFilter for concurrent search
  server/src/internalClusterTest/java/org/opensearch/search/fieldcaps/FieldCapabilitiesIT.java
Labels: skip-changelog

#11068 Fix SuggestSearch.testSkipDuplicates by forceing refresh when indexing its test documents
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/suggest/CompletionSuggestSearchIT.java
Labels: bug, >test-failure, flaky-test, backport 2.x

#11057 Flaky RemoteClustersIT: Add assert busy to avoid race condition
  qa/remote-clusters/src/test/java/org/opensearch/cluster/remote/test/RemoteClustersIT.java
  server/src/main/java/org/opensearch/transport/ProxyConnectionStrategy.java
  server/src/main/java/org/opensearch/transport/RemoteClusterService.java
Labels: skip-changelog

#10894 Deprecate CamelCase PathHierarchy tokenizer name
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisModulePlugin.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/PathHierarchyTokenizerFactoryTests.java
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/30_tokenizers.yml
Labels: Indexing & Search, v3.0.0

#11060 [Refactor] Use iterative approach to evaluate Regex.simpleMatch
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/regex/Regex.java
  server/src/test/java/org/opensearch/common/regex/RegexTests.java
Labels: v3.0.0, backport 2.x, v2.12.0

#11114 [Backport-2.x] Adding version condition while adding geoshape doc values to the index, to ensure backward compatibility.
  CHANGELOG.md
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
  qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/30_geoshape.yml
  qa/rolling-upgrade/src/test/resources/rest-api-spec/test/old_cluster/30_geoshape.yml
  qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/30_geoshape.yml
  server/src/main/java/org/opensearch/index/mapper/GeoShapeFieldMapper.java
Labels: bug, Geospatial, backport 2.11

#11134 Fix slice collectors to leaves association with post filter
  server/src/main/java/org/opensearch/common/lucene/search/FilteredCollector.java
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
Labels: bug, v3.0.0, skip-changelog, Search, v2.12.0

#11147 Manually backport #11060 (Simple regex normalization refactor)
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/regex/Regex.java
  server/src/test/java/org/opensearch/common/regex/RegexTests.java
Labels: bug, v2.12.0, backport 2.11

#11151 Make the gradle check comment more compact
  .github/workflows/gradle-check.yml
Labels: backport 2.x, skip-changelog

#11142 update index random function to fix the bogus document deletion
  server/src/internalClusterTest/java/org/opensearch/search/basic/TransportTwoNodesSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#11160 [Backport 2.x] Make the gradle check comment more compact
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#10528 Adding support for dynamically updating Leader/follower checker timeouts
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/FollowersChecker.java
  server/src/main/java/org/opensearch/cluster/coordination/LeaderChecker.java
  server/src/main/java/org/opensearch/transport/TransportChannel.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationCheckerSettingsTests.java
  server/src/test/java/org/opensearch/cluster/coordination/FollowersCheckerTests.java
  server/src/test/java/org/opensearch/cluster/coordination/LeaderCheckerTests.java
Labels: enhancement, good first issue, backport 2.x, Cluster Manager

#10985 [Remote Translog] Fix translog inconsistent generation assertion failure in ITs
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
Labels: bug, :test, flaky-test, skip-changelog

#10752 Mute CardinalityWithRequestBreakerIT pending fix
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityWithRequestBreakerIT.java
Labels: backport 2.x, skip-changelog

#11118 Add indexRandomForConcurrentSearch method to tests:
  server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/NaNSortingIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/NestedIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/RangeIT.java
Labels: skip-changelog

#11003 [Backport] [2.x] Update bundled JDK to JDK-21.0.1 (#10576)
  buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
  distribution/src/config/jvm.options
  distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/SystemJvmOptions.java
  libs/core/build.gradle
  server/build.gradle
  server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/StableClusterManagerDisruptionIT.java
  server/src/main/java/org/opensearch/common/util/concurrent/BaseFuture.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/MockSinglePrioritizingExecutor.java
  test/framework/src/test/java/org/opensearch/test/disruption/LongGCDisruptionTests.java
Labels: skip-changelog

#11184 Fixed flaky and failing test cases for concurrent search
  server/src/internalClusterTest/java/org/opensearch/search/fetch/FetchSubPhasePluginIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/RandomScoreFunctionIT.java
Labels: bug, backport 2.x, skip-changelog

#11181 Add indexRandomForConcurrentSearch for tests:
  server/src/internalClusterTest/java/org/opensearch/search/msearch/MultiSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java
  server/src/internalClusterTest/java/org/opensearch/search/preference/SearchPreferenceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java
  server/src/internalClusterTest/java/org/opensearch/search/scriptfilter/ScriptQuerySearchIT.java
Labels: skip-changelog

#11093 Fix tests for concurrent Search: TermsDocCountErrorIT
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsDocCountErrorIT.java
  test/framework/src/main/java/org/opensearch/test/ParameterizedOpenSearchIntegTestCase.java
Labels: backport 2.x, skip-changelog

#11214 Skipping half_float sort tests for 2.11.0 as well
  rest-api-spec/src/main/resources/rest-api-spec/test/search/260_sort_mixed.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
Labels: skip-changelog

#10934 Per request latency onPhaseEnd fix
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
Labels: backport 2.x

#10307 Passing IndicesService to ingest processor factory with processor params
  CHANGELOG.md
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/ingest/Processor.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: backport 2.x

#11023 Refactor common parts from the Rounding class into a separate 'round' package
  CHANGELOG.md
  benchmarks/src/main/java/org/opensearch/common/round/RoundableBenchmark.java
  libs/common/src/main/java/org/opensearch/common/round/BidirectionalLinearSearcher.java
  libs/common/src/main/java/org/opensearch/common/round/BinarySearcher.java
  libs/common/src/main/java/org/opensearch/common/round/Roundable.java
  libs/common/src/main/java/org/opensearch/common/round/RoundableFactory.java
  libs/common/src/main/java/org/opensearch/common/round/package-info.java
  libs/common/src/test/java/org/opensearch/common/round/RoundableTests.java
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/test/java/org/opensearch/common/RoundingTests.java
Labels: backport 2.x

#11159 Muting flaky tests in SegmentReplicationSuiteIT
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationSuiteIT.java
Labels: skip-changelog

#10569 Fix SegmentReplicationPressureService to not schedule async tasks when remote failures are disabled
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
Labels: bug, backport 2.x, skip-changelog

#10625 Treat Setting value with empty array string as empty array
  CHANGELOG.md
  server/build.gradle
  server/src/main/java/org/opensearch/common/settings/Settings.java
  server/src/test/java/org/opensearch/common/settings/SettingsTests.java
  server/src/test/java/org/opensearch/node/NodeRoleSettingsTests.java
  server/src/test/resources/org/opensearch/common/settings/loader/test-settings.yml
Labels: bug, >breaking, v3.0.0

#11223 [Backport 2.x] Refactor common parts from the Rounding class into a separate 'round' package (#11023)
  CHANGELOG.md
  benchmarks/src/main/java/org/opensearch/common/round/RoundableBenchmark.java
  libs/common/src/main/java/org/opensearch/common/round/BidirectionalLinearSearcher.java
  libs/common/src/main/java/org/opensearch/common/round/BinarySearcher.java
  libs/common/src/main/java/org/opensearch/common/round/Roundable.java
  libs/common/src/main/java/org/opensearch/common/round/RoundableFactory.java
  libs/common/src/main/java/org/opensearch/common/round/package-info.java
  libs/common/src/test/java/org/opensearch/common/round/RoundableTests.java
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/test/java/org/opensearch/common/RoundingTests.java
Labels: v2.12.0

#11207 Fixing the tests for concurrent search
  server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#11212 Fix tests for concurrent search with IndexRandomForConcurrentSearch f…
  server/src/internalClusterTest/java/org/opensearch/search/scroll/SearchScrollIT.java
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/internalClusterTest/java/org/opensearch/search/sort/GeoDistanceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/source/SourceFetchingIT.java
  server/src/internalClusterTest/java/org/opensearch/search/suggest/SuggestSearchIT.java
Labels: skip-changelog

#10584 Reduce amount of docs ingested for SegRep ITs
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: backport 2.x, skip-changelog

#11196 [Sort] Sending missing values in comparator instead sending null
  rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/DoubleValuesComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/FloatValuesComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/HalfFloatValuesComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/IntValuesComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/UnsignedLongValuesComparatorSource.java
Labels: skip-changelog

#11233 Fix SearchQueryIT to not depend on percentage
  server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#10650 Request level coordinator slow logs
  CHANGELOG.md
  distribution/docker/src/docker/config/log4j2.properties
  distribution/src/config/log4j2.properties
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/CanMatchPreFilterSearchPhase.java
  server/src/main/java/org/opensearch/action/search/SearchDfsQueryThenFetchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/SearchQueryThenFetchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
  server/src/main/java/org/opensearch/action/search/SearchRequestSlowLog.java
  server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/common/logging/SlowLogLevel.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexingSlowLog.java
  server/src/main/java/org/opensearch/index/SearchSlowLog.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/CanMatchPreFilterSearchPhaseTests.java
  server/src/test/java/org/opensearch/action/search/MockSearchPhaseContext.java
  server/src/test/java/org/opensearch/action/search/SearchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/SearchQueryThenFetchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestSlowLogTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestStatsTests.java
  server/src/test/java/org/opensearch/action/search/SearchTimeProviderTests.java
  server/src/test/java/org/opensearch/index/IndexingSlowLogTests.java
  server/src/test/java/org/opensearch/index/SearchSlowLogTests.java
  server/src/test/java/org/opensearch/index/SlowLogLevelTests.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, feature, Search, v2.11.0, v2.12.0

#11204 [Backport 2.x] Add indexRandomForConcurrentSearch for tests
  server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/NaNSortingIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/NestedIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/RangeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/FetchSubPhasePluginIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/InnerHitsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/MatchedQueriesIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/RandomScoreFunctionIT.java
  server/src/internalClusterTest/java/org/opensearch/search/msearch/MultiSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java
  server/src/internalClusterTest/java/org/opensearch/search/preference/SearchPreferenceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java
  server/src/internalClusterTest/java/org/opensearch/search/scriptfilter/ScriptQuerySearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/scroll/SearchScrollIT.java
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/internalClusterTest/java/org/opensearch/search/sort/GeoDistanceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/sort/SortFromPluginIT.java
  server/src/internalClusterTest/java/org/opensearch/search/source/MetadataFetchingIT.java
  server/src/internalClusterTest/java/org/opensearch/search/source/SourceFetchingIT.java
  server/src/internalClusterTest/java/org/opensearch/search/suggest/SuggestSearchIT.java
Labels: skip-changelog

#11242 [BWC and API enforcement] Reduce the visibility of some existing APIs
  server/src/main/java/org/opensearch/action/search/SearchPhaseContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
  server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
Labels: backport 2.x, skip-changelog

#11253 [Backport] [2.x] [BWC and API enforcement] Reduce the visibility of some existing APIs (#11242)
  server/src/main/java/org/opensearch/action/search/SearchPhaseContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
  server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
Labels: skip-changelog

#11088 Fix flaky test MoreExpressionIT.testSpecialValueVariable in concurrent search path
  modules/lang-expression/src/internalClusterTest/java/org/opensearch/script/expression/MoreExpressionIT.java
  modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionAggregationScript.java
  modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScriptEngine.java
  modules/lang-expression/src/main/java/org/opensearch/script/expression/PerThreadReplaceableConstDoubleValueSource.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#11259 Add indexRandomForConcurrentSearch to tests
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityWithRequestBreakerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/DecayFunctionScoreIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/FunctionScoreFieldValueIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/FunctionScoreIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/FunctionScorePluginIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/QueryRescorerIT.java
Labels: backport 2.x, skip-changelog

#11267 Fix maxScore check in reduce phase when some scores are NaN
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
Labels: bug, flaky-test, skip-changelog

#10873 [BUG] The thread context is not properly cleared and messes up the traces
  CHANGELOG.md
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultSpanScope.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Tracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/TracingContextPropagator.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/transport/TransportTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/transport/package-info.java
  libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerEnabledSanityIT.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelTracingContextPropagator.java
  plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/OTelTracingContextPropagatorTests.java
  server/src/main/java/org/opensearch/http/AbstractHttpServerTransport.java
  server/src/main/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorage.java
  server/src/main/java/org/opensearch/telemetry/tracing/TracerFactory.java
  server/src/main/java/org/opensearch/telemetry/tracing/WrappedTracer.java
  server/src/main/java/org/opensearch/transport/InboundHandler.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorageTests.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingContextPropagator.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/TelemetryValidators.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/NumberOfTraceIDsEqualToRequests.java
Labels: bug, v3.0.0, v2.12.0

#10980 fix-flaky: MultiCodecReindexTests
  modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java
  modules/reindex/src/test/java/org/opensearch/index/reindex/MultiCodecReindexTests.java
Labels: bug, flaky-test, skip-changelog, Indexing

#11249 Handle canMatchSearchAfter for frozen context scenario
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/240_date_nanos.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
Labels: bug, v3.0.0, v2.12.0

#11282 [Backport 2.x] fix-flaky: MultiCodecReindexTests
  modules/reindex/src/internalClusterTest/java/org/opensearch/index/codec/MultiCodecReindexIT.java
  modules/reindex/src/test/java/org/opensearch/index/reindex/MultiCodecReindexTests.java
Labels: skip-changelog

#11250 [Backport 2.x] [Sort] Sending missing values in comparator instead sending null
  rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/DoubleValuesComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/FloatValuesComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/HalfFloatValuesComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/IntValuesComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/UnsignedLongValuesComparatorSource.java
Labels: skip-changelog

#11234 [Backport 2.x] Fix SegmentReplicationPressureService to not schedule async tasks when remote failures are disabled
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
Labels: skip-changelog

#11284 Add 2.11.1 release notes
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.11.1.md
Labels: backport 2.x

#10040 Add template snippets support for field and target_field in KV ingest processor
  CHANGELOG.md
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonModulePlugin.java
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/KeyValueProcessor.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/KeyValueProcessorFactoryTests.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/KeyValueProcessorTests.java
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/150_kv.yml
Labels: v3.0.0, Indexing, API

#11303 [Backport] [1.x] Bump netty from 4.1.100.Final to 4.1.101.Final (#11294)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.97.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.101.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.97.Final.jar.sha1
Labels: backport

#11304 [Backport] [1.3] Bump netty from 4.1.100.Final to 4.1.101.Final (#11294)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.101.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.101.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.101.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.100.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.101.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.101.Final.jar.sha1
Labels: backport

#11298 Mute testNestedSort for concurrent segment search case
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
Labels: skip-changelog

#10543 Delegating CachingWeightWrapper#count to internal weight object
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/IndicesQueryCache.java
  server/src/test/java/org/opensearch/indices/IndicesQueryCacheTests.java
  server/src/test/java/org/opensearch/indices/IndicesServiceCloseTests.java
Labels: bug, good first issue, backport 2.x, Search

#11309 [Backport 2.x] Fix flaky test MoreExpressionIT.testSpecialValueVariable in concurrent search path
  modules/lang-expression/src/internalClusterTest/java/org/opensearch/script/expression/MoreExpressionIT.java
  modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionAggregationScript.java
  modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScriptEngine.java
  modules/lang-expression/src/main/java/org/opensearch/script/expression/PerThreadReplaceableConstDoubleValueSource.java
Labels: skip-changelog

#11153 Fix for stuck update action in a bulk with retry_on_conflict property
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/bulk/BulkPrimaryExecutionContext.java
  server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
Labels: Indexing

#11311 [Backport 2.x] Disallow removing some metadata fields by remove ingest processor
  CHANGELOG.md
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/RemoveProcessor.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveProcessorTests.java
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/290_remove_processor.yml
Labels: bug, v2.12.0

#10912 Stream read pool and default s3 timeouts tuning
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/StatsMetricPublisher.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
Labels: skip-changelog, v2.12.0

#11305 Bump OpenTelemetry from 1.31.0 to 1.32.0 and OpenTelemetry Semconv from 1.21.0-alpha to 1.23.1-alpha
  CHANGELOG.md
  buildSrc/version.properties
  plugins/telemetry-otel/build.gradle
  plugins/telemetry-otel/licenses/opentelemetry-api-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-extension-incubator-1.31.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-extension-incubator-1.32.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.21.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.23.1-alpha.jar.sha1
Labels: dependencies

#11321 Adding missing encryption context in decrypt call in KMS crypto plugin
  .github/dependabot.yml
  plugins/crypto-kms/src/main/java/org/opensearch/crypto/kms/KmsMasterKeyProvider.java
Labels: skip-changelog, v2.12.0

#11315 Properly encapsulate SearchRequestOperationsListener related APIs as package protected (internal)
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
  server/src/main/java/org/opensearch/action/search/SearchRequestSlowLog.java
  server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerSupport.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
Labels: skip-changelog, API

#11330 [Remote Store] Handoff refreshes, translog uploads during relocation from old to new primary
  server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/ReleasableRetryableRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/LocalTranslog.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
  server/src/test/java/org/opensearch/index/shard/ReleasableRetryableRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/TestTranslog.java
Labels: bug, Storage:Durability, skip-changelog, Storage:Remote, v2.12.0

#11361 [Backport 2.x] [Remote Store] Handoff refreshes, translog uploads during relocation from old to new primary (#11330)
  server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/ReleasableRetryableRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/LocalTranslog.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
  server/src/test/java/org/opensearch/index/shard/ReleasableRetryableRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/TestTranslog.java
Labels: skip-changelog

#11083 Improving the performance of date histogram aggregation (without any sub-aggregation)
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/10_histogram.yml
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/FilterRewriteHelper.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregatorTests.java
Labels: enhancement, Search:Aggregations, Performance, v2.12.0

#11350 Bump reactor-netty-core from 1.1.12 to 1.1.13
  CHANGELOG.md
  buildSrc/version.properties
  plugins/repository-azure/licenses/reactor-netty-core-1.1.12.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.13.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.12.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.13.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.12.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.13.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.12.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.13.jar.sha1
Labels: dependencies

#11317 Allow changing number of replicas of searchable snapshot index
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
Labels: backport 2.x

#11241 Adding lucene snapshot to the ci staging repository
  .github/workflows/lucene-snapshots.yml
Labels: backport 2.x, skip-changelog

#11377 Unmute nested sort related ITs
  server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#11340 [Remote Store] fail index template creation with refresh_interval less than cluster minimum
  server/src/internalClusterTest/java/org/opensearch/cluster/metadata/ClusterIndexRefreshIntervalIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/metadata/ClusterIndexRefreshIntervalWithNodeSettingsIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
Labels: bug, Storage:Durability, skip-changelog

#11369 Fix Shadow JAR dependency publication
  CHANGELOG.md
  modules/lang-painless/build.gradle
Labels: bug, backport 2.x, backport 2.11

#11392 Revert Rounding API visibility changes
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/FilterRewriteHelper.java
Labels: backport 2.x, skip-changelog

#11388 [Backport] [2.x] Bump com.gradle.enterprise from 3.14.1 to 3.15.1 (#11339)
  CHANGELOG.md
  settings.gradle
Labels: backport

#11380 Add log for unreferenced file cleanup
  server/src/main/java/org/opensearch/index/engine/Engine.java
Labels: skip-changelog

#11167 Fix remote shards balancer and remove unused variables
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AllocationDeciders.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/Decision.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsAllocateUnassignedTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
Labels: backport 2.x

#11397 Fix query profiler test basic with concurrent execution
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
Labels: bug, Severity-Major, backport 2.x, skip-changelog, v2.12.0

#11389 [Backport 2.x] Delegating CachingWeightWrapper#count to internal weight object (#10543)
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/IndicesQueryCache.java
  server/src/test/java/org/opensearch/indices/IndicesQueryCacheTests.java
  server/src/test/java/org/opensearch/indices/IndicesServiceCloseTests.java
Labels: bug, good first issue, Search
