Repository opensearch-project/OpenSearch, pull requests merged in 2023-04, with the labels that each got.

#6898 [Backport] [2.x] Upgrade forbiddenapis to 3.5.1 (#6840)
  buildSrc/build.gradle
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditPrecommitPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
  buildSrc/src/testKit/thirdPartyAudit/build.gradle
Labels: skip-changelog, distinguished-contributor

#6915 Fix testCacheFilesAreClosedAfterUse for Searchable Snapshots
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
Labels: backport 2.x, skip-changelog

#6920 Include all file cache access in privileged section
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
Labels: backport 2.x, skip-changelog

#6926 Fix sort in case of different numeric field types between indices
  server/src/main/java/org/opensearch/action/search/SearchPhaseController.java
  server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java
Labels: skip-changelog

#6930 Don't register destructiveDistroTest.docker twice
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
Labels: backport 2.x, skip-changelog

#6936 fix for updating version numbers for deprecation messages (SyncedFlus…
  client/rest-high-level/src/test/java/org/opensearch/client/documentation/IndicesClientDocumentationIT.java
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.flush/10_basic.yml
  server/src/main/java/org/opensearch/indices/flush/SyncedFlushService.java
Labels: skip-changelog

#6901 Fixing SortField comparison to use equals instead of reference equality
  rest-api-spec/src/main/resources/rest-api-spec/test/search/260_sort_mixed.yml
  server/src/main/java/org/opensearch/action/search/SearchPhaseController.java
Labels: skip-changelog, distinguished-contributor

#6959 Fix SHAs for lucene-core-9.6.0-snapshot-a3ae27f
  libs/core/licenses/lucene-core-9.5.0.jar.sha1
  libs/core/licenses/lucene-core-9.6.0-snapshot-a3ae27f.jar.sha1
Labels: skip-changelog

#6917 Avoid negative memory result in IndicesQueryCache stats calculation
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/IndicesQueryCache.java
  server/src/test/java/org/opensearch/indices/IndicesQueryCacheTests.java
Labels: backport 1.x, backport 2.x

#6894 [Backport to 2.x] Enhance search preference based routing for WRR (#6834)
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
  server/src/main/java/org/opensearch/cluster/routing/FailAwareWeightedRouting.java
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingUtils.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/routing/FailAwareWeightedRoutingTests.java
  server/src/test/java/org/opensearch/cluster/structure/RoutingIteratorTests.java
Labels: first-time-contributor

#6931 Validate checksum in footer separately for segment metadata files
  server/src/main/java/org/opensearch/common/io/VersionedCodecStreamWrapper.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
Labels: skip-changelog

#6825 [Remote Store] Add file details to recoveryState while downloading segments from remote store
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
Labels: skip-changelog, all-star-contributor

#6975 Fix assertion failure in updateGlobalCheckpointOnReplica() with remote translog
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: skip-changelog

#6974 [Backport] [2.6] fix for updating version numbers for deprecation messages (#4719) (#6848)
  modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/UserAgentProcessor.java
  modules/ingest-user-agent/src/yamlRestTest/resources/rest-api-spec/test/ingest-useragent/20_useragent_processor.yml
  plugins/mapper-annotated-text/src/internalClusterTest/java/org/opensearch/index/mapper/annotatedtext/AnnotatedTextFieldMapperTests.java
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/30_copy_settings.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/30_copy_settings.yml
  server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/TypeParsers.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestResizeHandler.java
  server/src/test/java/org/opensearch/index/mapper/BooleanFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: backport, skip-changelog

#6970 Use DirectoryFactory interface to create remote directory
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/IndexStorePlugin.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
Labels: backport 2.x, skip-changelog

#6979 [Segment Replication] Fix flaky testReplicaHasDiffFilesThanPrimary test
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: skip-changelog

#6968 Remove LinkedDeque and replace with LinkedHashMap
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/Linked.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LinkedDeque.java
Labels: skip-changelog

#6730 [Segment Replication] Compatibility check for differing lucene codec versions
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
  server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
  server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: backport 2.x, skip-changelog

#6591 Add circuit breaker support for file cache
  benchmarks/src/main/java/org/opensearch/benchmark/store/remote/filecache/FileCacheBenchmark.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/monitor/MonitorService.java
  server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
  server/src/main/java/org/opensearch/monitor/fs/FsService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
  server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
  server/src/test/java/org/opensearch/node/NodeTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: backport 2.x, skip-changelog

#6850 [Segment Replication] Add new background task to fail stale replica shards.
  server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: skip-changelog

#7011 [Backport 2.x] Add circuit breaker support for file cache (#6591)
  benchmarks/src/main/java/org/opensearch/benchmark/store/remote/filecache/FileCacheBenchmark.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/monitor/MonitorService.java
  server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
  server/src/main/java/org/opensearch/monitor/fs/FsService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
  server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
  server/src/test/java/org/opensearch/node/NodeTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: skip-changelog

#7004 [Backport] [2.x] Bump com.azure:azure-storage-blob from 12.20.0 to 12.21.1 in /plugins/repository-azure (#6942)
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-storage-blob-12.20.0.jar.sha1
  plugins/repository-azure/licenses/azure-storage-blob-12.21.1.jar.sha1
Labels: backport

#7013 [Segment Replication]Fix flaky test SegmentReplicationStatsIT.testSegmentReplicationStatsResponse
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
Labels: backport 2.x, skip-changelog

#7022 [Backport 2.x] [Segment Replication]Add background async task to fail stale replica shards.
  server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: skip-changelog

#6994 Bump version of protobuf-java to 3.22.2
  CHANGELOG.md
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/protobuf-java-3.21.7.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-3.22.2.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-util-3.20.0.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-util-3.22.2.jar.sha1
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport, dependencies, v2.7.0

#7024 [Backport 2.x] Bump version of protobuf-java to 3.22.2 (#6994)
  CHANGELOG.md
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/protobuf-java-3.21.7.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-3.22.2.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-util-3.20.0.jar.sha1
  plugins/repository-gcs/licenses/protobuf-java-util-3.22.2.jar.sha1
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport, dependencies, v2.7.0

#6956 feat: allow overwrite opensearch home
  CHANGELOG.md
  distribution/src/bin/opensearch-env
  distribution/src/bin/opensearch-env.bat
Labels: backport 1.x, backport 2.x

#6839 Fix GetSnapshots to not return non-existent snapshots with ignore_unavailable=true
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/get/TransportGetSnapshotsAction.java
Labels: first-time-contributor

#7035 Change port number for disconnected remote host to accomadate for Win…
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/90_remote.yml
Labels: :test, backport 1.x, backport 2.x, skip-changelog, backport 2.6

#7036 [Segment Replication] Fix SearchableSnapshotIT tests failing with segment replication enabled indices
  server/src/main/java/org/opensearch/indices/IndicesService.java
Labels: backport 2.x, skip-changelog

#7006 [Segment Replication] Introduce new SEGMENT_REPLICATION_EXPERIMENTAL feature flag.
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
Labels: backport 2.x

#6826 [Extensions] Added headers to extensions request
  server/src/main/java/org/opensearch/extensions/rest/ExtensionRestRequest.java
  server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
  server/src/test/java/org/opensearch/extensions/rest/ExtensionRestRequestTests.java
  server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java
Labels: backport 2.x, skip-changelog, CCI, first-time-contributor

#7072 Do not delete entire index cache on shard removal
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java
Labels: backport 2.x, skip-changelog

#7081 Extend the version range to run flat-object field REST Yaml test on 2.7.0
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/30_search.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml
Labels: :test, backport 2.x, skip-changelog, Search, v2.7.0

#7065 Removed duplicated 'nodeId' in cache path #7059
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
  server/src/test/java/org/opensearch/env/NodeRepurposeCommandTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
Labels: backport 2.x, skip-changelog

#7094 [Refactor] SegmentsStats#filesSizes from ImmutableOpenMap to java.util.Map
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/SegmentsStats.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: enhancement, skip-changelog, v2.7.0

#7102 Fix file cache active usage on restore
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
Labels: backport 2.x, skip-changelog

#7080 Resolve windows opensearch-env.bat having variable delayed expansion issues on OPENSEARCH_HOME assignment introduced in #6956
  distribution/src/bin/opensearch-env.bat
Labels: bug, windows, backport 1.x, backport 2.x, skip-changelog

#7108 Add autocut label for autocut issues
  .github/ISSUE_TEMPLATE/failed_check.md
Labels: backport 2.x, skip-changelog

#7105 Fix HTTP/2 Upgrade flow for requests with content (post/put/...)
  modules/transport-netty4/src/internalClusterTest/java/org/opensearch/http/netty4/Netty4Http2IT.java
  modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java
  modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpClient.java
Labels: bug, skip-changelog

#7053 [Segment Replication] Cancellation check before send files to prevent…
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
Labels: skip-changelog

#7062 [Segment Replication] Close writer on segment replication cancellation
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
Labels: skip-changelog

#6932 [Remote Store] Add support to create index with remote store by default
  distribution/src/config/opensearch.yml
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexTranslogDisabledIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/SettingsModule.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
Labels: skip-changelog

#7114 GlobalAggregation with profile option enabled returns incorrect result
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/GlobalIT.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationPhase.java
Labels: backport 2.x, v2.7.0

#7125 [Extensions] Increased visibility of BaseRestHandler’s `unrecognized` method using a new public `unrecognizedStrings` method
  CHANGELOG.md
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
Labels: backport 2.x

#7130 [Segment Replication] Cleanup and improvement on replica commit
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
Labels: skip-changelog

#7064 [Extensions] Handle Deprecated and Replaced Routes in Extension Rest Handlers
  server/src/main/java/org/opensearch/extensions/rest/RegisterRestActionsRequest.java
  server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/extensions/rest/RegisterRestActionsTests.java
  server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java
Labels: backport 2.x, skip-changelog

#7135 [SearchPipelines] Lower compatibility version to 2.7
  server/src/main/java/org/opensearch/OpenSearchException.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodeInfo.java
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
Labels: skip-changelog

#7129 Download block after adding cache entry
  benchmarks/src/main/java/org/opensearch/benchmark/store/remote/filecache/FileCacheBenchmark.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/CachedIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
Labels: backport 2.x, skip-changelog, v2.7.0

#7037 Fix: avoid ZSTD codec from overriding service codec factory.
  CHANGELOG.md
  sandbox/plugins/custom-codecs/build.gradle
  sandbox/plugins/custom-codecs/licenses/zstd-jni-1.5.4-1.jar.sha1
  sandbox/plugins/custom-codecs/licenses/zstd-jni-1.5.5-1.jar.sha1
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecPlugin.java
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecService.java
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecServiceFactory.java
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomStoredFieldsFormat.java
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/PerFieldMappingPostingFormatCodec.java
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCodec.java
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCompressionMode.java
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCodec.java
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCompressionMode.java
Labels: skip-changelog

#7117 Remove feature flag for searchable snapshots
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
  server/src/test/java/org/opensearch/node/NodeTests.java
Labels: backport 2.x, v2.7.0

#6999 Avoid Syncing Translog on Global Ckp Sync for Remote Translog
  server/src/main/java/org/opensearch/index/seqno/GlobalCheckpointSyncAction.java
  server/src/test/java/org/opensearch/index/seqno/GlobalCheckpointSyncActionTests.java
Labels: skip-changelog

#7141 Fix flaky integ tests - CreateRemoteIndexIT,CreateRemoteIndexTranslogDisabledIT,CreateRemoteIndexClusterDefaultDocRep
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexTranslogDisabledIT.java
Labels: skip-changelog

#7170 Update version guards for searchable snapshots
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
  server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
Labels: skip-changelog

#7169 Make file cache stats consistent with other APIs
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheStats.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheStatsTests.java
Labels: skip-changelog

#7185 Fix flaky integ remote store settings integ tests (#7141)
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexTranslogDisabledIT.java
Labels: skip-changelog

#7193 Change assertion to use value match instead of array match
  rest-api-spec/src/main/resources/rest-api-spec/test/search/260_sort_mixed.yml
Labels: skip-changelog

#7173 Unmuting TranslogTransferManagerTests for Windows
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#7183 [Segment Replication] Enable Segment Replication Backpressure setting by default.
  server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
Labels: backport 2.x, skip-changelog

#7056 [Segment Replication] Handle IndexShard.getLatestReplicationCheckpoint for closed indices
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
Labels: skip-changelog

#7166 [#7101] Fixing the GeoTileIT#testMultivaluedGeoPointsAggregation testcase
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoTileGridIT.java
Labels: :test, >test-failure, Geospatial, backport 2.x, skip-changelog

#7177 Remove mend config to reduce delay temporarily - reopen
  .whitesource
Labels: bug, Mend: configuration error, backport 1.x, backport 2.x, skip-changelog

#7191 [Segment Replication] Fix Assertion failure on primary mode.
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
Labels: backport 2.x, skip-changelog, backport 2.7

#7154 Adding more validation for fuzzy queries
  server/src/main/java/org/opensearch/common/unit/Fuzziness.java
  server/src/test/java/org/opensearch/common/unit/FuzzinessTests.java
Labels: skip-changelog

#7214 [Segment Replication] Prevent cancellation of ReplicationTracker's in-sync allocation ids
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
Labels: backport 2.x, skip-changelog, backport 2.7

#7232 Tweak log level to avoid spamming log
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
Labels: backport 2.x, skip-changelog, backport 2.7

#7238 Adding 2.8.0 to BWC versions
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#7239 Add release notes for v2.7.0
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.7.0.md
Labels: backport 2.x, backport 2.7

#6716 Add TopNSearchTasksLogger settings to Cluster Settings
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
  server/src/main/java/org/opensearch/tasks/TaskManager.java
  server/src/main/java/org/opensearch/tasks/consumer/TopNSearchTasksLogger.java
  server/src/test/java/org/opensearch/tasks/consumer/TopNSearchTasksLoggerTests.java
Labels: skip-changelog

#7241 Add TopNSearchTasksLogger settings to Cluster Settings (#6716)
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
  server/src/main/java/org/opensearch/tasks/TaskManager.java
  server/src/main/java/org/opensearch/tasks/consumer/TopNSearchTasksLogger.java
  server/src/test/java/org/opensearch/tasks/consumer/TopNSearchTasksLoggerTests.java
Labels: skip-changelog

#7247 Fix snapshotting searchable snapshot indexes
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
Labels: backport 2.x, skip-changelog, backport 2.7

#7251 [Backport 2.7] Fix snapshotting searchable snapshot indexes (#7247)
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
Labels: skip-changelog

#7250 [Backport 2.x] Fix snapshotting searchable snapshot indexes (#7247)
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
Labels: skip-changelog

#7242 Add TopNSearchTasksLogger settings to Cluster Settings (#6716)
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
  server/src/main/java/org/opensearch/tasks/TaskManager.java
  server/src/main/java/org/opensearch/tasks/consumer/TopNSearchTasksLogger.java
  server/src/test/java/org/opensearch/tasks/consumer/TopNSearchTasksLoggerTests.java
Labels: skip-changelog

#7231 Use lowercase letters for zstd, zstdnodict compression codecs.
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/CustomCodecPlugin.java
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/Lucene95CustomCodec.java
Labels: skip-changelog

#6748 Fix LocalTranslogTests.testWithRandomException test scenario
  server/src/test/java/org/opensearch/index/translog/LocalTranslogTests.java
Labels: skip-changelog

#7265 [Backport 2.x] Moving ExtensionsRequest to use Protobuf
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/protobuf-java-util-3.22.2.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/protobuf-java-3.22.2.jar.sha1
  plugins/repository-hdfs/licenses/protobuf-java-LICENSE.txt
  plugins/repository-hdfs/licenses/protobuf-java-NOTICE.txt
  plugins/transport-nio/build.gradle
  protobuf-java-NOTICE.txt
  server/build.gradle
  server/licenses/protobuf-java-3.22.2.jar.sha1
  server/licenses/protobuf-java-LICENSE.txt
  server/licenses/protobuf-java-NOTICE.txt
  server/src/main/java/org/opensearch/extensions/ExtensionRequest.java
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/main/proto/extensions/ExtensionRequestProto.proto
  server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
Labels: backport, extensions, v2.8.0

#7165 [Refactor] Metadata members from ImmutableOpenMap to j.u.Map
  client/rest-high-level/src/test/java/org/opensearch/client/indices/GetIndexResponseTests.java
  client/rest-high-level/src/test/java/org/opensearch/client/indices/GetMappingsResponseTests.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/CreateIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/get/GetIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterStateDiffIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/SimpleClusterStateIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/MetadataNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/operateAllIndices/DestructiveOperationsIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/delete/TransportDeleteDanglingIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/get/TransportGetIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/get/GetMappingsResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/get/TransportGetMappingsAction.java
  server/src/main/java/org/opensearch/action/admin/indices/template/get/TransportGetIndexTemplatesAction.java
  server/src/main/java/org/opensearch/cluster/ClusterChangedEvent.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/ClusterState.java
  server/src/main/java/org/opensearch/cluster/coordination/RemoveCustomsCommand.java
  server/src/main/java/org/opensearch/cluster/coordination/UnsafeBootstrapClusterManagerCommand.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/cluster/metadata/SystemIndexMetadataUpgradeService.java
  server/src/main/java/org/opensearch/cluster/metadata/TemplateUpgradeService.java
  server/src/main/java/org/opensearch/env/NodeRepurposeCommand.java
  server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java
  server/src/main/java/org/opensearch/gateway/DanglingIndicesState.java
  server/src/main/java/org/opensearch/gateway/Gateway.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/PersistedClusterStateService.java
  server/src/main/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommand.java
  server/src/main/java/org/opensearch/rest/action/cat/RestTemplatesAction.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotUtils.java
  server/src/test/java/org/opensearch/action/admin/cluster/reroute/ClusterRerouteResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/get/GetIndexResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/mapping/get/GetMappingsResponseTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
  server/src/test/java/org/opensearch/cluster/ClusterChangedEventTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/TemplateUpgradeServiceTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AddIncrementallyTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/ThrottlingAllocationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/EnableAllocationShortCircuitTests.java
  server/src/test/java/org/opensearch/gateway/DanglingIndicesStateTests.java
  server/src/test/java/org/opensearch/index/mapper/FieldFilterMapperPluginTests.java
  server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java
  server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotUtilsTests.java
Labels: enhancement, skip-changelog, v2.8.0

#7270 Update Gradle to 8.1.1
  gradle/wrapper/gradle-wrapper.properties
Labels: Build Libraries & Interfaces, skip-changelog

#7261 [Backport] [2.x] Bump com.google.protobuf:protobuf-java from 3.22.2 to 3.22.3 in /plugins/repository-hdfs (#7189)
  CHANGELOG.md
  buildSrc/version.properties
  server/licenses/protobuf-java-3.22.3.jar.sha1
Labels: backport

#7272 Bump com.google.protobuf:protobuf-java from 3.22.2 to 3.22.3
  buildSrc/version.properties
  server/licenses/protobuf-java-3.22.3.jar.sha1
Labels: dependencies, skip-changelog

#7274 [Segment Replication] Make SegmentReplicationPressureService a Singleton class and fix bug of rejected_requests reporting incorrect value
  server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
Labels: backport 2.x, skip-changelog, backport 2.7

#7279 [Segment Replication] - Remove redundant replica doc parsing on writes.
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/replication/RecoveryDuringReplicationTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#7292 Revert Enabling Segment Replication Backpressure setting by default
  server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
Labels: backport 2.x, skip-changelog, backport 2.7

#7297 Fix store type settings ordering for searchable snapshots
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
Labels: backport 2.x, skip-changelog, backport 2.7

#7286 Bump jackson from 2.14.2 to 2.15.0
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.14.2.jar.sha1
  client/sniffer/licenses/jackson-core-2.15.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.14.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.15.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.14.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.15.0.jar.sha1
  libs/core/licenses/jackson-core-2.14.2.jar.sha1
  libs/core/licenses/jackson-core-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.14.2.jar.sha1
  libs/x-content/licenses/jackson-core-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.14.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.14.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.14.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.15.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.14.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.15.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.14.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.15.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.14.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.15.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.14.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.14.2.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.14.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.14.2.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.14.2.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.14.2.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.15.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.14.2.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.15.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.14.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.15.0.jar.sha1
Labels: dependencies, backport 2.x

#7301 [Refactor] more ImmutableOpenMap to jdk Map in cluster package
  client/rest-high-level/src/test/java/org/opensearch/client/indices/GetIndexResponseTests.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/alias/ValidateIndicesAliasesRequestIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/get/GetIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/aliases/IndexAliasesIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterStateDiffIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesLifecycleListenerIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreClusterStateListener.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/TransportIndicesAliasesAction.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/get/GetAliasesResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/get/TransportGetAliasesAction.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/get/TransportGetIndexAction.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/ClusterState.java
  server/src/main/java/org/opensearch/cluster/RestoreInProgress.java
  server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
  server/src/main/java/org/opensearch/cluster/block/ClusterBlocks.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataDeleteIndexService.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/RoutingAllocation.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetAliasesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestAliasAction.java
  server/src/main/java/org/opensearch/snapshots/InFlightShardSnapshotStates.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/action/admin/indices/alias/get/GetAliasesResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/alias/get/TransportGetAliasesActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/datastream/DeleteDataStreamRequestTests.java
  server/src/test/java/org/opensearch/action/admin/indices/get/GetIndexResponseTests.java
  server/src/test/java/org/opensearch/cluster/ClusterStateTests.java
  server/src/test/java/org/opensearch/cluster/block/ClusterBlockTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataDeleteIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexStateServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AddIncrementallyTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/ThrottlingAllocationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/RestoreInProgressAllocationDeciderTests.java
  server/src/test/java/org/opensearch/cluster/serialization/ClusterSerializationTests.java
  server/src/test/java/org/opensearch/rest/action/admin/indices/RestGetAliasesActionTests.java
  server/src/test/java/org/opensearch/snapshots/InternalSnapshotsInfoServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotsInProgressSerializationTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotsServiceTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: enhancement, skip-changelog, v2.8.0

#7306 [Refactor] ImmutableOpenMap to j.u.Map in IndexMetadata
  client/rest-high-level/src/main/java/org/opensearch/client/indices/IndexTemplateMetadata.java
  client/rest-high-level/src/test/java/org/opensearch/client/indices/GetIndexTemplatesResponseTests.java
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterStateDiffIT.java
  server/src/main/java/org/opensearch/action/admin/indices/get/TransportGetIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/resolve/ResolveIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverService.java
  server/src/main/java/org/opensearch/cluster/DiffableUtils.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/gateway/DanglingIndicesState.java
  server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
  server/src/main/java/org/opensearch/snapshots/EmptySnapshotsInfoService.java
  server/src/main/java/org/opensearch/snapshots/InternalSnapshotsInfoService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardSizeInfo.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexTemplateMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/ThrottlingAllocationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/cluster/serialization/DiffableTests.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
Labels: enhancement, skip-changelog, v2.8.0

#7159 Remove builder instance from TextFieldMapper
  server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
Labels: skip-changelog

#7314 Add keyword to auto-close issue in PR template
  .github/pull_request_template.md
Labels: skip-changelog

#7317 Fix flakiness of testQueryFiltering due to error bound
  server/src/test/java/org/opensearch/search/aggregations/metrics/MedianAbsoluteDeviationAggregatorTests.java
Labels: skip-changelog

#6866 Add connectToNodeAsExtension in TransportService
  CHANGELOG.md
  server/src/main/java/org/opensearch/transport/TransportService.java
Labels: all-star-contributor

#7322 moved flat object from changed to added b/c it's new
  release-notes/opensearch.release-notes-2.7.0.md
Labels: backport 2.x, skip-changelog, backport 2.7
