Repository opensearch-project/OpenSearch, pull requests merged in 2023-08, with the labels that each got.

#8993 Fix flaky ResourceAwareTasksTests.testBasicTaskResourceTracking test
  CHANGELOG.md
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java
Labels: backport 2.x

#8718 [Remote Store] Add Segment download stats to remotestore stats API
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureService.java
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/DirectoryFileTransferTracker.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsResponseTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsActionTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#9017 Update version guards to deal for aggregation profiler with concurren…
  server/src/main/java/org/opensearch/search/profile/ProfileResult.java
Labels: skip-changelog

#9028 [Refactor] Recyclers to Common Library
  libs/common/src/main/java/org/opensearch/common/recycler/AbstractRecycler.java
  libs/common/src/main/java/org/opensearch/common/recycler/AbstractRecyclerC.java
  libs/common/src/main/java/org/opensearch/common/recycler/ConcurrentDequeRecycler.java
  libs/common/src/main/java/org/opensearch/common/recycler/DequeRecycler.java
  libs/common/src/main/java/org/opensearch/common/recycler/FilterRecycler.java
  libs/common/src/main/java/org/opensearch/common/recycler/NoneRecycler.java
  libs/common/src/main/java/org/opensearch/common/recycler/Recycler.java
  libs/common/src/main/java/org/opensearch/common/recycler/Recyclers.java
  libs/common/src/main/java/org/opensearch/common/recycler/package-info.java
  libs/common/src/main/java/org/opensearch/common/util/concurrent/ConcurrentCollections.java
  libs/common/src/main/java/org/opensearch/common/util/concurrent/ConcurrentHashMapLong.java
  libs/common/src/main/java/org/opensearch/common/util/concurrent/ConcurrentMapLong.java
  libs/common/src/test/java/org/opensearch/common/recycler/AbstractRecyclerTestCase.java
  libs/common/src/test/java/org/opensearch/common/recycler/ConcurrentRecyclerTests.java
  libs/common/src/test/java/org/opensearch/common/recycler/LockedRecyclerTests.java
  libs/common/src/test/java/org/opensearch/common/recycler/NoneRecyclerTests.java
  libs/common/src/test/java/org/opensearch/common/recycler/QueueRecyclerTests.java
Labels: enhancement, skip-changelog, v2.10.0

#9035 [BWC] Change BWC version check for MediaType
  server/src/main/java/org/opensearch/action/admin/cluster/storedscripts/PutStoredScriptRequest.java
  server/src/main/java/org/opensearch/action/index/IndexRequest.java
  server/src/main/java/org/opensearch/action/ingest/PutPipelineRequest.java
  server/src/main/java/org/opensearch/action/ingest/SimulatePipelineRequest.java
  server/src/main/java/org/opensearch/action/search/PutSearchPipelineRequest.java
  server/src/main/java/org/opensearch/action/termvectors/TermVectorsRequest.java
  server/src/main/java/org/opensearch/extensions/rest/ExtensionRestRequest.java
  server/src/main/java/org/opensearch/index/query/MoreLikeThisQueryBuilder.java
  server/src/main/java/org/opensearch/ingest/PipelineConfiguration.java
  server/src/main/java/org/opensearch/search/pipeline/PipelineConfiguration.java
Labels: non-issue, backwards-compatibility, v3.0.0, skip-changelog

#8486 Add workflow to check compatibility
  .github/workflows/check-compatibility.yml
  buildSrc/src/main/groovy/org/opensearch/gradle/CheckCompatibilityTask.groovy
Labels: skip-changelog

#9038 Update BwC version for file cache safeguards
  server/src/main/java/org/opensearch/cluster/ClusterInfo.java
Labels: skip-changelog

#9053 [BWC] Change BWC version check for MediaType in PercolateQueryBuilder
  modules/percolator/src/main/java/org/opensearch/percolator/PercolateQueryBuilder.java
Labels: non-issue, backwards-compatibility, v3.0.0, skip-changelog

#8767 [Segment Replication] Refactor RemoteStoreReplicationSource
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RemoteIndexSnapshotStatusApiIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/replication/GetSegmentFilesResponse.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationWithNodeToNodeIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationWithRemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/RemoteStoreReplicationSourceTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#8987 Readding codecs in the tests
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#8988 Added featureflag
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
Labels: skip-changelog

#9066 [Backport] [2.x] Added featureflag (#8988)
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
Labels: skip-changelog

#8472 [Snapshot Interop] Add Logic in Lock Manager to cleanup stale data po…
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerFactory.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: skip-changelog

#9084 skip engine instanceOf InternalEngine assertion for closed shards
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: skip-changelog

#8578 [Remote Store] Avoid indexing documents as stale in non primary mode
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexPrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#9057 Fix flaky test testStatsOnShardUnassigned in RemoteStoreStatsIT
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
Labels: skip-changelog

#9089 [Backport-2.x] Add Segment download stats to remotestore stats API
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureService.java
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/DirectoryFileTransferTracker.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsResponseTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsActionTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#9059 Change to determine if concurrent segment search should be used by the request during SearchContext creation
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
Labels: backport 2.x, skip-changelog

#9098 Remove empty if/try-finally in base integ test class
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: backport 2.x, skip-changelog

#9099 Fix testUploadMetadataMissingSegment unit test on 2.x
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: skip-changelog

#9101 [Remote Store] Add missing unit test in main
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: :test, skip-changelog, replication, storage

#9095 [Backport 2.x] Fix test testDropPrimaryDuringReplication and clean up ReplicationCheckpoint validation
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/SegmentReplicationCheckpointPublisher.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationWithNodeToNodeIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  server/src/test/java/org/opensearch/recovery/ReplicationCollectionTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#9047 Make MultiBucketConsumerService thread safe to use across slices during search
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/MultiBucketConsumerService.java
  server/src/test/java/org/opensearch/search/aggregations/MultiBucketConsumerTests.java
Labels: backport 2.x

#9126 [Refactor] Strings methods other than MediaType
  libs/core/src/main/java/org/opensearch/core/common/Strings.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/common/Strings.java
  server/src/main/java/org/opensearch/common/settings/PropertyPlaceholder.java
  server/src/main/java/org/opensearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshot.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
Labels: enhancement, skip-changelog, v2.10.0

#9131 Mute flaky test ReplicaToPrimaryPromotionIT.testFailoverWhileIndexing
  server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
Labels: skip-changelog

#8758 Fix local segments stats update in RemoteStoreRefreshListener
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/shard/CloseableRetryableRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  test/framework/src/main/java/org/opensearch/test/RemoteStoreTestUtils.java
Labels: skip-changelog

#9002 [Segment Replication] Remove Doc Parsing for segment replication enabled replica shard during translog replay from recovery
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: backport 2.x, skip-changelog

#8444 Added integration tests support for Telemetry span validation
  plugins/telemetry-otel/build.gradle
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/InMemorySingletonSpanExporter.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/IntegrationTestOTelTelemetryPlugin.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerDisabledSanityIT.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerEnabledSanityIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockSpanData.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingTelemetry.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/TelemetryValidators.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/TracingValidator.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/AllSpansAreEndedProperly.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/AllSpansHaveUniqueId.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/NumberOfTraceIDsEqualToRequests.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/TotalRootSpansEqualToRequests.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/package-info.java
Labels: skip-changelog

#9149 Fix compilation warning in CollectionUtils affecting maven snapshot publication
  libs/core/src/main/java/org/opensearch/core/common/util/CollectionUtils.java
Labels: skip-changelog

#8924 Add Gradle's 'assemble' check to catch the distribution generation issues
  .github/workflows/precommit.yml
  buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java
Labels: skip-changelog

#9159 Update the max_slice setting name to max_slice_count
  server/src/main/java/org/opensearch/search/SearchBootstrapSettings.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
Labels: skip-changelog

#9112 [Backport 2.x] Avoid duplicate indexing in case of SegRep enabled indices' translog …
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexPrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#9169 [Backport] [2.x] Bump io.projectreactor.netty:reactor-netty-http from 1.1.8 to 1.1.9 in /plugins/repository-azure (#9147)
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/reactor-netty-http-1.1.8.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.9.jar.sha1
Labels: backport

#9173 Reinstate maintainers from emeritus to active
  MAINTAINERS.md
Labels: non-issue, skip-changelog

#9174 [Backport] [2.x] Bump org.apache.maven:maven-model from 3.9.3 to 3.9.4 in /buildSrc (#9148)
  CHANGELOG.md
  buildSrc/build.gradle
Labels: backport

#9189 Fixing SnapshotResiliencyTests.testTransportGetSnapshotsAction
  CHANGELOG.md
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: skip-changelog

#9192 Backport/backport 8377 to 2.x
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: skip-changelog

#9188 [Backport 2.x] Added Integration tests support for Telemetry span Val…
  plugins/telemetry-otel/build.gradle
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/InMemorySingletonSpanExporter.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/IntegrationTestOTelTelemetryPlugin.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerDisabledSanityIT.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerEnabledSanityIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockSpanData.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingTelemetry.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/TelemetryValidators.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/TracingValidator.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/AllSpansAreEndedProperly.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/AllSpansHaveUniqueId.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/NumberOfTraceIDsEqualToRequests.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/TotalRootSpansEqualToRequests.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/validators/package-info.java
Labels: skip-changelog

#9181 Mute flaky test ShardMovementStrategyTests.testClusterGreenAfterParti…
  server/src/test/java/org/opensearch/cluster/routing/ShardMovementStrategyTests.java
Labels: skip-changelog

#9206 [BUG] org.opensearch.client.RestClientSingleHostIntegTests.testRequestResetAndAbort is flaky
  client/rest/src/test/java/org/opensearch/client/RestClientSingleHostIntegTests.java
Labels: skip-changelog

#9214 Add release notes for 1.3.12
  release-notes/opensearch.release-notes-1.3.12.md
Labels: skip-changelog

#9190 [Remote Store] Fix couple of Remote Store flaky test and use bulk api for ingestion
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
Labels: skip-changelog

#9221 Automatically update GitHub Actions dependencies with dependabot
  .github/dependabot.yml
Labels: skip-changelog

#9111 [Segment Replication] Refactor file cleanup logic and fix PIT/Scroll with remote store.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/ReplicaFileTracker.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/ReplicaFileTracker.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationWithNodeToNodeIndexShardTests.java
  server/src/test/java/org/opensearch/index/store/StoreTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: :test, skip-changelog

#9245 Fix flaky test SegmentReplicationIndexShardTests.testPrimaryRestart
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: skip-changelog

#9240 [Forwardport][2.x] Added bwc version 1.3.13.
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#9256 [Remote Store][Refactor] Introduce RemoteStoreRestoreService to handle restore from remote store
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/restore/TransportRestoreRemoteStoreAction.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
Labels: skip-changelog

#9260 [Backport] [2.x] Bump com.azure:azure-storage-blob from 12.22.3 to 12.23.0 in /plugins/repository-azure (#9231)
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-storage-blob-12.22.3.jar.sha1
  plugins/repository-azure/licenses/azure-storage-blob-12.23.0.jar.sha1
Labels: backport

#9244 Fix flaky test SegmentReplicationIT.testDeleteOperations.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: skip-changelog

#9270 Upgrade backport action to support failed labels
  .github/workflows/backport.yml
Labels: backport 1.x, backport 2.x, skip-changelog

#9269 Bump snakeyaml from 2.0 to 2.1
  CHANGELOG.md
  buildSrc/version.properties
  libs/x-content/licenses/snakeyaml-2.0.jar.sha1
  libs/x-content/licenses/snakeyaml-2.1.jar.sha1
Labels: dependencies

#9272 [Backport 2.x] [Segment Replication] Refactor file cleanup logic and fix PIT/Scroll with remote store.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/ReplicaFileTracker.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/ReplicaFileTracker.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationWithNodeToNodeIndexShardTests.java
  server/src/test/java/org/opensearch/index/store/StoreTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#9079 [Segment Replication] Unmute testIndexingWithSegRep rolling upgrade test
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: skip-changelog

#9278 [Backport to 2.x] [Segment Replication] Unmute testIndexingWithSegRep rolling upgrade test
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: skip-changelog

#9246 docCountError must be 0 for shard level reduce
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalTerms.java
Labels: skip-changelog

#9261 [Backport 2.x][Remote Store] Introduce RemoteStoreRestoreService to handle restore …
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/restore/TransportRestoreRemoteStoreAction.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
Labels: skip-changelog

#9268 [Backport 2.x] Fix local segments stats update in RemoteStoreRefreshListener (#8758)
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/shard/CloseableRetryableRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  test/framework/src/main/java/org/opensearch/test/RemoteStoreTestUtils.java
Labels: skip-changelog

#9293 [Remote Store] Remove stale code for remote restore from Restore Serv…
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
Labels: skip-changelog

#9308 [BWC and API enforcement] Extend the element types the initial set of annotations could be applied to
  libs/common/src/main/java/org/opensearch/common/annotation/DeprecatedApi.java
  libs/common/src/main/java/org/opensearch/common/annotation/ExperimentalApi.java
  libs/common/src/main/java/org/opensearch/common/annotation/InternalApi.java
  libs/common/src/main/java/org/opensearch/common/annotation/PublicApi.java
Labels: skip-changelog

#9296 [Backport] [2.x] [BWC and API enforcement] Define the initial set of annotations, their meaning and relations between them (#9223)
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  libs/common/src/main/java/org/opensearch/common/annotation/DeprecatedApi.java
  libs/common/src/main/java/org/opensearch/common/annotation/ExperimentalApi.java
  libs/common/src/main/java/org/opensearch/common/annotation/InternalApi.java
  libs/common/src/main/java/org/opensearch/common/annotation/PublicApi.java
  libs/common/src/main/java/org/opensearch/common/annotation/package-info.java
Labels: backport

#9307 [BUG] The spotless should take care of unified imports ordering (benchmarks/ subprojects)
  benchmarks/src/main/java/org/opensearch/benchmark/routing/allocation/AllocationBenchmark.java
  benchmarks/src/main/java/org/opensearch/benchmark/routing/allocation/Allocators.java
  benchmarks/src/main/java/org/opensearch/benchmark/search/aggregations/TermsReduceBenchmark.java
  benchmarks/src/main/java/org/opensearch/benchmark/search/aggregations/bucket/terms/StringTermsSerializationBenchmark.java
  benchmarks/src/main/java/org/opensearch/benchmark/store/remote/filecache/FileCacheBenchmark.java
  benchmarks/src/main/java/org/opensearch/benchmark/time/NanoTimeVsCurrentTimeMillisBenchmark.java
  benchmarks/src/main/java/org/opensearch/common/util/LongHashBenchmark.java
Labels: skip-changelog

#9139 Fix flaky testCorruptedTranslog test
  server/src/test/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommandTests.java
Labels: backport 2.x, skip-changelog

#9284 Restrict GitHub Actions to run only on OpenSearch repo
  .github/workflows/add-untriaged.yml
  .github/workflows/changelog_verifier.yml
  .github/workflows/check-compatibility.yml
  .github/workflows/gradle-check.yml
  .github/workflows/lucene-snapshots.yml
  .github/workflows/precommit.yml
  .github/workflows/publish-maven-snapshots.yml
  .github/workflows/stalled.yml
  .github/workflows/version.yml
  .github/workflows/wrapper.yml
Labels: skip-changelog

#8986 Return 409 Conflict HTTP status instead of 503 on failure to concurre…
  CHANGELOG.md
  server/src/main/java/org/opensearch/snapshots/ConcurrentSnapshotExecutionException.java
  server/src/test/java/org/opensearch/OpenSearchExceptionTests.java
Labels: v3.0.0

#9314 [BUG] The spotless should take care of unified imports ordering (buildSrc/ subprojects)
  buildSrc/src/main/java/org/opensearch/gradle/ConcatFilesTask.java
  buildSrc/src/main/java/org/opensearch/gradle/EmptyDirTask.java
  buildSrc/src/main/java/org/opensearch/gradle/LoggedExec.java
  buildSrc/src/main/java/org/opensearch/gradle/OpenSearchJavaPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/docker/DockerBuildTask.java
  buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java
  buildSrc/src/main/java/org/opensearch/gradle/http/WaitForHttpResource.java
  buildSrc/src/main/java/org/opensearch/gradle/info/GlobalBuildInfoPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalBwcGitPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveCheckPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/pluginzip/Publish.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/FilePermissionsTask.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ForbiddenApisPrecommitPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/JarHellTask.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/TestingConventionsTasks.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ValidateJsonAgainstSchemaTask.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ValidateJsonNoKeywordsTask.java
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/test/GradleDistroTestTask.java
  buildSrc/src/main/java/org/opensearch/gradle/test/JNAKernel32Library.java
  buildSrc/src/main/java/org/opensearch/gradle/test/RestIntegTestTask.java
  buildSrc/src/main/java/org/opensearch/gradle/test/TestSuiteConventionMappings.java
  buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestApiTask.java
  buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestTestsTask.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/StandaloneRestIntegTestTask.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClustersPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/util/Util.java
  buildSrc/src/main/java/org/opensearch/gradle/vagrant/VagrantMachine.java
  buildSrc/src/test/java/org/opensearch/gradle/ConcatFilesTaskTests.java
  buildSrc/src/test/java/org/opensearch/gradle/DistributionDownloadPluginTests.java
  buildSrc/src/test/java/org/opensearch/gradle/EmptyDirTaskTests.java
  buildSrc/src/test/java/org/opensearch/gradle/JdkDownloadPluginTests.java
  buildSrc/src/test/java/org/opensearch/gradle/plugin/OptionalDependenciesPluginTests.java
  buildSrc/src/test/java/org/opensearch/gradle/plugin/PluginBuildPluginTests.java
  buildSrc/src/test/java/org/opensearch/gradle/pluginzip/PublishTests.java
  buildSrc/src/test/java/org/opensearch/gradle/precommit/FilePermissionsTaskTests.java
  buildSrc/src/testFixtures/java/org/opensearch/gradle/test/BaseTestCase.java
  buildSrc/src/testFixtures/java/org/opensearch/gradle/test/GradleUnitTestCase.java
Labels: skip-changelog

#9262 Refactor Compressors from CompressorFactory to CompressorRegistry for extensibility
  gradle/missing-javadoc.gradle
  libs/compress/build.gradle
  libs/compress/licenses/zstd-jni-1.5.5-3.jar.sha1
  libs/compress/licenses/zstd-jni-LICENSE.txt
  libs/compress/licenses/zstd-jni-NOTICE.txt
  libs/compress/src/main/java/org/opensearch/compress/ZstdCompressor.java
  libs/compress/src/main/java/org/opensearch/compress/package-info.java
  libs/compress/src/main/java/org/opensearch/compress/spi/CompressionProvider.java
  libs/compress/src/main/java/org/opensearch/compress/spi/package-info.java
  libs/compress/src/main/java/org/opensearch/package-info.java
  libs/compress/src/main/resources/META-INF/services/org.opensearch.core.compress.spi.CompressorProvider
  libs/compress/src/test/java/org/opensearch/compress/ZstdCompressTests.java
  libs/core/src/main/java/org/opensearch/ExceptionsHelper.java
  libs/core/src/main/java/org/opensearch/core/compress/Compressor.java
  libs/core/src/main/java/org/opensearch/core/compress/CompressorRegistry.java
  libs/core/src/main/java/org/opensearch/core/compress/NoneCompressor.java
  libs/core/src/main/java/org/opensearch/core/compress/NotCompressedException.java
  libs/core/src/main/java/org/opensearch/core/compress/NotXContentException.java
  libs/core/src/main/java/org/opensearch/core/compress/package-info.java
  libs/core/src/main/java/org/opensearch/core/compress/spi/CompressorProvider.java
  libs/core/src/main/java/org/opensearch/core/compress/spi/DefaultCompressorProvider.java
  libs/core/src/main/java/org/opensearch/core/compress/spi/package-info.java
  libs/core/src/main/resources/META-INF/services/org.opensearch.core.compress.spi.CompressorProvider
  server/build.gradle
  server/src/main/java/org/opensearch/cluster/coordination/CompressedStreamUtils.java
  server/src/main/java/org/opensearch/common/compress/CompressedXContent.java
  server/src/main/java/org/opensearch/common/compress/CompressorFactory.java
  server/src/main/java/org/opensearch/common/compress/CompressorType.java
  server/src/main/java/org/opensearch/common/compress/DeflateCompressor.java
  server/src/main/java/org/opensearch/common/compress/spi/ServerCompressorProvider.java
  server/src/main/java/org/opensearch/common/compress/spi/package-info.java
  server/src/main/java/org/opensearch/common/io/stream/BytesStreamOutput.java
  server/src/main/java/org/opensearch/common/util/PageCacheRecycler.java
  server/src/main/java/org/opensearch/common/xcontent/XContentHelper.java
  server/src/main/java/org/opensearch/index/get/GetResult.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
  server/src/main/java/org/opensearch/search/SearchHit.java
  server/src/main/java/org/opensearch/transport/CompressibleBytesOutputStream.java
  server/src/main/java/org/opensearch/transport/TransportDecompressor.java
  server/src/main/java/org/opensearch/transport/TransportLogger.java
  server/src/main/resources/META-INF/services/org.opensearch.core.compress.spi.CompressorProvider
  server/src/test/java/org/opensearch/common/compress/DeflateCompressTests.java
  server/src/test/java/org/opensearch/common/compress/DeflateCompressedXContentTests.java
  server/src/test/java/org/opensearch/index/mapper/BinaryFieldMapperTests.java
  server/src/test/java/org/opensearch/snapshots/BlobStoreFormatTests.java
  server/src/test/java/org/opensearch/transport/CompressibleBytesOutputStreamTests.java
  server/src/test/java/org/opensearch/transport/TransportDecompressorTests.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchBlobStoreRepositoryIntegTestCase.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/core/compress/AbstractCompressorTestCase.java
Labels: enhancement, pending backport, skip-changelog, v2.10.0

#9323 Change noisy logs on SegRep and remote store paths to trace level
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
Labels: skip-changelog

#9324 [Segment Replication] Mute flaky testIndexingWithSegRep test
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: skip-changelog

#9335 Enforce up-to-date Guava in buildSrc
  buildSrc/build.gradle
Labels: skip-changelog

#9354 Mute RemoteRestoreSnapshotIT.testRestoreInSameRemoteStoreEnabledIndex
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
Labels: backport 2.x, skip-changelog

#9083 Add base class for parameterizing the search based tests
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/ConcurrentSegmentSearchCancellationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/ConcurrentSegmentSearchTimeoutIT.java
  server/src/internalClusterTest/java/org/opensearch/search/SearchCancellationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
  test/framework/src/main/java/org/opensearch/test/ParameterizedOpenSearchIntegTestCase.java
Labels: backport 2.x

#9366 Mute remote store + segRep flaky tests that frequently block checks.
  server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreForceMergeIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Labels: skip-changelog

#8508 Default to mmapfs within hybridfs
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/store/FsDirectoryFactory.java
  server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java
Labels: backport 2.x, v2.10.0

#9177 Rethrow OpenSearch exception in concurrent search
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/memory/breaker/CircuitBreakerServiceIT.java
  server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java
Labels: backport 2.x

#9389 [Remote Store] Changing remotestore based NodesStats metrics version to 2.10
  server/src/main/java/org/opensearch/index/engine/SegmentsStats.java
Labels: skip-changelog

#9387 [Remote Store] Rename RemoteRefreshSegmentPressureSettings and RemoteRefreshSegmentPressureService
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteSegmentStatsFromNodesStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePressureService.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePressureSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/DirectoryFileTransferTracker.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsActionTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureSettingsTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#9381 [Backport 2.x] Restrict GitHub Actions to run only on OpenSearch repo (#9284)
  .github/workflows/changelog_verifier.yml
  .github/workflows/check-compatibility.yml
  .github/workflows/gradle-check.yml
  .github/workflows/lucene-snapshots.yml
  .github/workflows/precommit.yml
  .github/workflows/publish-maven-snapshots.yml
  .github/workflows/version.yml
  .github/workflows/wrapper.yml
Labels: skip-changelog

#9365 Fix flaky test InternalEngineTests.testLastRefreshCheckpoint
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
Labels: backport 2.x, skip-changelog

#9378 Fix flaky test NRTReplicationEngineTests.testPreserveLatestCommit
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
Labels: backport 2.x, skip-changelog

#9355 [Remove] JodaCompatibleZonedDateTime
  libs/core/src/test/java/org/opensearch/core/common/io/stream/BaseStreamTests.java
  modules/lang-painless/src/main/java/org/opensearch/painless/AnalyzerCaster.java
  modules/lang-painless/src/main/java/org/opensearch/painless/Def.java
  modules/lang-painless/src/main/java/org/opensearch/painless/MethodWriter.java
  modules/lang-painless/src/main/java/org/opensearch/painless/Utility.java
  modules/lang-painless/src/main/java/org/opensearch/painless/WriterConstants.java
  modules/lang-painless/src/main/java/org/opensearch/painless/api/Augmentation.java
  modules/lang-painless/src/main/resources/org/opensearch/painless/spi/java.time.txt
  modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.score.txt
  modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.txt
  modules/lang-painless/src/test/java/org/opensearch/painless/BasicAPITests.java
  modules/lang-painless/src/test/java/org/opensearch/painless/DefCastTests.java
  modules/lang-painless/src/test/resources/org/opensearch/painless/spi/org.opensearch.painless.test
  server/src/main/java/org/opensearch/common/io/stream/Streamables.java
  server/src/main/java/org/opensearch/common/xcontent/XContentOpenSearchExtension.java
  server/src/main/java/org/opensearch/index/fielddata/ScriptDocValues.java
  server/src/main/java/org/opensearch/script/JodaCompatibleZonedDateTime.java
  server/src/main/java/org/opensearch/script/ScoreScriptUtils.java
  server/src/main/java/org/opensearch/search/aggregations/support/values/ScriptDoubleValues.java
  server/src/main/java/org/opensearch/search/aggregations/support/values/ScriptLongValues.java
  server/src/test/java/org/opensearch/common/io/stream/BytesStreamsTests.java
  server/src/test/java/org/opensearch/script/JodaCompatibleZonedDateTimeTests.java
Labels: enhancement, pending backport, backwards-compatibility, stalled, skip-changelog, v2.10.0, needs-review

#9184 Fix flaky test by preventing duplicate keys in random mapping fields
  test/framework/src/main/java/org/opensearch/index/RandomCreateIndexGenerator.java
Labels: backport 2.x, skip-changelog

#9421 [Backport 2.x][Segment Replication] Support realtime reads for GET requests (#9212)
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/action/get/TransportGetAction.java
  server/src/main/java/org/opensearch/action/get/TransportMultiGetAction.java
  server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java
Labels: v2.10.0

#9267 Introduce cluster default and minimum index refresh interval settings
  server/src/internalClusterTest/java/org/opensearch/cluster/metadata/ClusterIndexRefreshIntervalIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/metadata/ClusterIndexRefreshIntervalWithNodeSettingsIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
Labels: skip-changelog

#9350 [Remove] Joda from Serialization
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamInput.java
  server/src/main/java/org/opensearch/common/io/stream/Streamables.java
  server/src/main/java/org/opensearch/common/xcontent/XContentOpenSearchExtension.java
  server/src/main/java/org/opensearch/rest/action/cat/RestCatRecoveryAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestCatSegmentReplicationAction.java
  server/src/main/java/org/opensearch/search/DocValueFormat.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexGraveyardTests.java
  server/src/test/java/org/opensearch/common/io/stream/BytesStreamsTests.java
  server/src/test/java/org/opensearch/common/xcontent/BaseXContentTestCase.java
  server/src/test/java/org/opensearch/common/xcontent/builder/XContentBuilderTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestRecoveryActionTests.java
Labels: enhancement, pending backport, backwards-compatibility, skip-changelog, v2.10.0

#9445 Change log level of SegRep cancellations to debug
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
Labels: backport 2.x, skip-changelog

#9367 [Backport 2.x] Refactor Compressors from CompressorFactory to CompressorRegistry for extensibility (#9262)
  CHANGELOG.md
  gradle/missing-javadoc.gradle
  libs/compress/build.gradle
  libs/compress/licenses/zstd-jni-1.5.5-5.jar.sha1
  libs/compress/licenses/zstd-jni-LICENSE.txt
  libs/compress/licenses/zstd-jni-NOTICE.txt
  libs/compress/src/main/java/org/opensearch/compress/ZstdCompressor.java
  libs/compress/src/main/java/org/opensearch/compress/package-info.java
  libs/compress/src/main/java/org/opensearch/compress/spi/CompressionProvider.java
  libs/compress/src/main/java/org/opensearch/compress/spi/package-info.java
  libs/compress/src/main/java/org/opensearch/package-info.java
  libs/compress/src/main/resources/META-INF/services/org.opensearch.core.compress.spi.CompressorProvider
  libs/compress/src/test/java/org/opensearch/compress/ZstdCompressTests.java
  libs/core/src/main/java/org/opensearch/core/compress/Compressor.java
  libs/core/src/main/java/org/opensearch/core/compress/CompressorRegistry.java
  libs/core/src/main/java/org/opensearch/core/compress/NoneCompressor.java
  libs/core/src/main/java/org/opensearch/core/compress/NotCompressedException.java
  libs/core/src/main/java/org/opensearch/core/compress/NotXContentException.java
  libs/core/src/main/java/org/opensearch/core/compress/package-info.java
  libs/core/src/main/java/org/opensearch/core/compress/spi/CompressorProvider.java
  libs/core/src/main/java/org/opensearch/core/compress/spi/DefaultCompressorProvider.java
  libs/core/src/main/java/org/opensearch/core/compress/spi/package-info.java
  libs/core/src/main/resources/META-INF/services/org.opensearch.core.compress.spi.CompressorProvider
  server/build.gradle
  server/src/main/java/org/opensearch/cluster/coordination/CompressedStreamUtils.java
  server/src/main/java/org/opensearch/common/compress/CompressedXContent.java
  server/src/main/java/org/opensearch/common/compress/CompressorFactory.java
  server/src/main/java/org/opensearch/common/compress/CompressorType.java
  server/src/main/java/org/opensearch/common/compress/DeflateCompressor.java
  server/src/main/java/org/opensearch/common/compress/spi/ServerCompressorProvider.java
  server/src/main/java/org/opensearch/common/compress/spi/package-info.java
  server/src/main/java/org/opensearch/common/xcontent/XContentHelper.java
  server/src/main/java/org/opensearch/index/get/GetResult.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
  server/src/main/java/org/opensearch/search/SearchHit.java
  server/src/main/java/org/opensearch/transport/CompressibleBytesOutputStream.java
  server/src/main/java/org/opensearch/transport/TransportDecompressor.java
  server/src/main/java/org/opensearch/transport/TransportLogger.java
  server/src/main/resources/META-INF/services/org.opensearch.core.compress.spi.CompressorProvider
  server/src/test/java/org/opensearch/common/compress/DeflateCompressTests.java
  server/src/test/java/org/opensearch/common/compress/DeflateCompressedXContentTests.java
  server/src/test/java/org/opensearch/index/mapper/BinaryFieldMapperTests.java
  server/src/test/java/org/opensearch/snapshots/BlobStoreFormatTests.java
  server/src/test/java/org/opensearch/transport/CompressibleBytesOutputStreamTests.java
  server/src/test/java/org/opensearch/transport/TransportDecompressorTests.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchBlobStoreRepositoryIntegTestCase.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/core/compress/AbstractCompressorTestCase.java
Labels: enhancement, backport, >breaking, v2.10.0, needs-review

#9420 Fix testClusterRelocationNoPreferenceShardMovementPrimaryFirstEnabled failure due to timeout
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/test/java/org/opensearch/cluster/routing/ShardMovementStrategyTests.java
Labels: skip-changelog, v2.10.0

#9458 Bugfix: remove assert on non-empty translog reader list
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
Labels: skip-changelog

#9486 Github action for Gradle precommit failing on MacOS
  .github/workflows/precommit.yml
Labels: backport 2.x, skip-changelog

#9474 [2.x] Bump actions/setup-java from 2 to 3 (#9457)
  .github/workflows/lucene-snapshots.yml
Labels: backport, dependencies, skip-changelog

#9081 [Feature] Expose term frequency in Painless script score context
  CHANGELOG.md
  modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScoreScript.java
  modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScriptEngine.java
  modules/lang-painless/src/main/java/org/opensearch/painless/action/PainlessExecuteAction.java
  modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.score.txt
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/120_script_score_term_frequency.yml
  plugins/examples/script-expert-scoring/src/main/java/org/opensearch/example/expertscript/ExpertScriptPlugin.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/ExplainableScriptIT.java
  server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreFunctionBuilder.java
  server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/functionscore/TermFrequencyFunction.java
  server/src/main/java/org/opensearch/index/query/functionscore/TermFrequencyFunctionFactory.java
  server/src/main/java/org/opensearch/script/ScoreScript.java
  server/src/main/java/org/opensearch/script/ScoreScriptUtils.java
  server/src/main/java/org/opensearch/search/lookup/LeafTermFrequencyLookup.java
  server/src/test/java/org/opensearch/search/query/ScriptScoreQueryTests.java
  test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Labels: Search

#9480 [Remote Store] Fix tests when we restore index without any refresh
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/index/translog/TranslogHeader.java
  server/src/test/java/org/opensearch/index/store/StoreTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogHeaderTests.java
Labels: skip-changelog

#9410 [BUG] Reconstruct pit infos when deserialize GetAllPitNodesResponse
  server/src/main/java/org/opensearch/action/search/GetAllPitNodesResponse.java
  server/src/main/java/org/opensearch/action/search/ListPitInfo.java
  server/src/test/java/org/opensearch/action/search/GetAllPitNodesResponseTests.java
Labels: skip-changelog

#9501 Fix flaky test SegmentReplicationWithRemoteStorePressureIT.testAddReplicaWhileWritesBlocked
  server/src/internalClusterTest/java/org/opensearch/index/SegmentReplicationPressureIT.java
Labels: :test, backport 2.x, skip-changelog

#9374 Run compatibility check based on PR base branch
  .github/workflows/check-compatibility.yml
Labels: skip-changelog

#9463 Add Michael Froh as a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#9516 Fix range reads in respository-s3
  CHANGELOG.md
  plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsBlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/utils/HttpRangeUtils.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RetryingInputStreamTests.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchBlobStoreRepositoryIntegTestCase.java
Labels: backport 2.x

#9470 Handle null partSize in OnDemandBlockSnapshotIndexInput
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
Labels: backport 2.x

#8896 Update to Gradle 8.3
  buildSrc/src/main/java/org/opensearch/gradle/test/RestIntegTestTask.java
  buildSrc/src/main/java/org/opensearch/gradle/test/TestTask.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/StandaloneRestIntegTestTask.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: Build Libraries & Interfaces, skip-changelog

#9466 Fix the script sort related ITs
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/internalClusterTest/java/org/opensearch/search/sort/SimpleSortIT.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/BytesRefFieldComparatorSource.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/DoubleValuesComparatorSource.java
  server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java
Labels: backport 2.x

#9524 Implement range reads in HDFS repository
  CHANGELOG.md
  plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsBlobContainer.java
  plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsBlobStoreRepositoryTests.java
Labels: backport 2.x

#9528 Removing the vec file extension from INDEX_STORE_HYBRID_NIO_EXTENSIONS, to ensure the no performance degradation for vector search via Lucene Engine.
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/IndexModule.java
Labels: backport 2.x, v2.10.0

#9545 [Remote Store] Removing version checks from RemoteSegmentStats
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java
Labels: skip-changelog

#9515 Fix flaky test ArchivedIndexSettingsIT
  server/src/internalClusterTest/java/org/opensearch/indices/settings/ArchivedIndexSettingsIT.java
Labels: skip-changelog

#8788 Performance improvements for BytesRefHash
  CHANGELOG.md
  benchmarks/src/main/java/org/opensearch/common/hash/HashFunctionBenchmark.java
  benchmarks/src/main/java/org/opensearch/common/util/BytesRefHashBenchmark.java
  libs/common/src/main/java/org/opensearch/common/Numbers.java
  libs/common/src/main/java/org/opensearch/common/hash/T1ha1.java
  libs/common/src/main/java/org/opensearch/common/hash/package-info.java
  libs/common/src/test/java/org/opensearch/common/hash/T1Ha1Tests.java
  server/src/main/java/org/opensearch/common/util/BytesRefHash.java
  server/src/main/java/org/opensearch/common/util/ReorganizingLongHash.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/BytesKeyedBucketOrds.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificanceLookup.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/StringRareTermsAggregator.java
  server/src/test/java/org/opensearch/common/NumbersTests.java
  server/src/test/java/org/opensearch/common/util/BytesRefHashTests.java
  test/framework/src/main/java/org/opensearch/common/hash/AvalancheStats.java
  test/framework/src/main/java/org/opensearch/common/hash/HashFunctionTestCase.java
  test/framework/src/test/java/org/opensearch/common/hash/HashFunctionTestCaseTests.java
Labels: backport 2.x, v2.10.0

#9482 Fix test DeletePitMultiNodeIT.testDeleteWhileSearch
  server/src/internalClusterTest/java/org/opensearch/search/pit/DeletePitMultiNodeIT.java
Labels: backport 2.x, skip-changelog

#9560 [Backport] [1.3] Bump netty from 4.1.96.Final to 4.1.97.Final (#9553)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.97.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.96.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.97.Final.jar.sha1
Labels: dependencies

#9559 [Backport] [1.x] Bump netty from 4.1.96.Final to 4.1.97.Final (#9553)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.97.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.96.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.97.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.96.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.97.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.96.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.97.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.96.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.97.Final.jar.sha1
Labels: dependencies

#8951 Bugfix: add replica information in remote store restore flow
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingTableTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#9583 [Backport 2.x] Add Michael Froh as a maintainer (#9463)
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#9562 For sort request on timeseries field use non concurrent search path
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/main/java/org/opensearch/search/query/QueryPhaseSearcherWrapper.java
  server/src/main/java/org/opensearch/search/sort/SortAndFormats.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  test/framework/src/main/java/org/opensearch/test/TestSearchContext.java
Labels: backport 2.x

#9593 [Segment Replication] Add ClusterState utility to identify SEGMENT replication
  server/src/main/java/org/opensearch/action/get/TransportGetAction.java
  server/src/main/java/org/opensearch/cluster/ClusterState.java
  server/src/test/java/org/opensearch/cluster/ClusterStateTests.java
Labels: backport 2.x, skip-changelog

#9612 [Backport] [2.x] Bump io.grpc:grpc-api from 1.57.1 to 1.57.2 in /plugins/repository-gcs (#9578)
  CHANGELOG.md
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/grpc-api-1.57.1.jar.sha1
  plugins/repository-gcs/licenses/grpc-api-1.57.2.jar.sha1
Labels: backport, dependencies

#9379 Add SearchExtBuilders to SearchResponse
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchResponse.java
  server/src/main/java/org/opensearch/action/search/SearchResponseSections.java
  server/src/main/java/org/opensearch/search/GenericSearchExtBuilder.java
  server/src/main/java/org/opensearch/search/internal/InternalSearchResponse.java
  server/src/test/java/org/opensearch/action/search/SearchResponseTests.java
  server/src/test/java/org/opensearch/search/GenericSearchExtBuilderTests.java
Labels: Search, v2.10.0

#9596 Fix GH runners memory issue by increasing swapfile
  .github/workflows/check-compatibility.yml
Labels: skip-changelog

#9597 [Remote Store] Retry RemoteIndexShardTests flaky tests
  build.gradle
Labels: skip-changelog

#9520 [BWC and API enforcement] Decorate the existing APIs with proper annotations (part 1)
  CHANGELOG.md
  libs/common/src/main/java/org/opensearch/common/CheckedConsumer.java
  libs/common/src/main/java/org/opensearch/common/action/ActionFuture.java
  libs/common/src/main/java/org/opensearch/common/lifecycle/Lifecycle.java
  libs/common/src/main/java/org/opensearch/common/lifecycle/LifecycleComponent.java
  libs/common/src/main/java/org/opensearch/common/unit/TimeValue.java
  libs/core/src/main/java/org/opensearch/Version.java
  libs/core/src/main/java/org/opensearch/core/ParseField.java
  libs/core/src/main/java/org/opensearch/core/action/ActionListener.java
  libs/core/src/main/java/org/opensearch/core/common/bytes/BytesReference.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/NamedWriteableRegistry.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamInput.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamOutput.java
  libs/core/src/main/java/org/opensearch/core/common/settings/SecureString.java
  libs/core/src/main/java/org/opensearch/core/common/unit/ByteSizeUnit.java
  libs/core/src/main/java/org/opensearch/core/common/unit/ByteSizeValue.java
  libs/core/src/main/java/org/opensearch/core/index/Index.java
  libs/core/src/main/java/org/opensearch/core/index/shard/ShardId.java
  libs/core/src/main/java/org/opensearch/core/rest/RestStatus.java
  libs/core/src/main/java/org/opensearch/core/tasks/TaskId.java
  libs/core/src/main/java/org/opensearch/core/xcontent/MediaType.java
  libs/core/src/main/java/org/opensearch/core/xcontent/NamedXContentRegistry.java
  libs/core/src/main/java/org/opensearch/core/xcontent/XContentBuilder.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapCheck.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapContext.java
  server/src/main/java/org/opensearch/client/AdminClient.java
  server/src/main/java/org/opensearch/client/Client.java
  server/src/main/java/org/opensearch/client/ClusterAdminClient.java
  server/src/main/java/org/opensearch/client/IndicesAdminClient.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/common/inject/Module.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/SecureSettings.java
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/common/settings/SettingUpgrader.java
  server/src/main/java/org/opensearch/common/settings/Settings.java
  server/src/main/java/org/opensearch/common/settings/SettingsException.java
  server/src/main/java/org/opensearch/env/Environment.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/env/ShardLock.java
  server/src/main/java/org/opensearch/env/ShardLockObtainFailedException.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexSettingProvider.java
  server/src/main/java/org/opensearch/plugins/Plugin.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/main/java/org/opensearch/script/Script.java
  server/src/main/java/org/opensearch/script/ScriptContext.java
  server/src/main/java/org/opensearch/script/ScriptEngine.java
  server/src/main/java/org/opensearch/script/ScriptService.java
  server/src/main/java/org/opensearch/script/ScriptType.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/main/java/org/opensearch/watcher/ResourceWatcherService.java
Labels: API

#9471 Fix SegmentReplicationUsingRemoteStoreIT#testDropPrimaryDuringReplication.
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
Labels: skip-changelog

#9561 Allow MockTracingTelemetry to await for asynchronous tasks termination before validating spans
  test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetry.java
  test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetryPlugin.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockTracingTelemetry.java
Labels: skip-changelog

#9426 Add benchmark to measure CustomBinaryDocValuesField performance
  benchmarks/src/main/java/org/opensearch/benchmark/index/mapper/CustomBinaryDocValuesFieldBenchmark.java
  server/src/main/java/org/opensearch/index/mapper/BinaryFieldMapper.java
Labels: backport 2.x, skip-changelog

#9622 Adding concurrent search versions of query count/time metrics
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
  server/src/internalClusterTest/java/org/opensearch/search/stats/ConcurrentSearchStatsIT.java
  server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
  server/src/main/java/org/opensearch/index/search/stats/ShardSearchStats.java
  server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java
Labels: backport 2.x

#9536 [Segment Replication] Handle failover in mixed cluster mode
  server/src/main/java/org/opensearch/action/get/TransportGetAction.java
  server/src/main/java/org/opensearch/action/get/TransportMultiGetAction.java
  server/src/main/java/org/opensearch/cluster/ClusterState.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/test/java/org/opensearch/action/get/TransportGetActionTests.java
  server/src/test/java/org/opensearch/action/get/TransportMultiGetActionTests.java
  server/src/test/java/org/opensearch/cluster/ClusterStateTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/FailedNodeRoutingTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/FailedShardsRoutingTests.java
Labels: skip-changelog

#9546 [Remote Store] Add tracker factory to manage remote store stats trackers
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePressureService.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePressureSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreStatsTrackerFactory.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsActionTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureSettingsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreStatsTrackerFactoryTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreTestsHelper.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#9648 [Backport 2.x] Fix SegmentReplicationUsingRemoteStoreIT#testDropPrimaryDuringReplication. (#9471)
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
Labels: skip-changelog

#8466 initial commit of crypto lib
  CHANGELOG.md
  buildSrc/version.properties
  libs/common/src/main/java/org/opensearch/common/crypto/CryptoHandler.java
  libs/common/src/main/java/org/opensearch/common/crypto/DataKeyPair.java
  libs/common/src/main/java/org/opensearch/common/crypto/DecryptedRangedStreamProvider.java
  libs/common/src/main/java/org/opensearch/common/crypto/EncryptedHeaderContentSupplier.java
  libs/common/src/main/java/org/opensearch/common/crypto/MasterKeyProvider.java
  libs/common/src/main/java/org/opensearch/common/crypto/package-info.java
  libs/encryption-sdk/build.gradle
  libs/encryption-sdk/licenses/aws-encryption-sdk-java-2.4.0.jar.sha1
  libs/encryption-sdk/licenses/aws-encryption-sdk-java-LICENSE.txt
  libs/encryption-sdk/licenses/aws-encryption-sdk-java-NOTICE.txt
  libs/encryption-sdk/licenses/bcprov-jdk15to18-1.75.jar.sha1
  libs/encryption-sdk/licenses/bcprov-jdk15to18-LICENSE.txt
  libs/encryption-sdk/licenses/bcprov-jdk15to18-NOTICE.txt
  libs/encryption-sdk/licenses/commons-lang3-3.13.0.jar.sha1
  libs/encryption-sdk/licenses/commons-lang3-LICENSE.txt
  libs/encryption-sdk/licenses/commons-lang3-NOTICE.txt
  libs/encryption-sdk/licenses/commons-logging-1.2.jar.sha1
  libs/encryption-sdk/licenses/commons-logging-LICENSE.txt
  libs/encryption-sdk/licenses/commons-logging-NOTICE.txt
  libs/encryption-sdk/licenses/slf4j-api-1.7.36.jar.sha1
  libs/encryption-sdk/licenses/slf4j-api-LICENSE.txt
  libs/encryption-sdk/licenses/slf4j-api-NOTICE.txt
  libs/encryption-sdk/src/forbidden/crypto-signatures.txt
  libs/encryption-sdk/src/forbidden/crypto-test-signatures.txt
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/CryptoManager.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/CryptoManagerFactory.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/NoOpCryptoHandler.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/TrimmingStream.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/keyprovider/CryptoMasterKey.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/keyprovider/package-info.java
  libs/encryption-sdk/src/main/java/org/opensearch/encryption/package-info.java
  libs/encryption-sdk/src/test/java/org/opensearch/encryption/CryptoManagerFactoryTests.java
  libs/encryption-sdk/src/test/java/org/opensearch/encryption/MockKeyProvider.java
  libs/encryption-sdk/src/test/java/org/opensearch/encryption/NoOpCryptoHandlerTests.java
  libs/encryption-sdk/src/test/java/org/opensearch/encryption/TrimmingStreamTests.java
  libs/encryption-sdk/src/test/resources/encrypted_key
  libs/encryption-sdk/src/test/resources/raw_content_for_crypto_test
  libs/encryption-sdk/src/test/resources/raw_key
  plugins/ingest-attachment/build.gradle
  plugins/repository-azure/build.gradle
Labels: feature, durability, v2.10.0

#9671 [Backport] [2.x] Expose DelimitedTermFrequencyTokenFilter (#9479)
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisPlugin.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/DelimitedTermFrequencyTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/CommonAnalysisFactoryTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/DelimitedTermFrequencyTokenFilterFactoryTests.java
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/40_token_filters.yml
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: backport
