Repository opensearch-project/OpenSearch, pull requests merged in 2023-12, with the labels that each got.

#11390 [Backport 2.x] Improving the performance of date histogram aggregation (without any …
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/10_histogram.yml
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/FilterRewriteHelper.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregatorTests.java
Labels: enhancement, Search:Aggregations, Performance, v2.12.0

#11238 Fix bug where replication lag grows post primary relocation
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreDisruptionIT.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Labels: bug, backport 2.x, Indexing:Replication

#11327 Optimizations in s3 async upload flow and guards against S3 async SDK…
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
Labels: skip-changelog, v2.12.0

#9405 [Search Pipelines] Add request-scoped state shared between processors
  CHANGELOG.md
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/BasicMap.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/CollapseResponseProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/OversampleRequestProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/ScriptRequestProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchRequestMap.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchRequestMapProcessingException.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/TruncateHitsResponseProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/helpers/ContextUtils.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/helpers/SearchRequestMap.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/helpers/SearchResponseUtil.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/CollapseResponseProcessorTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/OversampleRequestProcessorTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/ScriptRequestProcessorTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchRequestMapTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/TruncateHitsResponseProcessorTests.java
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/60_oversample_truncate.yml
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/70_script_truncate.yml
  server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
  server/src/main/java/org/opensearch/search/pipeline/PipelineProcessingContext.java
  server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java
  server/src/main/java/org/opensearch/search/pipeline/Processor.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPhaseResultsProcessor.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/main/java/org/opensearch/search/pipeline/SearchRequestProcessor.java
  server/src/main/java/org/opensearch/search/pipeline/SearchResponseProcessor.java
  server/src/main/java/org/opensearch/search/pipeline/StatefulSearchRequestProcessor.java
  server/src/main/java/org/opensearch/search/pipeline/StatefulSearchResponseProcessor.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: v2.12.0

#11476 Bump `org.apache.zookeeper:zookeper` from 3.8.0 to 3.8.3
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport 1.3

#11492 Fix for flaky test SimpleBlocksIT.testAddBlockWhileDeletingIndices
  server/src/internalClusterTest/java/org/opensearch/blocks/SimpleBlocksIT.java
Labels: bug, >test-failure, flaky-test, backport 2.x, skip-changelog

#11449 Fix explanation message for TargetPoolAllocationDecider
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDeciderTests.java
Labels: backport 2.x, skip-changelog

#11417 Fix template setting override for replication type
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: bug, backport 2.x, Indexing:Replication, v2.12.0

#11175 [BWC and API enforcement] Introduce checks for enforcing the API restrictions
  CHANGELOG.md
  libs/common/src/main/java/org/opensearch/common/Nullable.java
  libs/common/src/main/java/org/opensearch/common/SuppressForbidden.java
  libs/common/src/main/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessor.java
  libs/common/src/main/java/org/opensearch/common/annotation/processor/package-info.java
  libs/common/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  libs/common/src/test/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessorTests.java
  libs/common/src/test/java/org/opensearch/common/annotation/processor/CompilerSupport.java
  libs/common/src/test/resources/org/acme/PublicApiAnnotated.java
  libs/common/src/test/resources/org/opensearch/bootstrap/test.policy
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/DeprecatedApiMethodReturnSelf.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/ExperimentalApiAnnotated.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/ExperimentalApiMethodReturnSelf.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/InternalApiAnnotated.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/NotAnnotated.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/NotAnnotatedAnnotation.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/NotAnnotatedException.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiAnnotated.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiConstructorArgumentAnnotatedInternalApi.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiConstructorArgumentNotAnnotated.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodArgumentAnnotatedPackagePrivate.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodArgumentNotAnnotated.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodArgumentNotAnnotatedGenerics.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodArgumentNotAnnotatedPackagePrivate.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodGenericsArgumentAnnotated.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodGenericsArgumentNotAnnotated.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodReturnAnnotatedArray.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodReturnAnnotatedGenerics.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodReturnNotAnnotated.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodReturnNotAnnotatedAnnotation.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodReturnNotAnnotatedArray.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodReturnNotAnnotatedBoundedGenerics.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodReturnNotAnnotatedGenerics.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodReturnNotAnnotatedWildcardGenerics.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodReturnSelf.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiMethodThrowsNotAnnotated.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiPackagePrivate.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiWithExperimentalApiMethod.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiWithInternalApiMethod.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiWithPackagePrivateMethod.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiWithProtectedInterface.java
  server/build.gradle
  server/src/main/java/org/opensearch/common/network/NetworkModule.java
  server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
  test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java
Labels: enhancement, Plugins, backport 2.x, API

#11334 Fixes to prevent segment fault errors arising due to unexpected SDK b…
  server/src/main/java/org/opensearch/common/StreamContext.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainer.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/stream/OffsetRangeIndexInputStream.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/stream/OffsetRangeInputStream.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/stream/RateLimitingOffsetRangeInputStream.java
  server/src/test/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainerTests.java
Labels: skip-changelog, v2.12.0

#11432 Remove cap of processors on remote store related threadpools
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: backport 2.x, skip-changelog

#11501 Bump jetty from 9.4.51.v20230217 to 9.4.52.v20230823 on 1.x line
  CHANGELOG.md
  buildSrc/version.properties
Labels: backport 1.3

#11516 Fix invalid BulkRequest construction for indexRandom()
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#11500 Bump versions of reactor-core and reactor-netty
  CHANGELOG.md
  buildSrc/version.properties
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/reactive-streams-1.0.3.jar.sha1
  plugins/repository-azure/licenses/reactive-streams-1.0.4.jar.sha1
  plugins/repository-azure/licenses/reactor-core-3.4.23.jar.sha1
  plugins/repository-azure/licenses/reactor-core-3.4.34.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-1.0.16.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-1.0.39.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.0.24.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.0.39.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.0.24.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.0.39.jar.sha1
Labels: backport 1.3

#11521 Force version of logback-core and logback-classic to 1.2.13
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport 1.x, backport 2.x

#11532 [Remote Store] Avoid repeated delete calls for the stale segment files
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: skip-changelog

#11539 Bump jetty version in hdfs-fixture to 9.4.53.v20231009
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport 2.x

#11562 Restore support for Java 8 for RestClient
  CHANGELOG.md
  client/rest/build.gradle
  client/rest/src/main/java/org/opensearch/client/RestClient.java
  client/rest/src/test/java/org/opensearch/client/nio/HeapBufferedAsyncEntityConsumerTests.java
  client/test/build.gradle
Labels: backport 2.x

#11564 Exclude apache avro version included with hadoop-minicluster
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport 1.x, backport 2.x, skip-changelog

#11565 Bump grgit-core from 5.2.0 to 5.2.1
  buildSrc/build.gradle
Labels: backport 1.x, backport 2.x, skip-changelog

#11571 Replace jgit version included through gradle-info-plugin on 1.x line
  buildSrc/build.gradle
Labels: backport 1.3, skip-changelog

#11572 [Backport 2.x] Bump grgit-core ffrom 5.2.0 to 5.2.1 (#11565)
  buildSrc/build.gradle
Labels: skip-changelog

#11170 Create separate transport action for render search template action
  CHANGELOG.md
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/MustacheModulePlugin.java
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/RenderSearchTemplateAction.java
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/RestRenderSearchTemplateAction.java
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/TransportRenderSearchTemplateAction.java
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/TransportSearchTemplateAction.java
Labels: v2.2.0

#11594 Add release notes for 1.3.14 (#11592)
  release-notes/opensearch.release-notes-1.3.14.md
Labels: skip-changelog

#11585 Add heuristic slice_size for slice level top buckets in concurrent segment search
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
Labels: enhancement, backport 2.x, skip-changelog, Search:Performance

#11599 [2.x] Add bwc version 1.3.15
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#11534 Convert issue and bug templates to use forms
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/bug_template.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/add-untriaged.yml
  .github/workflows/triage.yml
Labels: enhancement, skip-changelog

#11620 [Backport 2.x] Add heuristic slice_size for slice level top buckets in concurrent segment search (#11585)
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
Labels: skip-changelog

#11600 Personalize code ownership areas
  .github/CODEOWNERS
Labels: bug, RFC, skip-changelog

#11618 Fix regex in triage.yml to support label names with spaces
  .github/workflows/triage.yml
Labels: skip-changelog

#11622 [Backport 2.x] Personalize code ownership areas (#11600)
  .github/CODEOWNERS
Labels: skip-changelog

#11487 Fix flaky test of IndexShardTests.testRestoreLocalHistoryFromTranslogOnPromotion
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Labels: bug, distributed framework, flaky-test, skip-changelog

#11612 Fix automatic addition of protocol in discovery endpoint
  CHANGELOG.md
  plugins/discovery-ec2/src/main/java/org/opensearch/discovery/ec2/AwsEc2ServiceImpl.java
  plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/AwsEc2ServiceImplTests.java
Labels: bug, backport 2.x, Other

#11591 Add additional handling in SearchTemplateRequest when simulate is set to true
  CHANGELOG.md
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/SearchTemplateRequest.java
  modules/lang-mustache/src/test/java/org/opensearch/script/mustache/SearchTemplateRequestTests.java
Labels: v2.2.0

#11647 Bump actions/upload-artifact from 3 to 4
  .github/workflows/check-compatibility.yml
Labels: bug, skip-changelog, Other

#11651 Add context for custom GC tunings
  distribution/src/config/jvm.options
Labels: enhancement, backport 2.x, skip-changelog, Indexing:Performance, Search:Performance

#11661 Remove unused java11 gradle configuration
  server/build.gradle
Labels: backport 2.x, skip-changelog

#11659 Change visibility of action constructor (public -> private)
  server/src/main/java/org/opensearch/action/admin/cluster/remote/RemoteInfoAction.java
  server/src/main/java/org/opensearch/action/main/MainAction.java
Labels: skip-changelog

#11665 Remove unused java11 gradle configuration from lib/core
  libs/core/build.gradle
Labels: backport 2.x, skip-changelog

#11674 Fix flaky testPostFilterDisablesCountOptimization with concurrent search enabled
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Search
