Repository opensearch-project/OpenSearch, pull requests merged in 2023-01, with the labels that each got.

#5231 Adding core changes for API to check per awareness attribute health
  server/src/main/java/org/opensearch/cluster/awarenesshealth/ClusterAwarenessAttributeValueHealth.java
  server/src/main/java/org/opensearch/cluster/awarenesshealth/ClusterAwarenessAttributesHealth.java
  server/src/main/java/org/opensearch/cluster/awarenesshealth/ClusterAwarenessHealth.java
  server/src/main/java/org/opensearch/cluster/awarenesshealth/package-info.java
  server/src/test/java/org/opensearch/cluster/awarenesshealth/ClusterAwarenessAttributeValueHealthTests.java
  server/src/test/java/org/opensearch/cluster/awarenesshealth/ClusterAwarenessAttributesHealthSerializationTests.java
  server/src/test/java/org/opensearch/cluster/awarenesshealth/ClusterAwarenessAttributesHealthTests.java
  server/src/test/java/org/opensearch/cluster/awarenesshealth/ClusterAwarenessHealthTests.java
Labels: skip-changelog

#5681 Fix Flaky test org.opensearch.index.IndexServiceTests.testAsyncTranslogTrimTaskOnClosedIndex
  server/src/test/java/org/opensearch/index/IndexServiceTests.java
Labels: skip-changelog

#5607 Validate attributes of routing nodes for Routing Weights API
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/put/ClusterPutWeightedRoutingRequest.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
  server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingService.java
  server/src/test/java/org/opensearch/action/admin/cluster/shards/routing/weighted/put/ClusterPutWeightedRoutingRequestTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
  server/src/test/java/org/opensearch/cluster/routing/WeightedRoutingServiceTests.java
Labels: skip-changelog

#5691 [Backport 2.x] Validate attributes of routing nodes for Routing Weights API
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/put/ClusterPutWeightedRoutingRequest.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
  server/src/main/java/org/opensearch/cluster/routing/WeightedRoutingService.java
  server/src/test/java/org/opensearch/action/admin/cluster/shards/routing/weighted/put/ClusterPutWeightedRoutingRequestTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
  server/src/test/java/org/opensearch/cluster/routing/WeightedRoutingServiceTests.java
Labels: skip-changelog

#5649 [Remote Translog] Add support for downloading files from remote translog
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#5667 Add additional logging for future debugging of HA proxy mode flaky test
  qa/remote-clusters/src/test/java/org/opensearch/cluster/remote/test/RemoteClustersIT.java
Labels: skip-changelog

#5695 Adding @gbbafna to code owners
  .github/CODEOWNERS
Labels: backport 2.x, skip-changelog

#5700 Muting flaky SegmentReplication ITs.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
Labels: skip-changelog

#5717 Updated MAINTAINERS.md format.
  MAINTAINERS.md
Labels: skip-changelog

#5714 Mute flaky test testStartReplicaAfterPrimaryIndexesDocs.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: skip-changelog

#5737 Fix TransportReplicationActionTests
  server/src/test/java/org/opensearch/action/support/replication/TransportReplicationActionTests.java
Labels: skip-changelog

#5739 [Segment Replication] Mute flaky tests
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
Labels: skip-changelog

#5722 Fix flaky Segment Replication test testStartReplicaAfterPrimaryIndexesDocs.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: skip-changelog

#5742 [Segment Replication] Mute flaky tests
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
Labels: skip-changelog

#5744 Bumping 2.x to 2.6
  .ci/bwcVersions
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog, v2.6.0

#5745 Adding 2.6 to bwc versions
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog, v2.6.0

#5725 [Backport 2.x] Adding @gbbafna to code owners (#5695)
  .github/CODEOWNERS
Labels: skip-changelog

#5731 [Backport 2.x] Support no-op replication for remote-backed indexes
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/action/support/replication/FanoutReplicationProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationMode.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationModeAwareProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationOperation.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationProxyRequest.java
  server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoverySourceService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandlerFactory.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/test/java/org/opensearch/action/admin/indices/close/TransportVerifyShardBeforeCloseActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/flush/TransportShardFlushActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/readonly/TransportVerifyShardIndexBlockActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/refresh/TransportShardRefreshActionTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
  server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
  server/src/test/java/org/opensearch/action/support/replication/ReplicationOperationTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportReplicationActionTests.java
  server/src/test/java/org/opensearch/index/seqno/GlobalCheckpointSyncActionTests.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTestCase.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseBackgroundSyncActionTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseSyncActionTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#5753 [Backport 2.5] Adding @gbbafna to code owners
  .github/CODEOWNERS
Labels: skip-changelog

#5434 Updated the release notes to include the fix for CVE-2022-41917.
  release-notes/opensearch.release-notes-2.4.0.md
Labels: skip-changelog

#5774 [Backport 2.5] Support no-op replication for remote-backed indexes
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/action/support/replication/FanoutReplicationProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationMode.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationModeAwareProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationOperation.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationProxy.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationProxyRequest.java
  server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoverySourceService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandlerFactory.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/test/java/org/opensearch/action/admin/indices/close/TransportVerifyShardBeforeCloseActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/flush/TransportShardFlushActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/readonly/TransportVerifyShardIndexBlockActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/refresh/TransportShardRefreshActionTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
  server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
  server/src/test/java/org/opensearch/action/support/replication/ReplicationOperationTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportReplicationActionTests.java
  server/src/test/java/org/opensearch/index/seqno/GlobalCheckpointSyncActionTests.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTestCase.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseBackgroundSyncActionTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseSyncActionTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#5662 [Remote Translog] Trimming based on remote segment upload and cleaning older tlog files
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/listener/FileTransferListener.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#5793 [Backport 2.5][Remote Translog] Trimming based on remote segment upload and cleanin…
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/listener/FileTransferListener.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#5794 [2.x] Changing min version required for Awareness health api to 2.5
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
Labels: skip-changelog

#5792 [Backport 2.x] [Remote Translog] Trimming based on remote segment upload and cleanin…
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/listener/FileTransferListener.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#5789 [Remote Translog] Reduce number of operations in testConcurrentWriteViewsAndSnapshot
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
Labels: skip-changelog

#5542 Gracefully handle concurrent zone decommission action
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/put/DecommissionRequestBuilder.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionAttributeMetadata.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionController.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionHelper.java
  server/src/main/java/org/opensearch/cluster/decommission/DecommissionService.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionControllerTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionHelperTests.java
  server/src/test/java/org/opensearch/cluster/decommission/DecommissionServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/DecommissionAttributeMetadataSerializationTests.java
  server/src/test/java/org/opensearch/cluster/metadata/DecommissionAttributeMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/DecommissionAttributeMetadataXContentTests.java
  server/src/test/java/org/opensearch/cluster/routing/WeightedRoutingServiceTests.java
Labels: roadmap, v2.5.0

#5808 [Bug] Send replicated boolean on supported versions
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
Labels: skip-changelog, backport 2.5

#5809 [Bug] Update logic on CheckpointState around serialization/deserialization
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
Labels: skip-changelog

#5816 Add v2.5.0 release notes
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.5.0.md
Labels: backport 2.5

#5820 Update release notes
  release-notes/opensearch.release-notes-2.5.0.md
Labels: skip-changelog

#5821 [Backport 2.5] Add release notes for v2.5.0
  release-notes/opensearch.release-notes-2.5.0.md
Labels: skip-changelog

#5817 [Bug] Update test to consider OS version > 2.5.0 where extra field added into BytesStreamOutput
  server/src/test/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponsesTests.java
Labels: skip-changelog, backport 2.5

#5828 Reduce number of operations in RemoteFSTranslogTests.testConcurrentWr…
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
Labels: skip-changelog

#5513 [Feature/Identity] Identity use cases
  IDENTITY_USE_CASES.md
Labels: skip-changelog, Identity

#5839 Update release notes for v2.5
  release-notes/opensearch.release-notes-2.5.0.md
Labels: backport 2.x, skip-changelog, backport 2.5

#5847 Update changelog post release
  CHANGELOG.md
Labels: skip-changelog

#5777 Upgrading Jettison due to CVE-2022-45685
  CHANGELOG.md
  buildSrc/version.properties
  plugins/discovery-azure-classic/licenses/jettison-1.5.1.jar.sha1
  plugins/discovery-azure-classic/licenses/jettison-1.5.3.jar.sha1
Labels: CVE, >upgrade, dependencies, backport 2.x, backport 2.5

#5831 [Segment Replication] Adding check to avoid parallel replication events taking place
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
Labels: skip-changelog

#5868 [Remote Translog] Use InputStream that supports mark and reset while uploading translog files
  server/src/main/java/org/opensearch/index/translog/transfer/FileSnapshot.java
  server/src/test/java/org/opensearch/index/translog/transfer/FileSnapshotTests.java
Labels: skip-changelog

#5833 Removed unnecessary use of Long.toString from BlobStoreRepository.
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: skip-changelog

#5804 Handle translog upload during primary relocation for remote-backed indexes
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/TranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
Labels: distributed framework, durability, skip-changelog, v2.6.0

#5914 [Backport 2.x] Add builder for EngineConfig (#5618)
  server/src/internalClusterTest/java/org/opensearch/indices/IndexingMemoryControllerIT.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
  server/src/test/java/org/opensearch/indices/IndexingMemoryControllerTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Labels: skip-changelog

#5861 [Backport 2.x] Add query for initialized extensions
  CHANGELOG.md
  server/src/main/java/org/opensearch/extensions/DiscoveryExtensionNode.java
  server/src/main/java/org/opensearch/extensions/ExtensionDependencyResponse.java
  server/src/main/java/org/opensearch/extensions/ExtensionRequest.java
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
Labels: backport, extensions

#5922 Backporting unit tests for IndexMetadataGenerations and a javadoc fix from #5812
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/test/java/org/opensearch/repositories/IndexMetadataGenerationsTests.java
Labels: skip-changelog

#5924 Muting TranslogTransferManagerTests on Windows.
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#5928 [Segment Replication] Mute flaky SegmentReplicationIT.testCancelPrimaryAllocation
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: skip-changelog

#5931 Fix strict weighted routing integ test failure
  server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
Labels: skip-changelog

#5927 Add artifacts from benchmarks to .gitignore
  .gitignore
Labels: skip-changelog

#5937 Enable SearchableSnapshotIT to run during build
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
Labels: backport 2.x, skip-changelog

#5940 Apply OpenSearchIntegTestCase::featureFlagSettings by default
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#5942 Fix CHANGELOG on main
  CHANGELOG.md
Labels: skip-changelog

#5945 [Backport 2.x] Backport SegmentReplication test muting missing from 2.x.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: skip-changelog

#5944 [Backport 2.x] Apply OpenSearchIntegTestCase::featureFlagSettings by default (#5940)
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#5964 Fix dependabot changelog plugin version
  .github/workflows/dependabot_pr.yml
Labels: skip-changelog

#5979 Create an issue if an on push gradle check fails.
  .github/ISSUE_TEMPLATE/failed_check.md
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#5997 Add condition that PRs are merged in backport workflow
  .github/workflows/backport.yml
Labels: backport 2.x, skip-changelog

#6001 Added bwc version 2.5.1
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#5996 [BUG] javadoc warnings not causing failures
  build.gradle
  modules/lang-painless/build.gradle
  server/src/main/java/org/opensearch/index/fielddata/ScriptDocValues.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: Build Libraries & Interfaces, backport 2.x, skip-changelog

#6002 [Backport 2.x] Add condition that PRs are merged in backport workflow (#5997)
  .github/workflows/backport.yml
Labels: skip-changelog

#6015 Fix flaky SegmentReplicationITs.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
Labels: skip-changelog

#5970 Add method to Engine to fetch max seq no of given SegmentInfos
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: skip-changelog

#5918 Fix assertion failures in creation and deletion of remote store backed index
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: skip-changelog

#6047 [Backport 2.x] Reconcile DEVELOPER_GUIDE.md
  DEVELOPER_GUIDE.md
Labels: skip-changelog

#5952 Fix flaky test cases for DiskThresholdDeciderIT
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
Labels: skip-changelog

#6049 [Segment Replication] Log diff.different files for debuggability
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
Labels: skip-changelog

#5898 [Segment Replication] Update force segment replication round to be synchronous
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTargetHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/indices/recovery/AsyncRecoveryTarget.java
Labels: skip-changelog

#6055 [Segment Replication] Backport PRs from main
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTargetHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/indices/recovery/AsyncRecoveryTarget.java
Labels: skip-changelog

#5854 Batch translog sync/upload per x ms for remote-backed indexes
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/common/util/concurrent/AsyncIOProcessor.java
  server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: distributed framework, durability, skip-changelog, Performance, v2.6.0

#6063 Refactor buffer interval code for remote-backed indexes
  server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
Labels: durability, skip-changelog, v2.6.0

#6064 [Backport 2.x] Handle translog upload during primary relocation for remote-backed indexes (#5804)
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/TranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
Labels: skip-changelog

#6066 [Backport 2.x] Batch translog sync/upload per x ms for remote-backed indexes (#5854)
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/common/util/concurrent/AsyncIOProcessor.java
  server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: skip-changelog

#6075 OpenJDK Update (January 2023 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Labels: Build Libraries & Interfaces

#6074 OpenJDK Update (January 2023 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: Build Libraries & Interfaces

#6079 [Segment Replication] Mute testRelocateWhileContinuouslyIndexingAndWaitingForRefresh which …
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
Labels: skip-changelog

#6076 Bumps Mockito from 4.7.0 to 5.1.0, ByteBuddy from 1.12.18 to 1.12.22
  CHANGELOG.md
  buildSrc/version.properties
  client/rest/build.gradle
  client/sniffer/build.gradle
Labels: Build Libraries & Interfaces

#6081 Fix broken template for issue autocuts on GH failure.
  .github/ISSUE_TEMPLATE/failed_check.md
Labels: skip-changelog

#6077 OpenJDK Update (January 2023 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: Build Libraries & Interfaces

#6092 Fix autocut on GC failure caused by >test-failure label.
  .github/ISSUE_TEMPLATE/failed_check.md
Labels: skip-changelog

#6093 [Backport] [1.x] OpenJDK Update (January 2023 Patch releases)
  buildSrc/version.properties
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Labels: skip-changelog

#6098 Remove CI related changelog entry.
  CHANGELOG.md
Labels: skip-changelog

#6097 [Backport 2.x] build: harden worfklows permissions (#4587)
  .github/workflows/gradle-check.yml
  .github/workflows/links.yml
  .github/workflows/version.yml
Labels: skip-changelog

#6095 [Backport] [2.x] Update Joda to 2.12.2 (#6083)
  CHANGELOG.md
  buildSrc/version.properties
  server/licenses/joda-time-2.10.12.jar.sha1
  server/licenses/joda-time-2.12.2.jar.sha1
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Labels: dependencies

#6096 [Backport] [2.5] Update Joda to 2.12.2 (#6083)
  CHANGELOG.md
  buildSrc/version.properties
  server/licenses/joda-time-2.10.12.jar.sha1
  server/licenses/joda-time-2.12.2.jar.sha1
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Labels: dependencies

#6099 Move dependency updates that have been backported
  CHANGELOG.md
Labels: skip-changelog

#6101 [Extensions] Changing ExtensionActionRequest streaminput constructor to be public
  server/src/main/java/org/opensearch/extensions/action/ExtensionActionRequest.java
Labels: skip-changelog

#6100 Fix AUTOCUT title formatting in failed_check.md
  .github/ISSUE_TEMPLATE/failed_check.md
Labels: skip-changelog

#6078 [Upgrade] Lucene 9.5.0 release
  CHANGELOG.md
  buildSrc/version.properties
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/HighlighterWithAnalyzersTests.java
  modules/lang-expression/licenses/lucene-expressions-9.5.0-snapshot-0878271.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.5.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.5.0-snapshot-0878271.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.5.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.5.0-snapshot-0878271.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.5.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.5.0-snapshot-0878271.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.5.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.5.0-snapshot-0878271.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.5.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.5.0-snapshot-0878271.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.5.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.5.0-snapshot-0878271.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.5.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.5.0-snapshot-0878271.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.5.0.jar.sha1
  server/licenses/lucene-analysis-common-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-analysis-common-9.5.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-backward-codecs-9.5.0.jar.sha1
  server/licenses/lucene-core-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-core-9.5.0.jar.sha1
  server/licenses/lucene-grouping-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-grouping-9.5.0.jar.sha1
  server/licenses/lucene-highlighter-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-highlighter-9.5.0.jar.sha1
  server/licenses/lucene-join-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-join-9.5.0.jar.sha1
  server/licenses/lucene-memory-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-memory-9.5.0.jar.sha1
  server/licenses/lucene-misc-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-misc-9.5.0.jar.sha1
  server/licenses/lucene-queries-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-queries-9.5.0.jar.sha1
  server/licenses/lucene-queryparser-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-queryparser-9.5.0.jar.sha1
  server/licenses/lucene-sandbox-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-sandbox-9.5.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-spatial-extras-9.5.0.jar.sha1
  server/licenses/lucene-spatial3d-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-spatial3d-9.5.0.jar.sha1
  server/licenses/lucene-suggest-9.5.0-snapshot-0878271.jar.sha1
  server/licenses/lucene-suggest-9.5.0.jar.sha1
  server/src/main/java/org/opensearch/common/lucene/search/MultiPhrasePrefixQuery.java
  server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java
Labels: non-issue, >upgrade, backport 2.x, skip-changelog, v2.6.0

#5469 Documentation for in-process authentication state
  sandbox/libs/authn/docs/auth_flow.md
Labels: skip-changelog, Identity

#6113 [Segment Replication] Mute SegmentRelocationITs failing/flaky on CI
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
Labels: skip-changelog

#6118 Fix Apache Lucene version for 2.6.0
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog
