Repository opensearch-project/OpenSearch, pull requests merged in 2023-07, with the labels that each got.

#8391 Avoid search_after short cutting in case of missing is specified
  rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
Labels: skip-changelog

#8314 [Remote Store] Add method in BlobContainer to fetch the keys in sorted order
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  server/src/main/java/org/opensearch/common/blobstore/BlobContainer.java
  server/src/test/java/org/opensearch/common/blobstore/fs/FsBlobContainerTests.java
Labels: skip-changelog

#8413 [2.x] Added bwc version 1.3.12
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#8412 [Remote Store] Add remote store utils useful to name metadata files
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
Labels: skip-changelog

#8410 [Backport 2.x] [Remote Store] Optimize segments metadata upload (#7905)
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
Labels: skip-changelog

#8409 [Backport 2.x] Make remote translog upload buffer interval setting dynamic (#8175)
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexTranslogDisabledIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
  server/src/test/java/org/opensearch/index/IndexServiceTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
Labels: skip-changelog

#8422 Fix flaky tests in restore flow using snapshot interop
  server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
Labels: skip-changelog

#8425 [Backport 2.x] Add method in BlobContainer to fetch the keys in sorted order
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  server/src/main/java/org/opensearch/common/blobstore/BlobContainer.java
  server/src/test/java/org/opensearch/common/blobstore/fs/FsBlobContainerTests.java
Labels: skip-changelog

#8432 [Backport 2.] Avoid search_after short cutting in case of missing is specified (#8391)
  rest-api-spec/src/main/resources/rest-api-spec/test/search/90_search_after.yml
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
Labels: skip-changelog

#8434 Update Apache HttpCore/ HttpClient and Apache HttpCore5 / HttpClient5 dependencies
  CHANGELOG.md
  buildSrc/version.properties
  client/rest/licenses/httpclient5-5.1.4.jar.sha1
  client/rest/licenses/httpclient5-5.2.1.jar.sha1
  client/rest/licenses/httpcore5-5.1.5.jar.sha1
  client/rest/licenses/httpcore5-5.2.2.jar.sha1
  client/rest/licenses/httpcore5-h2-5.1.5.jar.sha1
  client/rest/licenses/httpcore5-h2-5.2.2.jar.sha1
  client/sniffer/licenses/httpclient5-5.1.4.jar.sha1
  client/sniffer/licenses/httpclient5-5.2.1.jar.sha1
  client/sniffer/licenses/httpcore5-5.1.5.jar.sha1
  client/sniffer/licenses/httpcore5-5.2.2.jar.sha1
  plugins/discovery-azure-classic/licenses/httpclient-4.5.13.jar.sha1
  plugins/discovery-azure-classic/licenses/httpclient-4.5.14.jar.sha1
  plugins/discovery-azure-classic/licenses/httpcore-4.4.15.jar.sha1
  plugins/discovery-azure-classic/licenses/httpcore-4.4.16.jar.sha1
  plugins/discovery-ec2/licenses/httpclient-4.5.13.jar.sha1
  plugins/discovery-ec2/licenses/httpclient-4.5.14.jar.sha1
  plugins/discovery-ec2/licenses/httpcore-4.4.15.jar.sha1
  plugins/discovery-ec2/licenses/httpcore-4.4.16.jar.sha1
  plugins/discovery-gce/licenses/httpclient-4.5.13.jar.sha1
  plugins/discovery-gce/licenses/httpclient-4.5.14.jar.sha1
  plugins/discovery-gce/licenses/httpcore-4.4.15.jar.sha1
  plugins/discovery-gce/licenses/httpcore-4.4.16.jar.sha1
  plugins/repository-s3/licenses/httpclient-4.5.13.jar.sha1
  plugins/repository-s3/licenses/httpclient-4.5.14.jar.sha1
  plugins/repository-s3/licenses/httpcore-4.4.15.jar.sha1
  plugins/repository-s3/licenses/httpcore-4.4.16.jar.sha1
Labels: dependencies

#8406 [Remote translog] Add integration tests for primary term validation
  server/src/internalClusterTest/java/org/opensearch/remotestore/PrimaryTermValidationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
Labels: :test, durability, skip-changelog, v2.9.0

#8441 [Remote Store + Segment Replication] Fix flaky test org.opensearch.remotestore.SegmentReplicationUsingRemoteStoreIT.testNodeDropWithOngoingReplication
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: backport 2.x, skip-changelog

#8436 [Backport] [2.x] Update Apache HttpCore / HttpClient dependencies (#8434)
  CHANGELOG.md
  buildSrc/version.properties
  client/rest/licenses/httpclient-4.5.13.jar.sha1
  client/rest/licenses/httpclient-4.5.14.jar.sha1
  client/rest/licenses/httpcore-4.4.15.jar.sha1
  client/rest/licenses/httpcore-4.4.16.jar.sha1
  client/rest/licenses/httpcore-nio-4.4.15.jar.sha1
  client/rest/licenses/httpcore-nio-4.4.16.jar.sha1
  client/sniffer/licenses/httpclient-4.5.13.jar.sha1
  client/sniffer/licenses/httpclient-4.5.14.jar.sha1
  client/sniffer/licenses/httpcore-4.4.15.jar.sha1
  client/sniffer/licenses/httpcore-4.4.16.jar.sha1
  plugins/discovery-azure-classic/licenses/httpclient-4.5.13.jar.sha1
  plugins/discovery-azure-classic/licenses/httpclient-4.5.14.jar.sha1
  plugins/discovery-azure-classic/licenses/httpcore-4.4.15.jar.sha1
  plugins/discovery-azure-classic/licenses/httpcore-4.4.16.jar.sha1
  plugins/discovery-ec2/licenses/httpclient-4.5.13.jar.sha1
  plugins/discovery-ec2/licenses/httpclient-4.5.14.jar.sha1
  plugins/discovery-ec2/licenses/httpcore-4.4.15.jar.sha1
  plugins/discovery-ec2/licenses/httpcore-4.4.16.jar.sha1
  plugins/discovery-gce/licenses/httpclient-4.5.13.jar.sha1
  plugins/discovery-gce/licenses/httpclient-4.5.14.jar.sha1
  plugins/discovery-gce/licenses/httpcore-4.4.15.jar.sha1
  plugins/discovery-gce/licenses/httpcore-4.4.16.jar.sha1
  plugins/repository-s3/licenses/httpclient-4.5.13.jar.sha1
  plugins/repository-s3/licenses/httpclient-4.5.14.jar.sha1
  plugins/repository-s3/licenses/httpcore-4.4.15.jar.sha1
  plugins/repository-s3/licenses/httpcore-4.4.16.jar.sha1
Labels: backport

#7957 Support transport action names when registering NamedRoutes
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/extensions/rest/RestInitializeExtensionAction.java
  server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
  server/src/main/java/org/opensearch/extensions/rest/RouteHandler.java
  server/src/main/java/org/opensearch/rest/NamedRoute.java
  server/src/test/java/org/opensearch/action/DynamicActionRegistryTests.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java
  server/src/test/java/org/opensearch/extensions/rest/RouteHandlerTests.java
  server/src/test/java/org/opensearch/rest/NamedRouteTests.java
Labels: backport, backport 2.x, v2.9.0

#8376 [Backport 2.x] [Search Pipelines] Add stats for search pipelines
  CHANGELOG.md
  modules/ingest-common/src/internalClusterTest/java/org/opensearch/ingest/common/IngestRestartIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/common/metrics/MeanMetric.java
  server/src/main/java/org/opensearch/common/metrics/OperationMetrics.java
  server/src/main/java/org/opensearch/common/metrics/OperationStats.java
  server/src/main/java/org/opensearch/ingest/CompoundProcessor.java
  server/src/main/java/org/opensearch/ingest/ConditionalProcessor.java
  server/src/main/java/org/opensearch/ingest/IngestMetric.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/ingest/IngestStats.java
  server/src/main/java/org/opensearch/ingest/Pipeline.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
  server/src/main/java/org/opensearch/search/pipeline/PipelineWithMetrics.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineStats.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodesTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  server/src/test/java/org/opensearch/ingest/CompoundProcessorTests.java
  server/src/test/java/org/opensearch/ingest/ConditionalProcessorTests.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
  server/src/test/java/org/opensearch/ingest/IngestStatsTests.java
  server/src/test/java/org/opensearch/ingest/PipelineProcessorTests.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineStatsTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: Priority-High, v2.9.0

#8416 [Search Pipelines] Changing Version Check to 2.9
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
Labels: skip-changelog, v2.9.0

#8457 [Backport 2.x] [Refactor] Stream Reader and Write Generics (#7465)
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/common/io/stream/BaseStreamInput.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/BaseStreamOutput.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/BaseWriteable.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/package-info.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/InternalGeoGrid.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/InternalGeoHashGrid.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/InternalGeoTileGrid.java
  server/src/main/java/org/opensearch/common/geo/GeoBoundingBox.java
  server/src/main/java/org/opensearch/common/geo/GeoPoint.java
  server/src/main/java/org/opensearch/common/io/stream/StreamInput.java
  server/src/main/java/org/opensearch/common/io/stream/StreamOutput.java
  server/src/main/java/org/opensearch/common/io/stream/Writeable.java
  server/src/main/java/org/opensearch/index/query/GeoDistanceQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/GeoPolygonQueryBuilder.java
  server/src/main/java/org/opensearch/script/JodaCompatibleZonedDateTime.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/common/io/stream/BaseStreamTests.java
  server/src/test/java/org/opensearch/common/io/stream/BytesStreamsTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: enhancement, backport, v2.9.0

#8458 Unmute remote store test testPressureServiceStats
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
Labels: skip-changelog

#8475 Add logs to debug NoSuchFileException during segments upload
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
Labels: durability, skip-changelog

#8363 [Remote Segment Store] Make metadata file immutable
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/test/java/org/opensearch/common/blobstore/fs/FsBlobContainerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: skip-changelog

#8431 Flaky test: Add condition to ensure data correctness on primary promotion
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: skip-changelog

#8200 [Segment Replication] Remove Restriction of strictly using only docrep for system indices and hidden indices
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: skip-changelog

#8502 [Backport 2.x] [Segment Replication] Remove Restriction of strictly using only docrep for system indices and hidden indices
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: skip-changelog

#8164 [Search pipelines] Pass "adhocness" flag to processor factories
  CHANGELOG.md
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/RenameFieldResponseProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/ScriptRequestProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessorTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/RenameFieldResponseProcessorTests.java
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/50_script_processor.yml
  server/src/main/java/org/opensearch/plugins/SearchPipelinePlugin.java
  server/src/main/java/org/opensearch/search/pipeline/PipelineWithMetrics.java
  server/src/main/java/org/opensearch/search/pipeline/Processor.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: Search, v2.9.0

#8018 Update to Gradle 8.2
  benchmarks/build.gradle
  build.gradle
  buildSrc/build.gradle
  buildSrc/reaper/build.gradle
  buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
  buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ForbiddenPatternsTask.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/LoggerUsageTask.java
  buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestApiTask.java
  buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestTestsTask.java
  buildSrc/src/main/java/org/opensearch/gradle/util/GradleUtils.java
  buildSrc/src/main/java/org/opensearch/gradle/util/Util.java
  client/benchmark/build.gradle
  client/rest-high-level/build.gradle
  client/rest/build.gradle
  client/sniffer/build.gradle
  client/test/build.gradle
  distribution/archives/integ-test-zip/build.gradle
  distribution/tools/java-version-checker/build.gradle
  distribution/tools/launchers/build.gradle
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/upgrade-cli/build.gradle
  doc-tools/build.gradle
  gradle.properties
  gradle/code-coverage.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  libs/common/build.gradle
  libs/core/build.gradle
  modules/lang-painless/build.gradle
  modules/lang-painless/spi/build.gradle
  server/build.gradle
  settings.gradle
Labels: Build Libraries & Interfaces, skip-changelog

#7997 Enable Partial Flat Object
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/100_partial_flat_object.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/105_partial_flat_object_nested.yml
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java
Labels: Search

#7496 Add Changes in Snapshot Clone Flow for remote store interoperability.
  server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
  server/src/main/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshot.java
  server/src/main/java/org/opensearch/index/store/lockmanager/FileLockInfo.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManager.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManager.java
  server/src/main/java/org/opensearch/repositories/FilterRepository.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/index/store/lockmanager/FileLockInfoTests.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
  test/framework/src/main/java/org/opensearch/index/shard/RestoreOnlyRepository.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: skip-changelog

#8512 [Backport 2.x] [Search Pipelines] Adding the SearchPhaseResultsProcessor interface in Search Pipeline
  CHANGELOG.md
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/50_script_processor.yml
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/ArraySearchPhaseResults.java
  server/src/main/java/org/opensearch/action/search/CanMatchPreFilterSearchPhase.java
  server/src/main/java/org/opensearch/action/search/DfsQueryPhase.java
  server/src/main/java/org/opensearch/action/search/ExpandSearchPhase.java
  server/src/main/java/org/opensearch/action/search/FetchSearchPhase.java
  server/src/main/java/org/opensearch/action/search/SearchPhase.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseContext.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseName.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseResults.java
  server/src/main/java/org/opensearch/action/search/SearchScrollAsyncAction.java
  server/src/main/java/org/opensearch/action/search/SearchScrollQueryThenFetchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/plugins/SearchPipelinePlugin.java
  server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
  server/src/main/java/org/opensearch/search/pipeline/PipelineWithMetrics.java
  server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPhaseResultsProcessor.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: backport, Search, v2.9.0

#8516 [Remote Segment Store] Mute testStaleCommitDeletion test cases
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
Labels: skip-changelog

#8350 [Remote Store] Update Translog Metadata file name
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#8145 [Extensions] Change extension integration testing to reflect new initialization sequence
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
Labels: backport 2.x, skip-changelog

#8542 [Remote Store] Mute testRemoteRefreshRetryOnFailure test case
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
Labels: skip-changelog

#8546 [Backport 2.x][Remote Store] Update Translog Metadata file name (#8350)
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#8463 [Segment Replication] Prevent store clean up post reader close and refactor
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/indices/recovery/MultiFileWriter.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/index/store/StoreTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#8547 Fix flakyness in RemoteStoreRefreshListenerIT
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
Labels: skip-changelog

#8459 [Backport 2.x] Support transport action names when registering NamedRoutes (#7957)
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/extensions/rest/RestInitializeExtensionAction.java
  server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
  server/src/main/java/org/opensearch/extensions/rest/RouteHandler.java
  server/src/main/java/org/opensearch/rest/NamedRoute.java
  server/src/test/java/org/opensearch/action/DynamicActionRegistryTests.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java
  server/src/test/java/org/opensearch/extensions/rest/RouteHandlerTests.java
  server/src/test/java/org/opensearch/rest/NamedRouteTests.java
Labels: v2.9.0

#8550 Fix flakyness in RemoteStoreRefreshListenerTests
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#8523 [Remote Segment Store] Fix flaky RemoteStoreIT.testStaleCommitDeletion tests
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
Labels: skip-changelog

#8505 Extend existing IndexRecoveryIT for remote indexes
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexRecoveryIT.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: durability, skip-changelog

#8564 Fix methods in InternalEngine to access translog methods via TranslogManager
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
Labels: skip-changelog

#8208 Add safeguard limits for file cache during node level allocation
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterInfoServiceIT.java
  server/src/main/java/org/opensearch/cluster/ClusterInfo.java
  server/src/main/java/org/opensearch/cluster/InternalClusterInfoService.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/test/java/org/opensearch/cluster/ClusterInfoTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitorTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/IndexShardConstraintDeciderOverlapTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderUnitTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: backport 2.x

#7855 replace with getField
  CHANGELOG.md
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/30_search.yml
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
Labels: v2.9.0

#8588 [Backport 2.x] Change extension integration testing to reflect new initialization sequence (#8145)
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
Labels: skip-changelog, v2.9.0

#8580 Update Gradle to 8.2.1
  buildSrc/build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Build Libraries & Interfaces, skip-changelog

#8601 add jdk.incubator.vector module support for JDK 20+
  CHANGELOG.md
  build.gradle
  distribution/src/config/jvm.options
Labels: enhancement, non-issue, v2.10.0

#8591 Fix CodecTests
  server/src/test/java/org/opensearch/index/codec/CodecTests.java
Labels: skip-changelog

#8522 [Search pipelines] Pass "adhocness" flag to processor factories (#8164)
  CHANGELOG.md
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/RenameFieldResponseProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/ScriptRequestProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessorTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/RenameFieldResponseProcessorTests.java
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/50_script_processor.yml
  server/src/main/java/org/opensearch/plugins/SearchPipelinePlugin.java
  server/src/main/java/org/opensearch/search/pipeline/PipelineWithMetrics.java
  server/src/main/java/org/opensearch/search/pipeline/Processor.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: v2.9.0

#8288 Disabled translog fsync in remote store path
  server/src/main/java/org/opensearch/index/translog/Checkpoint.java
  server/src/main/java/org/opensearch/index/translog/TranslogHeader.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
  server/src/test/java/org/opensearch/index/translog/LocalTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogHeaderTests.java
Labels: skip-changelog

#7495 [Snapshot Interop] Add Changes in Snapshot Status Flow for remote sto…
  modules/repository-url/src/main/java/org/opensearch/common/blobstore/url/URLBlobContainer.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
  server/src/main/java/org/opensearch/index/snapshots/blobstore/BlobStoreIndexShardSnapshot.java
  server/src/main/java/org/opensearch/index/snapshots/blobstore/IndexShardSnapshot.java
  server/src/main/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshot.java
  server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectoryFactory.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: skip-changelog

#8420 [Backport 2.x] Fix SegmentReplication flaky integ tests
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#8545 [Backport 2.x] [Remote Segment Store] Make metadata file immutable (#8363)
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/test/java/org/opensearch/common/blobstore/fs/FsBlobContainerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: skip-changelog

#7119 [Remote Store] Add multipart upload integration for translog and segment files
  libs/common/src/main/java/org/opensearch/common/io/InputStreamContainer.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartFileCorruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsBlobStore.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsRepository.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsRepositoryPlugin.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsVerifyingBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/VerifyingMultiStreamBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainer.java
  server/src/main/java/org/opensearch/common/util/ByteUtils.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/exception/ChecksumCombinationException.java
  server/src/main/java/org/opensearch/index/translog/Checkpoint.java
  server/src/main/java/org/opensearch/index/translog/TranslogCheckedContainer.java
  server/src/main/java/org/opensearch/index/translog/TranslogHeader.java
  server/src/main/java/org/opensearch/index/translog/TranslogReader.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/main/java/org/opensearch/index/translog/checked/package-info.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/FileSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/TestUploadListener.java
  server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceMockRepositoryTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/FileSnapshotTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/FileTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#8626 [Mute] flaky RemoteStoreRefreshListenerTests
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#8618 Add logs for remote store metadata intermittent read failures
  server/src/main/java/org/opensearch/common/io/VersionedCodecStreamWrapper.java
Labels: skip-changelog

#8478 Fix bug where ReplicationListeners would not complete on cancellation.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationSuiteIT.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationState.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationCollection.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  server/src/test/java/org/opensearch/recovery/ReplicationCollectionTests.java
Labels: backport 2.x, skip-changelog

#8307 Bump org.apache.logging.log4j:log4j-core from 2.17.1 to 2.20.0
  .gitignore
  CHANGELOG.md
  buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle
  buildSrc/version.properties
  libs/core/licenses/log4j-api-2.17.1.jar.sha1
  libs/core/licenses/log4j-api-2.20.0.jar.sha1
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.17.1.jar.sha1
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.20.0.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.17.1.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.20.0.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.17.1.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.20.0.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.17.1.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.20.0.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.17.1.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.20.0.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.17.1.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.20.0.jar.sha1
  qa/wildfly/build.gradle
  qa/wildfly/src/main/resources/log4j2.properties
  server/build.gradle
  server/licenses/log4j-api-2.17.1.jar.sha1
  server/licenses/log4j-api-2.20.0.jar.sha1
  server/licenses/log4j-core-2.17.1.jar.sha1
  server/licenses/log4j-core-2.20.0.jar.sha1
  server/licenses/log4j-jul-2.17.1.jar.sha1
  server/licenses/log4j-jul-2.20.0.jar.sha1
  server/src/main/java/org/opensearch/common/logging/LogConfigurator.java
  server/src/main/java/org/opensearch/common/logging/OpenSearchJsonLayout.java
  test/framework/build.gradle
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: dependencies, backport 2.x

#8627 [Backport 2.x] Add Changes in Snapshot Delete Flow for remote store interoperability. (#7497)
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/repositories/cleanup/TransportCleanupRepositoryAction.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Labels: skip-changelog

#8633 [Segment Replication] Add logic back to update tracking replication checkpoint on source
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
Labels: skip-changelog

#8613 [Search Pipeline] Flip SEARCH_PIPELINE feature flag for Search Pipeline GA
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
Labels: v2.9.0

#8602 [Refactor] HPPC IntArrayList and ObjectArrayList to j.u.List
  server/src/main/java/org/opensearch/action/get/MultiGetShardRequest.java
  server/src/main/java/org/opensearch/action/get/MultiGetShardResponse.java
  server/src/main/java/org/opensearch/action/search/FetchSearchPhase.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseController.java
  server/src/main/java/org/opensearch/action/search/SearchScrollQueryThenFetchAsyncAction.java
  server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsShardRequest.java
  server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsShardResponse.java
  server/src/main/java/org/opensearch/common/transport/PortsRange.java
  server/src/main/java/org/opensearch/search/fetch/ShardFetchRequest.java
  server/src/main/java/org/opensearch/search/fetch/ShardFetchSearchRequest.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  test/framework/src/main/java/org/opensearch/test/TestCluster.java
Labels: enhancement, skip-changelog, v2.10.0

#8640 Mute RemoteStoreRefreshListenerTests tests causing gradle check failure on 2.x branch
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#8643 [Backport 2.x] [Search Pipeline] Flip SEARCH_PIPELINE feature flag for search pipeline GA (#8613)
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
Labels: v2.9.0, >blocker

#8632 Fix remote segments sync retry regression introduced in PR #7119
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#8653 Make sure IndexOutput of metadata file is always closed
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: skip-changelog

#8656 Make sure IndexOutput of metadata file is always closed (#8653)
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: skip-changelog

#8654 [Backport 2.x] Manually backport #7119, #8626, #8632
  libs/common/src/main/java/org/opensearch/common/io/InputStreamContainer.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartFileCorruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsBlobStore.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsRepository.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsRepositoryPlugin.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsVerifyingBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/VerifyingMultiStreamBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainer.java
  server/src/main/java/org/opensearch/common/util/ByteUtils.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/exception/ChecksumCombinationException.java
  server/src/main/java/org/opensearch/index/translog/Checkpoint.java
  server/src/main/java/org/opensearch/index/translog/TranslogCheckedContainer.java
  server/src/main/java/org/opensearch/index/translog/TranslogHeader.java
  server/src/main/java/org/opensearch/index/translog/TranslogReader.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/main/java/org/opensearch/index/translog/checked/package-info.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/FileSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/TestUploadListener.java
  server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceMockRepositoryTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/FileSnapshotTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/FileTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#8529 [Backport] [2.x] Update to Gradle 8.2.1 (#8018)
  benchmarks/build.gradle
  build.gradle
  buildSrc/build.gradle
  buildSrc/reaper/build.gradle
  buildSrc/src/main/groovy/org/opensearch/gradle/plugin/PluginBuildPlugin.groovy
  buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ForbiddenPatternsTask.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/LoggerUsageTask.java
  buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestApiTask.java
  buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestTestsTask.java
  buildSrc/src/main/java/org/opensearch/gradle/util/GradleUtils.java
  buildSrc/src/main/java/org/opensearch/gradle/util/Util.java
  client/benchmark/build.gradle
  client/rest-high-level/build.gradle
  client/rest/build.gradle
  client/sniffer/build.gradle
  client/test/build.gradle
  distribution/archives/integ-test-zip/build.gradle
  distribution/tools/java-version-checker/build.gradle
  distribution/tools/launchers/build.gradle
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/upgrade-cli/build.gradle
  doc-tools/build.gradle
  gradle.properties
  gradle/code-coverage.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  libs/common/build.gradle
  libs/core/build.gradle
  modules/lang-painless/build.gradle
  modules/lang-painless/spi/build.gradle
  server/build.gradle
  settings.gradle
Labels: Build Libraries & Interfaces, skip-changelog, v2.10.0

#8657 [Segment Replication] [Revert] Remove Restriction of strictly using only docrep for system indices and hidden indices (#8502)
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: skip-changelog, v2.9.0

#7217 [Remote Store] Add S3 async upload utilities and models
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/AmazonAsyncS3Reference.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/AmazonAsyncS3WithCredentials.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/SocketAccess.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncExecutorContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferEventLoopGroup.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/io/CheckedContainer.java
  plugins/repository-s3/src/main/plugin-metadata/plugin-security.policy
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3AsyncServiceTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/ZeroInputStream.java
Labels: skip-changelog

#8667 Bump 2.x to version 2.10.0
  .ci/bwcVersions
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/180_percentiles_tdigest_metric_unsigned.yml
Labels: skip-changelog

#8670 Add 2.10.0 to bwc versions.
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
  rest-api-spec/src/main/resources/rest-api-spec/test/cluster.put_settings/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/40_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.forcemerge/20_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.open/30_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/40_max_shard_size.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/50_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/40_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/pit/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/180_percentiles_tdigest_metric.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/180_percentiles_tdigest_metric_unsigned.yml
Labels: skip-changelog

#7218 [Remote Store] Integrate S3 async upload with S3BlobContainer
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
Labels: skip-changelog

#8676 [Backport 2.x] [Remote Store] Integrate S3 async upload with S3BlobContainer
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
Labels: skip-changelog

#7626 [Backport] [Segment Replication] Added mixed and rolling upgrade bwc test (#7537)
  qa/mixed-cluster/build.gradle
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: blocked, skip-changelog

#8682 Create 2.9 release notes and clear out changelog
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.9.0.md
Labels: backport 2.x, backport 2.9

#8674 [Extensions] Removed unused extension directory
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
Labels: backport 2.x, skip-changelog, backport 2.9

#8470 Changing search shard failure logging to trace from debug
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
Labels: skip-changelog

#8433 Handle replication cases where the remote store metadata file is not present
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/test/java/org/opensearch/indices/replication/RemoteStoreReplicationSourceTests.java
Labels: skip-changelog

#8704 Fix RemoteStoreReplicationSourceTests.testGetCheckpointMetadataEmpty.
  server/src/test/java/org/opensearch/indices/replication/RemoteStoreReplicationSourceTests.java
Labels: backport 2.x, skip-changelog

#8705 [Backport 2.x] Fix RemoteStoreReplicationSourceTests.testGetCheckpointMetadataEmpty (#8704)
  server/src/test/java/org/opensearch/indices/replication/RemoteStoreReplicationSourceTests.java
Labels: skip-changelog

#8690 [Backport-2.x] Removed unused extension directory
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
Labels: skip-changelog

#8173 Segment Replication - Allow search idle with no replicas
  server/src/internalClusterTest/java/org/opensearch/action/search/TransportSearchIT.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: backport 2.x, skip-changelog, v2.10.0

#8726 Manually update io.grpc:grpc-context from 1.46.0 to 1.56.1
  CHANGELOG.md
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/grpc-context-1.46.0.jar.sha1
  plugins/repository-gcs/licenses/grpc-context-1.56.1.jar.sha1
Labels: backport 2.x

#8708 Mute ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting
  server/src/internalClusterTest/java/org/opensearch/cluster/shards/ClusterShardLimitIT.java
Labels: skip-changelog

#8715 Fix flaky test testDropPrimaryDuringReplication.
  server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationReaderManagerTests.java
Labels: skip-changelog

#8739 [Remote Store] Do not trigger storeDirectory.sync in segment download flow from remote store
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: skip-changelog

#8487 [Remote Segment Store] Use files from segmentInfosSnapshot in upload
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreForceMergeIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
Labels: skip-changelog

#8747 [Backport 2.x] Start replication checkpointTimers on primary before segments upload to remote store. (#8221)
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#8050 [Segment Replication][Remote Store] Remove commits when remote store is enabled
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
Labels: backport 2.x, skip-changelog

#8513 Remove SEARCH_PIPELINE feature flag
  client/rest-high-level/build.gradle
  distribution/src/config/opensearch.yml
  modules/search-pipeline-common/build.gradle
  modules/search-pipeline-common/src/internalClusterTest/java/org/opensearch/search/pipeline/common/SearchPipelineCommonIT.java
  qa/mixed-cluster/build.gradle
  qa/smoke-test-multinode/build.gradle
  rest-api-spec/build.gradle
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/search/RandomSearchRequestGenerator.java
Labels: Priority-High, backport 2.x, skip-changelog, v2.9.0, backport 2.9

#8764 Fix search pipeline bwc test
  qa/mixed-cluster/build.gradle
  rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml
Labels: skip-changelog, backport 2.9

#8773 [Backport 2.x] Use CloseableRetryableRefreshListener to drain ongoing after refresh tasks on relocation (#8683)
  server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/CloseableRetryableRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/index/shard/CloseableRetryableRefreshListenerTests.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#8768 [Remote Store] Change remote store integ tests to use remote store for replication
  server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
Labels: backport 2.x, skip-changelog

#8772 [Backport 2.x] Use files from segmentInfosSnapshot in upload (#8487)
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreForceMergeIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
Labels: skip-changelog

#8696 Make Tracer injectable
  server/src/main/java/org/opensearch/node/Node.java
Labels: skip-changelog

#8511 Composite directory implementation
  benchmarks/src/main/java/org/opensearch/benchmark/store/remote/filecache/FileCacheBenchmark.java
  server/src/internalClusterTest/java/org/opensearch/search/RemoteSearchIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/CompositeDirectory.java
  server/src/main/java/org/opensearch/index/store/CompositeDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/FileTracker.java
  server/src/main/java/org/opensearch/index/store/FileTrackerImp.java
  server/src/main/java/org/opensearch/index/store/FileTrackingInfo.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSearchIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheActionTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
  server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
  test/framework/src/main/java/org/opensearch/test/store/MockFSDirectoryFactory.java
Labels: skip-changelog

#8735 Change InternalSignificantTerms to only sum shard level counts in final reduce
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/SignificantTermsSignificanceScoreIT.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationCollectorManager.java
  server/src/main/java/org/opensearch/search/aggregations/InternalAggregation.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalSignificantTerms.java
  server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/test/search/aggregations/bucket/SharedSignificantTermsTestMethods.java
  test/framework/src/main/java/org/opensearch/test/TestSearchContext.java
Labels: backport 2.x, v2.10.0

#8810 Add integration tests for remote store restore flow (#8484)
  server/src/internalClusterTest/java/org/opensearch/remotestore/PrimaryTermValidationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
Labels: skip-changelog

#8818 Mute test - SegmentReplicationIndexShardTests#testNRTReplicaWithRemot…
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: skip-changelog

#8088 [Remote Segment Store] Add Lucene major version to UploadedSegmentMetadata
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
Labels: durability, skip-changelog, v2.9.0

#8820 [Remote Segment Store] Add Lucene major version to UploadedSegmentMetadata (#8088)
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
Labels: skip-changelog

#8799 fixtures: fix read-only krb5kdc composeBuild failure
  test/fixtures/krb5kdc-fixture/Dockerfile
Labels: skip-changelog

#8808 Remove searchSegmentOrderReversed from IndexSettings
  server/src/main/java/org/opensearch/index/IndexSettings.java
Labels: backport 2.x, skip-changelog, v2.10.0

#8828 Adding @sohami to OpenSearch maintainers
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#8835 Fix flaky test - org.opensearch.repositories.blobstore.BlobStoreRepos…
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Labels: skip-changelog

#8825 Retry only specified tests
  TESTING.md
  build.gradle
Labels: backport 2.x, skip-changelog

#8827 Fix flaky test SegmentReplicationRemoteStoreIT.testPressureServiceStats
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
Labels: skip-changelog

#8668 Update Apache Lucene to 9.8.0-snapshot-4373c3b
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.7.0.jar.sha1
  libs/core/licenses/lucene-core-9.8.0-snapshot-4373c3b.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.7.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.7.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.7.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.7.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.7.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.7.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.7.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.8.0-snapshot-4373c3b.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.7.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-analysis-common-9.7.0.jar.sha1
  server/licenses/lucene-analysis-common-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-backward-codecs-9.7.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-core-9.7.0.jar.sha1
  server/licenses/lucene-core-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-grouping-9.7.0.jar.sha1
  server/licenses/lucene-grouping-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-highlighter-9.7.0.jar.sha1
  server/licenses/lucene-highlighter-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-join-9.7.0.jar.sha1
  server/licenses/lucene-join-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-memory-9.7.0.jar.sha1
  server/licenses/lucene-memory-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-misc-9.7.0.jar.sha1
  server/licenses/lucene-misc-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-queries-9.7.0.jar.sha1
  server/licenses/lucene-queries-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-queryparser-9.7.0.jar.sha1
  server/licenses/lucene-queryparser-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-sandbox-9.7.0.jar.sha1
  server/licenses/lucene-sandbox-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-spatial-extras-9.7.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-spatial3d-9.7.0.jar.sha1
  server/licenses/lucene-spatial3d-9.8.0-snapshot-4373c3b.jar.sha1
  server/licenses/lucene-suggest-9.7.0.jar.sha1
  server/licenses/lucene-suggest-9.8.0-snapshot-4373c3b.jar.sha1
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/ExplainableScriptIT.java
  server/src/main/java/org/opensearch/search/suggest/completion/CompletionSuggester.java
Labels: skip-changelog

#8807 Create separate SourceLookup instance per segment slice in SignificantTextAggregatorFactory
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorFactory.java
Labels: backport 2.x, v2.10.0

#6995 Bump version of Hadoop dependencies to 3.3.6
  CHANGELOG.md
  distribution/src/config/jvm.options
  libs/secure-sm/src/main/java/org/opensearch/secure_sm/SecuredForkJoinWorkerThreadFactory.java
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/hadoop-client-api-3.3.4.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-api-3.3.6.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-runtime-3.3.4.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-client-runtime-3.3.6.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-3.3.4.jar.sha1
  plugins/repository-hdfs/licenses/hadoop-hdfs-3.3.6.jar.sha1
  plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsClientThreadLeakFilter.java
Labels: dependencies, backport 2.x

#8823 Extend publishXToMavenLocal explicit dependencies to all repo tasks
  modules/lang-painless/build.gradle
Labels: skip-changelog

#8877 Skip testPitCreatedOnReplica IT with remote store
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: backport 2.x, skip-changelog

#8863 Fix SegmentReplicationUsingRemoteStoreIT.testReplicaHasDiffFilesThanPrimary.
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
Labels: skip-changelog

#8859 Remove unnecessary refresh listeners from NRTReplicationReaderManager.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationReaderManager.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: backport 2.x, skip-changelog

#8883 Updated Version.java path from server to libs in version.yml
  .github/workflows/version.yml
Labels: skip-changelog

#8897 Increment version to 2.9.1
  .ci/bwcVersions
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#8923 Add 2.9.1 to BWC and known versions
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#8929 [Forwardport] Add 2.9.1 to BWC and known versions (#8923)
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#8901 Fix flakiness in MasterServiceTests.testThrottlingForMultipleTaskTypes
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
Labels: backport 2.x, skip-changelog

#8912 Fix SegmentReplicationIT.testReplicaHasDiffFilesThanPrimary for node-node replication
  server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
  server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
Labels: skip-changelog

#8933 Configure test-retry plugin filter properly
  build.gradle
Labels: backport 2.x, skip-changelog

#8940 [Refactor] MediaTypeParserRegistry to MediaTypeRegistry
  client/rest-high-level/src/main/java/org/opensearch/client/indices/CreateIndexRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/PutMappingRequest.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamInput.java
  libs/core/src/main/java/org/opensearch/core/xcontent/MediaType.java
  libs/core/src/main/java/org/opensearch/core/xcontent/MediaTypeRegistry.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java
  libs/x-content/src/test/java/org/opensearch/common/xcontent/MediaTypeParserTests.java
  server/src/main/java/org/opensearch/rest/AbstractRestChannel.java
  server/src/main/java/org/opensearch/transport/TransportService.java
Labels: enhancement, pending backport, skip-changelog, v2.10.0

#8937 [Segment Replication] Use deterministic mechanism to have concurrent invocation of segment replication
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Labels: skip-changelog

#8938 Register MediaTypes through SPI
  libs/core/src/main/java/org/opensearch/core/xcontent/MediaTypeRegistry.java
  libs/core/src/main/java/org/opensearch/core/xcontent/spi/MediaTypeProvider.java
  libs/core/src/main/java/org/opensearch/core/xcontent/spi/package-info.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentType.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/spi/XContentProvider.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/spi/package-info.java
  libs/x-content/src/main/resources/META-INF/services/org.opensearch.core.xcontent.spi.MediaTypeProvider
  server/src/main/java/org/opensearch/transport/TransportService.java
Labels: enhancement, pending backport, skip-changelog, v2.10.0

#8943 [Segment Replication] Remove testUpdateSegmentsWhileRefreshing flaky test failure
  server/src/test/java/org/opensearch/index/engine/NRTReplicationReaderManagerTests.java
Labels: backport 2.x, skip-changelog

#8907 Amend tests to include all codecs
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#8914 [Remote Store] Add metadata prefix to Remote Translog Metadata file
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Labels: skip-changelog

#8963 [BUG] CompletionSuggestSearchIT.testSkipDuplicates is flaky
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/main/java/org/opensearch/search/suggest/completion/CompletionSuggester.java
Labels: bug, skip-changelog

#8904 Added empty build.gradle files for arm64 and s390x because the gradle assemble task fails without them
  distribution/docker/docker-arm64-export/build.gradle
  distribution/docker/docker-s390x-export/build.gradle
Labels: skip-changelog

#8968 Revert "amending tests to include all codecs (#8907)"
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#8195 [distribution/archives] [Linux] [x64] Provide the variant of the distributions bundled with JRE
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  buildSrc/src/main/java/org/opensearch/gradle/JavaPackageType.java
  buildSrc/src/main/java/org/opensearch/gradle/JavaVariant.java
  buildSrc/src/main/java/org/opensearch/gradle/Jdk.java
  buildSrc/src/main/java/org/opensearch/gradle/Jre.java
  buildSrc/src/main/java/org/opensearch/gradle/JreDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/OpenSearchDistribution.java
  buildSrc/src/main/java/org/opensearch/gradle/VersionProperties.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/src/main/resources/META-INF/gradle-plugins/opensearch.jre-download.properties
  buildSrc/src/test/java/org/opensearch/gradle/DistributionDownloadPluginTests.java
  distribution/archives/build.gradle
  distribution/build.gradle
  distribution/src/bin/opensearch-env
  server/src/main/java/org/opensearch/monitor/jvm/JvmInfo.java
  server/src/main/java/org/opensearch/node/Node.java
  settings.gradle
Labels: Build Libraries & Interfaces

#8967 Replace deprecated Query#rewrite(IndexReader with rewrite(IndexSearcher
  modules/parent-join/src/main/java/org/opensearch/join/query/HasChildQueryBuilder.java
  modules/percolator/src/main/java/org/opensearch/percolator/PercolateQuery.java
  modules/percolator/src/test/java/org/opensearch/percolator/CandidateQueryTests.java
  server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java
  server/src/main/java/org/opensearch/common/lucene/search/MoreLikeThisQuery.java
  server/src/main/java/org/opensearch/common/lucene/search/MultiPhrasePrefixQuery.java
  server/src/main/java/org/opensearch/common/lucene/search/function/FunctionScoreQuery.java
  server/src/main/java/org/opensearch/common/lucene/search/function/ScriptScoreQuery.java
  server/src/main/java/org/opensearch/index/document/SortedUnsignedLongDocValuesRangeQuery.java
  server/src/main/java/org/opensearch/index/query/DateRangeIncludingNowQuery.java
  server/src/main/java/org/opensearch/index/search/OpenSearchToParentBlockJoinQuery.java
  server/src/main/java/org/opensearch/lucene/queries/MinDocQuery.java
  server/src/main/java/org/opensearch/search/suggest/completion/CompletionSuggester.java
  server/src/test/java/org/opensearch/deps/lucene/VectorHighlighterTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/SpanMultiTermQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/search/OpenSearchToParentBlockJoinQueryTests.java
  server/src/test/java/org/opensearch/lucene/queries/MinDocQueryTests.java
  server/src/test/java/org/opensearch/lucene/queries/SpanMatchNoDocsQueryTests.java
  server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java
Labels: enhancement, skip-changelog, v2.10.0

#8931 Unmute test SegmentReplicationIndexShardTests#testNRTReplicaWithRemot…
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: backport 2.x, skip-changelog

#8606 Add restore level safeguards to prevent file cache oversubscription
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestTests.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingTableTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: backport 2.x, v2.10.0

#8984 Remove MasterServiceTests from retries
  build.gradle
Labels: backport 2.x, skip-changelog

#9005 [Remove] Deprecated Fractional ByteSizeValue support
  CHANGELOG.md
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/BytesProcessorTests.java
  server/src/main/java/org/opensearch/common/unit/ByteSizeValue.java
  server/src/test/java/org/opensearch/common/unit/ByteSizeValueTests.java
Labels: enhancement, v2.10.0

#9011 [Bug] Fix Setting#byteSizeSetting to use whole value string
  server/src/main/java/org/opensearch/common/settings/Setting.java
Labels: bug, Severity-Blocker, skip-changelog, v2.10.0

#9007 [Backport 2.x] [Remove] Deprecated Fractional ByteSizeValue support (#9005)
  CHANGELOG.md
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/BytesProcessorTests.java
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/common/unit/ByteSizeValue.java
  server/src/test/java/org/opensearch/common/unit/ByteSizeValueTests.java
Labels: enhancement, backport, v2.10.0
