Repository opensearch-project/OpenSearch, pull requests merged in 2023-05, with the labels that each got.

#7167 Make verifier return type as ActionResponse
  test/framework/src/main/java/org/opensearch/test/rest/RestActionTestCase.java
Labels: skip-changelog

#7338 [Backport] [2.x] Bump com.netflix.nebula:nebula-publishing-plugin from 20.2.0 to 20.3.0 (#7311)
  CHANGELOG.md
  buildSrc/build.gradle
Labels: backport

#7343 [Backport] [2.x] Bump com.netflix.nebula.ospackage-base from 11.2.0 to 11.3.0 in /distribution/packages (#7310)
  CHANGELOG.md
  distribution/packages/build.gradle
Labels: backport

#7227 Add remote refresh segment pressure service, settings and tracker
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/util/MovingAverage.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureService.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
  server/src/main/java/org/opensearch/index/remote/package-info.java
  server/src/test/java/org/opensearch/common/util/MovingAverageTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureSettingsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentTrackerTests.java
Labels: backport 2.x, skip-changelog

#7302 [Extensions] Adding versioning support for registering Rest actions
  CHANGELOG.md
  server/build.gradle
  server/src/main/java/org/opensearch/extensions/ExtensionRequest.java
  server/src/main/java/org/opensearch/extensions/rest/RegisterRestActionsRequest.java
  server/src/main/proto/extensions/ExtensionIdentityProto.proto
  server/src/main/proto/extensions/ExtensionRequestProto.proto
  server/src/main/proto/extensions/RegisterRestActionsProto.proto
  server/src/test/java/org/opensearch/extensions/rest/RegisterRestActionsTests.java
Labels: backport 2.x, extensions

#7367 Updated developer guide for adding dependencies.
  DEVELOPER_GUIDE.md
Labels: skip-changelog

#7379 [Backport main] Add bwc version 2.7.1 (#7371)
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#7395 Fix flakiness for getNodeRoles based tests
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
Labels: skip-changelog

#7373 [Backport 2.x] Adding versioning support for registering Rest actions
  CHANGELOG.md
  server/build.gradle
  server/src/main/java/org/opensearch/extensions/ExtensionRequest.java
  server/src/main/java/org/opensearch/extensions/rest/RegisterRestActionsRequest.java
  server/src/main/proto/extensions/ExtensionIdentityProto.proto
  server/src/main/proto/extensions/ExtensionRequestProto.proto
  server/src/main/proto/extensions/RegisterRestActionsProto.proto
  server/src/test/java/org/opensearch/extensions/rest/RegisterRestActionsTests.java
Labels: backport, extensions, skip-changelog

#7397 Bump org.apache.shiro from 1.9.1 to 1.11.0
  CHANGELOG.md
  plugins/identity-shiro/build.gradle
  plugins/identity-shiro/licenses/shiro-core-1.11.0.jar.sha1
  plugins/identity-shiro/licenses/shiro-core-1.9.1.jar.sha1
Labels: backport 2.x

#7235 Add extensions to gradle plugin
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/ExtensionsProperties.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestExtensionsList.java
Labels: skip-changelog

#7403 [Extensions] Adding cross version support for registering Transport Actions
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  server/build.gradle
  server/src/main/java/org/opensearch/extensions/action/RegisterTransportActionsRequest.java
  server/src/main/proto/extensions/RegisterTransportActionsProto.proto
  server/src/test/java/org/opensearch/extensions/action/RegisterTransportActionsRequestTests.java
  server/src/test/java/org/opensearch/extensions/rest/RegisterRestActionsTests.java
Labels: backport 2.x, extensions

#7407 [Backport 2.x] Bump org.apache.shiro from 1.9.1 to 1.11.0 (#7397)
  CHANGELOG.md
  plugins/identity-shiro/build.gradle
  plugins/identity-shiro/licenses/shiro-core-1.11.0.jar.sha1
  plugins/identity-shiro/licenses/shiro-core-1.9.1.jar.sha1
Labels: backport, >upgrade, dependencies, v2.8.0

#7412 [Backport 2.x] Adding cross version support for registering Transport Actions
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  server/build.gradle
  server/src/main/java/org/opensearch/extensions/action/RegisterTransportActionsRequest.java
  server/src/main/proto/extensions/RegisterTransportActionsProto.proto
  server/src/test/java/org/opensearch/extensions/action/RegisterTransportActionsRequestTests.java
  server/src/test/java/org/opensearch/extensions/rest/RegisterRestActionsTests.java
Labels: backport, extensions, v2.8.0

#7405 Bump jetty-server from 9.4.49.v20220914 to 9.4.51.v20230217 in hdfs-fixture.
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: >upgrade, dependencies, backport 2.x

#7427 Update section for changelog entries
  .github/workflows/dependabot_pr.yml
Labels: skip-changelog

#7429 Upgrade all jetty dependencies to 9.4.51.v20230217.
  test/fixtures/hdfs-fixture/build.gradle
Labels: skip-changelog

#7375 Add back primary shard preference for queries
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/RareClusterStateIT.java
  server/src/internalClusterTest/java/org/opensearch/search/basic/SearchWhileCreatingIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/MatchedQueriesIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/RandomScoreFunctionIT.java
  server/src/internalClusterTest/java/org/opensearch/search/preference/SearchPreferenceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/ClusterSearchShardsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/ClusterSearchShardsRequestBuilder.java
  server/src/main/java/org/opensearch/action/get/GetRequest.java
  server/src/main/java/org/opensearch/action/get/GetRequestBuilder.java
  server/src/main/java/org/opensearch/action/get/MultiGetRequest.java
  server/src/main/java/org/opensearch/action/get/MultiGetShardRequest.java
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/action/search/SearchRequestBuilder.java
  server/src/main/java/org/opensearch/action/termvectors/MultiTermVectorsShardRequest.java
  server/src/main/java/org/opensearch/action/termvectors/TermVectorsRequest.java
  server/src/main/java/org/opensearch/action/termvectors/TermVectorsRequestBuilder.java
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/main/java/org/opensearch/cluster/routing/Preference.java
  server/src/test/java/org/opensearch/cluster/structure/RoutingIteratorTests.java
  test/framework/src/main/java/org/opensearch/test/client/RandomizingClient.java
Labels: backport 2.x

#7361 Add support to run SegRep integ tests using remote store settings
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Labels: skip-changelog

#7448 OpenJDK Update (April 2023 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: dependencies, backport 2.7

#7449 OpenJDK Update (April 2023 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: dependencies, backport 1.3

#7454 [Backport] [1.3] OpenJDK Update (April 2023 Patch releases) (#7449)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport

#7464 [Backport] [2.x] Bump org.apache.commons:commons-compress from 1.22 to 1.23.0 in /test/fixtures/hdfs-fixture (#7462)
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport, dependencies

#7430 [Backport 2.x] Add extensions to gradle plugin
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/ExtensionsProperties.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchCluster.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestClusterConfiguration.java
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/TestExtensionsList.java
Labels: skip-changelog

#7469 Exclude protobuf-java version included with hadoop-minicluster
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport 1.x, backport 2.x, backport 1.3, skip-changelog

#7400 [Remote Segments] Retry segment uploads to remote store on failure
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
  test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java
Labels: durability, skip-changelog, v2.8.0

#7451 [Backport 2.x] Cleanup interfaces around ExtensionManager (#7374)
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/main/java/org/opensearch/extensions/NoopExtensionsManager.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: skip-changelog

#7472 Manual backport of guava, netty, jetty version bumps in hdfs-fixture to 1.x.
  buildSrc/version.properties
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport 1.3, skip-changelog

#7476 [Backport] [2.x] Bump com.azure:azure-core from 1.34.0 to 1.39.0 in /plugins/repository-azure (#7069)
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-core-1.34.0.jar.sha1
  plugins/repository-azure/licenses/azure-core-1.39.0.jar.sha1
  plugins/repository-azure/licenses/azure-json-1.0.1.jar.sha1
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageService.java
  plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java
Labels: backport

#7468 [Extensions] Moving transport action API to support cross versions
  server/build.gradle
  server/src/main/java/org/opensearch/extensions/action/ExtensionActionRequest.java
  server/src/main/java/org/opensearch/extensions/action/ExtensionHandleTransportRequest.java
  server/src/main/java/org/opensearch/extensions/action/TransportActionRequestFromExtension.java
  server/src/main/proto/extensions/HandleTransportRequestProto.proto
  server/src/test/java/org/opensearch/extensions/action/ExtensionActionRequestTests.java
  server/src/test/java/org/opensearch/extensions/action/ExtensionHandleTransportRequestTests.java
  server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java
  server/src/test/java/org/opensearch/extensions/action/TransportActionRequestFromExtensionTests.java
Labels: backport 2.x, extensions, skip-changelog

#7480 [Backport 1.x] Exclude protobuf-java version included with hadoop-minicluster
  buildSrc/version.properties
  test/fixtures/hdfs-fixture/build.gradle
Labels: skip-changelog

#7482 [Backport 1.3] Manual backport of guava, netty, jetty version bumps in hdfs-fixture to 1.x. (#7472)
  buildSrc/version.properties
  test/fixtures/hdfs-fixture/build.gradle
Labels: skip-changelog

#7466 Adds ExtensionsManager.lookupExtensionSettingsById
  CHANGELOG.md
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
Labels: backport 2.x

#7494 [Backport 1.x] Bump net.minidev:json-smart from 2.4.7 to 2.4.10 in /t…
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: dependencies, dependabot

#7493 [Backport 1.3] Bump net.minidev:json-smart from 2.4.7 to 2.4.10 in /t…
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: CVE, dependencies, dependabot

#7305 Improve dedup logic using seperate map
  server/src/main/java/org/opensearch/cluster/service/TaskBatcher.java
  server/src/test/java/org/opensearch/cluster/service/TaskBatcherTests.java
Labels: skip-changelog

#7505 Update Apache Lucene to 9.6.0
  CHANGELOG.md
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.6.0-snapshot-a3ae27f.jar.sha1
  libs/core/licenses/lucene-core-9.6.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.6.0-snapshot-a3ae27f.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.6.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.6.0-snapshot-a3ae27f.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.6.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.6.0-snapshot-a3ae27f.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.6.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.6.0-snapshot-a3ae27f.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.6.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.6.0-snapshot-a3ae27f.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.6.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.6.0-snapshot-a3ae27f.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.6.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.6.0-snapshot-a3ae27f.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.6.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.6.0-snapshot-a3ae27f.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.6.0.jar.sha1
  server/licenses/lucene-analysis-common-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-analysis-common-9.6.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-backward-codecs-9.6.0.jar.sha1
  server/licenses/lucene-core-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-core-9.6.0.jar.sha1
  server/licenses/lucene-grouping-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-grouping-9.6.0.jar.sha1
  server/licenses/lucene-highlighter-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-highlighter-9.6.0.jar.sha1
  server/licenses/lucene-join-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-join-9.6.0.jar.sha1
  server/licenses/lucene-memory-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-memory-9.6.0.jar.sha1
  server/licenses/lucene-misc-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-misc-9.6.0.jar.sha1
  server/licenses/lucene-queries-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-queries-9.6.0.jar.sha1
  server/licenses/lucene-queryparser-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-queryparser-9.6.0.jar.sha1
  server/licenses/lucene-sandbox-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-sandbox-9.6.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-spatial-extras-9.6.0.jar.sha1
  server/licenses/lucene-spatial3d-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-spatial3d-9.6.0.jar.sha1
  server/licenses/lucene-suggest-9.6.0-snapshot-a3ae27f.jar.sha1
  server/licenses/lucene-suggest-9.6.0.jar.sha1
Labels: dependencies

#7504 Fix flaky SignificantTermsAggregatorTests
  libs/common/src/main/java/org/opensearch/common/Numbers.java
Labels: skip-changelog

#6787 [Remote Store] Add Lock Manager in Remote Segment Store to persist data
  server/src/main/java/org/opensearch/index/store/RemoteBufferedIndexOutput.java
  server/src/main/java/org/opensearch/index/store/RemoteBufferedOutputDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteIndexOutput.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/lockmanager/FileLockInfo.java
  server/src/main/java/org/opensearch/index/store/lockmanager/LockInfo.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreCommitLevelLockManager.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManager.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerFactory.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerUtils.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManager.java
  server/src/main/java/org/opensearch/index/store/lockmanager/package-info.java
  server/src/test/java/org/opensearch/index/store/RemoteBufferedIndexOutputTests.java
  server/src/test/java/org/opensearch/index/store/RemoteBufferedOutputDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/lockmanager/FileLockInfoTests.java
  server/src/test/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerFactoryTests.java
  server/src/test/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManagerTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog, first-time-contributor

#7528 Update Apache Lucene version for OpenSearch 2.8.0
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#7532 Clean up test cases for primary search preference
  server/src/internalClusterTest/java/org/opensearch/search/preference/SearchPreferenceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
Labels: backport 2.x, skip-changelog

#7511 [Docs] Clarify that Lucene Snapshot artifacts are releases, not snapshots
  DEVELOPER_GUIDE.md
Labels: skip-changelog

#7539 Fix flaky ScalingThreadPoolTests.testScalingThreadPoolConfiguration test
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: bug, durability, skip-changelog, v2.8.0

#7538 Change block check type for index clear cache APIs
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheBlocksIT.java
  server/src/main/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheAction.java
  server/src/test/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheActionTests.java
Labels: backport 2.x

#7523 [Remote Store] Clear feature flag set during unit test runs
  server/src/test/java/org/opensearch/common/settings/SettingsModuleTests.java
  server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/engine/ReadOnlyEngineTests.java
  server/src/test/java/org/opensearch/index/store/StoreTests.java
  test/framework/src/main/java/org/opensearch/test/FeatureFlagSetter.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: bug, durability, backport 2.x, skip-changelog, v2.8.0

#7550 Provide mechanism to configure XContent parsing constraints (after update to Jackson 2.15.0 and above)
  libs/x-content/src/main/java/org/opensearch/common/xcontent/cbor/CborXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/smile/SmileXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
  libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
Labels: backport 2.x, skip-changelog

#7470 [Search Pipelines] Add default_search_pipeline index setting
  CHANGELOG.md
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/30_filter_query.yml
  qa/mixed-cluster/build.gradle
  rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: backport 2.x

#7572 Fix flaky test SegmentReplicationIT.testScrollWithOngoingSegmentReplication
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: skip-changelog

#7498 Add filecache support in clear indices cache API
  CHANGELOG.md
  client/rest-high-level/src/main/java/org/opensearch/client/IndicesRequestConverters.java
  client/rest-high-level/src/test/java/org/opensearch/client/IndicesRequestConvertersTests.java
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.clear_cache.json
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheBlocksIT.java
  server/src/main/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheAction.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/RefCountedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestClearIndicesCacheAction.java
  server/src/test/java/org/opensearch/action/admin/indices/cache/clear/TransportClearIndicesCacheActionTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/cache/RefCountedCacheTestCase.java
Labels: backport 2.x

#7383 [Remote Translog] Trimming based on Remote Segment Store
  codecov.yml
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  test/framework/src/main/java/org/opensearch/test/BackgroundIndexer.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#7596 Update compatibility version for file cache API
  server/src/main/java/org/opensearch/action/admin/indices/cache/clear/ClearIndicesCacheRequest.java
Labels: skip-changelog

#7603 Bump Jackson from 2.15.0 to 2.15.1
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.15.0.jar.sha1
  client/sniffer/licenses/jackson-core-2.15.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.15.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.15.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.15.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.15.1.jar.sha1
  libs/core/licenses/jackson-core-2.15.0.jar.sha1
  libs/core/licenses/jackson-core-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-core-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.15.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.15.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.15.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.15.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.15.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.15.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.15.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.15.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.15.1.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.15.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.15.1.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.15.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.15.1.jar.sha1
Labels: dependencies

#7554 Fixed typo
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java
Labels: backport 2.x, skip-changelog

#7610 [Backport] [2.x] Bump com.azure:azure-storage-common from 12.20.0 to 12.21.0 in /plugins/repository-azure (#7566)
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-storage-common-12.20.0.jar.sha1
  plugins/repository-azure/licenses/azure-storage-common-12.21.0.jar.sha1
Labels: backport

#7609 [Backport] [2.x] Bump org.apache.commons:commons-compress from 1.22 to 1.23.0 (#7563)
  CHANGELOG.md
  buildSrc/build.gradle
Labels: backport

#7608 [Backport] [2.x] Bump Jackson from 2.15.0 to 2.15.1 (#7603)
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.15.0.jar.sha1
  client/sniffer/licenses/jackson-core-2.15.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.15.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.15.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.15.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.15.1.jar.sha1
  libs/core/licenses/jackson-core-2.15.0.jar.sha1
  libs/core/licenses/jackson-core-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-core-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.15.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.15.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.15.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.15.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.15.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.15.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.15.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.15.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.15.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.15.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.15.1.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.15.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.15.1.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.15.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.15.1.jar.sha1
Labels: backport

#7513 Segment Replication - Fixes for test SegmentReplicationIT.testReplicaHasDiffFilesThanPrimary
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: skip-changelog

#7441 [Remote Store] Add Remote store stats api
  client/rest-high-level/src/test/java/org/opensearch/client/RestHighLevelClientTests.java
  rest-api-spec/src/main/resources/rest-api-spec/api/remote_store.stats.json
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/package-info.java
  server/src/main/java/org/opensearch/client/ClusterAdminClient.java
  server/src/main/java/org/opensearch/client/support/AbstractClient.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestRemoteStoreStatsAction.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsRequestTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsResponseTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsActionTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentTrackerTests.java
Labels: skip-changelog

#7618 Fix version check for search pipelines REST test
  rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml
Labels: skip-changelog

#7537 [Segment Replication] Added mixed and rolling upgrade bwc test
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: backport 2.x, skip-changelog

#7617 Adds 1.3.10 release notes
  CHANGELOG.md
  release-notes/opensearch.release-notes-1.3.10.md
Labels: skip-changelog

#6870 Create NamedRoute to map extension routes to a shortened name
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/main/java/org/opensearch/extensions/rest/RestActionsRequestHandler.java
  server/src/main/java/org/opensearch/extensions/rest/RouteHandler.java
  server/src/main/java/org/opensearch/rest/NamedRoute.java
  server/src/main/java/org/opensearch/rest/RestHandler.java
  server/src/main/java/org/opensearch/rest/extensions/RestSendToExtensionAction.java
  server/src/main/java/org/opensearch/rest/extensions/package-info.java
  server/src/test/java/org/opensearch/action/ActionModuleTests.java
  server/src/test/java/org/opensearch/action/DynamicActionRegistryTests.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java
  server/src/test/java/org/opensearch/extensions/rest/RouteHandlerTests.java
  server/src/test/java/org/opensearch/rest/NamedRouteTests.java
Labels: backport 2.x, all-star-contributor

#7625 Fix flaky org.opensearch.common.xcontent.XContentParserTests.testString test case
  libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
Labels: skip-changelog

#7605 Update Apache Lucene to 9.7.0-snapshot-4d1ed9e
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.6.0.jar.sha1
  libs/core/licenses/lucene-core-9.7.0-snapshot-4d1ed9e.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.6.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.7.0-snapshot-4d1ed9e.jar.sha1
  modules/parent-join/src/test/java/org/opensearch/join/query/HasChildQueryBuilderTests.java
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.6.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.6.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.6.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.6.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.6.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.6.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.6.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-analysis-common-9.6.0.jar.sha1
  server/licenses/lucene-analysis-common-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-backward-codecs-9.6.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-core-9.6.0.jar.sha1
  server/licenses/lucene-core-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-grouping-9.6.0.jar.sha1
  server/licenses/lucene-grouping-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-highlighter-9.6.0.jar.sha1
  server/licenses/lucene-highlighter-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-join-9.6.0.jar.sha1
  server/licenses/lucene-join-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-memory-9.6.0.jar.sha1
  server/licenses/lucene-memory-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-misc-9.6.0.jar.sha1
  server/licenses/lucene-misc-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-queries-9.6.0.jar.sha1
  server/licenses/lucene-queries-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-queryparser-9.6.0.jar.sha1
  server/licenses/lucene-queryparser-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-sandbox-9.6.0.jar.sha1
  server/licenses/lucene-sandbox-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-spatial-extras-9.6.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-spatial3d-9.6.0.jar.sha1
  server/licenses/lucene-spatial3d-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-suggest-9.6.0.jar.sha1
  server/licenses/lucene-suggest-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/src/main/java/org/apache/lucene/search/vectorhighlight/CustomFieldQuery.java
  server/src/test/java/org/opensearch/lucene/queries/SpanMatchNoDocsQueryTests.java
Labels: dependencies, skip-changelog

#7459 [Remote segments] Add backpressure in write path on segments lag between local and remote store
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureService.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureSettingsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentTrackerTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/indices/IndicesLifecycleListenerSingleNodeTests.java
  server/src/test/java/org/opensearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
  server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java
Labels: durability, skip-changelog, v2.8.0

#7654 Mute SegmentReplicationRemoteStoreIT
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
Labels: skip-changelog

#7671 Remove workaround to access Lucene's "expert" readLatestCommit API
  server/src/main/java/org/opensearch/common/lucene/Lucene.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/test/java/org/opensearch/common/lucene/LuceneTests.java
Labels: backport 2.x, skip-changelog

#7607 [Search pipeline] Add script processor
  CHANGELOG.md
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/71_context_api.yml
  modules/search-pipeline-common/build.gradle
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/FilterQueryRequestProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/ScriptRequestProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/helpers/SearchRequestMap.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/helpers/SearchRequestMapProcessingException.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/helpers/package-info.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/ScriptRequestProcessorTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/helpers/SearchRequestMapTests.java
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/10_basic.yml
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/50_script_processor.yml
  server/src/main/java/org/opensearch/script/ScriptModule.java
  server/src/main/java/org/opensearch/script/SearchScript.java
  test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Labels: enhancement, backport 2.x, Search, v2.8.0

#7676 [Manual backport 2.x] Remove workaround to access Lucene's "expert" readLatestCommit API
  server/src/main/java/org/opensearch/common/lucene/Lucene.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/test/java/org/opensearch/common/lucene/LuceneTests.java
Labels: skip-changelog

#7689 [Backport 2.x] Fix flaky ScalingThreadPoolTests.testScalingThreadPoolConfiguration test (#7539)
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: skip-changelog

#7692 [Backport 2.x] Add support to run SegRep integ tests using remote store settings & Mute flaky test
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Labels: skip-changelog

#7672 Update SearchPipelineInfo backcompat check
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineInfo.java
Labels: skip-changelog

#7688 [Backport] [2.x] Bump commons-io:commons-io from 2.11.0 to 2.12.0 in /plugins/discovery-azure-classic (#7661)
  plugins/discovery-azure-classic/build.gradle
  plugins/discovery-azure-classic/licenses/commons-io-2.11.0.jar.sha1
  plugins/discovery-azure-classic/licenses/commons-io-2.12.0.jar.sha1
Labels: skip-changelog

#7697 Bump com.google.api:gax from 2.17.0 to 2.27.0 in /plugins/repository-gcs
  CHANGELOG.md
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/gax-2.17.0.jar.sha1
  plugins/repository-gcs/licenses/gax-2.27.0.jar.sha1
Labels: backport 2.x

#7674 [Extensions] Removing support for onIndexModule extension point
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/main/java/org/opensearch/extensions/NoopExtensionsManager.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: backport 2.x, extensions, skip-changelog

#7699 [Backport 2.x] [Remote Translog] Trimming based on Remote Segment Store (#7383)
  codecov.yml
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  test/framework/src/main/java/org/opensearch/test/BackgroundIndexer.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#7720 [Remote segments] Add backpressure in write path on segments lag between local and remote store (#7459)
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/ReplicaToPrimaryPromotionIT.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureService.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentPressureSettingsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentTrackerTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/indices/IndicesLifecycleListenerSingleNodeTests.java
  server/src/test/java/org/opensearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
  server/src/test/java/org/opensearch/indices/cluster/IndicesClusterStateServiceRandomUpdatesTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java
Labels: skip-changelog

#7712 Task cancellation API version guard fix
  server/src/main/java/org/opensearch/tasks/TaskInfo.java
Labels: skip-changelog

#7694 Add remote refresh lag in millis from local refresh
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteRefreshSegmentTrackerTests.java
Labels: skip-changelog

#7737 Remove flaky match conditions in script processor yaml test
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/50_script_processor.yml
Labels: skip-changelog

#7735 [Bugfix] Better exception handling in search pipelines
  CHANGELOG.md
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/30_filter_query.yml
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: backport 2.x, skip-changelog

#6645 fixing input validation in segments and delete pit request
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/segments/TransportPitSegmentsAction.java
  server/src/main/java/org/opensearch/action/search/TransportDeletePitAction.java
Labels: backport 2.x

#7526 [Extensions] Add ExtensionAwarePlugin extension point to add custom settings for extensions
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/extensions/ExtensionScopedSettings.java
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/main/java/org/opensearch/extensions/ExtensionsSettings.java
  server/src/main/java/org/opensearch/extensions/NoopExtensionsManager.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/ExtensionAwarePlugin.java
  server/src/main/java/org/opensearch/plugins/IdentityPlugin.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
Labels: backport 2.x

#7749 [Segment Replication] Mute testIndexingWithSegRep flaky test failure
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: skip-changelog

#7420 [Segment Replication] Allow Cluster Setting to enable default Replication type
  CHANGELOG.md
  distribution/src/config/opensearch.yml
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: skip-changelog

#7732 [Segment Replication] Use engine codec and replica shard ReplicationCheckpoint for replication events
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#7604 Add support for ignoring missing Javadoc on generated code using annotation (# 7264)
  CHANGELOG.md
  buildSrc/version.properties
  doc-tools/missing-doclet/build.gradle
  doc-tools/missing-doclet/src/main/java/org/opensearch/missingdoclet/MissingDoclet.java
  server/build.gradle
  server/licenses/jboss-annotations-api_1.2_spec-1.0.2.Final.jar.sha1
  server/licenses/jboss-annotations-api_1.2_spec-LICENSE.txt
  server/licenses/jboss-annotations-api_1.2_spec-NOTICE.txt
Labels: Build Libraries & Interfaces, backport 2.x

#7784 [Segment Replication] Move CLUSTER_REPLICATION_TYPE_SETTING out of experimental feature flag
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: backport 2.x, skip-changelog, backport 2.8

#7775 [Remote Store] Fix stats api rejection count response
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
Labels: durability, skip-changelog, v2.8.0

#7739 [Remote Store] Fix shards condition in stats api
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#7817 [Bug] Fix Build Metadata
  libs/core/src/main/java/org/opensearch/Build.java
  server/src/test/java/org/opensearch/BuildTests.java
Labels: skip-changelog

#7780 Generic Streamable Registry
  libs/core/src/main/java/org/opensearch/core/common/io/stream/BaseWriteable.java
  server/src/main/java/org/opensearch/common/geo/GeoPoint.java
  server/src/main/java/org/opensearch/common/io/stream/StreamInput.java
  server/src/main/java/org/opensearch/common/io/stream/StreamOutput.java
  server/src/main/java/org/opensearch/common/io/stream/Streamables.java
  server/src/main/java/org/opensearch/common/joda/Joda.java
  server/src/main/java/org/opensearch/script/JodaCompatibleZonedDateTime.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/common/io/stream/BytesStreamsTests.java
Labels: enhancement, skip-changelog, v2.9.0

#7797 [Segment Replication] Fix failing flaky test in SegmentReplicationSnapshotIT
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
Labels: backport 2.x, skip-changelog, backport 2.8

#7789 [Segment Replication] Use engine codec and replica shard ReplicationCheckpoint for replication events
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#7825 Add release notes v2.8.0
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.8.0.md
Labels: backport 2.x, backport 2.8

#7816 [Backport] [2.x] Bump com.azure:azure-storage-common from 12.21.0 to 12.21.1 in /plugins/repository-azure (#7814)
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-storage-common-12.21.0.jar.sha1
  plugins/repository-azure/licenses/azure-storage-common-12.21.1.jar.sha1
Labels: backport

#7709 Run publish maven snapshots on all branches matching pattern
  .github/workflows/publish-maven-snapshots.yml
Labels: skip-changelog

#7838 [Backport 2.x] [Remote Store] Fix stats api bugs (#7739) & (#7774)
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/TransportRemoteStoreStatsAction.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#7836 Replace jboss-annotations-api_1.2_spec with jakarta.annotation-api
  CHANGELOG.md
  buildSrc/version.properties
  qa/wildfly/build.gradle
  server/build.gradle
  server/licenses/jakarta.annotation-api-1.3.5.jar.sha1
  server/licenses/jakarta.annotation-api-LICENSE.txt
  server/licenses/jakarta.annotation-api-NOTICE.txt
  server/licenses/jboss-annotations-api_1.2_spec-1.0.2.Final.jar.sha1
  server/licenses/jboss-annotations-api_1.2_spec-LICENSE.txt
  server/licenses/jboss-annotations-api_1.2_spec-NOTICE.txt
Labels: dependencies, backport 2.x

#7844 [Backport] [2.x] Bump com.google.guava:guava from 31.1-jre to 32.0.0-jre in /distribution/tools/keystore-cli (#7811)
  CHANGELOG.md
  distribution/tools/keystore-cli/build.gradle
Labels: backport
