Repository opensearch-project/OpenSearch, pull requests merged in 2023-06, with the labels that each got.

#7673 Concurrent Search Tasks Response Updates
  CHANGELOG.md
  client/rest-high-level/src/test/java/org/opensearch/client/core/tasks/GetTaskResponseTests.java
  rest-api-spec/src/main/resources/rest-api-spec/test/tasks.list/10_basic.yml
  server/src/main/java/org/opensearch/tasks/Task.java
  server/src/main/java/org/opensearch/tasks/TaskResourceStats.java
  server/src/main/java/org/opensearch/tasks/TaskThreadUsage.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/TaskTests.java
  server/src/test/java/org/opensearch/tasks/ListTasksResponseTests.java
  server/src/test/java/org/opensearch/tasks/TaskInfoTests.java
  server/src/test/java/org/opensearch/tasks/TaskResourceTrackingServiceTests.java
Labels: v3.0.0, v2.9.0

#7865 [Backport] [2.x] Reduce memory copy in zstd compression (#7681)
  CHANGELOG.md
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdCompressionMode.java
  sandbox/plugins/custom-codecs/src/main/java/org/opensearch/index/codec/customcodecs/ZstdNoDictCompressionMode.java
Labels: backport

#7864 Bump 2.x to 2.9.0
  .ci/bwcVersions
  buildSrc/version.properties
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#7869 Add 2.9.0 to BWC versions
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#7870 [2.8] Reorder Setting enum to add Extension scope at bottom
  server/src/main/java/org/opensearch/common/settings/Setting.java
Labels: skip-changelog

#7871 Reorder Setting enum to add Extension scope at bottom
  server/src/main/java/org/opensearch/common/settings/Setting.java
Labels: backport 2.x, skip-changelog

#7344 OpenJDK Update (April 2023 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/JdkDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/VersionProperties.java
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
  distribution/build.gradle
  gradle/runtime-jdk-provision.gradle
  server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/discovery/StableClusterManagerDisruptionIT.java
  server/src/main/java/org/opensearch/common/util/concurrent/BaseFuture.java
  test/framework/src/test/java/org/opensearch/test/disruption/LongGCDisruptionTests.java
Labels: dependencies

#7879 [Remote Store] Fix flaky test - closes #7703
  server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
Labels: durability, skip-changelog, v2.9.0

#7889 Concurrent Search Tasks Response Updates (update BWC versions)
  rest-api-spec/src/main/resources/rest-api-spec/test/tasks.list/10_basic.yml
  server/src/main/java/org/opensearch/tasks/TaskResourceStats.java
Labels: skip-changelog

#7892 Revert "Time series based workload desc order optimization through re…
  release-notes/opensearch.release-notes-2.8.0.md
  server/src/main/java/org/opensearch/cluster/metadata/DataStream.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/mapper/MappingLookup.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: backport 2.x, skip-changelog

#7897 Bump jackson from 2.15.1 to 2.15.2
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.15.1.jar.sha1
  client/sniffer/licenses/jackson-core-2.15.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.15.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.15.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.15.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.15.2.jar.sha1
  libs/core/licenses/jackson-core-2.15.1.jar.sha1
  libs/core/licenses/jackson-core-2.15.2.jar.sha1
  libs/x-content/licenses/jackson-core-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-core-2.15.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.15.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.15.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.15.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.15.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.15.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.15.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.15.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.15.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.15.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.15.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.15.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.15.2.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.15.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.15.2.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.15.2.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.15.2.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.15.1.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.15.2.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.15.1.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.15.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.15.1.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.15.2.jar.sha1
Labels: backport 2.x

#7901 Bump netty from 4.1.91.Final to 4.1.93.Final
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http2-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http2-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.93.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.91.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.93.Final.jar.sha1
Labels: backport 1.x, dependencies, backport 2.x, backport 1.3

#7912 [Backport] [1.x] Bump netty from 4.1.91.Final to 4.1.93.Final (#7901)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.93.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.91.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.93.Final.jar.sha1
Labels: backport, dependencies

#7913 [Backport] [1.3] Bump netty from 4.1.91.Final to 4.1.93.Final (#7901)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.93.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.91.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.93.Final.jar.sha1
Labels: backport, dependencies

#7911 [Backport] [2.x] Bump netty from 4.1.91.Final to 4.1.93.Final (#7901)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.93.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.91.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.93.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.91.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.93.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.91.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.93.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.91.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.93.Final.jar.sha1
Labels: backport, dependencies

#7777 [Remote Segment Store] Combine metadata and snapshot files
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandler.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
Labels: skip-changelog

#7905 [Remote Store] Optimize segments metadata upload
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
Labels: durability, skip-changelog, v2.9.0

#7930 Update azure storage blob dependency to 12.22.2 from 12.21.1
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-storage-blob-12.21.1.jar.sha1
  plugins/repository-azure/licenses/azure-storage-blob-12.22.2.jar.sha1
Labels: dependencies

#7876 [Segment Replication] Wait for shard relocation before building node to shard allocation map
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: skip-changelog

#7887 Update Apache Lucene to 9.7.0-snapshot-204acc3
  buildSrc/version.properties
  libs/core/build.gradle
  libs/core/licenses/lucene-core-9.7.0-snapshot-204acc3.jar.sha1
  libs/core/licenses/lucene-core-9.7.0-snapshot-4d1ed9e.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.7.0-snapshot-204acc3.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.7.0-snapshot-4d1ed9e.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/build.gradle
  server/licenses/lucene-analysis-common-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-analysis-common-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-backward-codecs-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-backward-codecs-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-core-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-core-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-grouping-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-grouping-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-highlighter-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-highlighter-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-join-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-join-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-memory-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-memory-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-misc-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-misc-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-queries-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-queries-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-queryparser-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-queryparser-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-sandbox-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-sandbox-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-spatial-extras-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-spatial-extras-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-spatial3d-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-spatial3d-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/licenses/lucene-suggest-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-suggest-9.7.0-snapshot-4d1ed9e.jar.sha1
  server/src/main/java/org/opensearch/index/search/MatchQuery.java
  server/src/main/java/org/opensearch/index/search/MultiMatchQuery.java
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: skip-changelog

#7942 Add bwc version 2.8.1
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#7903 [Segment Replication] Add lucene codec tests
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: skip-changelog

#7961 [Remote Segment Store] Combine metadata and snapshot files (#7777)
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandler.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
Labels: skip-changelog

#7947 Make remote translog store path consistent to remote segment store
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/test/java/org/opensearch/index/translog/RemoteFSTranslogTests.java
Labels: skip-changelog

#7948 [Backport] [2.x] [Concurrent Segment Search]: Implement concurrent aggregations support without profile option
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/ScriptedMetricIT.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseController.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationCollectorManager.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationPhase.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationProcessor.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationReduceableSearchResult.java
  server/src/main/java/org/opensearch/search/aggregations/AggregatorFactories.java
  server/src/main/java/org/opensearch/search/aggregations/ConcurrentAggregationProcessor.java
  server/src/main/java/org/opensearch/search/aggregations/DefaultAggregationProcessor.java
  server/src/main/java/org/opensearch/search/aggregations/GlobalAggCollectorManager.java
  server/src/main/java/org/opensearch/search/aggregations/GlobalAggCollectorManagerWithSingleCollector.java
  server/src/main/java/org/opensearch/search/aggregations/InternalAggregations.java
  server/src/main/java/org/opensearch/search/aggregations/MultiBucketCollector.java
  server/src/main/java/org/opensearch/search/aggregations/NonGlobalAggCollectorManager.java
  server/src/main/java/org/opensearch/search/aggregations/NonGlobalAggCollectorManagerWithSingleCollector.java
  server/src/main/java/org/opensearch/search/aggregations/SearchContextAggregations.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filter/FiltersAggregatorFactory.java
  server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java
  server/src/main/java/org/opensearch/search/query/QueryCollectorContext.java
  server/src/main/java/org/opensearch/search/query/QueryCollectorManagerContext.java
  server/src/main/java/org/opensearch/search/query/QueryPhase.java
  server/src/main/java/org/opensearch/search/query/QueryPhaseSearcher.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  server/src/test/java/org/opensearch/search/aggregations/AggregationCollectorManagerTests.java
  server/src/test/java/org/opensearch/search/aggregations/AggregationCollectorTests.java
  server/src/test/java/org/opensearch/search/aggregations/AggregationProcessorTests.java
  server/src/test/java/org/opensearch/search/aggregations/AggregationSetupTests.java
  server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
  test/framework/src/main/java/org/opensearch/test/TestSearchContext.java
Labels: backport

#7933 Update com.networknt:json-schema-validator dependency from 1.0.81 to 1.0.83
  CHANGELOG.md
  buildSrc/build.gradle
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ValidateJsonAgainstSchemaTask.java
Labels: dependencies, backport 2.x

#7969 Default discovery-ec2 region to none.
  plugins/discovery-ec2/src/main/java/org/opensearch/discovery/ec2/AwsEc2ServiceImpl.java
  plugins/discovery-ec2/src/main/java/org/opensearch/discovery/ec2/Ec2ClientSettings.java
  plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2DiscoveryPluginTests.java
Labels: backport 2.x, skip-changelog

#7000 [Remote Store] Support to emit multiple streams for a file content each responsible for processing a specific part of the file
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  plugins/transport-nio/build.gradle
  server/build.gradle
  server/licenses/jzlib-1.1.3.jar.sha1
  server/licenses/jzlib-LICENSE.txt
  server/licenses/jzlib-NOTICE.txt
  server/src/main/java/org/opensearch/common/CheckedTriFunction.java
  server/src/main/java/org/opensearch/common/StreamContext.java
  server/src/main/java/org/opensearch/common/blobstore/exception/CorruptFileException.java
  server/src/main/java/org/opensearch/common/blobstore/exception/package-info.java
  server/src/main/java/org/opensearch/common/blobstore/stream/package-info.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/StreamContextSupplier.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WriteContext.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WritePriority.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/package-info.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainer.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/package-info.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/stream/OffsetRangeFileInputStream.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/stream/OffsetRangeIndexInputStream.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/stream/OffsetRangeInputStream.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/stream/ResettableCheckedInputStream.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/stream/package-info.java
  server/src/main/java/org/opensearch/common/io/InputStreamContainer.java
  server/src/main/java/org/opensearch/common/util/UploadListener.java
  server/src/main/java/org/opensearch/index/store/exception/ChecksumCombinationException.java
  server/src/main/java/org/opensearch/index/store/exception/package-info.java
  server/src/main/java/org/opensearch/index/translog/checked/TranslogCheckedContainer.java
  server/src/main/java/org/opensearch/index/translog/checked/package-info.java
  server/src/test/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainerTests.java
  server/src/test/java/org/opensearch/common/blobstore/transfer/stream/OffsetRangeFileInputStreamTests.java
  server/src/test/java/org/opensearch/common/blobstore/transfer/stream/OffsetRangeIndexInputStreamTests.java
  server/src/test/java/org/opensearch/common/blobstore/transfer/stream/ResettableCheckedInputStreamBaseTest.java
Labels: skip-changelog

#7863 Reduce allocations for field path text during parsing
  server/src/main/java/org/opensearch/index/mapper/ContentPath.java
Labels: skip-changelog

#7979 Update version guards to deal for new query profile collector fields
  server/src/main/java/org/opensearch/search/profile/query/CollectorResult.java
Labels: skip-changelog

#7988 [BUG] Fix org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/110_field_collapsing/field collapsing and search_after} flaky test
  rest-api-spec/src/main/resources/rest-api-spec/test/search/110_field_collapsing.yml
Labels: bug, backport 2.x, skip-changelog

#7970 Refactor QueryPhaseSearcher to support contextual aggregation processors at query phase
  server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java
  server/src/main/java/org/opensearch/search/query/QueryPhase.java
  server/src/main/java/org/opensearch/search/query/QueryPhaseSearcher.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
Labels: backport 2.x, skip-changelog

#7995 Add test case for OptionalDependenciesPlugin (com.netflix.nebula:gradle-extra-configurations-plugin plugin migration)
  buildSrc/src/test/java/org/opensearch/gradle/plugin/OptionalDependenciesPluginTests.java
  buildSrc/src/test/resources/plugin/optional-dependencies.gradle
Labels: backport 2.x, skip-changelog

#7967 Adding back [Time series based workload desc order optimization through reverse segment read (#7244)] with fixes
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/scroll/10_basic_timeseries.yml
  server/src/main/java/org/opensearch/cluster/metadata/DataStream.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/mapper/MappingLookup.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: backport 2.x

#8019 Add @sachinpkale as an OpenSearch maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#7953 Refactor Translog metadata upload/download to write/read header and footer via VersionedCodecStreamWrapper
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadataHandler.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferMetadataHandlerTests.java
Labels: skip-changelog

#7985 Fix flaky test `SearchRestCancellationIT.testAutomaticCancellationMultiSearchDuringFetchPhase`
  qa/smoke-test-http/src/test/java/org/opensearch/http/SearchRestCancellationIT.java
Labels: skip-changelog

#8033 Workflow to add a checklist for POC issues
  .github/workflows/poc-checklist.yml
Labels: skip-changelog

#8047 [Backport 2.x] Add @sachinpkale as an OpenSearch maintainer (#8019)
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#7682 [Remote Store] Deletion of Remote Segments and Translog upon Index Deletion
  server/src/internalClusterTest/java/org/opensearch/index/shard/GlobalCheckpointListenersIT.java
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManager.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManager.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/test/java/org/opensearch/index/engine/NoOpEngineRecoveryTests.java
  server/src/test/java/org/opensearch/index/replication/RecoveryDuringReplicationTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
  server/src/test/java/org/opensearch/indices/IndexingMemoryControllerTests.java
  server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoveryStatusTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#7458 [Remote Store] Ensure metadata file is deleted from local fs store during metadata upload failures
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#8061 [2.x] Added bwc version 1.3.11. (#7630)
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#5825 Fixed capitalization in ClusterAwarenessHealthIT class name
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterAwarenessHealthIT.java
Labels: skip-changelog

#8069 [TaskCancellationMonitoringService] Changing version check to 2.9
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
Labels: skip-changelog

#8057 Fix bug with delete shard routing weights on node restart
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java
  server/src/main/java/org/opensearch/cluster/routing/WeightedRouting.java
Labels: skip-changelog

#8039 Enforce 512 byte document ID limit in bulk updates
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/bulk/BulkIntegrationIT.java
  server/src/main/java/org/opensearch/action/DocWriteRequest.java
  server/src/main/java/org/opensearch/action/index/IndexRequest.java
  server/src/main/java/org/opensearch/action/update/UpdateRequest.java
  server/src/test/java/org/opensearch/action/bulk/BulkRequestTests.java
Labels: backport 2.x

#8092 [Snapshot Interop] Change Version Checks from 3.0 to 2.9
  server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
  server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
  server/src/test/java/org/opensearch/snapshots/SnapshotsInProgressSerializationTests.java
Labels: skip-changelog

#7591 Fix mapping char_filter when mapping a hashtag
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/MappingCharFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/MappingCharFilterFactoryTests.java
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/50_char_filters.yml
  server/src/main/java/org/opensearch/index/analysis/Analysis.java
Labels: backport 1.x, backport 2.x, backport 1.3

#4723 remove unnecessary empty `build.gradle` files
  distribution/archives/darwin-arm64-tar/build.gradle
  distribution/archives/darwin-tar/build.gradle
  distribution/archives/linux-arm64-tar/build.gradle
  distribution/archives/linux-tar/build.gradle
  distribution/archives/no-jdk-darwin-arm64-tar/build.gradle
  distribution/archives/no-jdk-darwin-tar/build.gradle
  distribution/archives/no-jdk-linux-tar/build.gradle
  distribution/archives/no-jdk-windows-zip/build.gradle
  distribution/archives/windows-zip/build.gradle
  distribution/docker/docker-arm64-export/build.gradle
  distribution/docker/docker-s390x-export/build.gradle
  distribution/packages/arm64-deb/build.gradle
  distribution/packages/arm64-rpm/build.gradle
  distribution/packages/deb/build.gradle
  distribution/packages/no-jdk-deb/build.gradle
  distribution/packages/no-jdk-rpm/build.gradle
  distribution/packages/rpm/build.gradle
Labels: backport 2.x, skip-changelog

#7989 Remove default s3 region
  plugins/repository-s3/build.gradle
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ServiceTests.java
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/20_repository_permanent_credentials.yml
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/30_repository_temporary_credentials.yml
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/40_repository_ec2_credentials.yml
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/50_repository_ecs_credentials.yml
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/60_repository_eks_credentials.yml
Labels: skip-changelog

#7868 Document testing of discovery-ec2 and repository-s3.
  plugins/discovery-ec2/README.md
  plugins/discovery-ec2/src/main/java/org/opensearch/discovery/ec2/Ec2NameResolver.java
  plugins/repository-s3/README.md
Labels: skip-changelog

#8124 [Backport 1.x] Bump guava bump to 32.0.1-jre
  CHANGELOG.md
  buildSrc/version.properties
  distribution/tools/keystore-cli/build.gradle
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/upgrade-cli/build.gradle
  plugins/ingest-attachment/build.gradle
  plugins/ingest-attachment/licenses/guava-18.0.jar.sha1
  plugins/ingest-attachment/licenses/guava-32.0.1-jre.jar.sha1
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/guava-31.1-jre.jar.sha1
  plugins/repository-azure/licenses/guava-32.0.1-jre.jar.sha1
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/guava-30.1.1-jre.jar.sha1
  plugins/repository-gcs/licenses/guava-32.0.1-jre.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/guava-30.1.1-jre.jar.sha1
  plugins/repository-hdfs/licenses/guava-32.0.1-jre.jar.sha1
Labels: backport 1.3

#8117 [Backport] Remove default s3 region (#7989)
  plugins/repository-s3/build.gradle
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ServiceTests.java
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/20_repository_permanent_credentials.yml
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/30_repository_temporary_credentials.yml
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/40_repository_ec2_credentials.yml
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/50_repository_ecs_credentials.yml
  plugins/repository-s3/src/yamlRestTest/resources/rest-api-spec/test/repository_s3/60_repository_eks_credentials.yml
Labels: skip-changelog

#8160 Bump json-smart from 2.4.7 to 2.4.11 in plugins/repository-hdfs/
  CHANGELOG.md
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/json-smart-2.4.11.jar.sha1
  plugins/repository-hdfs/licenses/json-smart-2.4.7.jar.sha1
Labels: backport 1.3

#8096 Consume all params and content on extension Rest Request exception
  server/src/main/java/org/opensearch/rest/extensions/RestSendToExtensionAction.java
Labels: backport 2.x, skip-changelog

#8181 Bump 'mockito' from 5.2.0 to 5.4.0
  CHANGELOG.md
  buildSrc/version.properties
Labels: dependencies, backport 2.x

#6969 [CCI] [Extensions] Added the ExtensionActionUtil class
  server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
  server/src/test/java/org/opensearch/extensions/action/ExtensionActionUtilTests.java
Labels: backport 2.x, skip-changelog

#8178 Add action to label and close stalled PRs
  .github/workflows/stalled.yml
Labels: skip-changelog

#7998 Add a gradle task to check compability with child components
  build.gradle
  buildSrc/build.gradle
  buildSrc/src/main/groovy/org/opensearch/gradle/CheckCompatibilityTask.groovy
Labels: skip-changelog

#8063 Fix #7972 SearchBackpressureIT flaky tests
  server/src/internalClusterTest/java/org/opensearch/search/backpressure/SearchBackpressureIT.java
  server/src/main/java/org/opensearch/tasks/CancellableTask.java
Labels: skip-changelog

#8206 Return null for aggregations factory even if empty aggs is present in search source
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/60_empty.yml
  server/src/main/java/org/opensearch/search/aggregations/AggregatorFactories.java
Labels: backport 2.x, skip-changelog

#8175 [Remote translog] Make translog buffer interval setting dynamic
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexTranslogDisabledIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessor.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/common/util/concurrent/BufferedAsyncIOProcessorTests.java
  server/src/test/java/org/opensearch/index/IndexServiceTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
Labels: durability, skip-changelog, v2.9.0

#8186 [Segment Replication + Remote Storage] Remove implicit replication strategy change when configuring remote storage with cluster setting
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: skip-changelog

#8185 Update compressed cluster state version guard
  server/src/main/java/org/opensearch/cluster/coordination/JoinHelper.java
Labels: skip-changelog

#8233 Force nebula plugins to use latest org.bouncycastle:* artifacts
  CHANGELOG.md
  buildSrc/build.gradle
Labels: dependencies, backport 1.3

#7350 adds storage & query layer to events correlation engine
  plugins/events-correlation-engine/src/javaRestTest/java/org/opensearch/plugin/correlation/CorrelationVectorsEngineIT.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/EventsCorrelationPlugin.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/CorrelationParamsContext.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/VectorField.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/BasePerFieldCorrelationVectorsFormat.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/CorrelationCodecService.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/CorrelationCodecVersion.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/correlation950/CorrelationCodec.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/correlation950/PerFieldCorrelationVectorsFormat.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/correlation950/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/mapper/CorrelationVectorFieldMapper.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/mapper/VectorFieldMapper.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/mapper/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/query/CorrelationQueryBuilder.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/query/CorrelationQueryFactory.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/query/package-info.java
  plugins/events-correlation-engine/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/CorrelationParamsContextTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/VectorFieldTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/codec/correlation950/CorrelationCodecTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/mapper/CorrelationVectorFieldMapperTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/query/CorrelationQueryBuilderTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/settings/EventsCorrelationSettingsTests.java
Labels: skip-changelog

#8228 [Extensions] Fixed duplicate extension unique id
  server/src/main/java/org/opensearch/transport/TransportService.java
Labels: skip-changelog

#8235 [Segment Replication + Remote Store] Removing exception throw when remote store is used with system indices
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: skip-changelog

#8244 Mute Flaky Test SegmentReplicationAllocationIT.testPerIndexPrimaryAllocation
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
Labels: backport 2.x, skip-changelog

#8203 [Segment Replication] Update segrep bwc tests to verify replica checkpoints and skip tests for 1.x bwc versions
  qa/mixed-cluster/build.gradle
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/IndexingIT.java
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: skip-changelog

#8243 [Backport 2.x] Backport PR's #8186 and #8235
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexClusterDefaultDocRep.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/CreateRemoteIndexIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: skip-changelog

#8261 [Backport 2.x] [Refactor] more ImmutableOpenMap to jdk Map in cluster package (#7301)
  CHANGELOG.md
  client/rest-high-level/src/test/java/org/opensearch/client/indices/GetIndexResponseTests.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/alias/ValidateIndicesAliasesRequestIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/get/GetIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/aliases/IndexAliasesIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterStateDiffIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesLifecycleListenerIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreClusterStateListener.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/TransportIndicesAliasesAction.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/get/GetAliasesResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/get/TransportGetAliasesAction.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/get/TransportGetIndexAction.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/ClusterState.java
  server/src/main/java/org/opensearch/cluster/RestoreInProgress.java
  server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
  server/src/main/java/org/opensearch/cluster/block/ClusterBlocks.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataDeleteIndexService.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitor.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/RoutingAllocation.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetAliasesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestAliasAction.java
  server/src/main/java/org/opensearch/snapshots/InFlightShardSnapshotStates.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/action/admin/indices/alias/get/GetAliasesResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/alias/get/TransportGetAliasesActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/datastream/DeleteDataStreamRequestTests.java
  server/src/test/java/org/opensearch/action/admin/indices/get/GetIndexResponseTests.java
  server/src/test/java/org/opensearch/cluster/ClusterStateTests.java
  server/src/test/java/org/opensearch/cluster/block/ClusterBlockTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataDeleteIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexStateServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AddIncrementallyTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/BalanceConfigurationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/ThrottlingAllocationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/RestoreInProgressAllocationDeciderTests.java
  server/src/test/java/org/opensearch/cluster/serialization/ClusterSerializationTests.java
  server/src/test/java/org/opensearch/rest/action/admin/indices/RestGetAliasesActionTests.java
  server/src/test/java/org/opensearch/snapshots/InternalSnapshotsInfoServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotsInProgressSerializationTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotsServiceTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: backport, v2.9.0

#8263 [Backport] [2.x] Bump io.projectreactor.netty:reactor-netty-http from 1.1.7 to 1.1.8 in /plugins/repository-azure (#8256)
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/reactor-netty-http-1.1.7.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.8.jar.sha1
Labels: backport, dependencies

#8266 [Backport 2.x] [Refactor] ImmutableOpenMap to j.u.Map in IndexMetadata (#7306)
  CHANGELOG.md
  client/rest-high-level/src/main/java/org/opensearch/client/indices/IndexTemplateMetadata.java
  client/rest-high-level/src/test/java/org/opensearch/client/indices/GetIndexTemplatesResponseTests.java
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterStateDiffIT.java
  server/src/main/java/org/opensearch/action/admin/indices/get/TransportGetIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/resolve/ResolveIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverService.java
  server/src/main/java/org/opensearch/cluster/DiffableUtils.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/gateway/DanglingIndicesState.java
  server/src/main/java/org/opensearch/search/internal/ShardSearchRequest.java
  server/src/main/java/org/opensearch/snapshots/EmptySnapshotsInfoService.java
  server/src/main/java/org/opensearch/snapshots/InternalSnapshotsInfoService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardSizeInfo.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexTemplateMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/NodeVersionAllocationDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/ThrottlingAllocationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/cluster/serialization/DiffableTests.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
Labels: backport, v2.9.0

#8135 Add integ tests for remote store stats api
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
Labels: skip-changelog

#8270 Make 2.x as default branch for check compatibility task
  buildSrc/src/main/groovy/org/opensearch/gradle/CheckCompatibilityTask.groovy
Labels: skip-changelog

#8272 [Upgrade] Lucene 9.7.0 release
  CHANGELOG.md
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.7.0-snapshot-204acc3.jar.sha1
  libs/core/licenses/lucene-core-9.7.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.7.0-snapshot-204acc3.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.7.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.7.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.7.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.7.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.7.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.7.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.7.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.7.0-snapshot-204acc3.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.7.0.jar.sha1
  server/licenses/lucene-analysis-common-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-analysis-common-9.7.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-backward-codecs-9.7.0.jar.sha1
  server/licenses/lucene-core-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-core-9.7.0.jar.sha1
  server/licenses/lucene-grouping-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-grouping-9.7.0.jar.sha1
  server/licenses/lucene-highlighter-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-highlighter-9.7.0.jar.sha1
  server/licenses/lucene-join-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-join-9.7.0.jar.sha1
  server/licenses/lucene-memory-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-memory-9.7.0.jar.sha1
  server/licenses/lucene-misc-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-misc-9.7.0.jar.sha1
  server/licenses/lucene-queries-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-queries-9.7.0.jar.sha1
  server/licenses/lucene-queryparser-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-queryparser-9.7.0.jar.sha1
  server/licenses/lucene-sandbox-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-sandbox-9.7.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-spatial-extras-9.7.0.jar.sha1
  server/licenses/lucene-spatial3d-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-spatial3d-9.7.0.jar.sha1
  server/licenses/lucene-suggest-9.7.0-snapshot-204acc3.jar.sha1
  server/licenses/lucene-suggest-9.7.0.jar.sha1
  server/src/main/java/org/opensearch/index/search/MatchQuery.java
  server/src/main/java/org/opensearch/index/search/MultiMatchQuery.java
Labels: non-issue, >upgrade

#8134 Fix SegmentReplication flaky integ tests
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#8277 [Backport 2.x] [Upgrade] Lucene 9.7.0 release (#8272)
  CHANGELOG.md
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.6.0.jar.sha1
  libs/core/licenses/lucene-core-9.7.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.6.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.7.0.jar.sha1
  modules/parent-join/src/test/java/org/opensearch/join/query/HasChildQueryBuilderTests.java
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.6.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.7.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.6.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.7.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.6.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.7.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.6.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.7.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.6.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.7.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.6.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.7.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.6.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.7.0.jar.sha1
  server/licenses/lucene-analysis-common-9.6.0.jar.sha1
  server/licenses/lucene-analysis-common-9.7.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.6.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.7.0.jar.sha1
  server/licenses/lucene-core-9.6.0.jar.sha1
  server/licenses/lucene-core-9.7.0.jar.sha1
  server/licenses/lucene-grouping-9.6.0.jar.sha1
  server/licenses/lucene-grouping-9.7.0.jar.sha1
  server/licenses/lucene-highlighter-9.6.0.jar.sha1
  server/licenses/lucene-highlighter-9.7.0.jar.sha1
  server/licenses/lucene-join-9.6.0.jar.sha1
  server/licenses/lucene-join-9.7.0.jar.sha1
  server/licenses/lucene-memory-9.6.0.jar.sha1
  server/licenses/lucene-memory-9.7.0.jar.sha1
  server/licenses/lucene-misc-9.6.0.jar.sha1
  server/licenses/lucene-misc-9.7.0.jar.sha1
  server/licenses/lucene-queries-9.6.0.jar.sha1
  server/licenses/lucene-queries-9.7.0.jar.sha1
  server/licenses/lucene-queryparser-9.6.0.jar.sha1
  server/licenses/lucene-queryparser-9.7.0.jar.sha1
  server/licenses/lucene-sandbox-9.6.0.jar.sha1
  server/licenses/lucene-sandbox-9.7.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.6.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.7.0.jar.sha1
  server/licenses/lucene-spatial3d-9.6.0.jar.sha1
  server/licenses/lucene-spatial3d-9.7.0.jar.sha1
  server/licenses/lucene-suggest-9.6.0.jar.sha1
  server/licenses/lucene-suggest-9.7.0.jar.sha1
  server/src/main/java/org/apache/lucene/search/vectorhighlight/CustomFieldQuery.java
  server/src/main/java/org/opensearch/Version.java
  server/src/test/java/org/opensearch/lucene/queries/SpanMatchNoDocsQueryTests.java
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: backport, >upgrade

#8197 [Remote Store] Add remote segment upload backpressure integ tests
  server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureIT.java
  test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java
Labels: durability, skip-changelog, v2.9.0

#8268 [Backport] [2.x] Bump org.apache.hadoop:hadoop-minicluster from 3.3.5 to 3.3.6 in /test/fixtures/hdfs-fixture (#8257)
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport, dependencies

#8209 Bump `resteasy-jackson2-provider` from 3.0.26.Final to 6.2.4.Final in /qa/wildfly
  CHANGELOG.md
  buildSrc/version.properties
  qa/wildfly/build.gradle
  qa/wildfly/docker-compose.yml
  qa/wildfly/src/main/java/org/opensearch/wildfly/model/Employee.java
  qa/wildfly/src/main/java/org/opensearch/wildfly/transport/RestHighLevelClientActivator.java
  qa/wildfly/src/main/java/org/opensearch/wildfly/transport/RestHighLevelClientEmployeeResource.java
  qa/wildfly/src/main/java/org/opensearch/wildfly/transport/RestHighLevelClientProducer.java
  qa/wildfly/src/main/java/org/opensearch/wildfly/transport/RestHighLevelJacksonJsonProvider.java
  qa/wildfly/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
Labels: dependencies, backport 2.x

#8290 Fix Apache Lucene verson for 2.9.0 release
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#8177 [Backport-2.x] Add latest local and remote refresh timestamps in the …
  server/src/main/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStats.java
  server/src/main/java/org/opensearch/index/remote/RemoteRefreshSegmentTracker.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/stats/RemoteStoreStatsTestHelper.java
Labels: skip-changelog

#6788 [Snapshot Interop] Add Changes in Restore Snapshot Flow for remote store Interoperability
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.restore.json
  server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestBuilder.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/opensearch/repositories/FilterRepository.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestTests.java
  server/src/test/java/org/opensearch/cluster/routing/RecoverySourceTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: skip-changelog, first-time-contributor

#8207 Removed redundant ubuntu precommit check
  .github/workflows/gradle-check.yml
  .github/workflows/precommit.yml
Labels: backport 2.x, skip-changelog

#8319 [Snapshot Interop] Change Version Checks from 3.0 to 2.9 in Restore S…
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
Labels: skip-changelog

#8267 [Segment Replication] Update bwc test to rely on segments for verification
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: skip-changelog

#8323 [1.3] Clear out changelog after release
  CHANGELOG.md
Labels: skip-changelog

#8324 [Mute] SegRepUsingRemoteStoreIT.testPressureServiceStats
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
Labels: >test-failure, cicd, flaky-test, skip-changelog

#8053 [Search Pipelines] Add stats for search pipelines
  CHANGELOG.md
  modules/ingest-common/src/internalClusterTest/java/org/opensearch/ingest/common/IngestRestartIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/common/metrics/MeanMetric.java
  server/src/main/java/org/opensearch/common/metrics/OperationMetrics.java
  server/src/main/java/org/opensearch/common/metrics/OperationStats.java
  server/src/main/java/org/opensearch/ingest/CompoundProcessor.java
  server/src/main/java/org/opensearch/ingest/ConditionalProcessor.java
  server/src/main/java/org/opensearch/ingest/IngestMetric.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/ingest/IngestStats.java
  server/src/main/java/org/opensearch/ingest/Pipeline.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
  server/src/main/java/org/opensearch/search/pipeline/PipelineWithMetrics.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineStats.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodesTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  server/src/test/java/org/opensearch/ingest/CompoundProcessorTests.java
  server/src/test/java/org/opensearch/ingest/ConditionalProcessorTests.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
  server/src/test/java/org/opensearch/ingest/IngestStatsTests.java
  server/src/test/java/org/opensearch/ingest/PipelineProcessorTests.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineStatsTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: v3.0.0, backport 2.x, Search, v2.9.0

#8276 Bump com.google.api-client:google-api-client from 1.34.0 to 2.2.0 in /plugins/repository-gcs
  CHANGELOG.md
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/google-api-client-1.34.0.jar.sha1
  plugins/repository-gcs/licenses/google-api-client-2.2.0.jar.sha1
  plugins/repository-gcs/licenses/google-api-services-storage-v1-rev20220608-1.32.1.jar.sha1
  plugins/repository-gcs/licenses/google-api-services-storage-v1-rev20230617-2.0.0.jar.sha1
  plugins/repository-gcs/licenses/google-http-client-gson-1.41.4.jar.sha1
  plugins/repository-gcs/licenses/google-http-client-gson-1.43.2.jar.sha1
  plugins/repository-gcs/licenses/google-http-client-jackson2-1.42.3.jar.sha1
  plugins/repository-gcs/licenses/google-http-client-jackson2-1.43.2.jar.sha1
  plugins/repository-gcs/licenses/google-oauth-client-1.33.3.jar.sha1
  plugins/repository-gcs/licenses/google-oauth-client-1.34.1.jar.sha1
Labels: dependencies, backport 2.x

#7318 Implement buildEmptyAggregations for MultiTermsAggregator (#7089)
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/370_multi_terms.yml
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregatorTests.java
Labels: backport 2.x, v2.9.0

#7283 Adding the SearchPhaseResultsProcessor interface in Search Pipeline
  CHANGELOG.md
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/50_script_processor.yml
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/ArraySearchPhaseResults.java
  server/src/main/java/org/opensearch/action/search/CanMatchPreFilterSearchPhase.java
  server/src/main/java/org/opensearch/action/search/DfsQueryPhase.java
  server/src/main/java/org/opensearch/action/search/ExpandSearchPhase.java
  server/src/main/java/org/opensearch/action/search/FetchSearchPhase.java
  server/src/main/java/org/opensearch/action/search/SearchPhase.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseContext.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseName.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseResults.java
  server/src/main/java/org/opensearch/action/search/SearchScrollAsyncAction.java
  server/src/main/java/org/opensearch/action/search/SearchScrollQueryThenFetchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/plugins/SearchPipelinePlugin.java
  server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
  server/src/main/java/org/opensearch/search/pipeline/PipelineWithMetrics.java
  server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPhaseResultsProcessor.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: backport 2.x, Search, v2.9.0

#8237 Handle case where IndexShard is null due to failed creation of index
  server/src/main/java/org/opensearch/index/IndexService.java
Labels: skip-changelog

#7902 [Fix] Replace cached time with system clock in MasterService debug logs
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
Labels: backport 2.x

#8359 Fix HDFS fixture by excluding BouncyCastle
  test/fixtures/hdfs-fixture/build.gradle
Labels: skip-changelog

#8358 Update search.aggregation/370_multi_terms.yml after backport
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/370_multi_terms.yml
Labels: skip-changelog

#8366 Fix primary balance flaky test
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
Labels: backport 2.x, skip-changelog

#8351 Fix search.aggregation/60_empty.yml test case (fails on BWC runs)
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/60_empty.yml
Labels: flaky-test, skip-changelog

#8362 [Backport] [2.x] Fix HDFS fixture by excluding BouncyCastle (#8359)
  test/fixtures/hdfs-fixture/build.gradle
Labels: skip-changelog

#8295 [Backport 2.x] GeoTile, and GeoGrid aggregation
  CHANGELOG.md
  modules/geo/build.gradle
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/GeoModulePluginIntegTestCase.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/AbstractGeoBucketAggregationIntegTest.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoHashGridIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/bucket/GeoTileGridIT.java
  modules/geo/src/internalClusterTest/java/org/opensearch/geo/search/aggregations/metrics/AbstractGeoAggregatorModulePluginTestCase.java
  modules/geo/src/main/java/org/opensearch/geo/GeoModulePlugin.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/composite/GeoTileGridValuesSourceBuilder.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/GeoGridAggregatorSupplier.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/GeoHashGridAggregationBuilder.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/GeoHashGridAggregatorFactory.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/GeoTileGridAggregationBuilder.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/GeoTileGridAggregatorFactory.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/cells/BoundedCellValues.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/cells/CellIdSource.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/cells/CellValues.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/cells/GeoShapeCellIdSource.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/cells/GeoShapeCellValues.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/cells/UnboundedCellValues.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/cells/package-info.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/bucket/geogrid/util/GeoShapeHashUtil.java
  modules/geo/src/main/java/org/opensearch/geo/search/aggregations/metrics/GeoBoundsAggregatorFactory.java
  modules/geo/src/test/java/org/opensearch/geo/tests/common/RandomGeoGenerator.java
  modules/geo/src/test/java/org/opensearch/geo/tests/common/RandomGeoGeometryGenerator.java
  server/src/main/java/org/opensearch/common/geo/GeoShapeDocValue.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/GeoTileUtils.java
Labels: feature, backport, Geospatial, v2.9.0

#8372 Add lower and upper bound support for appropriate variance thresholds
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
Labels: skip-changelog

#8380 [Backport 2.x] Fix primary balance flaky test
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
Labels: skip-changelog

#8385 Fix version script for higher patch numbers
  .github/workflows/version.yml
Labels: backport 1.x, backport 2.x, backport 1.3, skip-changelog
