Repository opensearch-project/OpenSearch, pull requests merged in 2023-10, with the labels that each got.

#10302 Bump asm from 9.5 to 9.6
  CHANGELOG.md
  buildSrc/version.properties
  modules/lang-expression/licenses/asm-9.5.jar.sha1
  modules/lang-expression/licenses/asm-9.6.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.5.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.6.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.5.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.6.jar.sha1
  modules/lang-painless/licenses/asm-9.5.jar.sha1
  modules/lang-painless/licenses/asm-9.6.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.5.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.6.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.5.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.6.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.5.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.6.jar.sha1
  modules/lang-painless/licenses/asm-util-9.5.jar.sha1
  modules/lang-painless/licenses/asm-util-9.6.jar.sha1
Labels: dependencies

#10194 Fix circular dependency in Settings initialization
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/Settings.java
Labels: bug, Clients & Libraries

#10200 Support terminate_after force termination for concurrent segment search
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/simple/ParameterizedSimpleSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
Labels: enhancement, backlog, distributed framework, backport 2.x

#10289 Replace deprecated command with environment file
  .github/workflows/lucene-snapshots.yml
Labels: enhancement, skip-changelog

#10242 Add TODO for updating public documentation
  .github/pull_request_template.md
Labels: skip-changelog

#10315 [Backport 2.x] Fix: register mulitple extensions.
  CHANGELOG.md
  server/src/main/java/org/opensearch/extensions/ExtensionsManager.java
  server/src/main/java/org/opensearch/extensions/rest/RestActionsRequestHandler.java
  server/src/main/java/org/opensearch/extensions/rest/RestInitializeExtensionAction.java
  server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/extensions/rest/RestInitializeExtensionActionTests.java
  server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java
Labels: v2.11.0

#10337 [Backport] [2.x] Bump peter-evans/create-pull-request from 3 to 5 (#10301)
  .github/workflows/version.yml
  CHANGELOG.md
Labels: backport

#10325 Fix the HttpChannel trace termination in case of exceptions
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
  server/src/main/java/org/opensearch/http/AbstractHttpServerTransport.java
  server/src/main/java/org/opensearch/http/HttpChannel.java
  server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableHttpChannel.java
  server/src/main/java/org/opensearch/telemetry/tracing/handler/TraceableTransportResponseHandler.java
  server/src/main/java/org/opensearch/transport/TransportResponseHandler.java
Labels: backport 2.x, skip-changelog, v2.11.0

#10312 Backport - Configurable merge policy and option to choose between LogByteSize and Tiered MergePolicy (#9992)
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/internalClusterTest/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommandIT.java
  server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/update/UpdateIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/LogByteSizeMergePolicyProvider.java
  server/src/main/java/org/opensearch/index/MergePolicyProvider.java
  server/src/main/java/org/opensearch/index/TieredMergePolicyProvider.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/action/admin/indices/segments/IndicesSegmentsRequestTests.java
  server/src/test/java/org/opensearch/index/MergePolicySettingsTests.java
  server/src/test/java/org/opensearch/index/MergeSchedulerSettingsTests.java
  server/src/test/java/org/opensearch/index/shard/RemoveCorruptedShardDataCommandTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: v2.11.0

#10336 Changing unrefernced file cleanup stats based MergeStats metrics version to 2.11
  server/src/main/java/org/opensearch/index/merge/MergeStats.java
Labels: skip-changelog

#10229 Add node id to segment and translog metadata
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/TranslogConfig.java
  server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
  server/src/test/java/org/opensearch/index/translog/LocalTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogManagerTestCase.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#10341 Retry on failure to acquire lock on remote metadata
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
Labels: skip-changelog

#10356 Enable remote segment upload backpressure by default
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/remote/RemoteStorePressureSettings.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureSettingsTests.java
Labels: enhancement, Storage:Durability, v2.11.0

#10363 Fix shard failure due to translog tragic close on upload failure
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Labels: bug, Storage:Durability, backport 2.x, skip-changelog

#10349 Refactor multipart download to a more async model
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsAsyncBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/AsyncMultiStreamBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/ReadContext.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/FileCompletionListener.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/FilePartWriter.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListener.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainerTests.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/FileCompletionListenerTests.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/FilePartWriterTests.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/indices/recovery/DefaultRecoverySettings.java
Labels: backport 2.x, skip-changelog, v2.11.0

#10372 Mute DeleteSnapshotIT.testDeleteShallowCopySnapshot
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
Labels: backport 2.x, skip-changelog

#10369 [Backport] [2.x] Bump org.xerial.snappy:snappy-java from 1.1.10.4 to 1.1.10.5 in /test/fixtures/hdfs-fixture (#10299)
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport

#9567 Added performance improvement for datetime field parsing
  CHANGELOG.md
  distribution/src/config/opensearch.yml
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DateHistogramIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DateHistogramOffsetIT.java
  server/src/main/java/org/opensearch/common/joda/JodaDateFormatter.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/time/DateFormatter.java
  server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/RangeFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/RangeType.java
  server/src/main/java/org/opensearch/index/mapper/RootObjectMapper.java
  server/src/main/java/org/opensearch/script/ScoreScriptUtils.java
  server/src/main/java/org/opensearch/search/DocValueFormat.java
  server/src/main/java/org/opensearch/search/aggregations/support/CoreValuesSourceType.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValueType.java
  server/src/test/java/org/opensearch/action/search/BottomSortValuesCollectorTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/RangeQueryBuilderTests.java
  server/src/test/java/org/opensearch/search/aggregations/AggregatorBaseTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTestCase.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateRangeHistogramAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/DateRangeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/pipeline/AvgBucketAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/pipeline/CumulativeSumAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/pipeline/MovFnAggrgatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/composite/BaseCompositeAggregatorTestCase.java
Labels: enhancement

#10143 [Tracing Instrumentation] Add instrumentation in InboundHandler
  CHANGELOG.md
  modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4ModulePlugin.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/Netty4Transport.java
  modules/transport-netty4/src/test/java/org/opensearch/transport/netty4/Netty4SizeHeaderFrameDecoderTests.java
  modules/transport-netty4/src/test/java/org/opensearch/transport/netty4/NettyTransportMultiPortTests.java
  modules/transport-netty4/src/test/java/org/opensearch/transport/netty4/SimpleNetty4TransportTests.java
  plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2DiscoveryTests.java
  plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2RetriesTests.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelSpan.java
  plugins/transport-nio/src/main/java/org/opensearch/transport/nio/NioTransport.java
  plugins/transport-nio/src/main/java/org/opensearch/transport/nio/NioTransportPlugin.java
  plugins/transport-nio/src/test/java/org/opensearch/transport/nio/SimpleNioTransportTests.java
  server/src/main/java/org/opensearch/common/network/NetworkModule.java
  server/src/main/java/org/opensearch/plugins/NetworkPlugin.java
  server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
  server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
  server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableTcpTransportChannel.java
  server/src/main/java/org/opensearch/transport/BaseTcpTransportChannel.java
  server/src/main/java/org/opensearch/transport/InboundHandler.java
  server/src/main/java/org/opensearch/transport/RequestHandlerRegistry.java
  server/src/main/java/org/opensearch/transport/TcpTransport.java
  server/src/main/java/org/opensearch/transport/TcpTransportChannel.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/TaskManagerTestCase.java
  server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
  server/src/test/java/org/opensearch/action/support/replication/BroadcastReplicationTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportReplicationActionTests.java
  server/src/test/java/org/opensearch/common/network/NetworkModuleTests.java
  server/src/test/java/org/opensearch/discovery/FileBasedSeedHostsProviderTests.java
  server/src/test/java/org/opensearch/discovery/SeedHostsResolverTests.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java
  server/src/test/java/org/opensearch/extensions/rest/RestInitializeExtensionActionTests.java
  server/src/test/java/org/opensearch/extensions/rest/RestSendToExtensionActionTests.java
  server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/TcpTransportTests.java
  server/src/test/java/org/opensearch/transport/TransportServiceHandshakeTests.java
  test/framework/src/main/java/org/opensearch/test/transport/MockTransportService.java
  test/framework/src/main/java/org/opensearch/transport/nio/MockNioTransport.java
  test/framework/src/main/java/org/opensearch/transport/nio/MockNioTransportPlugin.java
  test/framework/src/test/java/org/opensearch/transport/nio/SimpleMockNioTransportTests.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/MockSpan.java
Labels: enhancement, distributed framework, v3.0.0, v2.11.0

#10347 Update multipart download path to first write to temp files
  server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListener.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java
Labels: bug, distributed framework, backport 2.x, skip-changelog, v2.11.0

#9569 [Remote Store] Add support to reload repository metadata inplace
  CHANGELOG.md
  modules/repository-url/src/main/java/org/opensearch/repositories/url/URLRepository.java
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureRepository.java
  plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageRepository.java
  plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsRepository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/main/java/org/opensearch/common/blobstore/BlobStore.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/repositories/blobstore/MeteredBlobStoreRepository.java
  server/src/main/java/org/opensearch/repositories/fs/FsRepository.java
  server/src/main/java/org/opensearch/repositories/fs/ReloadableFsRepository.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  server/src/test/java/org/opensearch/repositories/fs/ReloadableFsRepositoryTests.java
  server/src/test/java/org/opensearch/snapshots/mockstore/MockEventuallyConsistentRepository.java
Labels: bug, Storage:Durability, backport 2.x, Storage, v2.11.0

#10326 Adding cancellation start time in client side TaskInfo
  client/rest-high-level/src/main/java/org/opensearch/client/tasks/TaskInfo.java
  client/rest-high-level/src/test/java/org/opensearch/client/tasks/CancelTasksResponseTests.java
Labels: backport 2.x, skip-changelog

#10373 [Backport 2.x] Refactor multipart download to a more async model
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsAsyncBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/AsyncMultiStreamBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/ReadContext.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/FileCompletionListener.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/FilePartWriter.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListener.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainerTests.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/FileCompletionListenerTests.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/FilePartWriterTests.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/indices/recovery/DefaultRecoverySettings.java
Labels: skip-changelog

#10389 [Backport 2.x] Update multipart download path to first write to temp files
  server/src/main/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListener.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java
Labels: skip-changelog

#10016 fix stale remote cluster uuid state not purged from remote
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#10408 Update TODO for updating public documentation
  .github/pull_request_template.md
Labels: skip-changelog

#10386 [Backport 2.x] Bump org.apache.commons:commons-compress from 1.23.0 to 1.24.0 in /buildSrc
  buildSrc/build.gradle
Labels: dependencies, skip-changelog

#10385 Race condition fix for datetime optimization
  server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java
Labels: enhancement, skip-changelog

#10370 Segment Replication - Fix ShardLockObtained error during corruption cases
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
Labels: bug, backport 2.x, Indexing, Indexing:Replication, v2.11.0

#10406 Fix error handling for future completion
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
Labels: backport 2.x, skip-changelog, v2.11.0

#10402 [Remote Store] Fix stats reporting for multistream downloads.
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: enhancement, distributed framework, backport 2.x, skip-changelog, Indexing:Replication, v2.11.0

#10379 Updating the separator for RemoteStoreLockManager since underscore is allowed in base64UUID url charset
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/main/java/org/opensearch/index/store/lockmanager/FileLockInfo.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerUtils.java
  server/src/test/java/org/opensearch/index/store/lockmanager/FileLockInfoTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryHelperTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
Labels: bug, flaky-test, v2.11.0

#10418 [Backport 2.x] Segment Replication - Fix ShardLockObtained error during corruption cases #10370
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
Labels: backport 2.11

#10261 Allow customization of netty channel handles before and during decompression
  CHANGELOG.md
  modules/transport-netty4/src/internalClusterTest/java/org/opensearch/http/netty4/Netty4HeaderVerifierIT.java
  modules/transport-netty4/src/internalClusterTest/java/org/opensearch/transport/Netty4BlockingPlugin.java
  modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4ModulePlugin.java
  server/src/main/java/org/opensearch/rest/RestHandler.java
Labels: enhancement, backport 2.x, v2.11.0, backport 2.11

#10452 Fix to include static settings in addition to dynamic repo metadata
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
Labels: skip-changelog

#10138 Update Gradle to 8.4
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalBwcGitPlugin.java
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: Build Libraries & Interfaces, skip-changelog

#10458 Bump 2.x to 2.12
  .ci/bwcVersions
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#10468 Bump 2.10 branch to 2.10.1
  .ci/bwcVersions
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#10437 Mute flaky concurrent segment search tests pending fixes
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DiversifiedSamplerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fieldcaps/FieldCapabilitiesIT.java
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: backport 2.x, skip-changelog

#10465 Add 2.10.1 to 2.x branch
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#10470 [Forwardport] [2.11] Add 2.10.1 to 2.11 branch
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#10461 [Forwardport] Bump 2.x to 2.12 (#10458)
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#10480 [Remote Store] Using hash of node id in metadata file names
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: bug, backport 2.x, skip-changelog, v2.11.0, backport 2.11

#10464 Fix flaky testRemoteRefreshRetryOnFailure in RemoteStoreRefreshListenerIT
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
Labels: bug, Storage:Durability, skip-changelog

#10490 Fix failing testGetPrimaryTermAndGeneration in TranslogTransferManagerTests
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: bug, Storage:Durability, skip-changelog

#10491 [Backport 2.x] [Remote Store] Using hash of node id in metadata file names
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#10449 Fix bugs causing red indexes with remote indexes during translog upload & store recovery
  server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureAndResiliencyIT.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: bug, Storage:Durability, backport 2.x, skip-changelog

#10492 [Backport 2.11] [Remote Store] Using hash of node id in metadata file names
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#10436 Avoid size=0 for terminate_after tests
  server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
Labels: flaky-test, backport 2.x, skip-changelog, Search

#10427 Fix ScalingThreadPoolTest to handle new pool
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: backport 2.x, skip-changelog, backport 2.11

#10388 Mute MoreExpressionIT.testSpecialValueVariable
  modules/lang-expression/src/internalClusterTest/java/org/opensearch/script/expression/MoreExpressionIT.java
Labels: skip-changelog

#10519 Replace multipart download with parallel file download
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/RemoteStoreFileDownloader.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteStoreFileDownloaderTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: bug, distributed framework, backport 2.x, skip-changelog, v2.11.0, backport 2.11

#10445 [S3 Repository] Make bulk delete size configurable
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
Labels: enhancement, backport 2.x, skip-changelog

#10547 Fix flaky query profile phase tests with concurrent search enabled
  CHANGELOG.md
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: bug, flaky-test, skip-changelog

#10562 Add the means to extract the contextual properties from HttpChannel, TcpChannel and TrasportChannel without excessive typecasting
  CHANGELOG.md
  modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpChannel.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/Netty4TcpChannel.java
  server/src/main/java/org/opensearch/http/HttpChannel.java
  server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableHttpChannel.java
  server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableTcpTransportChannel.java
  server/src/main/java/org/opensearch/transport/TaskTransportChannel.java
  server/src/main/java/org/opensearch/transport/TcpChannel.java
  server/src/main/java/org/opensearch/transport/TcpTransportChannel.java
  server/src/main/java/org/opensearch/transport/TransportChannel.java
Labels: enhancement, backport 2.x, skip-changelog

#10360 [Backport] [2.x] Upgrade Lucene to 9.8.0
  CHANGELOG.md
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.7.0.jar.sha1
  libs/core/licenses/lucene-core-9.8.0.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.7.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.8.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.7.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.8.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.7.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.8.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.7.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.8.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.7.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.8.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.7.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.8.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.7.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.8.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.7.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.8.0.jar.sha1
  server/licenses/lucene-analysis-common-9.7.0.jar.sha1
  server/licenses/lucene-analysis-common-9.8.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.7.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.8.0.jar.sha1
  server/licenses/lucene-core-9.7.0.jar.sha1
  server/licenses/lucene-core-9.8.0.jar.sha1
  server/licenses/lucene-grouping-9.7.0.jar.sha1
  server/licenses/lucene-grouping-9.8.0.jar.sha1
  server/licenses/lucene-highlighter-9.7.0.jar.sha1
  server/licenses/lucene-highlighter-9.8.0.jar.sha1
  server/licenses/lucene-join-9.7.0.jar.sha1
  server/licenses/lucene-join-9.8.0.jar.sha1
  server/licenses/lucene-memory-9.7.0.jar.sha1
  server/licenses/lucene-memory-9.8.0.jar.sha1
  server/licenses/lucene-misc-9.7.0.jar.sha1
  server/licenses/lucene-misc-9.8.0.jar.sha1
  server/licenses/lucene-queries-9.7.0.jar.sha1
  server/licenses/lucene-queries-9.8.0.jar.sha1
  server/licenses/lucene-queryparser-9.7.0.jar.sha1
  server/licenses/lucene-queryparser-9.8.0.jar.sha1
  server/licenses/lucene-sandbox-9.7.0.jar.sha1
  server/licenses/lucene-sandbox-9.8.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.7.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.8.0.jar.sha1
  server/licenses/lucene-spatial3d-9.7.0.jar.sha1
  server/licenses/lucene-spatial3d-9.8.0.jar.sha1
  server/licenses/lucene-suggest-9.7.0.jar.sha1
  server/licenses/lucene-suggest-9.8.0.jar.sha1
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/ConcurrentSearchTasksIT.java
  server/src/internalClusterTest/java/org/opensearch/search/functionscore/ExplainableScriptIT.java
  server/src/main/java/org/opensearch/common/lucene/Lucene.java
  server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java
  server/src/main/java/org/opensearch/index/search/comparators/UnsignedLongComparator.java
  server/src/main/java/org/opensearch/search/suggest/completion/CompletionSuggester.java
Labels: backport

#10549 [Backport 2.11] Replace multipart download with parallel file download
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/RemoteStoreFileDownloader.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteStoreFileDownloaderTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#10572 [Backport] [1.3] Bump netty from 4.1.99.Final to 4.1.100.Final (#10564)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.99.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.99.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.99.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.99.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.99.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.99.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.99.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.100.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.99.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.99.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.99.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.99.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.99.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.99.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.100.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.99.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.100.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.99.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.99.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.99.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.99.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.99.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.99.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.99.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.100.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.99.Final.jar.sha1
Labels: backport, dependencies

#10578 Update OpenSearch 2.12 to use Apache Lucene 9.8.0
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#10513 Fix shard failure on flush during upload failures for remote indexes
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureAndResiliencyIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogUploadFailedException.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Labels: bug, Storage:Durability, skip-changelog

#10585 [Backport 2.x] Fix shard failure on flush during upload failures for remote indexes
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureAndResiliencyIT.java
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogUploadFailedException.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Labels: skip-changelog

#10556 Fix system_repository setting is restored after cluster metadata recovery from local disk
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRepositoryRegistrationIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/repositories/get/GetRepositoriesResponse.java
  server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java
Labels: bug, skip-changelog

#10119 Validate checksum of each segment file post download from remote store
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/Store.java
Labels: skip-changelog, v2.11.0

#10594 Add release notes for 2.11
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.11.0.md
Labels: backport 2.11

#10522 Point deprecated settings to the new location.
  server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java
Labels: skip-changelog

#10601 Remove unrelease commits in 2.11
  release-notes/opensearch.release-notes-2.11.0.md
Labels: skip-changelog

#10607 Add more commits from 2.11 changelog
  release-notes/opensearch.release-notes-2.11.0.md
Labels: skip-changelog

#10606 Backport PR-9107 to make search.concurrent.max_slice_count setting dy…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/memory/breaker/CircuitBreakerServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/stats/ConcurrentSearchStatsIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchBootstrapSettings.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/main/java/org/opensearch/search/internal/FilteredSearchContext.java
  server/src/main/java/org/opensearch/search/internal/MaxTargetSliceSupplier.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/common/settings/SettingsModuleTests.java
  server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java
  server/src/test/java/org/opensearch/search/internal/IndexReaderUtils.java
  server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
  test/framework/src/main/java/org/opensearch/test/TestSearchContext.java
Labels: v2.12.0

#10617 Bump OpenTelemetry from 1.30.1 to 1.31.0
  CHANGELOG.md
  buildSrc/version.properties
  plugins/telemetry-otel/build.gradle
  plugins/telemetry-otel/licenses/opentelemetry-api-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-extension-incubator-1.30.1-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-extension-incubator-1.31.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.30.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.31.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.21.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.30.1-alpha.jar.sha1
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelResourceProvider.java
Labels: dependencies

#10351 Request level latency tracking
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/MultiSearchRequest.java
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/action/search/SearchResponse.java
  server/src/main/java/org/opensearch/action/search/SearchResponseMerger.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
  server/src/test/java/org/opensearch/action/search/SearchResponseTests.java
  server/src/test/java/org/opensearch/action/search/SearchTimeProviderTests.java
  test/framework/src/main/java/org/opensearch/search/RandomSearchRequestGenerator.java
Labels: enhancement, Search, v2.12.0

#10621 Fix broken test testCommitOnCloseThrowsException_decRefStore
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#10524 [Remote Store] Add Remote Store backpressure rejection stats to _nodes/stats
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Labels: bug, Storage:Remote

#10630 [Remote Store] Update version check for remote store backpressure rejection stats
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentStats.java
Labels: skip-changelog

#10615 [Backport] [2.x] Bump com.google.api.grpc:proto-google-common-protos from 2.25.0 to 2.25.1 in /plugins/repository-gcs (#10298)
  CHANGELOG.md
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/proto-google-common-protos-2.25.0.jar.sha1
  plugins/repository-gcs/licenses/proto-google-common-protos-2.25.1.jar.sha1
Labels: backport

#10614 Remove the authenticate token method from TokenManager and from the Subject interface
  plugins/identity-shiro/src/main/java/org/opensearch/identity/shiro/ShiroTokenManager.java
  plugins/identity-shiro/src/test/java/org/opensearch/identity/shiro/AuthTokenHandlerTests.java
  server/src/main/java/org/opensearch/identity/noop/NoopTokenManager.java
  server/src/main/java/org/opensearch/identity/tokens/TokenManager.java
Labels: skip-changelog

#10642 [BUG] Fix java.lang.SecurityException in repository-gcs plugin
  CHANGELOG.md
  plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageService.java
  plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/SocketAccess.java
Labels: bug, Storage:Snapshots, v2.12.0

#10649 Fix flaky testEqualsAndHashcode in SearchRequestTests
  server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
Labels: bug, flaky-test, skip-changelog

#10631 [Backport 2.x] Fix some test methods in SimulatePipelineRequestParsingTests never run and fix test failure
  server/src/test/java/org/opensearch/action/ingest/SimulatePipelineRequestParsingTests.java
Labels: skip-changelog

#9255 Fix dissect ingest processor parsing empty brackets failed
  CHANGELOG.md
  libs/dissect/src/main/java/org/opensearch/dissect/DissectParser.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/DissectProcessorTests.java
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/200_dissect_processor.yml
Labels: backport 2.x

#10395 Add telemetry tracer/metric enable flag and integ test
  CHANGELOG.md
  libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/MetricsTelemetry.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/DefaultTracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/Tracer.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/noop/NoopTracer.java
  libs/telemetry/src/test/java/org/opensearch/telemetry/tracing/DefaultTracerTests.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/IntegrationTestOTelTelemetryPlugin.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/metrics/InMemorySingletonMetricsExporter.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/metrics/TelemetryMetricsDisabledSanityIT.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/metrics/TelemetryMetricsEnabledSanityIT.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerDisabledSanityIT.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/tracing/TelemetryTracerEnabledSanityIT.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/OTelTelemetryPlugin.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetry.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelTelemetry.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelTracingTelemetry.java
  plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetryTests.java
  plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/tracing/OTelTracingTelemetryTests.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/telemetry/TelemetrySettings.java
  server/src/main/java/org/opensearch/telemetry/tracing/WrappedTracer.java
  server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableHttpChannel.java
  server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableRestChannel.java
  server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableTcpTransportChannel.java
  server/src/main/java/org/opensearch/telemetry/tracing/handler/TraceableTransportResponseHandler.java
  server/src/main/java/org/opensearch/telemetry/tracing/listener/TraceableActionListener.java
  server/src/test/java/org/opensearch/telemetry/metrics/MetricsRegistryFactoryTests.java
  server/src/test/java/org/opensearch/telemetry/tracing/TracerFactoryTests.java
  server/src/test/java/org/opensearch/telemetry/tracing/WrappedTracerTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
  test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetry.java
Labels: enhancement

#10671 Fix flaky test testFlushThrowsFlushFailedExceptionOnCorruption.
  server/src/test/java/org/opensearch/index/engine/NRTReplicationEngineTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#10503 revive remote cluster state auto restore integ tests
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: enhancement, skip-changelog, Cluster Manager

#10660 [Segment Replication] Unmute Test SegmentReplicationTargetServiceTests.testShardAlreadyReplicating
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Labels: bug, >test-failure, flaky-test, backport 2.x, skip-changelog

#10690 Added BufferedInputStream to allow mark and reset ops during IO errors
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
Labels: skip-changelog

#10644 Fix download reporting for segment replication
  server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationWithNodeToNodeIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
  server/src/test/java/org/opensearch/indices/replication/RemoteStoreReplicationSourceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  test/framework/src/main/java/org/opensearch/index/replication/TestReplicationSource.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: bug, skip-changelog, Indexing:Replication

#10447 Remote Restore Cluster Metadata if local disk state lost after quorum loss recovery
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  test/framework/src/main/java/org/opensearch/gateway/MockGatewayMetaState.java
Labels: enhancement, Storage:Remote

#10713 fix change log conflicts
  CHANGELOG.md
Labels: skip-changelog

#10712 Version fixes for Resource Usage Stats and FS Stats
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/monitor/fs/FsInfo.java
Labels: skip-changelog

#10679 Add missing entry for 2.11 release notes
  release-notes/opensearch.release-notes-2.11.0.md
Labels: backport 2.x, skip-changelog, backport 2.11

#10681 Add @abbashus and @adnapibar back to CODEOWNERS
  .github/CODEOWNERS
Labels: bug, skip-changelog

#10710 Closing buffered stream in s3
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
Labels: skip-changelog

#10711 [Backport 2.x] Upload global cluster state to remote store (#10404)
  CHANGELOG.md
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/snapshots/BlobStoreFormatTests.java
Labels: enhancement, Storage

#10736 Muting s3 request stats test
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
Labels: bug, skip-changelog

#10715 [Backport 2.x] Repository stats for remote store
  CHANGELOG.md
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/StatsMetricPublisher.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/common/blobstore/BlobStore.java
  server/src/main/java/org/opensearch/common/blobstore/EncryptedBlobStore.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/main/java/org/opensearch/repositories/RepositoriesStats.java
  server/src/main/java/org/opensearch/repositories/RepositoriesStatsArchive.java
  server/src/main/java/org/opensearch/repositories/RepositoryInfo.java
  server/src/main/java/org/opensearch/repositories/RepositoryStats.java
  server/src/main/java/org/opensearch/repositories/RepositoryStatsSnapshot.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/repositories/blobstore/MeteredBlobStoreRepository.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
  server/src/test/java/org/opensearch/repositories/RepositoriesStatsArchiveTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchMockAPIBasedRepositoryIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: enhancement, Storage:Durability, Storage

#10717 Changing version for repo stats blob post backport to 2.x
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
Labels: skip-changelog

#10448 [Backport 2.x] Performance Improvement for Datetime formats to 2.x
  CHANGELOG.md
  distribution/src/config/opensearch.yml
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DateHistogramIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DateHistogramOffsetIT.java
  server/src/main/java/org/opensearch/common/joda/JodaDateFormatter.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/time/DateFormatter.java
  server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/RangeFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/RangeType.java
  server/src/main/java/org/opensearch/index/mapper/RootObjectMapper.java
  server/src/main/java/org/opensearch/script/ScoreScriptUtils.java
  server/src/main/java/org/opensearch/search/DocValueFormat.java
  server/src/main/java/org/opensearch/search/aggregations/support/CoreValuesSourceType.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValueType.java
  server/src/test/java/org/opensearch/action/search/BottomSortValuesCollectorTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/RangeQueryBuilderTests.java
  server/src/test/java/org/opensearch/search/aggregations/AggregatorBaseTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTestCase.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateRangeHistogramAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/DateRangeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/pipeline/AvgBucketAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/pipeline/CumulativeSumAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/pipeline/MovFnAggrgatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/composite/BaseCompositeAggregatorTestCase.java
Labels: v2.12.0

#10754 Performance Improvement for Datetime formats (update version checks to 2.12.0)
  server/src/main/java/org/opensearch/search/DocValueFormat.java
Labels: skip-changelog

#10655 Fix bug where retries within RemoteStoreRefreshListener cause infos/checkpoint mismatch
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: bug, >test-failure, flaky-test, backport 2.x, skip-changelog, Indexing, Indexing:Replication, Storage

#10724 Categorize search queries by type and log query shape
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchQueryCategorizer.java
  server/src/main/java/org/opensearch/action/search/SearchQueryCategorizingVisitor.java
  server/src/main/java/org/opensearch/action/search/SearchQueryCounters.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/query/QueryShapeVisitor.java
  server/src/test/java/org/opensearch/action/search/SearchQueryCategorizerTests.java
  server/src/test/java/org/opensearch/index/query/QueryShapeVisitorTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, backport 2.x

#10352 Introduce ConcurrentQueryProfiler to profile query using concurrent segment search path and support concurrency during rewrite and create weight
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/profile/query/QueryProfilerIT.java
  server/src/main/java/org/opensearch/search/profile/Profilers.java
  server/src/main/java/org/opensearch/search/profile/Timer.java
  server/src/main/java/org/opensearch/search/profile/query/AbstractQueryProfileTree.java
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfiler.java
  server/src/main/java/org/opensearch/search/profile/query/QueryProfiler.java
  server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdownTests.java
  server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfilerTests.java
  server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java
Labels: bug, flaky-test

#10725 Make RemoteStoreReplicationSource#getSegmentFiles asynchronous
  server/src/internalClusterTest/java/org/opensearch/remotestore/AbstractRemoteStoreMockRepositoryIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreDisruptionIT.java
  server/src/main/java/org/opensearch/index/store/RemoteStoreFileDownloader.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
  server/src/test/java/org/opensearch/index/store/RemoteStoreFileDownloaderTests.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
  test/framework/src/main/java/org/opensearch/snapshots/mockstore/MockRepository.java
Labels: bug, enhancement, distributed framework, skip-changelog, Indexing:Replication

#10741 [Backport 2.x] Added BufferedInputStream to allow mark and reset ops during IO errors #10690
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
Labels: skip-changelog

#10665 Restore remote index shards with ExistingStoreRecoverySource after restore from remote state
  server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
  server/src/main/java/org/opensearch/gateway/ClusterStateUpdaters.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/test/java/org/opensearch/gateway/ClusterStateUpdatersTests.java
Labels: bug, skip-changelog, Cluster Manager, Storage, Storage:Remote, v2.12.0

#10780 Fix flaky remote cluster state UT
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#10782 Fix spotless failure
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#10273 Add tracing instrumentation for indexing paths
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/action/resync/TransportResyncReplicationAction.java
  server/src/main/java/org/opensearch/action/support/replication/TransportWriteAction.java
  server/src/main/java/org/opensearch/index/seqno/RetentionLeaseSyncAction.java
  server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
  server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTookTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
  server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionForIndexingPressureTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportWriteActionTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseSyncActionTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, v3.0.0, Search, Indexing, v2.12.0

#10761 [Remote Store] Fix relocation failure due to transport receive timeout
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoverySourceService.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: bug, Storage:Durability, backport 2.x, skip-changelog, v2.12.0

#10751 Update Github pull request template to have a task for inspecting failing checks
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: skip-changelog

#10750 Increase remote recovery thread pool size
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: backport 2.x, skip-changelog

#10794 [Backport] [1.3] Update Github pull request template to have a task for inspecting failing checks (#10751)
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: skip-changelog

#10723 Return unformatted Segment Replication metrics that take upload time into account for replication lag
  server/src/main/java/org/opensearch/index/ReplicationStats.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: bug, skip-changelog, Indexing:Replication

#10701 [Segment Replication] Fix Flaky test SegmentReplicationRelocationIT.testPrimaryRelocation
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
Labels: bug, >test-failure, flaky-test, backport 2.x, skip-changelog, Indexing, Indexing:Replication

#10656 [Segment Replication] Add Segment Replication backpressure rejection stats to _nodes/stats
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/main/java/org/opensearch/index/SegmentReplicationRejectionStats.java
  server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
  server/src/test/java/org/opensearch/index/SegmentReplicationStatsTrackerTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: bug, backport 2.x, skip-changelog, Storage:Remote

#10803 [Remote Store] Use time elapsed since last successful local refresh for refresh lag
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBackpressureAndResiliencyIT.java
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePressureService.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
Labels: skip-changelog

#10810 Remove remote store attributes from DiscoveryNode toString()
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
Labels: skip-changelog

#10661 Adds util to compare Metadata for remote state
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: enhancement, skip-changelog

#10784 [Backport 2.x] Fix flaky remote cluster state UT
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#10812 Fix custom metadata not getting stored for remote store not supporting async write
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
Labels: skip-changelog

#10783 Removed unnecessary catch statement
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
Labels: skip-changelog

#10748 Override local disk state if we are able to restore from remote
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
Labels: bug, skip-changelog

#10834 [Backport 2.x] [Segment Replication] Backport Adding Segment Replication Backpressure Rejection Stats to _nodes/stats
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/main/java/org/opensearch/index/SegmentReplicationRejectionStats.java
  server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  server/src/test/java/org/opensearch/index/SegmentReplicationPressureServiceTests.java
  server/src/test/java/org/opensearch/index/SegmentReplicationStatsTrackerTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: bug, skip-changelog, Storage:Remote

#10838 fix integ test: check for red indices and then manually restore to green
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
Labels: skip-changelog

#10835 [Segment Replication] Update version check for segment replication backpressure rejection stats
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/index/SegmentReplicationRejectionStats.java
Labels: bug, skip-changelog, Storage:Remote

#10777 Fix remote cluster restore for data stream
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/datastream/DataStreamTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#10830 [Remote Store] Sync segments in refresh listener on refresh after commit
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/index/remote/RemoteTranslogTransferTracker.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
Labels: enhancement, Storage:Durability, skip-changelog, Storage:Remote, v2.12.0

#10817 [Remote Store] Add extra buffer before deleting older generations of translog
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Labels: backport 2.x, skip-changelog

#10814 Make index and global metadata upload timeout dynamic cluster settings
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: enhancement

#10847 Revert "Validate checksum of each segment file post download from remote store (#10119)"
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/Store.java
Labels: skip-changelog

#10865 Update per request latency check to 2.12 on main
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/action/search/SearchResponse.java
Labels: skip-changelog

#10866 Add cluster setting cluster.restrict.index.replication_type t…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: enhancement, Indexing:Replication

#10862 [Backport] [2.x] Bump org.apache.logging.log4j:log4j-core from 2.20.0 to 2.21.0 (#10858)
  CHANGELOG.md
  buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle
  buildSrc/version.properties
  libs/core/licenses/log4j-api-2.20.0.jar.sha1
  libs/core/licenses/log4j-api-2.21.0.jar.sha1
  plugins/crypto-kms/licenses/log4j-1.2-api-2.20.0.jar.sha1
  plugins/crypto-kms/licenses/log4j-1.2-api-2.21.0.jar.sha1
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.20.0.jar.sha1
  plugins/discovery-azure-classic/licenses/log4j-1.2-api-2.21.0.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.20.0.jar.sha1
  plugins/discovery-ec2/licenses/log4j-1.2-api-2.21.0.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.20.0.jar.sha1
  plugins/discovery-gce/licenses/log4j-1.2-api-2.21.0.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.20.0.jar.sha1
  plugins/repository-gcs/licenses/log4j-1.2-api-2.21.0.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.20.0.jar.sha1
  plugins/repository-hdfs/licenses/log4j-slf4j-impl-2.21.0.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.20.0.jar.sha1
  plugins/repository-s3/licenses/log4j-1.2-api-2.21.0.jar.sha1
  qa/os/build.gradle
  server/build.gradle
  server/licenses/log4j-api-2.20.0.jar.sha1
  server/licenses/log4j-api-2.21.0.jar.sha1
  server/licenses/log4j-core-2.20.0.jar.sha1
  server/licenses/log4j-core-2.21.0.jar.sha1
  server/licenses/log4j-jul-2.20.0.jar.sha1
  server/licenses/log4j-jul-2.21.0.jar.sha1
Labels: backport, dependencies

#10844 Changing version check to 2.12 for remote cluster state
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
Labels: skip-changelog

#10685 Created new urgent priority threadpool for remote cluster state uploads
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/AmazonAsyncS3Reference.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/AmazonAsyncS3WithCredentials.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3AsyncServiceTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WritePriority.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/snapshots/BlobStoreFormatTests.java
Labels: enhancement, skip-changelog, Cluster Manager, v2.11.0

#10839 Sync translog to remote on primary activate
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Labels: skip-changelog

#10882 Sync translog to remote on primary activate (#10839)
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Labels: skip-changelog

#10878 Revert "Validate checksum of each segment file post download from remote store (#10119) (#10590)"
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/Store.java
Labels: skip-changelog

#10904 [Backport 2.x] Add cluster state stats
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/InMemoryPersistedState.java
  server/src/main/java/org/opensearch/cluster/coordination/PersistedStateStats.java
  server/src/main/java/org/opensearch/cluster/service/ClusterStateStats.java
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/discovery/DiscoveryStats.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
Labels: Storage:Remote

#10832 link previous cluster uuid to current cluster uuid even if current cluster uuid is not committed
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
Labels: bug, skip-changelog, Cluster Manager, Storage, Storage:Remote, v2.12.0

#10891 Delete corrupted file to re-download from remote store
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  test/framework/src/main/java/org/opensearch/test/CorruptionUtils.java
Labels: skip-changelog

#10897 Fix flaky test testSendCorruptBytesToReplica
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: bug, >test-failure, flaky-test, backport 2.x, skip-changelog, Indexing:Replication

#10922 Fix flaky testClusterStateBatchedUpdates test
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
Labels: bug, flaky-test, skip-changelog

#10929 Fix flaky test IndexShardTests.testLocalDirectoryContains
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardCorruptionTests.java
Labels: bug, backport 2.x, skip-changelog

#10918 [Remote Store] Fix refresh lag bug on primary term change
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
Labels: bug, Storage:Durability, skip-changelog, Storage:Remote, v2.12.0

#10933 [Segment Replication] Handle exceptions on local file read during replication
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
Labels: backport 2.x, skip-changelog

#10926 [Remote Store] Fix shard failure on flush due to upload timeout
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: bug, Storage:Durability, skip-changelog, Storage:Remote, v2.12.0

#10892 Improved logging around remote cluster state
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
Labels: skip-changelog

#10916 Fix valid cluster UUID logic for uncommitted cluster UUIDs
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#10942 Mute testSegRepSucceedsOnPreviousCopiedFiles and testNoFailuresOnFileReads unit tests
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
Labels: backport 2.x, skip-changelog

#10952 [Segment Replication] Add log for failover time
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: bug, backport 2.x, skip-changelog, Indexing:Replication

#10801 Fix unreferenced file cleanup flaky tests
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: bug, skip-changelog, Indexing
