Repository opensearch-project/OpenSearch, pull requests merged in 2024-01, with the labels that each got.

#8742 Batch Async Fetcher class changes
  server/src/main/java/org/opensearch/action/admin/indices/shards/TransportIndicesShardStoresAction.java
  server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java
  server/src/main/java/org/opensearch/gateway/GatewayAllocator.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
  server/src/main/java/org/opensearch/indices/store/ShardAttributes.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/test/java/org/opensearch/gateway/AsyncShardFetchTests.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardAllocatorTests.java
  server/src/test/java/org/opensearch/indices/store/ShardAttributesTests.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestGatewayAllocator.java
Labels: bug, skip-changelog, Cluster Manager

#11039 Implementation for match_only_text field
  CHANGELOG.md
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/11_match_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/20_ngram_search_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/30_ngram_highligthing_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/40_query_string_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/41_query_string_with_default_analyzer_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/50_queries_with_synonyms_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/60_synonym_graph_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/70_intervals_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.suggest/20_phrase_field_match_only_text.yml
  modules/mapper-extras/src/yamlRestTest/resources/rest-api-spec/test/search-as-you-type/20_highlighting_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.validate_query/20_query_string_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/30_sig_terms_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/90_sig_text_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.inner_hits/20_highlighting_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/160_exists_query_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/200_phrase_search_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/310_match_bool_prefix_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/320_disallow_queries_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search_shards/10_basic_field_match_only_field.yml
  server/src/main/java/org/opensearch/index/mapper/MappedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/MatchOnlyTextFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/opensearch/index/query/SourceFieldMatchQuery.java
  server/src/main/java/org/opensearch/index/search/MatchQuery.java
  server/src/main/java/org/opensearch/index/search/MultiMatchQuery.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/test/java/org/opensearch/index/mapper/MatchOnlyTextFieldAnalyzerModeTests.java
  server/src/test/java/org/opensearch/index/mapper/MatchOnlyTextFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/MatchOnlyTextFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldAnalyzerModeTests.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/SourceFieldMatchQueryTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/MapperServiceTestCase.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: backport 2.x

#11683 Fix flaky QueryProfilePhaseTests.testTerminateAfterEarlyTermination
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Search:Query Insights

#11726 Fix testIndexDeletionDuringSnapshotCreationInQueue flaky test
  server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
Labels: bug, distributed framework, flaky-test, backport 2.x, skip-changelog

#11728 Switch to more reliable OpenSearch Lucene snapshot location
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java
  gradle/code-coverage.gradle
Labels: backport 2.x

#11678 Add deleted doc count in _cat/shards
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java
Labels: enhancement, v2.12.0, Other

#11607 Fix simulate remove ingest processor throwing illegal_argument_exception
  CHANGELOG.md
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/RemoveProcessor.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveProcessorTests.java
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/290_remove_processor.yml
Labels: bug, v3.0.0, v2.12.0

#11209 Fixes Numeric exact match queries to use range queries internally
  CHANGELOG.md
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/ScaledFloatFieldMapper.java
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldTypeTests.java
  rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/340_keyword_doc_values.yml
  server/src/main/java/org/apache/lucene/util/LongHashSet.java
  server/src/main/java/org/opensearch/index/document/SortedUnsignedLongDocValuesSetQuery.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/TermQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/TermsQueryBuilderTests.java
Labels: bug, v3.0.0, Search:Performance, v2.12.0

#11754 [Backport] [2.x] Add the means to extract the contextual underlying channel from HttpChannel without excessive typecasting (#11751)
  CHANGELOG.md
  modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpChannel.java
  modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpChannelTests.java
Labels: v2.12.0

#11425 Fix parsing of flat object fields with dots in keys
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/test/java/org/opensearch/common/xcontent/JsonToStringXContentParserTests.java
Labels: bug, Search, Indexing

#11736 Update the skip version for match_only_text field Integ tests to 2.11.99
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/11_match_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/20_ngram_search_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/30_ngram_highligthing_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/40_query_string_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/41_query_string_with_default_analyzer_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/50_queries_with_synonyms_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/60_synonym_graph_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/70_intervals_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.suggest/20_phrase_field_match_only_text.yml
  modules/mapper-extras/src/yamlRestTest/resources/rest-api-spec/test/search-as-you-type/20_highlighting_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.validate_query/20_query_string_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/30_sig_terms_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/90_sig_text_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.inner_hits/20_highlighting_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/160_exists_query_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/200_phrase_search_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/310_match_bool_prefix_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/320_disallow_queries_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search_shards/10_basic_field_match_only_field.yml
Labels: skip-changelog

#11752 Update the skip version for match_only_text field Integ tests to 2.11.99
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/11_match_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/20_ngram_search_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/30_ngram_highligthing_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/40_query_string_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/41_query_string_with_default_analyzer_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/50_queries_with_synonyms_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/60_synonym_graph_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/70_intervals_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.suggest/20_phrase_field_match_only_text.yml
  modules/mapper-extras/src/yamlRestTest/resources/rest-api-spec/test/search-as-you-type/20_highlighting_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.validate_query/20_query_string_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/30_sig_terms_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/90_sig_text_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.inner_hits/20_highlighting_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/160_exists_query_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/200_phrase_search_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/310_match_bool_prefix_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/320_disallow_queries_field_match_only_text.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search_shards/10_basic_field_match_only_field.yml
Labels: skip-changelog

#11734 Add logging for tests in RemoteStoreStatsIT to catch assertion failure cause
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
Labels: skip-changelog

#11716 [Segment Replication] [Remote Store] Replace overriding mockInternalEngine() in test classes with NRTReplicationEngine.
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreDisruptionIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
  test/framework/src/main/java/org/opensearch/test/engine/MockEngineFactory.java
Labels: enhancement, skip-changelog, Indexing:Replication

#11717 Introduce a new feature flag "WRITEABLE_REMOTE_INDEX" to gate the writeable remote index functionality
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
Labels: enhancement, backport 2.x, Search:Remote Search

#11776 Update skip version to match branches
  rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml
Labels: skip-changelog

#11767 Mute flaky testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness
  server/src/internalClusterTest/java/org/opensearch/cluster/allocation/AwarenessAllocationIT.java
Labels: skip-changelog

#11786 Use SegmentReplicationTarget test to validate non-active on-disk files are reused for replication
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#11805 Update dropdowns in issue templates to have no option selected by default
  .github/ISSUE_TEMPLATE/bug_template.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: skip-changelog

#11582 Capture information for additional query types and aggregations types
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchQueryAggregationCategorizer.java
  server/src/main/java/org/opensearch/action/search/SearchQueryCategorizer.java
  server/src/main/java/org/opensearch/action/search/SearchQueryCategorizingVisitor.java
  server/src/main/java/org/opensearch/action/search/SearchQueryCounters.java
  server/src/main/java/org/opensearch/index/query/FieldMaskingSpanQueryBuilder.java
  server/src/test/java/org/opensearch/action/search/SearchQueryCategorizerTests.java
Labels: enhancement, Search, Search:Query Capabilities, Search:Query Insights

#11820 Bump peternied/required-approval from v1.2 to v1.3
  .github/workflows/maintainer-approval.yml
Labels: skip-changelog

#11490 Add support for conditional Transient header propagation
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContextStatePropagator.java
  server/src/main/java/org/opensearch/tasks/TaskThreadContextStatePropagator.java
  server/src/main/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorage.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
  server/src/test/java/org/opensearch/tasks/TaskThreadContextStatePropagatorTests.java
  server/src/test/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorageTests.java
Labels: enhancement, Indexing & Search

#11725 Fixed ingest pipeline script issue
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/ScriptProcessor.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/ScriptProcessorTests.java
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/190_script_processor.yml
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/90_simulate.yml
  server/src/main/java/org/opensearch/ingest/IngestDocument.java
  server/src/test/java/org/opensearch/ingest/IngestDocumentTests.java
Labels: CVE, skip-changelog

#10753 [Tiered caching] Framework changes
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/cache/Cache.java
  server/src/main/java/org/opensearch/common/cache/ICache.java
  server/src/main/java/org/opensearch/common/cache/LoadAwareCacheLoader.java
  server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java
  server/src/main/java/org/opensearch/common/cache/store/StoreAwareCache.java
  server/src/main/java/org/opensearch/common/cache/store/StoreAwareCacheRemovalNotification.java
  server/src/main/java/org/opensearch/common/cache/store/StoreAwareCacheValue.java
  server/src/main/java/org/opensearch/common/cache/store/builders/StoreAwareCacheBuilder.java
  server/src/main/java/org/opensearch/common/cache/store/builders/package-info.java
  server/src/main/java/org/opensearch/common/cache/store/enums/CacheStoreType.java
  server/src/main/java/org/opensearch/common/cache/store/enums/package-info.java
  server/src/main/java/org/opensearch/common/cache/store/listeners/StoreAwareCacheEventListener.java
  server/src/main/java/org/opensearch/common/cache/store/listeners/package-info.java
  server/src/main/java/org/opensearch/common/cache/store/package-info.java
  server/src/main/java/org/opensearch/common/cache/tier/TieredSpilloverCache.java
  server/src/main/java/org/opensearch/common/cache/tier/package-info.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/common/cache/tier/TieredSpilloverCacheTests.java
Labels: enhancement, distributed framework, backport 2.x

#11824 Unmute testNoFailuresOnFileReads flaky test
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Storage:Remote

#11833 [Backport 2.x] Enable must_exist parameter for update aliases API (#11210)
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.update_aliases/40_remove_with_must_exist.yml
  server/src/main/java/org/opensearch/action/admin/indices/alias/IndicesAliasesRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/TransportIndicesAliasesAction.java
  server/src/main/java/org/opensearch/cluster/metadata/AliasAction.java
  server/src/test/java/org/opensearch/action/admin/indices/alias/AliasActionsTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexAliasesServiceTests.java
  test/framework/src/main/java/org/opensearch/index/alias/RandomAliasActionsGenerator.java
Labels: v2.12.0

#11816 Single line comments can end in newline or EOF. Fixes #11815
  CHANGELOG.md
  modules/lang-painless/src/main/antlr/PainlessLexer.g4
  modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessLexer.java
  modules/lang-painless/src/test/java/org/opensearch/painless/CommentTests.java
Labels: bug, Other

#11837 Bump 2.12.0 to Lucene 9.9.1 in Version.java
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#11841 Enable test CardinalityWithRequestBreakerIT.testRequestBreaker after lucene 99 upgrade
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityWithRequestBreakerIT.java
Labels: bug, flaky-test, skip-changelog

#11825 [Backport 2.x] Fix parsing of flat object fields with dots in keys
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/test/java/org/opensearch/common/xcontent/JsonToStringXContentParserTests.java
Labels: v2.12.0

#11850 Remove unused segment replication feature flag
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
Labels: backport 2.x, skip-changelog

#10275 [Tiered Caching] Enabling serialization for IndicesRequestCache key o…
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/index/shard/ShardId.java
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/common/lucene/index/OpenSearchDirectoryReader.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
  server/src/test/java/org/opensearch/indices/IndicesServiceCloseTests.java
Labels: enhancement, Search, Search:Performance

#11681 Fix SimpleNestedIT.testExplain flaky test
  server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java
  server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedIT.java
Labels: bug, Search:Aggregations, flaky-test, backport 2.x, skip-changelog, Search, Search:Resiliency, Search:Performance, Search:Query Capabilities, Search:Query Insights, Search:Remote Search, Search:Searchable Snapshots, Search:Relevance

#11732 Correctly calculate doc count error at the slice level for concurrent segment search
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/ShardSizeTermsIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsDocCountErrorIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsFixedDocCountErrorIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsShardMinDocCountIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/InternalTerms.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
Labels: bug, enhancement, Search:Aggregations, flaky-test, backport 2.x, Search:Performance

#11844 Update runTask to optionally install plugins
  DEVELOPER_GUIDE.md
  gradle/run.gradle
Labels: enhancement, Build Libraries & Interfaces, skip-changelog, Build

#11862 [Backport 2.x] Update runTask to optionally install plugins (#11844)
  DEVELOPER_GUIDE.md
  gradle/run.gradle
Labels: skip-changelog

#11526 Support dynamically adding SearchRequestOperationsListener
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
  server/src/internalClusterTest/java/org/opensearch/search/stats/SearchStatsIT.java
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsCompositeListenerFactory.java
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
  server/src/main/java/org/opensearch/action/search/SearchRequestSlowLog.java
  server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
  server/src/main/java/org/opensearch/action/search/SearchResponseMerger.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/CanMatchPreFilterSearchPhaseTests.java
  server/src/test/java/org/opensearch/action/search/SearchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/SearchQueryThenFetchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsCompositeListenerFactoryTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerSupport.java
  server/src/test/java/org/opensearch/action/search/SearchRequestSlowLogTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestStatsTests.java
  server/src/test/java/org/opensearch/action/search/SearchResponseMergerTests.java
  server/src/test/java/org/opensearch/action/search/SearchTimeProviderTests.java
  server/src/test/java/org/opensearch/action/search/TransportSearchActionTests.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
  server/src/test/java/org/opensearch/indices/NodeIndicesStatsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, Search:Query Insights

#11485 Fix noop_update_total metric in indexing stats cannot be updated by bulk API
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/50_noop_update.yml
  server/src/internalClusterTest/java/org/opensearch/action/bulk/BulkWithUpdatesIT.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
Labels: backport 2.x

#11811 Ensure Jackson default maximums introduced in 2.16.0 do not conflict with OpenSearch settings
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.16.0.jar.sha1
  client/sniffer/licenses/jackson-core-2.16.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.16.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.16.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.16.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.16.1.jar.sha1
  libs/core/licenses/jackson-core-2.16.0.jar.sha1
  libs/core/licenses/jackson-core-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-core-2.16.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.16.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.16.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.16.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.16.1.jar.sha1
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentContraints.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/cbor/CborXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/smile/SmileXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
  libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
  libs/x-content/src/test/resources/org/opensearch/common/xcontent/depth-off-limit.cbor.gz
  libs/x-content/src/test/resources/org/opensearch/common/xcontent/depth-off-limit.json.gz
  libs/x-content/src/test/resources/org/opensearch/common/xcontent/depth-off-limit.smile.gz
  libs/x-content/src/test/resources/org/opensearch/common/xcontent/depth-off-limit.yaml.gz
  modules/ingest-geoip/licenses/jackson-annotations-2.16.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.16.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.16.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.16.0.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.16.0.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.16.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.16.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.16.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.16.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.16.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.16.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.16.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.16.1.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.16.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.16.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.16.1.jar.sha1
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java
Labels: enhancement, v3.0.0, v2.12.0

#11871 [Backport] [2.x] Ensure Jackson default maximums introduced in 2.16.0 do not conflict with OpenSearch settings (#11811)
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.16.0.jar.sha1
  client/sniffer/licenses/jackson-core-2.16.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.16.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.16.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.16.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.16.1.jar.sha1
  libs/core/licenses/jackson-core-2.16.0.jar.sha1
  libs/core/licenses/jackson-core-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-core-2.16.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.16.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.16.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.16.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.16.1.jar.sha1
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentContraints.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/cbor/CborXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/json/JsonXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/smile/SmileXContent.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
  libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
  libs/x-content/src/test/resources/org/opensearch/common/xcontent/depth-off-limit.cbor.gz
  libs/x-content/src/test/resources/org/opensearch/common/xcontent/depth-off-limit.json.gz
  libs/x-content/src/test/resources/org/opensearch/common/xcontent/depth-off-limit.smile.gz
  libs/x-content/src/test/resources/org/opensearch/common/xcontent/depth-off-limit.yaml.gz
  modules/ingest-geoip/licenses/jackson-annotations-2.16.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.16.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.16.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.16.0.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.16.0.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.16.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.16.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.16.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.16.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.16.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.16.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.16.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.16.1.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.16.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.16.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.16.1.jar.sha1
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java
Labels: v2.12.0

#11866 Fix log appender in InsecureSettingTests
  server/src/test/java/org/opensearch/common/logging/LoggersTests.java
  server/src/test/java/org/opensearch/common/settings/InsecureSettingTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Other

#11891 Bump OpenTelemetry from 1.32.0 to 1.34.1
  CHANGELOG.md
  buildSrc/version.properties
  plugins/telemetry-otel/licenses/opentelemetry-api-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-extension-incubator-1.32.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-extension-incubator-1.34.1-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.32.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.34.1.jar.sha1
Labels: dependencies, backport 2.x

#11883 Add missing code in InternalEngine part of #10513
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
Labels: skip-changelog

#8394 Support for Google Application Default Credentials
  CHANGELOG.md
  plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleApplicationDefaultCredentials.java
  plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageService.java
  plugins/repository-gcs/src/test/java/org/opensearch/repositories/gcs/GoogleCloudStorageServiceTests.java
Labels: enhancement, security

#11814 Add TRIAGING.md for triage agenda and processes
  TRIAGING.md
Labels: skip-changelog

#11803 Fix flaky RemoteStoreRefreshListenerTests testTrackerData #11256
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: bug, flaky-test, skip-changelog

#11505 Apply the fast filter optimization to composite aggregation
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeKey.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesCollectorQueue.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesSourceConfig.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/DateHistogramValuesSourceBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/InternalComposite.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/PointsSortedDocsProducer.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/RoundingValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/FilterRewriteHelper.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregatorTests.java
Labels: Search:Aggregations, Search:Performance, v2.12.0

#11899 Fix flaky RemoteFSTranslogTests testMetadataFileDeletion test #9605
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Labels: bug, flaky-test, skip-changelog, Storage:Remote

#11194 Add experimental SIMD implementation of B-tree to round down dates
  CHANGELOG.md
  benchmarks/build.gradle
  benchmarks/src/main/java/org/opensearch/common/round/RoundableBenchmark.java
  benchmarks/src/main/java/org/opensearch/common/round/RoundableSupplier.java
  benchmarks/src/main/java20/org/opensearch/common/round/RoundableSupplier.java
  libs/common/build.gradle
  libs/common/src/main/java20/org/opensearch/common/round/BtreeSearcher.java
  libs/common/src/main/java20/org/opensearch/common/round/RoundableFactory.java
  libs/common/src/test/java/org/opensearch/common/round/RoundableTests.java
Labels: enhancement, Search:Performance

#11917 Update supported version for fixing the bug of noop_update_total metric cannot be updated by bulk API
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/50_noop_update.yml
Labels: backport 2.x

#11563 Support index level allocation filtering for searchable snapshot index
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingNodesTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsMoveShardsTests.java
Labels: enhancement, Search:Remote Search

#11923 Add @SuppressWarnings("removal") to not fail the build with -Werror for some JDKs
  client/sniffer/src/main/java/org/opensearch/client/sniff/Sniffer.java
  libs/common/src/test/java/org/opensearch/common/annotation/processor/CompilerSupport.java
  libs/nio/src/main/java/org/opensearch/nio/ServerChannelContext.java
  libs/nio/src/main/java/org/opensearch/nio/SocketChannelContext.java
  libs/plugin-classloader/src/main/java/org/opensearch/plugins/ExtendedPluginsClassLoader.java
  libs/secure-sm/src/main/java/org/opensearch/secure_sm/SecureSM.java
  libs/secure-sm/src/main/java/org/opensearch/secure_sm/SecuredForkJoinWorkerThreadFactory.java
  libs/secure-sm/src/test/java/org/opensearch/secure_sm/SecureSMTests.java
  modules/ingest-geoip/src/main/java/org/opensearch/ingest/geoip/GeoIpProcessor.java
  modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScriptEngine.java
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/MustacheScriptEngine.java
  modules/lang-painless/spi/src/main/java/org/opensearch/painless/spi/AllowlistLoader.java
  modules/lang-painless/src/main/java/org/opensearch/painless/LambdaBootstrap.java
  modules/lang-painless/src/main/java/org/opensearch/painless/PainlessScriptEngine.java
  modules/lang-painless/src/main/java/org/opensearch/painless/lookup/PainlessLookupBuilder.java
  modules/lang-painless/src/test/java/org/opensearch/painless/DocFieldsPhaseTests.java
  modules/repository-url/src/main/java/org/opensearch/common/blobstore/url/URLBlobContainer.java
  modules/systemd/src/main/java/org/opensearch/systemd/Libsystemd.java
  plugins/crypto-kms/src/main/java/org/opensearch/crypto/kms/SocketAccess.java
  plugins/discovery-ec2/src/main/java/org/opensearch/discovery/ec2/SocketAccess.java
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/SocketAccess.java
  plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/SocketAccess.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/SocketAccess.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/ReloadSecureSettingsIT.java
  server/src/main/java/org/opensearch/SpecialPermission.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapChecks.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapInfo.java
  server/src/main/java/org/opensearch/bootstrap/OpenSearch.java
  server/src/main/java/org/opensearch/bootstrap/OpenSearchPolicy.java
  server/src/main/java/org/opensearch/bootstrap/OpenSearchUncaughtExceptionHandler.java
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/main/java/org/opensearch/monitor/jvm/JvmInfo.java
  server/src/main/java/org/opensearch/plugins/PluginSecurity.java
  server/src/main/java/org/opensearch/plugins/PluginsService.java
  server/src/main/java/org/opensearch/search/lookup/LeafDocLookup.java
  server/src/test/java/org/opensearch/bootstrap/OpenSearchPolicyTests.java
  server/src/test/java/org/opensearch/bootstrap/SecurityTests.java
  server/src/test/java/org/opensearch/index/shard/StoreRecoveryTests.java
  test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java
  test/framework/src/main/java/org/opensearch/mockito/plugin/PriviledgedMockMaker.java
  test/framework/src/main/java/org/opensearch/test/FeatureFlagSetter.java
  test/framework/src/main/java/org/opensearch/test/disruption/LongGCDisruption.java
Labels: skip-changelog

#11931 Add @SuppressWarnings("removal") to not fail the build with -Werror for some JDKs (more classes)
  distribution/archives/integ-test-zip/src/test/java/org/opensearch/test/rest/JsonLogsFormatAndParseIT.java
  plugins/discovery-azure-classic/src/internalClusterTest/java/org/opensearch/discovery/azure/classic/AzureDiscoveryClusterFormationTests.java
  plugins/discovery-azure-classic/src/main/java/org/opensearch/cloud/azure/classic/management/AzureComputeServiceImpl.java
  plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2NetworkTests.java
  plugins/discovery-gce/src/main/java/org/opensearch/cloud/gce/util/Access.java
  plugins/ingest-attachment/src/main/java/org/opensearch/ingest/attachment/TikaImpl.java
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageService.java
  plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageRetryingInputStream.java
  plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsPlugin.java
  plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsRepository.java
  plugins/repository-hdfs/src/main/java/org/opensearch/repositories/hdfs/HdfsSecurityContext.java
  plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HaHdfsFailoverTestSuiteIT.java
  plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsBlobStoreContainerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/OTelTelemetrySettings.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetry.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/metrics/exporter/OTelMetricsExporterFactory.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/OTelResourceProvider.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/tracing/exporter/OTelSpanExporterFactory.java
  qa/evil-tests/src/test/java/org/opensearch/bootstrap/OpenSearchPolicyUnitTests.java
  qa/evil-tests/src/test/java/org/opensearch/bootstrap/SystemCallFilterTests.java
  qa/evil-tests/src/test/java/org/opensearch/plugins/PluginSecurityTests.java
  qa/logging-config/src/test/java/org/opensearch/qa/custom_logging/CustomLoggingConfigIT.java
  qa/unconfigured-node-name/src/test/java/org/opensearch/unconfigured_node_name/JsonLogsFormatAndParseIT.java
Labels: skip-changelog

#11876 Expose RestController all handlers iterator.
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/path/PathTrie.java
  server/src/main/java/org/opensearch/rest/MethodHandlers.java
  server/src/main/java/org/opensearch/rest/RestController.java
  server/src/main/java/org/opensearch/rest/RestMethodHandlers.java
  server/src/test/java/org/opensearch/common/path/PathTrieTests.java
  server/src/test/java/org/opensearch/rest/RestControllerTests.java
Labels: v3.0.0, backport 2.x, v2.12.0

#11939 Only check LongVector.SPECIES_PREFERRED when jdk.incubator.vector is enabled
  libs/common/src/main/java20/org/opensearch/common/round/RoundableFactory.java
Labels: bug, Plugins, skip-changelog

#11946 Allow empty translog for ITs testing no ingestion post refresh/commit
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
Labels: skip-changelog

#11926 [Github Action] Enhance version increment script to create tracking issue
  .github/workflows/version.yml
Labels: bug, flaky-test, skip-changelog

#11968 Workaround for https://bugs.openjdk.org/browse/JDK-8323659 regression, introduced in JDK-21.0.2
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java
  server/src/test/java/org/opensearch/common/util/concurrent/OpenSearchExecutorsTests.java
Labels: skip-changelog

#11982 Fix flaky test for CopyProcessorTests
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/CopyProcessorTests.java
Labels: skip-changelog

#11992 Fix: remove unnecessary trailing/missing leading slash from REST paths.
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestRemoteClusterInfoAction.java
  server/src/main/java/org/opensearch/rest/action/admin/indices/RestPutMappingAction.java
Labels: backport 2.x, skip-changelog, API

#11998 OpenJDK Update (January 2024 Patch releases)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: skip-changelog

#11991 OpenJDK Update (January 2024 Patch releases)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: v3.0.0, skip-changelog, v2.12.0

#11983 Fix typo in RemoveProcessor
  CHANGELOG.md
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/RemoveProcessor.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveProcessorFactoryTests.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/RemoveProcessorTests.java
Labels: backport 2.x, skip-changelog

#12001 OpenJDK Update (January 2024 Patch releases) (#11998)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: skip-changelog

#11976 Disable index refresh for TermsFixedDocCountErrorIT
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/TermsFixedDocCountErrorIT.java
Labels: bug, Storage:Durability, flaky-test, backport 2.x, skip-changelog

#12000 Fix test cluster behavior @ClusterScope(scope = Scope.SUITE) and @OpenSearchIntegTestCase.SuiteScopeTestCase for parameterized test cases
  CHANGELOG.md
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestClusterRule.java
  test/framework/src/test/java/org/opensearch/test/ParameterizedDynamicSettingsOpenSearchIntegTests.java
  test/framework/src/test/java/org/opensearch/test/ParameterizedStaticSettingsOpenSearchIntegTests.java
  test/framework/src/test/java/org/opensearch/test/SuiteScopedParameterizedDynamicSettingsOpenSearchIntegTests.java
  test/framework/src/test/java/org/opensearch/test/SuiteScopedParameterizedStaticSettingsOpenSearchIntegTests.java
  test/framework/src/test/java/org/opensearch/test/TestScopedParameterizedDynamicSettingsOpenSearchIntegTests.java
  test/framework/src/test/java/org/opensearch/test/TestScopedParameterizedStaticSettingsOpenSearchIntegTests.java
Labels: backport 2.x, skip-changelog

#12014 Fixing Minio docker compose fixture
  test/fixtures/minio-fixture/docker-compose.yml
Labels: bug, flaky-test, backport 2.x, skip-changelog

#11465 Added New Fast DateTime parser implementation for RFC3339 Datetime format
  CHANGELOG.md
  NOTICE.txt
  server/src/main/java/org/opensearch/common/time/DateFormatters.java
  server/src/main/java/org/opensearch/common/time/FormatNames.java
  server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java
  server/src/main/java/org/opensearch/common/time/OpenSearchDateTimeFormatter.java
  server/src/main/java/org/opensearch/common/time/OpenSearchDateTimePrinter.java
  server/src/main/java/org/opensearch/common/time/RFC3339CompatibleDateTimeFormatter.java
  server/src/test/java/org/opensearch/common/joda/JavaJodaTimeDuellingTests.java
  server/src/test/java/org/opensearch/common/time/DateFormattersTests.java
Labels: enhancement, v3.0.0, Indexing, v2.12.0

#12013 Add calling class name to mock log appender
  test/framework/src/main/java/org/opensearch/test/MockLogAppender.java
Labels: skip-changelog

#12018 Fix limit check for listing S3 objects
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
Labels: skip-changelog

#11867 [Searchable Snapshot] Add Relevant Error handling for Index Creation with remote_snapshot.
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: enhancement, backport 2.x, Search:Searchable Snapshots

#11724 [BUG] Fix remote shards balancer when filtering throttled nodes
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
Labels: backport 2.x

#11987 Fetch all the locks for a shard to avoid multiple remote store calls
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManager.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/lockmanager/RemoteStoreMetadataLockManagerTests.java
Labels: enhancement, Storage:Durability, backport 2.x, skip-changelog

#12036 Update Mockito to 5.10.0
  buildSrc/version.properties
Labels: dependencies, skip-changelog

#12041 [Backport] [1.3] Bump Netty to 4.1.106.Final (#12034)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.106.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.104.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-buffer-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-dns-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-http-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-http2-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-common-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-handler-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-resolver-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-resolver-dns-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-transport-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-transport-native-unix-common-4.1.106.Final.jar.sha1
Labels: dependencies

#12040 [Backport] [1.x] Bump Netty to 4.1.106.Final (#12034)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/licenses/netty-buffer-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.106.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.104.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.106.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.104.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.106.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.104.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.106.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.104.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-buffer-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-dns-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-http-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-http2-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-common-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-handler-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-resolver-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-resolver-dns-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-transport-4.1.106.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-transport-native-unix-common-4.1.106.Final.jar.sha1
Labels: dependencies

#12042 Bump reactor-core and reactor-netty versions
  CHANGELOG.md
  buildSrc/version.properties
  plugins/repository-azure/licenses/reactor-netty-core-1.1.13.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.15.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.13.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.15.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.13.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.15.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.13.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.15.jar.sha1
  server/licenses/reactor-core-3.5.11.jar.sha1
  server/licenses/reactor-core-3.5.14.jar.sha1
Labels: dependencies, backport 2.x

#12028 Adding configurable connection count setting for S3 Sync Client
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
Labels: Storage:Durability

#12053 [Backport 2.x] Adding configurable connection count setting for S3 Sync Client (#12028)
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
Labels: Storage:Durability

#12063 Update to Apache Lucene 9.9.2
  CHANGELOG.md
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.9.1.jar.sha1
  libs/core/licenses/lucene-core-9.9.2.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.9.1.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.9.2.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.9.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.9.2.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.9.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.9.2.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.9.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.9.2.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.9.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.9.2.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.9.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.9.2.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.9.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.9.2.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.9.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.9.2.jar.sha1
  server/licenses/lucene-analysis-common-9.9.1.jar.sha1
  server/licenses/lucene-analysis-common-9.9.2.jar.sha1
  server/licenses/lucene-backward-codecs-9.9.1.jar.sha1
  server/licenses/lucene-backward-codecs-9.9.2.jar.sha1
  server/licenses/lucene-core-9.9.1.jar.sha1
  server/licenses/lucene-core-9.9.2.jar.sha1
  server/licenses/lucene-grouping-9.9.1.jar.sha1
  server/licenses/lucene-grouping-9.9.2.jar.sha1
  server/licenses/lucene-highlighter-9.9.1.jar.sha1
  server/licenses/lucene-highlighter-9.9.2.jar.sha1
  server/licenses/lucene-join-9.9.1.jar.sha1
  server/licenses/lucene-join-9.9.2.jar.sha1
  server/licenses/lucene-memory-9.9.1.jar.sha1
  server/licenses/lucene-memory-9.9.2.jar.sha1
  server/licenses/lucene-misc-9.9.1.jar.sha1
  server/licenses/lucene-misc-9.9.2.jar.sha1
  server/licenses/lucene-queries-9.9.1.jar.sha1
  server/licenses/lucene-queries-9.9.2.jar.sha1
  server/licenses/lucene-queryparser-9.9.1.jar.sha1
  server/licenses/lucene-queryparser-9.9.2.jar.sha1
  server/licenses/lucene-sandbox-9.9.1.jar.sha1
  server/licenses/lucene-sandbox-9.9.2.jar.sha1
  server/licenses/lucene-spatial-extras-9.9.1.jar.sha1
  server/licenses/lucene-spatial-extras-9.9.2.jar.sha1
  server/licenses/lucene-spatial3d-9.9.1.jar.sha1
  server/licenses/lucene-spatial3d-9.9.2.jar.sha1
  server/licenses/lucene-suggest-9.9.1.jar.sha1
  server/licenses/lucene-suggest-9.9.2.jar.sha1
Labels: dependencies

#12069 [Backport] [2.x] Update to Apache Lucene 9.9.2 (#12063)
  CHANGELOG.md
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.9.1.jar.sha1
  libs/core/licenses/lucene-core-9.9.2.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.9.1.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.9.2.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.9.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.9.2.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.9.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.9.2.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.9.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.9.2.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.9.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.9.2.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.9.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.9.2.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.9.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.9.2.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.9.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.9.2.jar.sha1
  server/licenses/lucene-analysis-common-9.9.1.jar.sha1
  server/licenses/lucene-analysis-common-9.9.2.jar.sha1
  server/licenses/lucene-backward-codecs-9.9.1.jar.sha1
  server/licenses/lucene-backward-codecs-9.9.2.jar.sha1
  server/licenses/lucene-core-9.9.1.jar.sha1
  server/licenses/lucene-core-9.9.2.jar.sha1
  server/licenses/lucene-grouping-9.9.1.jar.sha1
  server/licenses/lucene-grouping-9.9.2.jar.sha1
  server/licenses/lucene-highlighter-9.9.1.jar.sha1
  server/licenses/lucene-highlighter-9.9.2.jar.sha1
  server/licenses/lucene-join-9.9.1.jar.sha1
  server/licenses/lucene-join-9.9.2.jar.sha1
  server/licenses/lucene-memory-9.9.1.jar.sha1
  server/licenses/lucene-memory-9.9.2.jar.sha1
  server/licenses/lucene-misc-9.9.1.jar.sha1
  server/licenses/lucene-misc-9.9.2.jar.sha1
  server/licenses/lucene-queries-9.9.1.jar.sha1
  server/licenses/lucene-queries-9.9.2.jar.sha1
  server/licenses/lucene-queryparser-9.9.1.jar.sha1
  server/licenses/lucene-queryparser-9.9.2.jar.sha1
  server/licenses/lucene-sandbox-9.9.1.jar.sha1
  server/licenses/lucene-sandbox-9.9.2.jar.sha1
  server/licenses/lucene-spatial-extras-9.9.1.jar.sha1
  server/licenses/lucene-spatial-extras-9.9.2.jar.sha1
  server/licenses/lucene-spatial3d-9.9.1.jar.sha1
  server/licenses/lucene-spatial3d-9.9.2.jar.sha1
  server/licenses/lucene-suggest-9.9.1.jar.sha1
  server/licenses/lucene-suggest-9.9.2.jar.sha1
Labels: dependencies

#12072 Update Apache Lucene version for 2.12.0 release
  libs/core/src/main/java/org/opensearch/Version.java
Labels: dependencies, skip-changelog

#11508 Updating Ip fields to use doc_values to search
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml
  server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/IpFieldTypeTests.java
Labels: enhancement, v3.0.0, backport 2.x, Search:Performance, v2.12.0

#11990 Ensure latest replication checkpoint post failover has correct operational primary term
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#12085 The telemetry-otel should not publish any client JARs (since it does not expose client facing APIs)
  plugins/telemetry-otel/build.gradle
Labels: backport 2.x, skip-changelog

#12088 Flaky testRelocateWhileContinuouslyIndexingAndWaitingForRefresh test: Enable trace logs on replication and recovery
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationRelocationIT.java
Labels: skip-changelog

#12086 Move Google Application Default Credentials CHANGELOG entry to 2.x
  CHANGELOG.md
Labels: skip-changelog

#11878 Enable cluster and replication package debug logging for testSingleIndexShardAllocation test
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
Labels: skip-changelog

#12035 [Bug] Check phase name before SearchRequestOperationsListener onPhaseStart
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseName.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: backport 2.x, v2.12.0

#12043 Remove compounding retries within PrimaryShardReplicationSource
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreDisruptionIT.java
  server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/indices/replication/PrimaryShardReplicationSourceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Labels: bug, distributed framework, flaky-test, skip-changelog

#12051 Fixed typo in DEVELOPER_GUIDE.md.
  DEVELOPER_GUIDE.md
Labels: skip-changelog

#12080 [Backport 2.x] Support for Google Application Default Credentials (#8394)
  CHANGELOG.md
  plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleApplicationDefaultCredentials.java
  plugins/repository-gcs/src/main/java/org/opensearch/repositories/gcs/GoogleCloudStorageService.java
  plugins/repository-gcs/src/test/java/org/opensearch/repositories/gcs/GoogleCloudStorageServiceTests.java
Labels: v2.12.0

#12070 Fix flaky test SegmentReplicationStatsIT.testMultipleIndices
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
Labels: bug, flaky-test, skip-changelog

#11918 Fix flaky RemoteIndexRecoveryIT testRerouteRecovery test #9580
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexRecoveryIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: bug, :test, >test-failure, flaky-test, skip-changelog, Indexing:Replication, Storage

#12107 [Backport 2.x] Added New Fast DateTime parser implementation for RFC3339 Datetime format
  CHANGELOG.md
  NOTICE.txt
  server/src/main/java/org/opensearch/common/time/DateFormatters.java
  server/src/main/java/org/opensearch/common/time/FormatNames.java
  server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java
  server/src/main/java/org/opensearch/common/time/OpenSearchDateTimeFormatter.java
  server/src/main/java/org/opensearch/common/time/OpenSearchDateTimePrinter.java
  server/src/main/java/org/opensearch/common/time/RFC3339CompatibleDateTimeFormatter.java
  server/src/test/java/org/opensearch/common/joda/JavaJodaTimeDuellingTests.java
  server/src/test/java/org/opensearch/common/time/DateFormattersTests.java
Labels: enhancement, v3.0.0, Indexing, v2.12.0

#11981 fix flaky test - handle IllegalStateException and throw AssertionError to use assertbusy
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
Labels: bug, flaky-test, skip-changelog, Cluster Manager, Storage:Remote

#12049 Fix Flaky CloseIndexIT.testCloseWhileDeletingIndices
  server/src/internalClusterTest/java/org/opensearch/indices/state/CloseIndexIT.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Cluster Manager

#12079 Add additional logging for Azure repository stats
  plugins/repository-azure/src/internalClusterTest/java/org/opensearch/repositories/azure/AzureBlobStoreRepositoryTests.java
Labels: backport 2.x, skip-changelog
