Repository opensearch-project/OpenSearch, pull requests merged in 2024-02, with the labels that each got.

#12089 Add advance(int) for numeric values in order to allow point based optimization to kick in
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/main/java/org/opensearch/index/fielddata/AbstractNumericDocValues.java
  server/src/main/java/org/opensearch/index/fielddata/FieldData.java
  server/src/main/java/org/opensearch/index/fielddata/NumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsNumericDocValues.java
  server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsToNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsToSortedNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/SortedNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/UnsignedLongToNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/UnsignedLongToSortedNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/plain/SortedNumericIndexFieldData.java
  server/src/main/java/org/opensearch/index/query/functionscore/DecayFunctionBuilder.java
  server/src/main/java/org/opensearch/search/MultiValueMode.java
  server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
Labels: bug, flaky-test, Search, Search:Relevance

#12076 Added spotless for json files
  gradle/formatting.gradle
  server/src/test/resources/org/opensearch/index/analysis/shingle_analysis.json
Labels: skip-changelog

#12117 [Segment Replication] Modify shrink exception to be more informative
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationResizeRequestIT.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java
Labels: enhancement, backport 2.x, skip-changelog, API, Indexing:Replication

#12093 Add test testThreeNodesNoClusterManagerBlock to retry list
  build.gradle
Labels: backport 2.x, skip-changelog

#11896 Create a clone of local segements size map used for Remote Segment Stats until sync to remote completes
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
Labels: bug, Storage:Durability, skip-changelog, Storage:Remote

#12139 Fix race condition in testTracerLog
  test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Other

#12129 [Backport] [2.x] Add advance(int) for numeric values in order to allow point based optimization to kick in (#12089)
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/main/java/org/opensearch/index/fielddata/AbstractNumericDocValues.java
  server/src/main/java/org/opensearch/index/fielddata/FieldData.java
  server/src/main/java/org/opensearch/index/fielddata/NumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/SingletonSortedNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsNumericDocValues.java
  server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsToNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/SortableLongBitsToSortedNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/SortedNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/UnsignedLongToNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/UnsignedLongToSortedNumericDoubleValues.java
  server/src/main/java/org/opensearch/index/fielddata/plain/SortedNumericIndexFieldData.java
  server/src/main/java/org/opensearch/index/query/functionscore/DecayFunctionBuilder.java
  server/src/main/java/org/opensearch/search/MultiValueMode.java
  server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
Labels: bug, backport

#11499 Allow composite aggregation under filter or reverse_nested parent
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filter/FilterAggregatorFactory.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/composite/BaseCompositeAggregatorTestCase.java
Labels: enhancement, Search:Aggregations, backport 2.x, Search:Query Capabilities, v2.12.0

#11443 Cleanup file cache on deleting index/shard directory
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: bug, backport 2.x, skip-changelog, Search:Remote Search

#12156 Fix bwc for concurrent segment search GA
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.thread_pool/10_basic.yml
Labels: skip-changelog

#11720 [Remote Store] Waiting for remote store upload in snapshot/local recovery
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteCloneIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SystemRepositoryIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/repositories/RepositoriesModule.java
  server/src/main/java/org/opensearch/repositories/fs/ReloadableFsRepository.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: bug, enhancement, skip-changelog, Storage:Remote

#12157 Add drainRefreshes as part of tearDown in RemoteStoreRefreshListenerTests
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#11757 Update to Gradle 8.6
  gradle/wrapper/gradle-wrapper.properties
Labels: skip-changelog

#11027 Enable Fuzzy codec for doc id fields using a bloom filter
  CHANGELOG.md
  benchmarks/src/main/java/org/opensearch/benchmark/index/codec/fuzzy/FilterConstructionBenchmark.java
  benchmarks/src/main/java/org/opensearch/benchmark/index/codec/fuzzy/FilterLookupBenchmark.java
  qa/rolling-upgrade/build.gradle
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/codec/PerFieldMappingPostingFormatCodec.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/AbstractFuzzySet.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/BloomFilter.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/FuzzyFilterPostingsFormat.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/FuzzySet.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/FuzzySetFactory.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/FuzzySetParameters.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/IndexInputImmutableLongArray.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/LongArrayBackedBitSet.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/package-info.java
  server/src/main/java/org/opensearch/index/engine/SegmentsStats.java
  server/src/main/resources/META-INF/services/org.apache.lucene.codecs.PostingsFormat
  server/src/test/java/org/opensearch/index/codec/fuzzy/BloomFilterTests.java
  server/src/test/java/org/opensearch/index/codec/fuzzy/FuzzyFilterPostingsFormatTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, discuss, Indexing & Search, v2.12.0

#11903 Query insights plugin implementation
  CHANGELOG.md
  plugins/query-insights/build.gradle
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/Attribute.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/MetricType.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecord.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/package-info.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/TopQueriesServiceTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecordTests.java
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
  server/src/main/java/org/opensearch/action/search/SearchRequestSlowLog.java
  server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsCompositeListenerFactoryTests.java
Labels: Search:Query Insights, v2.12.0

#11904 Top N Queries by latency implementation
  CHANGELOG.md
  plugins/query-insights/src/internalClusterTest/java/org/opensearch/plugin/insights/QueryInsightsPluginTransportIT.java
  plugins/query-insights/src/javaRestTest/java/org/opensearch/plugin/insights/TopQueriesRestIT.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueries.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesAction.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesRequest.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesResponse.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/RestTopQueriesAction.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesAction.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/top_queries/package-info.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListenerTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesRequestTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesResponseTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/RestTopQueriesActionTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesActionTests.java
Labels: Search:Query Insights, v2.12.0

#12183 Disable seg-rep for fuzzy filter postings upgrade IT
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/IndexingIT.java
Labels: backport 2.x, skip-changelog

#12198 [Backport 2.x] Fix CVE 2023 39410
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: v2.12.0

#12199 [Backport 2.x] Query insights plugin implementation (#11903)
  CHANGELOG.md
  plugins/query-insights/build.gradle
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/Attribute.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/MetricType.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecord.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/package-info.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/TopQueriesServiceTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecordTests.java
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
  server/src/main/java/org/opensearch/action/search/SearchRequestSlowLog.java
  server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsCompositeListenerFactoryTests.java
Labels: v2.12.0

#12193 [Backport 2.x] [Snapshot Interop] Fix Flakiness in Snapshot Interop C…
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryHelperTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: skip-changelog, v2.12.0

#12201 Fix BwC for admission control
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
Labels: skip-changelog

#12196 Increase index_searcher thread count to 2x processor
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
Labels: v3.0.0, backport 2.x, skip-changelog, v2.12.0, backport 2.12

#12200 Bump org.apache.shiro:shiro-core from 1.11.0 to 1.13.0
  CHANGELOG.md
  plugins/identity-shiro/build.gradle
  plugins/identity-shiro/licenses/shiro-core-1.11.0.jar.sha1
  plugins/identity-shiro/licenses/shiro-core-1.13.0.jar.sha1
Labels: backport 2.x, backport 2.12

#11954 [Bugfix] Pass TwoPhaseIterator from subQueryScorer
  server/src/main/java/org/opensearch/common/lucene/search/function/ScriptScoreQuery.java
  server/src/test/java/org/opensearch/search/query/ScriptScoreQueryTests.java
Labels: backport 2.x, skip-changelog, v2.12.0, backport 2.12

#12203 [Backport 2.x] Top N Queries by latency implementation
  CHANGELOG.md
  plugins/query-insights/src/internalClusterTest/java/org/opensearch/plugin/insights/QueryInsightsPluginTransportIT.java
  plugins/query-insights/src/javaRestTest/java/org/opensearch/plugin/insights/TopQueriesRestIT.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueries.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesAction.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesRequest.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesResponse.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/RestTopQueriesAction.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesAction.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/top_queries/package-info.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListenerTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesRequestTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesResponseTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/RestTopQueriesActionTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesActionTests.java
Labels: v2.12.0, backport 2.12

#12207 [Backport 2.12] Increase index_searcher thread count to 2x processor (#12196)
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
Labels: skip-changelog

#12206 [Backport 2.x] Increase index_searcher thread count to 2x processor (#12196)
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
Labels: skip-changelog

#12005 [BugFix] Fixing Span operation names generated from RestActions
  CHANGELOG.md
  server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
  server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
  server/src/test/java/org/opensearch/telemetry/tracing/SpanBuilderTests.java
Labels: bug, v3.0.0, v2.12.0

#12224 [Backport 2.x] Add drainRefreshes as part of tearDown in RemoteStoreRefreshListenerT…
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#12227 Move 2.x version to 2.13.0
  .ci/bwcVersions
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#12073 Apply fast date histogram optimization at the segment level
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DateHistogramIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/composite/BaseCompositeAggregatorTestCase.java
Labels: Search:Aggregations, backport 2.x, skip-changelog

#12230 [Forwardport] Move 2.x version to 2.13.0 (#12227)
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#12148 Adding a "meta issue" template
  .github/ISSUE_TEMPLATE/meta.yml
Labels: skip-changelog

#12232 Fix 350_matched_queries.yml tests while awaiting for backport
  rest-api-spec/src/main/resources/rest-api-spec/test/search/350_matched_queries.yml
Labels: skip-changelog

#11441 Add support for dependencies in plugin descriptor properties with semver range
  CHANGELOG.md
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/ListPluginsCommand.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/ListPluginsCommandTests.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamInput.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamOutput.java
  libs/core/src/main/java/org/opensearch/semver/SemverRange.java
  libs/core/src/main/java/org/opensearch/semver/expr/Caret.java
  libs/core/src/main/java/org/opensearch/semver/expr/Equal.java
  libs/core/src/main/java/org/opensearch/semver/expr/Expression.java
  libs/core/src/main/java/org/opensearch/semver/expr/Tilde.java
  libs/core/src/main/java/org/opensearch/semver/expr/package-info.java
  libs/core/src/main/java/org/opensearch/semver/package-info.java
  libs/core/src/test/java/org/opensearch/semver/SemverRangeTests.java
  libs/core/src/test/java/org/opensearch/semver/expr/CaretTests.java
  libs/core/src/test/java/org/opensearch/semver/expr/EqualTests.java
  libs/core/src/test/java/org/opensearch/semver/expr/TildeTests.java
  qa/full-cluster-restart/src/test/java/org/opensearch/upgrades/PluginInfoIT.java
  qa/mixed-cluster/src/test/java/org/opensearch/backwards/PluginInfoIT.java
  server/src/internalClusterTest/java/org/opensearch/plugins/PluginsServiceIT.java
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
  server/src/main/java/org/opensearch/plugins/PluginsService.java
  server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
  server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
  test/framework/src/main/java/org/opensearch/test/VersionUtils.java
Labels: enhancement, Build Libraries & Interfaces, Priority-High, Plugins, extensions

#12260 Update the lucene snapshot url
  buildSrc/src/main/java/org/opensearch/gradle/RepositoriesSetupPlugin.java
  gradle/code-coverage.gradle
Labels: backport 2.x, skip-changelog

#12259 Fix flaky test FieldSortIT.testIssue6614
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
Labels: bug, flaky-test, backport 2.x, skip-changelog

#11773 [Segment Replication] Add Segment Replication Specific Integration Tests
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/stats/IndexStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RecoveryWhileUnderLoadIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/ParameterizedOpenSearchIntegTestCase.java
Labels: >test-failure, backport 2.x, skip-changelog, Indexing:Replication

#12273 Fix BwC for PluginInfo with semver range support
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
Labels: skip-changelog

#12267 Fix: reset the filter built at segment level for date histogram optimization
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/FilterRewriteIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
Labels: bug, skip-changelog, Other

#12279 [Backport 2.x] 12073 and 12267
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/DateHistogramIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/FilterRewriteIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/composite/BaseCompositeAggregatorTestCase.java
Labels: skip-changelog

#11670 Introduce index.query.max_nested_depth. fix #3268
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/index/query/support/NestedScope.java
  server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
Labels: enhancement, good first issue, v3.0.0, hacktoberfest, Search:Resiliency, v2.13.0

#11679 Fix for deserilization bug in weighted round robin metadata
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java
  server/src/main/java/org/opensearch/cluster/metadata/WeightedRoutingMetadata.java
  server/src/main/java/org/opensearch/cluster/routing/WeightedRouting.java
  server/src/test/java/org/opensearch/cluster/metadata/WeightedRoutingMetadataTests.java
Labels: bug, Search

#12163 Add toString() to MultiSearchRequest class.
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
  server/src/main/java/org/opensearch/action/get/MultiGetRequest.java
  server/src/main/java/org/opensearch/action/search/MultiSearchRequest.java
  server/src/test/java/org/opensearch/action/admin/indices/create/CreateIndexRequestTests.java
  server/src/test/java/org/opensearch/action/get/MultiGetRequestTests.java
  server/src/test/java/org/opensearch/action/search/MultiSearchRequestTests.java
Labels: bug, Clients, backport 2.x

#12301 Add a system property to configure YamlParser codepoint limits
  CHANGELOG.md
  libs/x-content/src/main/java/org/opensearch/common/xcontent/XContentContraints.java
  libs/x-content/src/main/java/org/opensearch/common/xcontent/yaml/YamlXContent.java
  libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
Labels: bug, flaky-test, Other

#12310 Add 2.12 release notes to 2.x branch
  release-notes/opensearch.release-notes-2.12.0.md
Labels: skip-changelog

#12321 Add 'Related component' dropdown to meta template
  .github/ISSUE_TEMPLATE/meta.yml
Labels: skip-changelog

#12314 Add toString() to MultiSearchRequest, MultiGetRequest and CreateIndex…
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
  server/src/main/java/org/opensearch/action/get/MultiGetRequest.java
  server/src/main/java/org/opensearch/action/search/MultiSearchRequest.java
  server/src/test/java/org/opensearch/action/admin/indices/create/CreateIndexRequestTests.java
  server/src/test/java/org/opensearch/action/get/MultiGetRequestTests.java
  server/src/test/java/org/opensearch/action/search/MultiSearchRequestTests.java
Labels: bug, Clients, backport 2.x

#10551 Fixes ByteArrayIndexInput::validatePos and adds UT
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/lucene/store/ByteArrayIndexInput.java
  server/src/test/java/org/opensearch/common/lucene/store/ByteArrayIndexInputTests.java
Labels: bug, stalled, Storage

#12330 Allow security manager in IntelliJ unit tests
  gradle/ide.gradle
Labels: skip-changelog

#12327 test: fix flaky for testMinDocCountOnDateHistogram
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/FilterRewriteIT.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Search

#12179 Fix a flaky test that relies on terminate_after for an exact count ma…
  server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
  test/framework/src/main/java/org/opensearch/test/hamcrest/OpenSearchAssertions.java
Labels: bug, flaky-test, skip-changelog, Search

#12328 Fix error in RemoteSegmentStoreDirectory when debug logging is enabled
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  test/framework/src/main/java/org/opensearch/test/MockLogAppender.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: backport 2.x

#12320 Fix flaky test cases
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/shards/ClusterShardLimitIT.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: skip-changelog

#12307 [Segment Replication] Enable test suites to run with segrep
  server/src/internalClusterTest/java/org/opensearch/indexing/IndexActionIT.java
  server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java
  server/src/internalClusterTest/java/org/opensearch/ingest/IngestProcessorNotInstalledOnAllNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RecoveryWhileUnderLoadIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/SimpleRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/TruncatedRecoveryIT.java
  test/framework/src/main/java/org/opensearch/test/ParameterizedStaticSettingsOpenSearchIntegTestCase.java
Labels: enhancement, backport 2.x, skip-changelog, Indexing:Replication

#10919 Fix the "highlight.max_analyzer_offset" request parameter with "plain" highlighter
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/PlainHighlighter.java
Labels: bug, Search

#12337 Avoid string out of bounds error in snapshot delete
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Storage:Snapshots

#12366 Fix FsHealthServiceTests flaky tests
  server/src/test/java/org/opensearch/monitor/fs/FsHealthServiceTests.java
Labels: backport 2.x, skip-changelog

#12380 Disable concurrent search path for composite aggregations.
  release-notes/opensearch.release-notes-2.12.0.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/CompositeAggIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationFactory.java
Labels: skip-changelog

#12373 Mute DeleteSnapshotIT.testDeleteMultipleShallowCopySnapshotsCase1
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
Labels: backport 2.x, skip-changelog

#12387 Bump `peternied/check-pull-request-description-checklist` from v1 to v1.1
  .github/workflows/pull-request-checks.yml
Labels: skip-changelog

#12388 Bump opentelemetry from 1.34.1 to 1.35.0
  CHANGELOG.md
  buildSrc/version.properties
  plugins/telemetry-otel/licenses/opentelemetry-api-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-extension-incubator-1.34.1-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-extension-incubator-1.35.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.34.1.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.35.0.jar.sha1
Labels: dependencies, backport 2.x

#12392 Bump Apache Lucene from 9.9.2 to 9.10.0
  CHANGELOG.md
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.10.0.jar.sha1
  libs/core/licenses/lucene-core-9.9.2.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.10.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.9.2.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.10.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.9.2.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.10.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.9.2.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.10.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.9.2.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.10.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.9.2.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.10.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.9.2.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.10.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.9.2.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.10.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.9.2.jar.sha1
  server/licenses/lucene-analysis-common-9.10.0.jar.sha1
  server/licenses/lucene-analysis-common-9.9.2.jar.sha1
  server/licenses/lucene-backward-codecs-9.10.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.9.2.jar.sha1
  server/licenses/lucene-core-9.10.0.jar.sha1
  server/licenses/lucene-core-9.9.2.jar.sha1
  server/licenses/lucene-grouping-9.10.0.jar.sha1
  server/licenses/lucene-grouping-9.9.2.jar.sha1
  server/licenses/lucene-highlighter-9.10.0.jar.sha1
  server/licenses/lucene-highlighter-9.9.2.jar.sha1
  server/licenses/lucene-join-9.10.0.jar.sha1
  server/licenses/lucene-join-9.9.2.jar.sha1
  server/licenses/lucene-memory-9.10.0.jar.sha1
  server/licenses/lucene-memory-9.9.2.jar.sha1
  server/licenses/lucene-misc-9.10.0.jar.sha1
  server/licenses/lucene-misc-9.9.2.jar.sha1
  server/licenses/lucene-queries-9.10.0.jar.sha1
  server/licenses/lucene-queries-9.9.2.jar.sha1
  server/licenses/lucene-queryparser-9.10.0.jar.sha1
  server/licenses/lucene-queryparser-9.9.2.jar.sha1
  server/licenses/lucene-sandbox-9.10.0.jar.sha1
  server/licenses/lucene-sandbox-9.9.2.jar.sha1
  server/licenses/lucene-spatial-extras-9.10.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.9.2.jar.sha1
  server/licenses/lucene-spatial3d-9.10.0.jar.sha1
  server/licenses/lucene-spatial3d-9.9.2.jar.sha1
  server/licenses/lucene-suggest-9.10.0.jar.sha1
  server/licenses/lucene-suggest-9.9.2.jar.sha1
  server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java
  server/src/main/java/org/opensearch/index/get/ShardGetService.java
  server/src/test/java/org/opensearch/search/lookup/LeafFieldsLookupTests.java
Labels: dependencies

#12389 Mute RemoteIndexPrimaryRelocationIT
  build.gradle
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
Labels: backport 2.x, skip-changelog

#12375 Disable concurrent search path for composite aggregations.
  release-notes/opensearch.release-notes-2.12.0.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/CompositeAggIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationFactory.java
Labels: backport 2.x, skip-changelog, Search:Performance, Search:Query Capabilities

#12382 Update TRIAGING instructions for closed issues
  TRIAGING.md
Labels: documentation, skip-changelog

#12394 [Forwardport] Update Apache Lucene version to 9.10.0 for OpenSearch 2.13.0
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#11193 Warn about `index.mapper.dynamic` usage instead of erroring
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java
Labels: bug, Indexing & Search, v3.0.0, v2.13.0

#12415 [BUG] org.opensearch.common.xcontent.XContentParserTests.testString is flaky
  libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
Labels: bug, flaky-test, skip-changelog, Other

#12077 Fix flaky SegRep test testScrollCreatedOnReplica
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/index/engine/ReplicaFileTracker.java
Labels: bug, flaky-test, skip-changelog

#12297 [Segment Replication] Add random replication strategy
  server/src/internalClusterTest/java/org/opensearch/cluster/SimpleClusterStateIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, backport 2.x, skip-changelog, Indexing:Replication

#12422 Unmute get field mapping test
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_field_mapping/20_missing_field.yml
Labels: bug, flaky-test, backport 2.x, skip-changelog

#1063 Shard id awareness of SearchLookup
  CHANGELOG.md
  modules/lang-expression/src/test/java/org/opensearch/script/expression/ExpressionFieldScriptTests.java
  modules/lang-expression/src/test/java/org/opensearch/script/expression/ExpressionNumberSortScriptTests.java
  modules/lang-expression/src/test/java/org/opensearch/script/expression/ExpressionTermsSetQueryTests.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/search/lookup/SearchLookup.java
  server/src/test/java/org/opensearch/index/fielddata/IndexFieldDataServiceTests.java
  server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/ScriptValuesTests.java
  server/src/test/java/org/opensearch/search/lookup/SearchLookupTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/MapperServiceTestCase.java
  test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java
Labels: distributed framework, backport 2.x

#12467 [Backport] [2.x] Bump antlr4 from 4.11.1 to 4.13.1 (#12445)
  CHANGELOG.md
  buildSrc/version.properties
  modules/lang-expression/licenses/antlr4-runtime-4.11.1.jar.sha1
  modules/lang-expression/licenses/antlr4-runtime-4.13.1.jar.sha1
  modules/lang-painless/licenses/antlr4-runtime-4.11.1.jar.sha1
  modules/lang-painless/licenses/antlr4-runtime-4.13.1.jar.sha1
  modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessLexer.java
  modules/lang-painless/src/main/java/org/opensearch/painless/antlr/PainlessParser.java
Labels: dependencies

#12478 Bump Apache Lucene to 9.11.0-snapshot-8a555eb (`main` only)
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.10.0.jar.sha1
  libs/core/licenses/lucene-core-9.11.0-snapshot-8a555eb.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.10.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.10.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.10.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.10.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.10.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.10.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.10.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.10.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-analysis-common-9.10.0.jar.sha1
  server/licenses/lucene-analysis-common-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-backward-codecs-9.10.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-core-9.10.0.jar.sha1
  server/licenses/lucene-core-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-grouping-9.10.0.jar.sha1
  server/licenses/lucene-grouping-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-highlighter-9.10.0.jar.sha1
  server/licenses/lucene-highlighter-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-join-9.10.0.jar.sha1
  server/licenses/lucene-join-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-memory-9.10.0.jar.sha1
  server/licenses/lucene-memory-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-misc-9.10.0.jar.sha1
  server/licenses/lucene-misc-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-queries-9.10.0.jar.sha1
  server/licenses/lucene-queries-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-queryparser-9.10.0.jar.sha1
  server/licenses/lucene-queryparser-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-sandbox-9.10.0.jar.sha1
  server/licenses/lucene-sandbox-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-spatial-extras-9.10.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-spatial3d-9.10.0.jar.sha1
  server/licenses/lucene-spatial3d-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-suggest-9.10.0.jar.sha1
  server/licenses/lucene-suggest-9.11.0-snapshot-8a555eb.jar.sha1
Labels: dependencies, skip-changelog

#12479 Remove transport-reactor-netty4/ plugin since it is not supported by 1.x line
  plugins/transport-reactor-netty4/licenses/netty-buffer-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-dns-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-http-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-http2-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-common-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-handler-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-resolver-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-resolver-dns-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-transport-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-transport-native-unix-common-4.1.107.Final.jar.sha1
Labels: skip-changelog

#12481 Remove transport-reactor-netty4/ plugin since it is not supported by 1.x line
  plugins/transport-reactor-netty4/licenses/netty-buffer-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-dns-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-http-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-codec-http2-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-common-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-handler-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-resolver-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-resolver-dns-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-transport-4.1.107.Final.jar.sha1
  plugins/transport-reactor-netty4/licenses/netty-transport-native-unix-common-4.1.107.Final.jar.sha1
Labels: skip-changelog

#12277 [Searchable Snapshot] Fix bug of Searchable Snapshot Dependency on repository chunk_size
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/utils/BlobFetchRequest.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTests.java
Labels: bug, backport 2.x, skip-changelog, Search:Searchable Snapshots

#12485 [Backport 2.x] Handle null partSize in OnDemandBlockSnapshotIndexInput (#9470)
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
Labels: skip-changelog
