Repository opensearch-project/OpenSearch, pull requests merged in 2024-06, with the labels that each got.

#13919 Update the `DEVELOPER_GUIDE.md` to add Gradle Check Metrics Dashboard details
  DEVELOPER_GUIDE.md
Labels: skip-changelog

#13367 [Remote Store] Adding ITs to ensure RemoteIndexPath file gets created after migration for each index.
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
Labels: backport 2.x, skip-changelog

#13809 Add comment to XContentBuilder.toString()
  libs/core/src/main/java/org/opensearch/core/xcontent/XContentBuilder.java
Labels: bug, backport 2.x, skip-changelog, Libraries

#13885 Painless: ensure type "UnmodifiableMap" for params
  CHANGELOG.md
  modules/lang-painless/src/test/java/org/opensearch/painless/WhenThingsGoWrongTests.java
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/17_update_error.yml
  server/src/main/java/org/opensearch/script/Script.java
  server/src/main/java/org/opensearch/script/UpdateScript.java
Labels: bug, v3.0.0, backport 2.x, Indexing, Other, v2.15.0

#13940 Bump japicmp plugin version
  server/build.gradle
Labels: backport 2.x, skip-changelog

#13945 [Backport] [2.14] Gradle Check Optimization (#13786) (#13787)
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#13592 [Derived Field] Dynamic FieldType inference based on random sampling of documents
  server/src/main/java/org/opensearch/index/mapper/FieldTypeInference.java
  server/src/test/java/org/opensearch/index/mapper/FieldTypeInferenceTests.java
Labels: enhancement, backport 2.x, skip-changelog, Search:Performance

#13942 Update gradle config for develocity rebranding
  build.gradle
  gradle.properties
  settings.gradle
Labels: backport 2.x, skip-changelog

#13970 Add DCO workflow until dcoapp/app issue is fixed
  .github/workflows/dco.yml
Labels: bug, >FORK, Priority-Medium, distributed framework, cicd, backport 1.x, backport 2.x, backport 1.3, skip-changelog, Other, backport 2.14

#13969 Revert "Optimize remote state stale file deletion (#13131)"
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#13655 [Tiered Caching] Additional ITs for cache stats
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheIT.java
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsIT.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsHolder.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  server/src/internalClusterTest/java/org/opensearch/indices/CacheStatsAPIIndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
  server/src/main/java/org/opensearch/common/cache/service/NodeCacheStats.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
Labels: enhancement, :test, backport 2.x, skip-changelog, Search:Performance, v2.15.0

#13958 [Backport 2.x] Update gradle config for develocity rebranding (#13942)
  build.gradle
  gradle.properties
  settings.gradle
Labels: skip-changelog

#13900 Another attempt to stabilize MacOS GA runner caused by QEMU / Colima / Docker issues
  .github/workflows/assemble.yml
Labels: backport 2.x, skip-changelog

#13703 [Backport 2.x] Split the remote global metadata file to metadata attribute files
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/ClusterStateIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/TemplatesMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#13981 [Backport 2.x] [Tiered Caching] Additional ITs for cache stats
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheIT.java
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsIT.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsHolder.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  server/src/internalClusterTest/java/org/opensearch/indices/CacheStatsAPIIndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
  server/src/main/java/org/opensearch/common/cache/service/NodeCacheStats.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
Labels: skip-changelog

#13304 [Remote Routing Table] Initial commit for RemoteRoutingTableService setup
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/package-info.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/node/RemoteStoreNodeAttributeTests.java
Labels: backport 2.x

#13979 Shorten PR template checklist and remove verification workflow
  .github/pull_request_template.md
  .github/workflows/pull-request-checks.yml
Labels: enhancement, Meta, stalled, backport 2.x, skip-changelog, Other

#14009 [Backport 2.x] Shorten PR template checklist (#13979)
  .github/pull_request_template.md
Labels: skip-changelog

#13778 [Backport 2.x] 13776: allow adding query parameters to RequestOptions
  CHANGELOG.md
  client/rest/src/main/java/org/opensearch/client/Request.java
  client/rest/src/main/java/org/opensearch/client/RequestOptions.java
  client/rest/src/test/java/org/opensearch/client/RequestOptionsTests.java
Labels: enhancement, Clients, v3.0.0, v2.15.0

#13801 [Backport 2.x] [Bugfix] [Tiered Caching] Fixes issues when integrating tiered cache with disk cache
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  plugins/cache-ehcache/build.gradle
  plugins/cache-ehcache/licenses/slf4j-api-LICENSE.txt
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/main/plugin-metadata/plugin-security.policy
Labels: skip-changelog

#14013 Add release notes for 1.3.17
  release-notes/opensearch.release-notes-1.3.17.md
Labels: backport 2.x, skip-changelog

#13785 [Remote Cluster State] Remote state interfaces
  server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableBlobEntity.java
  server/src/main/java/org/opensearch/common/remote/BlobPathParameters.java
  server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityStore.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntity.java
  server/src/main/java/org/opensearch/common/remote/package-info.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
  server/src/main/java/org/opensearch/gateway/remote/model/package-info.java
Labels: skip-changelog

#13995 Optimize remote state stale file deletion
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: bug, enhancement, flaky-test, skip-changelog, Cluster Manager, Storage:Remote

#13999 setting the response before latch countdown so that thread waiting do…
  server/src/internalClusterTest/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionForClusterManagerIT.java
Labels: skip-changelog

#12439 Adds counter metrics for leader and follower check failures
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/ClusterManagerMetrics.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/FollowersChecker.java
  server/src/main/java/org/opensearch/cluster/coordination/LeaderChecker.java
  server/src/main/java/org/opensearch/discovery/DiscoveryModule.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/coordination/FollowersCheckerTests.java
  server/src/test/java/org/opensearch/cluster/coordination/LeaderCheckerTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/discovery/DiscoveryModuleTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  server/src/test/java/org/opensearch/telemetry/TestInMemoryCounter.java
  server/src/test/java/org/opensearch/telemetry/TestInMemoryHistogram.java
  server/src/test/java/org/opensearch/telemetry/TestInMemoryMetricsRegistry.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
Labels: backport 2.x

#13577 [Remote Routing Table] Initial commit for index routing table manifest
  libs/core/src/main/java/org/opensearch/core/common/io/stream/BufferedChecksumStreamInput.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/BufferedChecksumStreamOutput.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/IndexRoutingTableHeader.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTable.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/package-info.java
  server/src/main/java/org/opensearch/index/translog/BaseTranslogReader.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogHeader.java
  server/src/main/java/org/opensearch/index/translog/TranslogSnapshot.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/IndexRoutingTableHeaderTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTableTests.java
  server/src/test/java/org/opensearch/snapshots/BlobStoreFormatTests.java
Labels: skip-changelog

#13998 [Remote Store] Add checks to skip remote uploads after shard is closed
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: backport 2.x, skip-changelog

#14028 A documentation issue, used CONTRIBUTING.md instead of DEVELOPER_GUIDE.md
  gradle/ide.gradle
Labels: bug, backport 2.x, skip-changelog, Other

#13986 Bump HdrHistogram to 2.2.2 and move the dependency version to version.properties
  CHANGELOG.md
  buildSrc/version.properties
  server/build.gradle
  server/licenses/HdrHistogram-2.2.1.jar.sha1
  server/licenses/HdrHistogram-2.2.2.jar.sha1
Labels: dependencies, backport 2.x

#14027 [Remote Store] Add support to disable flush based on translog reader count
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/test/java/org/opensearch/indices/RemoteStoreSettingsDynamicUpdateTests.java
Labels: backport 2.x

#13590 Add capability to disable source recovery_source for an index
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java
  server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/SourceFieldMapperTests.java
Labels: enhancement, backport 2.x, Indexing:Performance

#13888 [Remote Migration] Update checkpoint from remote nodes replicas
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
Labels: bug, backport 2.x, skip-changelog

#14015 Fix double invocation of postCollection when MultiBucketCollector is present
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/terms/StringTermsIT.java
  server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/BestBucketsDeferringCollector.java
Labels: bug, Search:Aggregations, backport 2.x, v2.15.0

#12982 Query insights exporters implementation
  CHANGELOG.md
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/DebugExporter.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/LocalIndexExporter.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporter.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporterFactory.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/SinkType.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecord.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/exporter/DebugExporterTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/exporter/LocalIndexExporterTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporterFactoryTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/TopQueriesServiceTests.java
Labels: enhancement, backport 2.x, Search:Query Insights, v2.15.0

#13720 [DerivedField] Support DerivedField object type and integration with Mapper
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/mapper/DefaultDerivedFieldResolver.java
  server/src/main/java/org/opensearch/index/mapper/DerivedField.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldResolver.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldResolverFactory.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldSupportedTypes.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
  server/src/main/java/org/opensearch/index/mapper/NoOpDerivedFieldResolver.java
  server/src/main/java/org/opensearch/index/mapper/ObjectDerivedFieldType.java
  server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/index/query/VectorGeoPointShapeQueryProcessor.java
  server/src/main/java/org/opensearch/index/search/QueryParserHelper.java
  server/src/main/java/org/opensearch/script/DerivedFieldScript.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightPhase.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldResolverTests.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
  server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java
  server/src/test/java/org/opensearch/search/fetch/subphase/highlight/DerivedFieldFetchAndHighlightTests.java
Labels: enhancement, skip-changelog, Search:Query Capabilities

#14017 [Caching] Move cache removal notifications outside lru lock
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/cache/Cache.java
  server/src/main/java/org/opensearch/common/cache/RemovalListener.java
Labels: enhancement, backport 2.x, Search:Performance

#14056 Revert "[Remote Migration] Update checkpoint from remote nodes replicas"
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
Labels: backport 2.x, skip-changelog

#13374 Add X-Opaque-Id to search request metadata for query insights
  CHANGELOG.md
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/Attribute.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListenerTests.java
  server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
Labels: backport 2.x, v2.15.0

#14022 Make recovery action retry timeout configurable
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/test/java/org/opensearch/indices/recovery/RecoverySettingsDynamicUpdateTests.java
Labels: backport 2.x

#14062 Update checkpoint from remote nodes replicas (#13888)
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
Labels: bug, backport 2.x, skip-changelog

#14042 Update to Apache Lucene 9.11.0
  CHANGELOG.md
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.11.0-snapshot-4be6531.jar.sha1
  libs/core/licenses/lucene-core-9.11.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.11.0-snapshot-4be6531.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.11.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.11.0-snapshot-4be6531.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.11.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.11.0-snapshot-4be6531.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.11.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.11.0-snapshot-4be6531.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.11.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.11.0-snapshot-4be6531.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.11.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.11.0-snapshot-4be6531.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.11.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.11.0-snapshot-4be6531.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.11.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.11.0-snapshot-4be6531.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.11.0.jar.sha1
  server/licenses/lucene-analysis-common-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-analysis-common-9.11.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-backward-codecs-9.11.0.jar.sha1
  server/licenses/lucene-core-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-core-9.11.0.jar.sha1
  server/licenses/lucene-grouping-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-grouping-9.11.0.jar.sha1
  server/licenses/lucene-highlighter-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-highlighter-9.11.0.jar.sha1
  server/licenses/lucene-join-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-join-9.11.0.jar.sha1
  server/licenses/lucene-memory-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-memory-9.11.0.jar.sha1
  server/licenses/lucene-misc-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-misc-9.11.0.jar.sha1
  server/licenses/lucene-queries-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-queries-9.11.0.jar.sha1
  server/licenses/lucene-queryparser-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-queryparser-9.11.0.jar.sha1
  server/licenses/lucene-sandbox-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-sandbox-9.11.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-spatial-extras-9.11.0.jar.sha1
  server/licenses/lucene-spatial3d-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-spatial3d-9.11.0.jar.sha1
  server/licenses/lucene-suggest-9.11.0-snapshot-4be6531.jar.sha1
  server/licenses/lucene-suggest-9.11.0.jar.sha1
Labels: dependencies, v3.0.0, backport 2.x, v2.16.0

#13172 Query-level resource usages tracking
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/tasks/resourcetracker/ResourceUsageInfo.java
  libs/core/src/main/java/org/opensearch/core/tasks/resourcetracker/TaskResourceInfo.java
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/FetchSearchPhase.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/tasks/Task.java
  server/src/main/java/org/opensearch/tasks/TaskResourceTrackingService.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/CanMatchPreFilterSearchPhaseTests.java
  server/src/test/java/org/opensearch/action/search/MockSearchPhaseContext.java
  server/src/test/java/org/opensearch/action/search/SearchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/SearchQueryThenFetchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerSupport.java
  server/src/test/java/org/opensearch/action/search/SearchRequestSlowLogTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestStatsTests.java
  server/src/test/java/org/opensearch/action/search/SearchResponseMergerTests.java
  server/src/test/java/org/opensearch/action/search/TransportSearchActionTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  server/src/test/java/org/opensearch/tasks/TaskResourceInfoTests.java
  server/src/test/java/org/opensearch/tasks/TaskResourceTrackingServiceTests.java
  test/framework/src/main/java/org/opensearch/node/MockNode.java
  test/framework/src/main/java/org/opensearch/search/MockSearchService.java
Labels: enhancement, backport 2.x, Search:Query Insights, v2.15.0

#14077 Mute all flaky IndicesRequestCacheIT tests
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
Labels: skip-changelog

#13834 Implementation of RemoteWritableEntity for objects to uploaded to remote store
  server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityStore.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntity.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadata.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteIndexMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadataTests.java
Labels: skip-changelog, v2.15.0

#14065 [Backport 2.x] Remote state interfaces (#13785)
  server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableBlobEntity.java
  server/src/main/java/org/opensearch/common/remote/BlobPathParameters.java
  server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityStore.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntity.java
  server/src/main/java/org/opensearch/common/remote/package-info.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
  server/src/main/java/org/opensearch/gateway/remote/model/package-info.java
Labels: skip-changelog

#14066 [Backport 2.x] [Remote Routing Table] Initial commit for index routing table manifest
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/IndexRoutingTableHeader.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTable.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/package-info.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/IndexRoutingTableHeaderTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTableTests.java
Labels: skip-changelog

#13836 Upload blob from input stream
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
Labels: skip-changelog, v2.15.0

#14097 [Backport 2.x] Upload blob from input stream
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
Labels: skip-changelog

#13926 Retaining the old constructors for classes marked as API changed as part of #12333
  server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/test/java/org/opensearch/cluster/InternalClusterInfoServiceSchedulingTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: bug, skip-changelog, Cluster Manager

#14094 [Backport 2.x] Update checkpoint from remote nodes replicas (#13888) (#14062)
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/common/ReplicationTarget.java
Labels: skip-changelog

#14096 [Remote Migration] Make remote seeding a low priority upload
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: backport 2.x, skip-changelog

#14098 [Backport 2.x] Implementation of RemoteWritableEntity for objects to uploaded to remote store
  server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityStore.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntity.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadata.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteIndexMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadataTests.java
Labels: skip-changelog

#14030 Implement missing methods for EncryptedBlobStore and EncryptedBlobContainer
  server/src/main/java/org/opensearch/common/blobstore/EncryptedBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/EncryptedBlobStore.java
  server/src/test/java/org/opensearch/common/blobstore/EncryptedBlobContainerTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreCustomMetadataResolverTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
Labels: backport 2.x, skip-changelog

#13994 Adds support to provide tags with value in Gauge metric
  CHANGELOG.md
  libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/DefaultMetricsRegistry.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/MetricsRegistry.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/TaggedMeasurement.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/noop/NoopMetricsRegistry.java
  libs/telemetry/src/test/java/org/opensearch/telemetry/metrics/DefaultMetricsRegistryTests.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/metrics/TelemetryMetricsEnabledSanityIT.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetry.java
  plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetryTests.java
  server/src/test/java/org/opensearch/telemetry/TestInMemoryMetricsRegistry.java
  test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetry.java
Labels: enhancement, v3.0.0, backport 2.x, Other, Telemetry:Metrics, v2.15.0

#14100 Move Remote Store Migration from DocRep to GA
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/ResizeIndexMigrationTestCase.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteStoreMigrationAllocationDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java
Labels: backport 2.x

#14123 Retaining old constructor of MasterService class to maintain compatib…
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerService.java
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
Labels: bug, skip-changelog, Cluster Manager

#14084 fix concurrent modification exceptions in thread context
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
  server/src/main/java/org/opensearch/tasks/TaskResourceTrackingService.java
  server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
Labels: backport 2.x, skip-changelog, v2.15.0

#13997 Add recovery chunk size setting
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/TruncatedRecoveryIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/indices/recovery/RecoverySettingsDynamicUpdateTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/node/MockNode.java
  test/framework/src/main/java/org/opensearch/node/RecoverySettingsChunkSizePlugin.java
Labels: backport 2.x, Storage:Remote

#14095 Create serde utility for Writable classes
  libs/core/src/main/java/org/opensearch/core/compress/CompressorRegistry.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumWritableBlobStoreFormat.java
  server/src/test/java/org/opensearch/repositories/blobstore/ChecksumWritableBlobStoreFormatTests.java
Labels: skip-changelog

#13835 Add remote state publication transport call
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/cluster/coordination/RemotePublishRequest.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/discovery/DiscoveryModule.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateManifestInfo.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/cluster/coordination/PublicationTransportHandlerTests.java
  server/src/test/java/org/opensearch/discovery/DiscoveryModuleTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
Labels: skip-changelog, v2.15.0

#14118 [Backport] ClusterManager metrics instrumentation changes
  CHANGELOG.md
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListenerTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesActionTests.java
  server/src/main/java/org/opensearch/cluster/ClusterManagerMetrics.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/FollowersChecker.java
  server/src/main/java/org/opensearch/cluster/coordination/LeaderChecker.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/discovery/DiscoveryModule.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestSlowLogTests.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/coordination/FollowersCheckerTests.java
  server/src/test/java/org/opensearch/cluster/coordination/LeaderCheckerTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
  server/src/test/java/org/opensearch/discovery/DiscoveryModuleTests.java
  server/src/test/java/org/opensearch/gateway/ClusterStateUpdatersTests.java
  server/src/test/java/org/opensearch/gateway/GatewayServiceTests.java
  server/src/test/java/org/opensearch/index/IndexingPressureServiceTests.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureConcurrentExecutionTests.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureMemoryManagerTests.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureSettingsTests.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureStoreTests.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureSettingsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreStatsTrackerFactoryTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/node/ResponseCollectorServiceTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionControlServiceTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionControlSettingsTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/controllers/CpuBasedAdmissionControllerTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/controllers/IoBasedAdmissionControllerTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/settings/CPUBasedAdmissionControllerSettingsTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/settings/IoBasedAdmissionControllerSettingsTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/stats/AdmissionControlStatsTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/stats/AdmissionControllerStatsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  server/src/test/java/org/opensearch/telemetry/TestInMemoryCounter.java
  server/src/test/java/org/opensearch/telemetry/TestInMemoryHistogram.java
  server/src/test/java/org/opensearch/telemetry/TestInMemoryMetricsRegistry.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
  test/framework/src/main/java/org/opensearch/cluster/service/FakeThreadPoolClusterManagerService.java
  test/framework/src/main/java/org/opensearch/test/ClusterServiceUtils.java
Labels: bug, Cluster Manager

#14137 [Backport 2.x]Add remote state publication transport call (#13835)
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/cluster/coordination/RemotePublishRequest.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/discovery/DiscoveryModule.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateManifestInfo.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/cluster/coordination/PublicationTransportHandlerTests.java
  server/src/test/java/org/opensearch/discovery/DiscoveryModuleTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
Labels: skip-changelog

#14135 [Backport] [2.x] Bump com.azure:azure-core-http-netty from 1.12.8 to 1.15.1 in /plugins/repository-azure (#14128)
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-core-1.47.0.jar.sha1
  plugins/repository-azure/licenses/azure-core-1.49.1.jar.sha1
  plugins/repository-azure/licenses/azure-core-http-netty-1.12.8.jar.sha1
  plugins/repository-azure/licenses/azure-core-http-netty-1.15.1.jar.sha1
  plugins/repository-azure/licenses/azure-xml-1.0.0.jar.sha1
Labels: dependencies

#13739 consume query level cpu and memory usage in query insights
  CHANGELOG.md
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporterFactory.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/Attribute.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/MetricType.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesAction.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListenerTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecordTests.java
Labels: backport 2.x, v2.15.0

#14143 Fix the breaking change check due to Derived fields changes in 2.15
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
Labels: skip-changelog

#14147 fix japicmp check for threadContext
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
  server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
Labels: skip-changelog

#13721 [Derived Field] Integration tests for derived fields
  CHANGELOG.md
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/10_derived_field_index_mapping_definition.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/20_derived_field_put_mapping.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/30_derived_field_search_definition.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/40_derived_field_fetch_and_highlight.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/50_derived_field_default_analyzer.yml
Labels: backport, backport 2.x

#13772 [Streaming Indexing] Enhance RestAction with request / response streaming support
  CHANGELOG.md
  client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java
  modules/opensearch-dashboards/src/main/java/org/opensearch/dashboards/OpenSearchDashboardsModulePlugin.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpChunk.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpRequest.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransport.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4NonStreamingHttpChannel.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4NonStreamingRequestConsumer.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingHttpChannel.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingRequestConsumer.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingResponseProducer.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/StreamingHttpContentSender.java
  plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorHttpClient.java
  plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransportStreamingTests.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/common/xcontent/support/XContentHttpChunk.java
  server/src/main/java/org/opensearch/http/AbstractHttpServerTransport.java
  server/src/main/java/org/opensearch/http/DefaultRestChannel.java
  server/src/main/java/org/opensearch/http/DefaultStreamingRestChannel.java
  server/src/main/java/org/opensearch/http/HttpChunk.java
  server/src/main/java/org/opensearch/http/HttpServerTransport.java
  server/src/main/java/org/opensearch/http/HttpTracer.java
  server/src/main/java/org/opensearch/http/StreamingHttpChannel.java
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
  server/src/main/java/org/opensearch/rest/RestController.java
  server/src/main/java/org/opensearch/rest/RestHandler.java
  server/src/main/java/org/opensearch/rest/StreamingRestChannel.java
  server/src/main/java/org/opensearch/rest/action/document/RestBulkStreamingAction.java
  server/src/test/java/org/opensearch/rest/action/document/RestBulkStreamingActionTests.java
Labels: enhancement, v3.0.0, backport 2.x, Indexing, v2.15.0

#13870 [Remote Routing Table] Add write flow for remote routing table
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactory.java
  server/src/main/java/org/opensearch/common/blobstore/BlobPath.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPath.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategy.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/test/java/org/opensearch/cluster/routing/IndexShardRoutingTableTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactoryTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: backport 2.x

#14151 Backport/backport 13721 to 2.x
  CHANGELOG.md
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/10_derived_field_index_mapping_definition.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/20_derived_field_put_mapping.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/30_derived_field_search_definition.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/40_derived_field_fetch_and_highlight.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/50_derived_field_default_analyzer.yml
Labels: v2.15.0

#14064 [Backport 2.x] Add capability to disable source recovery_source for an index (#13590)
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java
  server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/SourceFieldMapperTests.java
Labels: enhancement, Indexing:Performance, v2.15.0

#14006 Add POJO classes required for cluster state publication from remote
  server/src/main/java/org/opensearch/cluster/DiffableUtils.java
  server/src/main/java/org/opensearch/cluster/metadata/DiffableStringMap.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteStateTransferException.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteReadResult.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteTransientSettingsMetadata.java
  server/src/test/java/org/opensearch/cluster/block/ClusterBlockTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/ClusterStateDiffManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterBlocksTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustomsTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettingsTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteTransientSettingsMetadataTests.java
Labels: enhancement, skip-changelog, Cluster Manager, v2.15.0, ClusterManager:RemoteState

#14158 Adding back DEFAULT_CHUNK_SIZE to be visible to public API
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
Labels: skip-changelog

#14161 [Backport 2.x] Add recovery chunk size setting
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/TruncatedRecoveryIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/indices/recovery/RecoverySettingsDynamicUpdateTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/node/MockNode.java
  test/framework/src/main/java/org/opensearch/node/RecoverySettingsChunkSizePlugin.java
Labels: Storage:Remote

#14119 [Remote Store Migration] Skip segrep lag computation for shard copies on docrep nodes
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
Labels: backport 2.x, skip-changelog, Storage:Remote, v2.15.0

#13461 Add support for wildcard field type
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/270_wildcard_fieldtype_queries.yml
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/test/java/org/opensearch/index/mapper/WildcardFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/WildcardFieldTypeTests.java
Labels: enhancement, help wanted, feature, backport 2.x, Search, Indexing, Search:Query Capabilities, v2.15.0

#13529 Use correct names for snapshot indices while updating remote store index settings
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: backport 2.x, skip-changelog, Storage:Remote, v2.15.0

#14172 [Backport 2.x] Add POJO classes required for cluster state publication from remote (#14006)
  server/src/main/java/org/opensearch/cluster/DiffableUtils.java
  server/src/main/java/org/opensearch/cluster/metadata/DiffableStringMap.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteStateTransferException.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteReadResult.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteTransientSettingsMetadata.java
  server/src/test/java/org/opensearch/cluster/block/ClusterBlockTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/ClusterStateDiffManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterBlocksTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustomsTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettingsTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteTransientSettingsMetadataTests.java
Labels: skip-changelog

#14149 [Backport] [2.x] [Streaming Indexing] Enhance RestAction with request / response streaming support (#13772)
  CHANGELOG.md
  client/rest-high-level/src/main/java/org/opensearch/client/RestHighLevelClient.java
  modules/opensearch-dashboards/src/main/java/org/opensearch/dashboards/OpenSearchDashboardsPlugin.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpChunk.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpRequest.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransport.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4NonStreamingHttpChannel.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4NonStreamingRequestConsumer.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingHttpChannel.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingRequestConsumer.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingResponseProducer.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/StreamingHttpContentSender.java
  plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorHttpClient.java
  plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransportStreamingTests.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/common/xcontent/support/XContentHttpChunk.java
  server/src/main/java/org/opensearch/http/AbstractHttpServerTransport.java
  server/src/main/java/org/opensearch/http/DefaultRestChannel.java
  server/src/main/java/org/opensearch/http/DefaultStreamingRestChannel.java
  server/src/main/java/org/opensearch/http/HttpChunk.java
  server/src/main/java/org/opensearch/http/HttpServerTransport.java
  server/src/main/java/org/opensearch/http/HttpTracer.java
  server/src/main/java/org/opensearch/http/StreamingHttpChannel.java
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
  server/src/main/java/org/opensearch/rest/RestController.java
  server/src/main/java/org/opensearch/rest/RestHandler.java
  server/src/main/java/org/opensearch/rest/StreamingRestChannel.java
  server/src/main/java/org/opensearch/rest/action/document/RestBulkStreamingAction.java
  server/src/test/java/org/opensearch/rest/action/document/RestBulkStreamingActionTests.java
Labels: backport, v2.15.0

#14146 Java high-level REST client bulk() is not respecting the bulkRequest.requireAlias(true) method call
  CHANGELOG-3.0.md
  client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
  client/rest-high-level/src/test/java/org/opensearch/client/CrudIT.java
Labels: bug, good first issue, Clients, v3.0.0, backport 2.x, v2.15.0

#14175 Revert "Update to Gradle 8.8 (#13584)"
  buildSrc/src/main/java/org/opensearch/gradle/info/GlobalBuildInfoPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/DependencyLicensesPrecommitPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
  buildSrc/src/main/java/org/opensearch/gradle/tar/SymbolicLinkPreservingTar.java
  distribution/archives/build.gradle
  distribution/build.gradle
  distribution/packages/build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  server/build.gradle
  server/licenses/jackson-LICENSE
  server/licenses/jackson-NOTICE
  server/licenses/jackson-core-2.17.1.jar.sha1
  server/licenses/jackson-dataformat-cbor-2.17.1.jar.sha1
  server/licenses/jackson-dataformat-smile-2.17.1.jar.sha1
  server/licenses/jackson-dataformat-yaml-2.17.1.jar.sha1
  server/licenses/jopt-simple-5.0.4.jar.sha1
  server/licenses/jopt-simple-LICENSE.txt
  server/licenses/jopt-simple-NOTICE.txt
  server/licenses/snakeyaml-2.1.jar.sha1
  server/licenses/snakeyaml-LICENSE.txt
  server/licenses/snakeyaml-NOTICE.txt
  server/licenses/zstd-jni-1.5.5-5.jar.sha1
  server/licenses/zstd-jni-LICENSE.txt
  server/licenses/zstd-jni-NOTICE.txt
  settings.gradle
Labels: skip-changelog

#13946 Define component-based triage meetings
  TRIAGING.md
Labels: skip-changelog

#13924 Create Remote Object managers and use them in orchestration from RemoteClusterStateService
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableBlobEntity.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteTransientSettingsMetadata.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteManifestManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterBlocksTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteIndexMetadataTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteIndexPathUploaderTests.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: enhancement, skip-changelog, Cluster Manager, v2.15.0, ClusterManager:RemoteState

#14188 [Backport 2.x]Create Remote Object managers and use them in orchestration from Remo…
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableBlobEntity.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteTransientSettingsMetadata.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteManifestManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterBlocksTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteIndexMetadataTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteIndexPathUploaderTests.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: skip-changelog

#13909 Delete stale index routing files.
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
Labels: enhancement, backport 2.x, skip-changelog, ShardManagement:Resiliency

#14195 [Backport 2.x]Delete stale index routing table files resolves #14162 (#13909)
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
Labels: skip-changelog

#14089 Read write ephemeral objects for remote publication of cluster state
  server/src/main/java/org/opensearch/cluster/RepositoryCleanupInProgress.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactory.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactoryTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
Labels: enhancement, skip-changelog, Cluster Manager, ShardManagement:Resiliency, v2.15.0, ClusterManager:RemoteState

#13821 Support Dynamic Pruning in Cardinality Aggregation
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/InternalCardinality.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, Search:Aggregations, backport 2.x, v2.15.0

#14203 [Backport 13821] Support Dynamic Pruning in Cardinality Aggregation
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/metrics/CardinalityIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/InternalCardinality.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, Search:Aggregations, v2.15.0

#14201 [Flaky Test] Set refresh interval to -1 to only have 1 segment
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/10_histogram.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/330_auto_date_histogram.yml
Labels: bug, Search:Aggregations, flaky-test, backport 2.x, skip-changelog

#14208 Make sure processPostCollection is called in case of early termination
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
  server/src/main/java/org/opensearch/search/query/QueryPhase.java
Labels: bug, backport 2.x, skip-changelog, Search, v2.15.0

#14107 Switch to ShardsBatchGatewayAllocator in batch enabled mode for shard…
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
Labels: skip-changelog

#14209 [Backport 2.15] Read write ephemeral objects for remote publication of cluster state …
  server/src/main/java/org/opensearch/cluster/RepositoryCleanupInProgress.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactory.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactoryTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
Labels: skip-changelog

#14207 [Backport 2.x] Read write ephemeral objects for remote publication of cluster state
  server/src/main/java/org/opensearch/cluster/RepositoryCleanupInProgress.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactory.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactoryTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
Labels: skip-changelog

#14216 Bump 2.x to 2.16.0
  .ci/bwcVersions
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
Labels: release, skip-changelog, v2.16.0

#14219 Fix ShardNotFoundException during request cache clean up
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: bug, backport 2.x, v2.15.0

#14226 Update version for ClusterMetadataManifest after 2.15 backport
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
Labels: skip-changelog

#14237 [main] Add release notes for 2.15
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.15.0.md
Labels: skip-changelog

#14238 Revert "Mute all flaky IndicesRequestCacheIT tests (#14077)"
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
Labels: backport 2.x, skip-changelog

#14074 [Backport] [2.x] Update to Apache Lucene 9.11.0
  CHANGELOG.md
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.10.0.jar.sha1
  libs/core/licenses/lucene-core-9.11.0.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.10.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.11.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.10.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.11.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.10.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.11.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.10.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.11.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.10.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.11.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.10.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.11.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.10.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.11.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.10.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.11.0.jar.sha1
  server/licenses/lucene-analysis-common-9.10.0.jar.sha1
  server/licenses/lucene-analysis-common-9.11.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.10.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.11.0.jar.sha1
  server/licenses/lucene-core-9.10.0.jar.sha1
  server/licenses/lucene-core-9.11.0.jar.sha1
  server/licenses/lucene-grouping-9.10.0.jar.sha1
  server/licenses/lucene-grouping-9.11.0.jar.sha1
  server/licenses/lucene-highlighter-9.10.0.jar.sha1
  server/licenses/lucene-highlighter-9.11.0.jar.sha1
  server/licenses/lucene-join-9.10.0.jar.sha1
  server/licenses/lucene-join-9.11.0.jar.sha1
  server/licenses/lucene-memory-9.10.0.jar.sha1
  server/licenses/lucene-memory-9.11.0.jar.sha1
  server/licenses/lucene-misc-9.10.0.jar.sha1
  server/licenses/lucene-misc-9.11.0.jar.sha1
  server/licenses/lucene-queries-9.10.0.jar.sha1
  server/licenses/lucene-queries-9.11.0.jar.sha1
  server/licenses/lucene-queryparser-9.10.0.jar.sha1
  server/licenses/lucene-queryparser-9.11.0.jar.sha1
  server/licenses/lucene-sandbox-9.10.0.jar.sha1
  server/licenses/lucene-sandbox-9.11.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.10.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.11.0.jar.sha1
  server/licenses/lucene-spatial3d-9.10.0.jar.sha1
  server/licenses/lucene-spatial3d-9.11.0.jar.sha1
  server/licenses/lucene-suggest-9.10.0.jar.sha1
  server/licenses/lucene-suggest-9.11.0.jar.sha1
  server/src/main/java/org/apache/lucene/search/uhighlight/CustomFieldHighlighter.java
  server/src/main/java/org/opensearch/plugins/PluginsService.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/FastVectorHighlighter.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightBuilder.java
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: dependencies

#14241 [Forwardport] Update to Apache Lucene 9.11.0 (#14074)
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#14248 [2.15] Backport 14154
  server/src/main/java/org/opensearch/index/query/SourceFieldMatchQuery.java
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: skip-changelog, v2.15.0

#14154 Fix the rewrite method for MatchOnlyText field query
  server/src/main/java/org/opensearch/index/query/SourceFieldMatchQuery.java
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
Labels: bug, backport 2.x, skip-changelog, Search, v2.15.0

#14221 [Tiered Caching] [Bug Fix] Use concurrentMap instead of HashMap to fix Concurrent Modification Exception
  release-notes/opensearch.release-notes-2.15.0.md
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: bug, backport 2.x, skip-changelog, Search, Search:Performance, v2.15.0, backport 2.15

#14251 Add the match_only_text rewrite fix to release notes
  release-notes/opensearch.release-notes-2.15.0.md
Labels: skip-changelog

#14037 [Remote Store] Fix sleep time bug during remote store sync
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: backport 2.x, skip-changelog, backport 2.15

#13748 Fix unassigned shard allocation for batch mode
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
  server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
Labels: bug, skip-changelog, Cluster Manager

#14182 Update to Gradle 8.8 (#13584)
  buildSrc/src/main/java/org/opensearch/gradle/info/GlobalBuildInfoPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionArchiveSetupPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/DependencyLicensesPrecommitPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/DependencyLicensesTask.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/UpdateShasTask.java
  buildSrc/src/main/java/org/opensearch/gradle/tar/SymbolicLinkPreservingTar.java
  buildSrc/src/main/java/org/opensearch/gradle/util/GradleUtils.java
  buildSrc/src/test/java/org/opensearch/gradle/precommit/DependencyLicensesTaskTests.java
  buildSrc/src/test/java/org/opensearch/gradle/precommit/UpdateShasTaskTests.java
  distribution/archives/build.gradle
  distribution/build.gradle
  distribution/packages/build.gradle
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  server/build.gradle
  server/licenses/jackson-LICENSE
  server/licenses/jackson-NOTICE
  server/licenses/jackson-core-2.17.1.jar.sha1
  server/licenses/jackson-dataformat-cbor-2.17.1.jar.sha1
  server/licenses/jackson-dataformat-smile-2.17.1.jar.sha1
  server/licenses/jackson-dataformat-yaml-2.17.1.jar.sha1
  server/licenses/jopt-simple-5.0.4.jar.sha1
  server/licenses/jopt-simple-LICENSE.txt
  server/licenses/jopt-simple-NOTICE.txt
  server/licenses/snakeyaml-2.1.jar.sha1
  server/licenses/snakeyaml-LICENSE.txt
  server/licenses/snakeyaml-NOTICE.txt
  server/licenses/zstd-jni-1.5.5-5.jar.sha1
  server/licenses/zstd-jni-LICENSE.txt
  server/licenses/zstd-jni-NOTICE.txt
  settings.gradle
Labels: skip-changelog

#14274 Revert "[Remote Store] Fix sleep time bug during remote store sync (#…
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: bug, flaky-test, skip-changelog, Storage:Remote

#14286 Add the match_only_text rewrite fix to release notes main
  release-notes/opensearch.release-notes-2.15.0.md
Labels: bug, skip-changelog, Search, v2.15.0

#14285 Add the match_only_text rewrite fix to release notes 2.x
  release-notes/opensearch.release-notes-2.15.0.md
Labels: skip-changelog, v2.15.0

#14342 [Remote Store] Fix sleep time bug during remote store sync
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
Labels: backport 2.x, skip-changelog, backport 2.15

#14334 Update Gradle check workflow to remove the `Create Issue On Push Failure` section.
  .github/ISSUE_TEMPLATE/failed_check.md
  .github/workflows/gradle-check.yml
Labels: backport 1.x, backport 2.x, backport 1.3, skip-changelog, backport 2.15

#14230 Fix flakiness of testRemoteCleanupDeleteStale, bug fix in RemoteMetadataManifest and RemoteReadResult
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteReadResult.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterBlocksTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustomsTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
Labels: bug, >test-failure, flaky-test, backport 2.x, autocut, ClusterManager:RemoteState, backport 2.15

#14341 [Bugfix] Fix incorrect document order when there's exception during batch ingest
  server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
Labels: skip-changelog

#14364 [Backport] [1.3] Bump netty from 4.1.110.Final to 4.1.111.Final (#14356)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.111.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.110.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.111.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.111.Final.jar.sha1
Labels: dependencies

#14361 Bump org.wiremock:wiremock-standalone from 3.3.1 to 3.6.0
  CHANGELOG.md
  buildSrc/build.gradle
Labels: dependencies, backport 2.x

#14333 [Bugfix] Fix TieredSpilloverCache flaky tests
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/CacheStatsAPIIndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/common/cache/stats/ImmutableCacheStats.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Search:Performance, Other

#13724 Add fingerprint ingest processor
  CHANGELOG.md
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/FingerprintProcessor.java
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonModulePlugin.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/FingerprintProcessorFactoryTests.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/FingerprintProcessorTests.java
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/10_basic.yml
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/340_fingerprint_processor.yml
  server/src/main/java/org/opensearch/common/hash/MessageDigests.java
  server/src/test/java/org/opensearch/common/hash/MessageDigestsTests.java
Labels: v3.0.0, backport 2.x, ingest-pipeline, v2.16.0

#14363 [Backport] [1.x] Bump netty from 4.1.110.Final to 4.1.111.Final (#14356)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.111.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.110.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.111.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.110.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.111.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.110.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.111.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.111.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.110.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.111.Final.jar.sha1
Labels: dependencies

#14345 COMPAT locale provider will be removed in a future release
  CHANGELOG-3.0.md
  buildSrc/src/main/java/org/opensearch/gradle/OpenSearchTestBasePlugin.java
  distribution/tools/launchers/src/main/java/org/opensearch/tools/launchers/SystemJvmOptions.java
  gradle/ide.gradle
  server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
  server/src/test/java/org/opensearch/common/joda/JavaJodaTimeDuellingTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
Labels: good first issue, CI, Plugins, v3.0.0, Build

#14372 Fix AwarenessAttributeDecommissionIT.testConcurrentDecommissionAction
  server/src/internalClusterTest/java/org/opensearch/cluster/coordination/AwarenessAttributeDecommissionIT.java
Labels: bug, >test-failure, flaky-test, autocut, skip-changelog, Cluster Manager

#14338 Use remote publication flag to decide which custom objects to upload
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
Labels: backport 2.x, skip-changelog, backport 2.15

#14264 Fix flaky tests in org.opensearch.cluster.routing.remote.RemoteRoutingTableServiceTests
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
Labels: backport 2.x, skip-changelog

#14348 Fix unassigned batch allocation (#13748) (#13748)
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
  server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
Labels: skip-changelog

#14393 [Backport] [2.x] Bump org.wiremock:wiremock-standalone from 3.3.1 to 3.6.0 (#14361)
  CHANGELOG.md
  buildSrc/build.gradle
Labels: dependencies

#14400 [Backport] [2.x] Bump commons-net:commons-net from 3.10.0 to 3.11.1 in /test/fixtures/hdfs-fixture (#14396)
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: dependencies

#14402 [Backport] [2.x] Bump reactor from 3.5.17 to 3.5.18 and reactor-netty from 1.1.19 to 1.1.20 (#14395)
  CHANGELOG.md
  buildSrc/version.properties
  plugins/repository-azure/licenses/reactor-netty-core-1.1.19.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.20.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.19.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.20.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.19.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.20.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.19.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.20.jar.sha1
  server/licenses/reactor-core-3.5.17.jar.sha1
  server/licenses/reactor-core-3.5.18.jar.sha1
Labels: dependencies

#14360 Remove one unnecessary test and simply some code in a test
  server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
Labels: backport 2.x, skip-changelog

#14380 Add missing data types to IngestDocument deep copy
  CHANGELOG.md
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/190_script_processor.yml
  server/src/main/java/org/opensearch/ingest/IngestDocument.java
  server/src/test/java/org/opensearch/ingest/IngestDocumentTests.java
Labels: bug, backport 2.x, Indexing

#14374 [Remote Store] Rate limiter for low priority uploads
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteCloneIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/translogmetadata/mocks/MockFsMetadataSupportedRepository.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/repositories/FilterRepository.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: enhancement, backport 2.x, Storage:Remote

#14418 Fix flaky test IndexShardTests.testCommitLevelRestoreShardFromRemoteStore
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Labels: backport 2.x, skip-changelog

#14417 Update `DEVELOPER_GUIDE.md` to add `gradle-check-flaky-test-detector` automation information
  DEVELOPER_GUIDE.md
Labels: backport 2.x, skip-changelog

#14414 Bump Apache Lucene to 9.12.0-snapshot-c896995
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.11.0.jar.sha1
  libs/core/licenses/lucene-core-9.12.0-snapshot-c896995.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.11.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.12.0-snapshot-c896995.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.11.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.12.0-snapshot-c896995.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.11.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.12.0-snapshot-c896995.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.11.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.12.0-snapshot-c896995.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.11.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.12.0-snapshot-c896995.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.11.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.12.0-snapshot-c896995.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.11.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.12.0-snapshot-c896995.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.11.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-analysis-common-9.11.0.jar.sha1
  server/licenses/lucene-analysis-common-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-backward-codecs-9.11.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-core-9.11.0.jar.sha1
  server/licenses/lucene-core-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-grouping-9.11.0.jar.sha1
  server/licenses/lucene-grouping-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-highlighter-9.11.0.jar.sha1
  server/licenses/lucene-highlighter-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-join-9.11.0.jar.sha1
  server/licenses/lucene-join-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-memory-9.11.0.jar.sha1
  server/licenses/lucene-memory-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-misc-9.11.0.jar.sha1
  server/licenses/lucene-misc-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-queries-9.11.0.jar.sha1
  server/licenses/lucene-queries-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-queryparser-9.11.0.jar.sha1
  server/licenses/lucene-queryparser-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-sandbox-9.11.0.jar.sha1
  server/licenses/lucene-sandbox-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-spatial-extras-9.11.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-spatial3d-9.11.0.jar.sha1
  server/licenses/lucene-spatial3d-9.12.0-snapshot-c896995.jar.sha1
  server/licenses/lucene-suggest-9.11.0.jar.sha1
  server/licenses/lucene-suggest-9.12.0-snapshot-c896995.jar.sha1
Labels: dependencies, skip-changelog

#14409 [Tiered Cache] Use ConcurrentHashMap explicitly in IndicesRequestCache
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: backport 2.x, skip-changelog, Search:Performance

#14086 Switch to iterative version of WKT format parser
  CHANGELOG.md
  libs/geo/src/main/java/org/opensearch/geometry/utils/WellKnownText.java
  libs/geo/src/test/java/org/opensearch/geometry/GeometryCollectionTests.java
Labels: backport 2.x

#14424 Fix flaky test RecoveryFromGatewayIT.testMultipleReplicaShardAssignme…
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
Labels: backport 2.x, skip-changelog

#13568 Set INDICES_MAX_CLAUSE_COUNT dynamically
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/query/QueryStringIT.java
  server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/search/QueryParserHelper.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/SearchService.java
Labels: enhancement, v3.0.0, backport 2.x, Search, v2.16.0

#14357 Remove composeBuild fixture tasks when docker support not found
  buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java
Labels: enhancement, backport 2.x, skip-changelog, Build, ShardManagement:Resiliency

#14433 Fix flaky test : RemoteMigrationIndexMetadataUpdateIT.testRemoteIndexPathFileExistsAfterMigration
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Storage:Remote

#14448 Make the class CommunityIdProcessor final
  CHANGELOG.md
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/CommunityIdProcessor.java
Labels: backport 2.x, skip-changelog

#14394 Add tests for RemoteGlobalMetadataManager
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettingsTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadataTests.java
  test/framework/src/main/java/org/opensearch/common/util/TestCapturingListener.java
Labels: skip-changelog

#14369 Fix Indices Request Cache ITs from flaking and timing out
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheCleanupIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Search, Search:Performance

#13865 Apply the date histogram rewrite optimization to range aggregation
  CHANGELOG.md
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/ScaledFloatFieldMapper.java
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/NumericPointEncoder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/AbstractRangeAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/GeoDistanceAggregatorSupplier.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/GeoDistanceRangeAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregatorSupplier.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregatorTests.java
Labels: Search:Aggregations, backport 2.x, v2.16.0

#14461 Update @dreamer-89 maintainership status
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#14466 Move maintainer tlfeng to emeritus
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#14455 Add more details to testing bad practices
  TESTING.md
Labels: backport 2.x, skip-changelog

#14155 limit the max value of cluster.max_shards_per_node to avoid int overflow
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/ShardLimitValidator.java
  server/src/test/java/org/opensearch/indices/ShardLimitValidatorTests.java
Labels: bug, >breaking, backport 2.x, Cluster Manager

#14416 Optimize UnsignedLong range queries to convert to MatchNoDocsQuery when lower > upper bounds
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java
Labels: enhancement, good first issue, v3.0.0, backport 2.x, Search:Performance, v2.16.0

#12782 [Writable Warm] Composite Directory implementation and integrating it with FileCache
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/WritableWarmIT.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/CloseableFilterIndexOutput.java
  server/src/main/java/org/opensearch/index/store/CompositeDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/CachedFullFileIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FullFileCachedIndexInput.java
  server/src/main/java/org/opensearch/index/store/remote/utils/BlockIOContext.java
  server/src/main/java/org/opensearch/index/store/remote/utils/FileTypeUtils.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/index/store/BaseRemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/CompositeDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/file/OnDemandBlockSnapshotIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FullFileCachedIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerBlobContainerReaderTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerRemoteDirectoryReaderTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTestCase.java
  server/src/test/java/org/opensearch/index/store/remote/utils/cache/RefCountedCacheTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: backport 2.x
