Repository opensearch-project/OpenSearch, pull requests merged in 2024-04, with the labels that each got.

#12962 [Remote Store] Add RemoteStoreSettings class to handle remote store r…
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/indices/DefaultRemoteStoreSettings.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
  server/src/test/java/org/opensearch/indices/RemoteStoreSettingsDynamicUpdateTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoverySettingsDynamicUpdateTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#12285 feat: constant keyword field
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/ConstantKeywordFieldMapper.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldTypeTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/SignificantTextAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, good first issue, discuss, feature, Search

#12974 Detect breaking changes on pull requests v2.0
  .github/workflows/detect-breaking-change.yml
  CHANGELOG.md
  server/build.gradle
Labels: bug, enhancement, Plugins, backport 2.x, API

#12994 Memoize isOnRemoteNode in index settings and refactor as well
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreStatsTrackerFactory.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#12821 [Remote Store] Primary/Replica side changes to support Dual Replication
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationModeAwareProxy.java
  server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/seqno/GlobalCheckpointSyncAction.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandlerFactory.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceFactory.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/test/java/org/opensearch/action/admin/indices/close/TransportVerifyShardBeforeCloseActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/flush/TransportShardFlushActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/readonly/TransportVerifyShardIndexBlockActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/refresh/TransportShardRefreshActionTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
  server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
  server/src/test/java/org/opensearch/action/support/replication/ReplicationModeAwareProxyTests.java
  server/src/test/java/org/opensearch/action/support/replication/ReplicationOperationTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportReplicationActionTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreTestsHelper.java
  server/src/test/java/org/opensearch/index/replication/RetentionLeasesReplicationTests.java
  server/src/test/java/org/opensearch/index/seqno/GlobalCheckpointSyncActionTests.java
  server/src/test/java/org/opensearch/index/seqno/PeerRecoveryRetentionLeaseExpiryTests.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerRetentionLeaseTests.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTestCase.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseBackgroundSyncActionTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseSyncActionTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/PrimaryReplicaSyncerTests.java
  server/src/test/java/org/opensearch/indices/IndicesLifecycleListenerSingleNodeTests.java
  server/src/test/java/org/opensearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
  server/src/test/java/org/opensearch/indices/recovery/PeerRecoverySourceServiceTests.java
  server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestUtils.java
Labels: enhancement, Storage:Durability, RFC, skip-changelog, Storage:Remote

#12938 Add more identifiers to gradle-check job webhook payload
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#13027 Revert "Add more identifiers to gradle-check job webhook payload"
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#13030 Fix detect-breaking-change Github action configuration
  .github/workflows/detect-breaking-change.yml
Labels: bug, skip-changelog, Build

#12569 Add DerivedFieldMapper and support parsing it in mappings
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/MapperServiceTestCase.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, Search

#12989 Cache the shard routings with no weight for faster access
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/test/java/org/opensearch/cluster/structure/RoutingIteratorTests.java
Labels: skip-changelog, Performance

#13056 [Forwardport] [main] Fix bulk API ignores ingest pipeline for upsert (update version)
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
Labels: skip-changelog

#12837 [Derived Fields] Add support for emitting multiple values in DerivedFieldScripts
  modules/lang-painless/src/main/java/org/opensearch/painless/PainlessModulePlugin.java
  modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.derived.txt
  modules/lang-painless/src/test/java/org/opensearch/painless/DerivedFieldScriptTests.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
  server/src/main/java/org/opensearch/script/DerivedFieldScript.java
  server/src/main/java/org/opensearch/script/ScriptEmitValues.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
  server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
  test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Labels: enhancement, skip-changelog, Search

#13044 Remove duplicate methods from RemoteStoreBaseIntegTestCase
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#12981 Finish contributing updates; thanks @acarbonetto
  CONTRIBUTING.md
Labels: skip-changelog

#12988 Update Shallow Snapshot flows to support remote path type & hash algo
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategy.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshot.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshotTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: enhancement, skip-changelog, Storage:Performance, Storage:Resiliency, v2.14.0

#13067 Remove handling of `index.mapper.dynamic` in AutoCreateIndex
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/support/AutoCreateIndex.java
Labels: bug, Indexing, v2.14.0

#13083 [Backport 2.x] [Derived Fields] Add support for emitting multiple values in DerivedFieldScripts
  modules/lang-painless/src/main/java/org/opensearch/painless/PainlessPlugin.java
  modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.derived.txt
  modules/lang-painless/src/test/java/org/opensearch/painless/DerivedFieldScriptTests.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
  server/src/main/java/org/opensearch/script/DerivedFieldScript.java
  server/src/main/java/org/opensearch/script/ScriptEmitValues.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
  server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
  test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Labels: skip-changelog

#13099 Pre computing hash code for WeightedRouting to avoid recomputing it
  server/src/main/java/org/opensearch/cluster/routing/WeightedRouting.java
Labels: skip-changelog

#13023 Introduce interface changes to support read/write blob with object metadata
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsAsyncBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/BlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/BlobDownloadResponse.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/ReadContext.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WriteContext.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainer.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/test/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainerTests.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java
Labels: enhancement, skip-changelog, Storage:Performance, v2.14.0

#12967 Adding support for handling multiple transport protocols
  CHANGELOG.md
  server/build.gradle
  server/src/main/java/org/opensearch/transport/Header.java
  server/src/main/java/org/opensearch/transport/InboundBytesHandler.java
  server/src/main/java/org/opensearch/transport/InboundDecoder.java
  server/src/main/java/org/opensearch/transport/InboundHandler.java
  server/src/main/java/org/opensearch/transport/InboundMessage.java
  server/src/main/java/org/opensearch/transport/InboundPipeline.java
  server/src/main/java/org/opensearch/transport/NativeMessageHandler.java
  server/src/main/java/org/opensearch/transport/ProtocolInboundMessage.java
  server/src/main/java/org/opensearch/transport/ProtocolMessageHandler.java
  server/src/main/java/org/opensearch/transport/TcpTransport.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/NativeInboundBytesHandler.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/NativeInboundMessage.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/package-info.java
  server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/InboundPipelineTests.java
  server/src/test/java/org/opensearch/transport/OutboundHandlerTests.java
Labels: backport 2.x

#13103 Add implementation for remote store path types
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/main/java/org/opensearch/common/blobstore/BlobPath.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryHelperTests.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: enhancement, skip-changelog, Storage:Performance, Storage:Resiliency, v2.14.0

#12960 Skip Filter Allocation Decider during mixed mode for existing indices…
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationAllocationDeciderIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDecider.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/RemoteStoreMigrationAllocationDecider.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java
Labels: bug, skip-changelog, Storage:Remote

#13127 Skip Pull Request Checks / Verify Description Checklist for dependabot
  .github/workflows/pull-request-checks.yml
Labels: skip-changelog

#13040 Create separate file for unreleased 3.0 changes
  .github/workflows/changelog_verifier.yml
  CHANGELOG-3.0.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: bug, Build

#13098 implement mark() in class FilterStreamInput
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/common/io/stream/FilterStreamInput.java
  libs/core/src/test/java/org/opensearch/core/common/io/stream/FilterStreamInputTests.java
Labels: bug, Other

#13090 chore: remove repetitive words
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#13140 [Backport 2.x] Create separate file for unreleased 3.0 changes (#13040)
  .github/workflows/changelog_verifier.yml
  CONTRIBUTING.md
Labels: skip-changelog

#11868 [Snapshot Interop] Add changes for overriding remote store and replic…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
Labels: enhancement, Storage:Snapshots, v2.14.0

#12850 [Derived Fields] PR4: Capability to define derived fields in search request
  client/rest-high-level/src/test/java/org/opensearch/client/SearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java
  server/src/main/java/org/opensearch/action/search/SearchRequestBuilder.java
  server/src/main/java/org/opensearch/index/mapper/DerivedField.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldSupportedTypes.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
  server/src/main/java/org/opensearch/index/mapper/DocumentMapperParser.java
  server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/index/query/VectorGeoPointShapeQueryProcessor.java
  server/src/main/java/org/opensearch/script/DerivedFieldScript.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightPhase.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightUtils.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
  server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java
  server/src/test/java/org/opensearch/search/fetch/subphase/highlight/DerivedFieldFetchAndHighlightTests.java
  test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Labels: enhancement, skip-changelog, Search

#12504 Add ShardBatchCache to support caching for TransportNodesListGatewayStartedShardsBatch
  server/src/internalClusterTest/java/org/opensearch/gateway/GatewayRecoveryTestUtils.java
  server/src/main/java/org/opensearch/gateway/AsyncShardBatchFetch.java
  server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java
  server/src/main/java/org/opensearch/gateway/AsyncShardFetchCache.java
  server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java
  server/src/main/java/org/opensearch/gateway/ShardBatchResponseFactory.java
  server/src/main/java/org/opensearch/gateway/TransportNodesGatewayStartedShardHelper.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShardsBatch.java
  server/src/main/java/org/opensearch/indices/store/ShardAttributes.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java
  server/src/test/java/org/opensearch/gateway/AsyncShardFetchTests.java
  server/src/test/java/org/opensearch/gateway/BatchTestUtil.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/ShardBatchCacheTests.java
  server/src/test/java/org/opensearch/indices/store/ShardAttributesTests.java
Labels: skip-changelog, Cluster Manager

#13164 [BUG] Fix org.opensearch.common.xcontent.XContentParserTests.testString flaky test
  libs/x-content/src/test/java/org/opensearch/common/xcontent/XContentParserTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Other

#13163 [Backport 2.x] [Derived Fields] PR4: Capability to define derived fields in search request
  client/rest-high-level/src/test/java/org/opensearch/client/SearchIT.java
  server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java
  server/src/main/java/org/opensearch/action/search/SearchRequestBuilder.java
  server/src/main/java/org/opensearch/index/mapper/DerivedField.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldSupportedTypes.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
  server/src/main/java/org/opensearch/index/mapper/DocumentMapperParser.java
  server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/index/query/VectorGeoPointShapeQueryProcessor.java
  server/src/main/java/org/opensearch/script/DerivedFieldScript.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightPhase.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightUtils.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
  server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java
  server/src/test/java/org/opensearch/search/fetch/subphase/highlight/DerivedFieldFetchAndHighlightTests.java
  test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Labels: skip-changelog

#13063 [Tiered Caching] Making took time policy dynamic and adding additional IT tests
  CHANGELOG.md
  modules/cache-common/src/internalClusterTest/java/org.opensearch.cache.common.tier/TieredSpilloverCacheIT.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/policy/TookTimePolicy.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/policy/TookTimePolicyTests.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: enhancement, Search:Performance

#13168 Replace the right version to fix backward compatibility introduced wi…
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
Labels: skip-changelog

#13113 Implement interface changes for s3 plugin to read/write blob with obj…
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RetryingInputStreamTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
  server/src/main/java/org/opensearch/common/blobstore/BlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/FetchBlobResult.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WriteContext.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
Labels: enhancement, skip-changelog, Storage:Performance, v2.14.0

#12748 Update index settings during remote store migration
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationShardAllocationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/ResizeIndexMigrationTestCase.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteStoreMigrationAllocationDeciderTests.java
Labels: enhancement, Storage:Durability, skip-changelog, Storage:Remote

#13104 Refactoring globMatch using simpleMatchWithNormalizedStrings from Regex
  CHANGELOG.md
  libs/common/src/main/java/org/opensearch/common/Glob.java
  server/src/main/java/org/opensearch/common/regex/Regex.java
  server/src/test/java/org/opensearch/common/GlobTests.java
Labels: bug, good first issue, backport 2.x, Search

#11977 Fix flakiness with SegmentReplicationSuiteIT
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationSuiteIT.java
  server/src/main/java/org/opensearch/indices/replication/CheckpointInfoResponse.java
  server/src/main/java/org/opensearch/indices/replication/OngoingSegmentReplications.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceHandler.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
  server/src/main/java/org/opensearch/indices/replication/common/CopyState.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/indices/replication/OngoingSegmentReplicationsTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationSourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Indexing:Replication, v2.11.0

#12959 [segment replication] decouple the rateLimiter of segrep and recovery
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteRecoveryTargetHandler.java
  server/src/main/java/org/opensearch/indices/replication/RemoteSegmentFileChunkWriter.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/indices/recovery/RecoverySettingsDynamicUpdateTests.java
Labels: enhancement, documentation pending, Storage:Durability, backport 2.x, Indexing:Replication, Storage:Remote

#13186 [Backport 2.x] Update index settings during remote store migration (#12748)
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationShardAllocationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/ResizeIndexMigrationTestCase.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteStoreMigrationAllocationDeciderTests.java
Labels: skip-changelog

#13195 Update to Apache Lucene 9.11.0-snapshot-fb97840
  buildSrc/version.properties
  libs/core/licenses/lucene-core-9.11.0-snapshot-8a555eb.jar.sha1
  libs/core/licenses/lucene-core-9.11.0-snapshot-fb97840.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.11.0-snapshot-8a555eb.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.11.0-snapshot-fb97840.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.11.0-snapshot-fb97840.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.11.0-snapshot-fb97840.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.11.0-snapshot-fb97840.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.11.0-snapshot-fb97840.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.11.0-snapshot-fb97840.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.11.0-snapshot-fb97840.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.11.0-snapshot-8a555eb.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.11.0-snapshot-fb97840.jar.sha1
  server/build.gradle
  server/licenses/lucene-analysis-common-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-analysis-common-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-backward-codecs-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-backward-codecs-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-core-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-core-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-grouping-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-grouping-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-highlighter-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-highlighter-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-join-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-join-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-memory-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-memory-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-misc-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-misc-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-queries-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-queries-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-queryparser-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-queryparser-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-sandbox-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-sandbox-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-spatial-extras-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-spatial-extras-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-spatial3d-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-spatial3d-9.11.0-snapshot-fb97840.jar.sha1
  server/licenses/lucene-suggest-9.11.0-snapshot-8a555eb.jar.sha1
  server/licenses/lucene-suggest-9.11.0-snapshot-fb97840.jar.sha1
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: dependencies, skip-changelog

#12904 [Tiered Caching] Ehcache Disk cache IT
  plugins/cache-ehcache/build.gradle
  plugins/cache-ehcache/src/internalClusterTest/java/org/opensearch/cache/EhcacheDiskCacheIT.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/EhcacheDiskCacheSettings.java
Labels: skip-changelog

#13199 [BUG] Fix missing javadocs error for nested generated types
  doc-tools/missing-doclet/src/main/java/org/opensearch/missingdoclet/MissingDoclet.java
Labels: bug, javadocs, skip-changelog, Build, Other

#13167 Enhance changelog workflow to check for missing labels
  .github/workflows/changelog_verifier.yml
Labels: skip-changelog

#13204 Update maintainers based on activity since Jan 2024
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#13208 Triage meetings have moved to Zoom
  TRIAGING.md
Labels: skip-changelog

#13179 Add cluster setting to dynamically disable filter rewrite optimization
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/FilterRewriteIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
Labels: backport 2.x, v2.14.0

#13159 [Remote Store - Dual Replication] Create missing Retention Leases for docrep shard copies during failover
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
Labels: bug, skip-changelog, Storage:Remote

#13155 Add faster scaling composite hash value encoding for remote path
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshotTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#13193 Bump joda from 2.12.2 to 2.12.7
  CHANGELOG.md
  buildSrc/version.properties
  server/licenses/joda-time-2.12.2.jar.sha1
  server/licenses/joda-time-2.12.7.jar.sha1
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Labels: enhancement, >FORK, Rename, v2.0.0, v1.1.0, backport 2.x

#13188 [Fix FuzzyFilterPostingsFormatTests] Suppress sys out checks for test case
  server/src/test/java/org/opensearch/index/codec/fuzzy/FuzzyFilterPostingsFormatTests.java
Labels: bug, flaky-test, skip-changelog, Indexing, Other

#12971 Remove compatibility checker
  .github/workflows/check-compatibility.yml
Labels: enhancement, discuss, RFC, skip-changelog, Build

#13218 Add warn logs for remote backpressure rejection
  server/src/main/java/org/opensearch/index/remote/RemoteStorePressureService.java
Labels: skip-changelog

#13226 [Backport 2.x] Remove compatibility checker (#12971)
  .github/workflows/check-compatibility.yml
Labels: backport, skip-changelog

#13243 Bump bouncycastle from 1.77 to 1.78
  CHANGELOG.md
  buildSrc/version.properties
  plugins/identity-shiro/licenses/bcprov-jdk18on-1.77.jar.sha1
  plugins/identity-shiro/licenses/bcprov-jdk18on-1.78.jar.sha1
  plugins/ingest-attachment/licenses/bcmail-jdk18on-1.77.jar.sha1
  plugins/ingest-attachment/licenses/bcmail-jdk18on-1.78.jar.sha1
  plugins/ingest-attachment/licenses/bcpkix-jdk18on-1.77.jar.sha1
  plugins/ingest-attachment/licenses/bcpkix-jdk18on-1.78.jar.sha1
  plugins/ingest-attachment/licenses/bcprov-jdk18on-1.77.jar.sha1
  plugins/ingest-attachment/licenses/bcprov-jdk18on-1.78.jar.sha1
Labels: dependencies, backport 2.x

#13244 Revert "Add faster scaling composite hash value encoding for remote path"
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshotTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#13216 Cleanup CHANGELOG-3.0
  CHANGELOG-3.0.md
Labels: skip-changelog

#13248 Fix flaky test SegmentReplicationTargetServiceTests#testShardAlreadyReplicating
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Labels: bug, >test-failure, flaky-test, backport 2.x, skip-changelog, Search:Remote Search

#12812 Snapshot _status API to return correct status for partial snapshots
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java
  server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
Labels: bug, good first issue, distributed framework

#13028 [Backport 2.x] Remote Store - Add Primary/Replica side changes to support Dual Replication during Remote Store Migration
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
  server/src/main/java/org/opensearch/action/bulk/TransportShardBulkAction.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationModeAwareProxy.java
  server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/seqno/GlobalCheckpointSyncAction.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/index/shard/CheckpointRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/cluster/IndicesClusterStateService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandlerFactory.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceFactory.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/test/java/org/opensearch/action/admin/indices/close/TransportVerifyShardBeforeCloseActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/flush/TransportShardFlushActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/readonly/TransportVerifyShardIndexBlockActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/refresh/TransportShardRefreshActionTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportShardBulkActionTests.java
  server/src/test/java/org/opensearch/action/resync/TransportResyncReplicationActionTests.java
  server/src/test/java/org/opensearch/action/support/replication/ReplicationModeAwareProxyTests.java
  server/src/test/java/org/opensearch/action/support/replication/ReplicationOperationTests.java
  server/src/test/java/org/opensearch/action/support/replication/TransportReplicationActionTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreTestsHelper.java
  server/src/test/java/org/opensearch/index/replication/RetentionLeasesReplicationTests.java
  server/src/test/java/org/opensearch/index/seqno/GlobalCheckpointSyncActionTests.java
  server/src/test/java/org/opensearch/index/seqno/PeerRecoveryRetentionLeaseExpiryTests.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerRetentionLeaseTests.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTestCase.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseBackgroundSyncActionTests.java
  server/src/test/java/org/opensearch/index/seqno/RetentionLeaseSyncActionTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/PrimaryReplicaSyncerTests.java
  server/src/test/java/org/opensearch/indices/IndicesLifecycleListenerSingleNodeTests.java
  server/src/test/java/org/opensearch/indices/cluster/AbstractIndicesClusterStateServiceTestCase.java
  server/src/test/java/org/opensearch/indices/recovery/PeerRecoverySourceServiceTests.java
  server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointActionTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestUtils.java
Labels: skip-changelog

#13251 Add faster scaling composite hash value encoding for remote path
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshotTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#12691 [Remote Store] Cleanup local-only translog files if no metadata in remote
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Labels: skip-changelog

#13225 Add remote path settings to RemoteStoreSettings class
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
  server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#13054 enabled mockTelemetryPlugin for IT and fixed OOM
  CHANGELOG.md
  TESTING.md
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java
Labels: bug, flaky-test, backport 2.x, Other

#13213 Update google dependencies in repository-gcs and discovery-gce
  CHANGELOG.md
  buildSrc/version.properties
  plugins/discovery-gce/build.gradle
  plugins/discovery-gce/licenses/google-api-client-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-api-client-1.35.2.jar.sha1
  plugins/discovery-gce/licenses/google-api-services-compute-v1-rev160-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-api-services-compute-v1-rev235-1.25.0.jar.sha1
  plugins/discovery-gce/licenses/google-http-client-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-http-client-1.44.1.jar.sha1
  plugins/discovery-gce/licenses/google-http-client-gson-1.44.1.jar.sha1
  plugins/discovery-gce/licenses/google-http-client-jackson2-1.23.0.jar.sha1
  plugins/discovery-gce/licenses/google-http-client-jackson2-1.44.1.jar.sha1
  plugins/discovery-gce/licenses/grpc-api-1.57.2.jar.sha1
  plugins/discovery-gce/licenses/grpc-api-LICENSE.txt
  plugins/discovery-gce/licenses/grpc-api-NOTICE.txt
  plugins/discovery-gce/licenses/guava-32.1.1-jre.jar.sha1
  plugins/discovery-gce/licenses/guava-LICENSE.txt
  plugins/discovery-gce/licenses/guava-NOTICE.txt
  plugins/discovery-gce/licenses/opencensus-LICENSE.txt
  plugins/discovery-gce/licenses/opencensus-NOTICE.txt
  plugins/discovery-gce/licenses/opencensus-api-0.31.1.jar.sha1
  plugins/discovery-gce/licenses/opencensus-contrib-http-util-0.31.1.jar.sha1
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/google-http-client-1.43.3.jar.sha1
  plugins/repository-gcs/licenses/google-http-client-1.44.1.jar.sha1
  plugins/repository-gcs/licenses/google-http-client-appengine-1.43.3.jar.sha1
  plugins/repository-gcs/licenses/google-http-client-appengine-1.44.1.jar.sha1
  plugins/repository-gcs/licenses/google-http-client-gson-1.43.3.jar.sha1
  plugins/repository-gcs/licenses/google-http-client-gson-1.44.1.jar.sha1
Labels: backport 2.x

#13262 [Forwardport] Snapshot _status API to return correct status for partial snapshots (update version)
  server/src/main/java/org/opensearch/cluster/SnapshotsInProgress.java
Labels: skip-changelog

#13265 [Backport 2.x] Fix flaky test SegmentReplicationTargetServiceTests#testShardAlreadyReplicating
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Labels: skip-changelog

#13269 [Backport 2.x] enabled mockTelemetryPlugin for IT and fixed OOM (#13054)
  CHANGELOG.md
  TESTING.md
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/telemetry/src/main/java/org/opensearch/test/telemetry/tracing/StrictCheckSpanProcessor.java
Labels: bug, flaky-test, backport 2.x, backport-failed, Other

#13261 [Backport 2.x][Remote Store] Cleanup local-only translog files if no metadata in remote (#12691)
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Labels: skip-changelog

#13281 Fix flakiness in testDontAllowSwitchingCompatibilityModeForClusterWit…
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
Labels: bug, flaky-test, skip-changelog, Cluster Manager

#13279 Update supported version in yaml test file for the primary_only parameter in force-merge API
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.forcemerge/10_basic.yml
Labels: skip-changelog

#13283 Disabling breaking changes check on main
  .github/workflows/detect-breaking-change.yml
Labels: skip-changelog

#13126 Replacing InboundMessage with NativeInboundMessage for deprecation
  server/src/main/java/org/opensearch/transport/InboundAggregator.java
  server/src/main/java/org/opensearch/transport/InboundMessage.java
  server/src/main/java/org/opensearch/transport/NativeMessageHandler.java
  server/src/main/java/org/opensearch/transport/TcpTransport.java
  server/src/main/java/org/opensearch/transport/TransportLogger.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/NativeInboundBytesHandler.java
  server/src/test/java/org/opensearch/transport/InboundAggregatorTests.java
  server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/InboundPipelineTests.java
  server/src/test/java/org/opensearch/transport/OutboundHandlerTests.java
Labels: v3.0.0, skip-changelog

#13290 Ignore BaseRestHandler unconsumed content check as it's always consumed
  CHANGELOG.md
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
  server/src/test/java/org/opensearch/action/admin/indices/forcemerge/RestForceMergeActionTests.java
  server/src/test/java/org/opensearch/rest/BaseRestHandlerTests.java
  server/src/test/java/org/opensearch/search/pit/RestDeletePitActionTests.java
Labels: bug, backport 2.x, Other

#13313 Fix the flaky test for derived fields highlighter test
  server/src/test/java/org/opensearch/search/fetch/subphase/highlight/DerivedFieldFetchAndHighlightTests.java
Labels: bug, flaky-test, skip-changelog, Search

#13012 Improve error messages for `_stats` with closed indices
  CHANGELOG.md
  modules/rank-eval/src/internalClusterTest/java/org/opensearch/index/rankeval/RankEvalRequestIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexNameExpressionResolverTests.java
Labels: bug, v3.0.0, backport 2.x, Indexing, API, v2.14.0

#13282 [Remote Store] Throw IOException when remote is not in sync
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteCloneIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
Labels: skip-changelog

#13298 Ignoring unavailable shards during search request execution with igno…
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: bug, Indexing & Search, backport 2.x, Search

#13136 Prefer remote replicas for primary promotion during migration
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/FailedShardsRoutingTests.java
Labels: enhancement, Storage:Durability, skip-changelog, Storage:Remote

#13301 [Remote Store] Handle OpenSearchRejectedExecutionException while retrying refresh
  server/src/main/java/org/opensearch/index/shard/ReleasableRetryableRefreshListener.java
  server/src/test/java/org/opensearch/index/shard/ReleasableRetryableRefreshListenerTests.java
Labels: skip-changelog

#13344 Skip Search Pipeline integration tests for OpenSearch versions below 2.9.0
  rest-api-spec/src/main/resources/rest-api-spec/test/search_pipeline/10_basic.yml
Labels: bug, skip-changelog, Search

#13047 Fix from and size parameter can be negative when searching
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/360_from_and_size.yml
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java
Labels: backport 2.x, skip-changelog

#13347 [Backport 2.x] Prevent version upgrade during remote migration (#13185)
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
Labels: skip-changelog

#13329 Bump com.github.spullara.mustache.java:compiler from 0.9.10 to 0.9.11
  CHANGELOG.md
  modules/lang-mustache/build.gradle
  modules/lang-mustache/licenses/compiler-0.9.10.jar.sha1
  modules/lang-mustache/licenses/compiler-0.9.11.jar.sha1
  modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache/20_render_search_template.yml
Labels: backport 2.x, skip-changelog

#13150 Upload remote paths during index creation or full cluster upload
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreUploadIndexPathIT.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainer.java
  server/src/main/java/org/opensearch/gateway/remote/IndexMetadataUploadListener.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPath.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategy.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/repositories/blobstore/BaseBlobStoreFormat.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
  server/src/main/java/org/opensearch/repositories/blobstore/ConfigBlobStoreFormat.java
  server/src/test/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainerTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteIndexPathTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteIndexPathUploaderTests.java
Labels: enhancement, skip-changelog, Storage:Performance, Storage:Resiliency

#13259 Fix flat_object long field error
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldDataTests.java
Labels: backport 2.x

#13360 [Forwardport 2.x] Added bwc version 1.3.17
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#13364 [Backport 2.x - Remote Store - Dual Replication] Create missing Retention Leases for docrep shard copies during failover
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
Labels: skip-changelog

#13070 [Tiered Caching] Bug fix for IndicesRequestCache StaleKey management
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: enhancement, backport, backport 2.x, Search:Performance

#13350 Fix Flaky Test PersistentTasksExecutorFullRestartIT.testFullClusterRe…
  server/src/internalClusterTest/java/org/opensearch/persistent/PersistentTasksExecutorFullRestartIT.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Cluster Manager

#12992 [Remote Store] Add capability of doing refresh as determined by the translog
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/test/java/org/opensearch/indices/RemoteStoreSettingsDynamicUpdateTests.java
Labels: enhancement, backport 2.x, Storage:Remote

#12922 Integrate local recovery with remote store seeding during migration
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryLocalRecoveryIT.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/TranslogConfig.java
  server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/shard/RefreshListenersTests.java
  server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
  server/src/test/java/org/opensearch/index/translog/LocalTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogManagerTestCase.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
Labels: skip-changelog

#11411 Allow index & cluster default refresh interval setting value to be -1
  server/src/internalClusterTest/java/org/opensearch/cluster/metadata/ClusterIndexRefreshIntervalIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
Labels: bug, Storage:Durability, backport 2.x, skip-changelog

#13309 Take shallow copy snapshot only when remote store compatibility mode is STRICT
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationShardAllocationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Labels: enhancement, skip-changelog, Storage:Snapshots

#13377 [Backport 2.x] Prefer remote replicas for primary promotion during migration (#13136)
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/FailedShardsRoutingTests.java
Labels: skip-changelog

#13006 [Backport 2.x] FIX: UOE While building Exists query for nested search_as_you_type field
  CHANGELOG.md
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapperTests.java
  server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java
  test/framework/src/main/java/org/opensearch/index/mapper/MapperServiceTestCase.java
Labels: bug, good first issue, Search

#13383 flaky test fix - assert cluster stats on ClusterManager Node
  server/src/internalClusterTest/java/org/opensearch/discovery/ClusterManagerDisruptionIT.java
Labels: backport 2.x, skip-changelog

#8746 Async Batch shards changes for GatewayAllocator
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/ExistingShardsAllocator.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/ShardBatchCacheTests.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestGatewayAllocator.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Labels: backport 2.x, Cluster Manager

#13390 [Backport 2.x] Introduce remote store path type in customData in IndexMetadata (#12607)
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathResolver.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathType.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: skip-changelog

#13373 [Tiered Caching] Expose a dynamic setting to disable/enable disk cache
  CHANGELOG.md
  modules/cache-common/src/internalClusterTest/java/org.opensearch.cache.common.tier/TieredSpilloverCacheIT.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCachePluginTests.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
Labels: enhancement, backport 2.x, Search:Performance

#12941 [Tiered Caching] Make Indices Request Cache Stale Key Mgmt Threshold setting dynamic
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: enhancement, backport, backport 2.x, Search:Performance

#13406 OpenJDK Update (April 2024 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Labels: dependencies, Build

#13412 Switch to macos-13 runner for precommit and assemble github actions due to macos-latest is now arm64
  .github/workflows/assemble.yml
  .github/workflows/precommit.yml
  CHANGELOG.md
Labels: enhancement, backport 2.x

#13423 [Backport 2.x] Add implementation for remote store path types
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/main/java/org/opensearch/common/blobstore/BlobPath.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryHelperTests.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: skip-changelog

#13424 [Backport 2.x] Add faster scaling composite hash value encoding for remote path
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/snapshots/blobstore/RemoteStoreShardShallowCopySnapshotTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#13427 [Backport 2.x] Upload remote paths during index creation or full cluster upload
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreUploadIndexPathIT.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainer.java
  server/src/main/java/org/opensearch/gateway/remote/IndexMetadataUploadListener.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPath.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategy.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/repositories/blobstore/BaseBlobStoreFormat.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
  server/src/main/java/org/opensearch/repositories/blobstore/ConfigBlobStoreFormat.java
  server/src/test/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainerTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteIndexPathTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteIndexPathUploaderTests.java
Labels: skip-changelog

#13238 [Tiered Caching] Stats rework (2/4): Gates CacheStatsHolder logic behind FeatureFlags.PLUGGABLE_CACHE setting
  CHANGELOG.md
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  server/src/main/java/org/opensearch/common/cache/stats/CacheStatsHolder.java
  server/src/main/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolder.java
  server/src/main/java/org/opensearch/common/cache/stats/NoopCacheStatsHolder.java
  server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolderTests.java
  server/src/test/java/org/opensearch/common/cache/stats/ImmutableCacheStatsHolderTests.java
  server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: backport 2.x

#13415 Restore deleted section of Contributing.md
  CONTRIBUTING.md
Labels: skip-changelog

#13115 Add more Remote Migration Integration Tests
  server/src/internalClusterTest/java/org/opensearch/remotemigration/DocRepMigrationTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteDualReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteReplicaRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/ResizeIndexMigrationTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#13436 [Remote Store] Update version to 2.14 in path type min node version check
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
Labels: backport 2.x, skip-changelog, Storage:Remote

#13386 Add version details in remote index path file with code enhancements
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreUploadIndexPathIT.java
  server/src/main/java/org/opensearch/gateway/remote/IndexMetadataUploadListener.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPath.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/test/java/org/opensearch/index/remote/RemoteIndexPathUploaderTests.java
Labels: enhancement, skip-changelog, Storage:Remote, v2.14.0

#13400 Add unit test of multipler orders for multiple terms aggregation.
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/370_multi_terms.yml
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregationBuilder.java
Labels: bug, Search:Aggregations, backport 2.x, skip-changelog

#13276 [Search Pipeline]Handled default search pipeline for multiple indices
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: enhancement, backport 2.x, Search, Search:Relevance, v2.14.0

#13237 [Tiered Caching] Stats rework (3/4): Exposing new cache stats API
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamInput.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  server/src/internalClusterTest/java/org/opensearch/indices/CacheStatsAPIIndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
  server/src/main/java/org/opensearch/common/cache/CacheType.java
  server/src/main/java/org/opensearch/common/cache/ICache.java
  server/src/main/java/org/opensearch/common/cache/service/CacheService.java
  server/src/main/java/org/opensearch/common/cache/service/NodeCacheStats.java
  server/src/main/java/org/opensearch/common/cache/stats/CacheStats.java
  server/src/main/java/org/opensearch/common/cache/stats/CacheStatsHolder.java
  server/src/main/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolder.java
  server/src/main/java/org/opensearch/common/cache/stats/ImmutableCacheStats.java
  server/src/main/java/org/opensearch/common/cache/stats/ImmutableCacheStatsHolder.java
  server/src/main/java/org/opensearch/common/cache/stats/NoopCacheStatsHolder.java
  server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java
  server/src/main/java/org/opensearch/index/cache/request/ShardRequestCache.java
  server/src/main/java/org/opensearch/indices/AbstractIndexShardCacheEntity.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  server/src/test/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolderTests.java
  server/src/test/java/org/opensearch/common/cache/stats/ImmutableCacheStatsHolderTests.java
  server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: backport 2.x

#13453 Fix Flaky test IndicesRequestCacheIT.testStaleKeysCleanupWithMultipleIndices
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Search

#13306 Support batch ingestion in bulk API (#12457)
  CHANGELOG.md
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
  rest-api-spec/src/main/resources/rest-api-spec/api/bulk.json
  server/src/main/java/org/opensearch/action/bulk/BulkRequest.java
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
  server/src/main/java/org/opensearch/common/metrics/OperationMetrics.java
  server/src/main/java/org/opensearch/ingest/CompoundProcessor.java
  server/src/main/java/org/opensearch/ingest/IngestDocumentWrapper.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/ingest/Pipeline.java
  server/src/main/java/org/opensearch/ingest/Processor.java
  server/src/main/java/org/opensearch/rest/action/document/RestBulkAction.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
  server/src/test/java/org/opensearch/ingest/CompoundProcessorTests.java
  server/src/test/java/org/opensearch/ingest/IngestDocumentPreparer.java
  server/src/test/java/org/opensearch/ingest/IngestDocumentWrapperTests.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
  server/src/test/java/org/opensearch/ingest/ProcessorTests.java
Labels: backport 2.x, ingest-pipeline

#13460 [Tiered Caching] Bump versions for serialization in new cache stats API
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
  server/src/main/java/org/opensearch/index/cache/request/ShardRequestCache.java
Labels: skip-changelog

#13118 [Flaky Test] Setting the response before latch countdown
  server/src/internalClusterTest/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionForClusterManagerIT.java
Labels: bug, flaky-test, skip-changelog, Cluster Manager

#13449 [Backport] [2.x] Bump org.bouncycastle:bc-fips from 1.0.2.4 to 1.0.2.5 in /distribution/tools/plugin-cli (#13446)
  CHANGELOG.md
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/plugin-cli/licenses/bc-fips-1.0.2.4.jar.sha1
  distribution/tools/plugin-cli/licenses/bc-fips-1.0.2.5.jar.sha1
Labels: dependencies
