Repository opensearch-project/OpenSearch, pull requests merged in 2024-11, with the labels that each got.

#16532 Remove resource usages object from search response headers
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchTaskRequestOperationsListener.java
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
  server/src/main/java/org/opensearch/tasks/TaskResourceTrackingService.java
Labels: backport 2.x

#16484 Adds cluster setting to allow caching requests with size>0 in request cache
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
Labels: enhancement, backport 2.x, Search:Performance

#16543 Support retrieving doc values of unsigned long field
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/fielddata/plain/SortedNumericIndexFieldData.java
  server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java
Labels: v3.0.0, backport 2.x, v2.19.0

#16554 Bump versions in README to 2.19.0 and 2.18.1
  README.md
Labels: skip-changelog

#16483 rollover alias supports restored searchable snapshot index
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/alias/TransportIndicesAliasesAction.java
  server/src/main/java/org/opensearch/action/admin/indices/rollover/TransportRolloverAction.java
  server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
  server/src/main/java/org/opensearch/cluster/block/ClusterBlocks.java
  server/src/test/java/org/opensearch/cluster/block/ClusterBlocksTests.java
Labels: bug, backport 2.x, Search:Searchable Snapshots

#16564 Improve performance for resolving derived fields
  server/src/main/java/org/opensearch/index/mapper/DefaultDerivedFieldResolver.java
Labels: v3.0.0, backport 2.x, skip-changelog, v2.19.0

#16575 Fix non-x64 bwc build targets
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java
Labels: bug, backport 2.x, skip-changelog, Build

#16585 Detect Breaking Changes check does not fail on new method added to an @PublicApi interface
  server/build.gradle
Labels: bug, skip-changelog, Build

#16583 Make IndexStoreListener a pluggable interface
  CHANGELOG.md
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/index/store/IndexStoreListener.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/IndexStorePlugin.java
  server/src/test/java/org/opensearch/env/NodeEnvironmentTests.java
Labels: backport 2.x, v2.19.0

#16590 [2.18] Fix NPE in CatShardsRequestTests on version bump
  server/src/test/java/org/opensearch/action/admin/cluster/shards/CatShardsRequestTests.java
Labels: bug, skip-changelog, Other

#16561 Adds Integration Tests for Search Pipeline
  modules/search-pipeline-common/src/internalClusterTest/java/org/opensearch/search/pipeline/common/SearchPipelineCommonIT.java
Labels: skip-changelog

#16600 Add a flag in QueryShardContext to differentiate inner hit query
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
Labels: backport 2.x

#16489 Add vertical scaling and SoftReference for snapshot repository data cache
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Labels: enhancement, good first issue, v3.0.0, skip-changelog, Storage:Snapshots, v2.19.0

#16488 Add a new configuration setting `synonym_analyzer` for `synonym_graph` and `synonym`.
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisModulePlugin.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymGraphTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/SynonymTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/CommonAnalysisFactoryTests.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/SynonymsAnalysisTests.java
  server/src/main/java/org/opensearch/indices/analysis/AnalysisModule.java
  server/src/main/java/org/opensearch/plugins/AnalysisPlugin.java
  server/src/test/java/org/opensearch/indices/analysis/AnalysisModuleTests.java
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: backport 2.x

#16271 Support prefix list for remote repository attributes
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemotePublicationConfigurationIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRepositoryConfigurationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
  server/src/main/java/org/opensearch/index/remote/RemoteMigrationIndexMetadataUpdater.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteIndexPathUploaderTests.java
  server/src/test/java/org/opensearch/node/RemoteStoreNodeAttributeTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/RemoteStoreAttributeConstants.java
Labels: backport 2.x, skip-changelog

#16520 Bump google-auth-library-oauth2-http from 1.7.0 to 1.29.0 in /plugins/repository-gcs
  CHANGELOG.md
  gradle/libs.versions.toml
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/google-auth-library-credentials-1.29.0.jar.sha1
  plugins/repository-gcs/licenses/google-auth-library-credentials-1.7.0.jar.sha1
  plugins/repository-gcs/licenses/google-auth-library-oauth2-http-1.29.0.jar.sha1
  plugins/repository-gcs/licenses/google-auth-library-oauth2-http-1.7.0.jar.sha1
  plugins/repository-gcs/src/test/java/org/opensearch/repositories/gcs/GoogleCloudStorageServiceTests.java
Labels: backport 2.x

#16617 Fix stale index deletion in snapshots for hashed prefix path type
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardPaths.java
Labels: skip-changelog

#16581 Support installing plugin SNAPSHOTs with SNASPHOT distribution
  CHANGELOG.md
  distribution/tools/plugin-cli/src/main/java/org/opensearch/plugins/InstallPluginCommand.java
  distribution/tools/plugin-cli/src/test/java/org/opensearch/plugins/InstallPluginCommandTests.java
Labels: Plugins, backport 2.x, skip-changelog

#16533 Update DEVELOPER_GUIDE.md instructions for JDK-11
  DEVELOPER_GUIDE.md
Labels: skip-changelog

#16652 Update version check in yaml test file for allowing composite aggregation to run under a parent filter aggregation
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
Labels: backport 2.x, skip-changelog

#16655 Bump mockito from 5.14.1 to 5.14.2, objenesis from 3.2 to 3.3 and bytebuddy from 1.15.4 to 1.15.10
  CHANGELOG.md
  gradle/libs.versions.toml
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
  test/framework/build.gradle
Labels: dependencies, backport 2.x, skip-changelog

#16628 Search dv only IP masks
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml
  server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/IpFieldTypeTests.java
Labels: bug, v3.0.0, backport 2.x, v2.19.0

#16670 Fix stale cluster state custom file deletion
  CHANGELOG.md
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
Labels: backport 2.x

#16386 Update Gradle to 8.11
  build.gradle
  buildSrc/src/main/groovy/org/opensearch/gradle/test/TestWithDependenciesPlugin.groovy
  buildSrc/src/main/java/org/opensearch/gradle/LoggedExec.java
  buildSrc/src/main/java/org/opensearch/gradle/PublishPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
  gradle/missing-javadoc.gradle
  gradle/wrapper/gradle-wrapper.properties
  libs/build.gradle
  modules/lang-painless/build.gradle
Labels: skip-changelog, Build

#16685 Update Gradle version for Detect Breaking Changes Github action
  .github/workflows/detect-breaking-change.yml
Labels: skip-changelog

#16570 Change setting allowing size > 0 queries in request cache to be an int threshold
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
Labels: enhancement, skip-changelog, Search:Performance

#16694 Update Gradle to 8.11.1
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x, skip-changelog

#16560 [Bugfix] Fix TieredSpilloverCache stats not adding correctly when shards are closed
  CHANGELOG.md
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsIT.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsHolder.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsHolderTests.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  server/src/main/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolder.java
Labels: bug, backport 2.x, Search

#15364 Removed unused array
  server/src/main/java/org/opensearch/search/aggregations/bucket/BucketsAggregator.java
Labels: backport 2.x, skip-changelog

#16737 [Flaky Test] Fix Flaky Test SearchWithRandomExceptionsIT.testRandomExceptions
  server/src/internalClusterTest/java/org/opensearch/search/basic/SearchWithRandomExceptionsIT.java
Labels: >test-failure, flaky-test, autocut, skip-changelog
