Repository opensearch-project/OpenSearch, pull requests merged in 2024-07, with the labels that each got.

#14605 Star tree mapping changes
  distribution/src/config/opensearch.yml
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataMappingService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexValidator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DateDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/Dimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/Metric.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/MetricStat.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/NumericDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeField.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeFieldConfiguration.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeIndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeValidator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/package-info.java
  server/src/main/java/org/opensearch/index/mapper/CompositeDataCubeFieldType.java
  server/src/main/java/org/opensearch/index/mapper/CompositeMappedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/Mapper.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/RootObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: skip-changelog

#14564 [Bugfix] Fix ICacheKeySerializerTests flakiness
  server/src/test/java/org/opensearch/common/cache/serializer/ICacheKeySerializerTests.java
Labels: >test-failure, flaky-test, backport 2.x, autocut, skip-changelog, Search:Performance, Storage:Performance

#14621 Correct typo in method name
  server/src/test/java/org/opensearch/index/get/GetResultTests.java
Labels: backport 2.x, skip-changelog

#14200 Refactoring FilterPath.parse by using an iterative approach instead of recursion.
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/xcontent/filtering/FilterPath.java
  libs/core/src/test/java/org/opensearch/core/xcontent/filtering/FilterPathTests.java
Labels: bug, good first issue, backport 2.x, Search

#14612 Removing String format in RemoteStoreMigrationAllocationDecider
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/RemoteStoreMigrationAllocationDecider.java
Labels: backport 2.x, skip-changelog

#14513 Clear templates before Adding; Use NamedWriteableAwareStreamInput for RemoteCustomMetadata; Correct the check for deciding upload of HashesOfConsistentSettings
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
Labels: skip-changelog

#14613 Removing unnecessary List.removeAll from LocalShardsBalancer to filter remote search shard from relocation decision
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
Labels: skip-changelog

#14601 Fix assertion failure while deleting remote backed index
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/IndexService.java
Labels: backport 2.x, skip-changelog

#14635 Allow system index warning in OpenSearchRestTestCase.refreshAllIndices
  CHANGELOG.md
  test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java
Labels: backport 2.x

#14514 Star tree codec changes
  server/src/main/java/org/opensearch/index/codec/CodecService.java
  server/src/main/java/org/opensearch/index/codec/composite/Composite99Codec.java
  server/src/main/java/org/opensearch/index/codec/composite/Composite99DocValuesFormat.java
  server/src/main/java/org/opensearch/index/codec/composite/Composite99DocValuesReader.java
  server/src/main/java/org/opensearch/index/codec/composite/Composite99DocValuesWriter.java
  server/src/main/java/org/opensearch/index/codec/composite/CompositeCodecFactory.java
  server/src/main/java/org/opensearch/index/codec/composite/CompositeIndexReader.java
  server/src/main/java/org/opensearch/index/codec/composite/CompositeIndexValues.java
  server/src/main/java/org/opensearch/index/codec/composite/datacube/startree/StarTreeValues.java
  server/src/main/java/org/opensearch/index/codec/composite/datacube/startree/package-info.java
  server/src/main/java/org/opensearch/index/codec/composite/package-info.java
  server/src/main/java/org/opensearch/index/mapper/CompositeMappedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  server/src/test/java/org/opensearch/index/codec/CodecTests.java
  server/src/test/java/org/opensearch/index/codec/composite/datacube/startree/StarTreeDocValuesFormatTests.java
Labels: skip-changelog

#13669 Adding QueryGroup schema
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/QueryGroup.java
  server/src/main/java/org/opensearch/cluster/metadata/QueryGroupMetadata.java
  server/src/main/java/org/opensearch/search/ResourceType.java
  server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/metadata/QueryGroupMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/QueryGroupTests.java
  server/src/test/java/org/opensearch/search/backpressure/SearchBackpressureServiceTests.java
  server/src/test/java/org/opensearch/search/backpressure/trackers/NodeDuressTrackersTests.java
Labels: backport 2.x

#14660 Add UTs for RemoteIndexMetadataManager
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteIndexMetadataManagerTests.java
Labels: skip-changelog

#10959 Fix match_phrase_prefix_query not working on text field with multiple values and index_prefixes
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/190_index_prefix_search.yml
  server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldTypeTests.java
Labels: v3.0.0, backport 2.x, Search, v2.16.0

#14675 Offline calculation of total shard across all node and caching it for weight calculation inside LocalShardBalancer
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
Labels: skip-changelog

#14587 [bug fix] validate lower bound for top n size
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/TopQueriesServiceTests.java
Labels: backport 2.x, skip-changelog

#14415 Create SystemIndexRegistry with helper method matchesSystemIndex
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/SystemIndexDescriptor.java
  server/src/main/java/org/opensearch/indices/SystemIndexRegistry.java
  server/src/main/java/org/opensearch/indices/SystemIndices.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/indices/SystemIndicesTests.java
Labels: v3.0.0, backport 2.x, v2.16.0

#14206 Refactor Grok validate pattern to iterative approach
  CHANGELOG.md
  libs/grok/src/main/java/org/opensearch/grok/Grok.java
  libs/grok/src/test/java/org/opensearch/grok/GrokTests.java
Labels: backport 2.x, v2.16.0

#14674 Bump opentelemetry from 1.39.0 to 1.40.0
  CHANGELOG.md
  buildSrc/version.properties
  plugins/telemetry-otel/licenses/opentelemetry-api-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-incubator-1.39.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-incubator-1.40.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.39.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.25.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.26.0-alpha.jar.sha1
Labels: dependencies, backport 2.x

#14687 Bump jackson from 2.17.1 to 2.17.2
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.17.1.jar.sha1
  client/sniffer/licenses/jackson-core-2.17.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.17.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.17.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.17.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.17.2.jar.sha1
  libs/core/licenses/jackson-core-2.17.1.jar.sha1
  libs/core/licenses/jackson-core-2.17.2.jar.sha1
  libs/x-content/licenses/jackson-core-2.17.1.jar.sha1
  libs/x-content/licenses/jackson-core-2.17.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.17.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.17.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.17.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.17.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.17.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.17.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.17.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.17.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.17.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.17.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.17.1.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.17.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.17.1.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.17.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.17.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.17.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.17.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.17.2.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.17.1.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.17.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.17.1.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.17.2.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.17.1.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.17.2.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.17.1.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.17.2.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.17.1.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.17.2.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.17.1.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.17.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.17.1.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.17.2.jar.sha1
  server/licenses/jackson-core-2.17.1.jar.sha1
  server/licenses/jackson-core-2.17.2.jar.sha1
  server/licenses/jackson-dataformat-cbor-2.17.1.jar.sha1
  server/licenses/jackson-dataformat-cbor-2.17.2.jar.sha1
  server/licenses/jackson-dataformat-smile-2.17.1.jar.sha1
  server/licenses/jackson-dataformat-smile-2.17.2.jar.sha1
  server/licenses/jackson-dataformat-yaml-2.17.1.jar.sha1
  server/licenses/jackson-dataformat-yaml-2.17.2.jar.sha1
Labels: dependencies, backport 2.x

#14699 Add release notes for release 1.3.18
  release-notes/opensearch.release-notes-1.3.18.md
Labels: backport 2.x, skip-changelog

#14697 Bump reactor from 3.5.19 to 3.5.20
  CHANGELOG.md
  buildSrc/version.properties
  plugins/repository-azure/licenses/reactor-netty-core-1.1.20.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.21.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.20.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.21.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.20.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.21.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.20.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.21.jar.sha1
  server/licenses/reactor-core-3.5.18.jar.sha1
  server/licenses/reactor-core-3.5.19.jar.sha1
Labels: dependencies, backport 2.x

#14476 Add unit tests for read flow of RemoteClusterStateService and bug fix for transient settings
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateTestUtils.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
  test/framework/src/main/java/org/opensearch/test/TestClusterStateCustom.java
Labels: skip-changelog

#14703 Update version check for the bug fix of match_phrase_prefix_query not working on multiple values and index_prefixes
  rest-api-spec/src/main/resources/rest-api-spec/test/search/190_index_prefix_search.yml
Labels: skip-changelog

#14696 Remove unnecessary cast to int from test
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
Labels: bug, skip-changelog, Storage:Remote

#14604 print reason why parent task was cancelled
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/node/tasks/CancellableTasksIT.java
  server/src/main/java/org/opensearch/tasks/TaskCancellationService.java
  server/src/main/java/org/opensearch/tasks/TaskManager.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/CancellableTasksTests.java
Labels: enhancement, backport 2.x, Cluster Manager, Other

#14533 Use set for shard routings in batch check.
  server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
Labels: skip-changelog

#14677 Add versioning for UploadedIndexMetadata
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: backport 2.x, skip-changelog

#14574 Update to Gradle 8.9
  buildSrc/src/main/java/org/opensearch/gradle/test/rest/RestResourcesPlugin.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: backport 2.x, skip-changelog, Build

#14732 Fix hdfs-fixture hadoop-minicluster dependencies are not being updated / false positive reports on CVEs
  test/fixtures/hdfs-fixture/build.gradle
Labels: bug, :test, backport 2.x, skip-changelog, Storage, Storage:Snapshots, Build

#14555 The dynamic mapping parameter supports strict_allow_templates
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/110_strict_allow_templates.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.put_mapping/all_path_options.yml
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/StrictDynamicMappingException.java
  server/src/test/java/org/opensearch/index/mapper/CopyToMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
Labels: enhancement, v3.0.0, backport 2.x, v2.16.0

#14743 remove query insights plugin from core
  plugins/query-insights/build.gradle
  plugins/query-insights/src/internalClusterTest/java/org/opensearch/plugin/insights/QueryInsightsPluginTransportIT.java
  plugins/query-insights/src/javaRestTest/java/org/opensearch/plugin/insights/TopQueriesRestIT.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/QueryInsightsPlugin.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/DebugExporter.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/LocalIndexExporter.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporter.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporterFactory.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/SinkType.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/exporter/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/QueryInsightsService.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/TopQueriesService.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/service/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueries.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesAction.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesRequest.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesResponse.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/action/top_queries/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/Attribute.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/MetricType.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecord.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/model/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/RestTopQueriesAction.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesAction.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/rules/transport/top_queries/package-info.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/QueryInsightsSettings.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/settings/package-info.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsTestUtils.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/exporter/DebugExporterTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/exporter/LocalIndexExporterTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/exporter/QueryInsightsExporterFactoryTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListenerTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/QueryInsightsServiceTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/service/TopQueriesServiceTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesRequestTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesResponseTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/action/top_queries/TopQueriesTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/model/SearchQueryRecordTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/resthandler/top_queries/RestTopQueriesActionTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesActionTests.java
Labels: backport 2.x, skip-changelog

#14742 [Forwardport] Add `strict_allow_templates` dynamic mapping option (#14555) (#14737)
  rest-api-spec/src/main/resources/rest-api-spec/test/index/110_strict_allow_templates.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.put_mapping/all_path_options.yml
Labels: skip-changelog

#14759 Remove query categorization from core
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchQueryAggregationCategorizer.java
  server/src/main/java/org/opensearch/action/search/SearchQueryCategorizer.java
  server/src/main/java/org/opensearch/action/search/SearchQueryCategorizingVisitor.java
  server/src/main/java/org/opensearch/action/search/SearchQueryCounters.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/query/QueryShapeVisitor.java
  server/src/test/java/org/opensearch/action/search/SearchQueryCategorizerTests.java
  server/src/test/java/org/opensearch/index/query/QueryShapeVisitorTests.java
Labels: backport, backport 2.x

#14614 Add changes to propagate queryGroupId across child requests and nodes
  CHANGELOG.md
  server/src/main/java/org/opensearch/wlm/QueryGroupThreadContextStatePropagator.java
  server/src/main/java/org/opensearch/wlm/package-info.java
  server/src/test/java/org/opensearch/wlm/QueryGroupThreadContextStatePropagatorTests.java
Labels: backport 2.x

#14764 [Remote Store] Add consumer for Remote Store based index settings
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: bug, backport 2.x, skip-changelog, Storage:Remote

#14750 Add matchesPluginSystemIndexPattern to SystemIndexRegistry
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/SystemIndexRegistry.java
  server/src/main/java/org/opensearch/indices/SystemIndices.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/indices/SystemIndicesTests.java
Labels: backport 2.x

#14659 SPI for loading ABC templates
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/applicationtemplates/ClusterStateSystemTemplateLoader.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplate.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplateLoader.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplateRepository.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesPlugin.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesService.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/TemplateRepositoryMetadata.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/package-info.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/applicationtemplates/ClusterStateSystemTemplateLoaderTests.java
  server/src/test/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesServiceTests.java
  test/framework/src/main/java/org/opensearch/cluster/service/applicationtemplates/TestSystemTemplatesRepositoryPlugin.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
Labels: enhancement, backport, RFC, Indexing:Performance, v2.16.0

#14787 [ClusterStateSystemTemplateLoaderTests] Fix flaky test due to node being used across all tests
  server/src/test/java/org/opensearch/cluster/applicationtemplates/ClusterStateSystemTemplateLoaderTests.java
Labels: flaky-test, skip-changelog, Indexing:Performance

#14798 [Forwardport] [2.x] Added bwc version 1.3.19
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#14796 Add Gao Binlong as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#14738 Clear ehcache disk cache files during initialization
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
Labels: backport 2.x, skip-changelog

#14668 Refactor remote-routing-table service inline with remote state interfaces
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactory.java
  server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableBlobEntity.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteRoutingTableBlobStore.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/IndexRoutingTableHeader.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTable.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactoryTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteRoutingTableBlobStoreTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/IndexRoutingTableHeaderTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTableTests.java
Labels: enhancement, backport 2.x, ShardManagement:Routing

#14819 Set version to 2.15 for determining metadata during migration to remote store
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
Labels: backport 2.x, skip-changelog

#14793 [Forwardport] Fix bulk upsert ignores the default_pipeline and final_pipeline when the auto-created index matches the index template
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
Labels: skip-changelog

#14769 [Forwardport] [main] Fix create or update alias API doesn't throw exception for unsupported parameters
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.put_alias/10_basic.yml
Labels: skip-changelog

#14802 Added bwc version 1.3.19
  .ci/bwcVersions
  server/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#14814 Change RCSS info logs to debug
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
Labels: skip-changelog

#14385 [Bugfix] Fix NPE in ReplicaShardAllocator (#13993)
  CHANGELOG.md
  server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
Labels: bug, good first issue, backport 2.x, Cluster Manager

#14760 Run performance benchmark on pull requests
  .github/benchmark-configs.json
  .github/workflows/add-performance-comment.yml
  .github/workflows/benchmark-pull-request.yml
  PERFORMANCE_BENCHMARKS.md
Labels: skip-changelog

#14807 fix constant_keyword field type
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/110_constant_keyword.yml
  server/src/main/java/org/opensearch/index/mapper/ConstantKeywordFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldMapperTests.java
Labels: bug, backport 2.x, Indexing

#14792 [Remote Store Migration] Reconcile remote store based index settings during STRICT mode switch
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
Labels: bug, skip-changelog, Storage:Remote

#14790 Add prefix mode verification setting for repository verification
  CHANGELOG.md
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, skip-changelog, Storage:Performance, v2.16.0

#14842 Add restore-from-snapshot test procedure for snapshot run benchmark config
  .github/benchmark-configs.json
Labels: skip-changelog

#14843 Fix env variable name typo in benchmark workflow.
  .github/workflows/benchmark-pull-request.yml
Labels: skip-changelog

#14754 Use circuit breaker in InternalHistogram when adding empty buckets
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/InternalHistogram.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/InternalHistogramTests.java
Labels: bug, enhancement, Search:Aggregations, backport 2.x

#14671 [Remote State] Create interface RemoteEntitiesManager
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableEntityManager.java
  server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/common/remote/AbstractRemoteWritableEntityManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteIndexMetadataManagerTests.java
Labels: enhancement, skip-changelog, Cluster Manager, ClusterManager:RemoteState

#14839 [Backport 2.x] Add prefix mode verification setting for repository verification
  CHANGELOG.md
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#14749 Optimise TransportNodesAction to not send DiscoveryNodes for NodeStat…
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/TransportNodesInfoAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesInfoAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/test/java/org/opensearch/action/RestStatsActionTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesActionTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesInfoActionTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesStatsActionTests.java
Labels: bug, backport 2.x, Cluster Manager, v2.16.0

#14854 [Backport 2.x] Create interface RemoteEntitiesManager
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableEntityManager.java
  server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/common/remote/AbstractRemoteWritableEntityManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteIndexMetadataManagerTests.java
Labels: skip-changelog

#14273 Enabling term version check on local state for all ClusterManager Read Transport Actions
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/IndicesRequestIT.java
  server/src/internalClusterTest/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionForClusterManagerIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/decommission/awareness/get/TransportGetDecommissionStateAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/repositories/get/TransportGetRepositoriesAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/TransportClusterSearchShardsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/get/TransportGetWeightedRoutingAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/storedscripts/TransportGetStoredScriptAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/tasks/TransportPendingClusterTasksAction.java
  server/src/main/java/org/opensearch/action/admin/indices/alias/get/TransportGetAliasesAction.java
  server/src/main/java/org/opensearch/action/admin/indices/exists/indices/TransportIndicesExistsAction.java
  server/src/main/java/org/opensearch/action/admin/indices/shards/TransportIndicesShardStoresAction.java
  server/src/main/java/org/opensearch/action/admin/indices/template/get/TransportGetComponentTemplateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/template/get/TransportGetComposableIndexTemplateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/template/get/TransportGetIndexTemplatesAction.java
  server/src/main/java/org/opensearch/action/ingest/GetPipelineTransportAction.java
  server/src/main/java/org/opensearch/action/search/GetSearchPipelineTransportAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeReadAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/info/TransportClusterInfoAction.java
  server/src/test/java/org/opensearch/action/admin/indices/mapping/get/GetMappingsActionTests.java
Labels: backport 2.x

#14795 Reduce logging in DEBUG for MasterService:run
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/cluster/service/TaskBatcher.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/TaskBatcherTests.java
Labels: backport 2.x, v2.16.0

#14800 Add SplitResponseProcessor to Search Pipelines
  CHANGELOG.md
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SplitResponseProcessor.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SplitResponseProcessorTests.java
Labels: backport 2.x, v2.16.0

#14631 [Remote Routing Table] Add integration tests for Remote Routing Table
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/main/java/org/opensearch/cluster/coordination/PersistedStateStats.java
  server/src/test/java/org/opensearch/cluster/coordination/PersistedStateStatsTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, skip-changelog, ShardManagement:Resiliency

#14785 Add SortResponseProcessor to Search Pipelines
  CHANGELOG.md
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SortResponseProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SplitResponseProcessor.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SortResponseProcessorTests.java
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/80_sort_response.yml
Labels: backport 2.x, v2.16.0

#14862 [Backport 2.x] Refactor remote routing table service to implement remote objects
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactory.java
  server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableBlobEntity.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateBlobStore.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteRoutingTableBlobStore.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/IndexRoutingTableHeader.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTable.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactoryTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteRoutingTableBlobStoreTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/IndexRoutingTableHeaderTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTableTests.java
Labels: backport 2.16

#14868 [Backport 2.x] Add SortResponseProcessor to Search Pipelines (#14785)
  CHANGELOG.md
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SortResponseProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SplitResponseProcessor.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SortResponseProcessorTests.java
  modules/search-pipeline-common/src/yamlRestTest/resources/rest-api-spec/test/search_pipeline/80_sort_response.yml
Labels: backport 2.16

#13957 Fix allowUnmappedFields, mapUnmappedFieldAsString settings to be applied when parsing query string query
  CHANGELOG.md
  modules/percolator/src/yamlRestTest/resources/rest-api-spec/test/10_basic.yml
  server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java
  server/src/main/java/org/opensearch/index/search/QueryParserHelper.java
Labels: bug, backport 2.x, Search, Indexing

#14864 [Backport 2.x] Reduce logging in DEBUG for MasterService:run
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/cluster/service/TaskBatcher.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/TaskBatcherTests.java
Labels: backport 2.16

#14847 Use Lucene provided Persian stem
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisModulePlugin.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/PersianStemTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/CommonAnalysisFactoryTests.java
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/40_token_filters.yml
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: enhancement, backport 2.x, Search

#14725 Change default batch size of bulk API to Integer.MAX_VALUE
  CHANGELOG.md
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
  server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java
  server/src/main/java/org/opensearch/action/bulk/BulkRequest.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/rest/action/document/RestBulkAction.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
Labels: backport 2.x, backport 2.16

#14411 Add perms for remote snapshot cache eviction on scripted query
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
Labels: bug, backport 2.x, Search:Searchable Snapshots, backport 2.16

#13980 Add rest, transport layer changes for Tiering
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringAction.java
  server/src/main/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/tiering/RestWarmTieringAction.java
  server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringValidationResult.java
  server/src/main/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringAction.java
  server/src/main/java/org/opensearch/action/admin/indices/tiering/package-info.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/indices/tiering/TieringRequestValidator.java
  server/src/main/java/org/opensearch/indices/tiering/package-info.java
  server/src/test/java/org/opensearch/action/admin/indices/tiering/HotToWarmTieringResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/tiering/TieringIndexRequestTests.java
  server/src/test/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringActionTests.java
  server/src/test/java/org/opensearch/indices/tiering/TieringRequestValidatorTests.java
Labels: backport 2.x, v2.16.0

#14832 Create listener to refresh search thread resource usage
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchTaskRequestOperationsListener.java
  server/src/main/java/org/opensearch/node/Node.java
Labels: backlog, v3.0.0, backport 2.x, v2.16.0, backport 2.16

#14851 Caching avg total bytes and avg free bytes inside ClusterInfo
  server/src/main/java/org/opensearch/cluster/ClusterInfo.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
Labels: backport 2.x, skip-changelog

#14874 [Backport 2.x] Removing String format in RemoteStoreMigrationAllocationDecider
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/RemoteStoreMigrationAllocationDecider.java
Labels: skip-changelog

#14812 Use default value when index.number_of_replicas is null
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/CreateIndexIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: bug, backport 2.x, Indexing, backport 2.16

#14899 [Backport 2.16] Caching avg total bytes and avg free bytes inside ClusterInfo
  server/src/main/java/org/opensearch/cluster/ClusterInfo.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
Labels: skip-changelog

#14684 [Remote Routing Table] Implement write and read flow for shard diff file.
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTableIncrementalDiff.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteRoutingTableDiff.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/ClusterStateDiffManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTableDiffTests.java
Labels: backport 2.x

#14426 Optimized ClusterStatsIndices to precomute shard stats
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIndices.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodeResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsAction.java
  server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodesTests.java
Labels: bug, backport 2.x, Cluster Manager, v2.16.0

#14908 Fix constraint bug which allows more primary shards than average primary shards per index
  server/src/main/java/org/opensearch/cluster/routing/allocation/ConstraintTypes.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
Labels: backport 2.x, skip-changelog

#14761 Optimising hashmap.get call inside AwarenessAllocationDecider
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java
Labels: skip-changelog

#14904 [Backport 2.x] Add integration tests for RemoteRoutingTable Service. (#14631)
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/main/java/org/opensearch/cluster/coordination/PersistedStateStats.java
  server/src/test/java/org/opensearch/cluster/coordination/PersistedStateStatsTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#14905 [Backport 2.16] Add integration tests for RemoteRoutingTable Service. (#14631)
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/main/java/org/opensearch/cluster/coordination/PersistedStateStats.java
  server/src/test/java/org/opensearch/cluster/coordination/PersistedStateStatsTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#14918 Fix IngestServiceTests.testBulkRequestExecutionWithFailures
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
Labels: backport 2.x, skip-changelog, v2.16.0, backport 2.16

#14915 [Backport 2.x] Implement write and read flow for shard diff file.
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTableIncrementalDiff.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateUtils.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteRoutingTableDiff.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/ClusterStateDiffManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTableDiffTests.java
Labels: backport 2.16

#14894 [Backport 2.x] Use Lucene provided Persian stem
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisPlugin.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/PersianStemTokenFilterFactory.java
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/StemmerTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/CommonAnalysisFactoryTests.java
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/analysis-common/40_token_filters.yml
  test/framework/src/main/java/org/opensearch/indices/analysis/AnalysisFactoryTestCase.java
Labels: v2.16.0, backport 2.16

#14652 [Star tree] Star tree merge changes
  server/src/main/java/org/opensearch/index/codec/composite/Composite99DocValuesReader.java
  server/src/main/java/org/opensearch/index/codec/composite/Composite99DocValuesWriter.java
  server/src/main/java/org/opensearch/index/codec/composite/CompositeIndexFieldInfo.java
  server/src/main/java/org/opensearch/index/codec/composite/CompositeIndexReader.java
  server/src/main/java/org/opensearch/index/codec/composite/datacube/startree/StarTreeValues.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MetricAggregatorInfo.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregatorFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeDocValuesIteratorAdapter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreesBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/SequentialDocValuesIterator.java
  server/src/main/java/org/opensearch/index/mapper/CompositeMappedFieldType.java
  server/src/test/java/org/opensearch/index/codec/composite/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MetricAggregatorInfoTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregatorFactoryTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeDocValuesIteratorAdapterTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeValuesIteratorFactoryTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreesBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/SequentialDocValuesIteratorTests.java
  test/framework/src/main/java/org/opensearch/index/MapperTestUtils.java
Labels: enhancement, skip-changelog, Indexing:Performance, v2.16.0

#14888 Create new IndexInput for multi part upload
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumBlobStoreFormat.java
  server/src/main/java/org/opensearch/repositories/blobstore/ConfigBlobStoreFormat.java
  server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
Labels: skip-changelog

#14914 Updating Cluster Stats Optimisation Versions to 2.16
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodeResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java
Labels: skip-changelog, v2.16.0

#14938 Fix read/write in stream method for Diff Manifest when shard diff file is null
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
Labels: backport 2.x, skip-changelog

#14947 [Backport 2.x] Fix read/write in stream method for Diff Manifest when shard diff file is null
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
Labels: skip-changelog

#14848 Make reroute iteration time-bound for large shard allocations
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/ExistingShardsAllocator.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/util/BatchRunnableExecutor.java
  server/src/main/java/org/opensearch/common/util/concurrent/TimeoutAwareRunnable.java
  server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/ExistingShardsAllocatorTests.java
  server/src/test/java/org/opensearch/common/util/BatchRunnableExecutorTests.java
  server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Labels: backport 2.x, skip-changelog

#14935 Fix the documentation url of the Create or Update alias API in rest-api-spec
  rest-api-spec/src/main/resources/rest-api-spec/api/indices.put_alias.json
Labels: :test, backport 2.x, skip-changelog

#14811 Template creation using context
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/template/post/TransportSimulateIndexTemplateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/template/post/TransportSimulateTemplateAction.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesService.java
  server/src/main/java/org/opensearch/cluster/applicationtemplates/TemplateRepositoryMetadata.java
  server/src/main/java/org/opensearch/cluster/coordination/OpenSearchNodeCommand.java
  server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java
  server/src/main/java/org/opensearch/cluster/metadata/Context.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/test/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
Labels: enhancement, discuss, feature, RFC, skip-changelog, Indexing, Roadmap:Ease of Use, v2.16.0

#14958 Add changelog for remote state multi part upload fix
  CHANGELOG.md
Labels: backport 2.x, backport 2.16

#14739 [BUG FIX] Fix the visit of inner query for NestedQueryBuilder
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
Labels: backport 2.x, v2.16.0, backport 2.16

#14968 [Backport 2.16] [BUG FIX] Fix the visit of inner query for NestedQueryBuilder
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
Labels: skip-changelog

#14971 Update release notes for 2.16
  release-notes/opensearch.release-notes-2.16.0.md
Labels: skip-changelog

#14975 Forward port 2.16 release notes
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.16.0.md
Labels: backport 2.x

#14969 [Backport 2.16] fix constant_keyword field type (#14807)
  release-notes/opensearch.release-notes-2.16.0.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/110_constant_keyword.yml
  server/src/main/java/org/opensearch/index/mapper/ConstantKeywordFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldMapperTests.java
Labels: skip-changelog, v2.16.0

#14985 Fix version check after backport
  server/src/main/java/org/opensearch/cluster/metadata/ComposableIndexTemplate.java
Labels: skip-changelog

#14972 [Batch Fetch] Fix for hasInitiatedFetching to fix allocation explain and manual reroute APIs
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/main/java/org/opensearch/gateway/AsyncShardBatchFetch.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
Labels: bug, backport 2.x, Cluster Manager

#14962 Cache index shard limit to optimise ShardLimitsAllocationDecider
  benchmarks/src/main/java/org/opensearch/benchmark/routing/allocation/RerouteBenchmark.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
Labels: skip-changelog

#14998 OpenJDK Update (July 2024 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: backport 2.x, Build

#14618 [Derived Fields] Add aggregation support for derived fields
  CHANGELOG.md
  modules/lang-painless/build.gradle
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/60_derived_field_aggs.yml
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/ObjectDerivedFieldType.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSourceConfig.java
  server/src/main/java/org/opensearch/search/aggregations/support/values/ScriptBytesValues.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldTypeTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/DerivedFieldAggregationTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/ValuesSourceConfigTests.java
Labels: backport 2.x, Search:Query Capabilities, v2.17.0

#9392 Remove mmap.extensions setting
  CHANGELOG-3.0.md
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/store/FsDirectoryFactory.java
  server/src/test/java/org/opensearch/index/store/FsDirectoryFactoryTests.java
Labels: bug, distributed framework, v3.0.0

#15015 Fix derived field tests for percentile ranks.
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/derived_fields/60_derived_field_aggs.yml
Labels: skip-changelog

#15001 [Backport] [2.x] OpenJDK Update (July 2024 Patch releases) (#14998)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: Build

#15002 OpenJDK Update (July 2024 Patch releases)
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: Build

#15019 Fix version check in yml test for the bug fix of constant_keyword field type not working
  rest-api-spec/src/main/resources/rest-api-spec/test/index/110_constant_keyword.yml
Labels: backport 2.x, skip-changelog

#14963 Fix missing value of FieldSort for unsigned_long
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/UnsignedLongValuesComparatorSource.java
Labels: bug, v3.0.0, backport 2.x, v2.17.0

#14979 Add lower limit for primary and replica batch allocators timeout
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
Labels: bug, backport 2.x, Cluster Manager, Other

#15011 Fix test RestStatusTests.testStatusReturnsFailureStatusWhenFailuresExist
  server/src/test/java/org/opensearch/core/RestStatusTests.java
Labels: bug, :test, >test-failure, backport 2.x, skip-changelog

#14708 Add queryGroupId to search workload tasks at co-ordinator and data node level
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchShardTask.java
  server/src/main/java/org/opensearch/action/search/SearchTask.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/wlm/QueryGroupTask.java
  server/src/main/java/org/opensearch/wlm/WorkloadManagementTransportInterceptor.java
  server/src/test/java/org/opensearch/wlm/QueryGroupTaskTests.java
  server/src/test/java/org/opensearch/wlm/WorkloadManagementTransportInterceptorTests.java
  server/src/test/java/org/opensearch/wlm/WorkloadManagementTransportRequestHandlerTests.java
Labels: backport 2.x

#14991 Add setting to ignore throttling nodes for allocation of unassigned …
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/BalancedSingleShardTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/DecideAllocateUnassignedTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
  test/framework/src/main/java/org/opensearch/cluster/routing/TestShardRouting.java
Labels: backport 2.x

#15038 [Backport 2.x] Add ThreadContextPermission for markAsSystemContext and allow core to perform the method
  CHANGELOG.md
  libs/secure-sm/src/main/java/org/opensearch/secure_sm/ThreadContextPermission.java
  server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContextAccess.java
  server/src/main/java/org/opensearch/index/seqno/GlobalCheckpointSyncAction.java
  server/src/main/java/org/opensearch/index/seqno/RetentionLeaseBackgroundSyncAction.java
  server/src/main/java/org/opensearch/index/seqno/RetentionLeaseSyncAction.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
  server/src/main/java/org/opensearch/transport/RemoteClusterConnection.java
  server/src/main/java/org/opensearch/transport/SniffConnectionStrategy.java
  server/src/main/resources/org/opensearch/bootstrap/security.policy
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
  server/src/test/java/org/opensearch/cluster/metadata/TemplateUpgradeServiceTests.java
  server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
  server/src/test/java/org/opensearch/telemetry/tracing/ThreadContextBasedTracerContextStorageTests.java
  server/src/test/resources/org/opensearch/bootstrap/test.policy
  test/framework/src/main/java/org/opensearch/cluster/service/FakeThreadPoolClusterManagerService.java
Labels: v2.17.0

#15036 Fix MacOS Mx (arm64) and Linux (arm64, ppc64le, s390x) checks
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java
Labels: bug, backport 1.x, backport 2.x, backport 1.3, skip-changelog, Build, backport 2.16

#14437 [Streaming Indexing] Enhance RestClient with a new streaming API support
  CHANGELOG.md
  buildSrc/version.properties
  client/rest/build.gradle
  client/rest/licenses/httpclient5-5.2.1.jar.sha1
  client/rest/licenses/httpclient5-5.2.3.jar.sha1
  client/rest/licenses/httpcore5-5.2.2.jar.sha1
  client/rest/licenses/httpcore5-5.2.5.jar.sha1
  client/rest/licenses/httpcore5-h2-5.2.2.jar.sha1
  client/rest/licenses/httpcore5-h2-5.2.5.jar.sha1
  client/rest/licenses/httpcore5-reactive-5.2.5.jar.sha1
  client/rest/licenses/httpcore5-reactive-LICENSE.txt
  client/rest/licenses/httpcore5-reactive-NOTICE.txt
  client/rest/licenses/reactive-streams-1.0.4.jar.sha1
  client/rest/licenses/reactive-streams-LICENSE.txt
  client/rest/licenses/reactive-streams-NOTICE.txt
  client/rest/licenses/reactor-core-3.5.19.jar.sha1
  client/rest/licenses/reactor-core-LICENSE.txt
  client/rest/licenses/reactor-core-NOTICE.txt
  client/rest/src/main/java/org/opensearch/client/Cancellable.java
  client/rest/src/main/java/org/opensearch/client/Response.java
  client/rest/src/main/java/org/opensearch/client/ResponseWarningsExtractor.java
  client/rest/src/main/java/org/opensearch/client/RestClient.java
  client/rest/src/main/java/org/opensearch/client/StreamingRequest.java
  client/rest/src/main/java/org/opensearch/client/StreamingResponse.java
  client/rest/src/main/java/org/opensearch/client/http/ReactiveHttpUriRequestProducer.java
  client/rest/src/test/java/org/opensearch/client/RestClientTests.java
  client/sniffer/licenses/httpclient5-5.2.1.jar.sha1
  client/sniffer/licenses/httpclient5-5.2.3.jar.sha1
  client/sniffer/licenses/httpcore5-5.2.2.jar.sha1
  client/sniffer/licenses/httpcore5-5.2.5.jar.sha1
  plugins/transport-reactor-netty4/build.gradle
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4BadRequestIT.java
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4HeadBodyIsEmptyIT.java
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingIT.java
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransport.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4NonStreamingHttpChannel.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingHttpChannel.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingRequestConsumer.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingResponseProducer.java
  qa/smoke-test-http/build.gradle
  qa/smoke-test-http/src/test/java/org/opensearch/http/HttpSmokeTestCase.java
  qa/smoke-test-http/src/test/java/org/opensearch/http/IdentityAuthenticationIT.java
  qa/wildfly/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
  server/src/main/java/org/opensearch/rest/RestController.java
  server/src/main/java/org/opensearch/rest/action/document/RestBulkStreamingAction.java
Labels: enhancement, Build Libraries & Interfaces, v3.0.0, backport 2.x, v2.17.0

#14992 Caching total number of primary shards per node for evaluating constraints on avg primary shards across all indices per node
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
Labels: backport 2.x, skip-changelog

#15039 Add ThreadContextPermission for stashAndMergeHeaders and stashWithOrigin
  CHANGELOG.md
  server/src/main/java/org/opensearch/client/OriginSettingClient.java
  server/src/main/java/org/opensearch/client/support/AbstractClient.java
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
  server/src/main/resources/org/opensearch/bootstrap/security.policy
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
  server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
Labels: v3.0.0, backport 2.x, v2.17.0

#15049 [Backport 2.x] Add ThreadContextPermission for stashAndMergeHeaders and stashWithOrigin
  CHANGELOG.md
  server/src/main/java/org/opensearch/client/OriginSettingClient.java
  server/src/main/java/org/opensearch/client/support/AbstractClient.java
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
  server/src/main/resources/org/opensearch/bootstrap/security.policy
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
  server/src/test/java/org/opensearch/common/util/concurrent/ThreadContextTests.java
Labels: v2.17.0
