Repository opensearch-project/OpenSearch, pull requests merged in 2024-05, with the labels that each got.

#13477 Skip running gradle checks on release notes
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#13485 [Backport 2.14] [Bugfix] Fix flaky test CacheStatsAPIIndicesRequestCacheIT.testNullLevels()
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
  server/src/main/java/org/opensearch/common/cache/ICache.java
  server/src/main/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolder.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/common/cache/stats/ImmutableCacheStatsHolderTests.java
  server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: skip-changelog

#13486 Revert "Removing unused fetch sub phase processor initialization during fetch… (#12503)"
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/400_inner_hits.yml
  server/src/main/java/org/opensearch/search/fetch/FetchContext.java
  server/src/main/java/org/opensearch/search/fetch/subphase/InnerHitsContext.java
  server/src/main/java/org/opensearch/search/fetch/subphase/InnerHitsPhase.java
  server/src/main/java/org/opensearch/search/fetch/subphase/ScriptFieldsPhase.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/search/fetch/subphase/InnerHitsPhaseTests.java
  server/src/test/java/org/opensearch/search/fetch/subphase/ScriptFieldsPhaseTests.java
Labels: bug, Severity-Critical, Search:Aggregations, v3.0.0, backport 2.x, v2.14.0, backport 2.14

#13499 Revert "Skip running gradle checks on release notes"
  .github/workflows/gradle-check.yml
Labels: skip-changelog, Build, Other

#13322 Handle shard allocation for NONE migration direction
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationAllocationDeciderIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationShardAllocationBaseTestCase.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/RemoteStoreMigrationAllocationDecider.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteStoreMigrationAllocationDeciderTests.java
Labels: enhancement, Storage:Durability, skip-changelog, Storage:Remote

#13495 Bump 2.x to 2.15.0
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#13506 [Forwardport] [main] Bump 2.x to 2.15.0 (#13495)
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#13510 Fix org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/400_inner_hits/Include inner hits in top hits}
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/400_inner_hits.yml
Labels: skip-changelog

#13481 Refactor implementations of query phase searcher, add empty QueryCollectorContext
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/query/ConcurrentQueryPhaseSearcher.java
  server/src/main/java/org/opensearch/search/query/QueryCollectorContext.java
  server/src/main/java/org/opensearch/search/query/QueryPhase.java
  server/src/main/java/org/opensearch/search/query/RescoringQueryCollectorContext.java
  server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
Labels: backport 2.x

#13463 Increase cluster publish timeout in flaky test testStaleClusterManage…
  server/src/internalClusterTest/java/org/opensearch/discovery/StableClusterManagerDisruptionIT.java
Labels: bug, flaky-test, skip-changelog, Cluster Manager

#11650 Allow doc value search on unindexed boolean and date fields
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml
  server/src/main/java/org/opensearch/index/mapper/BooleanFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/BooleanFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/BooleanFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/TermsQueryBuilderTests.java
Labels: enhancement, backport 2.x, Search:Performance, v2.14.0

#12295 Add support for deep copying SearchRequest
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
Labels: enhancement, good first issue, Indexing & Search, backport 2.x, Search

#13517 Update TermsQueryBuilderTests to include TermQuery
  server/src/test/java/org/opensearch/index/query/TermsQueryBuilderTests.java
Labels: bug, backport 2.x, skip-changelog, Search, Build

#13236 [Tiered Caching] Stats rework (4/4): Adds stats implementation for TieredSpilloverCache
  CHANGELOG.md
  modules/cache-common/src/internalClusterTest/java/org.opensearch.cache.common.tier/TieredSpilloverCacheIT.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsHolder.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  server/src/main/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolder.java
  server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java
  server/src/main/java/org/opensearch/common/cache/store/builders/ICacheBuilder.java
  server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
  server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java
Labels: backport 2.x

#13317 Support multi ranges traversal when doing date histogram rewrite optimization
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/10_histogram.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/330_auto_date_histogram.yml
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: bug, Search:Aggregations, backport 2.x, Performance, v2.14.0

#8922 Support wildcard/regex for indices param in _remotestore/_restore
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/main/java/org/opensearch/common/util/IndexUtils.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotUtils.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/snapshots/SnapshotUtilsTests.java
Labels: bug, enhancement, backport 2.x, Storage, v2.15.0

#13508 [Flaky test] Clear transient cluster setting at the end of the test
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteCloneIndexIT.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: flaky-test, skip-changelog

#13478 FEATURE-13448: add use compound file setting
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: enhancement, backport 2.x, Indexing

#13505 Update Cluster Manager Node Timeout to 3mins for flaky test o.o.c.ClusterHealthIT.testHealthOnClusterManagerFailover
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterHealthIT.java
Labels: bug, flaky-test, skip-changelog, Cluster Manager

#13522 [Backport 2.x] Support multi ranges traversal when doing date histogram rewrite optimization (#13317)
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/10_histogram.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/330_auto_date_histogram.yml
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: backport 2.14

#13532 DATETIME_FORMATTER_CACHING_SETTING experimental feature should not default to 'true'
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldTypeTests.java
Labels: bug, v3.0.0, backport 2.x, Indexing, v2.14.0, backport 2.14

#13469 Update version for batch shard allocation to 2.14
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
Labels: skip-changelog

#13553 Fix negative requestStats memory_size issue
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/index/cache/request/ShardRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/indices/IRCKeyWriteableSerializerTests.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: bug, backport 2.x, Search:Performance, v2.14.0

#13408 Update supported version for the bug fix of from and size parameter can be negative when searching
  rest-api-spec/src/main/resources/rest-api-spec/test/search/360_from_and_size.yml
Labels: skip-changelog

#13583 Create 2.14 release notes
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.14.0.md
Labels: v2.14.0

#13589 Forward port 2.14 release notes to main
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.14.0.md
Labels: backport 2.x, skip-changelog

#13591 [Backport 2.14] Fix negative requestStats memory_size issue (#13553)
  release-notes/opensearch.release-notes-2.14.0.md
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/index/cache/request/ShardRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/indices/IRCKeyWriteableSerializerTests.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: skip-changelog

#13597 Fix IndicesRequestCache clean up logic
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/indices/IRCKeyWriteableSerializerTests.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: backport 2.x, skip-changelog, backport 2.14

#13617 [Backport 2.x] Removing extra protobuf notice file
  protobuf-java-NOTICE.txt
Labels: skip-changelog

#13624 Fix get field mapping API returns 404 error in mixed cluster with multiple versions
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/mapping/get/GetFieldMappingsResponse.java
Labels: backport 2.x

#13621 Add TODO for Updating API Spec
  .github/pull_request_template.md
Labels: enhancement, community, Clients, skip-changelog

#13633 Updating security reachout email
  README.md
  SECURITY.md
Labels: backport 2.x, skip-changelog

#12159 [Remote Store] Permit backed futures to prevent timeouts during upload bursts
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/GenericStatsMetricPublisher.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3TransferRejectedException.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/SizeBasedBlockingQ.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/TransferSemaphoresHolder.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/SizeBasedBlockingQTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/TransferSemaphoresHolderTests.java
  server/src/main/java/org/opensearch/common/blobstore/BlobStore.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WritePriority.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: skip-changelog, Storage:Remote, Storage:Resiliency, v2.15.0

#13293 Abstracting outbound side of transport
  CHANGELOG.md
  server/src/main/java/org/opensearch/transport/InboundHandler.java
  server/src/main/java/org/opensearch/transport/NativeMessageHandler.java
  server/src/main/java/org/opensearch/transport/OutboundHandler.java
  server/src/main/java/org/opensearch/transport/ProtocolMessageHandler.java
  server/src/main/java/org/opensearch/transport/ProtocolOutboundHandler.java
  server/src/main/java/org/opensearch/transport/TcpTransport.java
  server/src/main/java/org/opensearch/transport/TcpTransportChannel.java
  server/src/main/java/org/opensearch/transport/TransportStatus.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/CompressibleBytesOutputStream.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/NativeOutboundHandler.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/NativeOutboundMessage.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/NetworkMessage.java
  server/src/test/java/org/opensearch/transport/InboundDecoderTests.java
  server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/InboundPipelineTests.java
  server/src/test/java/org/opensearch/transport/NativeOutboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/OutboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/TcpTransportTests.java
  server/src/test/java/org/opensearch/transport/TransportLoggerTests.java
  server/src/test/java/org/opensearch/transport/nativeprotocol/CompressibleBytesOutputStreamTests.java
  server/src/test/java/org/opensearch/transport/nativeprotocol/NativeInboundDecoderTests.java
  server/src/test/java/org/opensearch/transport/nativeprotocol/NativeInboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/nativeprotocol/NativeInboundPipelineTests.java
  server/src/test/java/org/opensearch/transport/nativeprotocol/NativeOutboundMessageTests.java
  server/src/test/java/org/opensearch/transport/nativeprotocol/NativeTransportLoggerTests.java
  test/framework/src/main/java/org/opensearch/transport/TestRequest.java
  test/framework/src/main/java/org/opensearch/transport/TestResponse.java
Labels: backport 2.x, v2.15.0

#13645 [Backport][Remote Store] Permit backed futures to prevent timeouts during uploa…
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/GenericStatsMetricPublisher.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3TransferRejectedException.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/SizeBasedBlockingQ.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/TransferSemaphoresHolder.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/SizeBasedBlockingQTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/TransferSemaphoresHolderTests.java
  server/src/main/java/org/opensearch/common/blobstore/BlobStore.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WritePriority.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: skip-changelog

#13646 Allow clearing `remote_store.compatibility_mode` setting
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationShardAllocationBaseTestCase.java
  server/src/main/java/org/opensearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
Labels: bug, good first issue, low hanging fruit, backport 2.x, Storage, Storage:Remote, v2.15.0

#12559 Main repository azure managed identity support
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/precommit/LicenseAnalyzer.java
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/accessors-smart-2.5.0.jar.sha1
  plugins/repository-azure/licenses/accessors-smart-LICENSE.txt
  plugins/repository-azure/licenses/accessors-smart-NOTICE.txt
  plugins/repository-azure/licenses/asm-9.7.jar.sha1
  plugins/repository-azure/licenses/asm-LICENSE.txt
  plugins/repository-azure/licenses/asm-NOTICE.txt
  plugins/repository-azure/licenses/azure-identity-1.11.4.jar.sha1
  plugins/repository-azure/licenses/content-type-2.3.jar.sha1
  plugins/repository-azure/licenses/content-type-LICENSE.txt
  plugins/repository-azure/licenses/content-type-NOTICE.txt
  plugins/repository-azure/licenses/jna-platform-5.13.0.jar.sha1
  plugins/repository-azure/licenses/jna-platform-LICENSE.txt
  plugins/repository-azure/licenses/jna-platform-NOTICE.txt
  plugins/repository-azure/licenses/json-smart-2.5.0.jar.sha1
  plugins/repository-azure/licenses/json-smart-LICENSE.txt
  plugins/repository-azure/licenses/json-smart-NOTICE.txt
  plugins/repository-azure/licenses/lang-tag-1.7.jar.sha1
  plugins/repository-azure/licenses/lang-tag-LICENSE.txt
  plugins/repository-azure/licenses/lang-tag-NOTICE.txt
  plugins/repository-azure/licenses/msal4j-1.14.3.jar.sha1
  plugins/repository-azure/licenses/msal4j-LICENSE.txt
  plugins/repository-azure/licenses/msal4j-NOTICE.txt
  plugins/repository-azure/licenses/msal4j-persistence-extension-1.2.0.jar.sha1
  plugins/repository-azure/licenses/msal4j-persistence-extension-LICENSE.txt
  plugins/repository-azure/licenses/msal4j-persistence-extension-NOTICE.txt
  plugins/repository-azure/licenses/nimbus-jose-jwt-9.37.3.jar.sha1
  plugins/repository-azure/licenses/nimbus-jose-jwt-LICENSE.txt
  plugins/repository-azure/licenses/nimbus-jose-jwt-NOTICE.txt
  plugins/repository-azure/licenses/oauth2-oidc-sdk-11.9.1.jar.sha1
  plugins/repository-azure/licenses/oauth2-oidc-sdk-LICENSE.txt
  plugins/repository-azure/licenses/oauth2-oidc-sdk-NOTICE.txt
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureBlobStore.java
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureRepositoryPlugin.java
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageService.java
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/AzureStorageSettings.java
  plugins/repository-azure/src/main/java/org/opensearch/repositories/azure/TokenCredentialType.java
  plugins/repository-azure/src/main/plugin-metadata/plugin-security.policy
  plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureStorageServiceTests.java
  server/src/main/resources/org/opensearch/bootstrap/security.policy
Labels: enhancement, Plugins, v3.0.0, backport 2.x, v2.15.0

#13663 Revert "[Backport][Remote Store] Permit backed futures to prevent timeouts during uploa…"
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/GenericStatsMetricPublisher.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3TransferRejectedException.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/SizeBasedBlockingQ.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/TransferSemaphoresHolder.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/SizeBasedBlockingQTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/TransferSemaphoresHolderTests.java
  server/src/main/java/org/opensearch/common/blobstore/BlobStore.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WritePriority.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: skip-changelog

#13684 Run breaking changes workflow against latest release only (so the unreleased changes won't be reported as breaking ones)
  .github/workflows/detect-breaking-change.yml
Labels: skip-changelog

#13665 Bump mockito from 5.11.0 to 5.12.0
  CHANGELOG.md
  buildSrc/version.properties
Labels: dependencies, backport 2.x

#13688 Update `github.actor` with `github.event.pull_request.user.login` for `dependabot[bot]` CI's
  .github/workflows/dependabot_pr.yml
  .github/workflows/pull-request-checks.yml
Labels: skip-changelog

#12190 Split the remote global metadata file to metadata attribute files
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/ClusterStateIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/TemplatesMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: enhancement, Storage:Durability, skip-changelog, Cluster Manager, Storage, Storage:Remote, v2.15.0, ClusterManager:RemoteState

#13681 Backport 12159 to 2.x
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/GenericStatsMetricPublisher.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3TransferRejectedException.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/SizeBasedBlockingQ.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/TransferSemaphoresHolder.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/SizeBasedBlockingQTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/TransferSemaphoresHolderTests.java
  server/src/main/java/org/opensearch/common/blobstore/BlobStore.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WritePriority.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
Labels: skip-changelog

#13707 Add missing BWC versions
  .ci/bwcVersions
Labels: skip-changelog

#13618 Enhance tika document parsing tests
  plugins/ingest-attachment/src/test/java/org/opensearch/ingest/attachment/TikaDocTests.java
  plugins/ingest-attachment/src/test/resources/org/opensearch/ingest/attachment/test/.checksums
Labels: backport 2.x, skip-changelog

#13658 Fix org.opensearch.rest.action.admin.cluster.RestNodesStatsActionTests.testIndexMetricsRequestWithoutIndicesMetric is flaky
  server/src/test/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsActionTests.java
Labels: skip-changelog

#13714 Add more identifiers to gradle-check job webhook payload
  .github/workflows/gradle-check.yml
Labels: bug, >test-failure, v3.0.0, backport 2.x, backport 2.1, backport 2.2, backport 2.3, skip-changelog, Build

#13636 Adds support to inject telemetry instances to plugins
  CHANGELOG.md
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/TelemetryAwarePlugin.java
  server/src/test/java/org/opensearch/node/NodeTests.java
Labels: enhancement, v3.0.0, backport 2.x, Other, Telemetry:Tracing, Telemetry:Metrics, v2.15.0

#13567 TermsAggregatorTests flaky test fix
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
Labels: bug, Search:Aggregations, flaky-test, backport 2.x, skip-changelog

#12333 Adds latency metrics for ClusterState Appliers and Listeners
  CHANGELOG.md
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/QueryInsightsPluginTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListenerTests.java
  plugins/query-insights/src/test/java/org/opensearch/plugin/insights/rules/transport/top_queries/TransportTopQueriesActionTests.java
  server/src/main/java/org/opensearch/cluster/ClusterManagerMetrics.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestSlowLogTests.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/InternalClusterInfoServiceSchedulingTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
  server/src/test/java/org/opensearch/gateway/ClusterStateUpdatersTests.java
  server/src/test/java/org/opensearch/gateway/GatewayServiceTests.java
  server/src/test/java/org/opensearch/index/IndexingPressureServiceTests.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureConcurrentExecutionTests.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureMemoryManagerTests.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureSettingsTests.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureStoreTests.java
  server/src/test/java/org/opensearch/index/ShardIndexingPressureTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureSettingsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreStatsTrackerFactoryTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/node/ResponseCollectorServiceTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionControlServiceTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionControlSettingsTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/controllers/CpuBasedAdmissionControllerTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/controllers/IoBasedAdmissionControllerTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/settings/CPUBasedAdmissionControllerSettingsTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/settings/IoBasedAdmissionControllerSettingsTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/stats/AdmissionControlStatsTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/stats/AdmissionControllerStatsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
  test/framework/src/main/java/org/opensearch/cluster/service/FakeThreadPoolClusterManagerService.java
  test/framework/src/main/java/org/opensearch/test/ClusterServiceUtils.java
Labels: backport 2.x

#13678 Fix Flaky Test
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
Labels: bug, backport 2.x, skip-changelog, Search

#13750 Skip unnecessary string format in ThrottlingAllocationDecider when not in debug mode
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java
Labels: enhancement, skip-changelog, ShardManagement:Performance

#13757 Introduce interface changes to support read/write blob with object me…
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/mocks/MockFsAsyncBlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/BlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/BlobDownloadResponse.java
  server/src/main/java/org/opensearch/common/blobstore/stream/read/ReadContext.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WriteContext.java
  server/src/main/java/org/opensearch/common/blobstore/transfer/RemoteTransferContainer.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/test/java/org/opensearch/common/blobstore/AsyncMultiStreamEncryptedBlobContainerTests.java
  server/src/test/java/org/opensearch/common/blobstore/stream/read/listener/ReadContextListenerTests.java
Labels: skip-changelog

#13773 Add Jay Deng as a maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#13710 De-duping shards in ShardsBatchGatewayAllocator based on ShardId inst…
  CHANGELOG.md
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Labels: backport 2.x

#13765 Implement interface changes for s3 plugin to read/write blob with obj…
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RetryingInputStreamTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
  server/src/main/java/org/opensearch/common/blobstore/BlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/FetchBlobResult.java
  server/src/main/java/org/opensearch/common/blobstore/stream/write/WriteContext.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
Labels: skip-changelog

#13786 Gradle Check Optimization
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#13679 [Remote Store] Add segment transfer timeout dynamic setting
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/SegmentUploadFailedException.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: backport 2.x, Storage, Storage:Resiliency

#13637 [Remote Store] Upload translog checkpoint as object metadata to translog
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteCloneIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteShrinkIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteSplitIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteMigrationIndexMetadataUpdateIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/PrimaryTermValidationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreForceMergeIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRepositoryRegistrationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreUploadIndexPathIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/translogmetadata/mocks/MockFsMetadataSupportedBlobContainer.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/translogmetadata/mocks/MockFsMetadataSupportedBlobStore.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/translogmetadata/mocks/MockFsMetadataSupportedRepository.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/translogmetadata/mocks/MockFsMetadataSupportedRepositoryPlugin.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/IndexMetadataUpdater.java
  server/src/main/java/org/opensearch/common/blobstore/BlobContainer.java
  server/src/main/java/org/opensearch/common/blobstore/BlobStore.java
  server/src/main/java/org/opensearch/common/blobstore/InputStreamWithMetadata.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteMigrationIndexMetadataUpdater.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreCustomMetadataResolver.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategyResolver.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/BlobStoreTransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/FileSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferService.java
  server/src/main/java/org/opensearch/index/translog/transfer/TransferSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogCheckpointTransferSnapshot.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteMigrationIndexMetadataUpdaterTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreCustomMetadataResolverTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyResolverTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/BlobStoreTransferServiceTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
  server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, backport 2.x, Storage:Performance, Storage:Remote, v2.15.0

#13719 Refactor writable warm feature flag to include tiering
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
Labels: skip-changelog, Search:Remote Search

#13790 Sync GitHub workflows from main branch
  .github/workflows/assemble.yml
  .github/workflows/copy-linked-issue-labels.yml
  .github/workflows/dependabot_pr.yml
  .github/workflows/gradle-check.yml
  .github/workflows/maintainer-approval.yml
  .github/workflows/precommit.yml
  .github/workflows/version.yml
  .github/workflows/wrapper.yml
Labels: backport 1.3, skip-changelog

#13800 Add backport workflow to 1.x
  .github/workflows/backport.yml
Labels: skip-changelog

#13779 Add TestIssueLogging on flaky test - org.opensearch.repositories.url.RepositoryURLClientYamlTestSuiteIT.test
  modules/repository-url/src/yamlRestTest/java/org/opensearch/repositories/url/RepositoryURLClientYamlTestSuiteIT.java
Labels: skip-changelog

#13814 org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testRequestStats fails with NullPointerException
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
Labels: bug, good first issue, flaky-test, backport 2.x, skip-changelog, Storage

#13825 Bump reactor from 3.5.15 to 3.5.17 and reactor-netty from 1.1.17 to 1.1.19
  CHANGELOG.md
  buildSrc/version.properties
  plugins/repository-azure/licenses/reactor-netty-core-1.1.17.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.19.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.17.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.19.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.17.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.19.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.17.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.19.jar.sha1
  server/licenses/reactor-core-3.5.15.jar.sha1
  server/licenses/reactor-core-3.5.17.jar.sha1
Labels: dependencies, backport 2.x

#13799 Backport 2.x - Refactor writable warm feature flag to include tiering
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
Labels: skip-changelog

#13847 [Backport] [2.x] Bump com.google.code.gson:gson in /test/fixtures/hdfs-fixture (#13842)
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport, skip-changelog

#13498 Check changed files before running gradle check
  .github/workflows/gradle-check.yml
Labels: skip-changelog

#13131 Optimize remote state stale file deletion
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: bug, enhancement, backport, flaky-test, Cluster Manager, Storage:Remote, v2.15.0

#13860 Remove deprecated constant META_FIELDS_BEFORE_7DOT8
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
Labels: backport 2.x

#13874 Move CHANGELOG entry for #13860 to CHANGELOG 3.0
  CHANGELOG-3.0.md
  CHANGELOG.md
Labels: skip-changelog

#13598 Removing changelog entry for the released fix
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.14.0.md
Labels: backport 2.x, skip-changelog

#13877 Attempt to stabilize MacOS GA runner caused by QEMU / Colima / Docker issues
  .github/workflows/assemble.yml
Labels: skip-changelog

#13770 Pass parent filter to inner hit query
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
Labels: backport 2.x

#13866 Backport of 13814 - org.opensearch.repositories.s3.S3BlobStoreRepositoryTests.testRequest…
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
Labels: bug, good first issue, flaky-test, skip-changelog, Storage

#13869 Remove conflicting static method from Metadata.Custom interface
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
Labels: skip-changelog

#13887 Fix flaky test S3BlobStoreRepositoryTests.testRequestStats
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Storage

#13896 Revert "Pass parent filter to inner hit query (#13770)"
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
Labels: skip-changelog

#13903 Pass parent filter to inner hit query
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
Labels: backport 2.x

#13777 13776: allow adding query parameters to RequestOptions
  CHANGELOG.md
  client/rest/src/main/java/org/opensearch/client/Request.java
  client/rest/src/main/java/org/opensearch/client/RequestOptions.java
  client/rest/src/test/java/org/opensearch/client/RequestOptionsTests.java
Labels: enhancement, Clients, v3.0.0, backport 2.x, v2.15.0

#13910 Fix Flaky - testForceMergeWithSoftDeletesRetentionAndRecoverySource #5364
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: bug, flaky-test, skip-changelog, Indexing

#13829 Avoid negative scores returned from `multi_match` query with `cross_fields`
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/50_multi_match.yml
  server/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java
  test/framework/src/main/java/org/opensearch/test/rest/yaml/section/Assertion.java
  test/framework/src/main/java/org/opensearch/test/rest/yaml/section/GreaterThanAssertion.java
  test/framework/src/main/java/org/opensearch/test/rest/yaml/section/GreaterThanEqualToAssertion.java
  test/framework/src/main/java/org/opensearch/test/rest/yaml/section/LessThanAssertion.java
  test/framework/src/main/java/org/opensearch/test/rest/yaml/section/LessThanOrEqualToAssertion.java
Labels: bug, backport 2.x, Search:Relevance

#13911 Fix NPE on restore searchable snapshot
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
  server/src/main/java/org/opensearch/cluster/block/ClusterBlocks.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingPool.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDecider.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: bug, backport 2.x, Search:Remote Search, Storage:Snapshots, v2.15.0
