Repository opensearch-project/OpenSearch, pull requests merged in 2024-08, with the labels that each got.

#15051 Add javadoc about ThreadContextPermission for stashWithOrigin and stashAndMergeHeaders
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContext.java
Labels: backport 2.x, skip-changelog

#15082 Add MacOS aarch64 to precommit since we rolled out the support for such distribution
  .github/workflows/precommit.yml
Labels: backport 2.x, skip-changelog, arm64-mac-architecture

#15085 Decommission the Core Triage meeting
  TRIAGING.md
Labels: bug, RFC, skip-changelog, Other

#14711 support rangeQuery and regexpQuery in constant_keyword field type
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/110_constant_keyword.yml
  server/src/main/java/org/opensearch/index/mapper/ConstantFieldType.java
  server/src/main/java/org/opensearch/index/mapper/ConstantKeywordFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldTypeTests.java
Labels: bug, v3.0.0, backport 2.x, v2.17.0

#15072 Support scripting for composite aggs in concurrent segment search
  CHANGELOG.md
  modules/lang-painless/build.gradle
  modules/lang-painless/src/internalClusterTest/java/org/opensearch/painless/SimplePainlessIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationFactory.java
  server/src/main/java/org/opensearch/search/lookup/SearchLookup.java
  server/src/main/java/org/opensearch/search/lookup/SourceLookup.java
Labels: enhancement, Search:Aggregations, backport 2.x, Search:Performance, Search:Query Capabilities, v2.17.0

#15094 [Backport 2.x] Support scripting for composite aggs in concurrent segment search
  CHANGELOG.md
  modules/lang-painless/build.gradle
  modules/lang-painless/src/internalClusterTest/java/org/opensearch/painless/SimplePainlessIT.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationFactory.java
  server/src/main/java/org/opensearch/search/lookup/SearchLookup.java
  server/src/main/java/org/opensearch/search/lookup/SourceLookup.java
Labels: v2.17.0

#15037 Fix RemoteCloneIndex flaky test by using sync FS repo
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteCloneIndexIT.java
Labels: >test-failure, flaky-test, backport 2.x, autocut, skip-changelog, Storage:Remote

#15080 Fix delete index template failed when the index template matches a data stream but is unused
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.delete_index_template/10_basic.yml
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
Labels: bug, :Feature/Datastream, v3.0.0, backport 2.x, v2.17.0

#15099 Update stale reference in README from 2.14.1 to 2.17.0
  README.md
Labels: backport 2.x, skip-changelog

#15101 Fix version check in yml test for the bug fix of delete index template failed
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.delete_index_template/10_basic.yml
Labels: skip-changelog

#15086 Update old untriaged link to not require manually editing the url
  TRIAGING.md
Labels: skip-changelog

#15119 Bump org.apache.avro:avro from 1.11.3 to 1.12.0 in /plugins/repository-hdfs
  CHANGELOG.md
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/avro-1.11.3.jar.sha1
  plugins/repository-hdfs/licenses/avro-1.12.0.jar.sha1
Labels: backport 2.x

#15122 Bump org.bouncycastle:bcpg-fips from 1.0.7.1 to 2.0.8 and org.bouncycastle:bc-fips from 1.0.2.5 to 2.0.0
  CHANGELOG.md
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/plugin-cli/licenses/bc-fips-1.0.2.5.jar.sha1
  distribution/tools/plugin-cli/licenses/bc-fips-2.0.0.jar.sha1
  distribution/tools/plugin-cli/licenses/bcpg-fips-1.0.7.1.jar.sha1
  distribution/tools/plugin-cli/licenses/bcpg-fips-2.0.8.jar.sha1
Labels: dependencies, backport 2.x

#15127 Fix version check for adding rangeQuery and regexpQuery support for constant_keyword field type
  rest-api-spec/src/main/resources/rest-api-spec/test/index/115_constant_keyword.yml
Labels: backport 2.x, skip-changelog

#15134 Add baseline-cluster-config key to benchmark config
  .github/benchmark-configs.json
  .github/workflows/benchmark-pull-request.yml
Labels: skip-changelog

#15033 Fix bulk ingest NPE with empty pipeline
  CHANGELOG.md
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
Labels: bug, backport 2.x, Indexing

#15137 CODEOWNERS personalizations for jed326
  .github/CODEOWNERS
Labels: backport 1.x, backport 2.x, backport 1.3, skip-changelog

#14817 Changes to build star tree in off heap
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/common/util/ByteArrayBackedBitset.java
  server/src/main/java/org/opensearch/index/codec/composite/Composite99DocValuesWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractDocumentsFileManager.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/SegmentDocsFileManager.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeDocsFileManager.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreesBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentBitSetUtil.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentsSorter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/TreeNode.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreesBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/SequentialDocValuesIteratorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentBitSetUtilTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentsSorterTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: enhancement, skip-changelog, Performance, Indexing, Indexing:Performance, Other

#15139 [Backport 2.x] CODEOWNERS personalizations for jed326 (#15137)
  .github/CODEOWNERS
Labels: skip-changelog

#15140 [Backport 1.x] CODEOWNERS personalizations for jed326 (#15137)
  .github/CODEOWNERS
Labels: skip-changelog

#15141 [Backport 1.3] CODEOWNERS personalizations for jed326 (#15137)
  .github/CODEOWNERS
Labels: skip-changelog

#13897 QueryGroup Resource Tracking framework and implementation
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/search/ResourceType.java
  server/src/main/java/org/opensearch/wlm/QueryGroupLevelResourceUsageView.java
  server/src/main/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerService.java
  server/src/main/java/org/opensearch/wlm/tracker/package-info.java
  server/src/test/java/org/opensearch/search/ResourceTypeTests.java
  server/src/test/java/org/opensearch/wlm/QueryGroupLevelResourceUsageViewTests.java
  server/src/test/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerServiceTests.java
Labels: backport 2.x, v2.17.0

#14234 Add 'ShardManagement:*' labels to Cluster Manager triage search
  TRIAGING.md
Labels: stalled, skip-changelog

#15157 fix missing curly brace in benchmark workflow file
  .github/workflows/benchmark-pull-request.yml
Labels: skip-changelog

#15163 Add Varun Bansal as maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#15162 Fix yml test {p0=indices.delete_index_template/10_basic} is flaky
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.delete_index_template/10_basic.yml
Labels: bug, flaky-test, backport 2.x, skip-changelog

#14977 Optimise unassigned shards iteration after allocator timeout
  server/src/main/java/org/opensearch/common/util/BatchRunnableExecutor.java
  server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/test/java/org/opensearch/common/util/BatchRunnableExecutorTests.java
  server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Labels: bug, skip-changelog, Cluster Manager, Other

#15153 Add slice level operation listener methods
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/shard/SearchOperationListener.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/test/java/org/opensearch/index/shard/SearchOperationListenerTests.java
  server/src/test/java/org/opensearch/search/SearchCancellationTests.java
  server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java
  server/src/test/java/org/opensearch/search/profile/query/QueryProfilerTests.java
  server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
  server/src/test/java/org/opensearch/search/query/QueryProfilePhaseTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, backport 2.x, Search:Performance, Roadmap:Search and ML, v2.17.0

#14464 Refactor the filter rewrite optimization
  server/src/main/java/org/opensearch/search/aggregations/bucket/FastFilterRewriteHelper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/AggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/CompositeAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/DateHistogramAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/FilterRewriteOptimizationContext.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Helper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/PointTreeTraversal.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/RangeAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Ranges.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/package-info.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java
Labels: Search:Aggregations, backport 2.x, skip-changelog, Performance, v2.16.0, v2.17.0

#15172 Fix flaky test in {yaml=ingest/70_bulk}
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/70_bulk.yml
Labels: backport 2.x, skip-changelog

#15107 Flaky test : Don't use async repo for SplitIndex and wait for translo…
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteSplitIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
Labels: >test-failure, flaky-test, backport 2.x, autocut, skip-changelog, Storage, Storage:Remote

#15184 Fix (some_ AzureBlobContainerRetriesTests flaky tests
  plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, Storage:Snapshots

#15126 Fix array_index_out_of_bounds_exception when indexing documents with field name containing only dot
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/120_field_name.yml
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
Labels: bug, v3.0.0, backport 2.x, Indexing, v2.17.0

#15198 add required distribution key in setup-java action
  .github/workflows/benchmark-pull-request.yml
Labels: skip-changelog

#15189 Fix more AzureBlobContainerRetriesTests flaky tests
  plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java
Labels: flaky-test, backport 2.x, skip-changelog

#15200 [Backport 2.x] Flaky test : Don't use async repo for SplitIndex and wait for translo…
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteSplitIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
Labels: skip-changelog

#15192 [Forwardport] Update 120_field_name.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/120_field_name.yml
Labels: skip-changelog

#14625 Star Tree Min and Max Value Aggregators
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MaxValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MetricAggregatorInfo.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MinValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/StatelessDoubleValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregatorFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractDocumentsFileManager.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/AbstractValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MaxValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MinValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/StaticValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregatorFactoryTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
Labels: enhancement, Search:Aggregations, RFC, skip-changelog, Indexing:Performance, v2.17.0

#14680 Add Create QueryGroup API Logic
  CHANGELOG.md
  plugins/workload-management/build.gradle
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/WorkloadManagementPlugin.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/CreateQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/CreateQueryGroupRequest.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/CreateQueryGroupResponse.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportCreateQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/package-info.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/package-info.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rest/RestCreateQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rest/package-info.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceService.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/package-info.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/QueryGroupTestUtils.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/CreateQueryGroupRequestTests.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/CreateQueryGroupResponseTests.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceServiceTests.java
  plugins/workload-management/src/yamlRestTest/java/org/opensearch/plugin/wlm/WorkloadManagementClientYamlTestSuiteIT.java
  plugins/workload-management/src/yamlRestTest/resources/rest-api-spec/api/create_query_group_context.json
  plugins/workload-management/src/yamlRestTest/resources/rest-api-spec/test/wlm/10_create_query_group.yml
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/QueryGroup.java
  server/src/test/java/org/opensearch/cluster/metadata/QueryGroupMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/QueryGroupTests.java
Labels: backport 2.x

#15210 Refactor remote writeable entity and store to make it more reusable
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/common/remote/AbstractClusterMetadataWriteableBlobEntity.java
  server/src/main/java/org/opensearch/common/remote/AbstractRemoteWritableEntityManager.java
  server/src/main/java/org/opensearch/common/remote/RemoteWritableEntityManager.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableBlobEntity.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntityBlobStore.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterBlocks.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterStateCustoms.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCoordinationMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteGlobalMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteHashesOfConsistentSettings.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemotePersistentSettingsMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteRoutingTableBlobStore.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteTransientSettingsMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTable.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteRoutingTableDiff.java
  server/src/test/java/org/opensearch/common/remote/AbstractRemoteWritableEntityManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#15214 Improve breaking change logic for changelog verifier
  .github/workflows/changelog_verifier.yml
Labels: enhancement, good first issue, backport 2.x, skip-changelog, Build

#15220 Correction of a typo
  libs/core/src/main/java/org/opensearch/core/xcontent/AbstractXContentParser.java
  qa/os/src/test/java/org/opensearch/packaging/util/FileUtils.java
  qa/smoke-test-http/src/test/java/org/opensearch/http/DanglingIndicesRestIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/DanglingIndicesIT.java
  server/src/main/java/org/opensearch/http/HttpChannel.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/package-info.java
  server/src/main/java/org/opensearch/transport/TcpChannel.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/info/NodeInfoTests.java
  server/src/test/java/org/opensearch/common/LocalTimeOffsetTests.java
  server/src/test/java/org/opensearch/indices/breaker/HierarchyCircuitBreakerServiceTests.java
Labels: skip-changelog

#15173 Bump dnsjava version to 3.6.0 to address CVE-2024-25638
  test/fixtures/hdfs-fixture/build.gradle
Labels: CVE, Mend: dependency security vulnerability, backport 2.x, skip-changelog, Storage

#15223 Fix responsibility check for existing shards allocator when timed out
  server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
  server/src/main/java/org/opensearch/gateway/PrimaryShardAllocator.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
Labels: bug, skip-changelog, Other

#13620 Fix parseToken array popping
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/test/java/org/opensearch/common/xcontent/JsonToStringXContentParserTests.java
Labels: backport 2.x, v2.17.0

#15236 Fix logic for getting maintainer ids for benchmark workflow
  .github/workflows/benchmark-pull-request.yml
Labels: skip-changelog

#15143 Use clusterUUID for discovery nodes remote path
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
Labels: skip-changelog

#15187 Don't rely on test code execution time span for RemoteSegmentTransferTrackerTests
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, Storage:Remote

#15238 Replace and block usages of org.apache.logging.log4j.util.Strings
  CHANGELOG.md
  buildSrc/src/main/resources/forbidden/opensearch-all-signatures.txt
  server/src/main/java/org/opensearch/common/logging/JsonThrowablePatternConverter.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/shard/ShardPath.java
  test/framework/src/main/java/org/opensearch/client/RestClientBuilderTestCase.java
Labels: bug, backport 2.x, skip-changelog, Libraries

#13574 [Offline Nodes] Adds new library for offline tasks
  CHANGELOG.md
  libs/task-commons/build.gradle
  libs/task-commons/src/main/java/org/opensearch/task/commons/clients/TaskListRequest.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/clients/TaskManagerClient.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/clients/TaskProducerClient.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/clients/TaskWorkerClient.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/clients/package-info.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/package-info.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/task/Task.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/task/TaskId.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/task/TaskParams.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/task/TaskStatus.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/task/TaskType.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/task/package-info.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/worker/TaskWorker.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/worker/WorkerNode.java
  libs/task-commons/src/main/java/org/opensearch/task/commons/worker/package-info.java
  libs/task-commons/src/test/java/org/opensearch/task/commons/mocks/MockTaskParams.java
  libs/task-commons/src/test/java/org/opensearch/task/commons/task/TaskIdTests.java
  libs/task-commons/src/test/java/org/opensearch/task/commons/task/TaskTests.java
  libs/task-commons/src/test/java/org/opensearch/task/commons/worker/WorkerNodeTests.java
  server/build.gradle
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/TaskManagerClientPlugin.java
  server/src/main/java/org/opensearch/plugins/TaskWorkerPlugin.java
Labels: backport 2.x, Storage, Storage:Performance, v2.17.0

#15177 Update to Gradle 8.10
  .github/workflows/assemble.yml
  .github/workflows/precommit.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x, skip-changelog, Build

#15180 Add timestamp pinning service and scheduler to update in-memory state
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemotePinnedTimestamps.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteStorePinnedTimestampsBlobStore.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemotePinnedTimestampsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: skip-changelog

#15194 Remove filter rewrite optimization for range aggregations when segment is not effective match all
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/360_date_histogram.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/AggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/DateHistogramAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/RangeAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregatorTests.java
Labels: bug, Search:Aggregations, backport 2.x, v2.17.0, backport 2.16

#15267 Fix Gradle runtime JDK version post 8.10 version upgrade
  .ci/java-versions.properties
  buildSrc/src/main/resources/minimumCompilerVersion
Labels: skip-changelog

#15270 Fix Gradle runtime JDK version post 8.10 version upgrade
  .ci/java-versions.properties
  buildSrc/src/main/resources/minimumCompilerVersion
Labels: skip-changelog

#15262 Bump Project Reactor to 3.5.20 and Reactor Netty to 1.1.22
  CHANGELOG.md
  buildSrc/version.properties
  client/rest/licenses/reactor-core-3.5.19.jar.sha1
  client/rest/licenses/reactor-core-3.5.20.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.21.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.22.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.21.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.22.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.21.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.22.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.21.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.22.jar.sha1
  server/licenses/reactor-core-3.5.19.jar.sha1
  server/licenses/reactor-core-3.5.20.jar.sha1
Labels: dependencies, backport 2.x

#14709 Add Get QueryGroup API Logic
  CHANGELOG.md
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/WorkloadManagementPlugin.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/GetQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/GetQueryGroupRequest.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/GetQueryGroupResponse.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportGetQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rest/RestGetQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceService.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/QueryGroupTestUtils.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/GetQueryGroupRequestTests.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/GetQueryGroupResponseTests.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/TransportGetQueryGroupActionTests.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceServiceTests.java
  plugins/workload-management/src/yamlRestTest/resources/rest-api-spec/api/get_query_group_context.json
  plugins/workload-management/src/yamlRestTest/resources/rest-api-spec/test/wlm/10_query_group.yml
  server/src/main/java/org/opensearch/cluster/metadata/QueryGroup.java
Labels: backport 2.x

#15233 fix: MinHash token filter parameters not working
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/MinHashTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/MinHashFilterFactoryTests.java
Labels: bug, backport 2.x, Indexing

#15274 Star Tree Merge and Aggregation Fixes
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/StatelessDoubleValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/AbstractValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MaxValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MinValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
Labels: bug, skip-changelog, Indexing:Performance

#15147 [Star tree] Rename count to value_count to be inline with aggregations
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/MetricStat.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeIndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregatorFactory.java
  server/src/test/java/org/opensearch/common/util/ByteArrayBackedBitsetTests.java
  server/src/test/java/org/opensearch/index/codec/composite/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MetricAggregatorInfoTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregatorFactoryTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: skip-changelog

#15307 Update minimumCompilerVersion to use jdk 11
  buildSrc/src/main/resources/minimumCompilerVersion
Labels: backport 1.x, skip-changelog

#15293 fix: MinHash token filter parameters not working
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/MinHashTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/MinHashFilterFactoryTests.java
Labels: bug, Indexing

#15305 [Backport] [2.x] Bump com.azure:azure-core-http-netty from 1.15.1 to 1.15.3 in /plugins/repository-azure (#15300)
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-core-http-netty-1.15.1.jar.sha1
  plugins/repository-azure/licenses/azure-core-http-netty-1.15.3.jar.sha1
Labels: backport

#15304 Adding @jainankitk as a Maintainer
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#14774 Support Filtering on Large List encoded by Bitmap
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/370_bitmap_filtering.yml
  server/build.gradle
  server/licenses/RoaringBitmap-1.1.0.jar.sha1
  server/licenses/RoaringBitmap-LICENSE.txt
  server/licenses/RoaringBitmap-NOTICE.txt
  server/src/internalClusterTest/java/org/opensearch/search/query/SearchQueryIT.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/query/TermsQueryBuilder.java
  server/src/main/java/org/opensearch/indices/TermsLookup.java
  server/src/main/java/org/opensearch/search/query/BitmapDocValuesQuery.java
  server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/TermsQueryBuilderTests.java
  server/src/test/java/org/opensearch/indices/TermsLookupTests.java
  server/src/test/java/org/opensearch/search/query/BitmapDocValuesQueryTests.java
Labels: enhancement, backport 2.x, Search:Query Capabilities, v2.17.0

#15294 Move timestamp pinning settings to RemoteStoreSettings
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
Labels: skip-changelog

#14371 Optimize global ordinal includes/excludes for prefix matching
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/IncludeExclude.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/IncludeExcludeTests.java
Labels: enhancement, Search:Aggregations, backport 2.x, v2.16.0, v2.17.0

#15287 Backport/backport 15194 to 2.x
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/360_date_histogram.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregatorTests.java
Labels: bug, Search:Aggregations, v2.17.0, backport 2.16

#13895 Adding access to noSubMatches and noOverlappingMatches in Hyphenation…
  CHANGELOG.md
  modules/analysis-common/src/main/java/org/opensearch/analysis/common/HyphenationCompoundWordTokenFilterFactory.java
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/CompoundAnalysisTests.java
  modules/analysis-common/src/test/resources/org/opensearch/analysis/common/da_UTF8.xml
  test/framework/src/main/resources/org/opensearch/analysis/common/test1.json
  test/framework/src/main/resources/org/opensearch/analysis/common/test1.yml
Labels: enhancement, good first issue, low hanging fruit, backport 2.x, Search, Search:Relevance

#15028 [Workload Management] Add QueryGroupServiceSettings
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/wlm/WorkloadManagementSettings.java
  server/src/test/java/org/opensearch/wlm/WorkloadManagementSettingsTests.java
Labels: backport 2.x

#15322 Update affiliation for @nknize.
  MAINTAINERS.md
Labels: skip-changelog

#15224 Add log when download completes with its size
  server/src/main/java/org/opensearch/index/store/RemoteStoreFileDownloader.java
Labels: backport 2.x, skip-changelog

#15320 [Backport 2.x] Star tree mapping changes
  CHANGELOG.md
  distribution/src/config/opensearch.yml
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataMappingService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexValidator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DateDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/Dimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/Metric.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/MetricStat.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/NumericDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeField.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeFieldConfiguration.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeIndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeValidator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/package-info.java
  server/src/main/java/org/opensearch/index/mapper/CompositeDataCubeFieldType.java
  server/src/main/java/org/opensearch/index/mapper/CompositeMappedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/Mapper.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/RootObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/MapperTestCase.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: v2.17.0

#15352 [Forwardport] Support Filtering on Large List encoded by Bitmap (version update)
  server/src/main/java/org/opensearch/index/query/TermsQueryBuilder.java
  server/src/main/java/org/opensearch/indices/TermsLookup.java
Labels: skip-changelog

#15336 Add support for index level slice count setting
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
Labels: enhancement, backport 2.x, Search:Performance, Roadmap:Cost/Performance/Scale

#15325 Adding allowlist setting for ingest-useragent and ingest-geoip processors
  CHANGELOG.md
  modules/ingest-geoip/src/main/java/org/opensearch/ingest/geoip/IngestGeoIpModulePlugin.java
  modules/ingest-geoip/src/test/java/org/opensearch/ingest/geoip/IngestGeoIpModulePluginTests.java
  modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/IngestUserAgentModulePlugin.java
  modules/ingest-user-agent/src/test/java/org/opensearch/ingest/useragent/IngestUserAgentModulePluginTests.java
Labels: backport 2.x

#14735 Add Delete QueryGroup API Logic
  CHANGELOG.md
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/WorkloadManagementPlugin.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/WorkloadManagementPluginModule.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/DeleteQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/DeleteQueryGroupRequest.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportCreateQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportDeleteQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rest/RestDeleteQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceService.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/CreateQueryGroupResponseTests.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/DeleteQueryGroupRequestTests.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/action/TransportDeleteQueryGroupActionTests.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/rest/RestDeleteQueryGroupActionTests.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceServiceTests.java
  plugins/workload-management/src/yamlRestTest/resources/rest-api-spec/api/delete_query_group_context.json
  plugins/workload-management/src/yamlRestTest/resources/rest-api-spec/test/wlm/10_query_group.yml
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
Labels: backport 2.x

#15278 [Star Tree] Lucene Abstractions for Star Tree File Formats
  server/src/main/java/org/apache/lucene/codecs/lucene90/Lucene90DocValuesConsumerWrapper.java
  server/src/main/java/org/apache/lucene/codecs/lucene90/Lucene90DocValuesProducerWrapper.java
  server/src/main/java/org/apache/lucene/index/SortedNumericDocValuesWriterWrapper.java
  server/src/main/java/org/opensearch/index/codec/composite/CompositeCodecFactory.java
  server/src/main/java/org/opensearch/index/codec/composite/LuceneDocValuesConsumerFactory.java
  server/src/main/java/org/opensearch/index/codec/composite/LuceneDocValuesProducerFactory.java
  server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99Codec.java
  server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99DocValuesFormat.java
  server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99DocValuesReader.java
  server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99DocValuesWriter.java
  server/src/main/java/org/opensearch/index/codec/composite/composite99/package-info.java
  server/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  server/src/test/java/org/opensearch/index/codec/CodecTests.java
  server/src/test/java/org/opensearch/index/codec/composite/LuceneDocValuesConsumerFactoryTests.java
  server/src/test/java/org/opensearch/index/codec/composite/LuceneDocValuesProducerFactoryTests.java
  server/src/test/java/org/opensearch/index/codec/composite/SortedNumericDocValuesWriterWrapperTests.java
  server/src/test/java/org/opensearch/index/codec/composite/datacube/startree/StarTreeDocValuesFormatTests.java
Labels: enhancement, skip-changelog, Indexing:Performance

#15152 [Star tree] Changes to handle derived metrics such as avg as part of star tree mapping
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/MetricStat.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeIndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: enhancement, skip-changelog, Indexing:Performance, v2.17.0

#15374 [Backport 2.x] Adding allowlist setting for ingest-useragent and ingest-geoip processors
  CHANGELOG.md
  modules/ingest-geoip/src/main/java/org/opensearch/ingest/geoip/IngestGeoIpPlugin.java
  modules/ingest-geoip/src/test/java/org/opensearch/ingest/geoip/IngestGeoIpPluginTests.java
  modules/ingest-user-agent/src/main/java/org/opensearch/ingest/useragent/IngestUserAgentPlugin.java
  modules/ingest-user-agent/src/test/java/org/opensearch/ingest/useragent/IngestUserAgentPluginTests.java
Labels: backport

#15327 [Bugfix] Fixes IRC NPE bug for timed-out cacheable queries
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
Labels: bug, skip-changelog, Search

#15361 Bump opentelemetry from 1.40.0 to 1.41.0, opentelemetry-semconv from 1.26.0-alpha to 1.27.0-alpha
  CHANGELOG.md
  buildSrc/version.properties
  plugins/telemetry-otel/build.gradle
  plugins/telemetry-otel/licenses/opentelemetry-api-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-incubator-1.40.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-incubator-1.41.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.40.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.26.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.27.0-alpha.jar.sha1
Labels: dependencies, backport 2.x

#15390 [Backport 2.x] [Bugfix] Fixes IRC NPE bug for timed-out cacheable queries (#15327)
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
Labels: skip-changelog

#15393 Add SplitResponseProcessor to allowlist
  CHANGELOG.md
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
Labels: bug, backport 2.x, Search, v2.17.0

#15394 Fix unchecked cast in dynamic action map getter
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/test/java/org/opensearch/action/DynamicActionRegistryTests.java
Labels: bug, backport 2.x, extensions, Other

#15219 [Remote State] Disable remote publication if remote state disabled
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
Labels: bug, skip-changelog, Cluster Manager

#15366 Compare numbers with equals() instead of ==
  test/framework/src/main/java/org/opensearch/transport/nio/MockNioTransport.java
Labels: backport 2.x, skip-changelog

#15392 Add release notes for release 1.3.19
  release-notes/opensearch.release-notes-1.3.19.md
Labels: skip-changelog

#15375 Do not throw exception when flat_object field is explicitly null
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/100_partial_flat_object.yml
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
Labels: v3.0.0, backport 2.x, v2.17.0

#15017 Add support to skip pinned timestamp in remote segment garbage collector
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/store/BaseRemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryWithPinnedTimestampTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#15446 Throw UnsupportedOperationException in unused methods
  server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java
Labels: bug, backport 2.x, skip-changelog, Indexing

#15326 Fix DerivedFieldQuery to support concurrent search.
  CHANGELOG.md
  modules/lang-painless/src/internalClusterTest/java/org/opensearch/painless/SimplePainlessIT.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
  server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
Labels: enhancement, backport 2.x, Search:Query Capabilities, v2.17.0

#15124 [SnapshotV2] Support centralize snapshot creation
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoryFilterUserMetadataIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/TransportCreateSnapshotAction.java
  server/src/main/java/org/opensearch/repositories/FilterRepository.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/action/admin/cluster/snapshots/create/CreateSnapshotResponseTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/snapshots/get/GetSnapshotsResponseTests.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRestoreTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotInfoTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  server/src/test/java/org/opensearch/snapshots/mockstore/MockEventuallyConsistentRepositoryTests.java
  test/framework/src/main/java/org/opensearch/index/shard/RestoreOnlyRepository.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: enhancement, backport 2.x, Storage:Snapshots

#15381 [Streaming Indexing] Introduce bulk HTTP API streaming flavor
  CHANGELOG.md
  buildSrc/version.properties
  client/rest/licenses/httpclient5-5.2.3.jar.sha1
  client/rest/licenses/httpclient5-5.3.1.jar.sha1
  client/rest/src/main/java/org/opensearch/client/RestClient.java
  client/sniffer/licenses/httpclient5-5.2.3.jar.sha1
  client/sniffer/licenses/httpclient5-5.3.1.jar.sha1
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingIT.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingHttpChannel.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingRequestConsumer.java
  plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransportStreamingTests.java
  server/src/main/java/org/opensearch/common/xcontent/support/XContentHttpChunk.java
  server/src/main/java/org/opensearch/rest/action/document/RestBulkStreamingAction.java
Labels: enhancement, v3.0.0, backport 2.x, Indexing, v2.17.0

#15470 Added bwc version 1.3.20
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#15343 add query group stats constructs
  CHANGELOG.md
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceService.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/QueryGroupTestUtils.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/service/QueryGroupPersistenceServiceTests.java
  server/src/main/java/org/opensearch/cluster/metadata/QueryGroup.java
  server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
  server/src/main/java/org/opensearch/search/backpressure/trackers/NodeDuressTrackers.java
  server/src/main/java/org/opensearch/wlm/QueryGroupLevelResourceUsageView.java
  server/src/main/java/org/opensearch/wlm/ResourceType.java
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupState.java
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupStats.java
  server/src/main/java/org/opensearch/wlm/stats/package-info.java
  server/src/main/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerService.java
  server/src/test/java/org/opensearch/cluster/metadata/QueryGroupMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/QueryGroupTests.java
  server/src/test/java/org/opensearch/search/backpressure/SearchBackpressureServiceTests.java
  server/src/test/java/org/opensearch/search/backpressure/trackers/NodeDuressTrackersTests.java
  server/src/test/java/org/opensearch/wlm/QueryGroupLevelResourceUsageViewTests.java
  server/src/test/java/org/opensearch/wlm/ResourceTypeTests.java
  server/src/test/java/org/opensearch/wlm/stats/QueryGroupStateTests.java
  server/src/test/java/org/opensearch/wlm/stats/QueryGroupStatsTests.java
  server/src/test/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerServiceTests.java
Labels: backport 2.x

#15448 Update skip versions for flat_object tests
  rest-api-spec/src/main/resources/rest-api-spec/test/index/100_partial_flat_object.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/105_partial_flat_object_nested.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml
Labels: backport 2.x, skip-changelog

#15472 [Backport] [2.x] [Streaming Indexing] Introduce bulk HTTP API streaming flavor (#15381)
  CHANGELOG.md
  client/rest/src/main/java/org/opensearch/client/RestClient.java
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingIT.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingHttpChannel.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingRequestConsumer.java
  plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransportStreamingTests.java
  server/src/main/java/org/opensearch/common/xcontent/support/XContentHttpChunk.java
  server/src/main/java/org/opensearch/rest/action/document/RestBulkStreamingAction.java
Labels: backport

#15469 Bump icu4j from 70.1 to 75.1
  CHANGELOG.md
  buildSrc/version.properties
  plugins/analysis-icu/licenses/icu4j-70.1.jar.sha1
  plugins/analysis-icu/licenses/icu4j-75.1.jar.sha1
Labels: backport 1.x, dependencies, backport 2.x, backport 1.3

#15475 Fix Netty's ByteBuf leak
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpChunk.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingHttpChannel.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4StreamingRequestConsumer.java
Labels: backport 2.x, skip-changelog

#15432 Change abstraction point for transport protocol
  server/src/main/java/org/opensearch/transport/Header.java
  server/src/main/java/org/opensearch/transport/InboundAggregator.java
  server/src/main/java/org/opensearch/transport/InboundBytesHandler.java
  server/src/main/java/org/opensearch/transport/InboundDecoder.java
  server/src/main/java/org/opensearch/transport/InboundHandler.java
  server/src/main/java/org/opensearch/transport/InboundMessage.java
  server/src/main/java/org/opensearch/transport/InboundPipeline.java
  server/src/main/java/org/opensearch/transport/NativeMessageHandler.java
  server/src/main/java/org/opensearch/transport/TcpTransport.java
  server/src/main/java/org/opensearch/transport/TransportLogger.java
  server/src/main/java/org/opensearch/transport/TransportProtocol.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/NativeInboundBytesHandler.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/NativeInboundMessage.java
  server/src/test/java/org/opensearch/transport/InboundAggregatorTests.java
  server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/InboundPipelineTests.java
  server/src/test/java/org/opensearch/transport/NativeOutboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/TransportProtocolTests.java
Labels: backport 2.x, skip-changelog

#15486 Fixing backward incompatibility check from #15473
  server/src/main/java/org/opensearch/search/ResourceType.java
Labels: skip-changelog

#15295 Star Tree Meta and Data Writers
  server/src/main/java/org/opensearch/index/codec/composite/LuceneDocValuesConsumerFactory.java
  server/src/main/java/org/opensearch/index/codec/composite/LuceneDocValuesProducerFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexConstants.java
  server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexMetadata.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/MetricStat.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/ReadDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeFieldConfiguration.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/StarTreeWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/data/StarTreeDataWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/data/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetaWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/InMemoryTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNodeType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/data/StarTreeFileFormatsTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNodeTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNodeTypeTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeUtilsTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: enhancement, skip-changelog, Indexing:Performance

#15353 Populate RecoveryState details for shallow snapshot restore
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Labels: enhancement, skip-changelog, Storage:Snapshots, v2.17.0

#15489 [Remote Store] Add minTranslogGeneration to remote translog metadata filename
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#15496 Fix ResourceType API annotations and deprecations
  server/src/main/java/org/opensearch/search/ResourceType.java
  server/src/main/java/org/opensearch/wlm/ResourceType.java
Labels: skip-changelog

#15457 Change RemoteSegmentStoreDirectory init at given timestamp to ignore pinned timestamp setting
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryWithPinnedTimestampTests.java
Labels: skip-changelog

#15239 Make balanced shards allocator timebound
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/allocator/TimeBoundBalancedShardsAllocatorTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
Labels: backport 2.x

#15500 Update version check for fix the bug of missing validation for the search_backpressure.mode setting
  rest-api-spec/src/main/resources/rest-api-spec/test/cluster.put_settings/10_basic.yml
Labels: backport 2.x, skip-changelog

#14454 Optimize NodeIndicesStats output behind flag
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/nodestats/NodeStatsIT.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/NodeIndicesStats.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
Labels: bug, backport 2.x, Cluster Manager, Other, Stats, v2.16.0

#15502 Enhance OpenSearch APIs annotation processor with OpenSearch version validation
  libs/common/src/main/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessor.java
  libs/common/src/test/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessorTests.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiAnnotatedUnparseable.java
  libs/common/src/test/resources/org/opensearch/common/annotation/processor/PublicApiWithDeprecatedApiMethod.java
Labels: backport 2.x, skip-changelog

#15506 [Backport 2.x] Change abstraction point for transport protocol
  server/src/main/java/org/opensearch/transport/Header.java
  server/src/main/java/org/opensearch/transport/InboundBytesHandler.java
  server/src/main/java/org/opensearch/transport/InboundDecoder.java
  server/src/main/java/org/opensearch/transport/InboundHandler.java
  server/src/main/java/org/opensearch/transport/InboundMessage.java
  server/src/main/java/org/opensearch/transport/InboundPipeline.java
  server/src/main/java/org/opensearch/transport/TcpTransport.java
  server/src/main/java/org/opensearch/transport/TransportProtocol.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/NativeInboundBytesHandler.java
  server/src/main/java/org/opensearch/transport/nativeprotocol/NativeInboundMessage.java
  server/src/test/java/org/opensearch/transport/InboundAggregatorTests.java
  server/src/test/java/org/opensearch/transport/InboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/InboundPipelineTests.java
  server/src/test/java/org/opensearch/transport/NativeOutboundHandlerTests.java
  server/src/test/java/org/opensearch/transport/TransportProtocolTests.java
Labels: skip-changelog

#15428 Add query group level rejection logic
  CHANGELOG.md
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/wlm/QueryGroupService.java
  server/src/main/java/org/opensearch/wlm/WorkloadManagementTransportInterceptor.java
  server/src/main/java/org/opensearch/wlm/listeners/QueryGroupRequestRejectionOperationListener.java
  server/src/main/java/org/opensearch/wlm/listeners/package-info.java
  server/src/test/java/org/opensearch/wlm/WorkloadManagementTransportInterceptorTests.java
  server/src/test/java/org/opensearch/wlm/WorkloadManagementTransportRequestHandlerTests.java
  server/src/test/java/org/opensearch/wlm/listeners/QueryGroupRequestRejectionOperationListenerTests.java
Labels: backport 2.x

#14069 Fix null values indexed as "null" strings in flat_object field
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/91_flat_object_null_value.yml
  server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
  server/src/test/java/org/opensearch/common/xcontent/JsonToStringXContentParserTests.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
Labels: bug, backport 2.x, Indexing

#15517 update benchmark configs with concurrent search scenarios
  .github/benchmark-configs.json
Labels: skip-changelog

#15216 Remote publication using min node version for backward compatibility
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/cluster/coordination/PublicationTransportHandlerTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifestTests.java
Labels: backport 2.x

#15494 Adding translog durability validation in index templates
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
Labels: backport 2.x

#15290 Create Index using context
  CHANGELOG.md
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexResponse.java
  client/rest-high-level/src/test/java/org/opensearch/client/indices/GetIndexResponseTests.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/CreateIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/settings/UpdateSettingsIT.java
  server/src/main/java/org/opensearch/OpenSearchServerException.java
  server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexClusterStateUpdateRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/indices/create/TransportCreateIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/get/TransportGetIndexAction.java
  server/src/main/java/org/opensearch/cluster/metadata/Context.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/indices/InvalidIndexContextException.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
  server/src/test/java/org/opensearch/action/admin/indices/create/CreateIndexRequestTests.java
  server/src/test/java/org/opensearch/action/admin/indices/get/GetIndexActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/get/GetIndexResponseTests.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  test/framework/src/main/java/org/opensearch/action/support/replication/ClusterStateCreationUtils.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, discuss, feature, backport, RFC, Indexing, Roadmap:Ease of Use, v2.16.0, v2.17.0

#15518 Remove some unused code in the search backpressure package
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
  server/src/main/java/org/opensearch/search/backpressure/settings/SearchShardTaskSettings.java
  server/src/main/java/org/opensearch/search/backpressure/settings/SearchTaskSettings.java
Labels: enhancement, v3.0.0, backport 2.x, v2.17.0

#15410 Initial commit to support a search only replica for RW separation.
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaFeatureFlagIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/IndexMetadataUpdater.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ThrottlingAllocationDecider.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/shard/ReplicationGroup.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/test/java/org/opensearch/action/support/replication/ReplicationOperationTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/SearchOnlyReplicaTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/UpdateNumberOfReplicasTests.java
  server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
  test/framework/src/main/java/org/opensearch/cluster/routing/TestShardRouting.java
Labels: backport 2.x

#15527 add request failure listener to track failures at query group level
  CHANGELOG.md
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/wlm/QueryGroupService.java
  server/src/main/java/org/opensearch/wlm/ResourceType.java
  server/src/main/java/org/opensearch/wlm/listeners/QueryGroupRequestOperationListener.java
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupState.java
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupStats.java
  server/src/test/java/org/opensearch/wlm/listeners/QueryGroupRequestOperationListenerTests.java
  server/src/test/java/org/opensearch/wlm/listeners/QueryGroupRequestRejectionOperationListenerTests.java
Labels: Meta, backport 2.x, Search

#15328 Add fieldType to AbstractQueryBuilder and SortBuilder
  CHANGELOG.md
  modules/mapper-extras/src/main/java/org/opensearch/index/query/RankFeatureQueryBuilder.java
  modules/parent-join/src/main/java/org/opensearch/join/query/HasChildQueryBuilder.java
  modules/parent-join/src/main/java/org/opensearch/join/query/HasParentQueryBuilder.java
  modules/parent-join/src/main/java/org/opensearch/join/query/ParentIdQueryBuilder.java
  modules/percolator/src/main/java/org/opensearch/percolator/PercolateQueryBuilder.java
  server/src/main/java/org/opensearch/index/mapper/FieldTypeLookup.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/query/AbstractQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/BoolQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/BoostingQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/ConstantScoreQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/DisMaxQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/DistanceFeatureQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/IdsQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/IntervalQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchAllQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchNoneQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MoreLikeThisQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MultiMatchQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/index/query/QueryStringQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/ScriptQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SimpleQueryStringBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanContainingQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanFirstQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanMultiTermQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanNearQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanNotQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanOrQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanWithinQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/TermsSetQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/WrapperQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/functionscore/FunctionScoreQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreQueryBuilder.java
  server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/ScoreSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/SortBuilder.java
  server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
  server/src/test/java/org/opensearch/index/query/plugin/DummyQueryBuilder.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  server/src/test/java/org/opensearch/search/sort/AbstractSortTestCase.java
  server/src/test/java/org/opensearch/search/sort/FieldSortBuilderTests.java
  server/src/test/java/org/opensearch/search/sort/plugin/CustomSortBuilder.java
Labels: backport 2.x

#15511 Extract replicator logic from SegmentReplicationTargetService
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicator.java
  server/src/main/java/org/opensearch/node/Node.java
Labels: backport 2.x, skip-changelog

#15531 Handle unsupported media type properly for streaming requests
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4BadRequestIT.java
  server/src/main/java/org/opensearch/rest/RestController.java
Labels: bug, backport 2.x, skip-changelog

#15548 [Backport 2.x] Move timestamp pinning settings to RemoteStoreSettings (#15294)
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
Labels: skip-changelog
