Repository opensearch-project/OpenSearch, pull requests merged in 2024-10, with the labels that each got.

#16132 [Forwardport] [main] Add 2.17.1 release notes (#16104) (#16105)
  release-notes/opensearch.release-notes-2.17.1.md
Labels: skip-changelog

#16146 Fix flaky tests in SnapshotStatusApisIT
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#16046 Optimize checksum creation for remote cluster state
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateChecksum.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterStateChecksumTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#15611 [SnapshotV2] Add timestamp of last successful fetch of pinned timestamps in node stats
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/TransportNodesStatsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/node/NodeService.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeStats.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodesTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: enhancement, skip-changelog, Storage:Snapshots, v2.18.0

#16143 [Backport 2.x] Mitigation for remote snapshot filecache overflow
  release-notes/opensearch.release-notes-2.17.0.md
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTestCase.java
Labels: skip-changelog

#16150 [Backport 2.x] Optimize checksum creation for remote cluster state (#16046)
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateChecksum.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterStateChecksumTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#16024 Remove Identity FeatureFlag
  CHANGELOG.md
  qa/smoke-test-http/src/test/java/org/opensearch/http/IdentityAuthenticationIT.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/identity/IdentityService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java
Labels: v3.0.0, backport 2.x, v2.18.0

#15978 [S3 Repository] Change default retry mechanism of s3 clients to Standard Mode
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/AwsS3ServiceImplTests.java
Labels: enhancement, backport 2.x, Cluster Manager, ClusterManager:RemoteState, v2.18.0

#16154 Ensure RestHandler.Wrapper delegates all implementations to the wrapped handler
  CHANGELOG.md
  server/src/main/java/org/opensearch/rest/RestHandler.java
  server/src/test/java/org/opensearch/rest/BaseRestHandlerTests.java
Labels: v3.0.0, backport 2.x, v2.18.0

#16158 [BUG] Streaming bulk request hangs
  CHANGELOG.md
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingIT.java
  server/src/main/java/org/opensearch/rest/RestController.java
Labels: bug, v3.0.0, backport 2.x, Indexing, v2.18.0

#16168 [Backport 2.x] Change default retry mechanism of s3 client to Standard Mode (#15978)
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/AwsS3ServiceImplTests.java
Labels: v2.18.0

#16089 Fix client-rest-high-level tests for ppc64le
  client/rest-high-level/src/test/java/org/opensearch/client/OpenSearchRestHighLevelClientTestCase.java
  client/rest-high-level/src/test/java/org/opensearch/client/RankEvalIT.java
Labels: bug, CI, skip-changelog, Build, Other

#16174 Change version checks from CURRENT to 2.18 in #15611
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
Labels: skip-changelog

#15986 Add changes to block calls in cat shards, indices and segments based on dynamic limit settings
  CHANGELOG.md
  server/src/main/java/org/opensearch/OpenSearchServerException.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/TransportCatShardsAction.java
  server/src/main/java/org/opensearch/common/breaker/ResponseLimitBreachedException.java
  server/src/main/java/org/opensearch/common/breaker/ResponseLimitSettings.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/rest/action/cat/AbstractCatAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestSegmentsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/main/java/org/opensearch/rest/action/list/RestIndicesListAction.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
  server/src/test/java/org/opensearch/common/breaker/ResponseLimitSettingsTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestIndicesActionTests.java
Labels: enhancement, backport 2.x, Cluster Manager

#16080 Separate Remote State and Publication enabled and configured methods
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemotePublicationConfigurationIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#16148 [Snapshot V2] Remove orphan timestamps post create snapshot completion
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Labels: skip-changelog

#15915 Implement phone number analyzer
  CHANGELOG.md
  gradle/missing-javadoc.gradle
  libs/core/src/main/java/org/opensearch/core/common/Strings.java
  libs/core/src/test/java/org/opensearch/core/common/StringsTests.java
  plugins/analysis-phonenumber/build.gradle
  plugins/analysis-phonenumber/licenses/libphonenumber-8.13.45.jar.sha1
  plugins/analysis-phonenumber/licenses/libphonenumber-LICENSE.txt
  plugins/analysis-phonenumber/licenses/libphonenumber-NOTICE.txt
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalysisPlugin.java
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalyzer.java
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerProvider.java
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizer.java
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizerFactory.java
  plugins/analysis-phonenumber/src/test/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerTests.java
  plugins/analysis-phonenumber/src/test/resources/org/opensearch/analysis/phone/phone_analysis.json
  plugins/analysis-phonenumber/src/yamlRestTest/java/org/opensearch/analysis/phone/PhoneNumberAnalysisClientYamlTestSuiteIT.java
  plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/10_basic.yml
  plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/20_search.yml
Labels: enhancement, v3.0.0, backport 2.x, Search:Relevance, v2.18.0

#16181 [Forwardport] [main] Fix japicmp configuration by treating abstract-to-default method changes as non-breaking
  server/build.gradle
Labels: skip-changelog

#16151 Add more unit tests for RemoteStoreUtils and RemoteFsTimestampAwareTranslog
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
Labels: skip-changelog

#16187 implement phone number analyzer (cherry-pick to 2.x)
  CHANGELOG.md
  gradle/missing-javadoc.gradle
  libs/core/src/main/java/org/opensearch/core/common/Strings.java
  libs/core/src/test/java/org/opensearch/core/common/StringsTests.java
  plugins/analysis-phonenumber/build.gradle
  plugins/analysis-phonenumber/licenses/libphonenumber-8.13.45.jar.sha1
  plugins/analysis-phonenumber/licenses/libphonenumber-LICENSE.txt
  plugins/analysis-phonenumber/licenses/libphonenumber-NOTICE.txt
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalysisPlugin.java
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalyzer.java
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerProvider.java
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizer.java
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizerFactory.java
  plugins/analysis-phonenumber/src/test/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerTests.java
  plugins/analysis-phonenumber/src/test/resources/org/opensearch/analysis/phone/phone_analysis.json
  plugins/analysis-phonenumber/src/yamlRestTest/java/org/opensearch/analysis/phone/PhoneNumberAnalysisClientYamlTestSuiteIT.java
  plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/10_basic.yml
  plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/20_search.yml
Labels: enhancement, v3.0.0, Search:Relevance, v2.18.0

#16194 Fix warnings from SLF4J on startup when repository-s3 is installed
  CHANGELOG.md
  plugins/repository-s3/build.gradle
  plugins/repository-s3/licenses/log4j-slf4j-impl-2.21.0.jar.sha1
Labels: bug, Plugins, v3.0.0, backport 2.x, v2.18.0

#16192 [Bugfix] Fix unknown parameter `source_remote_translog_repository` bug
  server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestBuilder.java
Labels: skip-changelog

#16193 Mute snapshot v2 flaky tests
  server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsV2IT.java
Labels: skip-changelog

#14641 Implementing pagination for _cat/shards
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/shards/TransportCatShardsActionIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/TransportCatShardsAction.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsResponse.java
  server/src/main/java/org/opensearch/action/pagination/IndexPaginationStrategy.java
  server/src/main/java/org/opensearch/action/pagination/PageParams.java
  server/src/main/java/org/opensearch/action/pagination/PageToken.java
  server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java
  server/src/main/java/org/opensearch/action/pagination/ShardPaginationStrategy.java
  server/src/main/java/org/opensearch/action/pagination/package-info.java
  server/src/main/java/org/opensearch/common/Table.java
  server/src/main/java/org/opensearch/rest/RestRequest.java
  server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestTable.java
  server/src/main/java/org/opensearch/rest/action/list/AbstractListAction.java
  server/src/main/java/org/opensearch/rest/action/list/RestIndicesListAction.java
  server/src/main/java/org/opensearch/rest/action/list/RestShardsListAction.java
  server/src/main/java/org/opensearch/rest/pagination/PageParams.java
  server/src/main/java/org/opensearch/rest/pagination/PageToken.java
  server/src/test/java/org/opensearch/action/admin/cluster/shards/CatShardsRequestTests.java
  server/src/test/java/org/opensearch/action/admin/indices/shards/CatShardsResponseTests.java
  server/src/test/java/org/opensearch/action/pagination/IndexPaginationStrategyTests.java
  server/src/test/java/org/opensearch/action/pagination/PageParamsTests.java
  server/src/test/java/org/opensearch/action/pagination/PageTokenTests.java
  server/src/test/java/org/opensearch/action/pagination/ShardPaginationStrategyTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestIndicesActionTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestTableTests.java
  server/src/test/java/org/opensearch/rest/action/list/RestShardsListActionTests.java
  test/framework/src/main/java/org/opensearch/test/rest/FakeRestRequest.java
Labels: enhancement, backport 2.x, Cluster Manager

#14993 Latency improvements to Multi Term Aggregations
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/MultiTermsAggregatorTests.java
Labels: backport 2.x, Performance, v2.18.0

#16221 [Backport] [1.x] Fixing MacOS 13 assemble workflows (once again) (#15898) (#15899)
  .github/workflows/assemble.yml
Labels: skip-changelog

#15925 Add wlm resiliency orchestrator (query group service)
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/backpressure/SearchBackpressureIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
  server/src/main/java/org/opensearch/wlm/QueryGroupService.java
  server/src/main/java/org/opensearch/wlm/QueryGroupTask.java
  server/src/main/java/org/opensearch/wlm/QueryGroupsStateAccessor.java
  server/src/main/java/org/opensearch/wlm/WlmMode.java
  server/src/main/java/org/opensearch/wlm/WorkloadManagementSettings.java
  server/src/main/java/org/opensearch/wlm/cancellation/QueryGroupTaskCancellationService.java
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupState.java
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupStats.java
  server/src/main/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerService.java
  server/src/test/java/org/opensearch/search/backpressure/SearchBackpressureServiceTests.java
  server/src/test/java/org/opensearch/wlm/QueryGroupServiceTests.java
  server/src/test/java/org/opensearch/wlm/WorkloadManagementTransportInterceptorTests.java
  server/src/test/java/org/opensearch/wlm/cancellation/QueryGroupTaskCancellationServiceTests.java
  server/src/test/java/org/opensearch/wlm/listeners/QueryGroupRequestOperationListenerTests.java
  server/src/test/java/org/opensearch/wlm/stats/QueryGroupStateTests.java
  server/src/test/java/org/opensearch/wlm/stats/QueryGroupStatsTests.java
Labels: backport 2.x

#16047 [Tiered Caching] Segmented cache changes
  CHANGELOG.md
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheBaseIT.java
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheIT.java
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsIT.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/EhcacheDiskCacheSettings.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  server/src/main/java/org/opensearch/common/cache/Cache.java
  server/src/main/java/org/opensearch/common/cache/CacheBuilder.java
  server/src/main/java/org/opensearch/common/cache/settings/CacheSettings.java
  server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java
  server/src/main/java/org/opensearch/common/cache/store/builders/ICacheBuilder.java
  server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/common/cache/CacheTests.java
  server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: enhancement, backport 2.x, Search:Performance, v2.18.0

#15249 [Star tree] Adding date field rounding support in star tree
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DataCubeDateTimeUnit.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DateDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/Dimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/NumericDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/ReadDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeField.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeIndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractDocumentsFileManager.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/SegmentDocsFileManager.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeDocsFileManager.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/date/DateTimeUnitAdapter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/date/DateTimeUnitRounding.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/date/package-info.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/DateDimensionTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: enhancement, skip-changelog, Indexing:Performance

#16036 [Star tree] Refactoring builder tests
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BuilderTestsUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuildMetricTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderFlushFlowTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderMergeFlowTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderSortAndAggregateTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderTestCase.java
Labels: skip-changelog

#16110 Change successfulSearchShardIndices to Set<Index>
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
Labels: backport 2.x

#16207 Add more concurrent Snapshot V2 Integ Tests
  server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsV2IT.java
Labels: backport 2.x, skip-changelog

#16228 Close RemoteStorePinnedTimestampService on Node.close()
  server/src/main/java/org/opensearch/node/Node.java
Labels: skip-changelog

#16237 Add TLSv1.3 in jdk.tls.client.protocols systemProp in gradle.properties
  gradle.properties
Labels: backport 2.x, skip-changelog

#16240 Attempt to delete backport branches only for OpenSearch repo
  .github/workflows/delete_backport_branch.yml
Labels: backport 2.x, skip-changelog

#16238 Fix Cache breaking change
  server/src/main/java/org/opensearch/common/cache/Cache.java
Labels: skip-changelog

#16227 [Star tree] Moving compositeCodec to composite912Codec and dropping composite99Codec
  server/src/main/java/org/opensearch/index/codec/composite/CompositeCodecFactory.java
  server/src/main/java/org/opensearch/index/codec/composite/LuceneDocValuesProducerFactory.java
  server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912Codec.java
  server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesFormat.java
  server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesReader.java
  server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesWriter.java
  server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99Codec.java
  server/src/main/java/org/opensearch/index/codec/composite/composite99/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java
  server/src/main/java/org/opensearch/index/engine/SegmentsStats.java
  server/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  server/src/test/java/org/opensearch/index/codec/composite/LuceneDocValuesConsumerFactoryTests.java
  server/src/test/java/org/opensearch/index/codec/composite/LuceneDocValuesProducerFactoryTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BuilderTestsUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuildMetricTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderFlushFlowTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderMergeFlowTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderTestCase.java
Labels: skip-changelog

#16252 Update Apache Lucene version for 2.18.0
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#16144 Remove redundant force merge in rest tests
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/10_histogram.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/230_composite.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/330_auto_date_histogram.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/360_date_histogram.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml
Labels: backport 2.x, skip-changelog

#16254 The protobuf-java leaks through client library dependencies
  CHANGELOG.md
  client/rest-high-level/build.gradle
  server/src/main/java/org/opensearch/rest/action/document/RestBulkStreamingAction.java
Labels: bug, Clients, v3.0.0, backport 2.x, v2.18.0

#16093 Fix Flaky Test RecoveryFromGatewayIT.testShardStoreFetchMultiNodeMultiIndexesUsingBatchAction
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
Labels: >test-failure, flaky-test, autocut, Cluster Manager

#16250 Revert remote publication method renaming in DiscoveryNode
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
Labels: skip-changelog

#16248 BugFix: call listener.onFailure on failure to pin the timestamp
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
Labels: skip-changelog

#16249 [Backport 2.x] Separate Remote State and Publication enabled and configured methods
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemotePublicationConfigurationIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#15955 Add Integration Tests for Workload Management CRUD APIs
  CHANGELOG.md
  plugins/workload-management/build.gradle
  plugins/workload-management/src/javaRestTest/java/org/opensearch/rest/WorkloadManagementRestIT.java
Labels: backport 2.x

#16245 Reconfigure remote state thread pool count
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryPluginTests.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: skip-changelog

#16267 Add snapshot_path prefix to snapshot shards path file on remote store
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardPaths.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Labels: backport 2.x, skip-changelog

#16257 Support JDK-23 (build time and runtime)
  .github/workflows/precommit.yml
  buildSrc/build.gradle
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditPrecommitPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
  gradle/code-coverage.gradle
  libs/grok/src/main/java/org/opensearch/grok/GrokCaptureConfig.java
  plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2DiscoveryTests.java
  plugins/discovery-ec2/src/test/java/org/opensearch/discovery/ec2/Ec2RetriesTests.java
  plugins/repository-hdfs/build.gradle
  server/src/main/java/org/opensearch/common/lucene/search/MultiPhrasePrefixQuery.java
  server/src/main/java/org/opensearch/index/search/MatchQuery.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSource.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java
Labels: backport 2.x, skip-changelog

#16278 fix wlm stats output
  server/src/main/java/org/opensearch/wlm/QueryGroupService.java
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupState.java
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupStats.java
  server/src/test/java/org/opensearch/action/admin/cluster/wlm/WlmStatsResponseTests.java
  server/src/test/java/org/opensearch/wlm/QueryGroupServiceTests.java
  server/src/test/java/org/opensearch/wlm/listeners/QueryGroupRequestOperationListenerTests.java
  server/src/test/java/org/opensearch/wlm/stats/QueryGroupStateTests.java
  server/src/test/java/org/opensearch/wlm/stats/QueryGroupStatsTests.java
  server/src/test/java/org/opensearch/wlm/stats/WlmStatsTests.java
Labels: backport 2.x, skip-changelog

#16280 [Backport 2.x] wlm stats fix
  server/src/main/java/org/opensearch/wlm/QueryGroupService.java
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupState.java
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupStats.java
  server/src/test/java/org/opensearch/action/admin/cluster/wlm/WlmStatsResponseTests.java
  server/src/test/java/org/opensearch/wlm/QueryGroupServiceTests.java
  server/src/test/java/org/opensearch/wlm/listeners/QueryGroupRequestOperationListenerTests.java
  server/src/test/java/org/opensearch/wlm/stats/QueryGroupStateTests.java
  server/src/test/java/org/opensearch/wlm/stats/QueryGroupStatsTests.java
  server/src/test/java/org/opensearch/wlm/stats/WlmStatsTests.java
Labels: skip-changelog

#16281 Change remote store restore cluster state priority to URGENT
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
Labels: skip-changelog

#16273 Remove ApproximateIndexOrDocValuesQuery
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Helper.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateIndexOrDocValuesQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateScoreQuery.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldQueryStringQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/MatchPhraseQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/RangeQueryBuilderTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximateIndexOrDocValuesQueryTests.java
Labels: v3.0.0, backport 2.x, v2.18.0

#16276 Fix IndicesRequestCacheIT flaky tests
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
Labels: backport 2.x, skip-changelog

#16299 Skip unnecessary string format in RemoteStoreMigrationAllocationDecider when not in debug mode
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/RemoteStoreMigrationAllocationDecider.java
Labels: skip-changelog

#16296 Optimise clone operation for incremental full cluster snapshots
  CHANGELOG.md
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/snapshots/SnapshotsServiceTests.java
Labels: enhancement, skip-changelog, Storage:Snapshots

#16265 Fix multi-search with template doesn't return status code
  CHANGELOG.md
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/MultiSearchTemplateResponse.java
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/SearchTemplateResponse.java
  modules/lang-mustache/src/test/java/org/opensearch/script/mustache/MultiSearchTemplateResponseTests.java
  modules/lang-mustache/src/test/java/org/opensearch/script/mustache/SearchTemplateResponseTests.java
  modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache/50_multi_search_template.yml
Labels: backport 2.x

#16269 [Snapshot V2] Move timestamp pinning before cluster state update
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Labels: skip-changelog

#16290 Enable coordinator search.request_stats_enabled by default
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
Labels: backport 2.x

#14383 Flat object field use IndexOrDocValuesQuery to optimize query
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml
  server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java
Labels: bug, backport 2.x, Search:Query Capabilities, v2.16.0, v2.17.0

#16323 Add new benchmark config for query approximation
  .github/benchmark-configs.json
Labels: skip-changelog

#16215 Update last seen cluster state in commit phase
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/test/java/org/opensearch/cluster/coordination/PublicationTransportHandlerTests.java
Labels: backport 2.x

#16236 Add support to dynamically resize threadpools size
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/settings/ClusterSettingsIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/threadpool/ThreadPoolTests.java
Labels: backport 2.x

#16282 Fix deletion permits flow in RemoteFsTimestampAwareTranslog
  server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Labels: skip-changelog

#16331 Fix wrong default value when setting index.number_of_routing_shards to null on index creation
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.create/10_basic.yml
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: backport 2.x

#16342 JDK-23: Mitigation for https://bugs.openjdk.org/browse/JDK-8341127 issue (performance regression)
  distribution/src/config/jvm.options
Labels: skip-changelog

#16314 [Backport] Backport #16306 to 2.x
  CHANGELOG.md
  plugins/discovery-gce/build.gradle
  plugins/discovery-gce/licenses/google-oauth-client-1.35.0.jar.sha1
  plugins/discovery-gce/licenses/google-oauth-client-1.36.0.jar.sha1
Labels: backport

#16332 Bugfix in snapshot V2 restore flow
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsGarbageCollectionIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
Labels: skip-changelog

#15258 fix cluster not able to spin up issue when disk usage exceeds threshold
  CHANGELOG.md
  distribution/tools/keystore-cli/src/test/java/org/opensearch/bootstrap/BootstrapTests.java
  server/src/main/java/org/opensearch/bootstrap/Bootstrap.java
Labels: backport 2.x

#16344 [Snapshot V2] Use metadata from source snapshot while cloning snapshot V2
  server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotV2IT.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Labels: skip-changelog

#16337 [Streaming Indexing] Fix intermittent 'The bulk request must be terminated by a newline [\n]' failures
  CHANGELOG.md
  buildSrc/version.properties
  plugins/repository-azure/licenses/reactor-netty-core-1.1.22.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.23.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.22.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.23.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.22.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.23.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.22.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.23.jar.sha1
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingIT.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransport.java
Labels: bug, v3.0.0, backport 2.x, Indexing, v2.18.0

#15386 Fixed inefficient Stream API call chains ending with count()
  CHANGELOG.md
  modules/percolator/src/main/java/org/opensearch/percolator/QueryAnalyzer.java
Labels: backport 2.x, skip-changelog, v2.18.0

#16349 [Forwardport] [main] Update 10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.create/10_basic.yml
Labels: skip-changelog

#15937 Make Remote Publication a dynamic setting
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactory.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: enhancement, backport 2.x, skip-changelog, ClusterManager:RemoteState

#16037 [Star tree] Performance optimizations during flush flow
  server/src/main/java/org/opensearch/common/util/ByteArrayBackedBitset.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractDocumentsFileManager.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentBitSetUtil.java
  server/src/test/java/org/opensearch/common/util/ByteArrayBackedBitsetTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentBitSetUtilTests.java
Labels: skip-changelog

#16362 [Backport 2.x] Make Remote Publication a dynamic setting (#15937)
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactory.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#16358 Skip media type parsing for known string values
  libs/core/src/main/java/org/opensearch/core/xcontent/MediaTypeRegistry.java
Labels: enhancement, backport 2.x, skip-changelog, Performance, Libraries

#15384 Fixed assignment to catch block parameter
  server/src/main/java/org/opensearch/search/SearchService.java
Labels: backport 2.x, skip-changelog

#16370 make QueryGroups durable
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
Labels: backport 2.x

#16002 Removed suspicious call of getClass() on instance of Class, which erased type info
  libs/core/src/main/java/org/opensearch/core/common/io/stream/Writeable.java
  libs/core/src/test/java/org/opensearch/core/common/io/stream/WriteableTests.java
Labels: skip-changelog

#16377 Revert #15258 to figure out a better approach to fix the issue.
  CHANGELOG.md
  distribution/tools/keystore-cli/src/test/java/org/opensearch/bootstrap/BootstrapTests.java
  server/src/main/java/org/opensearch/bootstrap/Bootstrap.java
Labels: skip-changelog

#16379 [Snapshot v2] Fix bug in snapshot update check for multiple v2 repo
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
Labels: backport 2.x, skip-changelog

#16365 [Snapshot V2] Do orphan timestamp cleanup before completing the snapshot
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Labels: skip-changelog

#16387 Add method to return dynamic SecureTransportParameters from SecureTransportSettingsProvider interface
  CHANGELOG.md
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SecureNetty4Transport.java
  server/src/main/java/org/opensearch/plugins/DefaultSecureTransportParameters.java
  server/src/main/java/org/opensearch/plugins/SecureTransportSettingsProvider.java
Labels: v3.0.0, backport 2.x, v2.18.0

#16378 Fix array hashCode calculation in ResyncReplicationRequest
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/resync/ResyncReplicationRequest.java
  server/src/test/java/org/opensearch/action/resync/ResyncReplicationRequestTests.java
Labels: backport 2.x

#15362 Fix typo super->sb in method toString() of RemoteStoreNodeAttribute
  CHANGELOG.md
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
Labels: backport 2.x

#15881 [Backport 2.x] Optimizing get indices to segments map calculations for IndicesSegmentResponse (#14717)
  server/src/main/java/org/opensearch/action/admin/indices/segments/IndicesSegmentResponse.java
  server/src/test/java/org/opensearch/action/admin/indices/segments/IndicesSegmentResponseTests.java
Labels: skip-changelog

#16392 Treat last fetch timestamp of pinned timestamp as one of the pinned timestamps
  server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
Labels: skip-changelog

#16398 BugFix - Extract snapshot UUID from pinned entity correctly
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/snapshots/SnapshotsServiceTests.java
Labels: skip-changelog

#16380 [Star tree] Handle delete cases for star tree
  server/src/main/java/org/apache/lucene/index/DocValuesProducerUtil.java
  server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesReader.java
  server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/StarTreeDocValuesFormatTests.java
Labels: bug, skip-changelog, Indexing:Performance

#16394 Snapshot _status API: Include in-progress snapshots in total shard count and index filter
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestSnapshotsStatusAction.java
Labels: skip-changelog

#15289 [Star Tree] [Search] Support for metric aggregations with/without term query
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DateDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/Dimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/NumericDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/ReadDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeQueryHelper.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/iterator/SortedNumericStarTreeValuesIterator.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/AggregatorFactories.java
  server/src/main/java/org/opensearch/search/aggregations/AggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/AvgAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/AvgAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MetricAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/SumAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/SumAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/ValueCountAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/ValueCountAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSourceAggregatorFactory.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/main/java/org/opensearch/search/startree/StarTreeFilter.java
  server/src/main/java/org/opensearch/search/startree/StarTreeQueryContext.java
  server/src/main/java/org/opensearch/search/startree/package-info.java
  server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/StarTreeFilterTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: backport 2.x, v2.18.0

#15938 URI path filtering support in cluster stats API
  CHANGELOG.md
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/ClusterStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIndices.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/index/cache/query/QueryCacheStats.java
  server/src/main/java/org/opensearch/index/fielddata/FieldDataStats.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsAction.java
  server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsResponseTests.java
  server/src/test/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsActionTests.java
Labels: backport 2.x

#16428 Fixing inline javadocs usage in PaginationStrategy
  server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java
Labels: bug, backport 2.x, skip-changelog, Other

#16106 Fix unclosed store references with SearchOnlyReplicaIT
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java
  server/src/main/java/org/opensearch/indices/replication/PrimaryShardReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceFactory.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicatorTests.java
Labels: >test-failure, flaky-test, backport 2.x, autocut, skip-changelog

#16426 Update JDK to 21.0.5
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: skip-changelog

#16429 Update JDK to 23.0.1
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
Labels: v3.0.0, skip-changelog

#16417 improve the rejection logic for wlm
  CHANGELOG.md
  server/src/main/java/org/opensearch/wlm/QueryGroupService.java
  server/src/test/java/org/opensearch/wlm/QueryGroupServiceTests.java
Labels: backport 2.x

#16422 Wlm create/update REST API bug fix
  CHANGELOG.md
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/CreateQueryGroupRequest.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportCreateQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/TransportUpdateQueryGroupAction.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/action/UpdateQueryGroupRequest.java
Labels: backport 2.x

#16347 Make multiple settings dynamic for tuning on larger clusters
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/ElectionSchedulerFactory.java
  server/src/main/java/org/opensearch/cluster/coordination/FollowersChecker.java
  server/src/main/java/org/opensearch/cluster/coordination/LagDetector.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationCheckerSettingsTests.java
  server/src/test/java/org/opensearch/cluster/coordination/LagDetectorTests.java
  server/src/test/java/org/opensearch/gateway/ShardsBatchGatewayAllocatorTests.java
Labels: backport 2.x, v2.18.0

#16292 Add new parameters to snapshot restore to rename the restored aliases…
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestBuilder.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequestTests.java
  server/src/test/java/org/opensearch/snapshots/RestoreServiceIntegTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotRequestsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, backport 2.x, Storage:Snapshots

#16430 Disallow snapshot deletion while a v2 snapshot is in progress
  server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsV2IT.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Labels: backport 2.x, skip-changelog

#16441 Downgrade version to 2.18.0 for ser/de of new ClusterStatsRequest met…
  qa/rolling-upgrade/src/test/java/org/opensearch/upgrades/ClusterStatsIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java
Labels: skip-changelog

#16294 Fix get index settings API doesn't show number_of_routing_shards when it was explicitly set on index creation
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_settings/40_number_of_routing_shards.yml
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: backport 2.x

#16437 Add log message if SSL dual mode is enabled
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SecureNetty4Transport.java
Labels: skip-changelog

#16434 Fix flaky test in testApproximateRangeWithSizeOverDefault by adjusting totalHits assertion logic
  CHANGELOG.md
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: backport 2.x

#16111 Add support for restoring from snapshot with search replicas
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaRestoreIT.java
  server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/cluster/routing/SearchOnlyReplicaRestoreTests.java
  server/src/test/java/org/opensearch/snapshots/RestoreServiceTests.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
Labels: backport 2.x, v2.18.0

#16455 Update version to 2.18.0 for CatShards request and response
  server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsResponse.java
  server/src/main/java/org/opensearch/action/pagination/PageParams.java
  server/src/test/java/org/opensearch/action/admin/cluster/shards/CatShardsRequestTests.java
Labels: skip-changelog

#16465 Update 2.x to 2.19.0 (since 2.18.0 was cut)
  .ci/bwcVersions
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#16466 [Forwardport] [main] Update 2.x to 2.19.0 (since 2.18.0 was cut)
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#16472 Downgrade version to 2.18.0 for ser/de of new parameters of RequestRequest
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
Labels: skip-changelog

#16403 Revert uploading of remote cluster state manifest using min codec version
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: bug, backport 2.x, skip-changelog

#16471 Add Setting to adjust the primary constraint weights
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationConstraints.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/Constraint.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/ConstraintTypes.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/RebalanceConstraints.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationConstraintsTests.java
Labels: bug, backport 2.x, ShardManagement:Placement

#16480 Update version check in yaml test file for the bug fix for get index settings API
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.get_settings/40_number_of_routing_shards.yml
Labels: skip-changelog

#16421 Add logic in master service to optimize performance and retain detailed logging for critical cluster operations.
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/cluster/service/TaskBatcher.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
Labels: skip-changelog

#16383 create publication repos during join task execution
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemotePublicationConfigurationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
Labels: skip-changelog

#16284 Switch from `buildSrc/version.properties` to Gradle version catalog (`gradle/libs.versions.toml`) to enable dependabot to perform automated upgrades on common libs
  CHANGELOG.md
  buildSrc/build.gradle
  buildSrc/settings.gradle
  buildSrc/version.properties
  gradle/libs.versions.toml
Labels: enhancement, CI, feature, cicd, backport 2.x

#16511 [FORWARDPORT main] Add 2.18 release notes
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.18.0.md
Labels: skip-changelog

#16521 Bump com.azure:azure-storage-common from 12.25.1 to 12.27.1
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-storage-common-12.25.1.jar.sha1
  plugins/repository-azure/licenses/azure-storage-common-12.27.1.jar.sha1
Labels: backport 2.x
