Repository opensearch-project/OpenSearch, pull requests merged in 2024-12, with the labels that each got.

#16712 Deprecate performing update operation with default pipeline or final pipeline
  CHANGELOG.md
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/75_update.yml
  server/src/main/java/org/opensearch/action/update/TransportUpdateAction.java
Labels: v3.0.0, backport 2.x, ingest-pipeline, v2.19.0

#16759 [Forwardport][main] Deprecate performing update operation with default pipeline or final pipeline
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/75_update.yml
Labels: skip-changelog

#16741 [Backport 2.x] - create publication repos during join task execution (#16383)
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemotePublicationConfigurationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
Labels: skip-changelog

#16764 Fix allowed_warnings takes no effect for the yaml test in 75_update.yml
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/75_update.yml
Labels: backport 2.x, skip-changelog

#16758 Update Jackson to 2.18.2
  CHANGELOG.md
  client/sniffer/licenses/jackson-core-2.17.2.jar.sha1
  client/sniffer/licenses/jackson-core-2.18.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.17.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.18.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.17.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.18.2.jar.sha1
  gradle/libs.versions.toml
  libs/arrow-spi/licenses/jackson-annotations-2.17.2.jar.sha1
  libs/arrow-spi/licenses/jackson-annotations-2.18.2.jar.sha1
  libs/arrow-spi/licenses/jackson-databind-2.17.2.jar.sha1
  libs/arrow-spi/licenses/jackson-databind-2.18.2.jar.sha1
  libs/core/licenses/jackson-core-2.17.2.jar.sha1
  libs/core/licenses/jackson-core-2.18.2.jar.sha1
  libs/x-content/licenses/jackson-core-2.17.2.jar.sha1
  libs/x-content/licenses/jackson-core-2.18.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.17.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.18.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.17.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.18.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.17.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.18.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.17.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.18.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.17.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.18.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.17.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.18.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.17.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.18.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.17.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.18.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.17.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.18.2.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.17.2.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.18.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.17.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.18.2.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.17.2.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.18.2.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.17.2.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.18.2.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.17.2.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.18.2.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.17.2.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.18.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.17.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.18.2.jar.sha1
  server/licenses/jackson-core-2.17.2.jar.sha1
  server/licenses/jackson-core-2.18.2.jar.sha1
  server/licenses/jackson-dataformat-cbor-2.17.2.jar.sha1
  server/licenses/jackson-dataformat-cbor-2.18.2.jar.sha1
  server/licenses/jackson-dataformat-smile-2.17.2.jar.sha1
  server/licenses/jackson-dataformat-smile-2.18.2.jar.sha1
  server/licenses/jackson-dataformat-yaml-2.17.2.jar.sha1
  server/licenses/jackson-dataformat-yaml-2.18.2.jar.sha1
Labels: dependencies, backport 2.x

#16644 Ensure consistency of system flag on IndexMetadata after diff is applied
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
Labels: bug, Plugins, backport 2.x

#16778 Bump com.azure:azure-identity from 1.13.2 to 1.14.2 in /plugins/repository-azure
  CHANGELOG.md
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/azure-identity-1.13.2.jar.sha1
  plugins/repository-azure/licenses/azure-identity-1.14.2.jar.sha1
  plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureStorageServiceTests.java
Labels: dependencies, backport 2.x

#16793 Refactor Docker Compose version detection to predictably pick v2 only if v1 is not available
  buildSrc/src/main/java/org/opensearch/gradle/docker/DockerSupportService.java
  buildSrc/src/main/java/org/opensearch/gradle/testfixtures/TestFixturesPlugin.java
Labels: backport 2.x, skip-changelog

#16789 Consolidate cleanup for Azure blob tests
  plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureBlobContainerRetriesTests.java
  plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureRepositorySettingsTests.java
  plugins/repository-azure/src/test/java/org/opensearch/repositories/azure/AzureStorageServiceTests.java
Labels: backport 2.x, skip-changelog

#16812 Overflow prevention when handling date values
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/time/DateUtils.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
Labels: backport 2.x

#16763 Skip remote-repositories validations for node-joins when RepositoriesService is not in sync with cluster-state
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/discovery/DiscoveryDisruptionIT.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: bug, backport 2.x, Cluster Manager, ClusterManager:RemoteState

#16824 Added release notes for 1.3.20
  release-notes/opensearch.release-notes-1.3.20.md
Labels: skip-changelog

#16825 Update opensearch.release-notes-1.3.20.md
  release-notes/opensearch.release-notes-1.3.20.md
Labels: skip-changelog

#16606 Fixing _list/shards API for closed indices
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/shards/TransportCatShardsActionIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/TransportCatShardsAction.java
Labels: bug, backport 2.x, Cluster Manager

#16678 Added support for search replica to return segrep stats
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaReplicationIT.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
  server/src/test/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsActionTests.java
Labels: backport 2.x, v2.19.0

#15335 Fix remote shards balance
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsRebalanceShardsTests.java
Labels: bug, stalled, backport 2.x, Search:Searchable Snapshots

#16831 Fix snapshot repository registration failure in mixed OpenSearch version setups
  server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: bug, skip-changelog, Storage:Snapshots

#16798 introduce a setting to disable download of full cluster state from remote on term mismatch
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/support/clustermanager/term/TransportGetTermVersionAction.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
Labels: backport 2.x, Cluster Manager

#16846 Update Apache Lucene to 9.12.1
  CHANGELOG.md
  gradle/libs.versions.toml
  libs/core/licenses/lucene-core-9.12.0.jar.sha1
  libs/core/licenses/lucene-core-9.12.1.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.12.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.12.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.12.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.12.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.12.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.12.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.12.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.12.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.12.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.12.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.12.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.12.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.12.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.12.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.12.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.12.1.jar.sha1
  server/licenses/lucene-analysis-common-9.12.0.jar.sha1
  server/licenses/lucene-analysis-common-9.12.1.jar.sha1
  server/licenses/lucene-backward-codecs-9.12.0.jar.sha1
  server/licenses/lucene-backward-codecs-9.12.1.jar.sha1
  server/licenses/lucene-core-9.12.0.jar.sha1
  server/licenses/lucene-core-9.12.1.jar.sha1
  server/licenses/lucene-grouping-9.12.0.jar.sha1
  server/licenses/lucene-grouping-9.12.1.jar.sha1
  server/licenses/lucene-highlighter-9.12.0.jar.sha1
  server/licenses/lucene-highlighter-9.12.1.jar.sha1
  server/licenses/lucene-join-9.12.0.jar.sha1
  server/licenses/lucene-join-9.12.1.jar.sha1
  server/licenses/lucene-memory-9.12.0.jar.sha1
  server/licenses/lucene-memory-9.12.1.jar.sha1
  server/licenses/lucene-misc-9.12.0.jar.sha1
  server/licenses/lucene-misc-9.12.1.jar.sha1
  server/licenses/lucene-queries-9.12.0.jar.sha1
  server/licenses/lucene-queries-9.12.1.jar.sha1
  server/licenses/lucene-queryparser-9.12.0.jar.sha1
  server/licenses/lucene-queryparser-9.12.1.jar.sha1
  server/licenses/lucene-sandbox-9.12.0.jar.sha1
  server/licenses/lucene-sandbox-9.12.1.jar.sha1
  server/licenses/lucene-spatial-extras-9.12.0.jar.sha1
  server/licenses/lucene-spatial-extras-9.12.1.jar.sha1
  server/licenses/lucene-spatial3d-9.12.0.jar.sha1
  server/licenses/lucene-spatial3d-9.12.1.jar.sha1
  server/licenses/lucene-suggest-9.12.0.jar.sha1
  server/licenses/lucene-suggest-9.12.1.jar.sha1
Labels: dependencies, backport 2.x, backport 2.18

#16849 Handle version during repository registration for prefix mode verification
  server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: skip-changelog

#16850 Change Remote state read thread pool to Fixed type
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: skip-changelog

#16876 [Forward] [2.x] Update Apache Lucene to 9.12.1 for 2.18.1 (#16846) (#16870)
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#16877 [Forwardport] [main] Update Apache Lucene to 9.12.1 for 2.x and 2.18.1 (#16846) (#16870)
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#16641 Changes to support IP field in star tree indexing
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/IpDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/OrdinalDimension.java
  server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/StarTreeKeywordDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderFlushFlowTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderMergeFlowTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderTestCase.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: enhancement, skip-changelog, Indexing:Performance

#16879 [Backport 2.x] Change Remote state read thread pool to Fixed type (#16850)
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: skip-changelog

#16885 Remove the events-correlation-engine plugin
  gradle/missing-javadoc.gradle
  plugins/events-correlation-engine/build.gradle
  plugins/events-correlation-engine/src/internalClusterTest/java/org/opensearch/plugin/correlation/EventsCorrelationPluginTransportIT.java
  plugins/events-correlation-engine/src/javaRestTest/java/org/opensearch/plugin/correlation/CorrelationVectorsEngineIT.java
  plugins/events-correlation-engine/src/javaRestTest/java/org/opensearch/plugin/correlation/EventsCorrelationPluginRestIT.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/EventsCorrelationPlugin.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/CorrelationParamsContext.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/VectorField.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/BasePerFieldCorrelationVectorsFormat.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/CorrelationCodecService.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/CorrelationCodecVersion.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/correlation990/CorrelationCodec.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/correlation990/PerFieldCorrelationVectorsFormat.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/correlation990/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/codec/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/mapper/CorrelationVectorFieldMapper.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/mapper/VectorFieldMapper.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/mapper/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/query/CorrelationQueryBuilder.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/query/CorrelationQueryFactory.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/core/index/query/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/action/IndexCorrelationRuleAction.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/action/IndexCorrelationRuleRequest.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/action/IndexCorrelationRuleResponse.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/action/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/model/CorrelationQuery.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/model/CorrelationRule.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/model/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/resthandler/RestIndexCorrelationRuleAction.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/resthandler/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/transport/TransportIndexCorrelationRuleAction.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/rules/transport/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/settings/EventsCorrelationSettings.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/settings/package-info.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/utils/CorrelationRuleIndices.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/utils/IndexUtils.java
  plugins/events-correlation-engine/src/main/java/org/opensearch/plugin/correlation/utils/package-info.java
  plugins/events-correlation-engine/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec
  plugins/events-correlation-engine/src/main/resources/mappings/correlation-rules.json
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/EventsCorrelationPluginTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/CorrelationParamsContextTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/VectorFieldTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/codec/correlation990/CorrelationCodecTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/mapper/CorrelationVectorFieldMapperTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/core/index/query/CorrelationQueryBuilderTests.java
  plugins/events-correlation-engine/src/test/java/org/opensearch/plugin/correlation/settings/EventsCorrelationSettingsTests.java
Labels: enhancement, RFC, skip-changelog, Roadmap:Security Analytics

#16828 [Flaky Test] Fix Flaky Test SearchTimeoutIT.testSimpleTimeout
  server/src/internalClusterTest/java/org/opensearch/search/SearchTimeoutIT.java
Labels: >test-failure, flaky-test, backport 2.x, autocut

#16844 Create sub directories for ThirdPartyAudit dependency metadata
  buildSrc/src/main/java/org/opensearch/gradle/precommit/ThirdPartyAuditTask.java
Labels: bug, backport 2.x, skip-changelog, Build

#16802 Retrieve value from DocValues in a flat_object filed
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml
  server/src/internalClusterTest/java/org/opensearch/search/fields/SearchFieldsIT.java
  server/src/main/java/org/opensearch/index/mapper/DocValueFetcher.java
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
Labels: enhancement, backport 2.x, Indexing, Storage:Performance

#16534 Experimental gRPC transport plugin
  CHANGELOG.md
  gradle/libs.versions.toml
  plugins/discovery-gce/licenses/grpc-api-1.68.0.jar.sha1
  plugins/discovery-gce/licenses/grpc-api-1.68.2.jar.sha1
  plugins/repository-gcs/licenses/grpc-api-1.68.0.jar.sha1
  plugins/repository-gcs/licenses/grpc-api-1.68.2.jar.sha1
  plugins/transport-grpc/build.gradle
  plugins/transport-grpc/licenses/error_prone_annotations-2.24.1.jar.sha1
  plugins/transport-grpc/licenses/error_prone_annotations-LICENSE.txt
  plugins/transport-grpc/licenses/error_prone_annotations-NOTICE.txt
  plugins/transport-grpc/licenses/failureaccess-1.0.1.jar.sha1
  plugins/transport-grpc/licenses/failureaccess-LICENSE.txt
  plugins/transport-grpc/licenses/failureaccess-NOTICE.txt
  plugins/transport-grpc/licenses/grpc-LICENSE.txt
  plugins/transport-grpc/licenses/grpc-NOTICE.txt
  plugins/transport-grpc/licenses/grpc-api-1.68.2.jar.sha1
  plugins/transport-grpc/licenses/grpc-core-1.68.2.jar.sha1
  plugins/transport-grpc/licenses/grpc-netty-shaded-1.68.2.jar.sha1
  plugins/transport-grpc/licenses/grpc-protobuf-1.68.2.jar.sha1
  plugins/transport-grpc/licenses/grpc-protobuf-lite-1.68.2.jar.sha1
  plugins/transport-grpc/licenses/grpc-services-1.68.2.jar.sha1
  plugins/transport-grpc/licenses/grpc-stub-1.68.2.jar.sha1
  plugins/transport-grpc/licenses/grpc-util-1.68.2.jar.sha1
  plugins/transport-grpc/licenses/guava-33.2.1-jre.jar.sha1
  plugins/transport-grpc/licenses/guava-LICENSE.txt
  plugins/transport-grpc/licenses/guava-NOTICE.txt
  plugins/transport-grpc/licenses/perfmark-api-0.26.0.jar.sha1
  plugins/transport-grpc/licenses/perfmark-api-LICENSE.txt
  plugins/transport-grpc/licenses/perfmark-api-NOTICE.txt
  plugins/transport-grpc/src/main/java/org/opensearch/transport/grpc/GrpcPlugin.java
  plugins/transport-grpc/src/main/java/org/opensearch/transport/grpc/Netty4GrpcServerTransport.java
  plugins/transport-grpc/src/main/java/org/opensearch/transport/grpc/package-info.java
  plugins/transport-grpc/src/main/plugin-metadata/plugin-security.policy
  plugins/transport-grpc/src/test/java/org/opensearch/transport/grpc/Netty4GrpcServerTransportTests.java
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/main/java/org/opensearch/common/network/NetworkModule.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/http/AbstractHttpServerTransport.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/NetworkPlugin.java
  server/src/main/java/org/opensearch/transport/TcpTransport.java
  server/src/main/java/org/opensearch/transport/Transport.java
  server/src/test/java/org/opensearch/http/AbstractHttpServerTransportTests.java
  server/src/test/java/org/opensearch/transport/PublishPortTests.java
Labels: backport 2.x
