Repository opensearch-project/OpenSearch, pull requests merged in 2024-03, with the labels that each got.

#12511 [Backport 1.3] Release notes for 1.3.15
  CHANGELOG.md
  release-notes/opensearch.release-notes-1.3.15.md
Labels: skip-changelog

#12510 Add release notes for 1.3.15
  release-notes/opensearch.release-notes-1.3.15.md
Labels: backport 1.x, skip-changelog

#12512 Increase suite timeout for HighlighterSearchIT
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
Labels: flaky-test, backport 2.x, skip-changelog, Search

#12523 Clean up release notes for 1.3.15
  release-notes/opensearch.release-notes-1.3.15.md
Labels: backport 1.x, backport 1.3, skip-changelog

#12287 Add kuromoji_completion analyzer and filter (#4835)
  CHANGELOG.md
  plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiCompletionAnalyzerProvider.java
  plugins/analysis-kuromoji/src/main/java/org/opensearch/index/analysis/KuromojiCompletionFilterFactory.java
  plugins/analysis-kuromoji/src/main/java/org/opensearch/plugin/analysis/kuromoji/AnalysisKuromojiPlugin.java
  plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/AnalysisKuromojiFactoryTests.java
  plugins/analysis-kuromoji/src/test/java/org/opensearch/index/analysis/KuromojiAnalysisTests.java
  plugins/analysis-kuromoji/src/test/resources/org/opensearch/index/analysis/kuromoji_analysis.json
  plugins/analysis-kuromoji/src/yamlRestTest/resources/rest-api-spec/test/analysis_kuromoji/10_basic.yml
Labels: enhancement, feature, Plugins

#12550 Moving maintainer kartg to Emeritus
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#12564 Fixing IoUsage Stats Version Check After Backport
  server/src/main/java/org/opensearch/node/NodeResourceUsageStats.java
Labels: skip-changelog

#12557 Update feature_request.yml to support Shard Management
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: skip-changelog

#12499 Fix issue with float field terms query
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
Labels: bug, Search

#12565 [Remote Store] Add check for byte lag in time lag calculation
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePressureServiceTests.java
Labels: skip-changelog, Storage:Remote

#12441 Abstract AsyncShardFetch cache to allow restructuring for other caching strategies
  server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java
  server/src/main/java/org/opensearch/gateway/AsyncShardFetchCache.java
Labels: skip-changelog, Cluster Manager

#12158 onShardResult and onShardFailure are executed on one shard causes opensearch jvm crashed
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: bug, Severity-Major, Search, v2.13.0

#12533 [Tiered caching] Integrating IndicesRequestCache with CacheService controlled by a feature flag
  CHANGELOG.md
  distribution/src/config/opensearch.yml
  modules/cache-common/build.gradle
  modules/cache-common/src/internalClusterTest/java/org.opensearch.cache.common.tier/TieredSpilloverCacheIT.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  plugins/cache-ehcache/src/internalClusterTest/java/org/opensearch/cache/EhcacheDiskCacheIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/common/cache/service/CacheService.java
  server/src/main/java/org/opensearch/common/cache/settings/CacheSettings.java
  server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java
  server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
  server/src/main/java/org/opensearch/common/cache/store/settings/OpenSearchOnHeapCacheSettings.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/common/cache/service/CacheServiceTests.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: backport 2.x

#12599 [Forwardport 2.x] Added bwc version 1.3.16
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#12586 The org.opensearch.bootstrap.Security should support codebase for JAR files with classifiers
  CHANGELOG.md
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/test/java/org/opensearch/bootstrap/SecurityTests.java
  server/src/test/resources/org/opensearch/bootstrap/test-codebases.policy
  server/src/test/resources/org/opensearch/bootstrap/test.policy
Labels: enhancement, v3.0.0, v2.13.0, Other

#12543 Fix PluginInfo bwc for opensearch_version field
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
  server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
Labels: bug, Plugins, backport 2.x, skip-changelog, v2.13.0

#12613 [Backport] [2.x] The org.opensearch.bootstrap.Security should support codebase for JAR files with classifiers (#12586)
  CHANGELOG.md
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/test/java/org/opensearch/bootstrap/SecurityTests.java
  server/src/test/resources/org/opensearch/bootstrap/test-codebases.policy
  server/src/test/resources/org/opensearch/bootstrap/test.policy
Labels: enhancement, v2.13.0

#12618 Bump opentelemetry from 1.35.0 to 1.36.0
  CHANGELOG.md
  buildSrc/version.properties
  plugins/telemetry-otel/licenses/opentelemetry-api-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-extension-incubator-1.35.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-extension-incubator-1.36.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.36.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.35.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.36.0.jar.sha1
Labels: dependencies

#12614 [Backport] [2.x] Bump up jackson version to 2.16.2 (#12611)
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.16.1.jar.sha1
  client/sniffer/licenses/jackson-core-2.16.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.16.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.16.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.16.1.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.16.2.jar.sha1
  libs/core/licenses/jackson-core-2.16.1.jar.sha1
  libs/core/licenses/jackson-core-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-core-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-core-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.16.1.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.16.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.16.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.16.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.16.1.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.16.1.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.16.2.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.16.1.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.16.1.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.16.2.jar.sha1
Labels: dependencies

#12562 Mute flaky test testMultiGetWithNetworkDisruption_FailOpenEnabled
  server/src/internalClusterTest/java/org/opensearch/search/SearchWeightedRoutingIT.java
Labels: backport 2.x, skip-changelog

#11643 Improve string terms aggregation performance using Collector#setWeight
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/KeywordTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, Search:Performance, v2.13.0

#12561 Remote reindex: Add support for configurable retry mechanism
  CHANGELOG.md
  modules/reindex/src/main/java/org/opensearch/index/reindex/ReindexModulePlugin.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/TransportReindexAction.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/remote/RemoteScrollableHitSource.java
  modules/reindex/src/test/java/org/opensearch/index/reindex/remote/RemoteScrollableHitSourceTests.java
  server/src/main/java/org/opensearch/index/reindex/RetryListener.java
Labels: enhancement, Indexing

#12616 Remove duplicated assert in test
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
Labels: skip-changelog

#12103 Tracing for deep search path
  CHANGELOG.md
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanContext.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/tracing/SpanCreationContext.java
  plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/CanMatchPreFilterSearchPhase.java
  server/src/main/java/org/opensearch/action/search/SearchDfsQueryThenFetchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/SearchQueryThenFetchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/SearchRequestContext.java
  server/src/main/java/org/opensearch/action/search/SearchRequestOperationsListener.java
  server/src/main/java/org/opensearch/action/search/SearchRequestSlowLog.java
  server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/telemetry/tracing/AttributeNames.java
  server/src/main/java/org/opensearch/telemetry/tracing/SpanBuilder.java
  server/src/main/java/org/opensearch/telemetry/tracing/listener/TraceableSearchRequestOperationsListener.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/CanMatchPreFilterSearchPhaseTests.java
  server/src/test/java/org/opensearch/action/search/SearchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/SearchQueryThenFetchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsCompositeListenerFactoryTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerAssertingListener.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestStatsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  server/src/test/java/org/opensearch/telemetry/tracing/SpanBuilderTests.java
Labels: enhancement, backport 2.x, Search

#12643 Add no merge policy in test to avoid index merge
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
Labels: bug, flaky-test, skip-changelog

#12487 [Remote Store] Add support for Running Parameterized Remote Store Enabled Integration Tests
  server/src/internalClusterTest/java/org/opensearch/indices/store/IndicesStoreIntegrationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/ParameterizedStaticSettingsOpenSearchIntegTestCase.java
Labels: backport 2.x, skip-changelog

#12636 [Backport] [2.x] Bump reactor and reactor-netty dependencies (#12633)
  CHANGELOG.md
  buildSrc/version.properties
  plugins/repository-azure/licenses/reactor-netty-core-1.1.15.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.17.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.15.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.17.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.15.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.17.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.15.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.17.jar.sha1
  server/licenses/reactor-core-3.5.14.jar.sha1
  server/licenses/reactor-core-3.5.15.jar.sha1
Labels: dependencies

#12629 [Backport 2.x] Improve string terms aggregation performance using Collector#setWeight
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSource.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/KeywordTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: backport

#12601 Make search query counters dynamic to support all query types
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchQueryCounters.java
  server/src/test/java/org/opensearch/action/search/SearchQueryCategorizerTests.java
Labels: enhancement, good first issue, help wanted, Plugins, Search

#12503 Removing unused fetch sub phase processor initialization during fetch…
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/fetch/FetchContext.java
  server/src/main/java/org/opensearch/search/fetch/subphase/InnerHitsContext.java
  server/src/main/java/org/opensearch/search/fetch/subphase/InnerHitsPhase.java
  server/src/main/java/org/opensearch/search/fetch/subphase/ScriptFieldsPhase.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/search/fetch/subphase/InnerHitsPhaseTests.java
  server/src/test/java/org/opensearch/search/fetch/subphase/ScriptFieldsPhaseTests.java
Labels: bug, v3.0.0, Search:Performance, v2.13.0

#12319 Optimize remote store operations during snapshot Deletion
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/repositories/blobstore/RemoteStoreShardCleanupTask.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Labels: skip-changelog, Storage:Snapshots, v2.13.0

#8356 Add batch async shard fetch transport action for replica #8218
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataHelper.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardAllocatorTests.java
  server/src/test/java/org/opensearch/index/store/StoreTests.java
Labels: skip-changelog

#10254 Refactored the RSA to make it more extensible
  server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java
Labels: bug, skip-changelog, Cluster Manager

#12662 Bump Jackson version from 2.16.2 to 2.17.0
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.16.2.jar.sha1
  client/sniffer/licenses/jackson-core-2.17.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.16.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.17.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.16.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.17.0.jar.sha1
  libs/core/licenses/jackson-core-2.16.2.jar.sha1
  libs/core/licenses/jackson-core-2.17.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-core-2.17.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.17.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.17.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.17.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.16.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.17.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.16.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.17.0.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.17.0.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.17.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.17.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.17.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.17.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.17.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.17.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.17.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.17.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.17.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.17.0.jar.sha1
Labels: dependencies

#12650 [Tiered Caching] Fixing flaky tiered cache test
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
Labels: bug, flaky-test, skip-changelog, Search:Performance

#12668 [Backport] [2.x] Bump Jackson version from 2.16.2 to 2.17.0 (#12662)
  CHANGELOG.md
  buildSrc/version.properties
  client/sniffer/licenses/jackson-core-2.16.2.jar.sha1
  client/sniffer/licenses/jackson-core-2.17.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.16.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.17.0.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.16.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.17.0.jar.sha1
  libs/core/licenses/jackson-core-2.16.2.jar.sha1
  libs/core/licenses/jackson-core-2.17.0.jar.sha1
  libs/x-content/licenses/jackson-core-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-core-2.17.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-cbor-2.17.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-smile-2.17.0.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.16.2.jar.sha1
  libs/x-content/licenses/jackson-dataformat-yaml-2.17.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.16.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-annotations-2.17.0.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.16.2.jar.sha1
  modules/ingest-geoip/licenses/jackson-databind-2.17.0.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-annotations-2.17.0.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/crypto-kms/licenses/jackson-databind-2.17.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-annotations-2.17.0.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/discovery-ec2/licenses/jackson-databind-2.17.0.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-annotations-2.17.0.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-databind-2.17.0.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-dataformat-xml-2.17.0.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-datatype-jsr310-2.17.0.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.16.2.jar.sha1
  plugins/repository-azure/licenses/jackson-module-jaxb-annotations-2.17.0.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.16.2.jar.sha1
  plugins/repository-s3/licenses/jackson-annotations-2.17.0.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.16.2.jar.sha1
  plugins/repository-s3/licenses/jackson-databind-2.17.0.jar.sha1
Labels: dependencies

#12654 [Backport 2.x] Removing unused fetch sub phase processor initialization during fetch…
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/fetch/FetchContext.java
  server/src/main/java/org/opensearch/search/fetch/subphase/InnerHitsContext.java
  server/src/main/java/org/opensearch/search/fetch/subphase/InnerHitsPhase.java
  server/src/main/java/org/opensearch/search/fetch/subphase/ScriptFieldsPhase.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/search/fetch/subphase/InnerHitsPhaseTests.java
  server/src/test/java/org/opensearch/search/fetch/subphase/ScriptFieldsPhaseTests.java
Labels: bug, v3.0.0, Search:Performance, v2.13.0

#12679 [Backport 2.x] [Tiered Caching] Fixing flaky tiered cache test (#12650)
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
Labels: skip-changelog

#12676 Avoid overflow when sorting missing last on epoch_millis datetime field
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/time/EpochTime.java
  server/src/test/java/org/opensearch/common/time/DateFormattersTests.java
Labels: bug, good first issue, backport 2.x, Search:Query Capabilities, Search:Relevance

#12672 Simplify remote directory cleanup after snapshot delete to …
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/repositories/blobstore/RemoteStoreShardCleanupTask.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Labels: skip-changelog, Storage:Snapshots

#12577 handle unexpected exception on success callback of translog upload
  server/src/main/java/org/opensearch/index/translog/transfer/FileTransferTracker.java
  server/src/test/java/org/opensearch/index/translog/transfer/FileTransferTrackerTests.java
Labels: skip-changelog

#8776 BaseGatewayShardAllocator changes for Assigning the batch of shards
  server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
Labels: skip-changelog, Cluster Manager

#12505 Add allocation decider for mixed cluster
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/RemoteStoreMigrationAllocationDecider.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteStoreMigrationAllocationDeciderTests.java
Labels: skip-changelog

#12642 Adds support for asynchronous gauge metric type
  CHANGELOG.md
  libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/DefaultMetricsRegistry.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/MetricsRegistry.java
  libs/telemetry/src/main/java/org/opensearch/telemetry/metrics/noop/NoopMetricsRegistry.java
  libs/telemetry/src/test/java/org/opensearch/telemetry/metrics/DefaultMetricsRegistryTests.java
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/metrics/TelemetryMetricsEnabledSanityIT.java
  plugins/telemetry-otel/src/main/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetry.java
  plugins/telemetry-otel/src/test/java/org/opensearch/telemetry/metrics/OTelMetricsTelemetryTests.java
  test/framework/src/main/java/org/opensearch/test/telemetry/MockTelemetry.java
Labels: enhancement, Other, Telemetry:Metrics

#12542 [Tiered Caching] Cache tier policies
  CHANGELOG.md
  modules/cache-common/src/main/java/org/opensearch/cache/common/policy/TookTimePolicy.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/policy/package-info.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/policy/TookTimePolicyTests.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  server/src/main/java/org/opensearch/common/cache/policy/CachedQueryResult.java
  server/src/main/java/org/opensearch/common/cache/policy/package-info.java
  server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
Labels: backport 2.x

#12653 [Tiered caching] Supporting removal function on EhcacheDiskCache iterator
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
Labels: bug, backport 2.x, skip-changelog, Search:Performance

#12701 [Bug Fix] Fix issue where wrong shard blob files are picked up for del…
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: skip-changelog

#12625 [Tiered Caching] Indices Request cache stalekey management
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: backport 2.x

#11858 Decouple remote state configuration
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: skip-changelog, Cluster Manager

#12709 [Tiered Caching] Serializers for ehcache
  CHANGELOG.md
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  server/src/main/java/org/opensearch/common/cache/serializer/BytesReferenceSerializer.java
  server/src/main/java/org/opensearch/common/cache/serializer/Serializer.java
  server/src/main/java/org/opensearch/common/cache/serializer/package-info.java
  server/src/main/java/org/opensearch/common/cache/store/config/CacheConfig.java
  server/src/main/java/org/opensearch/indices/IRCKeyWriteableSerializer.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/common/cache/serializer/BytesReferenceSerializerTests.java
  server/src/test/java/org/opensearch/indices/IRCKeyWriteableSerializerTests.java
Labels: backport 2.x, v2.13.0

#12695 Fix flaky test SegmentReplicationWithNodeToNodeIndexShardTests#testReplicaClosesWhileReplicating_AfterGetCheckpoint
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationWithNodeToNodeIndexShardTests.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Indexing:Replication

#8916 Add PrimaryShardBatchAllocator to take allocation decisions for a batch of shards
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/main/java/org/opensearch/action/admin/indices/shards/TransportIndicesShardStoresAction.java
  server/src/main/java/org/opensearch/gateway/PrimaryShardAllocator.java
  server/src/main/java/org/opensearch/gateway/PrimaryShardBatchAllocator.java
  server/src/main/java/org/opensearch/gateway/TransportNodesGatewayStartedShardHelper.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShardsBatch.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestGatewayAllocator.java
Labels: bug, skip-changelog, Cluster Manager

#12745 Fixes flaky test org.opensearch.telemetry.metrics.TelemetryMetricsEna…
  plugins/telemetry-otel/src/internalClusterTest/java/org/opensearch/telemetry/metrics/TelemetryMetricsEnabledSanityIT.java
Labels: bug, Plugins, flaky-test, skip-changelog

#12700 [Tiered Caching] Fix test testComputeIfAbsentWithFactoryBasedCacheCreation
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
Labels: bug, backport 2.x, skip-changelog, Search:Performance

#12734 [Tiered Caching] Clear up disk cache(ehcache) files during node shutdown
  libs/core/src/main/java/org/opensearch/core/common/bytes/BytesReference.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  server/src/main/java/org/opensearch/common/cache/serializer/BytesReferenceSerializer.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
Labels: backport 2.x, skip-changelog

#12607 Introduce remote store path type in customData in IndexMetadata
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathResolver.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathType.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: enhancement, skip-changelog, Storage:Performance, v2.14.0

#12751 [Remote Store] Introducing mixed mode support for remote store migrat…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotemigration/DocRepMigrationTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeService.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
Labels: enhancement, Storage:Durability, Storage:Remote

#12720 Bump mockito & bytebuddy dependencies
  buildSrc/version.properties
  server/src/test/java/org/opensearch/transport/RemoteClusterClientTests.java
Labels: skip-changelog

#11699 Election scheduler should be cancelled after cluster state publication
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinatorTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
Labels: Cluster Manager

#12760 [Backport 2.x][Tiered Caching] Clear up disk cache(ehcache) files during node shutdown
  libs/core/src/main/java/org/opensearch/core/common/bytes/BytesReference.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  server/src/main/java/org/opensearch/common/cache/serializer/BytesReferenceSerializer.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
Labels: skip-changelog

#12761 Abstract AsyncShardFetch cache to allow restructuring for other cachi…
  server/src/main/java/org/opensearch/gateway/AsyncShardFetch.java
  server/src/main/java/org/opensearch/gateway/AsyncShardFetchCache.java
Labels: skip-changelog

#12770 Add batch async shard fetch transport action for replica #8218 (#8356)
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java
  server/src/main/java/org/opensearch/indices/IndicesModule.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataHelper.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardAllocatorTests.java
  server/src/test/java/org/opensearch/index/store/StoreTests.java
Labels: skip-changelog, v2.13.0

#12764 Fixing ehcache flaky test
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhcacheThreadLeakFilter.java
Labels: skip-changelog

#12657 Update supported version for the primary_only parameter in force-merge API
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.forcemerge/20_wait_for_completion.yml
  server/src/main/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeRequest.java
  server/src/test/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeRequestTests.java
Labels: skip-changelog

#12783 Fixing flaky test GeoPointShapeQueryTests.testQueryLinearRing
  server/src/test/java/org/opensearch/search/geo/GeoPointShapeQueryTests.java
Labels: bug, flaky-test, Geospatial, skip-changelog, Search

#12710 Added static setting for checkPendingFlushUpdate functionality of lucene index writer
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
Labels: enhancement, Indexing:Performance

#12435 [FEATURE] Built-in secure transports support
  CHANGELOG.md
  modules/transport-netty4/src/main/java/org/opensearch/http/netty4/ssl/SecureNetty4HttpServerTransport.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4ModulePlugin.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/DualModeSslHandler.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SecureConnectionTestUtil.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SecureNetty4Transport.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SslUtils.java
  modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpClient.java
  modules/transport-netty4/src/test/java/org/opensearch/http/netty4/ssl/SecureNetty4HttpServerTransportTests.java
  modules/transport-netty4/src/test/java/org/opensearch/transport/netty4/ssl/SimpleSecureNetty4TransportTests.java
  modules/transport-netty4/src/test/java/org/opensearch/transport/netty4/ssl/TrustAllManager.java
  modules/transport-netty4/src/test/resources/README.txt
  modules/transport-netty4/src/test/resources/certificate.crt
  modules/transport-netty4/src/test/resources/certificate.key
  modules/transport-netty4/src/test/resources/netty4-secure.jks
  server/src/main/java/org/opensearch/common/network/NetworkModule.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/NetworkPlugin.java
  server/src/main/java/org/opensearch/plugins/Plugin.java
  server/src/main/java/org/opensearch/plugins/SecureSettingsFactory.java
  server/src/main/java/org/opensearch/plugins/SecureTransportSettingsProvider.java
  server/src/test/java/org/opensearch/common/network/NetworkModuleTests.java
Labels: enhancement, Plugins, v3.0.0, v2.13.0

#12789 [Backport] [2.x] [FEATURE] Built-in secure transports support (#12435)
  CHANGELOG.md
  modules/transport-netty4/src/main/java/org/opensearch/http/netty4/ssl/SecureNetty4HttpServerTransport.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/Netty4Plugin.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/DualModeSslHandler.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SecureConnectionTestUtil.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SecureNetty4Transport.java
  modules/transport-netty4/src/main/java/org/opensearch/transport/netty4/ssl/SslUtils.java
  modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpClient.java
  modules/transport-netty4/src/test/java/org/opensearch/http/netty4/ssl/SecureNetty4HttpServerTransportTests.java
  modules/transport-netty4/src/test/java/org/opensearch/transport/netty4/ssl/SimpleSecureNetty4TransportTests.java
  modules/transport-netty4/src/test/java/org/opensearch/transport/netty4/ssl/TrustAllManager.java
  modules/transport-netty4/src/test/resources/README.txt
  modules/transport-netty4/src/test/resources/certificate.crt
  modules/transport-netty4/src/test/resources/certificate.key
  modules/transport-netty4/src/test/resources/netty4-secure.jks
  server/src/main/java/org/opensearch/common/network/NetworkModule.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/NetworkPlugin.java
  server/src/main/java/org/opensearch/plugins/Plugin.java
  server/src/main/java/org/opensearch/plugins/SecureSettingsFactory.java
  server/src/main/java/org/opensearch/plugins/SecureTransportSettingsProvider.java
  server/src/test/java/org/opensearch/common/network/NetworkModuleTests.java
Labels: backport

#12778 Fix test bwcSerialization issue in ForceMergeRequestTests
  server/src/test/java/org/opensearch/action/admin/indices/forcemerge/ForceMergeRequestTests.java
Labels: skip-changelog

#8992 Created new ReplicaShardBatchAllocator
  server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
Labels: enhancement, skip-changelog, Cluster Manager, v2.13.0

#12793 [Backport] [2.x] Bump org.apache.commons:commons-configuration2 from 2.9.0 to 2.10.0 in /plugins/repository-hdfs (#12721)
  CHANGELOG.md
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/commons-configuration2-2.10.0.jar.sha1
  plugins/repository-hdfs/licenses/commons-configuration2-2.8.0.jar.sha1
Labels: backport

#12252 Light weight Transport action to verify local term before fetching cluster-state from remote
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/state/FetchByTermVersionIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/TransportGetTermVersionAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/package-info.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/cluster/coordination/ClusterStateTermVersion.java
  server/src/test/java/org/opensearch/action/admin/cluster/state/term/ClusterTermVersionIT.java
  server/src/test/java/org/opensearch/action/admin/cluster/state/term/ClusterTermVersionTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerTermCheckTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, backport 2.x, Cluster Manager, v2.13.0

#12804 [Backport] [2.x] Bump com.google.api.grpc:proto-google-common-protos from 2.33.0 to 2.34.0 in /plugins/repository-gcs (#12365)
  CHANGELOG.md
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/proto-google-common-protos-2.25.1.jar.sha1
  plugins/repository-gcs/licenses/proto-google-common-protos-2.37.1.jar.sha1
Labels: backport

#12494 [Remote Migration] Changes for Primary Relocation during migration
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreStatsTrackerFactory.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/recovery/MultiFileWriter.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoverySourceService.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandlerFactory.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  server/src/test/java/org/opensearch/index/replication/IndexLevelReplicationTests.java
  server/src/test/java/org/opensearch/index/replication/RecoveryDuringReplicationTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/indices/IndicesLifecycleListenerSingleNodeTests.java
  server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
  server/src/test/java/org/opensearch/recovery/ReplicationCollectionTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: enhancement, Storage:Durability, skip-changelog

#12819 Update supported version for the wait_for_completion parameter in open&clone&shrink&split APIs
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/40_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.open/30_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/50_wait_for_completion.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/40_wait_for_completion.yml
Labels: skip-changelog

#12824 Light weight Transport action to verify local term before fetching cl…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/state/FetchByTermVersionIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/TransportGetTermVersionAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/package-info.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/cluster/coordination/ClusterStateTermVersion.java
  server/src/test/java/org/opensearch/action/admin/cluster/state/term/ClusterTermVersionIT.java
  server/src/test/java/org/opensearch/action/admin/cluster/state/term/ClusterTermVersionTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerTermCheckTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, Cluster Manager

#12575 Fix Flaky SimpleQueryStringIT Tests
  server/src/internalClusterTest/java/org/opensearch/search/query/SimpleQueryStringIT.java
Labels: bug, flaky-test, skip-changelog, Search

#12825 Light weight Transport action to verify local term before fetching cl…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/state/FetchByTermVersionIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/GetTermVersionResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/TransportGetTermVersionAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/term/package-info.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/cluster/coordination/ClusterStateTermVersion.java
  server/src/test/java/org/opensearch/action/admin/cluster/state/term/ClusterTermVersionIT.java
  server/src/test/java/org/opensearch/action/admin/cluster/state/term/ClusterTermVersionTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerTermCheckTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, Cluster Manager

#12829 Integrate with CPU admission controller for cluster-manager Read API'…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionForClusterManagerIT.java
  server/src/main/java/org/opensearch/action/support/HandledTransportAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeReadAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/ratelimitting/admissioncontrol/controllers/CpuBasedAdmissionController.java
  server/src/main/java/org/opensearch/ratelimitting/admissioncontrol/controllers/IoBasedAdmissionController.java
  server/src/main/java/org/opensearch/ratelimitting/admissioncontrol/enums/AdmissionControlActionType.java
  server/src/main/java/org/opensearch/ratelimitting/admissioncontrol/settings/CpuBasedAdmissionControllerSettings.java
  server/src/main/java/org/opensearch/ratelimitting/admissioncontrol/settings/IoBasedAdmissionControllerSettings.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/settings/CPUBasedAdmissionControllerSettingsTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/settings/IoBasedAdmissionControllerSettingsTests.java
Labels: enhancement, discuss, idea, distributed framework, RFC

#12830 Update the version for local term fetch to 2.13
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
Labels: enhancement, skip-changelog, Cluster Manager

#12832 Integrate with CPU admission controller for cluster-manager Read API'…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/ratelimitting/admissioncontrol/AdmissionForClusterManagerIT.java
  server/src/main/java/org/opensearch/action/support/HandledTransportAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeReadAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/ratelimitting/admissioncontrol/controllers/CpuBasedAdmissionController.java
  server/src/main/java/org/opensearch/ratelimitting/admissioncontrol/controllers/IoBasedAdmissionController.java
  server/src/main/java/org/opensearch/ratelimitting/admissioncontrol/enums/AdmissionControlActionType.java
  server/src/main/java/org/opensearch/ratelimitting/admissioncontrol/settings/CpuBasedAdmissionControllerSettings.java
  server/src/main/java/org/opensearch/ratelimitting/admissioncontrol/settings/IoBasedAdmissionControllerSettings.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/settings/CPUBasedAdmissionControllerSettingsTests.java
  server/src/test/java/org/opensearch/ratelimitting/admissioncontrol/settings/IoBasedAdmissionControllerSettingsTests.java
Labels: enhancement, discuss, idea, distributed framework, RFC

#12839 Switch 2.x to 2.14.0
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#12842 Add 2.14.0 to version & BWC
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#12841 Add release-notes for 2.13.0
  release-notes/opensearch.release-notes-2.13.0.md
Labels: backport 2.x, skip-changelog, backport 2.13

#12834 Catch task description error
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
  server/src/test/java/org/opensearch/search/geo/GeoPointShapeQueryTests.java
Labels: bug, flaky-test, Geospatial, backport 2.x, skip-changelog, Search, Other

#12816 [Backport 2.x] [Remote Migration] Changes for Primary Relocation during migration …
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationClusterSettingIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteIndexPrimaryRelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SegmentReplicationSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/indices/replication/TransportSegmentReplicationStatsAction.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/SegmentReplicationPressureService.java
  server/src/main/java/org/opensearch/index/SegmentReplicationStatsTracker.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreStatsTrackerFactory.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/recovery/MultiFileWriter.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoverySourceService.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandlerFactory.java
  server/src/main/java/org/opensearch/indices/recovery/RecoveryTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationSourceService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  server/src/test/java/org/opensearch/index/replication/IndexLevelReplicationTests.java
  server/src/test/java/org/opensearch/index/replication/RecoveryDuringReplicationTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/ReplicaRecoveryWithRemoteTranslogOnPrimaryTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/indices/IndicesLifecycleListenerSingleNodeTests.java
  server/src/test/java/org/opensearch/indices/recovery/PeerRecoveryTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoveryTests.java
  server/src/test/java/org/opensearch/recovery/ReplicationCollectionTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#12851 add missing changelog entry to 2.13 release nodes
  release-notes/opensearch.release-notes-2.13.0.md
Labels: skip-changelog

#12776 Fix SimpleNestedExplainIT.testExplainMultipleDocs flakiness
  server/src/internalClusterTest/java/org/opensearch/search/nested/SimpleNestedExplainIT.java
Labels: bug, flaky-test, skip-changelog, Search

#12864 Added missed API visibility annotations for public / experimental APIs
  libs/core/src/main/java/org/opensearch/OpenSearchException.java
  libs/core/src/main/java/org/opensearch/core/common/breaker/CircuitBreaker.java
  libs/core/src/main/java/org/opensearch/core/common/transport/BoundTransportAddress.java
  libs/core/src/main/java/org/opensearch/core/transport/TransportResponse.java
  libs/core/src/main/java/org/opensearch/semver/SemverRange.java
  server/src/main/java/org/opensearch/action/support/clustermanager/ClusterManagerNodeRequest.java
  server/src/main/java/org/opensearch/common/cache/RemovalListener.java
  server/src/main/java/org/opensearch/common/cache/policy/CachedQueryResult.java
  server/src/main/java/org/opensearch/common/cache/serializer/Serializer.java
  server/src/main/java/org/opensearch/common/lucene/index/OpenSearchDirectoryReader.java
  server/src/main/java/org/opensearch/common/metrics/MeanMetric.java
  server/src/main/java/org/opensearch/http/HttpInfo.java
  server/src/main/java/org/opensearch/http/HttpServerTransport.java
  server/src/main/java/org/opensearch/http/HttpStats.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/LongArrayBackedBitSet.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
  server/src/main/java/org/opensearch/rest/RestChannel.java
  server/src/main/java/org/opensearch/rest/RestHandler.java
  server/src/main/java/org/opensearch/rest/RestResponse.java
  server/src/main/java/org/opensearch/transport/ConnectionProfile.java
  server/src/main/java/org/opensearch/transport/Header.java
  server/src/main/java/org/opensearch/transport/InboundMessage.java
  server/src/main/java/org/opensearch/transport/RequestHandlerRegistry.java
  server/src/main/java/org/opensearch/transport/StatsTracker.java
  server/src/main/java/org/opensearch/transport/TcpChannel.java
  server/src/main/java/org/opensearch/transport/TcpTransport.java
  server/src/main/java/org/opensearch/transport/Transport.java
  server/src/main/java/org/opensearch/transport/TransportChannel.java
  server/src/main/java/org/opensearch/transport/TransportMessageListener.java
  server/src/main/java/org/opensearch/transport/TransportRequestHandler.java
  server/src/main/java/org/opensearch/transport/TransportResponseHandler.java
  server/src/main/java/org/opensearch/transport/TransportStats.java
Labels: skip-changelog

#12857 [Backport 2.13] Added static setting for checkPendingFlushUpdate functionality of lucene index writer
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.13.0.md
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
Labels: enhancement, Indexing:Performance

#12874 [Backport 2.13] Make GetTermVersionAction internal
  server/src/internalClusterTest/java/org/opensearch/action/support/clustermanager/term/FetchByTermVersionIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/GetTermVersionAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/GetTermVersionRequest.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/GetTermVersionResponse.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/TransportGetTermVersionAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/package-info.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerTermCheckTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/term/ClusterTermVersionIT.java
  server/src/test/java/org/opensearch/action/support/clustermanager/term/ClusterTermVersionTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: backport, skip-changelog

#12866 Make GetTermVersionAction internal
  server/src/internalClusterTest/java/org/opensearch/action/support/clustermanager/term/FetchByTermVersionIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/GetTermVersionAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/GetTermVersionRequest.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/GetTermVersionResponse.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/TransportGetTermVersionAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/package-info.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerTermCheckTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/term/ClusterTermVersionIT.java
  server/src/test/java/org/opensearch/action/support/clustermanager/term/ClusterTermVersionTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: skip-changelog

#12867 [Backport] [2.x] Added missed API visibility annotations for public / experimental APIs (#12864)
  libs/core/src/main/java/org/opensearch/OpenSearchException.java
  libs/core/src/main/java/org/opensearch/core/common/breaker/CircuitBreaker.java
  libs/core/src/main/java/org/opensearch/core/common/transport/BoundTransportAddress.java
  libs/core/src/main/java/org/opensearch/core/transport/TransportResponse.java
  libs/core/src/main/java/org/opensearch/semver/SemverRange.java
  server/src/main/java/org/opensearch/action/support/clustermanager/ClusterManagerNodeRequest.java
  server/src/main/java/org/opensearch/common/cache/RemovalListener.java
  server/src/main/java/org/opensearch/common/cache/policy/CachedQueryResult.java
  server/src/main/java/org/opensearch/common/cache/serializer/Serializer.java
  server/src/main/java/org/opensearch/common/lucene/index/OpenSearchDirectoryReader.java
  server/src/main/java/org/opensearch/common/metrics/MeanMetric.java
  server/src/main/java/org/opensearch/http/HttpInfo.java
  server/src/main/java/org/opensearch/http/HttpServerTransport.java
  server/src/main/java/org/opensearch/http/HttpStats.java
  server/src/main/java/org/opensearch/index/codec/fuzzy/LongArrayBackedBitSet.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/rest/BaseRestHandler.java
  server/src/main/java/org/opensearch/rest/RestChannel.java
  server/src/main/java/org/opensearch/rest/RestHandler.java
  server/src/main/java/org/opensearch/rest/RestResponse.java
  server/src/main/java/org/opensearch/transport/ConnectionProfile.java
  server/src/main/java/org/opensearch/transport/Header.java
  server/src/main/java/org/opensearch/transport/InboundMessage.java
  server/src/main/java/org/opensearch/transport/RequestHandlerRegistry.java
  server/src/main/java/org/opensearch/transport/StatsTracker.java
  server/src/main/java/org/opensearch/transport/TcpChannel.java
  server/src/main/java/org/opensearch/transport/TcpTransport.java
  server/src/main/java/org/opensearch/transport/Transport.java
  server/src/main/java/org/opensearch/transport/TransportChannel.java
  server/src/main/java/org/opensearch/transport/TransportMessageListener.java
  server/src/main/java/org/opensearch/transport/TransportRequestHandler.java
  server/src/main/java/org/opensearch/transport/TransportResponseHandler.java
  server/src/main/java/org/opensearch/transport/TransportStats.java
Labels: skip-changelog

#12895 Bump OpenSearch version in README for open issues
  README.md
Labels: skip-changelog

#12894 [2.x] Add README to version increment automation
  .github/workflows/version.yml
Labels: skip-changelog

#12444 Update to Gradle 8.7
  buildSrc/src/testFixtures/java/org/opensearch/gradle/test/GradleThreadsFilter.java
  gradle/wrapper/gradle-wrapper.properties
Labels: skip-changelog

#12877 Disable MockTelemetryPlugin by default for integ tests
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: bug, flaky-test, backport 2.x, skip-changelog, Storage:Snapshots, Build

#12746 [DerivedFields] PR1 - DerivedFieldScript and query execution logic
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/71_context_api.yml
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldValueFetcher.java
  server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java
  server/src/main/java/org/opensearch/script/DerivedFieldScript.java
  server/src/main/java/org/opensearch/script/ScriptModule.java
  server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
  test/framework/src/main/java/org/opensearch/script/MockScriptEngine.java
Labels: enhancement, skip-changelog, Search

#12908 Bump asm from 9.6 to 9.7
  CHANGELOG.md
  buildSrc/version.properties
  modules/lang-expression/licenses/asm-9.6.jar.sha1
  modules/lang-expression/licenses/asm-9.7.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.6.jar.sha1
  modules/lang-expression/licenses/asm-commons-9.7.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.6.jar.sha1
  modules/lang-expression/licenses/asm-tree-9.7.jar.sha1
  modules/lang-painless/licenses/asm-9.6.jar.sha1
  modules/lang-painless/licenses/asm-9.7.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.6.jar.sha1
  modules/lang-painless/licenses/asm-analysis-9.7.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.6.jar.sha1
  modules/lang-painless/licenses/asm-commons-9.7.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.6.jar.sha1
  modules/lang-painless/licenses/asm-tree-9.7.jar.sha1
  modules/lang-painless/licenses/asm-util-9.6.jar.sha1
  modules/lang-painless/licenses/asm-util-9.7.jar.sha1
Labels: dependencies

#12858 [Backport 2.x] Catch task description error (#12834)
  server/src/main/java/org/opensearch/action/search/SearchRequest.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/test/java/org/opensearch/action/search/SearchRequestTests.java
  server/src/test/java/org/opensearch/search/geo/GeoPointShapeQueryTests.java
Labels: skip-changelog

#12920 Add missed API visibility annotations for public APIs
  server/src/main/java/org/opensearch/common/blobstore/BlobPath.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreDataEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathType.java
Labels: skip-changelog

#12885 Fix flaky tests in CopyProcessorTests
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/CopyProcessorTests.java
  test/framework/src/main/java/org/opensearch/ingest/RandomDocumentPicks.java
Labels: skip-changelog

#12925 [Backport] [2.x] Bump net.minidev:json-smart from 2.5.0 to 2.5.1 in /test/fixtures/hdfs-fixture (#12893)
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: dependencies

#12817 Fix Flaky TaskBatcherTests Tests
  server/src/test/java/org/opensearch/cluster/service/TaskBatcherTests.java
Labels: bug, backport 2.x, skip-changelog, Cluster Manager, Other

#12931 [Backport] [1.3] Bump netty from 4.1.107.Final to 4.1.108.Final (#12924)
  CHANGELOG.md
  buildSrc/version.properties
  modules/transport-netty4/build.gradle
  modules/transport-netty4/licenses/netty-buffer-4.1.107.Final.jar.sha1
  modules/transport-netty4/licenses/netty-buffer-4.1.108.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.107.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-4.1.108.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.107.Final.jar.sha1
  modules/transport-netty4/licenses/netty-codec-http-4.1.108.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.107.Final.jar.sha1
  modules/transport-netty4/licenses/netty-common-4.1.108.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.107.Final.jar.sha1
  modules/transport-netty4/licenses/netty-handler-4.1.108.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.107.Final.jar.sha1
  modules/transport-netty4/licenses/netty-resolver-4.1.108.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.107.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-4.1.108.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.107.Final.jar.sha1
  modules/transport-netty4/licenses/netty-transport-native-unix-common-4.1.108.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.107.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-dns-4.1.108.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.107.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-http2-4.1.108.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.107.Final.jar.sha1
  plugins/repository-azure/licenses/netty-codec-socks-4.1.108.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.107.Final.jar.sha1
  plugins/repository-azure/licenses/netty-handler-proxy-4.1.108.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.107.Final.jar.sha1
  plugins/repository-azure/licenses/netty-resolver-dns-4.1.108.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.107.Final.jar.sha1
  plugins/repository-azure/licenses/netty-transport-native-unix-common-4.1.108.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.107.Final.jar.sha1
  plugins/repository-hdfs/licenses/netty-all-4.1.108.Final.jar.sha1
  plugins/transport-nio/build.gradle
  plugins/transport-nio/licenses/netty-buffer-4.1.107.Final.jar.sha1
  plugins/transport-nio/licenses/netty-buffer-4.1.108.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.107.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-4.1.108.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.107.Final.jar.sha1
  plugins/transport-nio/licenses/netty-codec-http-4.1.108.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.107.Final.jar.sha1
  plugins/transport-nio/licenses/netty-common-4.1.108.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.107.Final.jar.sha1
  plugins/transport-nio/licenses/netty-handler-4.1.108.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.107.Final.jar.sha1
  plugins/transport-nio/licenses/netty-resolver-4.1.108.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.107.Final.jar.sha1
  plugins/transport-nio/licenses/netty-transport-4.1.108.Final.jar.sha1
Labels: dependencies

#12768 Add a counter to node stat api to track shard going from idle to non-idle
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
  server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
  server/src/main/java/org/opensearch/index/search/stats/ShardSearchStats.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/SearchOperationListener.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
  server/src/test/java/org/opensearch/index/shard/SearchOperationListenerTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java
Labels: enhancement, backport 2.x, Search

#12933 Rebased version of #12706
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
Labels: bug, skip-changelog, Other

#12697 Perform buildAggregation concurrently and partially support composite aggs
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/bucket/CompositeAggIT.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationCollectorManager.java
  server/src/main/java/org/opensearch/search/aggregations/Aggregator.java
  server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java
  server/src/main/java/org/opensearch/search/aggregations/GlobalAggCollectorManager.java
  server/src/main/java/org/opensearch/search/aggregations/MultiBucketConsumerService.java
  server/src/main/java/org/opensearch/search/aggregations/NonGlobalAggCollectorManager.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregationFactory.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/search/aggregations/AggregationProcessorTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: bug, enhancement, backport 2.x, Search:Performance, Search:Query Capabilities, v2.14.0

#12921 Update supported version for the bug fix which adds more index blocks check in resize APIs
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.clone/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.split/10_basic.yml
Labels: skip-changelog

#12808 [DerivedFields] PR2 - Implementation for all supported types and DerivedFieldType
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldSupportedTypes.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldTypeTests.java
Labels: enhancement, backport 2.x, skip-changelog, Search

#12838 [Remote Store] Add RemoteStoreSettings class to handle remote store related settings
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/indices/DefaultRemoteStoreSettings.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
  server/src/test/java/org/opensearch/indices/IndicesServiceTests.java
  server/src/test/java/org/opensearch/indices/RemoteStoreSettingsDynamicUpdateTests.java
  server/src/test/java/org/opensearch/indices/recovery/RecoverySettingsDynamicUpdateTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: skip-changelog

#12954 Disable concurrent segment search for system indices and throttled search requests
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
Labels: enhancement, v3.0.0, backport 2.x, Search:Performance, v2.14.0

#12972 Update version checks for shard search idle metric after backport to 2.x
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
  server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
Labels: skip-changelog
