Repository opensearch-project/OpenSearch, pull requests merged in 2024-09, with the labels that each got.

#15554 BWC fix - correcting shard routing version
  server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java
Labels: skip-changelog

#15426 Add support to upload snapshot shard blobs with hashed prefix
  CHANGELOG.md
  modules/repository-url/src/internalClusterTest/java/org/opensearch/repositories/url/URLSnapshotRestoreIT.java
  plugins/repository-azure/src/internalClusterTest/java/org/opensearch/repositories/azure/AzureStorageCleanupThirdPartyTests.java
  plugins/repository-gcs/src/internalClusterTest/java/org/opensearch/repositories/gcs/GoogleCloudStorageThirdPartyTests.java
  plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsRepositoryTests.java
  plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsTests.java
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/RepositoryCredentialsTests.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/repositories/RepositoryBlocksIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/snapshots/SnapshotBlocksIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteCloneIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/shards/ClusterShardLimitIT.java
  server/src/internalClusterTest/java/org/opensearch/index/store/CorruptedFileIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesOptionsIntegrationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/MigrationBaseTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRepositoryRegistrationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartIT.java
  server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/repositories/fs/FsBlobStoreRepositoryIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/CorruptedBlobStoreRepositoryIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/MultiClusterRepoAccessIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoryFilterUserMetadataIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SharedClusterSnapshotRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SystemRepositoryIT.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/recovery/RemoteStoreRestoreService.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategy.java
  server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectoryFactory.java
  server/src/main/java/org/opensearch/repositories/IndexId.java
  server/src/main/java/org/opensearch/repositories/RepositoryData.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/repositories/blobstore/ConfigBlobStoreFormat.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardPaths.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyTests.java
  server/src/test/java/org/opensearch/repositories/IndexIdTests.java
  server/src/test/java/org/opensearch/repositories/RepositoryDataTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryHelperTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotShardPathsTests.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchBlobStoreRepositoryIntegTestCase.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, discuss, RFC, backport 2.x, Storage:Snapshots

#15559 Fix RepositoriesServiceIT.testUpdateRepository from #15426
  server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
Labels: skip-changelog

#15416 Add support to skip pinned timestamp in remote translog garbage collector
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteSplitIndexIT.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogWithPinnedTimestampTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#15560 Fix flaky tests due to hashed prefix path type snapshots
  server/src/internalClusterTest/java/org/opensearch/snapshots/CorruptedBlobStoreRepositoryIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#15499 Modify create snapshot v2 response when wait_for_completion is false
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/TransportCreateSnapshotAction.java
Labels: skip-changelog

#14809 Star Tree File Formats
  server/src/main/java/org/opensearch/index/codec/composite/CompositeIndexReader.java
  server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99DocValuesFormat.java
  server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99DocValuesReader.java
  server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99DocValuesWriter.java
  server/src/main/java/org/opensearch/index/codec/composite/datacube/startree/StarTreeValues.java
  server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexConstants.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreesBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/StarTreeWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/data/StarTreeDataWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/CompositeIndexValues.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/InMemoryTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNodeType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/SequentialDocValuesIterator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeUtils.java
  server/src/main/java/org/opensearch/index/engine/SegmentsStats.java
  server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreesBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/data/StarTreeFileFormatsTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNodeTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNodeTypeTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeUtilsTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: enhancement, Indexing & Search, Search:Aggregations, skip-changelog, Indexing, Indexing:Performance, v2.16.0, v2.17.0

#15566 [Backport 2.x] Populate RecoveryState details for shallow snapshot restore (#15353)
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
Labels: skip-changelog

#15100 Simplify diff calculation for remote routing table
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTableIncrementalDiff.java
  server/src/main/java/org/opensearch/cluster/routing/StringKeyDiffProvider.java
  server/src/main/java/org/opensearch/cluster/routing/remote/InternalRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/NoopRemoteRoutingTableService.java
  server/src/main/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableService.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateDiffManifest.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/routingtable/RemoteRoutingTableDiff.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingTableDiffTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/ClusterStateDiffManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/routingtable/RemoteIndexRoutingTableDiffTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
Labels: backport 2.x, skip-changelog

#15570 [Backport 2.x][Remote Publication] Add remote download stats (#15291)
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManager.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteUploadStats.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/cluster/coordination/PublicationTransportHandlerTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: v2.17.0

#15572 Update version check for context to comply with backport
  server/src/main/java/org/opensearch/OpenSearchServerException.java
  server/src/main/java/org/opensearch/action/admin/indices/create/CreateIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/get/GetIndexResponse.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
Labels: skip-changelog

#13788 Introduce ApproximateRangeQuery and ApproximateableQuery
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/370_approximate_range.yml
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Helper.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateIndexOrDocValuesQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateScoreQuery.java
  server/src/main/java/org/opensearch/search/approximate/package-info.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldQueryStringQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/MatchPhraseQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/RangeQueryBuilderTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximateIndexOrDocValuesQueryTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximateScoreQueryTests.java
Labels: enhancement, v3.0.0, backport 2.x, Search:Performance, v2.17.0

#15526 Change pinned timestamp file format stored in remote store
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStorePinnedTimestampsIT.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemotePinnedTimestamps.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteStorePinnedTimestampsBlobStore.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreUtils.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemotePinnedTimestampsTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryWithPinnedTimestampTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogWithPinnedTimestampTests.java
Labels: skip-changelog

#15465 Add limit on number of processors in Ingest pipelines
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/ingest/SimulateExecutionService.java
  server/src/main/java/org/opensearch/action/ingest/SimulatePipelineTransportAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/test/java/org/opensearch/action/ingest/SimulateExecutionServiceTests.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
Labels: backport 2.x

#15409 [SnapshotV2] Snapshot Status API changes
  CHANGELOG.md
  client/rest-high-level/src/test/java/org/opensearch/client/SnapshotRequestConvertersTests.java
  qa/repository-multi-version/src/test/java/org/opensearch/upgrades/MultiVersionRepositoryAccessIT.java
  rest-api-spec/src/main/resources/rest-api-spec/api/snapshot.status.json
  server/src/internalClusterTest/java/org/opensearch/snapshots/RemoteIndexSnapshotStatusApiIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
  server/src/main/java/org/opensearch/OpenSearchServerException.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestSnapshotsStatusAction.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/main/java/org/opensearch/snapshots/TooManyShardsInSnapshotsStatusException.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
Labels: enhancement, backport 2.x, Storage:Snapshots, v2.17.0

#15509 Fix missing order field in TemplatesMetadata deserialization
  server/src/main/java/org/opensearch/cluster/metadata/TemplatesMetadata.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteTemplatesMetadataTests.java
Labels: backport 2.x, skip-changelog

#13966 Support cancellation for admin apis
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/shards/TransportCatShardsActionIT.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/CatShardsResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/TransportCatShardsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/ClusterStateRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/IndicesStatsResponse.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/action/support/TimeoutTaskCancellationUtility.java
  server/src/main/java/org/opensearch/action/support/broadcast/BroadcastRequest.java
  server/src/main/java/org/opensearch/action/support/clustermanager/ClusterManagerNodeReadRequest.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/ClusterAdminTask.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/test/java/org/opensearch/action/admin/indices/shards/CatShardsResponseTests.java
Labels: enhancement, backport 2.x, Cluster Manager, v2.17.0

#15204 Fix flaky test MasterServiceTests.testClusterStateUpdateLoggingWithDebugEnabled
  server/src/test/java/org/opensearch/cluster/service/MasterServiceTests.java
Labels: backport 2.x, skip-changelog

#15598 Disable pinned timestamp flag and mute testRemoteStoreCleanupForDeletedIndex
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#15601 Adding awaitsFix to approximateRangeTest flaky tests
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: bug, skip-changelog, Search

#15533 [Star tree] Star tree index validations
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeIndexSettings.java
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/TranslogFlushIntervalSettingsTests.java
  server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: enhancement, skip-changelog, Indexing:Performance

#15557 Add prefix support to hashed prefix & infix path types on remote store
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryLocalRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRefreshListenerIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/repositories/cleanup/TransportCleanupRepositoryAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPath.java
  server/src/main/java/org/opensearch/index/remote/RemoteIndexPathUploader.java
  server/src/main/java/org/opensearch/index/remote/RemoteStoreEnums.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategy.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteIndexPathTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteIndexPathUploaderTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreCustomMetadataResolverTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreEnumsTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactoryTests.java
  server/src/test/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerFactoryTests.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryHelperTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/BlobStoreTestUtil.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: backport 2.x

#15602 [Snapshot V2] Fix for create snapshot build and test failures
  server/src/main/java/org/opensearch/repositories/FilterRepository.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
  test/framework/src/main/java/org/opensearch/index/shard/RestoreOnlyRepository.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, skip-changelog, Storage:Snapshots

#15596 Change version to V_2_17_0 in changes from #15409
  server/src/main/java/org/opensearch/OpenSearchServerException.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java
Labels: skip-changelog

#15218 Add cluster state checksum in manifest
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/common/io/stream/BufferedChecksumStreamOutput.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamOutput.java
  libs/core/src/main/java/org/opensearch/core/common/io/stream/VerifiableWriteable.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/AbstractDiffable.java
  server/src/main/java/org/opensearch/cluster/ClusterState.java
  server/src/main/java/org/opensearch/cluster/DiffableUtils.java
  server/src/main/java/org/opensearch/cluster/block/ClusterBlock.java
  server/src/main/java/org/opensearch/cluster/block/ClusterBlocks.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/TemplatesMetadata.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
  server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateChecksum.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/test/java/org/opensearch/cluster/block/ClusterBlocksTests.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexTemplateMetadataTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodesTests.java
  server/src/test/java/org/opensearch/cluster/routing/IndexShardRoutingTableTests.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingTableTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterStateChecksumTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: backport 2.x

#15341 Optimising node to node communication by serializing node attribute in DiscoveryNode only in scenarioes where it is required
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamOutput.java
  server/src/main/java/org/opensearch/action/admin/cluster/allocation/ClusterAllocationExplanation.java
  server/src/main/java/org/opensearch/action/support/nodes/BaseNodeResponse.java
  server/src/main/java/org/opensearch/cluster/ClusterState.java
  server/src/main/java/org/opensearch/cluster/coordination/Join.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinRequest.java
  server/src/main/java/org/opensearch/cluster/coordination/StartJoinRequest.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AbstractAllocationDecision.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/NodeAllocationResult.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/recovery/StartRecoveryRequest.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumWritableBlobStoreFormat.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/ChecksumWritableBlobStoreFormatTests.java
Labels: skip-changelog

#15603 [Star Tree] Interfaces Fixes for Star Tree Search
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNodeTests.java
Labels: enhancement, Search:Aggregations, skip-changelog

#15616 [SnapshotV2] SnapshotInfo pinned timestamp version change to V_2_17_0
  server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
Labels: skip-changelog

#15615 [Backport 2.x] Modify create snapshot v2 response when wait_for_completion is false
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/create/TransportCreateSnapshotAction.java
Labels: skip-changelog

#15579 Abstract out RemoteFsTranslogWithPinnedTimestamps
  server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
Labels: skip-changelog

#15568 Optimise snapshot deletion to speed up snapshot deletion and creation
  CHANGELOG.md
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/threadpool/ScalingThreadPoolTests.java
Labels: skip-changelog

#15617 Optimising node to node communication by serializing node attribute in DiscoveryNode only in scenarioes where it is required
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamOutput.java
  server/src/main/java/org/opensearch/action/admin/cluster/allocation/ClusterAllocationExplanation.java
  server/src/main/java/org/opensearch/action/support/nodes/BaseNodeResponse.java
  server/src/main/java/org/opensearch/cluster/ClusterState.java
  server/src/main/java/org/opensearch/cluster/coordination/Join.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinRequest.java
  server/src/main/java/org/opensearch/cluster/coordination/StartJoinRequest.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AbstractAllocationDecision.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/NodeAllocationResult.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodes.java
  server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryTargetService.java
  server/src/main/java/org/opensearch/indices/recovery/StartRecoveryRequest.java
  server/src/main/java/org/opensearch/repositories/blobstore/ChecksumWritableBlobStoreFormat.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateAttributesManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteDiscoveryNodesTests.java
  server/src/test/java/org/opensearch/repositories/blobstore/ChecksumWritableBlobStoreFormatTests.java
Labels: skip-changelog

#15619 [Backport] SnapshotInfo pinned timestamp version change to V_2_17_0 (#15616)
  server/src/main/java/org/opensearch/snapshots/SnapshotInfo.java
Labels: skip-changelog

#15624 Fix breaking changes of #15409
  client/rest-high-level/src/test/java/org/opensearch/client/SnapshotRequestConvertersTests.java
  qa/repository-multi-version/src/test/java/org/opensearch/upgrades/MultiVersionRepositoryAccessIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java
Labels: enhancement, skip-changelog, Storage:Snapshots, v2.17.0

#15010 Add canRemain method to TargetPoolAllocationDecider to move shards from local to remote pool for hot to warm tiering
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/tiering/TieringUtils.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingPool.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/ShardsTieringAllocationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/TieringAllocationBaseTestCase.java
Labels: backport 2.x, v2.17.0

#15363 Pluggable deciders for concurrent search
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/CombiIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/EquivalenceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/MetadataIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/MissingValueIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/AvgBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/BucketScriptIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/BucketSelectorIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/BucketSortIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/DateDerivativeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/DerivativeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/ExtendedStatsBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/MaxBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/MinBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/MovAvgIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/PercentilesBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/SerialDiffIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/StatsBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/SumBucketIT.java
  server/src/main/java/org/opensearch/common/settings/AbstractScopedSettings.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/SearchPlugin.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchDecider.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchDecision.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchVisitor.java
  server/src/main/java/org/opensearch/search/deciders/package-info.java
  server/src/test/java/org/opensearch/common/settings/ScopedSettingsTests.java
  server/src/test/java/org/opensearch/common/settings/SettingsModuleTests.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/node/MockNode.java
  test/framework/src/main/java/org/opensearch/search/MockSearchService.java
  test/framework/src/main/java/org/opensearch/test/ParameterizedOpenSearchIntegTestCase.java
Labels: enhancement, Plugins, Search:Aggregations, RFC, backport 2.x, Search, Search:Performance, Roadmap:Cost/Performance/Scale, Roadmap:Search, v2.17.0

#15626 Fixing Query Group stats OpenSearch API annotation errors
  server/src/main/java/org/opensearch/wlm/stats/QueryGroupStats.java
Labels: backport 2.x, skip-changelog

#15545 Fix flaky test in 91_flat_object_null_value.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/91_flat_object_null_value.yml
  test/framework/src/main/java/org/opensearch/test/NotEqualMessageBuilder.java
Labels: skip-changelog

#15633 Revert "Add fieldType to AbstractQueryBuilder and SortBuilder (#15328)"
  CHANGELOG.md
  modules/mapper-extras/src/main/java/org/opensearch/index/query/RankFeatureQueryBuilder.java
  modules/parent-join/src/main/java/org/opensearch/join/query/HasChildQueryBuilder.java
  modules/parent-join/src/main/java/org/opensearch/join/query/HasParentQueryBuilder.java
  modules/parent-join/src/main/java/org/opensearch/join/query/ParentIdQueryBuilder.java
  modules/percolator/src/main/java/org/opensearch/percolator/PercolateQueryBuilder.java
  server/src/main/java/org/opensearch/index/mapper/FieldTypeLookup.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/query/AbstractQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/BoolQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/BoostingQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/ConstantScoreQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/DisMaxQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/DistanceFeatureQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/IdsQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/IntervalQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchAllQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchNoneQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MoreLikeThisQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MultiMatchQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/index/query/QueryStringQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/ScriptQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SimpleQueryStringBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanContainingQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanFirstQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanMultiTermQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanNearQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanNotQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanOrQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanWithinQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/TermsSetQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/WrapperQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/functionscore/FunctionScoreQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/functionscore/ScriptScoreQueryBuilder.java
  server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/ScoreSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/ScriptSortBuilder.java
  server/src/main/java/org/opensearch/search/sort/SortBuilder.java
  server/src/test/java/org/opensearch/index/query/QueryShardContextTests.java
  server/src/test/java/org/opensearch/index/query/plugin/DummyQueryBuilder.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  server/src/test/java/org/opensearch/search/sort/AbstractSortTestCase.java
  server/src/test/java/org/opensearch/search/sort/FieldSortBuilderTests.java
  server/src/test/java/org/opensearch/search/sort/plugin/CustomSortBuilder.java
Labels: skip-changelog

#15630 [Backport 2.x] pluggable deciders for concurrent search (#15363)
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/AggregationsIntegrationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/CombiIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/EquivalenceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/MetadataIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/MissingValueIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/AvgBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/BucketScriptIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/BucketSelectorIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/BucketSortIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/DateDerivativeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/DerivativeIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/ExtendedStatsBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/MaxBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/MinBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/MovAvgIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/PercentilesBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/SerialDiffIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/StatsBucketIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/pipeline/SumBucketIT.java
  server/src/main/java/org/opensearch/common/settings/AbstractScopedSettings.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/SearchPlugin.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchDecider.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchDecision.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchVisitor.java
  server/src/main/java/org/opensearch/search/deciders/package-info.java
  server/src/test/java/org/opensearch/common/settings/ScopedSettingsTests.java
  server/src/test/java/org/opensearch/common/settings/SettingsModuleTests.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/node/MockNode.java
  test/framework/src/main/java/org/opensearch/search/MockSearchService.java
  test/framework/src/main/java/org/opensearch/test/ParameterizedOpenSearchIntegTestCase.java
Labels: backport 2.17

#15256 [Snapshot V2] Support pinned timestamp in delete flow
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotITV2.java
  server/src/main/java/org/opensearch/action/admin/cluster/repositories/cleanup/TransportCleanupRepositoryAction.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/RepositoryData.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Labels: enhancement, skip-changelog, Storage:Snapshots

#15610 [Backport 2.x] Star tree index validations (#15533)
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeIndexSettings.java
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/TranslogFlushIntervalSettingsTests.java
  server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: skip-changelog

#15508 ClusterManagerTaskThrottler Improvements
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskThrottler.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerThrottlingException.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java
Labels: backport 2.x

#15622 Changing checksum setting to support modes
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: backport 2.x, skip-changelog

#15620 Fix version check for BWC of Discovery Node serialization
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
Labels: skip-changelog

#15645 Initialize RemoteRoutingTableService when we have RoutingTableRepos
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#15131 Reset discovery nodes in all transport node actions request.
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/cluster/node/hotthreads/NodesHotThreadsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/usage/NodesUsageRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportNodesSnapshotsStatus.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/find/FindDanglingIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/list/ListDanglingIndicesRequest.java
  server/src/main/java/org/opensearch/action/search/GetAllPitNodesRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShardsBatch.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesInfoAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesActionTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesInfoActionTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesStatsActionTests.java
Labels: backport 2.x

#15648 [Backport 2.x] Optimise unassigned shards iteration after allocator timeout & Fix responsibility check for existing shards allocator when timed out
  server/src/main/java/org/opensearch/common/util/BatchRunnableExecutor.java
  server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
  server/src/main/java/org/opensearch/gateway/PrimaryShardAllocator.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/test/java/org/opensearch/common/util/BatchRunnableExecutorTests.java
  server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Labels: skip-changelog

#15650 [Backport 2.17] Optimise unassigned shards iteration after allocator timeout & Fix responsibility check for existing shards allocator when timed out
  server/src/main/java/org/opensearch/common/util/BatchRunnableExecutor.java
  server/src/main/java/org/opensearch/gateway/BaseGatewayShardAllocator.java
  server/src/main/java/org/opensearch/gateway/PrimaryShardAllocator.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardAllocator.java
  server/src/main/java/org/opensearch/gateway/ReplicaShardBatchAllocator.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/test/java/org/opensearch/common/util/BatchRunnableExecutorTests.java
  server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/PrimaryShardBatchAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/ReplicaShardBatchAllocatorTests.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Labels: skip-changelog

#15642 [Backport 2.x] Change version to V_2_17_0 (#15596)
  server/src/main/java/org/opensearch/OpenSearchServerException.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/SnapshotsStatusRequest.java
Labels: skip-changelog

#15652 Mute failing status tests from MixedClusterClientYamlTestSuiteIT
  rest-api-spec/src/main/resources/rest-api-spec/test/snapshot.status/10_basic.yml
Labels: skip-changelog

#15442 [Star Tree] Scaled Float Support
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/ScaledFloatFieldMapper.java
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldMapperTests.java
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/DocCountAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MaxValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MetricAggregatorInfo.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MinValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/StatelessDoubleValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregatorFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/numerictype/StarTreeNumericType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/numerictype/StarTreeNumericTypeConverters.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/numerictype/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractDocumentsFileManager.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNode.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DocCountFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/FieldValueConverter.java
  server/src/main/java/org/opensearch/index/mapper/Mapper.java
  server/src/main/java/org/opensearch/index/mapper/MapperBuilderProperties.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/AbstractValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/DocCountAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MaxValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MetricAggregatorInfoTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MinValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/StaticValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregatorFactoryTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: enhancement, Search:Aggregations, skip-changelog, Indexing, v2.17.0

#14717 Optimizing get indices to segments map calculations for IndicesSegmen…
  server/src/main/java/org/opensearch/action/admin/indices/segments/IndicesSegmentResponse.java
  server/src/test/java/org/opensearch/action/admin/indices/segments/IndicesSegmentResponseTests.java
Labels: bug, good first issue, skip-changelog, Cluster Manager

#15471 Relax the join validation for Remote State publication
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/metadata/RepositoriesMetadata.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/FailedShardsRoutingTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteStoreMigrationAllocationDeciderTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestUtils.java
Labels: backport 2.x

#15612 [Backport] Add cluster state checksum in manifest #15218
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/common/io/stream/StreamOutput.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/AbstractDiffable.java
  server/src/main/java/org/opensearch/cluster/ClusterState.java
  server/src/main/java/org/opensearch/cluster/DiffableUtils.java
  server/src/main/java/org/opensearch/cluster/block/ClusterBlock.java
  server/src/main/java/org/opensearch/cluster/block/ClusterBlocks.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/Metadata.java
  server/src/main/java/org/opensearch/cluster/metadata/TemplatesMetadata.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
  server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingTable.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterMetadataManifest.java
  server/src/main/java/org/opensearch/gateway/remote/ClusterStateChecksum.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteClusterMetadataManifest.java
  server/src/main/java/org/opensearch/index/translog/BufferedChecksumStreamOutput.java
  server/src/test/java/org/opensearch/cluster/block/ClusterBlocksTests.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexTemplateMetadataTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodesTests.java
  server/src/test/java/org/opensearch/cluster/routing/IndexShardRoutingTableTests.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingTableTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterMetadataManifestTests.java
  server/src/test/java/org/opensearch/gateway/remote/ClusterStateChecksumTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: backport 2.17

#15656 Set Version to 2.17 for hashed prefix snapshots
  server/src/main/java/org/opensearch/repositories/IndexId.java
  server/src/main/java/org/opensearch/repositories/RepositoryData.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/repositories/IndexIdTests.java
Labels: skip-changelog

#15661 [Backport 2.x] Set Version to 2.17 for hashed prefix snapshots
  server/src/main/java/org/opensearch/repositories/IndexId.java
  server/src/main/java/org/opensearch/repositories/RepositoryData.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/repositories/IndexIdTests.java
Labels: skip-changelog

#15607 fix wildcard term & terms query & add YAML REST test
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/270_wildcard_fieldtype_queries.yml
  server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
Labels: bug, backport 2.x, Search

#15590 Fix approximate pointrangequery tests
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: backport 2.x, skip-changelog

#15670 [2.17] Backporting of IndicesSegmentsResponse optimisation
  server/src/main/java/org/opensearch/action/admin/indices/segments/IndicesSegmentResponse.java
  server/src/test/java/org/opensearch/action/admin/indices/segments/IndicesSegmentResponseTests.java
Labels: skip-changelog

#15640 [Star tree][Bug] Fix for derived metrics
  server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99DocValuesReader.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/Metric.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
Labels: bug, skip-changelog, Indexing:Performance

#15676 [Backport 2.17] [Star tree] Star tree index validations (#15533) (#15610)
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/CompositeIndexSettings.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeIndexSettings.java
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/TranslogFlushIntervalSettingsTests.java
  server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: skip-changelog

#15563 [RW Separation] Add routing preference to route requests only to search replicas.
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java
  server/src/main/java/org/opensearch/cluster/routing/IndexShardRoutingTable.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/main/java/org/opensearch/cluster/routing/Preference.java
  server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java
  test/framework/src/main/java/org/opensearch/action/support/replication/ClusterStateCreationUtils.java
Labels: backport 2.x, skip-changelog

#15455 [RW Separation] Introduce allocation filter to control placement of search only replicas
  server/src/internalClusterTest/java/org/opensearch/cluster/allocation/SearchReplicaFilteringAllocationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaFeatureFlagIT.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/SearchReplicaAllocationDecider.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/SearchOnlyReplicaTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/SearchReplicaAllocationDeciderTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#15586 [Backport 2.x] Introduce ApproximateRangeQuery and ApproximateableQuery (#13788)
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/370_approximate_range.yml
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Helper.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateIndexOrDocValuesQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateScoreQuery.java
  server/src/main/java/org/opensearch/search/approximate/package-info.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldQueryStringQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/mapper/RangeFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/MatchPhraseQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/RangeQueryBuilderTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximateIndexOrDocValuesQueryTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximateScoreQueryTests.java
Labels: backport 2.17

#15637 Add new cluster setting for keyword indexordocvalues query
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
  server/src/test/java/org/opensearch/index/search/NestedHelperTests.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/FieldTypeTestCase.java
Labels: v3.0.0, backport 2.x, Search, v2.17.0

#15702 [Backport 2.x] Introduce allocation filter to control placement of search only replicas
  server/src/internalClusterTest/java/org/opensearch/cluster/allocation/SearchReplicaFilteringAllocationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaFeatureFlagIT.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/SearchReplicaAllocationDecider.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/SearchOnlyReplicaTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/SearchReplicaAllocationDeciderTests.java
Labels: skip-changelog, backport 2.17

#15709 Fix bwc test failures by updating wire compatibility on NodeIndicesStats
  server/src/main/java/org/opensearch/action/admin/indices/stats/CommonStatsFlags.java
  server/src/main/java/org/opensearch/indices/NodeIndicesStats.java
Labels: skip-changelog

#15680 Bump 2.x to 2.18.0 since 2.17.0 branch was cut already
  .ci/bwcVersions
  buildSrc/version.properties
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#15695 Mute test testRemoteStoreCleanupForDeletedIndexForSnapshotV2
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotV2IT.java
Labels: skip-changelog

#15627 [RW Separation] Add polling segment replication for search replicas
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaReplicationIT.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicator.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/IndexServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicatorTests.java
Labels: backport 2.x, backport 2.17

#15644 [SnapshotV2] Version change to V_2.17.0 for node min version check in create snapshot V2
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Labels: enhancement, skip-changelog, Storage:Snapshots

#15688 CircuitBreakingException for too many shards in snapshot status API call
  server/src/internalClusterTest/java/org/opensearch/snapshots/SnapshotStatusApisIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java
Labels: skip-changelog

#15716 [Backport 2.17] [Backport 2.x] [Star Tree] Scaled Float Support
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/ScaledFloatFieldMapper.java
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldMapperTests.java
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/DocCountAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MaxValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MetricAggregatorInfo.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MinValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/StatelessDoubleValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregatorFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/numerictype/StarTreeNumericType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/numerictype/StarTreeNumericTypeConverters.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/numerictype/package-info.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractDocumentsFileManager.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNode.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DocCountFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/FieldValueConverter.java
  server/src/main/java/org/opensearch/index/mapper/Mapper.java
  server/src/main/java/org/opensearch/index/mapper/MapperBuilderProperties.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/AbstractValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/CountValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/DocCountAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MaxValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MetricAggregatorInfoTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/MinValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/StaticValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/SumValueAggregatorTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/aggregators/ValueAggregatorFactoryTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilderTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: skip-changelog

#15717 [Backport 2.x] [RW Separation] Add polling segment replication for search replicas (#15627)
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaReplicationIT.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicator.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/IndexServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicatorTests.java
Labels: skip-changelog

#15722 [Backport 2.x] Support pinned timestamp in delete flow
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotITV2.java
  server/src/main/java/org/opensearch/action/admin/cluster/repositories/cleanup/TransportCleanupRepositoryAction.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/RepositoryData.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryTests.java
Labels: skip-changelog

#15565 Schedule reroute after allocator timed out
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsAllocator.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/allocator/TimeBoundBalancedShardsAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Labels: bug, skip-changelog, Cluster Manager, Other

#15575 Add dedicated string prefix for remote index metadata and remote routing table
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableBlobEntity.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntityBlobStore.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteRoutingTableBlobStore.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteIndexMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteIndexMetadataTests.java
Labels: skip-changelog

#15741 Fix MacOS assemble workflows
  .github/workflows/assemble.yml
Labels: backport 2.x, skip-changelog

#15712 Add 2.18.0 version
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#15713 Provide factory for pluggable deciders
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/SearchPlugin.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchDecision.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchRequestDecider.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchVisitor.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
  test/framework/src/main/java/org/opensearch/node/MockNode.java
Labels: enhancement, skip-changelog, Search:Performance, Roadmap:Cost/Performance/Scale, v2.17.0

#15729 [Backport 2.x] Provide factory for pluggable deciders
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/SearchPlugin.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchDecision.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchRequestDecider.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchVisitor.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
  test/framework/src/main/java/org/opensearch/node/MockNode.java
Labels: skip-changelog, v2.17.0

#15746 [Backport 2.17][Star tree][Bug] Fix for derived metrics (#15640) (#15686)
  server/src/main/java/org/opensearch/index/codec/composite/composite99/Composite99DocValuesReader.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/Metric.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/index/codec/composite99/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/AbstractStarTreeBuilderTests.java
Labels: skip-changelog

#15710 Update `newQueryShardContext()` to fix breaking changes
  server/src/main/java/org/opensearch/index/IndexService.java
Labels: skip-changelog

#15734 [Backport 2.17] Provide factory for pluggable deciders
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/SearchPlugin.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchDecision.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchRequestDecider.java
  server/src/main/java/org/opensearch/search/deciders/ConcurrentSearchVisitor.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
  test/framework/src/main/java/org/opensearch/node/MockNode.java
Labels: skip-changelog, v2.17.0

#15292 Optimising _cat/allocation API to use index level stats
  CHANGELOG.md
  server/src/main/java/org/opensearch/rest/action/cat/RestAllocationAction.java
Labels: backport 2.x, v2.17.0, backport 2.17

#15664 Add path prefix support to hashed prefix snapshots
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#15703 [Backport 2.x] Add new cluster setting for keyword indexordocvalues query (#15637)
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
  server/src/test/java/org/opensearch/index/search/NestedHelperTests.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/FieldTypeTestCase.java
Labels: backport 2.17

#15738 [Backport 2.17] Restore snapshot changes for shallow snapshot V2 (#15462)
  server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/TranslogConfig.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/InternalSnapshotsInfoService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#15077 Mitigation for remote snapshot filecache overflow
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTestCase.java
Labels: backport 2.x, backport 2.17

#15732 Mute flaky test RemoteFsTimestampAwareTranslogTests.testSimpleOperationsUpload
  server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
Labels: skip-changelog

#13845 [Backport 2.x] Add support for randomizing Remote Store enabled testing
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/ReplicaToPrimaryPromotionIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, stalled, skip-changelog, Storage

#15749 [Backport 2.x] Schedule reroute after allocator timed out (#15565)
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/ShardsAllocator.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/allocator/TimeBoundBalancedShardsAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
  test/framework/src/main/java/org/opensearch/test/gateway/TestShardBatchGatewayAllocator.java
Labels: skip-changelog

#15747 Fixing MacOS 13 assemble workflows
  .github/workflows/assemble.yml
Labels: bug, backport 2.x, skip-changelog, Build, backport 2.17

#15768 [Forwardport] [2.x] Add 2.17 release notes (#15762)
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.17.0.md
Labels: release

#15751 [Backport 2.17] Add new cluster setting for keyword indexordocvalues query (#15637)
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
  server/src/test/java/org/opensearch/index/search/NestedHelperTests.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  test/framework/src/main/java/org/opensearch/index/mapper/FieldTypeTestCase.java
Labels: skip-changelog

#15771 Adding release notes for new setting
  release-notes/opensearch.release-notes-2.17.0.md
Labels: skip-changelog

#15780 Add release notes for WithFieldName interface
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.17.0.md
Labels: backport main, backport 2.x

#15478 Make Remote Publication a static setting
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactoryTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: backport 2.x, v2.17.0, backport 2.17

#15772 Mute flaky test testRemotePublicationDisabledByRollingRestart
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
Labels: backport 2.x, skip-changelog

#15524 [Snapshot V2] Support pinned timestamp in clone flow
  server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/CloneSnapshotV2IT.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/clone/TransportCloneSnapshotAction.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
Labels: enhancement, skip-changelog, Storage:Snapshots, Storage:Remote

#15558 Add wait in replica recovery for allocation id to propagate on source node
  server/src/main/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
  server/src/main/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandler.java
  server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
  server/src/test/java/org/opensearch/indices/recovery/RemoteStorePeerRecoverySourceHandlerTests.java
Labels: skip-changelog

#15740 [Backport 2.17] Add dedicated string prefix for remote index metadata and remote routing table
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableBlobEntity.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntityBlobStore.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteRoutingTableBlobStore.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteIndexMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteIndexMetadataTests.java
Labels: skip-changelog

#15739 [Backport 2.x] Add dedicated string prefix for remote index metadata and remote routing table
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreClusterStateRestoreIT.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableBlobEntity.java
  server/src/main/java/org/opensearch/common/remote/RemoteWriteableEntityBlobStore.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteIndexMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteIndexMetadata.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteRoutingTableBlobStore.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteIndexMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteIndexMetadataTests.java
Labels: skip-changelog

#15784 [Backport 2.17] Make Remote Publication a static setting (#15478)
  release-notes/opensearch.release-notes-2.17.0.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactoryTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#15792 [Backport 2.17] [Remote State] Upload incremental cluster state on master re-election (#15145)
  release-notes/opensearch.release-notes-2.17.0.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/cluster/coordination/RemoteStatePublishRequest.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#15492 Health api memory optimisation
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterHealthIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/cluster/health/ClusterIndexHealth.java
  server/src/main/java/org/opensearch/cluster/health/ClusterShardHealth.java
  server/src/main/java/org/opensearch/cluster/health/ClusterStateHealth.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthAction.java
  server/src/test/java/org/opensearch/cluster/health/ClusterIndexHealthTests.java
  server/src/test/java/org/opensearch/cluster/health/ClusterShardHealthTests.java
  server/src/test/java/org/opensearch/cluster/health/ClusterStateHealthTests.java
Labels: backport 2.x, v2.17.0, backport 2.17

#15795 Mute testNewRestoredIndexIsRemoteStoreBackedForRemoteStoreDirectionAndMixedMode
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
Labels: skip-changelog

#15805 Flaky tests fix in 2.x branch
  rest-api-spec/src/main/resources/rest-api-spec/test/snapshot.status/10_basic.yml
  server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/DeleteSnapshotITV2.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/TranslogConfig.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/InternalSnapshotsInfoService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: skip-changelog

#15723 Change version to 2.17.0 for shallow snapshot V2 restore changes
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/restore/RestoreSnapshotRequest.java
  server/src/main/java/org/opensearch/cluster/routing/RecoverySource.java
Labels: skip-changelog

#15790 Making _cat/allocation API use indexLevelStats
  release-notes/opensearch.release-notes-2.17.0.md
  server/src/main/java/org/opensearch/rest/action/cat/RestAllocationAction.java
Labels: skip-changelog

#15802 Optimise memory for rest cluster health calls with in-line shard aggr…
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterHealthIT.java
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemoteStoreMigrationSettingsUpdateIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequestBuilder.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/TransportClusterHealthAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/cluster/health/ClusterIndexHealth.java
  server/src/main/java/org/opensearch/cluster/health/ClusterShardHealth.java
  server/src/main/java/org/opensearch/cluster/health/ClusterStateHealth.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterHealthAction.java
  server/src/test/java/org/opensearch/cluster/health/ClusterIndexHealthTests.java
  server/src/test/java/org/opensearch/cluster/health/ClusterShardHealthTests.java
  server/src/test/java/org/opensearch/cluster/health/ClusterStateHealthTests.java
Labels: skip-changelog

#15803 Downgrade version check for ser/de of applyLevelAtTransportLayer flag…
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthRequest.java
Labels: skip-changelog

#15684 Update protobuf from 3.22.3 to 3.25.4
  CHANGELOG.md
  buildSrc/version.properties
  plugins/repository-gcs/build.gradle
  server/licenses/protobuf-java-3.22.3.jar.sha1
  server/licenses/protobuf-java-3.25.4.jar.sha1
Labels: dependencies, backport 2.x

#15783 [Backport 2.x] Make Remote Publication a static setting (#15478)
  release-notes/opensearch.release-notes-2.17.0.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateCleanupManagerIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteRoutingTableServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceFactoryTests.java
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#15853 [Backport 2.x] [Remote State] Upload incremental cluster state on master re-election (#15145)
  release-notes/opensearch.release-notes-2.17.0.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/BaseRemoteStoreRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  server/src/main/java/org/opensearch/cluster/coordination/CoordinationState.java
  server/src/main/java/org/opensearch/cluster/coordination/PublicationTransportHandler.java
  server/src/main/java/org/opensearch/cluster/coordination/RemoteStatePublishRequest.java
  server/src/main/java/org/opensearch/gateway/GatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/cluster/coordination/CoordinationStateTests.java
  server/src/test/java/org/opensearch/gateway/GatewayMetaStatePersistedStateTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: skip-changelog

#15647 [Backport 2.x] ClusterManagerTaskThrottler Improvements
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskThrottler.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerThrottlingException.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java
Labels: skip-changelog

#15776 [Forwardport] [main] Add 2.17 release notes (#15762) (#15768)
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.17.0.md
Labels: release, skip-changelog

#15763 [Backport 2.x] Adding WithFieldName interface for QueryBuilders with fieldName
  server/src/main/java/org/opensearch/index/query/AbstractGeometryQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/BaseTermQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/CommonTermsQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/DistanceFeatureQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/FieldMaskingSpanQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/GeoBoundingBoxQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/GeoDistanceQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/GeoPolygonQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchBoolPrefixQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchPhrasePrefixQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchPhraseQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MatchQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/MultiTermQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/SpanNearQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/TermsQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/WithFieldName.java
Labels: skip-changelog

#15727 Remove awaits fix for ApproximatePointRangeQuery tests
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: bug, backport 2.x, skip-changelog, Search

#15867 Update to Gradle 8.10.1
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x, skip-changelog, Build

#15885 [BUG] Bug fix for checksum validation for mapping metadata
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MappingMetadata.java
  server/src/main/java/org/opensearch/common/compress/CompressedXContent.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
Labels: backport 2.x, skip-changelog, backport 2.17

#15737 fix escaped wildcard query on wildcard field
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/WildcardFieldTypeTests.java
Labels: bug, backport 2.x, Search

#15865 Add more wait time to assertBusy to fix RemoteFsTimestampAwareTranslo…
  server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
Labels: skip-changelog

#15884 Updating release-notes for 2.17
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.17.0.md
Labels: skip-changelog, v2.17.0

#15903 Fixing the CHANGELOG.md by removing change published in 2.17
  CHANGELOG.md
Labels: skip-changelog

#15890 [Backport 2.x] [BUG] Bug fix for checksum validation for mapping metadata #15888
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MappingMetadata.java
  server/src/main/java/org/opensearch/common/compress/CompressedXContent.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
Labels: skip-changelog, backport 2.17

#15424 Fallback on Term-Version check mismatch - Remote cluster-state
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteClusterStateTermVersionIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/state/TransportClusterStateAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/GetTermVersionResponse.java
  server/src/main/java/org/opensearch/action/support/clustermanager/term/TransportGetTermVersionAction.java
  server/src/main/java/org/opensearch/cluster/coordination/Coordinator.java
  server/src/main/java/org/opensearch/cluster/service/ClusterApplier.java
  server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateCache.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteManifestManager.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/term/ClusterTermVersionIT.java
  server/src/test/java/org/opensearch/cluster/coordination/NoOpClusterApplier.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, backport 2.x, Cluster Manager, backport 2.17

#15901 Add restriction to have a single repository with shallow snapshot v2 setting
  server/src/main/java/org/opensearch/node/remotestore/RemoteStorePinnedTimestampService.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/test/java/org/opensearch/repositories/blobstore/BlobStoreRepositoryRemoteIndexTests.java
Labels: skip-changelog

#15681 Reset discovery nodes in most transport node actions request. (#15131)
  server/src/main/java/org/opensearch/action/admin/cluster/node/hotthreads/NodesHotThreadsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/usage/NodesUsageRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportNodesSnapshotsStatus.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/find/FindDanglingIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/list/ListDanglingIndicesRequest.java
  server/src/main/java/org/opensearch/action/search/GetAllPitNodesRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShardsBatch.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterStatsAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesInfoAction.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestNodesStatsAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportClusterStatsActionTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesActionTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesInfoActionTests.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesStatsActionTests.java
Labels: skip-changelog

#15918 Removing task Id using remove() in TaskCancellationMonitoringService
  server/src/main/java/org/opensearch/tasks/TaskCancellationMonitoringService.java
Labels: backport 2.x, skip-changelog

#15906 Add the capability to override indices.breaker.total.use_real_memory setting for test clusters
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
Labels: enhancement, backport 2.x, skip-changelog, Build

#15866 [Backport] [2.x] Bump org.apache.logging.log4j:log4j-core from 2.23.1 to 2.24.0 in /buildSrc/src/testKit/thirdPartyAudit/sample_jars (#15858)
  CHANGELOG.md
  buildSrc/src/testKit/thirdPartyAudit/sample_jars/build.gradle
Labels: dependencies

#15859 Fix flaky org.opensearch.rest.ReactorNetty4StreamingStressIT.testCloseClientStreamingRequest test case
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Labels: >test-failure, flaky-test, backport 2.x, autocut, skip-changelog, backport 2.17

#15893 Update TESTING.md 'Building with extra plugins' documentation
  TESTING.md
Labels: backport 2.x, skip-changelog

#15932 [Backport] [2.x] Fix flaky org.opensearch.rest.ReactorNetty4StreamingStressIT.testCloseClientStreamingRequest test case (#15859)
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Labels: >test-failure, flaky-test, skip-changelog

#15882 fix case insensitive query on wildcard field
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/270_wildcard_fieldtype_queries.yml
  server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
Labels: bug, backport 2.x, Search

#15877 Remove TooManyShardsInSnapshotsStatusException
  server/src/main/java/org/opensearch/OpenSearchServerException.java
  server/src/main/java/org/opensearch/snapshots/TooManyShardsInSnapshotsStatusException.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
Labels: enhancement, skip-changelog, Storage:Snapshots

#15876 Unmute snapshot status tests from #15652
  rest-api-spec/src/main/resources/rest-api-spec/test/snapshot.status/10_basic.yml
Labels: skip-changelog

#15957 remote publication checksum stats
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteDownloadStats.java
  server/src/main/java/org/opensearch/gateway/remote/RemotePersistenceStats.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: backport 2.x, skip-changelog

#15501 Add validation for the search backpressure cancellation settings
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/cluster.put_settings/10_basic.yml
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureService.java
  server/src/main/java/org/opensearch/search/backpressure/SearchBackpressureState.java
  server/src/main/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettings.java
  server/src/main/java/org/opensearch/search/backpressure/settings/SearchShardTaskSettings.java
  server/src/main/java/org/opensearch/search/backpressure/settings/SearchTaskSettings.java
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
  server/src/test/java/org/opensearch/search/backpressure/settings/SearchBackpressureSettingsTests.java
Labels: backport 2.x, v2.18.0

#15959 Fix flaky terminaton conditions for org.opensearch.rest.ReactorNetty4StreamingStressIT.testCloseClientStreamingRequest test case
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Labels: skip-changelog

#15916 Implement WithFieldName interface in ValuesSourceAggregationBuilder & FieldSortBuilder
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSourceAggregationBuilder.java
  server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/range/RangeAggregationBuilderTests.java
  server/src/test/java/org/opensearch/search/sort/FieldSortBuilderTests.java
Labels: backport 2.x

#15962 Fix flaky terminaton conditions for org.opensearch.rest.ReactorNetty4StreamingStressIT.testCloseClientStreamingRequest test case (#15959)
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Labels: skip-changelog

#15968 Update version in README to 2.18.0
  README.md
Labels: skip-changelog

#15980 Fix breaking API changes introduced during the release window
  server/src/main/java/org/opensearch/wlm/ResourceType.java
Labels: skip-changelog

#15983 Refactor branch deletion for backports
  .github/workflows/delete_backport_branch.yml
Labels: bug, skip-changelog

#15931 Fix infinite loop in nested agg
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/410_nested_aggs.yml
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/nested/NestedAggregator.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
Labels: bug, backport 2.x, Search

#15972 Explicitly set the include discovery nodes flag for reload secure set…
  server/src/main/java/org/opensearch/action/admin/cluster/node/reload/NodesReloadSecureSettingsRequest.java
Labels: backport 2.x, skip-changelog

#15993 Update version check in yaml test file for bitmap filtering
  rest-api-spec/src/main/resources/rest-api-spec/test/search/370_bitmap_filtering.yml
Labels: backport 2.x, skip-changelog
