Repository opensearch-project/OpenSearch, pull requests merged in 2025-07, with the labels that each got.

#18069 Making snapshot store/restore rate dynamic
  CHANGELOG.md
  plugins/repository-hdfs/src/test/java/org/opensearch/repositories/hdfs/HdfsTests.java
  server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/ConcurrentSnapshotsIT.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: enhancement, Storage:Snapshots

#18631 Extend Profiler to allow for non-timing info
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/main/java/org/opensearch/search/profile/AbstractInternalProfileTree.java
  server/src/main/java/org/opensearch/search/profile/AbstractProfileBreakdown.java
  server/src/main/java/org/opensearch/search/profile/AbstractProfiler.java
  server/src/main/java/org/opensearch/search/profile/ContextualProfileBreakdown.java
  server/src/main/java/org/opensearch/search/profile/ProfileMetric.java
  server/src/main/java/org/opensearch/search/profile/ProfileMetricUtil.java
  server/src/main/java/org/opensearch/search/profile/ProfileResult.java
  server/src/main/java/org/opensearch/search/profile/Profilers.java
  server/src/main/java/org/opensearch/search/profile/Timer.java
  server/src/main/java/org/opensearch/search/profile/aggregation/AggregationProfileBreakdown.java
  server/src/main/java/org/opensearch/search/profile/aggregation/ConcurrentAggregationProfiler.java
  server/src/main/java/org/opensearch/search/profile/query/AbstractQueryProfileTree.java
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdown.java
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfileTree.java
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfiler.java
  server/src/main/java/org/opensearch/search/profile/query/InternalQueryProfileTree.java
  server/src/main/java/org/opensearch/search/profile/query/ProfileScorer.java
  server/src/main/java/org/opensearch/search/profile/query/ProfileWeight.java
  server/src/main/java/org/opensearch/search/profile/query/QueryProfileBreakdown.java
  server/src/main/java/org/opensearch/search/profile/query/QueryProfiler.java
  server/src/test/java/org/opensearch/search/profile/AbstractProfileBreakdownTests.java
  server/src/test/java/org/opensearch/search/profile/ProfileMetricTests.java
  server/src/test/java/org/opensearch/search/profile/TimerTests.java
  server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfileBreakdownTests.java
  server/src/test/java/org/opensearch/search/profile/query/ConcurrentQueryProfilerTests.java
  server/src/test/java/org/opensearch/search/profile/query/ProfileScorerTests.java
Labels: Search, v3.2.0

#18640 [Bug Fix] Fix the backward compatibility regression with `COMPLEMENT` for Regexp queries introduced in OpenSearch 3.0
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
  server/src/main/java/org/opensearch/index/query/RegexpQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/RegexpQueryBuilderTests.java
Labels: lucene, v3.2.0

#18602 Fix bugs in replication lag computation
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicator.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicatorTests.java
Labels: bug, Indexing:Replication

#18637 Inject QueryCollectorSpecFactory from Plugins to create QueryCollectorContext in QueryPhase
  CHANGELOG.md
  server/src/main/java/org/opensearch/plugins/SearchPlugin.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/query/QueryCollectorArguments.java
  server/src/main/java/org/opensearch/search/query/QueryCollectorContextSpec.java
  server/src/main/java/org/opensearch/search/query/QueryCollectorContextSpecFactory.java
  server/src/main/java/org/opensearch/search/query/QueryCollectorContextSpecRegistry.java
  server/src/main/java/org/opensearch/search/query/QueryPhase.java
  server/src/test/java/org/opensearch/search/query/QueryCollectorArgumentsTests.java
  server/src/test/java/org/opensearch/search/query/QueryCollectorContextSpecRegistryTests.java
Labels: Search, v3.2.0

#18636 Fix checkpoint handling to prevent segment replication infinite loop
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Labels: bug, skip-changelog, Storage:Remote

#18530 Extend Approximation Framework to other numeric types
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/RangeQueryBuilderTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: lucene, v3.2.0

#18593 Add support for custom index name resolver from cluster plugin
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
  server/src/main/java/org/opensearch/plugins/ClusterPlugin.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexNameExpressionResolverTests.java
Labels: enhancement, Plugins

#18662 Remove clone holder and add Cleaner logic to clean up clones in FullFileCachedIndexInput
  server/src/main/java/org/opensearch/index/store/remote/filecache/FullFileCachedIndexInput.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FullFileCachedIndexInputTests.java
Labels: bug, skip-changelog, Storage:Remote

#18677 [Backport 2.19] Fix checkpoint handling to prevent segment replication infinite loop
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
Labels: skip-changelog

#18557 Added support for range version support in semver
  libs/core/src/main/java/org/opensearch/semver/SemverRange.java
  libs/core/src/main/java/org/opensearch/semver/expr/Range.java
  libs/core/src/test/java/org/opensearch/semver/SemverRangeTests.java
  libs/core/src/test/java/org/opensearch/semver/expr/RangeTests.java
Labels: enhancement, Plugins, skip-changelog

#18690 Add Prudhvi Godithi (GH: prudhvigodithi) as a maintainer
  MAINTAINERS.md
Labels: skip-changelog, backport 2.19

#18697 Include named queries from rescore contexts in matched_queries array
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/350_matched_queries.yml
  server/src/main/java/org/opensearch/search/dfs/DfsPhase.java
  server/src/main/java/org/opensearch/search/fetch/subphase/MatchedQueriesPhase.java
  server/src/main/java/org/opensearch/search/rescore/QueryRescorer.java
  server/src/main/java/org/opensearch/search/rescore/QueryRescorerBuilder.java
  server/src/main/java/org/opensearch/search/rescore/RescoreContext.java
  server/src/test/java/org/opensearch/search/rescore/QueryRescorerBuilderTests.java
Labels: enhancement, Search:Query Capabilities

#18715 Fix max_score is null when using _score as a primary sort
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/400_max_score.yml
  server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
  server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
Labels: bug, Search

#18610 Changes for the Upload Workflow for merged segments
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreUploader.java
  server/src/main/java/org/opensearch/index/shard/RemoteStoreUploaderService.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreUploaderServiceTests.java
Labels: skip-changelog

#18710 `Lucene.java` Code Improvement
  server/src/main/java/org/opensearch/common/lucene/Lucene.java
Labels: skip-changelog, lucene

#18660 Fix sync method to account for block files in Composite Directory
  server/src/main/java/org/opensearch/index/store/CompositeDirectory.java
  server/src/test/java/org/opensearch/index/store/CompositeDirectoryTests.java
Labels: bug, skip-changelog, Storage:Remote, lucene

#18494 [Cleanup] Remove upgrade-cli tool and related build references
  .github/dependabot.yml
  distribution/build.gradle
  distribution/src/bin/opensearch-upgrade
  distribution/src/bin/opensearch-upgrade.bat
  distribution/tools/upgrade-cli/build.gradle
  distribution/tools/upgrade-cli/licenses/jackson-LICENSE
  distribution/tools/upgrade-cli/licenses/jackson-NOTICE
  distribution/tools/upgrade-cli/licenses/jackson-annotations-2.18.2.jar.sha1
  distribution/tools/upgrade-cli/licenses/jackson-databind-2.18.2.jar.sha1
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/DetectEsInstallationTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/ImportJvmOptionsTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/ImportKeystoreTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/ImportLog4jPropertiesTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/ImportYmlConfigTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/InstallPluginsTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/KeystoreWrapperUtil.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/TaskInput.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/UpgradeCli.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/UpgradeTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/ValidateInputTask.java
  distribution/tools/upgrade-cli/src/main/java/org/opensearch/tools/cli/upgrade/package-info.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/tools/cli/upgrade/DetectEsInstallationTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/tools/cli/upgrade/ImportLog4jPropertiesTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/tools/cli/upgrade/ImportYmlConfigTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/tools/cli/upgrade/InstallPluginsTaskTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/tools/cli/upgrade/UpgradeCliTests.java
  distribution/tools/upgrade-cli/src/test/java/org/opensearch/tools/cli/upgrade/ValidateInputTaskTests.java
  distribution/tools/upgrade-cli/src/test/resources/config/elasticsearch.keystore
  distribution/tools/upgrade-cli/src/test/resources/config/elasticsearch.yml
  distribution/tools/upgrade-cli/src/test/resources/config/jvm.options.d/test.options
  distribution/tools/upgrade-cli/src/test/resources/config/log4j2.properties
  settings.gradle
Labels: enhancement, good first issue, skip-changelog, Other

#18661 Check CircuitBreaker before put/compute in FileCache to avoid entry removal
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
Labels: bug, skip-changelog, Storage:Remote

#18774 [Backport 2.19] Add json-smart to version catalog
  gradle/libs.versions.toml
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/accessors-smart-2.5.1.jar.sha1
  plugins/repository-azure/licenses/accessors-smart-2.5.2.jar.sha1
  plugins/repository-azure/licenses/json-smart-2.5.1.jar.sha1
  plugins/repository-azure/licenses/json-smart-2.5.2.jar.sha1
  plugins/repository-hdfs/build.gradle
  plugins/repository-hdfs/licenses/json-smart-2.5.1.jar.sha1
  plugins/repository-hdfs/licenses/json-smart-2.5.2.jar.sha1
  test/fixtures/hdfs-fixture/build.gradle
Labels: skip-changelog

#18771 Add permission to read /sys/fs/cgroup/system.slice/hosted-compute-agent.service/memory.max in security.policy
  server/src/main/resources/org/opensearch/bootstrap/security.policy
Labels: skip-changelog

#18724 Add combined_fields query to utilize Lucene's CombinedField (BM25F Text)
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/400_combined_fields.yml
  server/src/main/java/org/opensearch/index/query/CombinedFieldsQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/QueryBuilders.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/test/java/org/opensearch/index/query/CombinedFieldsQueryBuilderTests.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
Labels: enhancement, help wanted, feature, Search, lucene

#18786 Mute newly introduced RemoteCloseIndexIT pending fix
  server/src/internalClusterTest/java/org/opensearch/indices/state/RemoteCloseIndexIT.java
Labels: skip-changelog

#18597 fix the bug of Access denied error when rolling log files
  CHANGELOG.md
  server/src/main/resources/org/opensearch/bootstrap/security.policy
Labels: bug, security, Other, _No response_

#18801 Fix flaky RemoteCloseIndexIT test
  server/src/internalClusterTest/java/org/opensearch/indices/state/CloseIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/state/RemoteCloseIndexIT.java
Labels: skip-changelog

#18767 FS stats for warm nodes based on addressable space
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheSettings.java
  server/src/main/java/org/opensearch/monitor/MonitorService.java
  server/src/main/java/org/opensearch/monitor/fs/FsServiceProvider.java
  server/src/main/java/org/opensearch/monitor/fs/WarmFsService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/monitor/fs/WarmFsServiceTests.java
Labels: Meta, Storage:Remote

#18810 Update JDK 21 to 21.0.8+9
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  gradle/libs.versions.toml
Labels: skip-changelog, Build

#18498 Apply boolean must_not rewrite to numeric match, term, and terms queries
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/query/BooleanQueryIT.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/query/BoolQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/ComplementAwareQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/ComplementHelperUtils.java
  server/src/main/java/org/opensearch/index/query/MatchQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/RangeQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/TermQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/TermsQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/BoolQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/MatchQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/TermQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/TermsQueryBuilderTests.java
Labels: stalled

#18536 Support for IndexSort in Nested Fields
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.sort/10_basic.yml
  server/src/internalClusterTest/java/org/opensearch/index/IndexSortIT.java
  server/src/main/java/org/opensearch/common/lucene/Lucene.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/mapper/DocumentMapper.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java
  server/src/test/java/org/opensearch/index/shard/StoreRecoveryTests.java
Labels: skip-changelog, lucene

#18858 Update Github Actions to use JDK-24
  .github/workflows/assemble.yml
  .github/workflows/precommit.yml
  plugins/repository-hdfs/build.gradle
Labels: skip-changelog

#18855 [BUG] Repository s3 plugin test S3RepositoryThirdPartyTests.java does not have an option to override path_style_access and endpoint #18796
  plugins/repository-s3/README.md
  plugins/repository-s3/build.gradle
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java
Labels: skip-changelog

#18763 Disable Approximation when dealing with multiple sorts
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/approximate/ApproximateMatchAllQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: bug, v3.2.0
