Repository opensearch-project/OpenSearch, pull requests merged in 2025-08, with the labels that each got.

#18195 Enhance terms lookup query to take a query clause
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/171_terms_lookup_query.yml
  server/src/main/java/org/opensearch/index/query/TermsQueryBuilder.java
  server/src/main/java/org/opensearch/indices/TermsLookup.java
  server/src/test/java/org/opensearch/index/query/TermQueryWithDocIdAndQueryTests.java
  server/src/test/java/org/opensearch/index/query/TermsQueryBuilderTests.java
  server/src/test/java/org/opensearch/indices/TermsLookupTests.java
Labels: enhancement, Search:Query Capabilities

#18834 Add ACL-aware routing processors for multi-tenant document routing
  CHANGELOG.md
  modules/ingest-common/src/internalClusterTest/java/org/opensearch/ingest/common/AclRoutingProcessorIT.java
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/AclRoutingProcessor.java
  modules/ingest-common/src/main/java/org/opensearch/ingest/common/IngestCommonModulePlugin.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/AclRoutingProcessorTests.java
  modules/ingest-common/src/test/java/org/opensearch/ingest/common/IngestCommonModulePluginTests.java
  modules/search-pipeline-common/src/internalClusterTest/java/org/opensearch/search/pipeline/common/AclRoutingSearchProcessorIT.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/AclRoutingSearchProcessor.java
  modules/search-pipeline-common/src/main/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePlugin.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/AclRoutingSearchProcessorTests.java
  modules/search-pipeline-common/src/test/java/org/opensearch/search/pipeline/common/SearchPipelineCommonModulePluginTests.java
Labels: enhancement, discuss, Search, ShardManagement:Routing

#18848 Ignore attribute awareness when custom preference is set
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
Labels: bug, Search

#18891 Fix flakey test testOverflowDisabledAsynchronous
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTestCase.java
Labels: skip-changelog

#18773 Add option to enable remote store for segments only
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/remotestore/RemoteStoreNodeAttribute.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
Labels: bug, skip-changelog, Storage:Remote

#18885 Ignore archived settings on update
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/settings/ArchivedIndexSettingsIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
Labels: bug, enhancement, good first issue, Plugins, distributed framework, API

#18722 API changes for stream transport and stream based search transport action
  CHANGELOG.md
  server/src/main/java/org/opensearch/OpenSearchServerException.java
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/main/java/org/opensearch/action/search/SearchRequestBuilder.java
  server/src/main/java/org/opensearch/action/search/SearchTransportService.java
  server/src/main/java/org/opensearch/action/search/StreamSearchAction.java
  server/src/main/java/org/opensearch/action/search/StreamSearchTransportService.java
  server/src/main/java/org/opensearch/action/search/StreamTransportSearchAction.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/action/support/StreamChannelActionListener.java
  server/src/main/java/org/opensearch/cluster/StreamNodeConnectionsService.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/common/network/NetworkModule.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/telemetry/tracing/channels/TraceableTcpTransportChannel.java
  server/src/main/java/org/opensearch/telemetry/tracing/handler/TraceableTransportResponseHandler.java
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/main/java/org/opensearch/transport/ConnectionProfile.java
  server/src/main/java/org/opensearch/transport/RemoteConnectionStrategy.java
  server/src/main/java/org/opensearch/transport/StreamTransportResponseHandler.java
  server/src/main/java/org/opensearch/transport/StreamTransportService.java
  server/src/main/java/org/opensearch/transport/TaskTransportChannel.java
  server/src/main/java/org/opensearch/transport/TransportChannel.java
  server/src/main/java/org/opensearch/transport/TransportMessageListener.java
  server/src/main/java/org/opensearch/transport/TransportRequestOptions.java
  server/src/main/java/org/opensearch/transport/TransportResponseHandler.java
  server/src/main/java/org/opensearch/transport/TransportService.java
  server/src/main/java/org/opensearch/transport/client/Client.java
  server/src/main/java/org/opensearch/transport/client/node/NodeClient.java
  server/src/main/java/org/opensearch/transport/client/support/AbstractClient.java
  server/src/main/java/org/opensearch/transport/stream/StreamErrorCode.java
  server/src/main/java/org/opensearch/transport/stream/StreamException.java
  server/src/main/java/org/opensearch/transport/stream/StreamTransportResponse.java
  server/src/main/java/org/opensearch/transport/stream/StreamingTransportChannel.java
  server/src/main/java/org/opensearch/transport/stream/package-info.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
  server/src/test/java/org/opensearch/transport/ConnectionProfileTests.java
  test/framework/src/main/java/org/opensearch/node/MockNode.java
  test/framework/src/main/java/org/opensearch/test/transport/MockTransportService.java
  test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
  test/framework/src/main/java/org/opensearch/transport/TestProfiles.java
Labels: v3.2.0

#18860 Issue #9675: [Remote Store] Add negative test cases and improve cluster stability validation in RemoteStoreRepositoryRegistrationIT
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreRepositoryRegistrationIT.java
Labels: enhancement, good first issue, skip-changelog, Storage, Storage:Remote

#18915 [GRPC] Remove `experimental` designation from transport-grpc settings
  CHANGELOG.md
  modules/transport-grpc/README.md
  modules/transport-grpc/build.gradle
  modules/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/Netty4GrpcServerTransport.java
  modules/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransport.java
Labels: Meta, v3.0.0, Performance, Search, Search:Performance, Roadmap:Cost/Performance/Scale, v3.2.0

#18911 Reset isPipelineResolved to false to resolve the system ingest pipeline again.
  CHANGELOG.md
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
Labels: bug, Indexing

#18928 Fix gRPC initialized even without aux type registered
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/GrpcPlugin.java
Labels: skip-changelog

#18531 [Composite Terms Aggregation] Optimize by removing unnecessary object allocations
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeValuesCollectorQueue.java
Labels: Search:Aggregations, skip-changelog, Search:Performance, v3.2.0

#18671 [Star Tree] IP field search support
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/DimensionFilterMapper.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DimensionFilterAndMapperTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java
Labels: enhancement, Search:Aggregations, v3.1.0, v3.2.0

#18933 Fix Gradle version minimum requirements
  buildSrc/src/main/resources/minimumGradleVersion
Labels: skip-changelog

#18565 Add integration of derived source feature across various paths like get/search/recovery
  CHANGELOG.md
  modules/reindex/src/test/java/org/opensearch/index/reindex/ReindexBasicTests.java
  server/src/internalClusterTest/java/org/opensearch/get/GetActionIT.java
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RecoveryWhileUnderLoadIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/update/UpdateIT.java
  server/src/main/java/org/opensearch/common/lucene/index/DerivedSourceDirectoryReader.java
  server/src/main/java/org/opensearch/common/lucene/index/DerivedSourceLeafReader.java
  server/src/main/java/org/opensearch/common/lucene/index/DerivedSourceStoredFieldsReader.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java
  server/src/main/java/org/opensearch/index/mapper/DocumentMapperParser.java
  server/src/main/java/org/opensearch/index/mapper/FieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/Mapper.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/RootObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/SortedSetDocValuesFetcher.java
  server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/LocalTranslog.java
  server/src/main/java/org/opensearch/index/translog/RemoteBlobStoreInternalTranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTranslog.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogFactory.java
  server/src/main/java/org/opensearch/index/translog/TranslogOperationHelper.java
  server/src/main/java/org/opensearch/index/translog/TranslogWriter.java
  server/src/main/java/org/opensearch/index/translog/TruncateTranslogAction.java
  server/src/main/java/org/opensearch/index/translog/WriteOnlyTranslogManager.java
  server/src/test/java/org/opensearch/common/lucene/index/DerivedSourceDirectoryReaderTests.java
  server/src/test/java/org/opensearch/common/lucene/index/DerivedSourceLeafReaderTests.java
  server/src/test/java/org/opensearch/common/lucene/index/DerivedSourceStoredFieldsReaderTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/engine/TranslogLeafReaderTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/SourceFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
  server/src/test/java/org/opensearch/index/translog/InternalTranslogManagerTests.java
  server/src/test/java/org/opensearch/index/translog/LocalTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/RemoteFsTranslogTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogDeletionPolicyTests.java
  server/src/test/java/org/opensearch/index/translog/TranslogManagerTestCase.java
  server/src/test/java/org/opensearch/index/translog/TranslogOperationHelperTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
  test/framework/src/main/java/org/opensearch/test/BackgroundIndexer.java
Labels: enhancement, Indexing:Performance

#18857 Add support for custom remote store segment path prefix to support clusterless configurations
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/remote/RemoteStorePathStrategy.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryFactory.java
  server/src/main/java/org/opensearch/index/store/lockmanager/RemoteStoreLockManagerFactory.java
  server/src/test/java/org/opensearch/cluster/metadata/IndexMetadataTests.java
  server/src/test/java/org/opensearch/index/remote/RemoteStorePathStrategyTests.java
Labels: enhancement, Storage:Remote

#18896 Approximation framework to support numeric `search_after` queries
  CHANGELOG.md
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/ScaledFloatFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/NumericPointEncoder.java
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/NumberFieldMapperTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: enhancement, Search:Performance, Roadmap:Search, lucene, v3.2.0

#18910 Expose SETTING_GRPC_MAX_MSG_SIZE to settings service
  CHANGELOG.md
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/GrpcPlugin.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/GrpcPluginTests.java
Labels: skip-changelog

#18955 Update commonslang to use 3.18.0
  gradle/libs.versions.toml
  plugins/ingest-attachment/licenses/commons-lang3-3.14.0.jar.sha1
  plugins/ingest-attachment/licenses/commons-lang3-3.18.0.jar.sha1
  plugins/repository-azure/licenses/commons-lang3-3.14.0.jar.sha1
  plugins/repository-azure/licenses/commons-lang3-3.18.0.jar.sha1
  plugins/repository-hdfs/build.gradle
Labels: skip-changelog, backport 3.2

#18967 Update changelog file
  CHANGELOG.md
  release-notes/opensearch.release-notes-3.2.0.md
Labels: backport 3.2

#18958 [Backport 2.19] Fix segment replication bug during primary relocation
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
Labels: skip-changelog

#18702 Optimization in Numeric Terms Aggregation query for Large Bucket Counts
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/BucketSelectionStrategy.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregator.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregatorTests.java
Labels: bug, Search:Performance

#18925 [GRPC] Map to proper GRPC status codes and achieve exception handling parity with HTTP
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/ExceptionsHelper.java
  libs/core/src/main/java/org/opensearch/OpenSearchException.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/listeners/BulkRequestActionListener.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/listeners/SearchRequestActionListener.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/response/document/bulk/BulkItemResponseProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/services/DocumentServiceImpl.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/services/SearchServiceImpl.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/util/GrpcErrorHandler.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/util/RestToGrpcStatusConverter.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/util/package-info.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/listeners/SearchRequestActionListenerTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/response/BulkResponseProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/response/document/bulk/BulkItemResponseProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/util/GrpcErrorHandlerTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/util/RestToGrpcStatusConverterTests.java
  server/src/test/java/org/opensearch/ExceptionsHelperTests.java
Labels: enhancement, Libraries

#18987 Update permission for read in /sys/fs/cgroup/system.slice/- path
  distribution/packages/src/common/systemd/opensearch.service
  server/src/main/resources/org/opensearch/bootstrap/security.policy
Labels: release, backport main, skip-changelog, v3.2.0

#19002 [Backport 3.2] Exclude commons-beanutils from dep on hadoop-miniclusters
  test/fixtures/hdfs-fixture/build.gradle
Labels: skip-changelog

#19001 [Forwardport main] Exclude commons-beanutils from dep on hadoop-miniclusters
  test/fixtures/hdfs-fixture/build.gradle
Labels: skip-changelog

#18936 Expand fetch phase profiling to support inner hits and top hits aggregation phases
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search.profile/10_fetch_phase.yml
  server/src/internalClusterTest/java/org/opensearch/search/profile/aggregation/AggregationProfilerIT.java
  server/src/internalClusterTest/java/org/opensearch/search/profile/fetch/FetchProfilerIT.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/TopHitsAggregator.java
  server/src/main/java/org/opensearch/search/fetch/FetchPhase.java
  server/src/main/java/org/opensearch/search/fetch/subphase/InnerHitsPhase.java
  server/src/main/java/org/opensearch/search/profile/fetch/FlatFetchProfileTree.java
  server/src/test/java/org/opensearch/search/fetch/FetchProfilePhaseTests.java
  server/src/test/java/org/opensearch/search/profile/fetch/FetchProfilerTests.java
Labels: enhancement, Search:Query Insights

#19032 fix flaky WeightedRoutingIT
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#19024 Fix faulty assertion in AutoForceMergeManagerTests
  server/src/test/java/org/opensearch/index/autoforcemerge/AutoForceMergeManagerTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#18993 [Backport 2.19] Fix CloseIndexIT test (#18946)
  server/src/internalClusterTest/java/org/opensearch/indices/state/CloseIndexIT.java
Labels: skip-changelog

#18825 Add false_allow_templates as a dynamic mapping option
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/111_false_allow_templates.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.put_mapping/all_path_options.yml
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/test/java/org/opensearch/index/mapper/CopyToMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
  server/src/test/java/org/opensearch/index/mapper/DynamicMappingTests.java
Labels: enhancement, Indexing

#19065 Add `false_allow_templates` as a dynamic mapping option
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/111_false_allow_templates.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.put_mapping/all_path_options.yml
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/test/java/org/opensearch/index/mapper/CopyToMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/DocumentParserTests.java
  server/src/test/java/org/opensearch/index/mapper/DynamicMappingTests.java
Labels: enhancement, Indexing

#19049 Fix the version check in 400_max_score.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/400_max_score.yml
Labels: skip-changelog

#19077 Reverts accidental access changes in IpFieldMapper parser util
  server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java
  server/src/main/java/org/opensearch/search/startree/StarTreeQueryHelper.java
Labels: non-issue, skip-changelog

#18297 Set context class loader to plugin's class loader when creating kafka consumer
  plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaPartitionConsumer.java
Labels: skip-changelog

#19076 Fix flaky CompletionStatsCacheTests.testCompletionStatsCache
  server/src/test/java/org/opensearch/index/engine/CompletionStatsCacheTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#19066 Add circuit breaking logic for shard level results
  .idea/runConfigurations/Debug_OpenSearch.xml
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/search/QueryPhaseResultConsumer.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseController.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/test/java/org/opensearch/action/search/QueryPhaseResultConsumerTests.java
  server/src/test/java/org/opensearch/action/search/SearchPhaseControllerTests.java
Labels: bug, Search

#19072 Clone index input in multipart upload flow
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/test/java/org/opensearch/index/shard/RemoteStoreRefreshListenerTests.java
Labels: skip-changelog

#19091 Add StoreFactory plugin interface for custom Store implementations
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/IndexStorePlugin.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/plugins/IndexStorePluginTests.java
Labels: enhancement, Indexing:Replication

#18766 [Bug Fix] fix skip_unavailable setting changing to default during node drop
  CHANGELOG.md
  qa/ccs-unavailable-clusters/src/test/java/org/opensearch/search/CrossClusterSearchUnavailableClusterIT.java
  server/src/main/java/org/opensearch/transport/RemoteClusterAware.java
Labels: bug, Search

#19083 Attempt to fix flaky AzureBlobStoreRepositoryTests
  plugins/repository-gcs/src/internalClusterTest/java/org/opensearch/repositories/gcs/GoogleCloudStorageThirdPartyTests.java
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java
  test/framework/src/main/java/org/opensearch/repositories/AbstractThirdPartyRepositoryTestCase.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchBlobStoreRepositoryIntegTestCase.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, Storage:Snapshots

#19113 Fix access specifier for FieldMapper method to allow usage by plugins
  modules/mapper-extras/src/javaRestTest/java/org/opensearch/index/mapper/ScaledFloatDerivedSourceIT.java
  server/src/main/java/org/opensearch/index/mapper/FieldMapper.java
Labels: skip-changelog

#19050 [Backport 3.2] Fix max_score yaml test is skipped
  rest-api-spec/src/main/resources/rest-api-spec/test/search/400_max_score.yml
Labels: skip-changelog

#19159 Update comments and errors messages for: Replace centos:8 with almalinux:8
  distribution/docker/build.gradle
Labels: skip-changelog

#18389 Replace usage of deprecated createIndex() method in tests
  modules/analysis-common/src/test/java/org/opensearch/analysis/common/DisableGraphQueryTests.java
  modules/lang-painless/src/test/java/org/opensearch/painless/NeedsScoreTests.java
  modules/lang-painless/src/test/java/org/opensearch/painless/action/PainlessExecuteApiTests.java
  modules/percolator/src/test/java/org/opensearch/percolator/PercolatorQuerySearchTests.java
  plugins/mapper-size/src/internalClusterTest/java/org/opensearch/index/mapper/size/SizeMappingTests.java
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/search/aggregations/FiltersAggsRewriteIT.java
  server/src/test/java/org/opensearch/action/termvectors/GetTermVectorsTests.java
  server/src/test/java/org/opensearch/index/analysis/PreBuiltAnalyzerTests.java
  server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/MapperServiceTests.java
  server/src/test/java/org/opensearch/index/mapper/NestedObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/UpdateMappingTests.java
  server/src/test/java/org/opensearch/index/search/NestedHelperTests.java
  server/src/test/java/org/opensearch/index/search/nested/NestedSortingTests.java
  server/src/test/java/org/opensearch/index/similarity/SimilarityTests.java
  server/src/test/java/org/opensearch/index/termvectors/TermVectorsServiceTests.java
  server/src/test/java/org/opensearch/search/aggregations/AggregatorBaseTests.java
  server/src/test/java/org/opensearch/search/aggregations/support/ValuesSourceConfigTests.java
  server/src/test/java/org/opensearch/search/fetch/subphase/FieldFetcherTests.java
  server/src/test/java/org/opensearch/search/fetch/subphase/highlight/DerivedFieldFetchAndHighlightTests.java
  server/src/test/java/org/opensearch/search/geo/GeoShapeQueryTests.java
  server/src/test/java/org/opensearch/search/suggest/completion/CategoryContextMappingTests.java
  server/src/test/java/org/opensearch/search/suggest/completion/GeoContextMappingTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
Labels: skip-changelog

#18981 Update delete_backport_branch workflow to include release-chores branches
  .github/workflows/delete_backport_branch.yml
Labels: skip-changelog

#19171 Fix deadlock in SearchPhaseControllerTests cancellation tests
  server/src/test/java/org/opensearch/action/search/SearchPhaseControllerTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#19053 Remove the setShardIndex parameter in CollapseTopFieldDocs.merge()
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/110_field_collapsing.yml
  server/src/main/java/org/apache/lucene/search/grouping/CollapseTopFieldDocs.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseController.java
  server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
  server/src/test/java/org/opensearch/lucene/grouping/CollapsingTopDocsCollectorTests.java
  server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
Labels: bug, Search

#19164 Handling concurrent segment search as part of fetch profiling
  server/src/main/java/org/opensearch/search/profile/fetch/FlatFetchProfileTree.java
Labels: >test-failure, flaky-test, autocut, skip-changelog
