Repository opensearch-project/OpenSearch, pull requests merged in 2025-03, with the labels that each got.

#17444 [Pull-based Ingestion] add basic NodeStats metrics
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/TransportClusterStatsAction.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/ShardStats.java
  server/src/main/java/org/opensearch/action/admin/indices/stats/TransportIndicesStatsAction.java
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/engine/IngestionEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
  server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java
  server/src/main/java/org/opensearch/indices/pollingingest/PollingIngestStats.java
  server/src/main/java/org/opensearch/indices/pollingingest/StreamPoller.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/stats/NodeStatsTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodesTests.java
  server/src/test/java/org/opensearch/action/admin/cluster/stats/ClusterStatsResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/rollover/TransportRolloverActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/shards/CatShardsResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/stats/IndicesStatsResponseTests.java
  server/src/test/java/org/opensearch/cluster/DiskUsageTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  server/src/test/java/org/opensearch/indices/pollingingest/PollingIngestStatsTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java
Labels: enhancement, skip-changelog, Indexing

#17165 [Star Tree] [Search] Keyword & Numeric Terms Aggregation
  CHANGELOG-3.0.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/BucketsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregator.java
  server/src/main/java/org/opensearch/search/startree/StarTreeQueryContext.java
  server/src/main/java/org/opensearch/search/startree/StarTreeQueryHelper.java
  server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/KeywordTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/NumericTermsAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, Search:Aggregations

#17286 fix explain action on query rewrite
  CHANGELOG-3.0.md
  server/src/internalClusterTest/java/org/opensearch/explain/ExplainActionIT.java
  server/src/main/java/org/opensearch/action/explain/TransportExplainAction.java
Labels: enhancement

#17427 [Pull-based Ingestion] Add error handling strategy to pull-based ingestion
  CHANGELOG-3.0.md
  plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaPartitionConsumer.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IngestionShardConsumer.java
  server/src/main/java/org/opensearch/index/engine/IngestionEngine.java
  server/src/main/java/org/opensearch/indices/pollingingest/BlockIngestionErrorStrategy.java
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
  server/src/main/java/org/opensearch/indices/pollingingest/DropIngestionErrorStrategy.java
  server/src/main/java/org/opensearch/indices/pollingingest/IngestionErrorStrategy.java
  server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java
  server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java
  server/src/test/java/org/opensearch/index/engine/FakeIngestionSource.java
  server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
Labels: enhancement, Indexing

#17207 Fix Bug - Handle unsigned long in sorting order assertion of LongHashSet
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/document/SortedUnsignedLongDocValuesSetQuery.java
  server/src/main/java/org/opensearch/lucene/util/UnsignedLongHashSet.java
  server/src/test/java/org/opensearch/lucene/util/DocValuesUnsignedLongHashSetTests.java
Labels: bug, backport 2.x, Search

#17508 Add Windows 2025+Java 21 combination to build matrix
  .github/workflows/precommit.yml
Labels: CI, skip-changelog

#17516 Resolve typo in 2.x jdk version 21
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
Labels: enhancement, skip-changelog, backport 2.19

#17410 Add sample integ tests for latest systemd unit file
  CHANGELOG-3.0.md
  qa/systemd-test/build.gradle
  qa/systemd-test/src/test/java/org/opensearch/systemdinteg/SystemdIntegTests.java
  qa/systemd-test/src/test/resources/scripts/terminate.sh
Labels: v3.0.0

#17512 Small typo found while reading DEVELOPER_GUIDE.md
  DEVELOPER_GUIDE.md
Labels: skip-changelog

#17521 Fix red index on close for remote enabled clusters
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
Labels: skip-changelog

#17390 Writable warm replica replication/recovery
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationUsingRemoteStoreIT.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/IndexMetadataUpdater.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/CompositeDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/utils/FileTypeUtils.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/test/java/org/opensearch/index/store/CompositeDirectoryTests.java
Labels: enhancement, skip-changelog, Storage:Remote, Roadmap:Search, v2.16.0

#17502 Change IOContext from READONCE to DEFAULT to avoid WrongThreadException
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  test/framework/src/main/java/org/opensearch/test/store/MockFSDirectoryFactory.java
Labels: backport 2.x, skip-changelog, backport 2.19

#17535 Fix flaky tests in RemoteStoreStatsIT
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, Storage:Remote

#17546 Fix compilation issue for #17535 backport PR
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
Labels: skip-changelog

#17545 Change IOContext from READONCE to DEFAULT to avoid WrongThreadException (#17502)
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  test/framework/src/main/java/org/opensearch/test/store/MockFSDirectoryFactory.java
Labels: skip-changelog

#17547 Add test for stale writer correctness with pinned timestamp snapshots
  server/src/test/java/org/opensearch/index/remote/RemoteStoreUtilsTests.java
Labels: skip-changelog

#17548 [Backport 2.x] Fix flaky tests in RemoteStoreStatsIT
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreStatsIT.java
  server/src/main/java/org/opensearch/index/remote/RemoteSegmentTransferTracker.java
Labels: skip-changelog

#17344 [Tiered Caching] Remove PLUGGABLE_CACHE feature flag
  CHANGELOG-3.0.md
  distribution/src/config/opensearch.yml
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheBaseIT.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCachePluginTests.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  plugins/cache-ehcache/src/internalClusterTest/java/org/opensearch/cache/EhcacheDiskCacheIT.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  server/src/internalClusterTest/java/org/opensearch/indices/CacheStatsAPIIndicesRequestCacheIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/IndicesRequestCacheIT.java
  server/src/main/java/org/opensearch/common/cache/service/CacheService.java
  server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/common/cache/service/CacheServiceTests.java
  server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: enhancement, Storage:Performance

#17544 Change IOContext from READONCE to DEFAULT to avoid WrongThreadException (#17502)
  server/src/main/java/org/opensearch/index/shard/RemoteStoreRefreshListener.java
  server/src/main/java/org/opensearch/index/store/RemoteDirectory.java
  server/src/test/java/org/opensearch/index/store/RemoteDirectoryTests.java
  test/framework/src/main/java/org/opensearch/test/store/MockFSDirectoryFactory.java
Labels: skip-changelog

#17569 Add json-smart to version catalog
  gradle/libs.versions.toml
  plugins/repository-azure/build.gradle
  plugins/repository-azure/licenses/accessors-smart-2.5.1.jar.sha1
  plugins/repository-azure/licenses/accessors-smart-2.5.2.jar.sha1
  plugins/repository-azure/licenses/json-smart-2.5.1.jar.sha1
  plugins/repository-azure/licenses/json-smart-2.5.2.jar.sha1
  plugins/repository-hdfs/build.gradle
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport 2.x, skip-changelog

#17555 Update to use RandomAccessInput.readBytes bulk method
  server/src/main/java/org/opensearch/common/util/ByteArrayBackedBitset.java
Labels: skip-changelog

#16776 Fix: visit of inner query for FunctionScoreQueryBuilder
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/query/functionscore/FunctionScoreQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/functionscore/FunctionScoreQueryBuilderTests.java
Labels: bug, stalled, backport 2.x, Search:Query Capabilities

#17578 Add support to run RemoteStoreIT with S3 integration
  plugins/repository-s3/build.gradle
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RemoteStoreIT.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3ClientSettings.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/multipart/RemoteStoreMultipartCoreTestCase.java
  server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java
  test/framework/src/main/java/org/opensearch/remotestore/RemoteStoreBaseIntegTestCase.java
  test/framework/src/main/java/org/opensearch/remotestore/RemoteStoreCoreTestCase.java
  test/framework/src/main/java/org/opensearch/remotestore/mocks/MockFsMetadataSupportedBlobContainer.java
  test/framework/src/main/java/org/opensearch/remotestore/mocks/MockFsMetadataSupportedBlobStore.java
  test/framework/src/main/java/org/opensearch/remotestore/mocks/MockFsMetadataSupportedRepository.java
  test/framework/src/main/java/org/opensearch/remotestore/mocks/MockFsMetadataSupportedRepositoryPlugin.java
  test/framework/src/main/java/org/opensearch/remotestore/multipart/mocks/MockFsAsyncBlobContainer.java
  test/framework/src/main/java/org/opensearch/remotestore/multipart/mocks/MockFsBlobStore.java
  test/framework/src/main/java/org/opensearch/remotestore/multipart/mocks/MockFsRepository.java
  test/framework/src/main/java/org/opensearch/remotestore/multipart/mocks/MockFsRepositoryPlugin.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: skip-changelog

#17576 Add search backpressure service check for query group tasks
  CHANGELOG.md
  server/src/main/java/org/opensearch/wlm/QueryGroupService.java
  server/src/test/java/org/opensearch/wlm/QueryGroupServiceTests.java
Labels: bug, backport 2.x, Search

#17590 [Flaky test fix] Give more time for relocation to complete
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
Labels: >test-failure, flaky-test, backport 2.x, autocut, skip-changelog

#17605 Removing references for 2.20.0 as we not planning to release it
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#17565 [Pull-based Ingestion] Add support for dynamically updating ingestion error handling strategy with minor fixes
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/KafkaIngestionBaseIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/index/engine/IngestionEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/pollingingest/BlockIngestionErrorStrategy.java
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
  server/src/main/java/org/opensearch/indices/pollingingest/DropIngestionErrorStrategy.java
  server/src/main/java/org/opensearch/indices/pollingingest/IngestionErrorStrategy.java
  server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java
  server/src/main/java/org/opensearch/indices/pollingingest/StreamPoller.java
  server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
Labels: skip-changelog

#17573 Renaming the node role search to warm
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterInfoServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/WritableWarmIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/bootstrap/BootstrapChecks.java
  server/src/main/java/org/opensearch/cluster/InternalClusterInfoService.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingPool.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/env/NodeRepurposeCommand.java
  server/src/main/java/org/opensearch/indices/tiering/TieringRequestValidator.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringActionTests.java
  server/src/test/java/org/opensearch/bootstrap/BootstrapChecksTests.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDeciderTests.java
  server/src/test/java/org/opensearch/cluster/structure/RoutingIteratorTests.java
  server/src/test/java/org/opensearch/env/NodeRepurposeCommandTests.java
  server/src/test/java/org/opensearch/indices/tiering/TieringRequestValidatorTests.java
  server/src/test/java/org/opensearch/node/NodeTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/NodeRoles.java
Labels: bug, skip-changelog, Search:Performance

#16445 Change priority for scheduling reroute during timeout
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/allocator/TimeBoundBalancedShardsAllocatorTests.java
  server/src/test/java/org/opensearch/gateway/GatewayAllocatorTests.java
Labels: backport 2.x

#17620 Introduce a new search node role to hold search only shards
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
  server/src/test/java/org/opensearch/cluster/node/DiscoveryNodeTests.java
  server/src/test/java/org/opensearch/monitor/fs/FsProbeTests.java
  server/src/test/java/org/opensearch/node/NodeRoleSettingsTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/NodeRoles.java
Labels: skip-changelog

#17618 Update changelog for new branching strategy
  .github/workflows/changelog_verifier.yml
  CHANGELOG-3.0.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: skip-changelog

#17589 Fix flakiness of RemoteRestoreSnapshotIT.testClusterManagerFailoverDuringSnapshotCreation
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
Labels: >test-failure, flaky-test, autocut, Storage:Remote

#17621 Update beta1 qualifier for 3.0.0 version
  .github/workflows/benchmark-pull-request.yml
  .github/workflows/publish-maven-snapshots.yml
Labels: release, v3.0.0, skip-changelog

#17612 Add dfs transformation function in XContentMapValues
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/xcontent/support/XContentMapValues.java
  server/src/test/java/org/opensearch/common/xcontent/support/XContentMapValuesTests.java
Labels: bug, cicd

#17642 Mute flaky tests - S3RemoteStoreIT
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RemoteStoreIT.java
Labels: skip-changelog

#17644 Remove dead benchmarking code
  benchmarks/src/main/java20/org/opensearch/common/round/RoundableSupplier.java
Labels: skip-changelog

#17604 Bump com.google.api:api-common from 1.8.1 to 2.46.1 in /plugins/repository-gcs
  CHANGELOG.md
  plugins/repository-gcs/build.gradle
  plugins/repository-gcs/licenses/api-common-1.8.1.jar.sha1
  plugins/repository-gcs/licenses/api-common-2.46.1.jar.sha1
Labels: dependencies, backport 2.x

#17505 [bug fix] fix precompute ordering in max & min aggregator
  server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java
Labels: bug, backport 2.x, skip-changelog

#17645 Update dependabot changelog helper for 3.x major version
  .github/workflows/dependabot_pr.yml
Labels: skip-changelog

#17641 Resolve integTest bug on deb to check for opensearch:adm
  CHANGELOG.md
  qa/systemd-test/src/test/java/org/opensearch/systemdinteg/SystemdIntegTests.java
Labels: bug, enhancement, release, v3.0.0, Other

#17238 [Rule-based Auto Tagging] Add rule schema for auto tagging
  CHANGELOG.md
  server/src/main/java/org/opensearch/autotagging/Attribute.java
  server/src/main/java/org/opensearch/autotagging/AutoTaggingRegistry.java
  server/src/main/java/org/opensearch/autotagging/FeatureType.java
  server/src/main/java/org/opensearch/autotagging/Rule.java
  server/src/main/java/org/opensearch/autotagging/RuleValidator.java
  server/src/main/java/org/opensearch/autotagging/package-info.java
  server/src/test/java/org/opensearch/autotagging/AutoTaggingRegistryTests.java
  server/src/test/java/org/opensearch/autotagging/FeatureTypeTests.java
  server/src/test/java/org/opensearch/autotagging/RuleTests.java
  server/src/test/java/org/opensearch/autotagging/RuleValidatorTests.java
Labels: backport 2.x

#17626 Fix flaky test due to incorrect use of SSDV.nextOrd()
  server/src/test/java/org/opensearch/index/fielddata/ordinals/MultiOrdinalsTests.java
Labels: skip-changelog

#17457 Search Replica Allocation and Recovery
  server/src/internalClusterTest/java/org/opensearch/cluster/allocation/SearchReplicaAllocationIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaReplicationAndRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaFeatureFlagIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/SearchReplicaAllocationDecider.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/shard/StoreRecovery.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancerTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/SearchReplicaAllocationDeciderTests.java
  server/src/test/java/org/opensearch/index/shard/IndexShardTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
Labels: bug, enhancement, skip-changelog, Search:Performance

#17640 Fix Flaky Test SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes
  server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java
Labels: >test-failure, flaky-test, autocut

#17663 [Security Manager Replacement] Add support of Java policies
  CHANGELOG.md
  gradle/missing-javadoc.gradle
  libs/agent-sm/agent-policy/build.gradle
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/package-info.java
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/ParseUtil.java
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/Password.java
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PolicyFile.java
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PolicyParser.java
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PolicyUtil.java
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PropertyExpander.java
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/SecurityConstants.java
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/package-info.java
  libs/agent-sm/bootstrap/build.gradle
  libs/agent-sm/bootstrap/src/main/java/org/opensearch/javaagent/bootstrap/AgentPolicy.java
  libs/agent-sm/bootstrap/src/main/java/org/opensearch/javaagent/bootstrap/package-info.java
  libs/agent-sm/bootstrap/src/main/java/org/opensearch/package-info.java
  libs/agent-sm/build.gradle
Labels: enhancement, security, v3.0.0, _No response_

#17688 Authenticate jenkins calls for benchmark workflow
  .github/workflows/benchmark-pull-request.yml
Labels: skip-changelog

#17329 TimeSeries Desc Sort gets skipped with Lucene 10 upgrade
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
Labels: bug, skip-changelog, Search:Performance, Other

#17690 Add simple PolicyParser unit test
  libs/agent-sm/agent-policy/build.gradle
  libs/agent-sm/agent-policy/src/test/java/org/opensearch/secure_sm/policy/PolicyParserTests.java
Labels: skip-changelog

#17691 Authenticate jenkins calls for gradle check
  .github/workflows/gradle-check.yml
Labels: backport 2.x, skip-changelog, backport 2.19

#17724 Create initial Java Agent to intercept Socket::connect calls
  CHANGELOG.md
  gradle/libs.versions.toml
  libs/agent-sm/agent/build.gradle
  libs/agent-sm/agent/licenses/byte-buddy-1.17.4.jar.sha1
  libs/agent-sm/agent/licenses/byte-buddy-LICENSE.txt
  libs/agent-sm/agent/licenses/byte-buddy-NOTICE.txt
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/Agent.java
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SocketChannelInterceptor.java
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerChainExtractor.java
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/package-info.java
  libs/agent-sm/agent/src/main/java/org/opensearch/package-info.java
  libs/agent-sm/bootstrap/build.gradle
  libs/agent-sm/bootstrap/src/main/java/org/opensearch/javaagent/bootstrap/AgentPolicy.java
  libs/agent-sm/bootstrap/src/main/java/org/opensearch/javaagent/bootstrap/package-info.java
  libs/agent-sm/bootstrap/src/main/java/org/opensearch/package-info.java
  libs/agent-sm/build.gradle
  libs/build.gradle
  plugins/repository-azure/licenses/jna-platform-5.13.0.jar.sha1
  plugins/repository-azure/licenses/jna-platform-5.16.0.jar.sha1
  server/licenses/jna-5.13.0.jar.sha1
  server/licenses/jna-5.16.0.jar.sha1
  test/framework/licenses/byte-buddy-1.15.10.jar.sha1
  test/framework/licenses/byte-buddy-1.17.4.jar.sha1
  test/framework/licenses/mockito-core-5.14.2.jar.sha1
  test/framework/licenses/mockito-core-5.16.1.jar.sha1
Labels: enhancement, security, v3.0.0

#17697 attempt to fix flaky test in IngestFromKinesisIT
  plugins/ingestion-kinesis/src/internalClusterTest/java/org/opensearch/plugin/kinesis/IngestFromKinesisIT.java
Labels: skip-changelog

#17652 Support Allocation Awareness for Search replicas
  server/src/internalClusterTest/java/org/opensearch/cluster/allocation/AwarenessAllocationIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/allocation/SearchReplicaAwarenessAllocationIT.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNodes.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AwarenessReplicaBalance.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/AwarenessAllocationDecider.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AwarenessAllocationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AwarenessReplicaBalanceTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/SearchReplicaAwarenessAllocationTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
Labels: enhancement, skip-changelog, Search:Performance
