Repository opensearch-project/OpenSearch, pull requests merged in 2025-09, with the labels that each got.

#19199 Attempt to fix the jdt formatter error
  gradle/formatting.gradle
Labels: CI, skip-changelog, backport 2.19, backport 3.1, backport 3.2

#19212 [Pull-based Ingestion] Fix ingestion pause state initialization on replica promotion
  CHANGELOG.md
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
Labels: >test-failure, flaky-test, autocut

#19132 Add subdirectory-aware store module with recovery support
  CHANGELOG.md
  modules/store-subdirectory/build.gradle
  modules/store-subdirectory/src/internalClusterTest/java/org/opensearch/plugin/store/subdirectory/SubdirectoryAwareRecoveryTests.java
  modules/store-subdirectory/src/main/java/org/opensearch/plugin/store/subdirectory/SubdirectoryAwareStore.java
  modules/store-subdirectory/src/main/java/org/opensearch/plugin/store/subdirectory/SubdirectoryStorePlugin.java
  modules/store-subdirectory/src/main/java/org/opensearch/plugin/store/subdirectory/package-info.java
  modules/store-subdirectory/src/test/java/org/opensearch/plugin/store/subdirectory/SubdirectoryStorePluginTests.java
  server/src/main/java/org/opensearch/index/store/Store.java
  server/src/main/java/org/opensearch/indices/recovery/MultiFileWriter.java
Labels: enhancement, Plugins

#19224 Move Vachashah@ to Emeritus
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#19221 Add Atri Sharma as a maintainer
  MAINTAINERS.md
Labels: skip-changelog

#19197 [Auto Force Merge] Async task initialization fix
  server/src/main/java/org/opensearch/index/autoforcemerge/AutoForceMergeManager.java
Labels: skip-changelog

#19268 Remove errantly added file
  mustache.patch
Labels: skip-changelog

#19239 Replace deprecated AccessController in :server
  server/src/main/java/org/opensearch/bootstrap/OpenSearchUncaughtExceptionHandler.java
  server/src/main/java/org/opensearch/common/util/concurrent/ThreadContextAccess.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/main/java/org/opensearch/plugins/PluginsService.java
  server/src/main/java/org/opensearch/search/lookup/LeafDocLookup.java
  server/src/test/java/org/opensearch/bootstrap/OpenSearchPolicyTests.java
  server/src/test/java/org/opensearch/bootstrap/SecurityTests.java
Labels: skip-changelog

#19274 Add an example plugin for system generated search processors.
  plugins/examples/system-search-processor/build.gradle
  plugins/examples/system-search-processor/src/main/java/org/opensearch/example/systemsearchprocessor/ExampleSearchPhaseResultsProcessor.java
  plugins/examples/system-search-processor/src/main/java/org/opensearch/example/systemsearchprocessor/ExampleSearchRequestPostProcessor.java
  plugins/examples/system-search-processor/src/main/java/org/opensearch/example/systemsearchprocessor/ExampleSearchRequestPreProcessor.java
  plugins/examples/system-search-processor/src/main/java/org/opensearch/example/systemsearchprocessor/ExampleSearchResponseProcessor.java
  plugins/examples/system-search-processor/src/main/java/org/opensearch/example/systemsearchprocessor/ExampleSystemSearchProcessorPlugin.java
  plugins/examples/system-search-processor/src/main/java/org/opensearch/example/systemsearchprocessor/package-info.java
  plugins/examples/system-search-processor/src/test/java/org/opensearch/example/systemsearchprocessor/ExampleSearchPhaseResultsProcessorTests.java
  plugins/examples/system-search-processor/src/test/java/org/opensearch/example/systemsearchprocessor/ExampleSearchRequestPostProcessorTests.java
  plugins/examples/system-search-processor/src/test/java/org/opensearch/example/systemsearchprocessor/ExampleSearchRequestPreProcessorTests.java
  plugins/examples/system-search-processor/src/test/java/org/opensearch/example/systemsearchprocessor/ExampleSearchResponseProcessorTests.java
  plugins/examples/system-search-processor/src/test/java/org/opensearch/example/systemsearchprocessor/ExampleSystemSearchProcessorPluginTests.java
  plugins/examples/system-search-processor/src/yamlRestTest/java/org/opensearch/example/systemsearchprocessor/ExampleSystemSearchProcessorClientYamlTestSuiteIT.java
  plugins/examples/system-search-processor/src/yamlRestTest/resources/rest-api-spec/test/example-system-search-processor/10_basic.yml
  plugins/examples/system-search-processor/src/yamlRestTest/resources/rest-api-spec/test/example-system-search-processor/20_system_search_processor_and_user_defined.yml
  plugins/examples/system-search-processor/src/yamlRestTest/resources/rest-api-spec/test/example-system-search-processor/30_enable_all_system_search_processor.yml
  plugins/examples/system-search-processor/src/yamlRestTest/resources/rest-api-spec/test/example-system-search-processor/40_system_search_processor_with_conflict.yml
Labels: enhancement, skip-changelog, Search

#19261 Field collapsing supports search_after
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/110_field_collapsing.yml
  server/src/main/java/org/apache/lucene/search/grouping/CollapsingTopDocsCollector.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/collapse/CollapseContext.java
  server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
  server/src/test/java/org/opensearch/lucene/grouping/CollapsingTopDocsCollectorTests.java
Labels: enhancement, feature, Indexing & Search

#19303 Issue 19271: Fix DerivedFieldScript to support emitting Float type
  modules/lang-painless/src/test/java/org/opensearch/painless/DerivedFieldScriptTests.java
  server/src/main/java/org/opensearch/script/DerivedFieldScript.java
Labels: bug, skip-changelog, Search

#19088 Date Histogram Optimization with Date Rounding utility refactoring
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/Rounding.java
Labels: Search:Aggregations, Search:Performance, v3.3.0

#19273 Fix regression: preserve not(not X) in BooleanFlatteningRewriter
  server/src/main/java/org/opensearch/search/query/rewriters/BooleanFlatteningRewriter.java
  server/src/test/java/org/opensearch/search/query/QueryRewriterRegistryTests.java
  server/src/test/java/org/opensearch/search/query/rewriters/BooleanFlatteningRewriterTests.java
  server/src/test/java/org/opensearch/search/query/rewriters/MatchAllRemovalRewriterTests.java
  server/src/test/java/org/opensearch/search/query/rewriters/MustNotToShouldRewriterTests.java
  server/src/test/java/org/opensearch/search/query/rewriters/MustToFilterRewriterTests.java
  server/src/test/java/org/opensearch/search/query/rewriters/TermsMergingRewriterTests.java
Labels: bug, skip-changelog, Search

#19318 Add version check in 121_grok_capture_all_matches.yml
  modules/ingest-common/src/yamlRestTest/resources/rest-api-spec/test/ingest/121_grok_capture_all_matches.yml
Labels: skip-changelog

#19316 [Pull-based Ingestion] Support all-active mode in pull-based ingestion
  CHANGELOG.md
  plugins/ingestion-fs/src/test/java/org/opensearch/plugin/ingestion/fs/FileBasedIngestionSingleNodeTests.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaSingleNodeTests.java
  plugins/ingestion-kinesis/src/internalClusterTest/java/org/opensearch/plugin/kinesis/IngestFromKinesisIT.java
  server/src/main/java/org/opensearch/action/admin/indices/streamingingestion/state/GetIngestionStateResponse.java
  server/src/main/java/org/opensearch/action/admin/indices/streamingingestion/state/ShardIngestionState.java
  server/src/main/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportGetIngestionStateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportUpdateIngestionStateAction.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/engine/IngestionEngine.java
  server/src/main/java/org/opensearch/indices/pollingingest/IngestionEngineFactory.java
  server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/GetIngestionStateResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/ShardIngestionStateTests.java
  server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportGetIngestionStateActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportUpdateIngestionStateActionTests.java
  server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java
  server/src/test/java/org/opensearch/index/engine/IngestionEngineTests.java
Labels: enhancement, Indexing

#19347 Miscellaneous cleanup of `:qa` projects
  build.gradle
  qa/evil-tests/build.gradle
  qa/evil-tests/src/test/java/org/opensearch/bootstrap/EvilBootstrapChecksTests.java
  qa/translog-policy/src/test/java/org/opensearch/upgrades/TranslogPolicyIT.java
Labels: skip-changelog

#19356 Fix flaky test in 130_script_fields_profile.yml
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/130_script_fields_profile.yml
Labels: bug, flaky-test, skip-changelog, Build

#19344 [Rule-based Auto-tagging] restructure the in-memory trie to store values as a set
  CHANGELOG.md
  modules/autotagging-commons/common/src/main/java/org/opensearch/rule/storage/AttributeValueStore.java
  modules/autotagging-commons/common/src/main/java/org/opensearch/rule/storage/DefaultAttributeValueStore.java
  modules/autotagging-commons/common/src/test/java/org/opensearch/rule/storage/AttributeValueStoreTests.java
  modules/autotagging-commons/src/main/java/org/opensearch/rule/InMemoryRuleProcessingService.java
Labels: v3.3.0

#19404 fix StreamStringTermsAggregatorTests by replacing RandomIndexWriter with plain IndexWriter #18956 WIP
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/StreamStringTermsAggregatorTests.java
Labels: skip-changelog

#19397 Migrate deprecated usages of Operations#union
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/lucene/search/AutomatonQueries.java
  server/src/main/java/org/opensearch/common/xcontent/support/XContentMapValues.java
  server/src/main/java/org/opensearch/indices/SystemIndices.java
Labels: lucene

#19437 Fix flaky test RemoteClusterStateServiceTests.testReadClusterStateInParallel_ExceptionDuringRead
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, ClusterManager:RemoteState

#19403 Asynchronous FlightServerChannel to avoid thread contention per request
  plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/bootstrap/ServerConfig.java
  plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/transport/ArrowFlightProducer.java
  plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/transport/FlightOutboundHandler.java
  plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/transport/FlightServerChannel.java
  plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/transport/FlightTransport.java
  plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/transport/FlightTransportChannel.java
  plugins/arrow-flight-rpc/src/test/java/org/opensearch/arrow/flight/transport/FlightTransportChannelTests.java
Labels: skip-changelog

#19432 Delegate primitive write methods with ByteSizeCachingDirectory wrapped IndexOutput
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/store/ByteSizeCachingDirectory.java
Labels: bug, Indexing:Performance, lucene

#19181 Omit maxScoreCollector for field collapsing when sort by score descending
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/400_max_score.yml
  server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
  server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
Labels: bug, enhancement, Search, Search:Performance

#19428 Update gradle run to be able to fetch and run external plugins
  DEVELOPER_GUIDE.md
  gradle/run.gradle
Labels: skip-changelog

#19457 [FIX BUG] Fix QueryPhaseTests.testMaxScoreWithSortOnScoreAndCollapsingResults
  server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java
Labels: skip-changelog

#19449 [GRPC][Full-text queries] Implement GRPC Match Phrase, MultiMatch queries
  CHANGELOG.md
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/MatchPhraseQueryBuilderProtoConverter.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/MatchPhraseQueryBuilderProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/MultiMatchQueryBuilderProtoConverter.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/MultiMatchQueryBuilderProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterRegistryImpl.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/MatchPhraseQueryBuilderProtoConverterTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/MatchPhraseQueryBuilderProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/MultiMatchQueryBuilderProtoConverterTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/MultiMatchQueryBuilderProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterRegistryTests.java
Labels: enhancement, Search

#19471 Refresh performance benchmark configs
  .github/benchmark-configs.json
Labels: skip-changelog

#19391 [GRPC][Compound queries] Implement Boolean query and inject registry for all built-in query converters
  CHANGELOG.md
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/GrpcPlugin.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/BoolQueryBuilderProtoConverter.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/BoolQueryBuilderProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterRegistryImpl.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterSpiRegistry.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/GrpcPluginTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/BoolQueryBuilderProtoConverterTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/BoolQueryBuilderProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterRegistryTests.java
Labels: enhancement, Search, _No response_

#19465 Fix flaky WlmAutoTaggingIT test
  plugins/workload-management/src/internalClusterTest/java/org/opensearch/plugin/wlm/WlmAutoTaggingIT.java
Labels: >test-failure, flaky-test, autocut

#19209 Introducing query_failed as part of nodes, indices and shards stats
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.shards/10_basic.yml
  server/src/main/java/org/opensearch/index/search/stats/SearchStats.java
  server/src/main/java/org/opensearch/index/search/stats/ShardSearchStats.java
  server/src/main/java/org/opensearch/rest/action/cat/RestIndicesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestShardsAction.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
  server/src/test/java/org/opensearch/rest/action/cat/RestShardsActionTests.java
Labels: enhancement, Search, Search:Query Insights, v3.3.0

#19229 Replace commons-lang:commons-lang with org.apache.commons:commons-lang3
  CHANGELOG.md
  plugins/discovery-azure-classic/build.gradle
  plugins/discovery-azure-classic/licenses/commons-lang-2.6.jar.sha1
  plugins/discovery-azure-classic/licenses/commons-lang-NOTICE.txt
  plugins/discovery-azure-classic/licenses/commons-lang3-3.18.0.jar.sha1
  plugins/discovery-azure-classic/licenses/commons-lang3-LICENSE.txt
  plugins/discovery-azure-classic/licenses/commons-lang3-NOTICE.txt
  plugins/discovery-azure-classic/licenses/javax.inject-1.jar.sha1
  plugins/discovery-azure-classic/licenses/jaxb-impl-2.2.3-1.jar.sha1
  plugins/discovery-azure-classic/licenses/jersey-client-1.13.jar.sha1
  plugins/discovery-azure-classic/licenses/jersey-core-1.13.jar.sha1
  plugins/discovery-azure-classic/licenses/jersey-json-1.13.jar.sha1
  plugins/discovery-azure-classic/src/main/java/org/apache/commons/lang/StringUtils.java
  plugins/identity-shiro/build.gradle
  plugins/identity-shiro/licenses/commons-lang-2.6.jar.sha1
  plugins/identity-shiro/licenses/commons-lang3-3.18.0.jar.sha1
  plugins/identity-shiro/licenses/commons-lang3-LICENSE.txt
  plugins/identity-shiro/licenses/commons-lang3-NOTICE.txt
Labels: backport 2.19

#19451 [GRPC][Geographic queries] Implement GRPC GeoBoundingBox, GeoDistance queries
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/common/GeoPointProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/GeoBoundingBoxQueryBuilderProtoConverter.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/GeoBoundingBoxQueryBuilderProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/GeoDistanceQueryBuilderProtoConverter.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/GeoDistanceQueryBuilderProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterRegistryImpl.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/common/GeoPointProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/GeoBoundingBoxQueryBuilderProtoConverterTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/GeoBoundingBoxQueryBuilderProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/GeoDistanceQueryBuilderProtoConverterTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/GeoDistanceQueryBuilderProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterRegistryTests.java
  server/src/main/java/org/opensearch/common/geo/GeoBoundingBox.java
  server/src/main/java/org/opensearch/common/geo/GeoUtils.java
Labels: enhancement, skip-changelog, _No response_

#19453 [GRPC][Joining queries] Implement GRPC Nested query, fix InnerHits, and bump to 0.19.0 protobufs
  CHANGELOG.md
  gradle/libs.versions.toml
  modules/transport-grpc/licenses/protobufs-0.18.0.jar.sha1
  modules/transport-grpc/licenses/protobufs-0.19.0.jar.sha1
  modules/transport-grpc/spi/licenses/protobufs-0.18.0.jar.sha1
  modules/transport-grpc/spi/licenses/protobufs-0.19.0.jar.sha1
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/CollapseBuilderProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/FieldAndFormatProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/InnerHitsBuilderProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/NestedQueryBuilderProtoConverter.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/NestedQueryBuilderProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterRegistryImpl.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/FieldAndFormatProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/InnerHitsBuilderProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/NestedQueryBuilderProtoConverterTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/NestedQueryBuilderProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterRegistryTests.java
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
Labels: enhancement, Search:Query Capabilities

#19470 Fix stats API of SubdirectoryAwareStore
  CHANGELOG.md
  modules/store-subdirectory/src/main/java/org/opensearch/plugin/store/subdirectory/SubdirectoryAwareStore.java
  modules/store-subdirectory/src/test/java/org/opensearch/plugin/store/subdirectory/SubdirectoryStorePluginTests.java
Labels: bug, Other

#19448 [GRPC][Term-level queries] Implement GRPC Ids, Range, and Terms Set queries
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/IdsQueryBuilderProtoConverter.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/IdsQueryBuilderProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterRegistryImpl.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/RangeQueryBuilderProtoConverter.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/RangeQueryBuilderProtoUtils.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/TermsSetQueryBuilderProtoConverter.java
  modules/transport-grpc/src/main/java/org/opensearch/transport/grpc/proto/request/search/query/TermsSetQueryBuilderProtoUtils.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/IdsQueryBuilderProtoConverterTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/IdsQueryBuilderProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/QueryBuilderProtoConverterRegistryTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/RangeQueryBuilderProtoConverterTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/RangeQueryBuilderProtoUtilsTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/TermsSetQueryBuilderProtoConverterTests.java
  modules/transport-grpc/src/test/java/org/opensearch/transport/grpc/proto/request/search/query/TermsSetQueryBuilderProtoUtilsTests.java
Labels: enhancement, skip-changelog

#18732 Optimization in String Terms Aggregation query for Large Bucket Counts
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
Labels: bug, Search:Performance
