Repository opensearch-project/OpenSearch, pull requests merged in 2025-05, with the labels that each got.

#18163 Make HASHED_PREFIX as the default path type for remote store and snapshot
  server/src/main/java/org/opensearch/indices/RemoteStoreSettings.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/test/java/org/opensearch/index/remote/RemoteStoreCustomMetadataResolverTests.java
Labels: skip-changelog

#17843 Fix object field exists query
  CHANGELOG.md
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapperTests.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
  server/src/main/java/org/opensearch/index/query/ExistsQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/ExistsQueryBuilderTests.java
Labels: bug, v3.0.0, Search

#18167 Reduce runtime of PitMultiNodeIT by 6 minutes
  server/src/internalClusterTest/java/org/opensearch/search/pit/PitMultiNodeIT.java
Labels: skip-changelog

#18169 Fail fast if initial delete call fails in CreateIndexIT
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/CreateIndexIT.java
Labels: skip-changelog

#18176 Mute WarmIndexSegmentReplicationIT
  server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java
Labels: skip-changelog

#18177 Mute ShardsLimitAllocationDeciderRemoteStoreEnabledIT
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/ShardsLimitAllocationDeciderRemoteStoreEnabledIT.java
Labels: skip-changelog

#18185 Adding new permission for _cat/shard action to 3.0 release notes.
  release-notes/opensearch.release-notes-3.0.0.md
Labels: skip-changelog, backport 3.0

#18161 Use Bad Request status for InputCoercionException
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/ExceptionsHelper.java
  rest-api-spec/src/main/resources/rest-api-spec/test/search/30_limits.yml
  server/src/test/java/org/opensearch/ExceptionsHelperTests.java
Labels: backport 2.19, v3.1.0

#18199 Fix flaky RepositoriesServiceIT.testCreatSnapAndUpdateReposityCauseInfiniteLoop
  server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, disabled-test

#18196 Fix systemd seccomp test
  qa/systemd-test/src/test/java/org/opensearch/systemdinteg/SystemdIntegTests.java
Labels: skip-changelog

#18186 Change single shard assignment log message from warn to debug
  CHANGELOG.md
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
Labels: bug, Cluster Manager

#18194 Null check field names in QueryStringQueryBuilder
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/50_multi_match.yml
  server/src/main/java/org/opensearch/index/query/QueryStringQueryBuilder.java
  server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
Labels: bug, Search, backport 2.19, v3.1.0

#18211 [AUTO] [3.0] Add bwc version 2.19.3. (#18160)
  .ci/bwcVersions
  README.md
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#18216 Fix flaky pull-based ingestion tests
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaUtils.java
Labels: >test-failure, flaky-test, autocut

#18189 Improve sort-query performance by retaining the default `totalHitsThreshold` for approximated `match_all` queries
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateScoreQuery.java
  server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
Labels: feature, Search:Performance, backport 3.0

#18218 Avoid NPE if on SnapshotInfo if 'shallow' boolean not present
  CHANGELOG.md
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: bug, Search:Searchable Snapshots, Storage:Snapshots, backport 2.19

#18222 [Backport] [2.19] Fixing Flaky ReactorNetty4StreamingStressIT test case (another attempt) (#18193)
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Labels: flaky-test, skip-changelog

#18209 Fix flaky RepositoriesServiceIT.testCreatSnapAndUpdateReposityCauseInfiniteLoop
  server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, disabled-test

#18221 [Backport] [3.0] Fixing Flaky ReactorNetty4StreamingStressIT test case (another attempt) (#18193)
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Labels: flaky-test, skip-changelog

#18212 Add tolerance for matrix stats agg variance value assertion
  client/rest-high-level/src/test/java/org/opensearch/client/SearchIT.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#17759 Adding support for derive source feature and implementing it for various type of field mappers
  CHANGELOG.md
  modules/mapper-extras/src/main/java/org/opensearch/index/mapper/ScaledFloatFieldMapper.java
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldMapperTests.java
  server/src/main/java/org/opensearch/index/mapper/BooleanFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/ConstantKeywordFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DateFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldGenerator.java
  server/src/main/java/org/opensearch/index/mapper/FieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/FieldValueFetcher.java
  server/src/main/java/org/opensearch/index/mapper/FieldValueType.java
  server/src/main/java/org/opensearch/index/mapper/GeoPointFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/IpFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/SortedNumericDocValuesFetcher.java
  server/src/main/java/org/opensearch/index/mapper/SortedSetDocValuesFetcher.java
  server/src/main/java/org/opensearch/index/mapper/StoredFieldFetcher.java
  server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/BooleanFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/ConstantKeywordFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/GeoPointFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/IpFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/NumberFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/SortedNumericDocValuesFetcherTests.java
  server/src/test/java/org/opensearch/index/mapper/SortedSetDocValuesFetcherTests.java
  server/src/test/java/org/opensearch/index/mapper/StoredFieldFetcherTests.java
  server/src/test/java/org/opensearch/index/mapper/TextFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/WildcardFieldMapperTests.java
Labels: enhancement, Indexing:Performance

#18237 Replaced Thread::getId() with Thread::threadId()
  libs/common/src/main/java/org/opensearch/common/recycler/Recyclers.java
  modules/lang-expression/src/main/java/org/opensearch/script/expression/PerThreadReplaceableConstDoubleValueSource.java
  server/src/main/java/org/opensearch/monitor/jvm/HotThreads.java
  server/src/main/java/org/opensearch/search/profile/query/ConcurrentQueryProfiler.java
  server/src/main/java/org/opensearch/tasks/TaskResourceTrackingService.java
  server/src/main/java/org/opensearch/threadpool/TaskAwareRunnable.java
  server/src/test/java/org/opensearch/action/admin/cluster/node/tasks/ResourceAwareTasksTests.java
  server/src/test/java/org/opensearch/tasks/TaskResourceTrackingServiceTests.java
Labels: enhancement, good first issue, skip-changelog, Build

#18234 Add @yupeng9 as a maintainer
  MAINTAINERS.md
Labels: skip-changelog

#18247 Unregister rest and transport action handlers for HotToWarmTiering
  server/src/main/java/org/opensearch/action/ActionModule.java
  server/src/test/java/org/opensearch/action/admin/indices/tiering/TransportHotToWarmTieringActionTests.java
Labels: skip-changelog

#18235 Fix `SimpleSearchIT.doTestSimpleTerminateAfterTrackTotalHitsUpTo` flaky test
  server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
Labels: skip-changelog

#17817 Introduce system ingest pipeline.
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/index/FinalPipelineIT.java
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
  server/src/main/java/org/opensearch/action/index/IndexRequest.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/ingest/AbstractBatchingSystemProcessor.java
  server/src/main/java/org/opensearch/ingest/IndexRequestWrapper.java
  server/src/main/java/org/opensearch/ingest/IngestPipelineInfo.java
  server/src/main/java/org/opensearch/ingest/IngestPipelineType.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/ingest/Pipeline.java
  server/src/main/java/org/opensearch/ingest/Processor.java
  server/src/main/java/org/opensearch/ingest/SystemIngestPipelineCache.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/IngestPlugin.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionTests.java
  server/src/test/java/org/opensearch/ingest/AbstractBatchingSystemProcessorTests.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
  server/src/test/java/org/opensearch/ingest/PipelineTests.java
  server/src/test/java/org/opensearch/ingest/SystemIngestPipelineCacheTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: bug, enhancement, Indexing, ingest-pipeline

#18248 Fix incorrect constructor param ordering in ShardRouting
  server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java
Labels: skip-changelog

#18259 Expose method for getting reference count of entry in FileCache
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/RefCountedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/cache/RefCountedCacheTestCase.java
Labels: skip-changelog

#18201 Attempt to fix ThreadLeakControl issues in S3BlobContainerRetriesTests
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/AwsS3ServiceImplTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3ClientSettingsTests.java
Labels: bug, >test-failure, flaky-test, autocut, skip-changelog, Build

#18260 Fix incorrect PR references in 3.x release notes
  release-notes/opensearch.release-notes-3.0.0-alpha1.md
  release-notes/opensearch.release-notes-3.0.0-beta1.md
  release-notes/opensearch.release-notes-3.0.0.md
Labels: skip-changelog, backport 3.0

#18270 Decouple the init of Crypto Plugin and KeyProvider in Registry
  CHANGELOG.md
  server/src/main/java/org/opensearch/crypto/CryptoHandlerRegistry.java
Labels: enhancement, help wanted, discuss, Plugins

#18282 Fix flaky failures in PitMultiNodeIT
  server/src/internalClusterTest/java/org/opensearch/search/pit/PitMultiNodeIT.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, Search

#18256 Apply cluster state metadata and routing table diff when building clu…
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
Labels: bug, Cluster Manager

#18283 Update concurrency setting for gradle check to exclude cancellation of the post_merge runs
  .github/workflows/gradle-check.yml
Labels: backport 2.x, skip-changelog, backport 2.19, backport 3.0

#18290 Fix flaky tests in GoogleCloudStorageBlobStoreRepositoryTests, S3BlobStoreRepositoryTests, AzureBlobStoreRepositoryTests
  plugins/repository-azure/src/internalClusterTest/java/org/opensearch/repositories/azure/AzureBlobStoreRepositoryTests.java
  plugins/repository-gcs/src/internalClusterTest/java/org/opensearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/OpenSearchMockAPIBasedRepositoryIntegTestCase.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, Storage:Snapshots, backport 2.19

#18280 [Pull-based Ingestion] Support cluster write blocks
  CHANGELOG.md
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/KafkaIngestionBaseIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/main/java/org/opensearch/action/admin/indices/streamingingestion/state/ShardIngestionState.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
  server/src/main/java/org/opensearch/index/engine/IngestionEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
  server/src/main/java/org/opensearch/indices/pollingingest/StreamPoller.java
  server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/GetIngestionStateResponseTests.java
  server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/ShardIngestionStateTests.java
  server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportGetIngestionStateActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/streamingingestion/state/TransportUpdateIngestionStateActionTests.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
  server/src/test/java/org/opensearch/index/engine/IngestionEngineTests.java
  server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: enhancement, Indexing

#18299 Composite Directory - silently fail instead of throwing error for non-existent file in deleteFile() call
  server/src/main/java/org/opensearch/index/store/CompositeDirectory.java
  server/src/test/java/org/opensearch/index/store/CompositeDirectoryTests.java
Labels: skip-changelog

#18301 [Flaky Test] Fix Flaky SearchServiceTests.testConcurrentSegmentSearchWithRandomizedModeSettings
  server/src/test/java/org/opensearch/search/SearchServiceTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, Search, backport 3.0

#18304 [Pull-based Ingestion] Add warning when message is dropped
  server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java
  server/src/test/java/org/opensearch/indices/pollingingest/MessageProcessorTests.java
Labels: skip-changelog

#18316 Switch ingest-geoip and lang-painless modules to use the gradle version catalog
  gradle/libs.versions.toml
  modules/ingest-geoip/build.gradle
  modules/lang-painless/build.gradle
Labels: skip-changelog

#18006 Fix QueueResizableOpenSearchThreadPoolExecutorTests
  server/src/test/java/org/opensearch/common/util/concurrent/QueueResizableOpenSearchThreadPoolExecutorTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, Cluster Manager, Other

#18329 Fix Flaky RemoteSplitIndexIT (#15107)
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/RemoteSplitIndexIT.java
Labels: skip-changelog

#18166 Add support for matched_fields with the unified highlighter
  CHANGELOG.md
  plugins/mapper-annotated-text/src/test/java/org/opensearch/search/fetch/subphase/highlight/AnnotatedTextHighlighterTests.java
  rest-api-spec/src/main/resources/rest-api-spec/test/search.highlight/10_unified.yml
  server/src/internalClusterTest/java/org/opensearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
  server/src/main/java/org/opensearch/lucene/search/uhighlight/CustomFieldHighlighter.java
  server/src/main/java/org/opensearch/lucene/search/uhighlight/CustomUnifiedHighlighter.java
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/UnifiedHighlighter.java
  server/src/test/java/org/opensearch/lucene/search/uhighlight/CustomUnifiedHighlighterTests.java
Labels: enhancement, Search

#18317 Attempt to fix ThreadLeakControl issues in S3BlobStoreRepositoryTests
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Service.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, Storage:Snapshots

#18343 Add `http_logs` search only test procedure
  .github/benchmark-configs.json
Labels: skip-changelog

#18154 Remove tests for legacy keystore format
  distribution/tools/keystore-cli/src/test/java/org/opensearch/tools/cli/keystore/KeyStoreWrapperTests.java
  distribution/tools/keystore-cli/src/test/java/org/opensearch/tools/cli/keystore/UpgradeKeyStoreCommandTests.java
  distribution/tools/keystore-cli/src/test/resources/format-v3-elasticsearch.keystore
Labels: skip-changelog

#18321 Improve failure message in AbstractSimpleTransportTestCase
  test/framework/src/main/java/org/opensearch/transport/AbstractSimpleTransportTestCase.java
Labels: skip-changelog

#18322 Prepare the codebase for running on JDK-24+
  distribution/tools/plugin-cli/build.gradle
  distribution/tools/plugin-cli/src/main/java/org/opensearch/tools/cli/plugin/PluginSecurity.java
  gradle/code-coverage.gradle
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PolicyFile.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/FileInterceptorIntegTests.java
  qa/evil-tests/src/test/java/org/opensearch/tools/cli/plugin/PluginSecurityTests.java
  server/src/main/java/org/opensearch/monitor/os/OsProbe.java
  server/src/main/resources/org/opensearch/bootstrap/security.policy
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
  server/src/main/resources/org/opensearch/bootstrap/test.policy
  test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java
  test/framework/src/main/java/org/opensearch/repositories/blobstore/AbstractBlobContainerRetriesTestCase.java
Labels: enhancement, Build Libraries & Interfaces, skip-changelog, v3.1.0

#18349 Add @rishabhmaurya as a maintainer
  MAINTAINERS.md
Labels: skip-changelog

#18312 Add support for SSE-KMS and bucket owner verification
  CHANGELOG.md
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobStore.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3Repository.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RetryingInputStream.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncPartsHandler.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/AsyncTransferManager.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/S3AsyncDeleteHelper.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/async/UploadRequest.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/utils/SseKmsUtil.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerMockClientTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/async/AsyncTransferManagerTests.java
Labels: enhancement, security, Plugins, Storage:Snapshots, Storage:Remote, v3.1.0

#18352 Fix IndexServiceTests sort field test cases
  server/src/test/java/org/opensearch/index/IndexServiceTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
Labels: skip-changelog

#18331 Flaky MetricAggregatorTests
  server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java
Labels: >test-failure, Search:Aggregations, flaky-test, autocut, skip-changelog, disabled-test

#18359 Replace wrapper-validation-action GitHub action
  .github/workflows/wrapper.yml
Labels: skip-changelog

#17538 Added changes to enable full file cache stats
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterInfoServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/WritableWarmIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/SearchableSnapshotIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
  server/src/main/java/org/opensearch/cluster/ClusterInfo.java
  server/src/main/java/org/opensearch/cluster/InternalClusterInfoService.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/WarmDiskThresholdDecider.java
  server/src/main/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolder.java
  server/src/main/java/org/opensearch/common/cache/stats/ImmutableCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/AggregateFileCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/utils/TransferManager.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/CacheUsage.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/RefCountedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/AggregateRefCountedCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/DefaultStatsCounter.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/FileStatsCounter.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/IRefCountedCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/RefCountedCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/StatsCounter.java
  server/src/main/java/org/opensearch/monitor/fs/FsProbe.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/cluster/ClusterInfoTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/WarmDiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/AggregateFileCacheStatsTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheStatsTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCachedIndexInputTests.java
  server/src/test/java/org/opensearch/index/store/remote/utils/TransferManagerTestCase.java
  server/src/test/java/org/opensearch/index/store/remote/utils/cache/RefCountedCacheTestCase.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: bug, enhancement, Storage:Remote, _No response_

#18353 Update `big5` (`id_4`) to test against Lucene 10.2.1
  .github/benchmark-configs.json
Labels: skip-changelog

#18327 Disabling _close API invocation during remote migration.
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotemigration/CloseIndexMigrationTestCase.java
  server/src/main/java/org/opensearch/action/admin/indices/close/TransportCloseIndexAction.java
  server/src/test/java/org/opensearch/action/admin/indices/close/TransportCloseIndexActionTests.java
Labels: enhancement, Storage:Remote

#18364 Code of Conduct - update AWS to LF links/contact
  CODE_OF_CONDUCT.md
  README.md
Labels: skip-changelog, backport 3.0

#17617 Add changes to support pinning in FileCache
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/store/CompositeDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/AggregateFileCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/RefCountedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/AggregateRefCountedCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/DefaultStatsCounter.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/FileStatsCounter.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/IRefCountedCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/RefCountedCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/stats/StatsCounter.java
  server/src/test/java/org/opensearch/cluster/ClusterInfoTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/WarmDiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/AggregateFileCacheStatsTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheStatsTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, Storage:Remote

#18124 Switch percentiles implementation to MergingDigest
  CHANGELOG.md
  gradle/libs.versions.toml
  server/src/main/java/org/opensearch/search/aggregations/metrics/InternalMedianAbsoluteDeviation.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/TDigestState.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/InternalTDigestPercentilesRanksTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/InternalTDigestPercentilesTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/TDigestPercentilesAggregatorTests.java
Labels: enhancement, Search:Performance

#18363 Validate Search Phase Request Processors in Search Pipeline
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: skip-changelog

#18395 Replace the deprecated construction method of TopScoreDocCollectorManager with the new method in Lucene
  CHANGELOG.md
  modules/parent-join/src/main/java/org/opensearch/join/query/ParentChildInnerHitContextBuilder.java
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/sampler/BestDocsDeferringCollector.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/TopHitsAggregator.java
  server/src/main/java/org/opensearch/search/query/TopDocsCollectorContext.java
Labels: bug, Other

#18367 Add tolerance for matrix stats agg variance value assertion
  client/rest-high-level/src/test/java/org/opensearch/client/SearchIT.java
Labels: >test-failure, flaky-test, autocut

#18399 fix indices.simulate_index_template test spec
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.simulate_index_template/10_basic.yml
Labels: skip-changelog

#18400 Add Search Phase Result Processors to SearchPipelineInfo
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: skip-changelog

#18358 Fix performance regression in `ApproximatePointRangeQuery` with Lucene 10.2.1 change
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: v3.1.0
