Repository opensearch-project/OpenSearch, pull requests merged in 2025-01, with the labels that each got.

#16923 Update script supports java.lang.String.sha1() and java.lang.String.sha256() methods
  CHANGELOG.md
  modules/lang-painless/src/main/java/org/opensearch/painless/PainlessModulePlugin.java
  modules/lang-painless/src/main/resources/org/opensearch/painless/spi/org.opensearch.update.txt
  modules/lang-painless/src/yamlRestTest/resources/rest-api-spec/test/painless/15_update.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/85_scripting.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/update_by_query/80_scripting.yml
Labels: v3.0.0, backport 2.x, v2.19.0

#16940 Add benchmark config for lucene-10 big5 index snapshot
  .github/benchmark-configs.json
Labels: skip-changelog

#16942 Remove duplicate DCO check
  .github/workflows/dco.yml
Labels: backport 1.x, backport 2.x, backport 1.3, skip-changelog

#16909 Allow extended plugins to be optional
  CHANGELOG.md
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
  server/src/main/java/org/opensearch/plugins/PluginsService.java
  server/src/test/java/org/opensearch/plugins/PluginInfoTests.java
  server/src/test/java/org/opensearch/plugins/PluginsServiceTests.java
Labels: v3.0.0, backport 2.x, v2.19.0

#16947 Change version in PluginInfo to V_2_19_0 after backport to 2.x merged
  server/src/main/java/org/opensearch/plugins/PluginInfo.java
Labels: skip-changelog

#16728 Support object fields in star-tree index
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/index/mapper/DocumentParser.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/mapper/StarTreeMapper.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: backport 2.x

#16944 [Backport] [1.3] Remove duplicate DCO check (#16942)
  .github/workflows/dco.yml
Labels: skip-changelog

#16945 [Backport] [1.x] Remove duplicate DCO check (#16942)
  .github/workflows/dco.yml
Labels: skip-changelog

#16359 [Workload Management] Add Workload Management IT
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/backpressure/SearchBackpressureIT.java
  server/src/internalClusterTest/java/org/opensearch/wlm/WorkloadManagementIT.java
Labels: backport 2.x

#16956 Add new benchmark config for nested workload
  .github/benchmark-configs.json
Labels: skip-changelog

#16964 Always use constant_score query for match_only_text
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/MatchOnlyTextFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/MatchOnlyTextFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/MatchOnlyTextFieldTypeTests.java
Labels: backport 2.x, v2.19.0

#16788 Use async client for delete blob or path in S3 Blob Container
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3BlobStoreRepositoryTests.java
  plugins/repository-s3/src/internalClusterTest/java/org/opensearch/repositories/s3/S3RepositoryThirdPartyTests.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3AsyncService.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3RepositoryPlugin.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3RepositoryPluginTests.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: bug, skip-changelog, Storage:Snapshots

#16868 Fix Shallow copy snapshot failures on closed index
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteStoreIT.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/repositories/Repository.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
  server/src/main/java/org/opensearch/snapshots/SnapshotShardsService.java
  server/src/test/java/org/opensearch/index/shard/RemoteIndexShardTests.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
  server/src/test/java/org/opensearch/repositories/RepositoriesServiceTests.java
  test/framework/src/main/java/org/opensearch/index/replication/OpenSearchIndexLevelReplicationTestCase.java
Labels: backport 2.x, skip-changelog

#16978 Add Response Status Number in Http Trace Logs.
  server/src/main/java/org/opensearch/http/HttpTracer.java
  server/src/test/java/org/opensearch/http/AbstractHttpServerTransportTests.java
Labels: backport 2.x, skip-changelog

#16974 Support searching from doc_value using termQueryCaseInsensitive/termQuery in flat_object/keyword field
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/92_flat_object_support_doc_values.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/340_doc_values_field.yml
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
Labels: enhancement, backport 2.x, Search

#16881 use the correct type to widen the sort fields when merging top docs
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/main/java/org/opensearch/action/search/SearchPhaseController.java
  server/src/main/java/org/opensearch/search/sort/SortedWiderNumericSortField.java
Labels: bug, v3.0.0, backport 2.x, Search, v2.19.0

#16732 Fix multi-value sort for unsigned long
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/260_sort_double.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/260_sort_long.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/260_sort_unsigned_long.yml
  server/src/main/java/org/opensearch/index/fielddata/LongToSortedNumericUnsignedLongValues.java
  server/src/main/java/org/opensearch/index/fielddata/SortedNumericUnsignedLongValues.java
  server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/UnsignedLongValuesComparatorSource.java
  server/src/main/java/org/opensearch/search/MultiValueMode.java
  server/src/test/java/org/opensearch/search/MultiValueModeTests.java
Labels: bug, v3.0.0, backport 2.x, Search, v2.19.0

#16993 `phone-search` analyzer: don't emit sip/tel prefix, int'l prefix, extension & unformatted input
  CHANGELOG.md
  plugins/analysis-phonenumber/src/main/java/org/opensearch/analysis/phone/PhoneNumberTermTokenizer.java
  plugins/analysis-phonenumber/src/test/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerTests.java
  plugins/analysis-phonenumber/src/yamlRestTest/resources/rest-api-spec/test/analysis-phone/20_search.yml
Labels: bug, v3.0.0, backport 2.x, v2.19.0

#16827 Fix case insensitive and escaped query on wildcard
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/270_wildcard_fieldtype_queries.yml
  server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
Labels: bug, backport 2.x, Search, v2.19.0

#17000 Bump opentelemetry from 1.41.0 to 1.46.0 and opentelemetry-semconv from 1.27.0-alpha to 1.29.0-alpha
  CHANGELOG.md
  gradle/libs.versions.toml
  plugins/telemetry-otel/build.gradle
  plugins/telemetry-otel/licenses/opentelemetry-api-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-incubator-1.41.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-api-incubator-1.46.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-context-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-common-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-logging-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-otlp-common-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-exporter-sender-okhttp-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-common-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-logs-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-metrics-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.41.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-sdk-trace-1.46.0.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.27.0-alpha.jar.sha1
  plugins/telemetry-otel/licenses/opentelemetry-semconv-1.29.0-alpha.jar.sha1
Labels: dependencies, backport 2.x

#16950 Delete useless loop in TransportBulkAction$BulkOperation.doRun()
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
Labels: backport 2.x, skip-changelog, Indexing

#11733 Show only intersecting buckets to the Adjacency matrix aggregation
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/70_adjacency_matrix.yml
  server/src/main/java/org/opensearch/search/aggregations/bucket/adjacency/AdjacencyMatrixAggregationBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/adjacency/AdjacencyMatrixAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/adjacency/AdjacencyMatrixAggregatorFactory.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/adjacency/AdjacencyMatrixAggregationBuilderTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/AdjacencyMatrixTests.java
Labels: backport 2.x, skip-changelog

#17016 improve `PhoneNumberAnalyzerTests#testTelPrefixSearch`
  plugins/analysis-phonenumber/src/test/java/org/opensearch/analysis/phone/PhoneNumberAnalyzerTests.java
Labels: skip-changelog

#16771 Filter shards for sliced search at coordinator
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/api/search_shards.json
  rest-api-spec/src/main/resources/rest-api-spec/test/search_shards/20_slice.yml
  server/src/main/java/org/opensearch/action/admin/cluster/shards/ClusterSearchShardsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/shards/TransportClusterSearchShardsAction.java
  server/src/main/java/org/opensearch/action/fieldcaps/TransportFieldCapabilitiesIndexAction.java
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestClusterSearchShardsAction.java
  server/src/main/java/org/opensearch/search/slice/SliceBuilder.java
  server/src/test/java/org/opensearch/action/search/TransportSearchActionTests.java
  server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java
Labels: enhancement, backport 2.x, Search:Resiliency

#16757 Upgrade HttpCore5/HttpClient5 to support ExtendedSocketOption in HttpAsyncClient
  CHANGELOG-3.0.md
  client/rest-high-level/src/test/resources/org/opensearch/bootstrap/test.policy
  client/rest/licenses/httpclient5-5.3.1.jar.sha1
  client/rest/licenses/httpclient5-5.4.1.jar.sha1
  client/rest/licenses/httpcore5-5.2.5.jar.sha1
  client/rest/licenses/httpcore5-5.3.2.jar.sha1
  client/rest/licenses/httpcore5-h2-5.2.5.jar.sha1
  client/rest/licenses/httpcore5-h2-5.3.2.jar.sha1
  client/rest/licenses/httpcore5-reactive-5.2.5.jar.sha1
  client/rest/licenses/httpcore5-reactive-5.3.2.jar.sha1
  client/rest/src/test/java/org/opensearch/client/RestClientBuilderTests.java
  client/rest/src/test/java/org/opensearch/client/RestClientSingleHostIntegTests.java
  client/rest/src/test/java/org/opensearch/client/documentation/RestClientDocumentation.java
  client/sniffer/licenses/httpclient5-5.3.1.jar.sha1
  client/sniffer/licenses/httpclient5-5.4.1.jar.sha1
  client/sniffer/licenses/httpcore5-5.2.5.jar.sha1
  client/sniffer/licenses/httpcore5-5.3.2.jar.sha1
  gradle/libs.versions.toml
  plugins/repository-azure/licenses/reactor-netty-core-1.1.23.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.26.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.23.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.26.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.23.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.26.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.23.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.26.jar.sha1
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransport.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/transport/reactor/ReactorNetty4Plugin.java
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
Labels: enhancement, Clients, v3.0.0

#17030 Update version checks for backport
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/70_adjacency_matrix.yml
  server/src/main/java/org/opensearch/search/aggregations/bucket/adjacency/AdjacencyMatrixAggregationBuilder.java
Labels: skip-changelog

#17031 [Forwardport] [main] Fix versions and breaking API changes
  rest-api-spec/src/main/resources/rest-api-spec/test/search_shards/20_slice.yml
  server/src/main/java/org/opensearch/action/admin/cluster/shards/ClusterSearchShardsRequest.java
Labels: skip-changelog

#17007 Remove user data from logs when not in debug/trace mode
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/delete_by_query/50_wait_for_active_shards.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/60_wait_for_active_shards.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/update_by_query/50_consistency.yml
  server/src/internalClusterTest/java/org/opensearch/action/support/WaitActiveShardCountIT.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationOperation.java
  server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/opensearch/action/update/UpdateHelper.java
Labels: skip-changelog

#16636 [Bugfix] Fix cache maximum size settings not working properly with pluggable caching
  CHANGELOG.md
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/MockDiskCache.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/EhcacheDiskCacheSettings.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  server/src/main/java/org/opensearch/common/cache/service/CacheService.java
  server/src/main/java/org/opensearch/common/cache/store/OpenSearchOnHeapCache.java
  server/src/main/java/org/opensearch/common/cache/store/settings/OpenSearchOnHeapCacheSettings.java
  server/src/main/java/org/opensearch/indices/IndicesRequestCache.java
  server/src/test/java/org/opensearch/common/cache/store/OpenSearchOnHeapCacheTests.java
  server/src/test/java/org/opensearch/common/settings/MemorySizeSettingsTests.java
  server/src/test/java/org/opensearch/indices/IndicesRequestCacheTests.java
Labels: bug, backport 2.x, Search

#17037 Fix GRPC AUX_TRANSPORT_PORT and SETTING_GRPC_PORT settings and remove lingering HTTP terminology
  CHANGELOG.md
  plugins/transport-grpc/src/main/java/org/opensearch/transport/grpc/GrpcPlugin.java
  plugins/transport-grpc/src/main/java/org/opensearch/transport/grpc/Netty4GrpcServerTransport.java
  plugins/transport-grpc/src/test/java/org/opensearch/transport/grpc/Netty4GrpcServerTransportTests.java
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/main/java/org/opensearch/plugins/NetworkPlugin.java
Labels: Meta, backport 2.x, Roadmap:Cost/Performance/Scale, Roadmap:Modular Architecture, v2.19.0

#17009 Fix getTime field name to time in GetStats (#16894)
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/60_include_both_time_and_gettime_in_stats.yml
  server/src/main/java/org/opensearch/index/get/GetStats.java
Labels: bug, good first issue, v3.0.0, backport 2.x, Other, v2.19.0

#16790 [Backport 2.x] [Bugfix] Fix TieredSpilloverCache stats not adding correctly when sha…
  CHANGELOG.md
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsIT.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsHolder.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsHolderTests.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
  server/src/main/java/org/opensearch/common/cache/stats/DefaultCacheStatsHolder.java
Labels: backport 2.x

#17046 Add Craig Perkins as OpenSearch Maintainer
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#17053 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#17049 Improve exception handling in S3BlobContainer synchronous operations
  plugins/repository-s3/src/main/java/org/opensearch/repositories/s3/S3BlobContainer.java
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobStoreContainerTests.java
Labels: skip-changelog

#17063 Fix the compiler task status reporting for annotation processor
  libs/common/src/test/java/org/opensearch/common/annotation/processor/ApiAnnotationProcessorTests.java
  libs/common/src/test/java/org/opensearch/common/annotation/processor/CompilerSupport.java
Labels: :test, backport 2.x, skip-changelog

#16891 [BugFix] Hide stracktrace in response while translog transfer upload failure
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferManagerTests.java
Labels: bug, skip-changelog, Storage:Remote

#17074 Revert "Bump com.diffplug.spotless from 6.25.0 to 7.0.2"
  CHANGELOG.md
  build.gradle
  server/src/test/java/org/opensearch/cluster/routing/remote/RemoteRoutingTableServiceTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreesBuilderTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryWithPinnedTimestampTests.java
  server/src/test/java/org/opensearch/indices/replication/RemoteStoreReplicationSourceTests.java
Labels: backport 2.x

#17070 Fix interchanged formats of total_indexing_buffer_in_bytes and total_indexing_buffer
  CHANGELOG-3.0.md
  rest-api-spec/src/main/resources/rest-api-spec/test/nodes.info/50_nodes_total_indexing_buffer_format.yml
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoResponse.java
Labels: bug, v3.0.0, Cluster Manager

#16936 Improve performance of the bitmap filtering
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/search/query/BitmapDocValuesQuery.java
  server/src/main/java/org/opensearch/search/query/BitmapIndexQuery.java
  server/src/test/java/org/opensearch/index/mapper/NumberFieldTypeTests.java
  server/src/test/java/org/opensearch/search/query/BitmapDocValuesQueryTests.java
  server/src/test/java/org/opensearch/search/query/BitmapIndexQueryTests.java
Labels: backport 2.x, Search:Performance, Search:Query Capabilities, Roadmap:Search, v2.19.0

#16937 Optimize innerhits query performance
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/DocumentMapper.java
  server/src/main/java/org/opensearch/index/query/NestedQueryBuilder.java
  server/src/main/java/org/opensearch/search/fetch/FetchPhase.java
Labels: enhancement, backport 2.x, Search:Performance, v2.19.0

#16297 Improve flat_object field parsing performance by reducing two passes to a single pass
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/xcontent/JsonToStringXContentParser.java
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/test/java/org/opensearch/common/xcontent/JsonToStringXContentParserTests.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java
Labels: backport 2.x, v2.19.0

#17079 Add ubuntu-24.04-arm to Github actions workflow
  .github/workflows/assemble.yml
  .github/workflows/precommit.yml
Labels: backport 2.x, skip-changelog

#17020 Bump 3.0.0 version with alpha qualifier
  buildSrc/version.properties
Labels: release, v3.0.0, skip-changelog

#17075 [Backport 2.x] Remove user data from logs when not in debug/trace mode
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/delete_by_query/50_wait_for_active_shards.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/reindex/60_wait_for_active_shards.yml
  modules/reindex/src/yamlRestTest/resources/rest-api-spec/test/update_by_query/50_consistency.yml
  server/src/internalClusterTest/java/org/opensearch/action/support/WaitActiveShardCountIT.java
  server/src/main/java/org/opensearch/action/support/replication/ReplicationOperation.java
  server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/opensearch/action/update/UpdateHelper.java
Labels: skip-changelog

#17057 Add BulkShardRequest Serialization Test
  server/src/main/java/org/opensearch/action/support/replication/ReplicationRequest.java
  server/src/test/java/org/opensearch/action/bulk/BulkShardRequestTests.java
Labels: backport 2.x, skip-changelog

#17091 Fix JDK version for publish-maven-snapshots GA workflow
  .github/workflows/publish-maven-snapshots.yml
Labels: skip-changelog

#17094 Switch alpha to alpha1 and update publish maven to support qualifier and meet requirements
  .github/workflows/publish-maven-snapshots.yml
  buildSrc/version.properties
Labels: release, v3.0.0, skip-changelog

#16843 Add verbose pipeline parameter to output each processor's execution details
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchResponse.java
  server/src/main/java/org/opensearch/action/search/SearchResponseSections.java
  server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java
  server/src/main/java/org/opensearch/search/SearchHits.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/main/java/org/opensearch/search/internal/InternalSearchResponse.java
  server/src/main/java/org/opensearch/search/pipeline/Pipeline.java
  server/src/main/java/org/opensearch/search/pipeline/PipelineProcessingContext.java
  server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java
  server/src/main/java/org/opensearch/search/pipeline/ProcessorExecutionDetail.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/main/java/org/opensearch/search/pipeline/TrackingSearchRequestProcessorWrapper.java
  server/src/main/java/org/opensearch/search/pipeline/TrackingSearchResponseProcessorWrapper.java
  server/src/test/java/org/opensearch/action/search/SearchResponseTests.java
  server/src/test/java/org/opensearch/search/GenericSearchExtBuilderTests.java
  server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java
  server/src/test/java/org/opensearch/search/pipeline/ProcessorExecutionDetailTests.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
  server/src/test/java/org/opensearch/search/pipeline/TrackingSearchRequestProcessorWrapperTests.java
  server/src/test/java/org/opensearch/search/pipeline/TrackingSearchResponseProcessorWrapperTests.java
Labels: enhancement, Priority-High, backport 2.x, Search, Other, v2.19.0

#16803 Fix exists queries on nested flat_object fields throws exception
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/index/90_flat_object.yml
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldMapperTests.java
Labels: bug, backport 2.x, Search

#17098 Updates version to fix BWC for SearchSourceBuilder
  server/src/main/java/org/opensearch/action/search/SearchResponseSections.java
  server/src/main/java/org/opensearch/search/builder/SearchSourceBuilder.java
  server/src/main/java/org/opensearch/search/internal/InternalSearchResponse.java
Labels: skip-changelog

#16818 Introduce Template query
  CHANGELOG.md
  server/build.gradle
  server/src/main/java/org/opensearch/action/search/TransportSearchAction.java
  server/src/main/java/org/opensearch/index/query/BaseQueryRewriteContext.java
  server/src/main/java/org/opensearch/index/query/QueryBuilders.java
  server/src/main/java/org/opensearch/index/query/QueryCoordinatorContext.java
  server/src/main/java/org/opensearch/index/query/QueryRewriteContext.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/index/query/TemplateQueryBuilder.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/search/SearchModule.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/pipeline/PipelineProcessingContext.java
  server/src/main/java/org/opensearch/search/pipeline/PipelinedRequest.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/RewriteableTests.java
  server/src/test/java/org/opensearch/index/query/TemplateQueryBuilderTests.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
  server/src/test/java/org/opensearch/search/aggregations/AggregatorFactoriesTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/FiltersTests.java
  server/src/test/java/org/opensearch/search/builder/SearchSourceBuilderTests.java
Labels: backport 2.x

#17080 Propagate includes and excludes from fetchSourceContext to FieldsVisitor
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/fieldvisitor/CustomFieldsVisitor.java
  server/src/main/java/org/opensearch/index/fieldvisitor/FieldsVisitor.java
  server/src/main/java/org/opensearch/search/fetch/FetchPhase.java
  server/src/test/java/org/opensearch/index/mapper/StoredNumericValuesTests.java
  server/src/test/java/org/opensearch/search/fetch/FetchPhaseTests.java
Labels: backport 2.x, v2.19.0

#17108 Fix exists query for flat object
  rest-api-spec/src/main/resources/rest-api-spec/test/index/100_partial_flat_object.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/105_partial_flat_object_nested.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/91_flat_object_null_value.yml
  server/src/main/java/org/opensearch/index/mapper/FlatObjectFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java
Labels: bug, skip-changelog, Search:Query Capabilities

#16957 Added new Setting property `UnmodifiableOnRestore` to prevent updating settings on restore snapshot
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/RestoreShallowSnapshotV2IT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/common/settings/AbstractScopedSettings.java
  server/src/main/java/org/opensearch/common/settings/Setting.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/common/settings/ScopedSettingsTests.java
  server/src/test/java/org/opensearch/common/settings/SettingTests.java
Labels: backport 2.x

#17113 Fix Binlong's name in MAINTAINERS.md
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#17005 Stop processing search requests when _msearch is canceled
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/TransportMultiSearchAction.java
  server/src/test/java/org/opensearch/action/search/TransportMultiSearchActionTests.java
Labels: bug, v3.0.0, backport 2.x, Search:Resiliency, v2.19.0

#17128 Fix flaky test RemoteSegmentTransferTrackerTests.testGetInflightUploadBytes
  server/src/test/java/org/opensearch/index/remote/RemoteSegmentTransferTrackerTests.java
Labels: skip-changelog

#16494 Add opensearch version info while deserialization
  CHANGELOG.md
  server/src/main/java/org/opensearch/gateway/remote/RemoteClusterStateService.java
  server/src/main/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManager.java
  server/src/main/java/org/opensearch/gateway/remote/model/RemoteCustomMetadata.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteGlobalMetadataManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/model/RemoteCustomMetadataTests.java
Labels: backport 2.x

#16674 [Star Tree] [Search] Resolving Date histogram with metric aggregation using star-tree
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DateDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeQueryHelper.java
  server/src/main/java/org/opensearch/search/aggregations/StarTreeBucketCollector.java
  server/src/main/java/org/opensearch/search/aggregations/StarTreePreComputeCollector.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/BucketsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/AvgAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/SumAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/ValueCountAggregator.java
  server/src/main/java/org/opensearch/search/startree/StarTreeFilter.java
  server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DateHistogramAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/StarTreeFilterTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, Search:Aggregations, backport 2.x

#17145 Update Gradle to 8.12.1
  gradle/wrapper/gradle-wrapper.properties
Labels: backport 2.x, skip-changelog, Build

#17141 OpenJDK Update (January 2025 Patch releases)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  gradle/libs.versions.toml
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Labels: skip-changelog, Build

#17143 OpenJDK Update (January 2025 Patch releases)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Labels: skip-changelog, Build

#17144 OpenJDK Update (January 2025 Patch releases)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  buildSrc/version.properties
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Labels: skip-changelog, Build

#17139 OpenJDK Update (January 2025 Patch releases)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  gradle/libs.versions.toml
  server/src/test/java/org/opensearch/common/time/DateUtilsTests.java
Labels: skip-changelog, Build

#17039 Add support for append only indices
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/core/index/AppendOnlyIndexOperationRetryException.java
  server/src/internalClusterTest/java/org/opensearch/action/bulk/AppendOnlyIndicesIT.java
  server/src/main/java/org/opensearch/action/bulk/BulkPrimaryExecutionContext.java
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/test/java/org/opensearch/action/bulk/BulkPrimaryExecutionContextTests.java
Labels: backport 2.x, v2.19.0

#17156 Add Star Tree unsigned-long indexing changes
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesReader.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/Dimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionDataType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/ReadDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/UnsignedLongDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/StarTreeWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/DimensionConfig.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentsSorter.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/search/startree/StarTreeFilter.java
  server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BuilderTestsUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuildMetricTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderFlushFlowTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderMergeFlowTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderTestCase.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentsSorterTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: backport 2.x, skip-changelog

#17151 Remove MasterService class
  server/src/internalClusterTest/java/org/opensearch/clustermanager/ClusterManagerTaskThrottlingIT.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/cluster/service/MasterService.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/MasterServiceRenamedSettingTests.java
  test/framework/src/main/java/org/opensearch/cluster/coordination/AbstractCoordinatorTestCase.java
  test/framework/src/main/java/org/opensearch/cluster/service/FakeThreadPoolClusterManagerService.java
  test/framework/src/main/java/org/opensearch/cluster/service/FakeThreadPoolMasterService.java
  test/framework/src/main/java/org/opensearch/test/ClusterServiceUtils.java
  test/framework/src/main/java/org/opensearch/test/disruption/BlockMasterServiceOnMaster.java
  test/framework/src/main/java/org/opensearch/test/disruption/BusyMasterServiceDisruption.java
Labels: skip-changelog

#17161 [Backport 2.x] Add Star Tree unsigned-long indexing changes (#17156)
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/index/codec/composite/composite912/Composite912DocValuesReader.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/Dimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionDataType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionFactory.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/ReadDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/UnsignedLongDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/BaseStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OffHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/OnHeapStarTreeBuilder.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/StarTreeWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/DimensionConfig.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadata.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataWriter.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/index/StarTreeValues.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentsSorter.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/search/startree/StarTreeFilter.java
  server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/StarTreeDocValuesFormatTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeTestUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/BuilderTestsUtils.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuildMetricTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderFlushFlowTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderMergeFlowTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreeBuilderTestCase.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/meta/StarTreeMetadataTests.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeDocumentsSorterTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
Labels: skip-changelog

#17023 Fix auto date histogram rounding assertion bug
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/main/java/org/opensearch/search/DocValueFormat.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/DateHistogramAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: bug, backport 2.x, Search

#16981 [WLM] add wlm support for scroll API
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/TransportSearchScrollAction.java
  server/src/main/java/org/opensearch/wlm/QueryGroupTask.java
  server/src/main/java/org/opensearch/wlm/tracker/QueryGroupResourceUsageTrackerService.java
  server/src/test/java/org/opensearch/wlm/tracker/QueryGroupTaskResourceTrackingTests.java
  server/src/test/java/org/opensearch/wlm/tracker/ResourceUsageCalculatorTrackerServiceTests.java
Labels: bug, backport 2.x, Search, v2.19.0

#17166 Remove more deprecated master classes
  server/src/internalClusterTest/java/org/opensearch/remotestore/RemoteRestoreSnapshotIT.java
  server/src/main/java/org/opensearch/action/support/clustermanager/ClusterManagerNodeOperationRequestBuilder.java
  server/src/main/java/org/opensearch/cluster/LocalNodeMasterListener.java
  server/src/main/java/org/opensearch/cluster/MasterNodeChangePredicate.java
  server/src/main/java/org/opensearch/cluster/NotMasterException.java
  server/src/main/java/org/opensearch/cluster/coordination/UnsafeBootstrapMasterCommand.java
  server/src/main/java/org/opensearch/cluster/service/ClusterApplierService.java
  server/src/main/java/org/opensearch/common/settings/ConsistentSettingsService.java
  server/src/main/java/org/opensearch/discovery/MasterNotDiscoveredException.java
  server/src/main/java/org/opensearch/rest/action/cat/RestMasterAction.java
  server/src/test/java/org/opensearch/ExceptionSerializationTests.java
  server/src/test/java/org/opensearch/action/RenamedTimeoutRequestParameterTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionUtils.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportMasterNodeActionUtils.java
  server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
  server/src/test/java/org/opensearch/common/settings/ConsistentSettingsServiceTests.java
  server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
Labels: skip-changelog

#17163 [Backport 2.x] [Star Tree] [Search] Resolving Date histogram with metric aggregation using star-tree
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DateDimension.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeQueryHelper.java
  server/src/main/java/org/opensearch/search/aggregations/StarTreeBucketCollector.java
  server/src/main/java/org/opensearch/search/aggregations/StarTreePreComputeCollector.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/BucketsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/AvgAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/SumAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/ValueCountAggregator.java
  server/src/main/java/org/opensearch/search/startree/StarTreeFilter.java
  server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DateHistogramAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/StarTreeFilterTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, Search:Aggregations, v2.19.0

#17172 Fix failing CI's with `Failed to load eclipse jdt formatter`.
  CHANGELOG.md
  gradle/formatting.gradle
Labels: backport 2.x, skip-changelog

#17137 Extensible design to add new query and field type support for Star Tree
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/StarTreeQueryHelper.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/iterator/SortedNumericStarTreeValuesIterator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/iterator/SortedSetStarTreeValuesIterator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/utils/iterator/StarTreeValuesIterator.java
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/AvgAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/SumAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/ValueCountAggregator.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/main/java/org/opensearch/search/startree/StarTreeNodeCollector.java
  server/src/main/java/org/opensearch/search/startree/StarTreeQueryContext.java
  server/src/main/java/org/opensearch/search/startree/StarTreeQueryHelper.java
  server/src/main/java/org/opensearch/search/startree/StarTreeTraversalUtil.java
  server/src/main/java/org/opensearch/search/startree/filter/DimensionFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/ExactMatchDimFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/MatchNoneFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/RangeMatchDimFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/StarTreeFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/package-info.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/DimensionFilterMapper.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/StarTreeFilterProvider.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/package-info.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNodeSearchTests.java
  server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/ArrayBasedCollector.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DateHistogramAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DimensionFilterAndMapperTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/StarTreeFilterTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, backport 2.x, Search

#17177 Throwing exception for any update call for Append only indices
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: backport 2.x, skip-changelog, v2.19.0

#17180 Enforcing append only setting for star-tree index
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldMapperTests.java
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/test/java/org/opensearch/cluster/metadata/TranslogFlushIntervalSettingsTests.java
  server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/AbstractStarTreeDVFormatTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
  server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
Labels: backport 2.x, skip-changelog

#17184 [Backport 2.x] Enforcing append only setting for star-tree index (#17180)
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldMapperTests.java
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/test/java/org/opensearch/cluster/metadata/TranslogFlushIntervalSettingsTests.java
  server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/AbstractStarTreeDVFormatTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
  server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
Labels: skip-changelog

#16958 [Pull-based Ingestion] Introduce the new pull-based ingestion engine, APIs, and Kafka plugin
  CHANGELOG-3.0.md
  gradle/missing-javadoc.gradle
  plugins/ingestion-kafka/build.gradle
  plugins/ingestion-kafka/licenses/kafka-clients-3.8.1.jar.sha1
  plugins/ingestion-kafka/licenses/kafka-clients-LICENSE.txt
  plugins/ingestion-kafka/licenses/kafka-clients-NOTICE.txt
  plugins/ingestion-kafka/licenses/slf4j-api-1.7.36.jar.sha1
  plugins/ingestion-kafka/licenses/slf4j-api-LICENSE.txt
  plugins/ingestion-kafka/licenses/slf4j-api-NOTICE.txt
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java
  plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaConsumerFactory.java
  plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaMessage.java
  plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaOffset.java
  plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaPartitionConsumer.java
  plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaPlugin.java
  plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaSourceConfig.java
  plugins/ingestion-kafka/src/main/plugin-metadata/plugin-security.policy
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaConsumerFactoryTests.java
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaMessageTests.java
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaOffsetTests.java
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaPartitionConsumerTests.java
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaSourceConfigTests.java
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaUtils.java
  server/build.gradle
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IngestionConsumerFactory.java
  server/src/main/java/org/opensearch/index/IngestionShardConsumer.java
  server/src/main/java/org/opensearch/index/IngestionShardPointer.java
  server/src/main/java/org/opensearch/index/Message.java
  server/src/main/java/org/opensearch/index/engine/EngineConfig.java
  server/src/main/java/org/opensearch/index/engine/EngineConfigFactory.java
  server/src/main/java/org/opensearch/index/engine/IngestionEngine.java
  server/src/main/java/org/opensearch/index/engine/NoOpEngine.java
  server/src/main/java/org/opensearch/index/engine/ReadOnlyEngine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
  server/src/main/java/org/opensearch/indices/pollingingest/IngestionEngineFactory.java
  server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java
  server/src/main/java/org/opensearch/indices/pollingingest/StreamPoller.java
  server/src/main/java/org/opensearch/indices/pollingingest/package-info.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/IngestionConsumerPlugin.java
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
  server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java
  server/src/test/java/org/opensearch/index/engine/EngineConfigFactoryTests.java
  server/src/test/java/org/opensearch/index/engine/FakeIngestionSource.java
  server/src/test/java/org/opensearch/index/engine/IngestionEngineTests.java
  server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
  server/src/test/java/org/opensearch/indices/pollingingest/MessageProcessorTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, Indexing

#17183 Fix java.security.AccessControlException during OpenSearch server shutdown cycle
  modules/transport-netty4/src/main/java/org/opensearch/transport/SharedGroupFactory.java
  modules/transport-netty4/src/main/plugin-metadata/plugin-security.policy
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/transport/reactor/SharedGroupFactory.java
  plugins/transport-reactor-netty4/src/main/plugin-metadata/plugin-security.policy
  server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java
  server/src/main/resources/org/opensearch/bootstrap/security.policy
Labels: backport 2.x, skip-changelog

#17188 Remove deprecated 'reindex.remote.whitelist` setting
  modules/reindex/src/main/java/org/opensearch/index/reindex/ReindexModulePlugin.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/TransportReindexAction.java
  modules/reindex/src/test/java/org/opensearch/index/reindex/ReindexRenamedSettingTests.java
Labels: skip-changelog

#17193 Fix flaky TransportMultiSearchActionTests.testCancellation
  server/src/test/java/org/opensearch/action/search/TransportMultiSearchActionTests.java
Labels: flaky-test, skip-changelog

#16733 Unify precomputation of aggregations behind a common API
  server/src/main/java/org/opensearch/search/aggregations/AggregatorBase.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/AvgAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/SumAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/ValueCountAggregator.java
  server/src/main/java/org/opensearch/search/startree/StarTreeQueryHelper.java
Labels: skip-changelog

#17121 Register UnmodifiableOnRestore settings
  client/rest-high-level/src/test/java/org/opensearch/client/IndicesClientIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/create/CreateIndexIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  test/framework/src/main/java/org/opensearch/test/InternalSettingsPlugin.java
Labels: v3.0.0, skip-changelog

#17194 Replace usage of transitive shaded dependency
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaUtils.java
Labels: skip-changelog

#17205 [Backport] [1.x] Fix java.security.AccessControlException during OpenSearch server shutdown cycle (#17183)
  modules/transport-netty4/src/main/java/org/opensearch/transport/SharedGroupFactory.java
  modules/transport-netty4/src/main/plugin-metadata/plugin-security.policy
  server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java
  server/src/main/resources/org/opensearch/bootstrap/security.policy
Labels: skip-changelog

#17204 [Backport] [1.3] Fix java.security.AccessControlException during OpenSearch server shutdown cycle (#17183)
  modules/transport-netty4/src/main/java/org/opensearch/transport/SharedGroupFactory.java
  modules/transport-netty4/src/main/plugin-metadata/plugin-security.policy
  server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java
  server/src/main/resources/org/opensearch/bootstrap/security.policy
Labels: skip-changelog

#17101 Add highlighting for match_only_text type
  CHANGELOG.md
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/11_match_field_match_only_text.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/30_ngram_highlighting.yml
  modules/analysis-common/src/yamlRestTest/resources/rest-api-spec/test/search.query/30_ngram_highlighting_field_match_only_text.yml
  server/src/main/java/org/opensearch/search/fetch/subphase/highlight/HighlightPhase.java
Labels: backport 2.x, v2.19.0

#17175 [Backport 2.x] Fix auto date histogram rounding assertion bug
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/Rounding.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/DateHistogramAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: backport 2.19

#17195 Remove DEBUG log level from test cluster node
  buildSrc/src/main/java/org/opensearch/gradle/testclusters/OpenSearchNode.java
Labels: skip-changelog

#17217 Update dependabot_pr workflow to use jdk 21
  .github/workflows/dependabot_pr.yml
Labels: skip-changelog

#17209 Update 2.x to 2.20.0
  buildSrc/version.properties
  gradle/libs.versions.toml
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#17220 [Forwardport] [main] Update 2.x to 2.20.0
  .ci/bwcVersions
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#17218 More removal of deprecated 'master' code
  client/rest-high-level/src/main/java/org/opensearch/client/RequestConverters.java
  client/rest-high-level/src/main/java/org/opensearch/client/TimedRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComponentTemplatesRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetComposableIndexTemplateRequest.java
  client/rest-high-level/src/main/java/org/opensearch/client/indices/GetIndexTemplatesRequest.java
  client/rest/src/main/java/org/opensearch/client/Node.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RepositoriesIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java
  server/src/main/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeAction.java
  server/src/main/java/org/opensearch/action/support/clustermanager/info/TransportClusterInfoAction.java
  server/src/main/java/org/opensearch/cluster/ClusterChangedEvent.java
  server/src/main/java/org/opensearch/cluster/ClusterStateTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/ClusterStateTaskListener.java
  server/src/main/java/org/opensearch/cluster/action/index/MappingUpdatedAction.java
  server/src/main/java/org/opensearch/cluster/coordination/JoinTaskExecutor.java
  server/src/main/java/org/opensearch/cluster/coordination/NoClusterManagerBlockService.java
  server/src/main/java/org/opensearch/cluster/coordination/PeersResponse.java
  server/src/main/java/org/opensearch/cluster/health/ClusterStateHealth.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodes.java
  server/src/main/java/org/opensearch/cluster/routing/DelayedAllocationService.java
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
  server/src/main/java/org/opensearch/rest/action/admin/cluster/RestRestoreRemoteStoreAction.java
  server/src/test/java/org/opensearch/action/admin/cluster/remotestore/restore/RestoreRemoteStoreRequestTests.java
  server/src/test/java/org/opensearch/action/support/clustermanager/TransportClusterManagerNodeActionTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/coordination/NodeJoinTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterApplierServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java
  server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
  test/framework/src/main/java/org/opensearch/snapshots/AbstractSnapshotIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
  test/framework/src/main/java/org/opensearch/test/NodeRoles.java
  test/framework/src/main/java/org/opensearch/test/TestCluster.java
  test/framework/src/main/java/org/opensearch/test/rest/yaml/ClientYamlTestClient.java
  test/framework/src/main/java/org/opensearch/test/rest/yaml/ClientYamlTestExecutionContext.java
Labels: skip-changelog
