Repository opensearch-project/OpenSearch, pull requests merged in 2025-10, with the labels that each got.

#19438 Add sub aggregation support for histogram aggregation using skiplist
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregatorTests.java
Labels: Search:Aggregations, Performance, v3.3.0

#19497 [Rule-based Auto-tagging] bug fix on Update Rule API with multiple attributes
  CHANGELOG.md
  modules/autotagging-commons/common/src/main/java/org/opensearch/rule/RuleUtils.java
Labels: v3.3.0

#19396 Harden the circuit breaker and failure handle logic in query result consumer
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/QueryPhaseResultConsumer.java
  server/src/main/java/org/opensearch/action/search/StreamQueryPhaseResultConsumer.java
  server/src/test/java/org/opensearch/action/search/SearchPhaseControllerTests.java
Labels: v3.3.0, backport 3.3

#19488 Streaming aggregation planning to determine the appropriate flush mode
  CHANGELOG.md
  plugins/arrow-flight-rpc/src/internalClusterTest/java/org/opensearch/streaming/aggregation/SubAggregationIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/aggregations/AggregationCollectorManager.java
  server/src/main/java/org/opensearch/search/aggregations/AggregatorTreeEvaluator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/StreamNumericTermsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/StreamStringTermsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java
  server/src/main/java/org/opensearch/search/internal/ContextIndexSearcher.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/main/java/org/opensearch/search/profile/aggregation/ProfilingAggregator.java
  server/src/main/java/org/opensearch/search/streaming/FlushMode.java
  server/src/main/java/org/opensearch/search/streaming/FlushModeResolver.java
  server/src/main/java/org/opensearch/search/streaming/Streamable.java
  server/src/main/java/org/opensearch/search/streaming/StreamingCostMetrics.java
  server/src/main/java/org/opensearch/search/streaming/package-info.java
  server/src/test/java/org/opensearch/search/DefaultSearchContextTests.java
  server/src/test/java/org/opensearch/search/aggregations/AggregatorTreeEvaluatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/StreamNumericTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/StreamStringTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/streaming/FlushModeResolverTests.java
  server/src/test/java/org/opensearch/search/streaming/StreamingCostMetricsTests.java
Labels: v3.3.0, backport 3.3

#19484 Expand streaming Aggregations to Cardinality Aggregator
  CHANGELOG.md
  plugins/arrow-flight-rpc/src/internalClusterTest/java/org/opensearch/streaming/aggregation/SubAggregationIT.java
  server/src/main/java/org/opensearch/search/aggregations/AggregatorBase.java
  server/src/main/java/org/opensearch/search/aggregations/BucketCollectorProcessor.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/StreamCardinalityAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/StreamCardinalityAggregatorTests.java
Labels: v3.3.0

#19496 Fix derived query rewrite
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/query/DerivedFieldQuery.java
  server/src/test/java/org/opensearch/index/mapper/DerivedFieldMapperQueryTests.java
  server/src/test/java/org/opensearch/index/query/DerivedFieldQueryTests.java
Labels: bug, Search, lucene, v3.3.0, backport 3.3

#19520 Disable request cache for streaming and other fixes
  CHANGELOG.md
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MaxAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/MinAggregator.java
  server/src/main/java/org/opensearch/search/profile/aggregation/ProfilingAggregator.java
  server/src/main/java/org/opensearch/search/streaming/FlushModeResolver.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/MaxAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/MinAggregatorTests.java
Labels: bug, Search, v3.3.0

#19538 Exclude commons-lang and org.jsonschema2pojo from hadoop-miniclusters
  CHANGELOG.md
  test/fixtures/hdfs-fixture/build.gradle
Labels: backport 3.3

#19540 Bump lucene version from 10.3.0 to 10.3.1
  CHANGELOG.md
  gradle/libs.versions.toml
  libs/core/licenses/lucene-core-10.3.0.jar.sha1
  libs/core/licenses/lucene-core-10.3.1.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-10.3.0.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-10.3.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-10.3.0.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-10.3.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-10.3.0.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-10.3.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-10.3.0.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-10.3.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-10.3.0.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-10.3.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-10.3.0.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-10.3.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-10.3.0.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-10.3.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-10.3.0.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-10.3.1.jar.sha1
  server/licenses/lucene-analysis-common-10.3.0.jar.sha1
  server/licenses/lucene-analysis-common-10.3.1.jar.sha1
  server/licenses/lucene-backward-codecs-10.3.0.jar.sha1
  server/licenses/lucene-backward-codecs-10.3.1.jar.sha1
  server/licenses/lucene-core-10.3.0.jar.sha1
  server/licenses/lucene-core-10.3.1.jar.sha1
  server/licenses/lucene-grouping-10.3.0.jar.sha1
  server/licenses/lucene-grouping-10.3.1.jar.sha1
  server/licenses/lucene-highlighter-10.3.0.jar.sha1
  server/licenses/lucene-highlighter-10.3.1.jar.sha1
  server/licenses/lucene-join-10.3.0.jar.sha1
  server/licenses/lucene-join-10.3.1.jar.sha1
  server/licenses/lucene-memory-10.3.0.jar.sha1
  server/licenses/lucene-memory-10.3.1.jar.sha1
  server/licenses/lucene-misc-10.3.0.jar.sha1
  server/licenses/lucene-misc-10.3.1.jar.sha1
  server/licenses/lucene-queries-10.3.0.jar.sha1
  server/licenses/lucene-queries-10.3.1.jar.sha1
  server/licenses/lucene-queryparser-10.3.0.jar.sha1
  server/licenses/lucene-queryparser-10.3.1.jar.sha1
  server/licenses/lucene-sandbox-10.3.0.jar.sha1
  server/licenses/lucene-sandbox-10.3.1.jar.sha1
  server/licenses/lucene-spatial-extras-10.3.0.jar.sha1
  server/licenses/lucene-spatial-extras-10.3.1.jar.sha1
  server/licenses/lucene-spatial3d-10.3.0.jar.sha1
  server/licenses/lucene-spatial3d-10.3.1.jar.sha1
  server/licenses/lucene-suggest-10.3.0.jar.sha1
  server/licenses/lucene-suggest-10.3.1.jar.sha1
  test/framework/licenses/lucene-codecs-10.3.0.jar.sha1
  test/framework/licenses/lucene-codecs-10.3.1.jar.sha1
  test/framework/licenses/lucene-test-framework-10.3.0.jar.sha1
  test/framework/licenses/lucene-test-framework-10.3.1.jar.sha1
Labels: backport 3.3

#19416 StreamStringTermsAggregator explicitly asserts single leaf
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/StreamStringTermsAggregator.java
  server/src/main/java/org/opensearch/search/profile/aggregation/ProfilingAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/StreamStringTermsAggregatorTests.java
Labels: skip-changelog

#19556 [2.19] remove license files from ingestion-kinesis which does not exist in 2.19
  plugins/ingestion-kinesis/licenses/netty-buffer-4.1.125.Final.jar.sha1
  plugins/ingestion-kinesis/licenses/netty-codec-4.1.125.Final.jar.sha1
  plugins/ingestion-kinesis/licenses/netty-codec-http-4.1.125.Final.jar.sha1
  plugins/ingestion-kinesis/licenses/netty-codec-http2-4.1.125.Final.jar.sha1
  plugins/ingestion-kinesis/licenses/netty-common-4.1.125.Final.jar.sha1
  plugins/ingestion-kinesis/licenses/netty-handler-4.1.125.Final.jar.sha1
  plugins/ingestion-kinesis/licenses/netty-resolver-4.1.125.Final.jar.sha1
  plugins/ingestion-kinesis/licenses/netty-transport-4.1.125.Final.jar.sha1
  plugins/ingestion-kinesis/licenses/netty-transport-classes-epoll-4.1.125.Final.jar.sha1
  plugins/ingestion-kinesis/licenses/netty-transport-native-unix-common-4.1.125.Final.jar.sha1
Labels: skip-changelog

#19555 Increment version to 3.4 and clear the CHANGELOG
  .ci/bwcVersions
  CHANGELOG.md
  buildSrc/version.properties
  gradle/libs.versions.toml
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#19549 Add karenyrx as a maintainer
  MAINTAINERS.md
Labels: skip-changelog

#19551 Refactor to move prepareIndex and prepareDelete methods to the Engine
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/engine/Engine.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  test/framework/src/main/java/org/opensearch/index/engine/TranslogHandler.java
Labels: enhancement, Indexing

#19553 Use `pack` method for `half_float` and `usigned_long`
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/mapper/NumberFieldMapper.java
Labels: Search:Performance
