Repository opensearch-project/OpenSearch, pull requests merged in 2025-04, with the labels that each got.

#17627 Add FilterFieldType
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/index/mapper/FilterFieldTypeTest.java
  server/src/main/java/org/opensearch/index/mapper/FilterFieldType.java
  server/src/main/java/org/opensearch/index/mapper/MappedFieldType.java
Labels: enhancement, Search:Query Capabilities

#17765 Skip list creation on stack walker
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SocketChannelInterceptor.java
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerChainExtractor.java
Labels: skip-changelog

#17741 Support AutoExpand for SearchReplica
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/metadata/AutoExpandSearchReplicasIT.java
  server/src/main/java/org/opensearch/cluster/metadata/AutoExpandReplicas.java
  server/src/main/java/org/opensearch/cluster/metadata/AutoExpandSearchReplicas.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AllocationService.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/AwarenessReplicaBalance.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/test/java/org/opensearch/cluster/metadata/AutoExpandReplicasTests.java
  server/src/test/java/org/opensearch/cluster/metadata/AutoExpandSearchReplicasTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationServiceTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AwarenessReplicaBalanceTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: enhancement, Search:Performance

#17720 Fix weight calculation of decideRebalance when explain
  server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/LocalShardsBalancer.java
Labels: skip-changelog

#17784 Fix socket interceptor and add unit test
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SocketChannelInterceptor.java
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerProtectionDomainChainExtractor.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/AgentTestCase.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/AgentTests.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/SocketChannelInterceptorTests.java
Labels: skip-changelog

#17793 Fix StackCallerClassChainExtractor and respectively RuntimeHaltInterceptor, SystemExitInterceptor
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/RuntimeHaltInterceptor.java
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerClassChainExtractor.java
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SystemExitInterceptor.java
  libs/agent-sm/bootstrap/src/main/java/org/opensearch/javaagent/bootstrap/AgentPolicy.java
Labels: skip-changelog

#17798 Add some additional tests for SocketChannelInterceptor
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/SocketChannelInterceptorTests.java
Labels: enhancement, security, skip-changelog

#17786 Introduce 512 byte limit to search and ingest pipeline IDs
  CHANGELOG.md
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
  server/src/test/java/org/opensearch/search/pipeline/SearchPipelineServiceTests.java
Labels: bug, good first issue, ingest-pipeline

#17799 Check for gradle.xml before trying to modify it
  gradle/ide.gradle
Labels: skip-changelog

#17805 Remove dblock@ from core maintainers.
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#17806 [Backport 2.x] Remove dblock@ from maintainers.
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog

#17816 Fix FileInterceptor to deduct the access level from the list of OpenOption
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/FileInterceptor.java
Labels: skip-changelog

#17821 Remove dependency on :test:framework in :libs:opensearch-agent-sm:agent-policy
  gradle/libs.versions.toml
  libs/agent-sm/agent-policy/build.gradle
  libs/agent-sm/agent-policy/src/test/java/org/opensearch/secure_sm/policy/PolicyParserTests.java
Labels: skip-changelog

#17778 Fix possible NPE in RestTasksAction.java
  server/src/main/java/org/opensearch/rest/action/cat/RestTasksAction.java
  server/src/test/java/org/opensearch/rest/action/cat/RestTasksActionTests.java
Labels: bug, skip-changelog, Cluster Manager

#17836 Fix FileInterceptor to properly check read / write sides path separation
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/FileInterceptor.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/FileInterceptorIntegTests.java
Labels: skip-changelog

#17750 Fix remove skip tags for version 6
  modules/geo/src/yamlRestTest/resources/rest-api-spec/test/geo_shape/290_geotile_grid.yml
  qa/rolling-upgrade/src/test/resources/rest-api-spec/test/old_cluster/20_date_range.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/cat.thread_pool/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/cluster.state/20_filtering.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/cluster.voting_config_exclusions/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/create/10_with_id.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/create/15_without_id.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/create/35_external_version.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/create/40_routing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/create/60_refresh.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/delete/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/delete/11_shard_header.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/delete/12_result.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/delete/20_cas.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/delete/25_external_version.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/delete/26_external_gte_version.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/delete/30_routing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/delete/50_refresh.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/delete/60_missing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/exists/40_routing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/exists/60_realtime_refresh.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/get/40_routing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/get/50_with_headers.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/get/60_realtime_refresh.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/get/90_versions.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/get_source/40_routing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/get_source/60_realtime_refresh.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/get_source/80_missing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/get_source/85_source_missing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/10_with_id.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/15_without_id.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/20_optype.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/35_external_version.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/36_external_gte_version.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/40_routing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/index/60_refresh.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.shrink/20_source_mapping.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/mget/40_routing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/mget/60_realtime_refresh.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/40_range.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search.inner_hits/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/search/115_multiple_field_collapsing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/termvectors/10_basic.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/update/11_shard_header.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/update/35_if_seq_no.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/update/40_routing.yml
  rest-api-spec/src/main/resources/rest-api-spec/test/update/60_refresh.yml
Labels: skip-changelog

#17803 Added Search Only strict routing setting
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java
Labels: bug

#17670 Switch from IOContext.DEFAULT(RANDOM) to READONLY for sequential cases
  server/src/main/java/org/opensearch/common/settings/KeyStoreWrapper.java
  server/src/main/java/org/opensearch/gateway/MetadataStateFormat.java
  server/src/main/java/org/opensearch/index/translog/Checkpoint.java
Labels: enhancement, skip-changelog, Search

#17840 Fix possible NPE in WorkerBulkByScrollTaskState.java
  server/src/main/java/org/opensearch/index/reindex/WorkerBulkByScrollTaskState.java
Labels: bug, skip-changelog

#17643 Add singleton optimization for DateHistogramAggregator
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
Labels: backport 2.x, Search:Performance

#17832 [Java Agent] Implement protection domain caching
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PolicyFile.java
Labels: skip-changelog

#17844 Support `_close` and `_open` of an index in `search_only` mode
  server/src/internalClusterTest/java/org/opensearch/cluster/metadata/MetadataIndexStateServiceIT.java
  server/src/main/java/org/opensearch/action/support/ActiveShardCount.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexStateService.java
  server/src/main/java/org/opensearch/cluster/routing/IndexRoutingTable.java
Labels: v3.0.0, skip-changelog

#17838 Update StartupException.java
  server/src/main/java/org/opensearch/bootstrap/StartupException.java
Labels: bug, skip-changelog

#17848 Fix ScaleIndexIT `testFullSearchOnlyReplicasFullLifecycle` flaky test
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/scale/searchonly/ScaleIndexIT.java
Labels: skip-changelog

#17814 Add a builder to ingestion source
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java
  server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java
Labels: skip-changelog

#17852 Add the support of trusted file systems to AgentPolicy
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/FileInterceptor.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/AgentTestCase.java
  libs/agent-sm/bootstrap/src/main/java/org/opensearch/javaagent/bootstrap/AgentPolicy.java
Labels: skip-changelog

#17801 Remove deprecated batch_size parameter from _bulk
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/ingest/IngestClientIT.java
  server/src/main/java/org/opensearch/action/bulk/BulkRequest.java
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/rest/action/document/RestBulkAction.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
Labels: enhancement, >breaking, v3.0.0, Indexing

#17611 Refactor FeatureFlags
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  modules/mapper-extras/src/test/java/org/opensearch/index/mapper/ScaledFloatFieldMapperTests.java
  plugins/arrow-flight-rpc/src/internalClusterTest/java/org/opensearch/arrow/flight/ArrowFlightServerIT.java
  plugins/arrow-flight-rpc/src/test/java/org/opensearch/arrow/flight/FlightStreamPluginTests.java
  plugins/arrow-flight-rpc/src/test/java/org/opensearch/arrow/flight/bootstrap/FlightClientManagerTests.java
  plugins/arrow-flight-rpc/src/test/java/org/opensearch/arrow/flight/bootstrap/FlightServiceTests.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/test/java/org/opensearch/action/admin/indices/shrink/TransportResizeActionTests.java
  server/src/test/java/org/opensearch/cluster/applicationtemplates/SystemTemplatesServiceTests.java
  server/src/test/java/org/opensearch/cluster/coordination/JoinTaskExecutorTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/FailedShardsRoutingTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/ShardsTieringAllocationTests.java
  server/src/test/java/org/opensearch/common/settings/SettingsModuleTests.java
  server/src/test/java/org/opensearch/common/util/FeatureFlagTests.java
  server/src/test/java/org/opensearch/extensions/ExtensionsManagerTests.java
  server/src/test/java/org/opensearch/gateway/remote/RemoteClusterStateServiceTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/codec/composite912/datacube/startree/AbstractStarTreeDVFormatTests.java
  server/src/test/java/org/opensearch/index/engine/ReadOnlyEngineTests.java
  server/src/test/java/org/opensearch/index/mapper/ObjectMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/StarTreeMapperTests.java
  server/src/test/java/org/opensearch/index/store/StoreTests.java
  server/src/test/java/org/opensearch/node/NodeTests.java
  server/src/test/java/org/opensearch/search/SearchModuleTests.java
  server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DateHistogramAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/KeywordTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/NumericTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/StarTreeFilterTests.java
  test/framework/src/main/java/org/opensearch/test/FeatureFlagSetter.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java
Labels: bug, good first issue, v3.0.0, Search

#17858 Fix feature flag error in SearchServiceStarTreeTests
  server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
Labels: skip-changelog

#17513 [Tiered Cache] Using a single cache manager for all ehcache disk caches
  CHANGELOG.md
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/EhcacheDiskCacheSettings.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCache.java
  plugins/cache-ehcache/src/main/java/org/opensearch/cache/store/disk/EhcacheDiskCacheManager.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhCacheDiskCacheTests.java
  plugins/cache-ehcache/src/test/java/org/opensearch/cache/store/disk/EhcacheDiskCacheManagerTests.java
Labels: backport 2.x

#17857 Rename search_only_replica settings to search_replica
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaReplicationAndRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java
  server/src/internalClusterTest/java/org/opensearch/snapshots/RestoreSnapshotIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/test/java/org/opensearch/cluster/metadata/SearchOnlyReplicaTests.java
  server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java
Labels: skip-changelog

#17865 Adjust the `getAutoExpandReplicaChanges` logic to honor `search_only` mode.
  server/src/internalClusterTest/java/org/opensearch/indices/settings/UpdateNumberOfReplicasIT.java
  server/src/main/java/org/opensearch/cluster/metadata/AutoExpandReplicas.java
  server/src/test/java/org/opensearch/cluster/metadata/AutoExpandReplicasTests.java
Labels: skip-changelog

#17867 Remove reference to removed class org.opensearch.secure_sm.SecureSM
  test/framework/src/main/java/org/opensearch/bootstrap/BootstrapForTesting.java
Labels: skip-changelog

#17869 Fix :libs:agent-sm:agent publication
  libs/agent-sm/agent/build.gradle
Labels: v3.0.0, autocut, skip-changelog

#17824 Increase window interval for CancellableBulkScorer inline with BooleanScorer
  server/src/main/java/org/opensearch/search/internal/CancellableBulkScorer.java
Labels: bug, good first issue, v3.0.0, skip-changelog, Search:Performance

#17216 Fix flaky test SegmentReplicationIT.testReplicaAlreadyAtCheckpoint
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
Labels: good first issue, >test-failure, flaky-test, autocut, skip-changelog, Storage, Storage:Remote

#17873 Fix FileInterceptor's delete calls for Unix Domain Sockets on Windows
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/FileInterceptor.java
Labels: skip-changelog

#17878 Fix security policy for Windows based builds and deployments
  server/src/main/resources/org/opensearch/bootstrap/security.policy
  server/src/main/resources/org/opensearch/bootstrap/test-framework.policy
Labels: skip-changelog

#17882 Fix security policy for Windows based builds and deployments for transport plugins
  modules/transport-netty4/src/main/plugin-metadata/plugin-security.policy
  plugins/transport-reactor-netty4/src/main/plugin-metadata/plugin-security.policy
Labels: skip-changelog

#17568 [segment replication] Increase the default segment counter step size when replica promoting
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/engine/NRTReplicationEngine.java
Labels: enhancement, Indexing:Replication

#17575 Allow plugins to access/override some functions of ParametrizedFieldMapper; Modify the the constructor of the MappedFieldType to support FilterFieldType.
  server/src/main/java/org/opensearch/index/mapper/MappedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/ParametrizedFieldMapper.java
Labels: skip-changelog

#17886 Fix javaagent arg when running in IntelliJ
  gradle/ide.gradle
Labels: bug, skip-changelog, _No response_

#17275 Add query changes to support unsigned-long in star tree
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/compositeindex/datacube/DimensionDataType.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNode.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/node/StarTreeNode.java
  server/src/main/java/org/opensearch/search/startree/filter/ExactMatchDimFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/RangeMatchDimFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/DimensionFilterMapper.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNodeSearchTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/BigIntegerField.java
  server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java
Labels: enhancement, backport 2.x, Indexing:Performance

#17896 [Java Agent Policy Parser] Skip evaluation of AttachPermission
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/policy/PolicyFile.java
Labels: skip-changelog

#17775 Cardinality Aggregation dynamic pruning null pointer exception catch
  server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregator.java
Labels: Search:Aggregations, v3.0.0, skip-changelog

#17900 Custom Gradle plugin to leverage java agent
  buildSrc/src/main/java/org/opensearch/gradle/agent/JavaAgent.java
  buildSrc/src/main/resources/META-INF/gradle-plugins/opensearch.java-agent.properties
  buildSrc/src/test/java/org/opensearch/gradle/agent/JavaAgentTests.java
Labels: v3.0.0, skip-changelog

#17902 FIX BytesRefsCollectionBuilderTests.testBuildSortedNotSorted; Followup for #17714: Remove redundant tests
  server/src/test/java/org/opensearch/index/mapper/BytesRefsCollectionBuilderTests.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
Labels: skip-changelog

#17772 Approximate match all query with a sort
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/indices.validate_query/10_basic.yml
  server/src/internalClusterTest/java/org/opensearch/search/sort/FieldSortIT.java
  server/src/internalClusterTest/java/org/opensearch/validate/SimpleValidateQueryIT.java
  server/src/main/java/org/opensearch/index/query/MatchAllQueryBuilder.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateMatchAllQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximateScoreQuery.java
  server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
  server/src/test/java/org/opensearch/index/query/BoolQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/MatchAllQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/NestedQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/WrapperQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/functionscore/FunctionScoreQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/search/NestedHelperTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximateMatchAllQueryTests.java
  server/src/test/java/org/opensearch/search/sort/GeoDistanceSortBuilderTests.java
  server/src/test/java/org/opensearch/search/sort/ScriptSortBuilderTests.java
Labels: enhancement, v3.0.0, Roadmap:Cost/Performance/Scale

#17908 Remove ide.gradle debug artifact.
  gradle/ide.gradle
Labels: skip-changelog

#17447 Support sub agg in filter rewrite optimization
  CHANGELOG.md
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/CompositeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/AggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/DateHistogramAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/FilterRewriteOptimizationContext.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/PointTreeTraversal.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/RangeAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/Ranges.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/rangecollector/AbstractRangeCollector.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/rangecollector/RangeCollector.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/rangecollector/SimpleRangeCollector.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/rangecollector/SubAggRangeCollector.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/rangecollector/package-info.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/AutoDateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java
  server/src/main/java/org/opensearch/search/internal/SearchContext.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/filterrewrite/FilterRewriteSubAggTests.java
Labels: Search:Aggregations, v3.0.0, backport 2.x, Search:Performance, Roadmap:Search

#17905 Fix flaky test AzureBlobStoreRepositoryTests
  plugins/repository-azure/src/internalClusterTest/java/org/opensearch/repositories/azure/AzureBlobStoreRepositoryTests.java
Labels: skip-changelog

#17889 Disable scoring of Keyword Term search by default, allow user use old logic using useSimilarity parameter
  CHANGELOG.md
  modules/percolator/src/test/java/org/opensearch/percolator/QueryBuilderStoreTests.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/MappedFieldType.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
  server/src/test/java/org/opensearch/index/query/MultiMatchQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/SimpleQueryStringBuilderTests.java
  server/src/test/java/org/opensearch/index/query/functionscore/FunctionScoreQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/search/MultiMatchQueryTests.java
  server/src/test/java/org/opensearch/index/search/NestedHelperTests.java
  server/src/test/java/org/opensearch/search/sort/FieldSortBuilderTests.java
Labels: bug, Search

#17917 [FIX] Add agent files in deb/rpm
  distribution/packages/build.gradle
Labels: skip-changelog

#17880 Remove Reader Writer Split experimental feature flag
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/scale/searchonly/ScaleIndexIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/allocation/SearchReplicaAllocationIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/allocation/SearchReplicaAwarenessAllocationIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/metadata/AutoExpandSearchReplicasIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/metadata/MetadataIndexStateServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaReplicationAndRecoveryIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SearchReplicaRestoreIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaFeatureFlagIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java
  server/src/main/java/org/opensearch/cluster/ClusterModule.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNode.java
  server/src/main/java/org/opensearch/cluster/node/DiscoveryNodeRole.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/main/java/org/opensearch/cluster/routing/ShardRouting.java
  server/src/main/java/org/opensearch/common/settings/FeatureFlagSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/common/util/FeatureFlags.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/test/java/org/opensearch/cluster/ClusterModuleTests.java
  server/src/test/java/org/opensearch/cluster/ClusterStateTests.java
  server/src/test/java/org/opensearch/cluster/metadata/SearchOnlyReplicaTests.java
  server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/UpdateNumberOfReplicasTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/SearchReplicaAllocationDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/SearchReplicaAwarenessAllocationTests.java
  server/src/test/java/org/opensearch/common/settings/ScopedSettingsTests.java
  server/src/test/java/org/opensearch/index/IndexServiceTests.java
  test/framework/src/main/java/org/opensearch/cluster/OpenSearchAllocationTestCase.java
Labels: skip-changelog

#17918 [Pull-based Ingestion] Support versioning in pull-based ingestion
  CHANGELOG.md
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/KafkaIngestionBaseIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java
  server/src/main/java/org/opensearch/index/engine/IngestionEngine.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java
Labels: enhancement, Indexing

#17945 Add UT for getSleepDuration in AbstractAsyncTask
  server/src/test/java/org/opensearch/common/util/concurrent/AbstractAsyncTaskTests.java
Labels: skip-changelog

#17749 [segment replication] Add cluster setting for retry timeout of publish checkpoint tx action
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationIT.java
  server/src/main/java/org/opensearch/action/support/replication/TransportReplicationAction.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/PublishCheckpointAction.java
Labels: bug, Indexing:Replication

#17944 Fix flaky test BoolQueryBuilderTests.testToQuery
  server/src/test/java/org/opensearch/index/query/BoolQueryBuilderTests.java
Labels: skip-changelog

#17635 Introduce mapping transformer to allow transform mappings during index create/update or index template create/update
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/indices/create/TransportCreateIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/put/TransportPutMappingAction.java
  server/src/main/java/org/opensearch/action/admin/indices/template/put/TransportPutComponentTemplateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/template/put/TransportPutComposableIndexTemplateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/template/put/TransportPutIndexTemplateAction.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/cluster/metadata/Template.java
  server/src/main/java/org/opensearch/index/mapper/MappingTransformer.java
  server/src/main/java/org/opensearch/index/mapper/MappingTransformerRegistry.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/MapperPlugin.java
  server/src/test/java/org/opensearch/action/admin/indices/create/TransportCreateIndexActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/mapping/put/TransportPutMappingActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/template/put/TransportPutComponentTemplateActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/template/put/TransportPutComposableIndexTemplateActionTests.java
  server/src/test/java/org/opensearch/action/admin/indices/template/put/TransportPutIndexTemplateActionTests.java
  server/src/test/java/org/opensearch/index/mapper/MappingTransformerRegistryTests.java
  server/src/test/java/org/opensearch/indices/cluster/ClusterStateChanges.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
Labels: enhancement, Plugins, Cluster Manager

#17774 Increase default maxMergeAtOnce from 10 to 30
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/index/ClusterMaxMergesAtOnceIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/TieredMergePolicyProvider.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
Labels: enhancement, Indexing:Performance

#17938 add metric of skipped messages in pull-based ingestion processing
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java
  plugins/ingestion-kinesis/src/internalClusterTest/java/org/opensearch/plugin/kinesis/IngestFromKinesisIT.java
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
  server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java
  server/src/main/java/org/opensearch/indices/pollingingest/PollingIngestStats.java
  server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
  server/src/test/java/org/opensearch/indices/pollingingest/MessageProcessorTests.java
  server/src/test/java/org/opensearch/indices/pollingingest/PollingIngestStatsTests.java
Labels: skip-changelog

#17968 Closing the directory reader to fix test
  server/src/test/java/org/opensearch/search/aggregations/startree/RangeAggregatorTests.java
Labels: skip-changelog

#17969 Fix flaky test SegmentReplicationTargetServiceTests.testStartReplicationListenerSuccess
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/index/shard/SegmentReplicationIndexShardTests.java
Labels: skip-changelog

#17976 Use test-retry plugin in place of develocity
  build.gradle
  gradle.properties
  settings.gradle
Labels: skip-changelog

#17973 Additional settings for gRPC experimental transport.
  plugins/transport-grpc/README.md
  plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/GrpcPlugin.java
  plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/Netty4GrpcServerTransport.java
  plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/GrpcPluginTests.java
Labels: enhancement, Clients, skip-changelog

#17954 Intercept java.net.Socket::connect
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/Agent.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/SocketChannelInterceptorTests.java
  modules/repository-url/src/test/resources/org/opensearch/bootstrap/test.policy
  plugins/discovery-ec2/src/test/resources/org/opensearch/bootstrap/test.policy
  plugins/repository-s3/src/test/resources/org/opensearch/bootstrap/test.policy
Labels: skip-changelog

#17912 [Pull-based ingestion] Support multi-threaded writes in pull based ingestion
  CHANGELOG.md
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/KafkaIngestionBaseIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/engine/IngestionEngine.java
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
  server/src/main/java/org/opensearch/indices/pollingingest/IngestionUtils.java
  server/src/main/java/org/opensearch/indices/pollingingest/MessageProcessorRunnable.java
  server/src/main/java/org/opensearch/indices/pollingingest/PartitionedBlockingQueueContainer.java
  server/src/main/java/org/opensearch/indices/pollingingest/ShardUpdateMessage.java
  server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java
  server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
  server/src/test/java/org/opensearch/indices/pollingingest/MessageProcessorTests.java
  server/src/test/java/org/opensearch/indices/pollingingest/PartitionedBlockingQueueContainerTests.java
Labels: enhancement, Indexing

#17995 [Pull-based Ingesiton] Pass the maxPoll, timeout from config to poller
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
  server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
Labels: skip-changelog

#18005 Resolve compile error in DefaultStreamPoller
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
Labels: skip-changelog

#17996 Use 'FIXED' path type in DedicatedClusterSnapshotRestoreIT
  server/src/internalClusterTest/java/org/opensearch/snapshots/DedicatedClusterSnapshotRestoreIT.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#18008 Fix flaky ReactorNetty4StreamingStressIT
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#18012 Update my affiliation
  MAINTAINERS.md
Labels: skip-changelog

#17951 Add Unwrapfunction to all the fieldType instaceof check
  CHANGELOG.md
  modules/lang-expression/src/main/java/org/opensearch/script/expression/ExpressionScriptEngine.java
  modules/mapper-extras/src/main/java/org/opensearch/index/query/RankFeatureQueryBuilder.java
  modules/percolator/src/main/java/org/opensearch/percolator/PercolateQueryBuilder.java
  server/src/internalClusterTest/java/org/opensearch/index/mapper/StarTreeMapperIT.java
  server/src/main/java/org/opensearch/action/admin/indices/analyze/TransportAnalyzeAction.java
  server/src/main/java/org/opensearch/index/codec/PerFieldMappingPostingFormatCodec.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/StarTreeValidator.java
  server/src/main/java/org/opensearch/index/compositeindex/datacube/startree/builder/StarTreesBuilder.java
  server/src/main/java/org/opensearch/index/mapper/DefaultDerivedFieldResolver.java
  server/src/main/java/org/opensearch/index/mapper/DerivedFieldType.java
  server/src/main/java/org/opensearch/index/mapper/MapperService.java
  server/src/main/java/org/opensearch/index/mapper/MappingLookup.java
  server/src/main/java/org/opensearch/index/query/GeoPolygonQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/PrefixQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/QueryShardContext.java
  server/src/main/java/org/opensearch/index/query/TermQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/TermsQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/VectorGeoPointShapeQueryProcessor.java
  server/src/main/java/org/opensearch/index/query/WildcardQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/functionscore/DecayFunctionBuilder.java
  server/src/main/java/org/opensearch/index/search/MatchQuery.java
  server/src/main/java/org/opensearch/index/search/QueryStringQueryParser.java
  server/src/main/java/org/opensearch/index/termvectors/TermVectorsService.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/BinaryValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/GlobalOrdinalValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/LongValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/composite/UnsignedLongValuesSource.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/CompositeAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/filterrewrite/DateHistogramAggregatorBridge.java
  server/src/main/java/org/opensearch/search/aggregations/support/CoreValuesSourceType.java
  server/src/main/java/org/opensearch/search/aggregations/support/ValuesSourceConfig.java
  server/src/main/java/org/opensearch/search/collapse/CollapseBuilder.java
  server/src/main/java/org/opensearch/search/collapse/CollapseContext.java
  server/src/main/java/org/opensearch/search/sort/FieldSortBuilder.java
  server/src/main/java/org/opensearch/search/suggest/completion/CompletionSuggestionBuilder.java
  server/src/main/java/org/opensearch/search/suggest/completion/context/GeoContextMapping.java
  server/src/test/java/org/opensearch/index/mapper/FieldAliasMapperTests.java
  server/src/test/java/org/opensearch/index/query/GeoBoundingBoxQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/GeoDistanceQueryBuilderTests.java
  server/src/test/java/org/opensearch/index/query/RangeQueryBuilderTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/composite/BaseCompositeAggregatorTestCase.java
Labels: enhancement, _No response_

#17953 Visit the subquery builder recursively
  server/src/main/java/org/opensearch/index/query/ConstantScoreQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/DisMaxQueryBuilder.java
  server/src/main/java/org/opensearch/index/query/functionscore/FunctionScoreQueryBuilder.java
Labels: backport 2.x, skip-changelog

#17532 fix simultaneously creating a snapshot and updating the repository can potentially trigger an infinite loop
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
  server/src/main/java/org/opensearch/repositories/blobstore/BlobStoreRepository.java
Labels: bug, Storage:Snapshots

#17682 Unset discovery nodes for every transport node actions request
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/cluster/node/hotthreads/NodesHotThreadsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/reload/NodesReloadSecureSettingsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/usage/NodesUsageRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportNodesSnapshotsStatus.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/wlm/WlmStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/find/FindDanglingIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/list/ListDanglingIndicesRequest.java
  server/src/main/java/org/opensearch/action/search/GetAllPitNodesRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShardsBatch.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesActionTests.java
Labels: enhancement, >breaking, v3.0.0, Cluster Manager

#18013 Fix flaky multimatchquerybuildertests
  server/src/test/java/org/opensearch/index/query/MultiMatchQueryBuilderTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#18024 Increase default http.max_header_size to `16kb`
  CHANGELOG.md
  server/src/main/java/org/opensearch/http/HttpTransportSettings.java
Labels: enhancement, Other

#18030 Ignore 3.0 branch for breaking changes check
  .github/workflows/detect-breaking-change.yml
Labels: skip-changelog

#17894 Limit stack walking in the java agent to frames before the call to AccessController.doPrivileged
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SocketChannelInterceptor.java
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerProtectionDomainChainExtractor.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/StackCallerProtectionDomainExtractorTests.java
Labels: skip-changelog

#18029 [Backport 3.0] Limit stack walking to frames before AccessController.doPrivileged
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SocketChannelInterceptor.java
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerProtectionDomainChainExtractor.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/StackCallerProtectionDomainExtractorTests.java
Labels: skip-changelog

#18034 Update JavaVersionChecker to enforce min of JDK21
  distribution/tools/java-version-checker/src/main/java/org/opensearch/tools/java_version_checker/JavaVersionChecker.java
Labels: skip-changelog, backport 3.0

#18040 Increase Kafka topic polling time in test to 10 seconds
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaUtils.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#18039 Bump OpenSearch Core main branch to 3.0.0 and update key id for native plugin checks
  .github/workflows/benchmark-pull-request.yml
  .github/workflows/publish-maven-snapshots.yml
  CHANGELOG.md
  distribution/tools/plugin-cli/src/main/java/org/opensearch/tools/cli/plugin/InstallPluginCommand.java
Labels: enhancement, release, v3.0.0, skip-changelog, backport 3.0

#18041 Update bundled JDK to 21.0.7+6 (April 2025 Patch releases)
  buildSrc/src/main/java/org/opensearch/gradle/test/DistroTestPlugin.java
  gradle/libs.versions.toml
Labels: skip-changelog, Build, backport 3.0

#18047 [Backport 3.0] Unset discovery nodes for every transport node actions request (#17682)
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/admin/cluster/node/hotthreads/NodesHotThreadsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/info/NodesInfoRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/reload/NodesReloadSecureSettingsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodesStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/node/usage/NodesUsageRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/snapshots/status/TransportNodesSnapshotsStatus.java
  server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/cluster/wlm/WlmStatsRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/find/FindDanglingIndexRequest.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/list/ListDanglingIndicesRequest.java
  server/src/main/java/org/opensearch/action/search/GetAllPitNodesRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/BaseNodesRequest.java
  server/src/main/java/org/opensearch/action/support/nodes/TransportNodesAction.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayMetaState.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShards.java
  server/src/main/java/org/opensearch/gateway/TransportNodesListGatewayStartedShardsBatch.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadata.java
  server/src/main/java/org/opensearch/indices/store/TransportNodesListShardStoreMetadataBatch.java
  server/src/test/java/org/opensearch/action/support/nodes/TransportNodesActionTests.java
Labels: enhancement, >breaking, v3.0.0, Cluster Manager

#18044 [Backport 3.0] Bump OpenSearch Core main branch to 3.0.0 and update key id for native plugin checks
  .github/workflows/benchmark-pull-request.yml
  .github/workflows/publish-maven-snapshots.yml
  distribution/tools/plugin-cli/src/main/java/org/opensearch/tools/cli/plugin/InstallPluginCommand.java
Labels: release, v3.0.0, skip-changelog

#18003 Fix ingest pipeline cannot be executed when retry the failed index requests for update_by_query and reindex
  CHANGELOG.md
  modules/reindex/src/main/java/org/opensearch/index/reindex/AbstractAsyncBulkByScrollAction.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/Reindexer.java
  modules/reindex/src/main/java/org/opensearch/index/reindex/TransportUpdateByQueryAction.java
  server/src/main/java/org/opensearch/action/bulk/BulkItemResponse.java
  server/src/main/java/org/opensearch/action/bulk/Retry.java
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
  server/src/test/java/org/opensearch/action/bulk/BulkItemResponseTests.java
  server/src/test/java/org/opensearch/action/bulk/BulkRequestModifierTests.java
  server/src/test/java/org/opensearch/action/bulk/RetryTests.java
Labels: bug, Indexing, ingest-pipeline

#18058 Set Java version to 21 for use in bwc tests
  .ci/java-versions.properties
Labels: skip-changelog

#18027 Add remote to local pool change handling in TargetPoolAllocationDecider
  server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java
  server/src/main/java/org/opensearch/cluster/routing/OperationRouting.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDecider.java
  server/src/test/java/org/opensearch/cluster/routing/OperationRoutingTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/ShardsTieringAllocationTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/TieringAllocationBaseTestCase.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/TargetPoolAllocationDeciderTests.java
Labels: skip-changelog

#18017 Skip approximation when `track_total_hits` is set to `true`
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/approximate/ApproximateMatchAllQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/test/java/org/opensearch/search/approximate/ApproximateMatchAllQueryTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: v3.0.0, Search:Performance

#17978 Enable concurrent_segment_search auto mode by default
  CHANGELOG.md
  modules/aggs-matrix-stats/src/yamlRestTest/resources/rest-api-spec/test/stats/30_single_value_field.yml
  modules/aggs-matrix-stats/src/yamlRestTest/resources/rest-api-spec/test/stats/40_multi_value_field.yml
  server/src/internalClusterTest/java/org/opensearch/indices/memory/breaker/CircuitBreakerServiceIT.java
  server/src/internalClusterTest/java/org/opensearch/search/stats/ConcurrentSearchStatsIT.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/search/DefaultSearchContext.java
  server/src/main/java/org/opensearch/search/SearchService.java
  server/src/test/java/org/opensearch/search/internal/ContextIndexSearcherTests.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchIntegTestCase.java
  test/framework/src/main/java/org/opensearch/test/OpenSearchSingleNodeTestCase.java
Labels: enhancement, Search:Performance

#18057 Mute ClusterMaxMergesAtOnceIT
  server/src/internalClusterTest/java/org/opensearch/index/ClusterMaxMergesAtOnceIT.java
Labels: flaky-test, skip-changelog, backport 3.0

#18072 Fix race condition in SearchOnlyReplicaIT
  server/src/internalClusterTest/java/org/opensearch/indices/settings/SearchOnlyReplicaIT.java
Labels: skip-changelog

#17711 Enabled default throttling for all tasks submitted to cluster manager
  CHANGELOG.md
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/WorkloadGroupPersistenceService.java
  server/src/main/java/org/opensearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/storedscripts/TransportDeleteStoredScriptAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/storedscripts/TransportPutStoredScriptAction.java
  server/src/main/java/org/opensearch/action/admin/indices/create/AutoCreateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/delete/TransportDeleteDanglingIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/datastream/DeleteDataStreamAction.java
  server/src/main/java/org/opensearch/action/admin/indices/rollover/TransportRolloverAction.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateDataStreamService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataDeleteIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexAliasesService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataMappingService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerTask.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskKeys.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskThrottler.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/persistent/PersistentTasksClusterService.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java
Labels: enhancement, v3.0.0, Cluster Manager

#17942 Update to Gradle 8.14
  buildSrc/src/main/groovy/org/opensearch/gradle/test/StandaloneRestTestPlugin.groovy
  buildSrc/src/main/java/org/opensearch/gradle/precommit/TestingConventionsTasks.java
  buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestApiTask.java
  buildSrc/src/main/java/org/opensearch/gradle/test/rest/CopyRestTestsTask.java
  buildSrc/src/main/java/org/opensearch/gradle/util/GradleUtils.java
  gradle/wrapper/gradle-wrapper.properties
Labels: skip-changelog, Build, backport 3.0

#18043 Bump main branch to be version 3.1.0
  .ci/bwcVersions
  .ci/java-versions.properties
  buildSrc/version.properties
  gradle/libs.versions.toml
  libs/core/src/main/java/org/opensearch/Version.java
Labels: release, skip-changelog, v3.1.0

#18067 Fix testAddReplicaWhileWritesBlocked test under SegmentReplicationWithRemoteStorePressureIT
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationBaseIT.java
Labels: skip-changelog

#17941 [Star Tree] Support of Boolean Queries in Aggregations
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/startree/filter/DimensionFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/DimensionFilterMergerUtils.java
  server/src/main/java/org/opensearch/search/startree/filter/ExactMatchDimFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/MatchNoneFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/RangeMatchDimFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/BoolStarTreeFilterProvider.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/DimensionFilterMapper.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/StarTreeFilterProvider.java
  server/src/test/java/org/opensearch/search/aggregations/startree/BoolStarTreeFilterProviderTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DimensionFilterAndMapperTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DimensionFilterMergerUtilsTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/MetricAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/StarTreeFilterTests.java
Labels: enhancement, Search:Aggregations

#18094 [Backport 3.0] Enabled default throttling for all tasks submitted to cluster manager (#17711)
  CHANGELOG.md
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/service/WorkloadGroupPersistenceService.java
  server/src/main/java/org/opensearch/action/admin/cluster/reroute/TransportClusterRerouteAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/storedscripts/TransportDeleteStoredScriptAction.java
  server/src/main/java/org/opensearch/action/admin/cluster/storedscripts/TransportPutStoredScriptAction.java
  server/src/main/java/org/opensearch/action/admin/indices/create/AutoCreateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/dangling/delete/TransportDeleteDanglingIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/datastream/DeleteDataStreamAction.java
  server/src/main/java/org/opensearch/action/admin/indices/rollover/TransportRolloverAction.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateDataStreamService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataDeleteIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexAliasesService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataMappingService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerService.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerTask.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskKeys.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerTaskThrottler.java
  server/src/main/java/org/opensearch/cluster/service/ClusterService.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/persistent/PersistentTasksClusterService.java
  server/src/main/java/org/opensearch/repositories/RepositoriesService.java
  server/src/main/java/org/opensearch/search/pipeline/SearchPipelineService.java
  server/src/main/java/org/opensearch/snapshots/RestoreService.java
  server/src/main/java/org/opensearch/snapshots/SnapshotsService.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerServiceTests.java
  server/src/test/java/org/opensearch/cluster/service/ClusterManagerTaskThrottlerTests.java
Labels: enhancement, v3.0.0, Cluster Manager

#18087 [Backport 3.0] Skip approximation when `track_total_hits` is set to `true`
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/approximate/ApproximateMatchAllQuery.java
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/test/java/org/opensearch/search/approximate/ApproximateMatchAllQueryTests.java
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: v3.0.0

#17927 Create thread id to SourceLookup map
  server/src/main/java/org/opensearch/search/lookup/SearchLookup.java
  server/src/test/java/org/opensearch/script/ScriptServiceTests.java
Labels: v3.0.0, skip-changelog

#18059 [Bug-fix] Fix redundant loading of global ordinals
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
Labels: bug, Search:Aggregations, v3.0.0, skip-changelog, backport 3.0

#18114 Add shared memory access
  distribution/packages/src/common/systemd/opensearch.service
Labels: backport main, skip-changelog

#18109 Mute RepositoriesServiceIT.testCreatSnapAndUpdateReposityCauseInfiniteLoop
  server/src/internalClusterTest/java/org/opensearch/repositories/RepositoriesServiceIT.java
Labels: skip-changelog

#18120 Fix release notes title
  release-notes/opensearch.release-notes-3.0.0.md
Labels: skip-changelog

#18123 Remove testSystemCallFilter temporarily
  qa/systemd-test/src/test/java/org/opensearch/systemdinteg/SystemdIntegTests.java
Labels: backport main, skip-changelog

#18135 Fix systemd configs in main
  distribution/packages/src/common/systemd/opensearch.service
Labels: bug, skip-changelog, Other

#18140 Updated 3.0 release note related to #17682
  release-notes/opensearch.release-notes-3.0.0.md
Labels: skip-changelog, backport 3.0

#18116 Revert "Avoid invalid retries on multiple replicas when querying"
  CHANGELOG.md
  libs/core/src/main/java/org/opensearch/OpenSearchException.java
  server/src/main/java/org/opensearch/action/search/AbstractSearchAsyncAction.java
  server/src/main/java/org/opensearch/action/support/TransportActions.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
Labels: >test-failure, flaky-test, autocut, Cluster Manager, Indexing:Replication

#18144 Gracefully tear down S3BlobContainerRetriesTests
  plugins/repository-s3/src/test/java/org/opensearch/repositories/s3/S3BlobContainerRetriesTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#18099 Fix flaky TransportMultiSearchActionTests.testCancellation
  server/src/test/java/org/opensearch/action/search/TransportMultiSearchActionTests.java
Labels: skip-changelog

#18060 Remove test fixture old-elasticsearch
  .github/dependabot.yml
  gradle/missing-javadoc.gradle
  settings.gradle
  test/fixtures/old-elasticsearch/build.gradle
  test/fixtures/old-elasticsearch/src/main/java/oldes/OldElasticsearch.java
Labels: skip-changelog

#18148 Add syscalls for merge operation error
  distribution/packages/src/common/systemd/opensearch.service
Labels: release, backport main, v3.0.0, skip-changelog

#18147 Fix the native plugin installation error
  CHANGELOG.md
  distribution/tools/plugin-cli/src/main/java/org/opensearch/tools/cli/plugin/InstallPluginCommand.java
  distribution/tools/plugin-cli/src/main/resources/public_key.sig
Labels: v3.0.0, backport 3.0

#18145 Fix assertion in RemoteStatePublicationIT
  server/src/internalClusterTest/java/org/opensearch/gateway/remote/RemoteStatePublicationIT.java
Labels: skip-changelog

#18152 Update Apache HttpClient5 and HttpCore5 (CVE-2025-27820)
  CHANGELOG.md
  client/rest/licenses/httpclient5-5.4.1.jar.sha1
  client/rest/licenses/httpclient5-5.4.4.jar.sha1
  client/rest/licenses/httpcore5-5.3.2.jar.sha1
  client/rest/licenses/httpcore5-5.3.4.jar.sha1
  client/rest/licenses/httpcore5-h2-5.3.2.jar.sha1
  client/rest/licenses/httpcore5-h2-5.3.4.jar.sha1
  client/rest/licenses/httpcore5-reactive-5.3.2.jar.sha1
  client/rest/licenses/httpcore5-reactive-5.3.4.jar.sha1
  client/rest/src/test/java/org/opensearch/client/RestClientSingleHostIntegTests.java
  client/sniffer/licenses/httpclient5-5.4.1.jar.sha1
  client/sniffer/licenses/httpclient5-5.4.4.jar.sha1
  client/sniffer/licenses/httpcore5-5.3.2.jar.sha1
  client/sniffer/licenses/httpcore5-5.3.4.jar.sha1
  gradle/libs.versions.toml
Labels: security, backport 2.19, backport 3.0

#18153 [Backport 3.0] Fix the native plugin installation error
  CHANGELOG.md
  distribution/tools/plugin-cli/src/main/java/org/opensearch/tools/cli/plugin/InstallPluginCommand.java
  distribution/tools/plugin-cli/src/main/resources/public_key.sig
Labels: v3.0.0

#18111 Define code ownership with maintainers team instead of individual maintainers
  .github/CODEOWNERS
  .github/workflows/maintainer-approval.yml
Labels: >FORK, Rename, skip-changelog

#18139 Enabled Async Shard Batch Fetch by default
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/indices/recovery/IndexRecoveryIT.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/ExistingShardsAllocator.java
  server/src/main/java/org/opensearch/gateway/ShardsBatchGatewayAllocator.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/AllocationServiceTests.java
  server/src/test/java/org/opensearch/index/SearchSlowLogTests.java
Labels: enhancement, v3.0.0, Cluster Manager, backport 3.0

#18165 Add Seccomp and Reboot call tests
  qa/systemd-test/src/test/java/org/opensearch/systemdinteg/SystemdIntegTests.java
Labels: release, skip-changelog, v3.1.0

#18156 Add support for linux riscv64 platform
  CHANGELOG.md
  buildSrc/src/main/java/org/opensearch/gradle/Architecture.java
  buildSrc/src/main/java/org/opensearch/gradle/DistributionDownloadPlugin.java
  buildSrc/src/main/java/org/opensearch/gradle/JavaVariant.java
  buildSrc/src/main/java/org/opensearch/gradle/VersionProperties.java
  buildSrc/src/main/java/org/opensearch/gradle/internal/InternalDistributionBwcSetupPlugin.java
  buildSrc/src/test/java/org/opensearch/gradle/ArchitectureTests.java
  buildSrc/src/test/java/org/opensearch/gradle/JdkDownloadPluginTests.java
  distribution/archives/build.gradle
  distribution/archives/linux-riscv64-tar/build.gradle
  distribution/archives/no-jdk-linux-riscv64-tar/build.gradle
  distribution/build.gradle
  distribution/docker/build.gradle
  distribution/docker/docker-riscv64-export/build.gradle
  server/src/main/java/org/opensearch/bootstrap/SystemCallFilter.java
  settings.gradle
Labels: enhancement, Build Libraries & Interfaces
