Repository opensearch-project/OpenSearch, pull requests merged in 2025-02, with the labels that each got.

#17239 Fix date hardcoding in date aggregator
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
Labels: bug, Search:Aggregations, backport 2.x, skip-changelog, v2.19.0, backport 2.19

#17093 Updated the validation for search only replica settings
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
Labels: enhancement, skip-changelog, Search:Performance

#17248 Add HTTP/2 protocol support to HttpRequest.HttpVersion
  CHANGELOG-3.0.md
  modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpRequest.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpRequest.java
  server/src/main/java/org/opensearch/http/HttpRequest.java
Labels: v3.0.0

#17249 Remove master term from AckedRequest
  server/src/main/java/org/opensearch/action/admin/indices/alias/TransportIndicesAliasesAction.java
  server/src/main/java/org/opensearch/action/admin/indices/close/TransportCloseIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/create/AutoCreateAction.java
  server/src/main/java/org/opensearch/action/admin/indices/create/TransportCreateIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/delete/TransportDeleteIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/mapping/put/TransportPutMappingAction.java
  server/src/main/java/org/opensearch/action/admin/indices/open/TransportOpenIndexAction.java
  server/src/main/java/org/opensearch/action/admin/indices/readonly/TransportAddIndexBlockAction.java
  server/src/main/java/org/opensearch/action/admin/indices/rollover/MetadataRolloverService.java
  server/src/main/java/org/opensearch/action/admin/indices/settings/put/TransportUpdateSettingsAction.java
  server/src/main/java/org/opensearch/action/admin/indices/shrink/TransportResizeAction.java
  server/src/main/java/org/opensearch/action/admin/indices/upgrade/post/TransportUpgradeSettingsAction.java
  server/src/main/java/org/opensearch/cluster/AckedClusterStateUpdateTask.java
  server/src/main/java/org/opensearch/cluster/ack/AckedRequest.java
  server/src/main/java/org/opensearch/cluster/ack/ClusterStateUpdateRequest.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateDataStreamService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexStateService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataMappingService.java
Labels: skip-changelog

#17260 Add Gradle registries for dependabot
  .github/dependabot.yml
Labels: backport 2.x, skip-changelog

#16021 Fix Flaky Test SpecificClusterManagerNodesIT.testElectOnlyBetweenClusterManagerNodes
  server/src/internalClusterTest/java/org/opensearch/cluster/SpecificClusterManagerNodesIT.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: bug, >test-failure, flaky-test, backport 2.x, autocut, skip-changelog, Cluster Manager

#17233 Convert transport-reactor-netty4 to use gradle version catalog
  CHANGELOG.md
  gradle/libs.versions.toml
  plugins/transport-reactor-netty4/build.gradle
  server/build.gradle
Labels: backport 2.x

#17240 [Pull-based Ingestion] Fix snappy related Kafka errors and relax thread leak checks
  plugins/ingestion-kafka/build.gradle
  plugins/ingestion-kafka/licenses/snappy-java-1.1.10.7.jar.sha1
  plugins/ingestion-kafka/licenses/snappy-java-LICENSE.txt
  plugins/ingestion-kafka/licenses/snappy-java-NOTICE.txt
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/TestContainerWatchdogThreadLeakFilter.java
  plugins/ingestion-kafka/src/main/plugin-metadata/plugin-security.policy
Labels: >test-failure, flaky-test, autocut

#17252 Prevent unnecessary heap sort when buckets needs to be ordered by key…
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregator.java
Labels: backport, backport 2.x

#17160 Add HashSet based filtering optimization to XContentMapValues
  CHANGELOG-3.0.md
  server/src/main/java/org/opensearch/common/xcontent/support/XContentMapValues.java
Labels: bug, good first issue, v3.0.0

#17268 Remove MinimizationOperations
  CHANGELOG-3.0.md
  modules/reindex/src/main/java/org/opensearch/index/reindex/ReindexValidator.java
  server/src/main/java/org/opensearch/common/lucene/search/AutomatonQueries.java
  server/src/main/java/org/opensearch/index/mapper/KeywordFieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/TextFieldMapper.java
  server/src/main/java/org/opensearch/indices/SystemIndices.java
  server/src/main/java/org/opensearch/lucene/util/automaton/MinimizationOperations.java
  server/src/main/java/org/opensearch/lucene/util/automaton/package-info.java
  server/src/test/java/org/opensearch/index/mapper/FlatObjectFieldTypeTests.java
  server/src/test/java/org/opensearch/index/mapper/KeywordFieldTypeTests.java
Labels: bug, Search:Resiliency

#17325 Remove priviledged thread factory (fix integrated into latest Netty 4.1.118.Final)
  modules/transport-netty4/src/main/java/org/opensearch/transport/SharedGroupFactory.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/transport/reactor/SharedGroupFactory.java
  server/src/main/java/org/opensearch/common/util/concurrent/OpenSearchExecutors.java
Labels: backport 2.x, skip-changelog, backport 2.19

#17317 [FORWARDPORT main] Release notes 2.19 on main
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.19.0.md
Labels: skip-changelog

#17346 [Backport] [2.x] Bump reactor_netty from 1.1.26 to 1.1.27 (#17322)
  CHANGELOG.md
  gradle/libs.versions.toml
  plugins/repository-azure/licenses/reactor-netty-core-1.1.23.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-core-1.1.27.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.23.jar.sha1
  plugins/repository-azure/licenses/reactor-netty-http-1.1.27.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.23.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-core-1.1.27.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.23.jar.sha1
  plugins/transport-reactor-netty4/licenses/reactor-netty-http-1.1.27.jar.sha1
Labels: backport 2.19.1

#17255 Making force merge threadpool 1/8th of total cores
  CHANGELOG.md
  server/src/main/java/org/opensearch/threadpool/ThreadPool.java
  server/src/test/java/org/opensearch/threadpool/ThreadPoolTests.java
Labels: backport 2.x

#17021 [Remote Store] Using RemoteDirectory#delete to clear all segments during migration
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/main/java/org/opensearch/common/blobstore/fs/FsBlobContainer.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
Labels: skip-changelog

#17360 [Backport 2.x] Using RemoteDirectory#delete to clear all segments during migration (…
  server/src/internalClusterTest/java/org/opensearch/remotemigration/RemotePrimaryRelocationIT.java
  server/src/main/java/org/opensearch/common/blobstore/fs/FsBlobContainer.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
Labels: skip-changelog

#17357 Remove deprecated settings to defer cluster recovery
  CHANGELOG-3.0.md
  distribution/src/config/opensearch.yml
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/stats/ClusterStatsIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/cluster/tasks/PendingTasksBlocksIT.java
  server/src/internalClusterTest/java/org/opensearch/action/admin/indices/exists/IndicesExistsIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoverAfterNodesIT.java
  server/src/internalClusterTest/java/org/opensearch/gateway/RecoveryFromGatewayIT.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/gateway/GatewayService.java
  server/src/test/java/org/opensearch/gateway/GatewayServiceTests.java
Labels: enhancement, deprecate, v3.0.0, Cluster Manager

#16781 [Bugfix] Fix IllegalArgumentException thrown when creating a PIT
  CHANGELOG.md
  server/src/main/java/org/opensearch/action/search/SearchPhase.java
  server/src/main/java/org/opensearch/action/search/SearchRequestStats.java
  server/src/test/java/org/opensearch/action/search/AbstractSearchAsyncActionTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestOperationsListenerTests.java
  server/src/test/java/org/opensearch/action/search/SearchRequestStatsTests.java
  server/src/test/java/org/opensearch/index/search/stats/SearchStatsTests.java
Labels: bug, v3.0.0, backport 2.x, Search, v2.19.0

#14580 Segment Replication stats throwing NPE when shards are unassigned or are in delayed allocation phase
  server/src/main/java/org/opensearch/index/seqno/ReplicationTracker.java
Labels: bug, good first issue, low hanging fruit, skip-changelog, Storage

#17349 Wildcard field use only 3-gram to index
  CHANGELOG-3.0.md
  qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/40_wildcard.yml
  qa/rolling-upgrade/src/test/resources/rest-api-spec/test/old_cluster/40_wildcard.yml
  qa/rolling-upgrade/src/test/resources/rest-api-spec/test/upgraded_cluster/40_wildcard.yml
  server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
  server/src/test/java/org/opensearch/index/mapper/WildcardFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/WildcardFieldTypeTests.java
Labels: enhancement, Search

#17384 Explicitly disable FeatureFlag in MetadataCreateIndexServiceTests.testCreateIndexWithContextDisabled
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#17312 Introduce `execution_hint` for Cardinality aggregation
  CHANGELOG-3.0.md
  server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregationBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorFactory.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorSupplier.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/CardinalityAggregatorTests.java
  test/framework/src/main/java/org/opensearch/search/aggregations/AggregatorTestCase.java
Labels: enhancement, good first issue, Search:Aggregations, Search:Performance

#17408 HTTP API calls hang with 'Accept-Encoding: zstd'
  CHANGELOG.md
  modules/transport-netty4/src/main/java/org/opensearch/http/netty4/Netty4HttpServerTransport.java
  modules/transport-netty4/src/test/java/org/opensearch/http/netty4/Netty4HttpServerTransportTests.java
Labels: bug, v3.0.0, backport 2.x, Other, v2.19.1

#17418 Fix missing bucket in terms aggregation with missing value
  CHANGELOG-3.0.md
  server/src/main/java/org/opensearch/search/aggregations/support/MissingValues.java
  server/src/test/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregatorTests.java
Labels: bug, Search:Aggregations, v3.0.0

#17430 Update Andriy Redko (https://github.com/reta) affiliation
  MAINTAINERS.md
Labels: backport 1.x, backport 2.x, backport 1.3, skip-changelog, backport 2.19

#17431 [Backport] [2.x] Update Andriy Redko (https://github.com/reta) affiliation (#17430)
  MAINTAINERS.md
Labels: skip-changelog

#17435 [Backport] [1.3] Update Andriy Redko (https://github.com/reta) affiliation (#17430) (#17431)
  MAINTAINERS.md
Labels: skip-changelog

#17342 [rule based autotagging] add attribute value store
  CHANGELOG.md
  plugins/workload-management/build.gradle
  plugins/workload-management/licenses/commons-collections-LICENSE.txt
  plugins/workload-management/licenses/commons-collections-NOTICE.txt
  plugins/workload-management/licenses/commons-collections4-4.4.jar.sha1
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/package-info.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/storage/AttributeValueStore.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/storage/DefaultAttributeValueStore.java
  plugins/workload-management/src/main/java/org/opensearch/plugin/wlm/rule/storage/package-info.java
  plugins/workload-management/src/test/java/org/opensearch/plugin/wlm/rule/storage/AttributeValueStoreTests.java
Labels: backport 2.x

#17354 [Pull-based Ingestion] Offset management, support rewind by offset or timestamp
  CHANGELOG-3.0.md
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java
  plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaPartitionConsumer.java
  plugins/ingestion-kafka/src/main/java/org/opensearch/plugin/kafka/KafkaSourceConfig.java
  plugins/ingestion-kafka/src/test/java/org/opensearch/plugin/kafka/KafkaPartitionConsumerTests.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/IngestionSource.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IngestionShardConsumer.java
  server/src/main/java/org/opensearch/index/engine/IngestionEngine.java
  server/src/main/java/org/opensearch/indices/pollingingest/DefaultStreamPoller.java
  server/src/main/java/org/opensearch/indices/pollingingest/StreamPoller.java
  server/src/test/java/org/opensearch/cluster/metadata/IngestionSourceTests.java
  server/src/test/java/org/opensearch/index/engine/FakeIngestionSource.java
  server/src/test/java/org/opensearch/indices/pollingingest/DefaultStreamPollerTests.java
Labels: enhancement, Indexing

#17295 Add new index and cluster level settings to limit the total primary shards per node and per index
  CHANGELOG-3.0.md
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/ShardsLimitAllocationDeciderIT.java
  server/src/internalClusterTest/java/org/opensearch/cluster/routing/allocation/decider/ShardsLimitAllocationDeciderRemoteStoreEnabledIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/settings/TransportClusterUpdateSettingsAction.java
  server/src/main/java/org/opensearch/cluster/metadata/IndexMetadata.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataCreateIndexService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataIndexTemplateService.java
  server/src/main/java/org/opensearch/cluster/metadata/MetadataUpdateSettingsService.java
  server/src/main/java/org/opensearch/cluster/routing/RoutingNode.java
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataCreateIndexServiceTests.java
  server/src/test/java/org/opensearch/cluster/metadata/MetadataIndexTemplateServiceTests.java
  server/src/test/java/org/opensearch/cluster/routing/RoutingNodeTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/ShardsLimitAllocationDeciderTests.java
Labels: enhancement, _No response_

#17450 Updated affiliation for @dblock.
  MAINTAINERS.md
Labels: backport 2.x, skip-changelog

#17440 Correct the isStored flag for wildcard field type
  server/src/main/java/org/opensearch/index/mapper/WildcardFieldMapper.java
Labels: v3.0.0, skip-changelog

#17429 Fix flaky tests from`SegmentReplicationAllocationIT`
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationAllocationIT.java
Labels: good first issue, >test-failure, flaky-test, autocut, skip-changelog, Storage, Storage:Remote

#17028 Fix ConcurrentModificationException in RemoteFsTimestampAwareTranslog.trimUnreferencedReaders
  server/src/main/java/org/opensearch/index/translog/RemoteFsTimestampAwareTranslog.java
Labels: skip-changelog

#17055 Implemented computation of segment replication stats at shard level
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/index/shard/IndexShardIT.java
  server/src/internalClusterTest/java/org/opensearch/indices/replication/SegmentReplicationStatsIT.java
  server/src/main/java/org/opensearch/common/io/IndexIOStreamHandlerFactory.java
  server/src/main/java/org/opensearch/common/io/VersionedCodecStreamWrapper.java
  server/src/main/java/org/opensearch/index/IndexModule.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/index/ReplicationStats.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/main/java/org/opensearch/index/store/RemoteSegmentStoreDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadata.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandler.java
  server/src/main/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerFactory.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
  server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadataHandlerFactory.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
  server/src/main/java/org/opensearch/indices/replication/RemoteStoreReplicationSource.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTarget.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicationTargetService.java
  server/src/main/java/org/opensearch/indices/replication/SegmentReplicator.java
  server/src/main/java/org/opensearch/indices/replication/checkpoint/ReplicationCheckpoint.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/common/io/VersionedCodecStreamWrapperTests.java
  server/src/test/java/org/opensearch/index/IndexModuleTests.java
  server/src/test/java/org/opensearch/index/seqno/ReplicationTrackerTests.java
  server/src/test/java/org/opensearch/index/store/RemoteSegmentStoreDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerFactoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/metadata/RemoteSegmentMetadataHandlerTests.java
  server/src/test/java/org/opensearch/index/translog/transfer/TranslogTransferMetadataHandlerFactoryTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetServiceTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicationTargetTests.java
  server/src/test/java/org/opensearch/indices/replication/SegmentReplicatorTests.java
  server/src/test/java/org/opensearch/indices/replication/common/CopyStateTests.java
  test/framework/src/main/java/org/opensearch/index/shard/IndexShardTestCase.java
Labels: enhancement, backport 2.x, Search:Performance

#17359 [Pull-based Ingestion] Support segment replication for pull-based ingestion
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/IngestFromKafkaIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/KafkaIngestionBaseIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/RemoteStoreKafkaIT.java
  plugins/ingestion-kafka/src/internalClusterTest/java/org/opensearch/plugin/kafka/TestContainerThreadLeakFilter.java
  server/src/main/java/org/opensearch/index/engine/IngestionEngine.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/translog/InternalTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/NoOpTranslogManager.java
  server/src/main/java/org/opensearch/index/translog/Translog.java
  server/src/main/java/org/opensearch/index/translog/TranslogManager.java
  server/src/main/java/org/opensearch/indices/pollingingest/IngestionEngineFactory.java
  server/src/test/java/org/opensearch/index/engine/IngestionEngineTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: enhancement, skip-changelog, Indexing

#17190 Move TSC took-time policy to guard both heap and disk tier
  CHANGELOG.md
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheIT.java
  modules/cache-common/src/internalClusterTest/java/org/opensearch/cache/common/tier/TieredSpilloverCacheStatsIT.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/policy/TookTimePolicy.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCache.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCachePlugin.java
  modules/cache-common/src/main/java/org/opensearch/cache/common/tier/TieredSpilloverCacheSettings.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/policy/TookTimePolicyTests.java
  modules/cache-common/src/test/java/org/opensearch/cache/common/tier/TieredSpilloverCacheTests.java
Labels: enhancement, backport, RFC, backport 2.x, Search:Performance

#17476 Refresh benchmark configs to use 3.0.0-alpha1 version
  .github/benchmark-configs.json
  .github/workflows/benchmark-pull-request.yml
Labels: skip-changelog

#17477 Add 2.19.1 release notes (#17468)
  CHANGELOG.md
  release-notes/opensearch.release-notes-2.19.1.md
Labels: skip-changelog

#17481 add alpha1 qualifier to assemble command in benchmark workflow
  .github/workflows/benchmark-pull-request.yml
Labels: skip-changelog

#17466 Add @bugmakerrrrrr as maintainerrrrrr
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: skip-changelog
