Repository opensearch-project/OpenSearch, pull requests merged in 2025-06, with the labels that each got.

#18408 An attempt to fix flaky ReactorNetty4StreamingStressIT (new failure mode)
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#17780 Added time_in_execution attribute to /_cluster/pending_tasks response
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/service/ClusterServiceIT.java
  server/src/main/java/org/opensearch/action/admin/cluster/tasks/PendingClusterTasksResponse.java
  server/src/main/java/org/opensearch/cluster/service/ClusterManagerService.java
  server/src/main/java/org/opensearch/cluster/service/PendingClusterTask.java
  server/src/main/java/org/opensearch/common/util/concurrent/PrioritizedOpenSearchThreadPoolExecutor.java
  server/src/test/java/org/opensearch/common/util/concurrent/PrioritizedExecutorsTests.java
Labels: enhancement, Cluster Manager

#18354 Support/fix for star-tree keyword aggregation dfs mode
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/TermsAggregator.java
  server/src/test/java/org/opensearch/search/aggregations/startree/KeywordTermsAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/NumericTermsAggregatorTests.java
Labels: skip-changelog

#18449 Add `nyc_taxis` search only test-procedure to test with Lucene 10.2.1
  .github/benchmark-configs.json
Labels: skip-changelog

#18442 Execute `:libs:opensearch-agent-sm:agent` tests in separate JVMs
  libs/agent-sm/agent/build.gradle
Labels: bug, skip-changelog, Build

#18453 Remove extra call to initializeFeatureFlags
  server/src/main/java/org/opensearch/node/Node.java
Labels: skip-changelog

#18452 Standardize setting key for aux transports
  plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/bootstrap/FlightService.java
  plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/bootstrap/FlightStreamPlugin.java
  plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/bootstrap/ServerComponents.java
  plugins/arrow-flight-rpc/src/test/java/org/opensearch/arrow/flight/FlightStreamPluginTests.java
  plugins/transport-grpc/src/internalClusterTest/java/org/opensearch/plugin/transport/grpc/GrpcTransportBaseIT.java
  plugins/transport-grpc/src/internalClusterTest/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransportIT.java
  plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/GrpcPlugin.java
  plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/Netty4GrpcServerTransport.java
  plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransport.java
  plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/GrpcPluginTests.java
  plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/ssl/SecureSettingsHelpers.java
  server/src/main/java/org/opensearch/bootstrap/Security.java
  server/src/main/java/org/opensearch/common/network/NetworkModule.java
  server/src/main/java/org/opensearch/common/settings/ClusterSettings.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/main/java/org/opensearch/plugins/NetworkPlugin.java
  server/src/main/java/org/opensearch/plugins/SecureAuxTransportSettingsProvider.java
  server/src/main/java/org/opensearch/transport/AuxTransport.java
Labels: skip-changelog

#18474 Set git attributes to union changes in the CHANGELOG to reduce merge conflicts
  .gitattributes
Labels: bug, skip-changelog, Build

#18456 Minor fixes in WarmDiskThresholdDecider
  server/src/main/java/org/opensearch/cluster/routing/allocation/decider/WarmDiskThresholdDecider.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/WarmDiskThresholdDeciderTests.java
Labels: skip-changelog

#18054 Adding integration of derived source feature across diff paths
  CHANGELOG.md
  modules/reindex/src/test/java/org/opensearch/index/reindex/ReindexBasicTests.java
  server/src/internalClusterTest/java/org/opensearch/get/GetActionIT.java
  server/src/internalClusterTest/java/org/opensearch/indexing/IndexActionIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RecoveryWhileUnderLoadIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RelocationIT.java
  server/src/internalClusterTest/java/org/opensearch/search/simple/SimpleSearchIT.java
  server/src/internalClusterTest/java/org/opensearch/update/UpdateIT.java
  server/src/main/java/org/opensearch/common/lucene/index/DerivedSourceDirectoryReader.java
  server/src/main/java/org/opensearch/common/lucene/index/DerivedSourceLeafReader.java
  server/src/main/java/org/opensearch/common/lucene/index/DerivedSourceStoredFieldsReader.java
  server/src/main/java/org/opensearch/common/settings/IndexScopedSettings.java
  server/src/main/java/org/opensearch/index/IndexSettings.java
  server/src/main/java/org/opensearch/index/engine/InternalEngine.java
  server/src/main/java/org/opensearch/index/engine/TranslogLeafReader.java
  server/src/main/java/org/opensearch/index/mapper/DocumentMapperParser.java
  server/src/main/java/org/opensearch/index/mapper/FieldMapper.java
  server/src/main/java/org/opensearch/index/mapper/Mapper.java
  server/src/main/java/org/opensearch/index/mapper/ObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/RootObjectMapper.java
  server/src/main/java/org/opensearch/index/mapper/SortedSetDocValuesFetcher.java
  server/src/main/java/org/opensearch/index/mapper/SourceFieldMapper.java
  server/src/main/java/org/opensearch/index/shard/IndexShard.java
  server/src/test/java/org/opensearch/common/lucene/index/DerivedSourceDirectoryReaderTests.java
  server/src/test/java/org/opensearch/common/lucene/index/DerivedSourceLeafReaderTests.java
  server/src/test/java/org/opensearch/common/lucene/index/DerivedSourceStoredFieldsReaderTests.java
  server/src/test/java/org/opensearch/index/IndexSettingsTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
  server/src/test/java/org/opensearch/index/engine/TranslogLeafReaderTests.java
  server/src/test/java/org/opensearch/index/mapper/DateFieldMapperTests.java
  server/src/test/java/org/opensearch/index/mapper/SourceFieldMapperTests.java
  test/framework/src/main/java/org/opensearch/index/engine/EngineTestCase.java
  test/framework/src/main/java/org/opensearch/test/BackgroundIndexer.java
Labels: enhancement, Indexing:Performance

#17855 [Star Tree] [Search] Support of Date Range Queries in Aggregations
  CHANGELOG.md
  server/src/main/java/org/opensearch/index/query/RangeQueryBuilder.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/histogram/DateHistogramAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/range/RangeAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/GlobalOrdinalsStringTermsAggregator.java
  server/src/main/java/org/opensearch/search/aggregations/bucket/terms/NumericTermsAggregator.java
  server/src/main/java/org/opensearch/search/startree/StarTreeTraversalUtil.java
  server/src/main/java/org/opensearch/search/startree/filter/DimensionFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/DimensionFilterMergerUtils.java
  server/src/main/java/org/opensearch/search/startree/filter/ExactMatchDimFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/MatchAllFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/MatchNoneFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/RangeMatchDimFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/StarTreeFilter.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/BoolStarTreeFilterProvider.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/DimensionFilterMapper.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/StarDateFieldMapper.java
  server/src/main/java/org/opensearch/search/startree/filter/provider/StarTreeFilterProvider.java
  server/src/test/java/org/opensearch/index/compositeindex/datacube/startree/fileformats/node/FixedLengthStarTreeNodeSearchTests.java
  server/src/test/java/org/opensearch/search/SearchServiceStarTreeTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/BoolStarTreeFilterProviderTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DateHistogramAggregatorTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DateRangeQueryTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DimensionFilterAndMapperTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/DimensionFilterMergerUtilsTests.java
  server/src/test/java/org/opensearch/search/aggregations/startree/RangeAggregatorTests.java
Labels: enhancement, Search:Aggregations

#18439 Approximation Framework Enhancement: Update the BKD traversal logic to improve the performance on skewed data
  CHANGELOG.md
  server/src/main/java/org/opensearch/search/approximate/ApproximatePointRangeQuery.java
  server/src/test/java/org/opensearch/search/approximate/ApproximatePointRangeQueryTests.java
Labels: v3.1.0

#18483 Bugfix arrow-flight-rpc plugin dependency injection collision
  plugins/arrow-flight-rpc/README.md
  plugins/arrow-flight-rpc/src/internalClusterTest/java/org/opensearch/arrow/flight/ArrowFlightServerIT.java
  plugins/arrow-flight-rpc/src/main/java/org/opensearch/arrow/flight/bootstrap/FlightStreamPlugin.java
  plugins/arrow-flight-rpc/src/test/java/org/opensearch/arrow/flight/FlightStreamPluginTests.java
Labels: skip-changelog

#18277 Support system ingest pipelines for bulk update operations
  CHANGELOG.md
  plugins/examples/mapping-transformer/src/yamlRestTest/resources/rest-api-spec/test/example-mapping-transformer/20_mapping_transformer.yml
  plugins/examples/system-ingest-processor/src/test/java/org/opensearch/example/systemingestprocessor/ExampleSystemIngestProcessorTests.java
  plugins/examples/system-ingest-processor/src/yamlRestTest/resources/rest-api-spec/test/example-system-ingest-processor/20_system_ingest_processor.yml
  server/src/main/java/org/opensearch/action/bulk/TransportBulkAction.java
  server/src/main/java/org/opensearch/action/update/UpdateRequest.java
  server/src/main/java/org/opensearch/ingest/AbstractBatchingSystemProcessor.java
  server/src/main/java/org/opensearch/ingest/CompoundProcessor.java
  server/src/main/java/org/opensearch/ingest/IndexRequestWrapper.java
  server/src/main/java/org/opensearch/ingest/IngestDocumentWrapper.java
  server/src/main/java/org/opensearch/ingest/IngestService.java
  server/src/main/java/org/opensearch/ingest/Processor.java
  server/src/main/java/org/opensearch/ingest/SystemIngestPipelineCache.java
  server/src/test/java/org/opensearch/action/bulk/BulkRequestModifierTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIndicesThatCannotBeCreatedTests.java
  server/src/test/java/org/opensearch/action/bulk/TransportBulkActionIngestTests.java
  server/src/test/java/org/opensearch/action/update/UpdateRequestTests.java
  server/src/test/java/org/opensearch/ingest/IngestDocumentPreparer.java
  server/src/test/java/org/opensearch/ingest/IngestDocumentWrapperTests.java
  server/src/test/java/org/opensearch/ingest/IngestServiceTests.java
Labels: enhancement, Indexing

#18493 [Flaky Tests] Fixing flaky tests related to derived source tests
  server/src/internalClusterTest/java/org/opensearch/recovery/FullRollingRestartIT.java
  server/src/internalClusterTest/java/org/opensearch/recovery/RecoveryWhileUnderLoadIT.java
  server/src/test/java/org/opensearch/common/lucene/index/DerivedSourceLeafReaderTests.java
  server/src/test/java/org/opensearch/index/engine/InternalEngineTests.java
Labels: bug, skip-changelog, Build

#18497 Revert "Switch percentiles implementation to MergingDigest (#18124)"
  gradle/libs.versions.toml
  server/src/main/java/org/opensearch/search/aggregations/metrics/InternalMedianAbsoluteDeviation.java
  server/src/main/java/org/opensearch/search/aggregations/metrics/TDigestState.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/InternalTDigestPercentilesRanksTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/InternalTDigestPercentilesTests.java
  server/src/test/java/org/opensearch/search/aggregations/metrics/TDigestPercentilesAggregatorTests.java
Labels: >test-failure, flaky-test, autocut

#18085 Update bundled JDK to JDK-24
  DEVELOPER_GUIDE.md
  gradle/libs.versions.toml
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/Agent.java
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/SubjectInterceptor.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/SubjectTests.java
  plugins/repository-hdfs/build.gradle
  server/src/main/resources/org/opensearch/bootstrap/security.policy
Labels: enhancement, Build Libraries & Interfaces, skip-changelog, v3.2.0

#18506 Document GRPC settings and default values in README
  plugins/transport-grpc/README.md
Labels: skip-changelog

#18547 Forward port 3.1 release notes
  CHANGELOG.md
  release-notes/opensearch-release-notes-3.1.0.md
Labels: documentation, skip-changelog

#18467 Initialize FileCache for warm index on node boot-up/restart
  server/src/internalClusterTest/java/org/opensearch/indices/replication/WarmIndexSegmentReplicationIT.java
  server/src/internalClusterTest/java/org/opensearch/remotestore/WritableWarmIT.java
  server/src/main/java/org/opensearch/common/cache/RemovalReason.java
  server/src/main/java/org/opensearch/env/NodeEnvironment.java
  server/src/main/java/org/opensearch/env/NodeRepurposeCommand.java
  server/src/main/java/org/opensearch/index/store/CompositeDirectory.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/AggregateFileCacheStats.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCache.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheCleaner.java
  server/src/main/java/org/opensearch/index/store/remote/filecache/FileCacheFactory.java
  server/src/main/java/org/opensearch/index/store/remote/utils/FileTypeUtils.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/LRUCache.java
  server/src/main/java/org/opensearch/index/store/remote/utils/cache/SegmentedCache.java
  server/src/main/java/org/opensearch/node/Node.java
  server/src/test/java/org/opensearch/index/store/CompositeDirectoryTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheCleanerTests.java
  server/src/test/java/org/opensearch/index/store/remote/filecache/FileCacheTests.java
  test/framework/src/main/java/org/opensearch/test/InternalTestCluster.java
Labels: bug, skip-changelog, Storage:Remote, disabled-test

#18548 [ref #18085] Allow READ access to `/sys/fs/cgroup/memory.swap.current`
  server/src/main/resources/org/opensearch/bootstrap/security.policy
Labels: skip-changelog

#18552 [Backport 3.1] Add release notes for 3.1
  CHANGELOG.md
  release-notes/opensearch.release-notes-3.1.0.md
Labels: skip-changelog

#18544 Bump version on main branch to 3.2
  .ci/bwcVersions
  buildSrc/version.properties
  gradle/libs.versions.toml
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog

#18572 Introduce SecureHttpTransportParameters experimental API (to complement SecureTransportParameters counterpart)
  CHANGELOG.md
  server/src/main/java/org/opensearch/plugins/DefaultSecureHttpTransportParameters.java
  server/src/main/java/org/opensearch/plugins/SecureHttpTransportSettingsProvider.java
  server/src/main/java/org/opensearch/plugins/SecureTransportSettingsProvider.java
Labels: bug, v3.2.0

#18573 Bump Apache Lucene to 10.2.2
  CHANGELOG.md
  gradle/libs.versions.toml
  libs/core/licenses/lucene-core-10.2.1.jar.sha1
  libs/core/licenses/lucene-core-10.2.2.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-10.2.1.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-10.2.2.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-10.2.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-10.2.2.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-10.2.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-10.2.2.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-10.2.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-10.2.2.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-10.2.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-10.2.2.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-10.2.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-10.2.2.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-10.2.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-10.2.2.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-10.2.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-10.2.2.jar.sha1
  server/licenses/lucene-analysis-common-10.2.1.jar.sha1
  server/licenses/lucene-analysis-common-10.2.2.jar.sha1
  server/licenses/lucene-backward-codecs-10.2.1.jar.sha1
  server/licenses/lucene-backward-codecs-10.2.2.jar.sha1
  server/licenses/lucene-core-10.2.1.jar.sha1
  server/licenses/lucene-core-10.2.2.jar.sha1
  server/licenses/lucene-grouping-10.2.1.jar.sha1
  server/licenses/lucene-grouping-10.2.2.jar.sha1
  server/licenses/lucene-highlighter-10.2.1.jar.sha1
  server/licenses/lucene-highlighter-10.2.2.jar.sha1
  server/licenses/lucene-join-10.2.1.jar.sha1
  server/licenses/lucene-join-10.2.2.jar.sha1
  server/licenses/lucene-memory-10.2.1.jar.sha1
  server/licenses/lucene-memory-10.2.2.jar.sha1
  server/licenses/lucene-misc-10.2.1.jar.sha1
  server/licenses/lucene-misc-10.2.2.jar.sha1
  server/licenses/lucene-queries-10.2.1.jar.sha1
  server/licenses/lucene-queries-10.2.2.jar.sha1
  server/licenses/lucene-queryparser-10.2.1.jar.sha1
  server/licenses/lucene-queryparser-10.2.2.jar.sha1
  server/licenses/lucene-sandbox-10.2.1.jar.sha1
  server/licenses/lucene-sandbox-10.2.2.jar.sha1
  server/licenses/lucene-spatial-extras-10.2.1.jar.sha1
  server/licenses/lucene-spatial-extras-10.2.2.jar.sha1
  server/licenses/lucene-spatial3d-10.2.1.jar.sha1
  server/licenses/lucene-spatial3d-10.2.2.jar.sha1
  server/licenses/lucene-suggest-10.2.1.jar.sha1
  server/licenses/lucene-suggest-10.2.2.jar.sha1
  test/framework/licenses/lucene-codecs-10.2.1.jar.sha1
  test/framework/licenses/lucene-codecs-10.2.2.jar.sha1
  test/framework/licenses/lucene-test-framework-10.2.1.jar.sha1
  test/framework/licenses/lucene-test-framework-10.2.2.jar.sha1
Labels: dependencies

#18575 Fix flaky ReactorNetty4StreamingStressIT
  plugins/transport-reactor-netty4/src/javaRestTest/java/org/opensearch/rest/ReactorNetty4StreamingStressIT.java
Labels: >test-failure, flaky-test, autocut, skip-changelog

#18574 Bump Apache Lucene to 9.12.2
  CHANGELOG.md
  gradle/libs.versions.toml
  libs/core/licenses/lucene-core-9.12.1.jar.sha1
  libs/core/licenses/lucene-core-9.12.2.jar.sha1
  libs/core/src/main/java/org/opensearch/Version.java
  modules/lang-expression/licenses/lucene-expressions-9.12.1.jar.sha1
  modules/lang-expression/licenses/lucene-expressions-9.12.2.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.12.1.jar.sha1
  plugins/analysis-icu/licenses/lucene-analysis-icu-9.12.2.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.12.1.jar.sha1
  plugins/analysis-kuromoji/licenses/lucene-analysis-kuromoji-9.12.2.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.12.1.jar.sha1
  plugins/analysis-nori/licenses/lucene-analysis-nori-9.12.2.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.12.1.jar.sha1
  plugins/analysis-phonetic/licenses/lucene-analysis-phonetic-9.12.2.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.12.1.jar.sha1
  plugins/analysis-smartcn/licenses/lucene-analysis-smartcn-9.12.2.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.12.1.jar.sha1
  plugins/analysis-stempel/licenses/lucene-analysis-stempel-9.12.2.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.12.1.jar.sha1
  plugins/analysis-ukrainian/licenses/lucene-analysis-morfologik-9.12.2.jar.sha1
  server/licenses/lucene-analysis-common-9.12.1.jar.sha1
  server/licenses/lucene-analysis-common-9.12.2.jar.sha1
  server/licenses/lucene-backward-codecs-9.12.1.jar.sha1
  server/licenses/lucene-backward-codecs-9.12.2.jar.sha1
  server/licenses/lucene-core-9.12.1.jar.sha1
  server/licenses/lucene-core-9.12.2.jar.sha1
  server/licenses/lucene-grouping-9.12.1.jar.sha1
  server/licenses/lucene-grouping-9.12.2.jar.sha1
  server/licenses/lucene-highlighter-9.12.1.jar.sha1
  server/licenses/lucene-highlighter-9.12.2.jar.sha1
  server/licenses/lucene-join-9.12.1.jar.sha1
  server/licenses/lucene-join-9.12.2.jar.sha1
  server/licenses/lucene-memory-9.12.1.jar.sha1
  server/licenses/lucene-memory-9.12.2.jar.sha1
  server/licenses/lucene-misc-9.12.1.jar.sha1
  server/licenses/lucene-misc-9.12.2.jar.sha1
  server/licenses/lucene-queries-9.12.1.jar.sha1
  server/licenses/lucene-queries-9.12.2.jar.sha1
  server/licenses/lucene-queryparser-9.12.1.jar.sha1
  server/licenses/lucene-queryparser-9.12.2.jar.sha1
  server/licenses/lucene-sandbox-9.12.1.jar.sha1
  server/licenses/lucene-sandbox-9.12.2.jar.sha1
  server/licenses/lucene-spatial-extras-9.12.1.jar.sha1
  server/licenses/lucene-spatial-extras-9.12.2.jar.sha1
  server/licenses/lucene-spatial3d-9.12.1.jar.sha1
  server/licenses/lucene-spatial3d-9.12.2.jar.sha1
  server/licenses/lucene-suggest-9.12.1.jar.sha1
  server/licenses/lucene-suggest-9.12.2.jar.sha1
Labels: dependencies

#18580 Bump 2.19.3 to Apache Lucene 9.12.2
  libs/core/src/main/java/org/opensearch/Version.java
Labels: skip-changelog, backport 3.1

#18480 Add NodeResourceUsageStats to ClusterInfo
  CHANGELOG.md
  server/src/internalClusterTest/java/org/opensearch/cluster/ClusterInfoServiceIT.java
  server/src/main/java/org/opensearch/cluster/ClusterInfo.java
  server/src/main/java/org/opensearch/cluster/InternalClusterInfoService.java
  server/src/main/java/org/opensearch/node/IoUsageStats.java
  server/src/main/java/org/opensearch/node/NodeResourceUsageStats.java
  server/src/main/java/org/opensearch/node/NodesResourceUsageStats.java
  server/src/test/java/org/opensearch/cluster/ClusterInfoTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/DiskThresholdMonitorTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/IndexShardConstraintDeciderOverlapTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/RemoteShardsBalancerBaseTestCase.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderTests.java
  server/src/test/java/org/opensearch/cluster/routing/allocation/decider/DiskThresholdDeciderUnitTests.java
  server/src/test/java/org/opensearch/indices/tiering/TieringRequestValidatorTests.java
  server/src/test/java/org/opensearch/snapshots/SnapshotResiliencyTests.java
  test/framework/src/main/java/org/opensearch/cluster/MockInternalClusterInfoService.java
Labels: Meta

#18346 Create equivalents of JSM's AccessController in the java agent
  CHANGELOG.md
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/AccessController.java
  libs/agent-sm/agent-policy/src/main/java/org/opensearch/secure_sm/package-info.java
  libs/agent-sm/agent/build.gradle
  libs/agent-sm/agent/src/main/java/org/opensearch/javaagent/StackCallerProtectionDomainChainExtractor.java
  libs/agent-sm/agent/src/test/java/org/opensearch/javaagent/StackCallerProtectionDomainExtractorTests.java
  modules/ingest-geoip/src/main/java/org/opensearch/ingest/geoip/GeoIpProcessor.java
Labels: enhancement, Plugins

#18564 Add support for search pipeline in search and msearch template
  CHANGELOG.md
  client/rest-high-level/src/test/java/org/opensearch/client/RequestConvertersTests.java
  modules/lang-mustache/src/internalClusterTest/java/org/opensearch/script/mustache/SearchTemplateIT.java
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/RestMultiSearchTemplateAction.java
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/RestSearchTemplateAction.java
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/SearchTemplateRequest.java
  modules/lang-mustache/src/main/java/org/opensearch/script/mustache/SearchTemplateRequestBuilder.java
  modules/lang-mustache/src/test/java/org/opensearch/script/mustache/MultiSearchTemplateRequestTests.java
  modules/lang-mustache/src/test/java/org/opensearch/script/mustache/SearchTemplateRequestXContentTests.java
  modules/lang-mustache/src/test/resources/org/opensearch/script/mustache/simple-msearch-template.json
  server/src/main/java/org/opensearch/action/search/MultiSearchRequest.java
Labels: enhancement, discuss, Search:Query Capabilities

#18591 [Pull-based Ingestion] Create ingestion-fs plugin for simpler local testing
  CHANGELOG.md
  plugins/ingestion-fs/README.md
  plugins/ingestion-fs/build.gradle
  plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FileConsumerFactory.java
  plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FileMessage.java
  plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FileOffset.java
  plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FilePartitionConsumer.java
  plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FilePlugin.java
  plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/FileSourceConfig.java
  plugins/ingestion-fs/src/main/java/org/opensearch/plugin/ingestion/fs/package-info.java
  plugins/ingestion-fs/src/test/java/org/opensearch/plugin/ingestion/fs/FileBasedIngestionSingleNodeTests.java
  plugins/ingestion-fs/src/test/java/org/opensearch/plugin/ingestion/fs/FileMessageTests.java
  plugins/ingestion-fs/src/test/java/org/opensearch/plugin/ingestion/fs/FileOffsetTests.java
Labels: enhancement, Indexing

#18604 Fix the version increment workflow with the branching strategy update
  .github/workflows/version.yml
Labels: skip-changelog

#18614 Fix serialization failure due to wrong version
  server/src/main/java/org/opensearch/cluster/ClusterInfo.java
Labels: >test-failure, flaky-test, autocut, skip-changelog, Indexing

#18623 Fix flaky test in IngestServiceTests
  server/src/main/java/org/opensearch/ingest/IngestService.java
Labels: skip-changelog

#18599 [BUG] Cannot communicate with http2 when reactor-netty is enabled
  CHANGELOG.md
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransport.java
  plugins/transport-reactor-netty4/src/main/java/org/opensearch/http/reactor/netty4/ssl/SslUtils.java
  plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorHttpClient.java
  plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ReactorNetty4HttpServerTransportTests.java
  plugins/transport-reactor-netty4/src/test/java/org/opensearch/http/reactor/netty4/ssl/SecureReactorNetty4HttpServerTransportTests.java
Labels: bug, skip-changelog, Other, v3.2.0

#18632 Remove exclusions from breaking changes check (post 3.1.0 release)
  server/build.gradle
  server/src/main/java/org/opensearch/cluster/ClusterInfo.java
  server/src/main/java/org/opensearch/index/IndexService.java
  server/src/main/java/org/opensearch/indices/IndicesService.java
Labels: skip-changelog

#18215 Fix regex query to work with field alias
  CHANGELOG.md
  rest-api-spec/src/main/resources/rest-api-spec/test/search/61_query_string_field_alias.yml
  server/src/main/java/org/opensearch/index/search/QueryStringQueryParser.java
  server/src/test/java/org/opensearch/index/query/QueryStringQueryBuilderTests.java
Labels: bug, Search, lucene

#18629 Add workflow to automatically trigger manifest generation process
  .github/workflows/trigger-manifest-generation.yml
Labels: skip-changelog, backport 2.19

#18616 Provide aux transport to SecureAuxTransportSettingsProvider
  CHANGELOG.md
  plugins/transport-grpc/src/main/java/org/opensearch/plugin/transport/grpc/ssl/SecureNetty4GrpcServerTransport.java
  plugins/transport-grpc/src/test/java/org/opensearch/plugin/transport/grpc/ssl/SecureSettingsHelpers.java
  server/src/main/java/org/opensearch/plugins/SecureAuxTransportSettingsProvider.java
Labels: v3.2.0
